import { createHash } from 'node:crypto';
import type { Database, PgTransaction } from '../api/database.ts';
import type { Engine } from '../api/engine.ts';
import { assert, DomainError, type Actor, type Data, type Entity } from '../../packages/domain/core.ts';
import { whatsAppPolicy, isQuietHour } from '../../packages/domain/communications.ts';
import { DeepSeekAdapter, WhatsAppCloudAdapter, type WhatsAppInbound, type WhatsAppOutput, type SupportedLanguage } from '../../packages/integrations/index.ts';

export interface OutboxJob {id:string;company_id:string;type:string;data:Data;attempts:number;leased_until:string|Date;lease_token?:string;}
export interface SqlRunner {query:(statement:string,params?:unknown[])=>Promise<{rows:any[]}>;}
export interface WorkerOptions {companyId:string;appMode:string;batchSize?:number;leaseMs?:number;maxAttempts?:number;now?:()=>Date;ai?:DeepSeekAdapter;whatsapp?:WhatsAppCloudAdapter;testRecipients?:string[];publicOrigin?:string;}
const key=(...values:string[])=>createHash('sha256').update(values.join('\u0000')).digest('hex');
const at=(value:string|Date)=>new Date(value).toISOString();
export const serviceId='knaba-integration-service';
const servicePermissions=['integration.process','automation.execute','chat.read','chat.write','translation.use','notifications.manage','report.create','scope.company'];
export class DeferredJob extends Error {constructor(public availableAt:string){super('NOT_DUE');}}
export function retryDelayMs(attempt:number){return Math.min(3600000,1000*2**Math.min(12,Math.max(0,attempt)));}
export function retryable(error:unknown){return !(error instanceof DomainError)||error.code==='PROVIDER_UNAVAILABLE'&&error.details.retryable!==false;}
export async function leaseOutbox(db:SqlRunner,limit=10,leaseMs=120000,companyId?:string):Promise<OutboxJob[]> {
  assert(Number.isInteger(limit)&&limit>=1&&limit<=100&&leaseMs>=10000&&leaseMs<=600000,'VALIDATION_ERROR');
  const result=await db.query(`WITH picked AS (
    SELECT id FROM outbox WHERE ($3::text IS NULL OR company_id=$3) AND ((status IN ('PENDING','RETRY_SCHEDULED') AND available_at<=now()) OR (status='RUNNING' AND leased_until<now()))
    ORDER BY available_at,created_at,id FOR UPDATE SKIP LOCKED LIMIT $1
  ) UPDATE outbox o SET status='RUNNING',attempts=o.attempts+1,lease_token=gen_random_uuid()::text,leased_until=clock_timestamp()+($2::int*interval '1 millisecond')
    FROM picked WHERE o.id=picked.id RETURNING o.*`,[limit,leaseMs,companyId??null]);
  return result.rows;
}
export async function finishOutbox(db:SqlRunner,job:OutboxJob,status:'SUCCEEDED'|'FAILED'|'CANCELLED'|'RETRY_SCHEDULED',error?:string,availableAt?:string) {
  const result=await db.query(`UPDATE outbox SET status=$1,last_error=$2,attempts=CASE WHEN $2='NOT_DUE' THEN GREATEST(attempts-1,0) ELSE attempts END,available_at=COALESCE($3::timestamptz,available_at),finished_at=CASE WHEN $1 IN ('SUCCEEDED','FAILED','CANCELLED') THEN now() ELSE NULL END,leased_until=NULL
    WHERE id=$4 AND status='RUNNING' AND lease_token=$5 AND leased_until>clock_timestamp() RETURNING id`,[status,error??null,availableAt??null,job.id,job.lease_token??null]);
  return result.rows.length===1;
}
export function automationMatches(rule:Data,event:{type:string;data:Data},now:string){return rule.status==='ACTIVE'&&Boolean(rule.approvedBy)&&Date.parse(rule.activeFrom)<=Date.parse(now)&&rule.trigger===event.type&&Object.entries(rule.filters??{}).every(([k,v])=>event.data[k]===v)&&(!(rule.scope?.siteIds?.length)||rule.scope.siteIds.includes(event.data.siteId))&&(!(rule.scope?.customerIds?.length)||rule.scope.customerIds.includes(event.data.customerId));}
export function berlinParts(date:Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(parts.map(p=>[p.type,p.value])) as Record<string,string>;}
/** Only the small explicit schedule contract is executable; other cron text remains a typed configuration error. */
export function scheduleDue(cron:string,now:Date){const p=berlinParts(now);const fields=cron.trim().split(/\s+/);assert(fields.length===5&&fields[2]==='*'&&fields[3]==='*'&&(fields[4]==='*'||/^\d$/.test(fields[4])),'AUTOMATION_SCHEDULE_UNSUPPORTED');assert(/^\d{1,2}$/.test(fields[0]!)&&/^\d{1,2}$/.test(fields[1]!)&&Number(fields[0])<=59&&Number(fields[1])<=23,'AUTOMATION_SCHEDULE_UNSUPPORTED');const weekday=Number(new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Berlin',weekday:'short'}).format(now).replace(/Sun|Mon|Tue|Wed|Thu|Fri|Sat/g,m=>String(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(m))));return Number(p.hour)===Number(fields[1])&&Number(p.minute)===Number(fields[0])&&(fields[4]==='*'||Number(fields[4])===weekday);}

export class WorkerRunner {
  private stopping=false;private running=false;private lastScheduleMinute='';
  readonly now:()=>Date;
  constructor(public db:Database,public engine:Engine,public options:WorkerOptions){this.now=options.now??(()=>new Date());}
  async initialize(){await this.db.query('SELECT knaba_assert_gps_storage_safe()');await this.db.transaction(this.options.companyId,'WORKER_BOOT',async tx=>{const users=await tx.list('user');const user=users.find(u=>u.id===serviceId);if(!user)await tx.add('user',{name:'KNABA DE integration worker',roles:['SERVICE_ACCOUNT'],permissions:servicePermissions,active:true,siteIds:[],customerIds:[],warehouseIds:[],credentialDisabled:true},serviceId);else assert(user.data.roles.includes('SERVICE_ACCOUNT')&&user.data.active!==false,'ACCESS_DENIED');});}
  async actor(companyId:string){return this.engine.getActor(serviceId,companyId);}
  async command(job:OutboxJob,name:string,input:Data,suffix=name,actor?:Actor){return this.engine.execute(actor??await this.actor(job.company_id),name,{input,idempotency_key:key('worker',job.id,suffix)});}
  private async entity(job:OutboxJob,kind:string,id:string){return this.db.transaction(job.company_id,serviceId,tx=>tx.get(kind,id));}
  private async record(job:OutboxJob,kind:string,id:string,update:(entity:Entity,tx:PgTransaction)=>Promise<Data>|Data){return this.db.transaction(job.company_id,serviceId,async tx=>{const entity=await tx.get(kind,id);return tx.save(entity,await update(entity,tx));});}
  async tick(){if(this.running||this.stopping)return {processed:0};this.running=true;let processed=0;try{await this.db.query('SELECT knaba_purge_gps($1::timestamptz,500,$2::text) AS purged',[this.now().toISOString(),this.options.companyId]);await this.scheduled();const jobs=await leaseOutbox(this.db,this.options.batchSize??5,this.options.leaseMs??120000,this.options.companyId);await Promise.all(jobs.map(async job=>{if(this.stopping)return;await this.process(job);processed++;}));return {processed};}finally{this.running=false;}}
  stop(){this.stopping=true;}
  async process(job:OutboxJob){let leaseLost=false;let renewing:Promise<void>|undefined;const leaseMs=this.options.leaseMs??120000;
    const heartbeat=setInterval(()=>{if(renewing)return;renewing=this.db.query(`UPDATE outbox SET leased_until=clock_timestamp()+($1::int*interval '1 millisecond') WHERE id=$2 AND status='RUNNING' AND lease_token=$3 AND leased_until>clock_timestamp() RETURNING leased_until`,[leaseMs,job.id,job.lease_token??null]).then(r=>{if(r.rows[0])job.leased_until=r.rows[0].leased_until;else leaseLost=true;}).catch(()=>{leaseLost=true;}).finally(()=>{renewing=undefined;});},Math.floor(leaseMs/3));heartbeat.unref();
    const finish=async(status:'SUCCEEDED'|'FAILED'|'CANCELLED'|'RETRY_SCHEDULED',error?:string,availableAt?:string)=>{clearInterval(heartbeat);await renewing;if(!leaseLost)await finishOutbox(this.db,job,status,error,availableAt);};
    try{if(job.data.not_before&&Date.parse(job.data.not_before)>this.now().getTime())throw new DeferredJob(job.data.not_before);assert(job.attempts<=(this.options.maxAttempts??5),'RETRY_LIMIT_EXHAUSTED');await this.handle(job);await this.applyRules(job);await finish('SUCCEEDED');}
    catch(error){if(error instanceof DeferredJob)await finish('RETRY_SCHEDULED','NOT_DUE',error.availableAt);else {const code=error instanceof DomainError?error.code:'WORKER_ERROR';const retry=job.attempts<(this.options.maxAttempts??5)&&retryable(error);await finish(retry?'RETRY_SCHEDULED':'FAILED',code,retry?new Date(this.now().getTime()+retryDelayMs(job.attempts)).toISOString():undefined);}}finally{clearInterval(heartbeat);}}
  async handle(job:OutboxJob){switch(job.type){
    case 'whatsapp.inbound':case 'whatsapp.webhook_received':return this.inbound(job);
    case 'translation.requested':return this.translation(job);
    case 'translation.ready':return this.translationReady(job);
    case 'message.created':case 'message.corrected':return this.messageCreated(job);
    case 'delivery.requested':return this.delivery(job);
    case 'notification.scheduled':return this.notification(job);
    case 'assistant.answer_requested':return this.answer(job);
    case 'automation.action_requested':return this.automationAction(job);
    case 'report.daily_requested':return this.command(job,'report.daily_draft',{siteId:job.data.siteId,orderId:job.data.orderId,day:job.data.day});
    default:return;
  }}
  private async currentlyReadable(tx:PgTransaction,userId:string,message:Entity){try{const actor=await this.engine.actorIn(tx,userId);return actor.permissions.includes('chat.read')&&await this.engine.visible(tx,actor,message);}catch{return false;}}
  private async translation(job:OutboxJob){const t=await this.entity(job,'translation',job.data.translation_id);if(t.data.status!=='PENDING')return;const allowed=await this.db.transaction(job.company_id,serviceId,async tx=>{const message=await tx.get('message',t.data.message_id);if(message.data.message_version!==t.data.message_version||message.data.deleted_at)return false;for(const request of await tx.list('translation_request'))if(request.data.translation_id===t.id&&request.data.status!=='CANCELLED'&&await this.currentlyReadable(tx,request.data.user_id,message))return true;return false;});if(!allowed){await this.record(job,'translation',t.id,e=>({...e.data,status:'CANCELLED',error:'ACCESS_REVOKED',completed_at:this.now().toISOString()}));return;}
    const config=await this.db.transaction(job.company_id,serviceId,async tx=>(await tx.list('assistant_config')).find(c=>c.data.status==='ACTIVE'&&c.data.provider==='DEEPSEEK'));
    if(!this.options.ai||!config)return this.command(job,'translation.result',{translation_id:t.id,status:'FAILED',provider:t.data.provider,model:t.data.model,error:'PROVIDER_DISABLED'});
    try{const budget=await this.reserveBudget(job,config,t.data.source_text);const result=await this.options.ai.translate({text:t.data.source_text,sourceLanguage:t.data.source_language,targetLanguage:t.data.target_language,glossary:t.data.glossary,canonicalFacts:t.data.canonical_facts,synthetic:['DEMO','TEST'].includes(this.options.appMode)&&config.data.testOnly===true,budgetRemainingCents:budget});await this.command(job,'translation.result',{translation_id:t.id,status:'SUCCEEDED',text:result.text,provider:result.provider,model:result.model,usage:result.usage});await this.settleBudget(job,result.usage?.cost_cents);}
    catch(error){return this.command(job,'translation.result',{translation_id:t.id,status:'FAILED',provider:t.data.provider,model:t.data.model,error:error instanceof DomainError?error.code:'PROVIDER_UNAVAILABLE'});}}
  private async translationReady(job:OutboxJob){await this.db.transaction(job.company_id,serviceId,async tx=>{const translation=await tx.get('translation',job.data.translation_id),request=await tx.get('translation_request',job.data.request_id),message=await tx.get('message',job.data.message_id);if(request.data.status==='CANCELLED')return;if(translation.data.status!=='SUCCEEDED'||message.data.message_version!==translation.data.message_version||!await this.currentlyReadable(tx,job.data.recipient_id,message)){await tx.save(request,{...request.data,status:'CANCELLED'});return;}const id=key('translated-copy',job.id);if((await tx.list('notification')).some(n=>n.id===id))return;await tx.add('notification',{recipient_id:job.data.recipient_id,event:'TRANSLATION_READY',category:'CHAT',channel:'WEB',status:'SUCCEEDED',translation_id:translation.id,message_id:message.id,message_version:translation.data.message_version,machine_translation:true,language:translation.data.target_language,attempts:1,max_attempts:1},id);});}
  private async reserveBudget(job:OutboxJob,config:Entity,text:string){return this.db.transaction(job.company_id,serviceId,async tx=>{const current=await tx.get('assistant_config',config.id);assert(current.data.status==='ACTIVE'&&current.version===config.version,'VERSION_CONFLICT');const synthetic=['DEMO','TEST'].includes(this.options.appMode)&&current.data.testOnly===true;if(!synthetic){assert(current.data.transferApprovalId,'NEEDS_APPROVAL');const approval=await tx.get('legal_approval',current.data.transferApprovalId);assert(approval.data.status==='APPROVED'&&approval.data.subject==='AI_TRANSFER'&&approval.data.active!==false&&(!approval.data.expiresAt||Date.parse(approval.data.expiresAt)>this.now().getTime()),'NEEDS_APPROVAL');}const usage=await tx.list('ai_usage');const duplicate=usage.find(u=>u.data.event_id===job.id);assert(!duplicate,'PROVIDER_OUTCOME_UNKNOWN');const spent=usage.filter(u=>u.data.config_id===config.id).reduce((n,u)=>n+u.data.reserved_cents,0);const remaining=current.data.budgetCents-spent;const reserve=this.options.ai!.maximumCostCents(text)+this.options.ai!.maximumCostCents('x'.repeat(10000));assert(remaining>=reserve&&reserve>0,'AI_BUDGET_EXHAUSTED');await tx.add('ai_usage',{config_id:config.id,config_version:config.version,event_id:job.id,reserved_cents:reserve,status:'RUNNING',started_at:this.now().toISOString()});return reserve;});}
  private async settleBudget(job:OutboxJob,actual?:number){await this.db.transaction(job.company_id,serviceId,async tx=>{const usage=(await tx.list('ai_usage')).find(u=>u.data.event_id===job.id);if(usage)await tx.save(usage,{...usage.data,status:'SUCCEEDED',actual_cents:actual??null,reserved_cents:actual??usage.data.reserved_cents,completed_at:this.now().toISOString()});});}
  private async messageCreated(job:OutboxJob){const message=await this.entity(job,'message',job.data.message_id);if(message.data.deleted_at||message.data.message_version!==job.data.version)return;const channel=await this.entity(job,'channel',message.data.channel_id);for(const member of channel.data.members??[]){if(member.revoked_at||member.user_id===message.data.author_id||member.user_id===serviceId)continue;const recipient=await this.db.transaction(job.company_id,serviceId,async tx=>{if(!await this.currentlyReadable(tx,member.user_id,message))return;const actor=await this.engine.actorIn(tx,member.user_id);const preferences=(await tx.list('translation_preference')).filter(p=>p.data.user_id===member.user_id);const preference=preferences.find(p=>p.data.channel_id===channel.id)??preferences.find(p=>!p.data.channel_id);const settings=(await tx.list('notification_setting')).find(p=>p.data.user_id===member.user_id);return {actor,preference,settings};});if(!recipient)continue;
    await this.command(job,'delivery.prepare',{message_id:message.id,recipient_id:member.user_id,channel:'WEB'},`web:${member.user_id}`);
    if(recipient.settings?.data.whatsapp_consent===true&&!recipient.settings?.data.opted_out)await this.command(job,'delivery.prepare',{message_id:message.id,recipient_id:member.user_id,channel:'WHATSAPP'},`wa:${member.user_id}`);
    if(recipient.preference?.data.mode==='ORIGINAL_AND_AUTO'&&recipient.preference.data.target_language!==message.data.language&&recipient.actor.permissions.includes('translation.use'))await this.command(job,'translation.request',{message_id:message.id,target_language:recipient.preference.data.target_language},`translation:${member.user_id}`,recipient.actor);
  }}
  private async delivery(job:OutboxJob){const entity=await this.entity(job,'delivery',job.data.delivery_id);if(['API_ACCEPTED','SENT','DELIVERED','READ','FAILED','CANCELLED'].includes(entity.data.status))return;if(entity.data.status==='SENDING'){await this.command(job,'delivery.status',{delivery_id:entity.id,status:'FAILED',error:'PROVIDER_OUTCOME_UNKNOWN'});return;}
    const snapshot=await this.db.transaction(job.company_id,serviceId,async tx=>{const delivery=await tx.get('delivery',entity.id),message=await tx.get('message',delivery.data.message_id);if(message.data.message_version!==delivery.data.message_version||!await this.currentlyReadable(tx,delivery.data.recipient_id,message)){await tx.save(delivery,{...delivery.data,status:'CANCELLED',error:'ACCESS_REVOKED'});return;}
      const settings=(await tx.list('notification_setting')).find(s=>s.data.user_id===delivery.data.recipient_id);const template=delivery.data.approved_template?(await tx.list('whatsapp_template')).find(t=>t.data.name===delivery.data.approved_template&&t.data.status==='APPROVED'):undefined;
      const policy=delivery.data.channel==='WEB'?{allowed:true,channel:'WEB' as const}:whatsAppPolicy({now:this.now().toISOString(),last_inbound_at:settings?.data.last_inbound_at,consent:settings?.data.whatsapp_consent===true,opted_out:settings?.data.opted_out,approved_template:template?.data.name,template_status:template?.data.status});
      if(!policy.allowed){await tx.save(delivery,{...delivery.data,status:'FAILED',error:policy.reason});return;}
      if(delivery.data.channel==='WHATSAPP'&&isQuietHour(this.now().toISOString(),settings?.data.quiet_start??22,settings?.data.quiet_end??7))throw new DeferredJob(new Date(this.now().getTime()+3600000).toISOString());
      const identities=(await tx.list('contact_identity')).filter(c=>c.data.userId===delivery.data.recipient_id&&c.data.verified&&c.data.active!==false&&['WHATSAPP','PHONE'].includes(c.data.type));const phones=[...new Set(identities.map(c=>String(c.data.value).replace(/[^\d]/g,'')))];return {delivery,message,policy,phone:phones.length===1?phones[0]:undefined,language:settings?.data.language??'DE'};});
    if(!snapshot)return;if(snapshot.delivery.data.channel==='WEB'){await this.command(job,'delivery.status',{delivery_id:entity.id,status:'DELIVERED'});return;}
    if(!this.options.whatsapp||!snapshot.phone)return this.command(job,'delivery.status',{delivery_id:entity.id,status:'FAILED',error:!this.options.whatsapp?'PROVIDER_DISABLED':'RECIPIENT_UNVERIFIED'});
    if(this.options.appMode!=='PRODUCTION'&&!this.options.testRecipients?.includes(snapshot.phone))return this.command(job,'delivery.status',{delivery_id:entity.id,status:'FAILED',error:'TEST_RECIPIENT_NOT_ALLOWED'});
    await this.record(job,'delivery',entity.id,e=>({...e.data,status:'SENDING',attempts:e.data.attempts+1,sending_started_at:this.now().toISOString()}));
    const output:WhatsAppOutput=snapshot.policy.kind==='TEMPLATE'?{kind:'TEMPLATE',name:snapshot.policy.template!,language:snapshot.language.toLowerCase()==='uk'?'uk':snapshot.language.toLowerCase(),approved:true,parameters:[this.options.publicOrigin??'https://knaba.example.invalid']}:{kind:'TEXT',text:`${job.data.notice==='CORRECTION'?'Korrektur · ':''}${snapshot.message.data.text}`.slice(0,4096)};
    try{const result=await this.options.whatsapp.send(snapshot.phone,output,{kind:snapshot.policy.kind as 'TEXT'|'TEMPLATE',template:snapshot.policy.template});await this.command(job,'delivery.status',{delivery_id:entity.id,...result});}catch(error){await this.command(job,'delivery.status',{delivery_id:entity.id,status:'FAILED',error:error instanceof DomainError?error.code:'PROVIDER_OUTCOME_UNKNOWN'});}
  }
  private async notification(job:OutboxJob){const item=await this.command(job,'notifications.prepare',{notification_id:job.data.notification_id});if(!item?.id||item.data.status!=='RUNNING')return;const allowed=await this.db.transaction(job.company_id,serviceId,async tx=>{try{const actor=await this.engine.actorIn(tx,item.data.recipient_id);if(item.data.message_id&&!await this.currentlyReadable(tx,actor.userId,await tx.get('message',item.data.message_id)))return false;if(item.data.related_kind&&item.data.related_id&&!await this.engine.visible(tx,actor,await tx.get(item.data.related_kind,item.data.related_id)))return false;return true;}catch{return false;}});if(!allowed){await this.record(job,'notification',item.id,e=>({...e.data,status:'CANCELLED',reason:'ACCESS_REVOKED'}));return;}
    if(item.data.channel==='WEB')return this.command(job,'notifications.complete',{notification_id:item.id,succeeded:true});
    if(!item.data.message_id)return this.command(job,'notifications.complete',{notification_id:item.id,succeeded:false,error:'WHATSAPP_MESSAGE_REQUIRED'});
    const delivery=await this.command(job,'delivery.prepare',{message_id:item.data.message_id,recipient_id:item.data.recipient_id,channel:'WHATSAPP',approved_template:item.data.template,template_status:item.data.template_status},'notification-delivery');if(!delivery?.id)return this.command(job,'notifications.complete',{notification_id:item.id,succeeded:false,error:delivery.reason??'CHANNEL_POLICY'});
    await this.delivery({...job,data:{delivery_id:delivery.id}});const latest=await this.entity(job,'delivery',delivery.id);return this.command(job,'notifications.complete',{notification_id:item.id,succeeded:['API_ACCEPTED','SENT','DELIVERED','READ'].includes(latest.data.status),error:latest.data.error});
  }
  private async inbound(job:OutboxJob){const provider=job.data.provider??'WHATSAPP';const inbox=await this.db.query('SELECT payload FROM webhook_inbox WHERE provider=$1 AND event_id=$2 AND company_id=$3',[provider,job.data.event_id,job.company_id]);assert(inbox.rows.length===1,'NOT_FOUND_SAFE');const input=inbox.rows[0].payload as WhatsAppInbound;assert(input.kind==='MESSAGE'||input.kind==='STATUS','VALIDATION_ERROR');
    if(input.kind==='STATUS'){const matches=await this.db.transaction(job.company_id,serviceId,async tx=>(await tx.list('delivery')).filter(d=>d.data.provider_message_id===input.id));for(const d of matches)await this.command(job,'delivery.status',{delivery_id:d.id,status:input.status,provider_message_id:input.id,error:input.error_code?`META_${input.error_code}`:undefined},`status:${d.id}`);return;}
    const route=await this.db.transaction(job.company_id,serviceId,async tx=>{const old=(await tx.list('conversation_input')).find(i=>i.data.provider_event_id===input.id);if(old)return old;const identities=(await tx.list('contact_identity')).filter(i=>['PHONE','WHATSAPP'].includes(i.data.type)&&i.data.active!==false&&i.data.verified&&String(i.data.value).replace(/[^\d]/g,'')===input.sender);const userIds=[...new Set(identities.map(i=>i.data.userId))];assert(userIds.length<=1,'AMBIGUOUS_RECIPIENT');let userId=userIds[0];if(!userId){const user=await tx.add('user',{name:'WhatsApp guest',roles:['GUEST','CLIENT'],permissions:['chat.read','chat.write','lead.create','lead.manage','commerce.read','translation.use'],siteIds:[],customerIds:[],warehouseIds:[],active:true,guest:true});userId=user.id;await tx.add('contact_identity',{type:'WHATSAPP',value:input.sender,userId,verified:true,active:true,verificationSource:'SIGNED_META_CHANNEL',verifiedAt:this.now().toISOString(),customerVerified:false});}
      const actor=await this.engine.actorIn(tx,userId);let channel:Entity|undefined;let replyId:string|undefined;if(input.context_message_id){const copies=(await tx.list('delivery')).filter(d=>d.data.provider_message_id===input.context_message_id&&d.data.recipient_id===userId);if(copies.length===1){const original=await tx.get('message',copies[0]!.data.message_id);if(await this.currentlyReadable(tx,userId,original)){channel=await tx.get('channel',original.data.channel_id);replyId=original.id;}}}
      if(!channel)channel=(await tx.list('channel')).find(c=>c.data.created_by===userId&&c.data.type==='PRIVATE_CUSTOMER_ASSISTANT');if(!channel){const external=actor.roles.some(r=>['CLIENT','CUSTOMER','GUEST'].includes(r));channel=await tx.add('channel',{type:external?'PRIVATE_CUSTOMER_ASSISTANT':'DIRECT',name:external?'Private WhatsApp consultation':'Private operator inbox',created_by:userId,members:[{user_id:userId,joined_at:this.now().toISOString(),history_from:this.now().toISOString(),external},{user_id:serviceId,joined_at:this.now().toISOString(),history_from:this.now().toISOString(),external:false}],handoff:{state:'AI_ACTIVE',owner_id:null}});}
      const setting=(await tx.list('notification_setting')).find(s=>s.data.user_id===userId);const language=setting?.data.language??'DE';return tx.add('conversation_input',{provider_event_id:input.id,provider:'WHATSAPP',user_id:userId,channel_id:channel.id,received_at:input.received_at,input,language,reply_to_id:replyId,status:'PENDING'});});
    if(route.data.status!=='PENDING')return;const actor=await this.engine.getActor(route.data.user_id,job.company_id);await this.command(job,'notifications.inbound',{user_id:actor.userId,received_at:input.received_at},'inbound-window');
    if(input.action_id){try{const action=await this.command(job,'callback.consume',{action_id:input.action_id},'callback',actor);if(action.action==='ACK')await this.command(job,'message.ack',{message_id:action.message_id},'callback-ack',actor);if(action.action==='TRANSLATE')await this.command(job,'translation.request',{message_id:action.message_id,target_language:action.target_language},'callback-translate',actor);await this.record(job,'conversation_input',route.id,e=>({...e.data,status:'PROCESSED',action,completed_at:this.now().toISOString()}));return;}catch(error){await this.record(job,'conversation_input',route.id,e=>({...e.data,status:'REJECTED',error:error instanceof DomainError?error.code:'INVALID_CALLBACK',completed_at:this.now().toISOString()}));return;}}
    if(input.type==='location'||input.media||!input.text){await this.record(job,'conversation_input',route.id,e=>({...e.data,status:'MANUAL_REVIEW',reason:input.type==='location'?'ONE_TIME_LOCATION_NOT_GPS_TRACKING':'MEDIA_UPLOAD_REQUIRES_QUARANTINE',completed_at:this.now().toISOString()}));return;}
    const message=await this.command(job,'message.send',{channel_id:route.data.channel_id,text:input.text,language:route.data.language,reply_to_id:route.data.reply_to_id},'inbound-message',actor);await this.record(job,'conversation_input',route.id,async(e,tx)=>{const channel=await tx.get('channel',route.data.channel_id);const config=(await tx.list('assistant_config')).find(c=>c.data.status==='ACTIVE');if(channel.data.type==='PRIVATE_CUSTOMER_ASSISTANT'&&channel.data.handoff?.state==='AI_ACTIVE'&&config?.data.provider==='DEEPSEEK')await tx.event('assistant.answer_requested',{channelId:channel.id,messageId:message.id,actorId:actor.userId,configId:config.id,configVersion:config.data.configVersion,language:route.data.language});return {...e.data,status:'PROCESSED',message_id:message.id,router_state:channel.data.type==='PRIVATE_CUSTOMER_ASSISTANT'?'NEW_OR_EXISTING_CUSTOMER_MENU':'OPERATOR_INBOX',completed_at:this.now().toISOString()};});
  }
  private async answer(job:OutboxJob){const snapshot=await this.db.transaction(job.company_id,serviceId,async tx=>{const config=await tx.get('assistant_config',job.data.configId),channel=await tx.get('channel',job.data.channelId),message=await tx.get('message',job.data.messageId);if(config.data.status!=='ACTIVE'||config.data.configVersion!==job.data.configVersion||channel.data.handoff?.state!=='AI_ACTIVE'||!await this.currentlyReadable(tx,job.data.actorId,message))return;assert(['PRIVATE_CUSTOMER_ASSISTANT','SITE_CLIENT'].includes(channel.data.type),'ACCESS_DENIED');if(channel.data.lead_id){const lead=await tx.get('lead',channel.data.lead_id);if(lead.data.ownership!=='AI_ACTIVE')return;}
    const docs=await tx.list('knowledge');const sources=docs.filter(d=>config.data.knowledgeIds.includes(d.id)&&d.data.status==='APPROVED'&&Date.parse(d.data.validFrom??d.data.effective_at)<=this.now().getTime()&&(!d.data.validUntil||Date.parse(d.data.validUntil)>this.now().getTime())&&(d.data.visibility==='PUBLIC'||d.data.visibility==='PERSONAL'&&d.data.subjectUserId===job.data.actorId)).map(d=>({id:d.id,text:d.data.content??d.data.text}));const services=(await tx.list('service')).filter(s=>s.data.active&&s.data.approvedBy&&config.data.allowedServiceIds.includes(s.id)).map(s=>({id:s.id,text:`${s.data.name}: ${s.data.description}. ${s.data.included?.join('; ')??''}`}));return {config,channel,message,sources:[...sources,...services].slice(0,20)};});if(!snapshot)return;
    if(!this.options.ai||snapshot.config.data.provider!=='DEEPSEEK'){await this.fallback(job,'PROVIDER_DISABLED');return;}
    try{const budget=await this.reserveBudget(job,snapshot.config,snapshot.message.data.text+JSON.stringify(snapshot.sources));const response=await this.options.ai.answer({text:snapshot.message.data.text,language:job.data.language as SupportedLanguage,sources:snapshot.sources,ownership:'AI_ACTIVE',synthetic:['DEMO','TEST'].includes(this.options.appMode)&&snapshot.config.data.testOnly===true,budgetRemainingCents:budget,maxReplyChars:snapshot.config.data.maxResponseLength});if(response.handoff_required){await this.fallback(job,response.reason??'AI_HANDOFF_REQUIRED');await this.settleBudget(job,response.usage?.cost_cents);return;}
      await this.db.transaction(job.company_id,serviceId,async tx=>{const channel=await tx.get('channel',snapshot.channel.id),config=await tx.get('assistant_config',snapshot.config.id);assert(channel.data.handoff?.state==='AI_ACTIVE'&&config.data.status==='ACTIVE'&&config.version===snapshot.config.version,'AI_SUPPRESSED');assert(await this.currentlyReadable(tx,job.data.actorId,snapshot.message),'ACCESS_DENIED');if(!channel.data.members?.some((m:Data)=>m.user_id===serviceId&&!m.revoked_at))await tx.save(channel,{...channel.data,members:[...channel.data.members,{user_id:serviceId,joined_at:this.now().toISOString(),history_from:this.now().toISOString(),external:false}]});});
      await this.command(job,'message.send',{channel_id:snapshot.channel.id,text:`KI-Assistent · ${response.answer}`,language:job.data.language,source:'AI'},'ai-answer');await this.settleBudget(job,response.usage?.cost_cents);
    }catch(error){await this.fallback(job,error instanceof DomainError?error.code:'PROVIDER_UNAVAILABLE');}}
  private async fallback(job:OutboxJob,reason:string){await this.db.transaction(job.company_id,serviceId,async tx=>{const channel=await tx.get('channel',job.data.channelId);if(channel.data.handoff?.state==='HUMAN_ACTIVE')return;if(channel.data.handoff?.state==='AI_ACTIVE')await tx.save(channel,{...channel.data,handoff:{state:'HANDOFF_PENDING',owner_id:null,reason,requested_at:this.now().toISOString()}});const dedup=key('assistant-fallback',job.id);if(!(await tx.list('decision')).some(d=>d.data.dedupeKey===dedup))await tx.add('decision',{status:'OPEN',reason,ownerId:'UNASSIGNED',channelId:channel.id,sources:[job.data.messageId],actions:['APPROVE','RETURN','DELEGATE'],summaryDE:'Die private Kundenanfrage benötigt menschliche Unterstützung. Es wurde keine Zusage gemacht.',dedupeKey:dedup,history:[]});});}
  private async applyRules(job:OutboxJob){if(job.type.startsWith('automation.')||job.type.startsWith('assistant.')||job.type==='translation.requested')return;const now=this.now().toISOString();const rules=await this.db.transaction(job.company_id,serviceId,async tx=>(await tx.list('automation_rule')).filter(r=>automationMatches(r.data,job,now)));for(const rule of rules)await this.command(job,'automation_rule.run',{id:rule.id,event:{id:job.id,type:job.type,data:job.data}},`rule:${rule.id}`);}
  private async automationAction(job:OutboxJob){const run=await this.entity(job,'automation_run',job.data.runId);if(['COMPLETED','SUCCEEDED','CANCELLED'].includes(run.data.status))return;const rule=await this.entity(job,'automation_rule',run.data.ruleId);assert(rule.data.status==='ACTIVE'&&rule.data.approvedBy&&run.data.ruleVersion===rule.data.ruleVersion,'NEEDS_APPROVAL');const actor=await this.engine.getActor(rule.data.ownerId,job.company_id);const parameters=run.data.parameters;let result:unknown;
    try{switch(run.data.action){
      case 'DRAFT_REPORT':{const sites=rule.data.scope.siteIds;assert(sites.length>0,'VALIDATION_ERROR');const orders=await this.db.transaction(job.company_id,serviceId,async tx=>(await tx.list('order')).filter(o=>sites.includes(o.data.siteId)&&(!rule.data.scope.customerIds.length||rule.data.scope.customerIds.includes(o.data.customerId))&&!['CANCELLED','CLOSED'].includes(o.data.status)));const day=parameters.day??this.localDay();const drafts=[];for(const order of orders)drafts.push(await this.command(job,'report.daily_draft',{siteId:order.data.siteId,orderId:order.id,day},`draft:${order.id}`,actor));result=drafts;break;}
      case 'DRAFT_QUOTE':{const input=parameters.input??parameters;const lead=await this.entity(job,'lead',input.leadId);assert(!rule.data.scope.customerIds.length||rule.data.scope.customerIds.includes(lead.data.customerId),'ACCESS_DENIED');result=await this.command(job,'quote.create',input,'draft-quote',actor);break;}
      case 'REMIND':{const input={...parameters,scheduled_at:parameters.scheduled_at??this.now().toISOString(),dedup_key:`automation:${run.id}`,max_attempts:Math.min(3,rule.data.maxAttempts)};if(input.related_id&&input.related_kind){const related=await this.entity(job,input.related_kind,input.related_id);const sid=related.data.siteId??related.data.site_id;assert(!rule.data.scope.siteIds.length||rule.data.scope.siteIds.includes(sid),'ACCESS_DENIED');}result=await this.command(job,'notifications.schedule',input,'remind',actor);break;}
      case 'PROPOSE_CREW':result=await this.command(job,'dispatch.recommend',parameters.input??parameters,'propose-crew',actor);break;
      case 'DETECT_SHORTAGE':{const data=await this.db.transaction(job.company_id,serviceId,async tx=>{const requests=(await tx.list('material_request')).filter(r=>(!rule.data.scope.siteIds.length||rule.data.scope.siteIds.includes(r.data.siteId))&&r.data.approvedBase>r.data.receivedBase&&['APPROVED','PARTIALLY_APPROVED','PARTIALLY_RESERVED'].includes(r.data.state));return requests.map(r=>({requestId:r.id,siteId:r.data.siteId,materialId:r.data.materialId,unreceivedBase:r.data.approvedBase-r.data.receivedBase}));});result=data;break;}
      default:throw new DomainError('AUTOMATION_ACTION_UNSUPPORTED');}
      await this.record(job,'automation_run',run.id,e=>({...e.data,status:'SUCCEEDED',attempts:e.data.attempts+1,result,completedAt:this.now().toISOString()}));
    }catch(error){await this.record(job,'automation_run',run.id,e=>({...e.data,status:'FAILED',attempts:e.data.attempts+1,error:error instanceof DomainError?error.code:'WORKER_ERROR',completedAt:this.now().toISOString()}));throw error;}}
  private localDay(){const p=berlinParts(this.now());return `${p.year}-${p.month}-${p.day}`;}
  async scheduled(){const now=this.now(),p=berlinParts(now),minute=`${this.localDay()}:${p.hour}:${p.minute}`;if(minute===this.lastScheduleMinute)return;await this.db.transaction(this.options.companyId,serviceId,async tx=>{const day=this.localDay();if(Number(p.hour)>=18){for(const order of await tx.list('order'))if(order.data.siteId&&order.data.customerId&&!['CANCELLED','CLOSED'].includes(order.data.status)){const id=key('daily-report',tx.companyId,order.id,day);await tx.query(`INSERT INTO outbox(id,company_id,type,data) VALUES($1,$2,'report.daily_requested',$3) ON CONFLICT(id) DO NOTHING`,[id,tx.companyId,JSON.stringify({siteId:order.data.siteId,orderId:order.id,day})]);}}
    for(const rule of await tx.list('automation_rule')){if(rule.data.status!=='ACTIVE'||!rule.data.approvedBy||Date.parse(rule.data.activeFrom)>now.getTime()||!rule.data.schedule?.cron)continue;try{if(!scheduleDue(rule.data.schedule.cron,now))continue;}catch{continue;}const id=key('scheduled-rule',rule.id,String(rule.data.ruleVersion),minute);await tx.query('INSERT INTO outbox(id,company_id,type,data) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO NOTHING',[id,tx.companyId,rule.data.trigger,JSON.stringify({...rule.data.parameters?.eventData,scheduledRuleId:rule.id,siteId:rule.data.scope.siteIds.length===1?rule.data.scope.siteIds[0]:undefined,customerId:rule.data.scope.customerIds.length===1?rule.data.scope.customerIds[0]:undefined})]);}
  });this.lastScheduleMinute=minute;}
}
