import { createHash } from 'node:crypto';
import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand, HeadBucketCommand } from '@aws-sdk/client-s3';
import { assert, DomainError } from '../domain/core.ts';

export interface BlobSql { query(sql:string,params?:any[]):Promise<{rows:any[]}>; }
export interface BlobInput { id:string;companyId:string;ownerId:string;bytes:Buffer;mimeType:string;sha256?:string; }
export interface PrivateBlob { id:string;companyId:string;ownerId:string;bytes:Buffer;mimeType:string;sha256:string;provider:'POSTGRES'|'S3'; }
export interface BlobReceipt {key:string;sha256:string;byteSize:number;mimeType:string;provider:'POSTGRES'|'S3';created:boolean;}
export interface PrivateBlobStore {
 readonly provider:'POSTGRES'|'S3';
 put(input:BlobInput,tx?:BlobSql):Promise<BlobReceipt>;
 get(companyId:string,id:string):Promise<PrivateBlob>;
 delete(companyId:string,id:string):Promise<void>;
 probe():Promise<{provider:string;configured:boolean;available:boolean;reason?:string}>;
}
const MAX_BYTES=25*1024*1024;
const MIME_TYPES=['image/jpeg','image/png','image/webp','application/pdf','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv; charset=utf-8'];
const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
function checked(input:BlobInput){assert(input.id&&input.companyId&&input.ownerId,'VALIDATION_ERROR');assert(input.bytes.length>0&&input.bytes.length<=MAX_BYTES,'VALIDATION_ERROR',{reason:'BLOB_SIZE'});assert(MIME_TYPES.includes(input.mimeType),'VALIDATION_ERROR');const sha256=hash(input.bytes);assert(!input.sha256||input.sha256===sha256,'VALIDATION_ERROR',{reason:'BLOB_CHECKSUM'});return sha256;}
const receipt=(input:BlobInput,sha256:string,provider:'POSTGRES'|'S3',created=true):BlobReceipt=>({key:input.id,sha256,byteSize:input.bytes.length,mimeType:input.mimeType,provider,created});
export class PostgresPrivateBlobStore implements PrivateBlobStore {
 readonly provider='POSTGRES' as const;
 constructor(private db:BlobSql){}
 async put(input:BlobInput,tx:BlobSql=this.db){const sha256=checked(input);const inserted=await tx.query('INSERT INTO media_blobs(id,company_id,owner_id,bytes,mime_type,sha256) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO NOTHING RETURNING id',[input.id,input.companyId,input.ownerId,input.bytes,input.mimeType,sha256]);if(!inserted.rows.length){const existing=(await tx.query('SELECT company_id,owner_id,bytes,sha256,mime_type FROM media_blobs WHERE id=$1',[input.id])).rows[0];assert(existing?.company_id===input.companyId&&existing?.owner_id===input.ownerId&&existing?.sha256===sha256&&existing?.mime_type===input.mimeType,'DUPLICATE_EFFECT',{reason:'BLOB_KEY_CONFLICT'});assert(hash(Buffer.from(existing.bytes))===existing.sha256,'INVALID_STATE',{reason:'STORAGE_CHECKSUM_MISMATCH'});}return receipt(input,sha256,this.provider,!!inserted.rows.length);}
 async get(companyId:string,id:string){const row=(await this.db.query('SELECT owner_id,bytes,mime_type,sha256 FROM media_blobs WHERE id=$1 AND company_id=$2',[id,companyId])).rows[0];assert(row,'NOT_FOUND_SAFE');const bytes=Buffer.from(row.bytes);assert(bytes.length<=MAX_BYTES&&hash(bytes)===row.sha256,'INVALID_STATE',{reason:'STORAGE_CHECKSUM_MISMATCH'});return {id,companyId,ownerId:row.owner_id,bytes,mimeType:row.mime_type,sha256:row.sha256,provider:this.provider};}
 async delete(companyId:string,id:string){await this.db.query('DELETE FROM media_blobs WHERE id=$1 AND company_id=$2',[id,companyId]);}
 async probe(){try{await this.db.query('SELECT 1');return {provider:this.provider,configured:true,available:true};}catch{return {provider:this.provider,configured:true,available:false,reason:'PROVIDER_UNAVAILABLE'};}}
}
export interface S3Config {bucket:string;region:string;endpoint?:string;forcePathStyle?:boolean;kmsKeyId?:string;allowInsecureLocalTest?:boolean;timeoutMs?:number;}
export interface S3Sender {send(command:any,options?:any):Promise<any>;}
async function boundedBytes(body:any){if(Buffer.isBuffer(body)){assert(body.length<=MAX_BYTES,'INVALID_STATE',{reason:'STORAGE_SIZE_LIMIT'});return body;}assert(body&&body[Symbol.asyncIterator],'PROVIDER_UNAVAILABLE');const chunks:Buffer[]=[];let total=0;for await(const chunk of body){const bytes=Buffer.from(chunk);total+=bytes.length;if(total>MAX_BYTES){body.destroy?.();throw new DomainError('INVALID_STATE',{reason:'STORAGE_SIZE_LIMIT'});}chunks.push(bytes);}return Buffer.concat(chunks,total);}
export class S3PrivateBlobStore implements PrivateBlobStore {
 readonly provider='S3' as const;
 private client:S3Sender;
 constructor(private config:S3Config,client?:S3Sender){assert(/^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/.test(config.bucket)&&config.region,'MISSING_CONFIGURATION',{reason:'S3_BUCKET_REGION'});if(config.endpoint){const url=new URL(config.endpoint);assert(!url.username&&!url.password&&(url.protocol==='https:'||config.allowInsecureLocalTest&&['localhost','127.0.0.1','::1','[::1]'].includes(url.hostname)),'MISSING_CONFIGURATION',{reason:'S3_TLS_REQUIRED'});}this.client=client??new S3Client({region:config.region,endpoint:config.endpoint,forcePathStyle:config.forcePathStyle??!!config.endpoint,maxAttempts:2});}
 private key(companyId:string,id:string){assert(companyId&&/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$/.test(id)&&!id.includes('..'),'VALIDATION_ERROR');return `companies/${createHash('sha256').update(companyId).digest('hex')}/blobs/${id}`;}
 private async send(command:any){try{return await this.client.send(command,{abortSignal:AbortSignal.timeout(this.config.timeoutMs??10000)});}catch(error:any){if(error?.name==='NoSuchKey'||error?.name==='NotFound'||error?.$metadata?.httpStatusCode===404)throw new DomainError('NOT_FOUND_SAFE');if(error?.name==='PreconditionFailed'||error?.$metadata?.httpStatusCode===412)throw new DomainError('DUPLICATE_EFFECT');throw new DomainError('PROVIDER_UNAVAILABLE',{provider:'S3'});}}
 async put(input:BlobInput){const sha256=checked(input),metadata={record:Buffer.from(JSON.stringify({id:input.id,companyId:input.companyId,ownerId:input.ownerId,sha256,byteSize:input.bytes.length,mimeType:input.mimeType})).toString('base64url'),sha256};let created=true;try{await this.send(new PutObjectCommand({Bucket:this.config.bucket,Key:this.key(input.companyId,input.id),Body:input.bytes,ContentType:input.mimeType,ChecksumSHA256:Buffer.from(sha256,'hex').toString('base64'),Metadata:metadata,ServerSideEncryption:this.config.kmsKeyId?'aws:kms':'AES256',...(this.config.kmsKeyId?{SSEKMSKeyId:this.config.kmsKeyId}:{}),IfNoneMatch:'*'}));}catch(error){if(!(error instanceof DomainError)||error.code!=='DUPLICATE_EFFECT')throw error;created=false;const previous=await this.get(input.companyId,input.id);assert(previous.sha256===sha256&&previous.ownerId===input.ownerId&&previous.mimeType===input.mimeType,'DUPLICATE_EFFECT',{reason:'BLOB_KEY_CONFLICT'});}return receipt(input,sha256,this.provider,created);}
 async get(companyId:string,id:string){const response=await this.send(new GetObjectCommand({Bucket:this.config.bucket,Key:this.key(companyId,id),ChecksumMode:'ENABLED'}));try{assert(!response.ContentLength||response.ContentLength<=MAX_BYTES,'INVALID_STATE',{reason:'STORAGE_SIZE_LIMIT'});let record:any;try{record=JSON.parse(Buffer.from(response.Metadata?.record??'','base64url').toString('utf8'));}catch{throw new DomainError('INVALID_STATE',{reason:'STORAGE_METADATA_INVALID'});}assert(record.id===id&&record.companyId===companyId,'NOT_FOUND_SAFE');assert(record.mimeType===response.ContentType&&MIME_TYPES.includes(record.mimeType),'INVALID_STATE',{reason:'STORAGE_MIME_MISMATCH'});const bytes=await boundedBytes(response.Body);assert(record.byteSize===bytes.length&&record.sha256===hash(bytes)&&response.Metadata?.sha256===record.sha256,'INVALID_STATE',{reason:'STORAGE_CHECKSUM_MISMATCH'});if(response.ChecksumSHA256)assert(response.ChecksumSHA256===Buffer.from(record.sha256,'hex').toString('base64'),'INVALID_STATE',{reason:'STORAGE_CHECKSUM_MISMATCH'});return {id,companyId,ownerId:record.ownerId,bytes,mimeType:response.ContentType||'application/octet-stream',sha256:record.sha256,provider:this.provider};}catch(error){response.Body?.destroy?.();throw error;}}
 async delete(companyId:string,id:string){await this.send(new DeleteObjectCommand({Bucket:this.config.bucket,Key:this.key(companyId,id)}));}
 async probe(){try{await this.send(new HeadBucketCommand({Bucket:this.config.bucket}));return {provider:this.provider,configured:true,available:true};}catch{return {provider:this.provider,configured:true,available:false,reason:'PROVIDER_UNAVAILABLE'};}}
}
export function createPrivateBlobStore(db:BlobSql,env:NodeJS.ProcessEnv=process.env):PrivateBlobStore {if(!env.S3_BUCKET)return new PostgresPrivateBlobStore(db);return new S3PrivateBlobStore({bucket:env.S3_BUCKET,region:env.AWS_REGION||env.S3_REGION||'eu-central-1',endpoint:env.S3_ENDPOINT,forcePathStyle:env.S3_FORCE_PATH_STYLE!=='false',kmsKeyId:env.S3_KMS_KEY_ID,allowInsecureLocalTest:env.APP_MODE!=='PRODUCTION'&&env.S3_ALLOW_INSECURE_LOCAL_TEST==='true'});}
