import { deflateRawSync } from 'node:zlib';
import { assert } from '../domain/core.ts';

export type XlsxCell = string | number | boolean | null | undefined;
export interface XlsxImage {bytes:Buffer;mimeType:'image/jpeg'|'image/png';row:number;column:number;widthPx:number;heightPx:number;}
export interface XlsxSheet {name:string;rows:XlsxCell[][];columnWidths?:number[];header?:boolean;images?:XlsxImage[];}
export interface XlsxWorkbook {creator:string;createdAt:string;title:string;subject:string;description:string;sheets:XlsxSheet[];}
const MAIN='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
const REL='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const PACKAGE_REL='http://schemas.openxmlformats.org/package/2006/relationships';
const XML='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
const escapeXml=(value:string)=>{assert(!/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value)&&Buffer.from(value,'utf8').toString('utf8')===value,'VALIDATION_ERROR',{reason:'XLSX_XML_TEXT'});return value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;').replaceAll('\r','&#13;').replaceAll('\n','&#10;').replaceAll('\t','&#9;');};
function columnName(index:number){let name='';for(let value=index+1;value>0;value=Math.floor((value-1)/26))name=String.fromCharCode(65+(value-1)%26)+name;return name;}
function cellXml(value:XlsxCell,row:number,column:number,header:boolean){if(value===null||value===undefined)return '';const address=`${columnName(column)}${row}`,style=header?' s="1"':'';if(typeof value==='boolean')return `<c r="${address}"${style} t="b"><v>${value?1:0}</v></c>`;if(typeof value==='number'){assert(Number.isSafeInteger(value),'VALIDATION_ERROR',{reason:'XLSX_EXACT_INTEGER_REQUIRED'});if(Math.abs(value)<1_000_000_000_000_000)return `<c r="${address}"${style} t="n"><v>${value}</v></c>`;value=String(value);}assert(value.length<=32767,'VALIDATION_ERROR',{reason:'XLSX_CELL_LENGTH'});return `<c r="${address}"${style} t="inlineStr"><is><t xml:space="preserve">${escapeXml(value)}</t></is></c>`;}

const crcTable=new Uint32Array(256);for(let i=0;i<256;i++){let crc=i;for(let bit=0;bit<8;bit++)crc=crc&1?0xedb88320^(crc>>>1):crc>>>1;crcTable[i]=crc>>>0;}
function crc32(bytes:Buffer){let crc=0xffffffff;for(const byte of bytes)crc=crcTable[(crc^byte)&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
function zip(entries:Map<string,Buffer>,createdAt:string):Buffer {assert(entries.size<=65535,'VALIDATION_ERROR');const original=new Date(createdAt);assert(Number.isFinite(original.getTime()),'VALIDATION_ERROR');const year=Math.min(2107,Math.max(1980,original.getUTCFullYear())),date=((year-1980)<<9)|((original.getUTCMonth()+1)<<5)|original.getUTCDate(),time=(original.getUTCHours()<<11)|(original.getUTCMinutes()<<5)|Math.floor(original.getUTCSeconds()/2);const local:Buffer[]=[],central:Buffer[]=[];let offset=0,centralSize=0;for(const [path,bytes] of entries){const name=Buffer.from(path,'utf8'),compressed=deflateRawSync(bytes,{level:9}),crc=crc32(bytes);assert(bytes.length<=0xffffffff&&compressed.length<=0xffffffff&&offset<=0xffffffff,'VALIDATION_ERROR');const header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50,0);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(8,8);header.writeUInt16LE(time,10);header.writeUInt16LE(date,12);header.writeUInt32LE(crc,14);header.writeUInt32LE(compressed.length,18);header.writeUInt32LE(bytes.length,22);header.writeUInt16LE(name.length,26);local.push(header,name,compressed);const directory=Buffer.alloc(46);directory.writeUInt32LE(0x02014b50,0);directory.writeUInt16LE(20,4);directory.writeUInt16LE(20,6);directory.writeUInt16LE(0x800,8);directory.writeUInt16LE(8,10);directory.writeUInt16LE(time,12);directory.writeUInt16LE(date,14);directory.writeUInt32LE(crc,16);directory.writeUInt32LE(compressed.length,20);directory.writeUInt32LE(bytes.length,24);directory.writeUInt16LE(name.length,28);directory.writeUInt32LE(offset,42);central.push(directory,name);centralSize+=directory.length+name.length;offset+=header.length+name.length+compressed.length;}const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries.size,8);end.writeUInt16LE(entries.size,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,...central,end]);}
const relationships=(items:{id:string;type:string;target:string}[])=>`${XML}<Relationships xmlns="${PACKAGE_REL}">${items.map(item=>`<Relationship Id="${item.id}" Type="${REL}/${item.type}" Target="${escapeXml(item.target)}"/>`).join('')}</Relationships>`;

/** Actual ECMA-376 workbook, including ZIP CRCs, inline strings and private report photo parts. */
export function writeXlsxWorkbook(spec:XlsxWorkbook):Buffer {
 assert(spec.sheets.length>0&&spec.sheets.length<=100&&new Set(spec.sheets.map(s=>s.name.toLocaleUpperCase())).size===spec.sheets.length,'VALIDATION_ERROR');
 const entries=new Map<string,Buffer>(),add=(path:string,xml:string)=>entries.set(path,Buffer.from(xml,'utf8')),overrides:{part:string;type:string}[]=[],mediaTypes=new Set<string>();
 add('_rels/.rels',`${XML}<Relationships xmlns="${PACKAGE_REL}"><Relationship Id="rId1" Type="${REL}/officeDocument" Target="xl/workbook.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="${REL}/extended-properties" Target="docProps/app.xml"/></Relationships>`);
 add('docProps/core.xml',`${XML}<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:creator>${escapeXml(spec.creator)}</dc:creator><cp:lastModifiedBy>${escapeXml(spec.creator)}</cp:lastModifiedBy><dc:title>${escapeXml(spec.title)}</dc:title><dc:subject>${escapeXml(spec.subject)}</dc:subject><dc:description>${escapeXml(spec.description)}</dc:description><dcterms:created xsi:type="dcterms:W3CDTF">${escapeXml(spec.createdAt)}</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">${escapeXml(spec.createdAt)}</dcterms:modified></cp:coreProperties>`);
 add('docProps/app.xml',`${XML}<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>KNABA DE</Application><AppVersion>1.0</AppVersion><TitlesOfParts><vt:vector size="${spec.sheets.length}" baseType="lpstr">${spec.sheets.map(s=>`<vt:lpstr>${escapeXml(s.name)}</vt:lpstr>`).join('')}</vt:vector></TitlesOfParts></Properties>`);
 add('xl/workbook.xml',`${XML}<workbook xmlns="${MAIN}" xmlns:r="${REL}"><bookViews><workbookView/></bookViews><sheets>${spec.sheets.map((sheet,index)=>`<sheet name="${escapeXml(sheet.name)}" sheetId="${index+1}" r:id="rId${index+1}"/>`).join('')}</sheets></workbook>`);
 add('xl/_rels/workbook.xml.rels',relationships([...spec.sheets.map((_,index)=>({id:`rId${index+1}`,type:'worksheet',target:`worksheets/sheet${index+1}.xml`})),{id:'rIdStyles',type:'styles',target:'styles.xml'}]));
 add('xl/styles.xml',`${XML}<styleSheet xmlns="${MAIN}"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF163E34"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="1" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`);
 let imageIndex=0,drawingIndex=0;
 for(let index=0;index<spec.sheets.length;index++){const sheet=spec.sheets[index],part=`/xl/worksheets/sheet${index+1}.xml`;assert(sheet.name.length>0&&sheet.name.length<=31&&!/[\\/*?:\[\]]/.test(sheet.name)&&sheet.rows.length<=1048576,'VALIDATION_ERROR');const columns=sheet.rows.reduce((n,row)=>Math.max(n,row.length),1);assert(columns<=16384,'VALIDATION_ERROR');let drawing='';
  if(sheet.images?.length){drawingIndex++;const anchors:string[]=[],rels:{id:string;type:string;target:string}[]=[];for(const image of sheet.images){assert(Number.isInteger(image.row)&&image.row>=1&&image.row<=1048576&&Number.isInteger(image.column)&&image.column>=1&&image.column<=16384&&image.widthPx>0&&image.heightPx>0&&image.widthPx<=10000&&image.heightPx<=10000,'VALIDATION_ERROR');assert(image.bytes.length>0&&image.bytes.length<=25*1024*1024,'VALIDATION_ERROR');const png=image.mimeType==='image/png';assert(png?image.bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):image.bytes[0]===255&&image.bytes[1]===216,'VALIDATION_ERROR',{reason:'XLSX_IMAGE_SIGNATURE'});imageIndex++;const extension=png?'png':'jpeg',id=`rIdImage${imageIndex}`,cx=Math.round(image.widthPx*9525),cy=Math.round(image.heightPx*9525);entries.set(`xl/media/image${imageIndex}.${extension}`,image.bytes);mediaTypes.add(extension);rels.push({id,type:'image',target:`../media/image${imageIndex}.${extension}`});anchors.push(`<xdr:oneCellAnchor><xdr:from><xdr:col>${image.column-1}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${image.row-1}</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="${cx}" cy="${cy}"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${imageIndex}" name="Report photo ${imageIndex}"/><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="${id}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`);}
   add(`xl/drawings/drawing${drawingIndex}.xml`,`${XML}<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${REL}">${anchors.join('')}</xdr:wsDr>`);add(`xl/drawings/_rels/drawing${drawingIndex}.xml.rels`,relationships(rels));add(`xl/worksheets/_rels/sheet${index+1}.xml.rels`,relationships([{id:'rIdDrawing',type:'drawing',target:`../drawings/drawing${drawingIndex}.xml`}]));overrides.push({part:`/xl/drawings/drawing${drawingIndex}.xml`,type:'application/vnd.openxmlformats-officedocument.drawing+xml'});drawing='<drawing r:id="rIdDrawing"/>';
  }
  const widths=sheet.columnWidths?.map((width,i)=>{assert(width>0&&width<=255,'VALIDATION_ERROR');return `<col min="${i+1}" max="${i+1}" width="${width}" customWidth="1"/>`;}).join('')||'';
  add(part.slice(1),`${XML}<worksheet xmlns="${MAIN}" xmlns:r="${REL}"><dimension ref="A1:${columnName(columns-1)}${Math.max(1,sheet.rows.length)}"/><sheetViews><sheetView workbookViewId="0">${sheet.header?'<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/><selection pane="bottomLeft" activeCell="A2" sqref="A2"/>':'<selection activeCell="A1" sqref="A1"/>'}</sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/>${widths?`<cols>${widths}</cols>`:''}<sheetData>${sheet.rows.map((row,i)=>`<row r="${i+1}">${row.map((value,j)=>cellXml(value,i+1,j,sheet.header===true&&i===0)).join('')}</row>`).join('')}</sheetData>${sheet.header?`<autoFilter ref="A1:${columnName(columns-1)}${Math.max(1,sheet.rows.length)}"/>`:''}<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/>${drawing}</worksheet>`);overrides.push({part,type:'application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml'});
 }
 add('[Content_Types].xml',`${XML}<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${[...mediaTypes].map(ext=>`<Default Extension="${ext}" ContentType="image/${ext==='jpeg'?'jpeg':'png'}"/>`).join('')}<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>${overrides.map(item=>`<Override PartName="${item.part}" ContentType="${item.type}"/>`).join('')}</Types>`);
 return zip(entries,spec.createdAt);
}
