import type { SupportedLanguage } from './deepseek.ts';
export const routerLanguages:SupportedLanguage[]=['DE','UK','RU','PL','LT','EN'];
const rows:Record<string,string[]>={
 main:['KNABA DE · Arbeitsmenü','KNABA DE · Робоче меню','KNABA DE · Рабочее меню','KNABA DE · Menu pracy','KNABA DE · Darbo meniu','KNABA DE · Work menu'],
 select:['Auswählen','Вибрати','Выбрать','Wybierz','Pasirinkti','Choose'],
 shift:['Meine Schicht','Моя зміна','Моя смена','Moja zmiana','Mano pamaina','My shift'],
 start:['Schicht starten','Почати зміну','Начать смену','Rozpocznij zmianę','Pradėti pamainą','Start shift'],
 pause:['Private Pause','Приватна перерва','Личный перерыв','Przerwa prywatna','Privati pertrauka','Private break'],
 resume:['Zurück zur Arbeit','Повернутися до роботи','Вернуться к работе','Wróć do pracy','Grįžti į darbą','Return to work'],
 end:['Schicht beenden','Завершити зміну','Завершить смену','Zakończ zmianę','Baigti pamainą','End shift'],
 travel:['Dienstfahrt','Службовий переїзд','Служебный переезд','Przejazd służbowy','Darbo kelionė','Business travel'],
 materials:['Materialien','Матеріали','Материалы','Materiały','Medžiagos','Materials'],
 tasks:['Meine Aufgaben','Мої завдання','Мои задачи','Moje zadania','Mano užduotys','My tasks'],
 hours:['Meine Stunden','Мої години','Мои часы','Moje godziny','Mano valandos','My hours'],
 payroll:['Meine Auszahlungen','Мої виплати','Мои выплаты','Moje wypłaty','Mano išmokos','My payouts'],
 chats:['Chats','Чати','Чаты','Czaty','Pokalbiai','Chats'],
 gps:['GPS / Gerät','GPS / пристрій','GPS / устройство','GPS / urządzenie','GPS / įrenginys','GPS / device'],
 admin:['Verwaltung','Адміністрування','Администрирование','Administracja','Administravimas','Administration'],
 language:['Sprache','Мова','Язык','Język','Kalba','Language'],
 help:['Hilfe / Mensch','Допомога / людина','Помощь / человек','Pomoc / człowiek','Pagalba / žmogus','Help / human'],
 more:['Weiter','Далі','Далее','Dalej','Toliau','Next'],
 back:['Zurück','Назад','Назад','Wstecz','Atgal','Back'],
 cancel:['Abbrechen','Скасувати','Отменить','Anuluj','Atšaukti','Cancel'],
 continue:['Entwurf fortsetzen','Продовжити чернетку','Продолжить черновик','Kontynuuj szkic','Tęsti juodraštį','Resume draft'],
 confirm:['Bestätigen','Підтвердити','Подтвердить','Potwierdź','Patvirtinti','Confirm'],
 preview:['Vorschau – erst Ihre Bestätigung führt die Aktion aus.','Попередній перегляд — дію виконає лише ваше підтвердження.','Предпросмотр — действие выполнится только после подтверждения.','Podgląd — działanie nastąpi dopiero po potwierdzeniu.','Peržiūra — veiksmas bus atliktas tik patvirtinus.','Preview — only your confirmation performs this action.'],
 saved:['Server hat die Aktion bestätigt.','Сервер підтвердив дію.','Сервер подтвердил действие.','Serwer potwierdził działanie.','Serveris patvirtino veiksmą.','Server confirmed the action.'],
 already:['Diese Bestätigung wurde bereits verarbeitet.','Це підтвердження вже оброблено.','Это подтверждение уже обработано.','To potwierdzenie zostało już przetworzone.','Šis patvirtinimas jau apdorotas.','This confirmation was already processed.'],
 processing:['Die Bestätigung wird verarbeitet. Kein zweites Mal ausführen.','Підтвердження обробляється. Повторної дії не буде.','Подтверждение обрабатывается. Повторного действия не будет.','Potwierdzenie jest przetwarzane. Bez ponownego działania.','Patvirtinimas apdorojamas. Pakartotinio veiksmo nebus.','Confirmation is being processed. No second action will run.'],
 taskStart:['Aufgabe beginnen','Почати завдання','Начать задачу','Rozpocznij zadanie','Pradėti užduotį','Start task'],
 settings:['Einstellungen','Налаштування','Настройки','Ustawienia','Nustatymai','Settings'],
 system:['Systemstatus','Стан системи','Состояние системы','Stan systemu','Sistemos būsena','System status'],
 people:['Menschen / Rollen','Люди / ролі','Люди / роли','Osoby / role','Žmonės / rolės','People / roles'],
 decisions:['Entscheidungen','Рішення','Решения','Decyzje','Sprendimai','Decisions'],
 noGps:['GPS wurde dadurch nicht eingeschaltet.','GPS від цієї дії не ввімкнувся.','GPS от этого действия не включился.','To działanie nie włączyło GPS.','Šis veiksmas GPS neįjungė.','This action did not activate GPS.'],
 empty:['Keine passenden Einträge.','Немає відповідних записів.','Нет подходящих записей.','Brak pasujących wpisów.','Tinkamų įrašų nėra.','No matching records.'],
 noShift:['Keine aktive Schicht.','Немає активної зміни.','Нет активной смены.','Brak aktywnej zmiany.','Aktyvios pamainos nėra.','No active shift.'],
 stale:['Diese Auswahl ist abgelaufen oder der Zustand wurde geändert. Öffnen Sie MENU erneut.','Цей вибір прострочено або стан змінився. Відкрийте MENU знову.','Выбор просрочен или состояние изменилось. Откройте MENU снова.','Wybór wygasł lub stan się zmienił. Otwórz ponownie MENU.','Pasirinkimas nebegalioja arba būsena pasikeitė. Atidarykite MENU.','This selection expired or the state changed. Open MENU again.'],
 denied:['Aktueller Zugriff fehlt. Anmeldung oder Freigabe im geschützten Webkonto prüfen.','Чинного доступу немає. Перевірте вхід і права в захищеному вебкабінеті.','Доступ отсутствует. Проверьте вход и права в защищённом вебкабинете.','Brak aktualnego dostępu. Sprawdź logowanie i prawa w portalu.','Dabartinės prieigos nėra. Patikrinkite prisijungimą ir teises portale.','Current access is missing. Check sign-in and permissions in the secure portal.'],
 error:['Aktion nicht ausgeführt. Bitte Eingaben prüfen oder im Webkonto fortsetzen.','Дію не виконано. Перевірте дані або продовжте у вебкабінеті.','Действие не выполнено. Проверьте данные или продолжите в вебкабинете.','Działanie nie zostało wykonane. Sprawdź dane lub kontynuuj w portalu.','Veiksmas neatliktas. Patikrinkite duomenis arba tęskite portale.','Action was not performed. Check input or continue in the portal.'],
 site:['Zugewiesenes Objekt auswählen','Виберіть призначений об’єкт','Выберите назначенный объект','Wybierz przypisany obiekt','Pasirinkite priskirtą objektą','Choose an assigned site'],
 destination:['Genehmigtes Dienstziel auswählen. Kein privater Heimweg.','Виберіть дозволений службовий пункт. Не приватний шлях додому.','Выберите разрешённый служебный пункт. Не личный путь домой.','Wybierz dozwolony cel służbowy. Bez prywatnej drogi do domu.','Pasirinkite leidžiamą darbo tikslą. Ne privačią kelionę namo.','Choose an allowed business destination. Exclude private journeys home.'],
 purpose:['Zweck der Dienstfahrt als Text senden. Während der Fahrt nur nach sicherem Halt bedienen.','Надішліть мету переїзду текстом. Користуйтеся телефоном лише після безпечної зупинки.','Отправьте цель переезда текстом. Пользуйтесь телефоном только после безопасной остановки.','Wyślij cel przejazdu. Telefon obsługuj po bezpiecznym zatrzymaniu.','Siųskite kelionės tikslą. Telefonu naudokitės tik saugiai sustoję.','Send the travel purpose. Use the phone only after stopping safely.'],
 arrive:['Ankunft bestätigen','Підтвердити прибуття','Подтвердить прибытие','Potwierdź przyjazd','Patvirtinti atvykimą','Confirm arrival'],
 arriveWork:['Ankunft + Arbeit','Прибуття + робота','Прибытие + работа','Przyjazd + praca','Atvykimas + darbas','Arrival + start work'],
 newRequest:['Neue Materialanfrage','Нова заявка матеріалів','Новая заявка материалов','Nowy wniosek materiałów','Nauja medžiagų užklausa','New material request'],
 material:['Material auswählen','Виберіть матеріал','Выберите материал','Wybierz materiał','Pasirinkite medžiagą','Choose a material'],
 quantity:['Menge mit freigegebener Einheit senden, z. B. 2 l oder 3 pcs.','Надішліть кількість із дозволеною одиницею: 2 l або 3 pcs.','Отправьте количество с разрешённой единицей: 2 l или 3 pcs.','Wyślij ilość z dozwoloną jednostką, np. 2 l lub 3 pcs.','Siųskite kiekį su leidžiamu vienetu, pvz. 2 l arba 3 pcs.','Send quantity with an allowed unit, e.g. 2 l or 3 pcs.'],
 reason:['Begründung als Text senden.','Надішліть пояснення текстом.','Отправьте объяснение текстом.','Wyślij uzasadnienie tekstem.','Siųskite paaiškinimą tekstu.','Send the reason as text.'],
 due:['Benötigt bis: ISO-Zeit mit Zeitzone senden, z. B. 2026-10-07T08:00:00+02:00.','Потрібно до: надішліть ISO-час із часовим поясом, наприклад 2026-10-07T08:00:00+02:00.','Требуется до: отправьте ISO-время с часовым поясом, например 2026-10-07T08:00:00+02:00.','Termin: wyślij czas ISO ze strefą, np. 2026-10-07T08:00:00+02:00.','Reikia iki: siųskite ISO laiką su zona, pvz. 2026-10-07T08:00:00+02:00.','Needed by: send ISO time with zone, e.g. 2026-10-07T08:00:00+02:00.'],
 draft:['Entwurf; noch nicht eingereicht oder freigegeben.','Чернетка; ще не подано і не погоджено.','Черновик; ещё не подан и не согласован.','Szkic; jeszcze nie złożony ani zatwierdzony.','Juodraštis; dar nepateiktas ir nepatvirtintas.','Draft; not submitted or approved.'],
 submit:['Zur Prüfung einreichen','Подати на перевірку','Подать на проверку','Prześlij do sprawdzenia','Pateikti peržiūrai','Submit for review'],
 full:['Vollständig erhalten','Отримано повністю','Получено полностью','Otrzymano całość','Gauta visa suma','Received in full'],
 partial:['Teilweise erhalten','Отримано частково','Получено частично','Otrzymano część','Gauta dalis','Received partially'],
 disputed:['Bestreiten','Оспорити','Оспорить','Zakwestionuj','Ginčyti','Dispute'],
 amount:['Tatsächlich erhaltenen EUR-Betrag senden, z. B. 25,50.','Надішліть фактично отриману суму EUR, наприклад 25,50.','Отправьте фактически полученную сумму EUR, например 25,50.','Wyślij faktycznie otrzymaną kwotę EUR, np. 25,50.','Siųskite faktiškai gautą EUR sumą, pvz. 25,50.','Send the EUR amount actually received, e.g. 25.50.'],
 statement:['Ihre eigene Empfangserklärung oder den Streitgrund senden.','Надішліть власне підтвердження отримання або причину спору.','Отправьте своё подтверждение получения или причину спора.','Wyślij własne oświadczenie odbioru lub powód sporu.','Siųskite savo gavimo pareiškimą arba ginčo priežastį.','Send your own receipt statement or dispute reason.'],
 compose:['Text wird nur im genannten Kanal gesendet. /MENU wechselt zum Menü.','Текст буде надіслано лише у вказаний канал. /MENU відкриває меню.','Текст отправится только в указанный канал. /MENU открывает меню.','Tekst zostanie wysłany tylko do wskazanego kanału. /MENU otwiera menu.','Tekstas siunčiamas tik į nurodytą kanalą. /MENU atidaro meniu.','Text goes only to the named channel. /MENU opens the menu.'],
 description:['Ergebnisbeschreibung senden. Fotos benötigen einen bestätigten Kontext.','Надішліть опис результату. Фото потребують підтвердженого контексту.','Отправьте описание результата. Фото требуют подтверждённого контекста.','Wyślij opis wyniku. Zdjęcia wymagają potwierdzonego kontekstu.','Siųskite rezultato aprašymą. Nuotraukoms būtinas patvirtintas kontekstas.','Send the result description. Photos require confirmed context.'],
 gpsNotice:['WhatsApp liefert nur manuell gesendete Einzelpunkte. Hintergrund-GPS benötigt die native App, Ihre Aktivierung und genehmigte Richtlinie.','WhatsApp передає лише вручну надіслані точки. Фоновий GPS потребує native-застосунку, вашої активації та погодженої політики.','WhatsApp передаёт только вручную отправленные точки. Фоновый GPS требует native-приложения, вашей активации и согласованной политики.','WhatsApp przekazuje ręcznie wysłane pojedyncze punkty. GPS w tle wymaga aplikacji native, aktywacji i zatwierdzonej polityki.','WhatsApp perduoda tik rankiniu būdu siųstus taškus. GPS fone reikia native programėlės, jūsų aktyvavimo ir patvirtintos politikos.','WhatsApp provides only manually sent points. Background GPS requires the native app, your activation and an approved policy.'],
 helpNotice:['MENU, START, BREAK, RESUME, END, TRAVEL, MATERIALS, PAYROLL, CHATS, LANGUAGE. Freier Text bleibt Original. Kein AI-Befehl ändert Rechte. Unterstützung im geschützten Webkonto.','MENU, START, BREAK, RESUME, END, TRAVEL, MATERIALS, PAYROLL, CHATS, LANGUAGE. Вільний текст лишається оригіналом. AI не змінює права. Допомога у захищеному вебкабінеті.','MENU, START, BREAK, RESUME, END, TRAVEL, MATERIALS, PAYROLL, CHATS, LANGUAGE. Свободный текст сохраняется оригиналом. AI не меняет права. Помощь в защищённом вебкабинете.','MENU, START, BREAK, RESUME, END, TRAVEL, MATERIALS, PAYROLL, CHATS, LANGUAGE. Tekst pozostaje oryginałem. AI nie zmienia uprawnień. Pomoc w portalu.','MENU, START, BREAK, RESUME, END, TRAVEL, MATERIALS, PAYROLL, CHATS, LANGUAGE. Tekstas lieka originalus. AI nekeičia teisių. Pagalba saugiame portale.','MENU, START, BREAK, RESUME, END, TRAVEL, MATERIALS, PAYROLL, CHATS, LANGUAGE. Free text remains original. AI cannot change permissions. Support in the secure portal.'],
 web:['Im sicheren Webkonto fortsetzen','Продовжте у захищеному вебкабінеті','Продолжите в защищённом вебкабинете','Kontynuuj w bezpiecznym portalu','Tęskite saugiame portale','Continue in the secure portal'],
 optin:['Arbeitsbenachrichtigungen erlaubt. Keine Marketing-Einwilligung. STOP widerruft die Zustellung.','Робочі сповіщення дозволено. Це не згода на маркетинг. STOP відкликає доставку.','Рабочие уведомления разрешены. Это не согласие на маркетинг. STOP отменяет доставку.','Powiadomienia robocze dozwolone. Bez zgody marketingowej. STOP cofa dostarczanie.','Darbo pranešimai leidžiami. Tai ne rinkodaros sutikimas. STOP atšaukia siuntimą.','Work notifications allowed. This does not grant marketing consent. STOP revokes delivery.'],
 stopped:['WhatsApp-Zustellung widerrufen. Webkonto und Arbeitszeiterfassung bleiben verfügbar.','Доставку WhatsApp відкликано. Вебкабінет і облік часу залишаються доступними.','Доставка WhatsApp отключена. Вебкабинет и учёт времени остаются доступными.','Dostarczanie WhatsApp wycofane. Portal i ewidencja czasu pozostają dostępne.','WhatsApp siuntimas atšauktas. Portalas ir laiko apskaita lieka prieinami.','WhatsApp delivery revoked. Portal and timekeeping remain available.'],
 mediaSite:['Datei geprüft. Objekt ausdrücklich wählen; noch kein Arbeitsnachweis registriert.','Файл перевірено. Явно виберіть об’єкт; доказ робіт ще не зареєстровано.','Файл проверен. Явно выберите объект; доказательство работ ещё не зарегистрировано.','Plik sprawdzony. Wybierz obiekt; dowód pracy nie jest jeszcze zarejestrowany.','Failas patikrintas. Pasirinkite objektą; darbo įrodymas dar neregistruotas.','File checked. Explicitly choose the site; no work evidence has been registered yet.'],
 mediaTask:['Aufgabe ausdrücklich wählen oder Objektbezug ohne Aufgabe.','Явно виберіть завдання або прив’язку до об’єкта без завдання.','Явно выберите задачу или объект без задачи.','Wybierz zadanie lub powiązanie z samym obiektem.','Pasirinkite užduotį arba tik objektą.','Choose a task explicitly or site context without a task.'],
 siteOnly:['Nur Objekt','Лише об’єкт','Только объект','Tylko obiekt','Tik objektas','Site only'],
 stage:['Beweisphase auswählen','Виберіть етап доказу','Выберите этап доказательства','Wybierz etap dowodu','Pasirinkite įrodymo etapą','Choose evidence stage'],
 BEFORE:['Vorher','До','До','Przed','Prieš','Before'],AFTER:['Nachher','Після','После','Po','Po','After'],DEFECT:['Mangel','Дефект','Дефект','Wada','Defektas','Defect'],MATERIALS:['Materialien','Матеріали','Материалы','Materiały','Medžiagos','Materials'],DOCUMENT:['Dokument','Документ','Документ','Dokument','Dokumentas','Document'],
 internal:['Nur intern; nicht automatisch für Kunden freigegeben.','Лише внутрішнє; клієнту автоматично не відкривається.','Только внутреннее; клиенту автоматически не открывается.','Tylko wewnętrzne; bez automatycznego udostępnienia klientowi.','Tik viduje; klientui automatiškai neatskleidžiama.','Internal only; no automatic customer publication.'],
 WORKING:['Arbeit','Робота','Работа','Praca','Darbas','Working'],ON_BREAK:['Private Pause','Приватна перерва','Личный перерыв','Przerwa prywatna','Privati pertrauka','Private break'],TRAVELLING:['Dienstfahrt','Службовий переїзд','Служебный переезд','Przejazd','Kelionė','Travelling'],AWAY_PENDING_REASON:['Erklärung offen','Очікує пояснення','Ожидает объяснения','Oczekuje wyjaśnienia','Laukiama paaiškinimo','Explanation pending'],SERVICE_TASK:['Dienstauftrag','Службове доручення','Служебное поручение','Zadanie służbowe','Darbo pavedimas','Service task'],WAITING_WORK:['Dienstliches Warten','Службове очікування','Служебное ожидание','Oczekiwanie służbowe','Darbo laukimas','Work waiting'],
 noReauth:['Diese Aktion benötigt Web-Anmeldung/MFA. WhatsApp ersetzt diese Prüfung nicht.','Ця дія потребує входу/MFA у вебкабінеті. WhatsApp не замінює цю перевірку.','Это действие требует входа/MFA в вебкабинете. WhatsApp не заменяет проверку.','Ta akcja wymaga logowania/MFA w portalu. WhatsApp nie zastępuje weryfikacji.','Šiam veiksmui reikia prisijungimo/MFA portale. WhatsApp to nepakeičia.','This action requires portal sign-in/MFA. WhatsApp does not replace that check.'],
 manualMedia:['Datei noch nicht geprüft oder Kontext fehlt. Im geschützten Webkonto fortsetzen.','Файл ще не перевірено або немає контексту. Продовжте у захищеному вебкабінеті.','Файл ещё не проверен или отсутствует контекст. Продолжите в защищённом вебкабинете.','Plik niesprawdzony lub brak kontekstu. Kontynuuj w portalu.','Failas nepatikrintas arba nėra konteksto. Tęskite saugiame portale.','File has not been checked or context is missing. Continue in the secure portal.'],
};
export function routerText(language:SupportedLanguage,key:string){return rows[key]?.[routerLanguages.indexOf(language)]??key;}
export const languageLabel:Record<SupportedLanguage,string>={DE:'Deutsch',UK:'Українська',RU:'Русский',PL:'Polski',LT:'Lietuvių',EN:'English'};
/** Original-message metadata only. This does not change interface preference or treat a quote as a language-setting command. */
export function originalMessageLanguage(text:string,fallback:SupportedLanguage):SupportedLanguage {
 if(/[іїєґ]/iu.test(text))return 'UK';
 if(/[ыэъё]/iu.test(text))return 'RU';
 if(/[łńśźż]/iu.test(text))return 'PL';
 if(/[ėįųū]/iu.test(text))return 'LT';
 const scores:{language:SupportedLanguage;matches:number}[]=[['DE',/\b(?:bitte|nicht|fenster|boden|reinigen|zuerst|heute|morgen|arbeiten|st[üu]ck)\b/giu],['EN',/\b(?:please|not|windows|floor|clean|first|today|tomorrow|work|received)\b/giu],['PL',/\b(?:proszę|nie|okna|podłoga|najpierw|dzisiaj)\b/giu],['LT',/\b(?:prašau|negalima|langai|grindys|šiandien)\b/giu]].map(([language,pattern])=>({language:language as SupportedLanguage,matches:(text.match(pattern as RegExp)??[]).length}));
 scores.sort((a,b)=>b.matches-a.matches);return scores[0]!.matches>=2&&scores[0]!.matches>scores[1]!.matches?scores[0]!.language:fallback;
}
/** Exact standalone commands only. Quoted text and an ordinary sentence never execute a work action. */
export function parseRouterCommand(text:string):{command:string;language?:SupportedLanguage}|undefined {
  const value=text.trim().replace(/^\//,'').toLocaleUpperCase();if(!value||value.length>40||value.includes('\n'))return;
  const common=['MENU','BACK','CANCEL','CONTINUE','HELP','SHIFT','START','BREAK','RESUME','END','TRAVEL','MATERIALS','TASKS','HOURS','PAYROLL','CHATS','GPS','ADMIN','LANGUAGE','OPTIN','STOP'];
  if(common.includes(value))return {command:value};
  const aliases:Record<string,[string,SupportedLanguage]>={МЕНЮ:['MENU','UK'],ПЕРЕРВА:['BREAK','UK'],ПОВЕРНУВСЯ:['RESUME','UK'],ЗАВЕРШИТИ:['END','UK'],ПЕРЕЇЗД:['TRAVEL','UK'],МАТЕРІАЛИ:['MATERIALS','UK'],МОВА:['LANGUAGE','UK'],ДОПОМОГА:['HELP','UK'],НАЧАТЬ:['START','RU'],ПЕРЕРЫВ:['BREAK','RU'],ВЕРНУЛСЯ:['RESUME','RU'],ЗАВЕРШИТЬ:['END','RU'],ПЕРЕЕЗД:['TRAVEL','RU'],ЯЗЫК:['LANGUAGE','RU'],ПОМОЩЬ:['HELP','RU'],PAUSE:['BREAK','DE'],ENDE:['END','DE'],SPRACHE:['LANGUAGE','DE'],HILFE:['HELP','DE'],PRZERWA:['BREAK','PL'],WRÓCIŁEM:['RESUME','PL'],KONIEC:['END','PL'],JĘZYK:['LANGUAGE','PL'],POMOC:['HELP','PL'],PERTRAUKA:['BREAK','LT'],GRĮŽAU:['RESUME','LT'],BAIGTI:['END','LT'],KALBA:['LANGUAGE','LT'],PAGALBA:['HELP','LT']};
  const match=aliases[value];return match?{command:match[0],language:match[1]}:undefined;
}
