import {describe,expect,it} from 'vitest';
import {zodToJsonSchema} from 'zod-to-json-schema';
import {commerceCommands} from '../packages/domain/commerce.js';
import {AUTOMATION_CRON_PATTERN,automationScheduleDue,parseAutomationCron,validateAutomationSchedule} from '../packages/domain/automation-schedule.js';
import {authorizeAutomationRule,type AutomationAuthorityHost,type AutomationPermission} from '../packages/domain/automation-authority.js';
import {DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.js';

const now='2026-10-06T12:00:00.000Z';
const actor:Actor={userId:'operator',companyId:'synthetic-company',roles:['OPERATIONS_MANAGER'],permissions:['automation.manage','automation.approve'],siteIds:['site'],customerIds:[],warehouseIds:[],mfaVerified:true};
const base={name:'Synthetic bounded reminder',trigger:'synthetic.event',filters:{critical:true},action:'CREATE_DECISION',ownerId:actor.userId,scope:{siteIds:[],customerIds:[]},activeFrom:'2026-01-01T00:00:00.000Z'};
class ScheduleTransaction implements Transaction {
 companyId=actor.companyId;rows=new Map<string,Entity>();mutations:string[]=[];sequence=0;
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const row=this.rows.get(`${kind}:${id}`);if(!row||row.companyId!==actor.companyId)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(row) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.rows.values()].filter(row=>row.kind===kind&&row.companyId===actor.companyId).map(row=>structuredClone(row) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`${kind}-${++this.sequence}`):Promise<Entity<T>>{this.mutations.push(`add:${kind}`);const row={id,kind,companyId:actor.companyId,data:structuredClone(data),version:1,createdAt:now,updatedAt:now};this.rows.set(`${kind}:${id}`,row);return structuredClone(row);}
 async save(row:Entity,data:Data,expectedVersion=row.version):Promise<Entity>{const current=await this.get(row.kind,row.id);if(current.version!==expectedVersion)throw new DomainError('VERSION_CONFLICT');this.mutations.push(`save:${row.kind}`);const next={...current,data:structuredClone(data),version:current.version+1,updatedAt:now};this.rows.set(`${row.kind}:${row.id}`,next);return structuredClone(next);}
 async event(type:string){this.mutations.push(`outbox:${type}`);}
}
type SyntheticAutomationAuthorization=(rule:Entity)=>Promise<Actor>;
// Explicit in-memory authorization double only for these authored automation
// tests. Real Engine contexts must provide the fresh transaction-bound server hook.
const syntheticAuthorization:SyntheticAutomationAuthorization=async rule=>{if(rule.companyId!==actor.companyId||rule.data.ownerId!==actor.userId)throw new DomainError('ACCESS_DENIED');return {...actor,permissions:['automation.manage','decision.manage','scope.company']};};
function context(tx:Transaction,authorize:SyntheticAutomationAuthorization|null=syntheticAuthorization,authorizeRun:SyntheticAutomationAuthorization|null=authorize===null?null:syntheticAuthorization):CommandContext{return {tx,actor,now,idempotencyKey:'synthetic-schedule-case',...(authorize===null?{}:{authorizeAutomationRule:authorize}),...(authorizeRun===null?{}:{authorizeAutomationRun:authorizeRun}),requireSite:siteId=>{if(!actor.siteIds.includes(siteId))throw new DomainError('ACCESS_DENIED');},requireOwn:userId=>{if(userId!==actor.userId)throw new DomainError('ACCESS_DENIED');}};}
async function command(tx:Transaction,name:string,input:Data,authorize:SyntheticAutomationAuthorization|null=syntheticAuthorization,authorizeRun:SyntheticAutomationAuthorization|null=authorize===null?null:syntheticAuthorization){const definition=commerceCommands[name]!;return definition.handler(context(tx,authorize,authorizeRun),definition.schema.parse(input));}
const reproducedUnsupported=['* * * * *','0 18 1 * *','0 18 * * 7','0 18 * * 9','not a cron',''];

describe('bounded automation schedule parser and real Berlin instants',()=>{
 it.each(['0 0 * * *','59 23 * * *','0 18 * * 0','0 18 * * 6','00 09 * * 1'])('accepts supported boundary %s',cron=>{const parsed=parseAutomationCron(cron);expect(parsed.timeZone).toBe('Europe/Berlin');expect(parsed.minute).toBeGreaterThanOrEqual(0);expect(parsed.minute).toBeLessThanOrEqual(59);expect(parsed.hour).toBeLessThanOrEqual(23);expect(AUTOMATION_CRON_PATTERN.test(parsed.cron)).toBe(true);});
 it('canonicalizes harmless whitespace without widening schedule grammar',()=>{expect(parseAutomationCron(' \t00\t09  * * 1\n')).toEqual({cron:'00 09 * * 1',minute:0,hour:9,weekday:1,timeZone:'Europe/Berlin'});});
 it('rejects malformed, ranged, stepped, monthly and out-of-bound values with the typed domain error',()=>{
  for(const cron of [...reproducedUnsupported,'60 0 * * *','0 24 * * *','-1 0 * * *','1.5 0 * * *','000 0 * * *','0 000 * * *','0 18 * * -1','0 18 * * 06','0 18 * * 1,2','0 18 * * 1-5','*/5 18 * * *','0 18 * 1 *','0 18 * * * *',' '.repeat(101)+'0 18 * * *',null,undefined,18,{}]){expect(()=>parseAutomationCron(cron)).toThrowError(DomainError);expect(()=>parseAutomationCron(cron)).toThrow('AUTOMATION_SCHEDULE_UNSUPPORTED');}
 });
 it('matches daily local time in summer and winter rather than fixing a UTC hour',()=>{expect(automationScheduleDue('0 18 * * *',new Date('2026-07-06T16:00:00Z'))).toBe(true);expect(automationScheduleDue('0 18 * * *',new Date('2026-01-06T17:00:00Z'))).toBe(true);expect(automationScheduleDue('0 18 * * *',new Date('2026-07-06T17:00:00Z'))).toBe(false);});
 it('accepts Sunday zero and Saturday six but never aliases an unsupported weekday',()=>{expect(automationScheduleDue('0 18 * * 0',new Date('2026-07-05T16:00:00Z'))).toBe(true);expect(automationScheduleDue('0 18 * * 6',new Date('2026-07-04T16:00:00Z'))).toBe(true);expect(automationScheduleDue('0 18 * * 1',new Date('2026-07-05T16:00:00Z'))).toBe(false);expect(()=>automationScheduleDue('0 18 * * 7',new Date('2026-07-05T16:00:00Z'))).toThrow('AUTOMATION_SCHEDULE_UNSUPPORTED');});
 it('uses real DST wall times: nonexistent spring hour does not fire and repeated autumn hour matches both instants',()=>{for(const instant of ['2026-03-29T00:30:00Z','2026-03-29T01:30:00Z'])expect(automationScheduleDue('30 2 * * 0',new Date(instant))).toBe(false);for(const instant of ['2026-10-25T00:30:00Z','2026-10-25T01:30:00Z'])expect(automationScheduleDue('30 2 * * 0',new Date(instant))).toBe(true);});
 it('matches midnight as hour zero and rejects an invalid scheduler instant',()=>{expect(automationScheduleDue('0 0 * * 0',new Date('2026-07-04T22:00:00Z'))).toBe(true);expect(()=>automationScheduleDue('0 18 * * *',new Date('invalid'))).toThrow('AUTOMATION_SCHEDULE_UNSUPPORTED');});
 it('keeps event-only rules compatible and rejects wrong timezone or malformed stored schedule objects',()=>{expect(validateAutomationSchedule(undefined)).toBeUndefined();expect(validateAutomationSchedule({})).toEqual({timezone:'Europe/Berlin'});expect(validateAutomationSchedule({timezone:'Europe/Berlin'})).toEqual({timezone:'Europe/Berlin'});for(const schedule of [null,[],false,{timezone:'UTC',cron:'0 18 * * *'},{cron:'0 18 * * *',arbitrary:true},{cron:null}])expect(()=>validateAutomationSchedule(schedule)).toThrow('AUTOMATION_SCHEDULE_UNSUPPORTED');});
});

describe('commerce automation authorization boundary before all effects',()=>{
 const event={id:'fresh-event',type:'synthetic.event',data:{critical:true}};
 const deny:SyntheticAutomationAuthorization=async()=>{throw new DomainError('ACCESS_DENIED',{reason:'SYNTHETIC_OWNER_REVOKED'});};
 async function existing(tx:ScheduleTransaction,status='ACTIVE',patch:Data={}){const input=commerceCommands['automation_rule.create']!.schema.parse(base);return tx.add('automation_rule',{...input,status,ruleVersion:1,approvedBy:actor.userId,...patch});}
 it('missing server authorization hook denies creation before persisting an owner-selected rule',async()=>{const tx=new ScheduleTransaction();await expect(command(tx,'automation_rule.create',base,null)).rejects.toMatchObject({code:'ACCESS_DENIED',details:{reason:'AUTOMATION_AUTHORIZATION_REQUIRED'}});expect(tx.rows.size).toBe(0);expect(tx.mutations).toEqual([]);});
 it('creation checks a server-built DRAFT candidate before any write and cannot assign an unauthorized owner string',async()=>{const tx=new ScheduleTransaction(),seen:Entity[]=[];const authorize:SyntheticAutomationAuthorization=async candidate=>{seen.push(structuredClone(candidate));expect(tx.mutations).toEqual([]);return syntheticAuthorization(candidate);};await expect(command(tx,'automation_rule.create',{...base,ownerId:'unauthorized-owner'},authorize)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(seen).toHaveLength(1);expect(seen[0]).toMatchObject({id:'automation-rule-candidate',kind:'automation_rule',companyId:actor.companyId,version:1,createdAt:now,data:{status:'DRAFT',ruleVersion:1,createdBy:actor.userId,ownerId:'unauthorized-owner'}});expect(tx.mutations).toEqual([]);});
 it.each(['automation_rule.preview','automation_rule.activate','automation_rule.run'])('%s fails closed without the authoritative callback',async name=>{const tx=new ScheduleTransaction(),row=await existing(tx,name.endsWith('preview')?'DRAFT':name.endsWith('activate')?'PREVIEWED':'ACTIVE');const before=structuredClone(tx.rows);tx.mutations=[];const input=name.endsWith('preview')?{id:row.id,events:[event]}:name.endsWith('run')?{id:row.id,event}:{id:row.id};await expect(command(tx,name,input,null)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it.each(['REMIND','CREATE_DECISION','DRAFT_REPORT','DRAFT_QUOTE','PROPOSE_CREW','DETECT_SHORTAGE'])('revoked owner for %s denies runs, inline decisions and queued actions before mutations',async action=>{const tx=new ScheduleTransaction(),row=await existing(tx,'ACTIVE',{action});const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event},deny)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);expect(await tx.list('automation_run')).toEqual([]);expect(await tx.list('decision')).toEqual([]);});
 it('previewed rules recheck owner authority again at activation and leave prior preview intact on revocation',async()=>{const tx=new ScheduleTransaction(),row=await command(tx,'automation_rule.create',base);await command(tx,'automation_rule.preview',{id:row.id,events:[event]});const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.activate',{id:row.id},deny)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it('rejects a callback result bound to a different owner or company even if it claims broad privileges',async()=>{for(const badOwner of [{...actor,userId:'different-owner'},{...actor,companyId:'different-company'}]){const tx=new ScheduleTransaction(),row=await existing(tx),before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event},async()=>badOwner)).rejects.toMatchObject({code:'ACCESS_DENIED',details:{reason:'AUTOMATION_OWNER_AUTHORIZATION_MISMATCH'}});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);}});
 it('authorized CREATE_DECISION stays idempotent but retries require fresh authorization before returning a historic run',async()=>{const tx=new ScheduleTransaction(),row=await existing(tx),seen:Entity[]=[];const authorize:SyntheticAutomationAuthorization=async rule=>{seen.push(structuredClone(rule));return syntheticAuthorization(rule);};const first=await command(tx,'automation_rule.run',{id:row.id,event},authorize);expect(first.data.status).toBe('COMPLETED');expect(await tx.list('decision')).toHaveLength(1);const second=await command(tx,'automation_rule.run',{id:row.id,event},authorize);expect(second.id).toBe(first.id);expect(seen).toHaveLength(2);expect(seen.every(rule=>rule.id===row.id&&rule.version===row.version)).toBe(true);const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event},deny)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);expect(await tx.list('decision')).toHaveLength(1);});
 it('a fresh authorized rule cannot return a prior run without separately authorizing that exact stored copy',async()=>{const tx=new ScheduleTransaction(),row=await existing(tx),first=await command(tx,'automation_rule.run',{id:row.id,event});await tx.save(await tx.get('automation_rule',row.id),{...row.data,parameters:{privateCopy:'changed-after-original-run'}});const before=structuredClone(tx.rows);let priorChecks=0;const deniedRun:SyntheticAutomationAuthorization=async prior=>{priorChecks++;expect(prior.id).toBe(first.id);expect(prior.version).toBe(first.version);expect(prior.data.parameters).toEqual({});throw new DomainError('ACCESS_DENIED');};for(const runHook of [null,deniedRun,async()=>({...actor,userId:'different-owner'})]){tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event},syntheticAuthorization,runHook)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);}expect(priorChecks).toBe(1);expect(await tx.list('decision')).toHaveLength(1);expect(await tx.list('automation_run')).toHaveLength(1);});
 it('queued action is emitted only after fresh authorization, and revoked replay cannot acknowledge its prior run',async()=>{const tx=new ScheduleTransaction(),row=await existing(tx,'ACTIVE',{action:'REMIND'});let authorized=false;const authorize:SyntheticAutomationAuthorization=async rule=>{expect(tx.mutations).toEqual([]);authorized=true;return syntheticAuthorization(rule);};tx.mutations=[];const first=await command(tx,'automation_rule.run',{id:row.id,event},authorize);expect(authorized).toBe(true);expect(first.data.status).toBe('QUEUED');expect(tx.mutations).toEqual(['add:automation_run','outbox:automation.action_requested']);const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event},deny)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it('event site/customer outside the declared scope cannot produce inline decisions',async()=>{for(const data of [{critical:true,siteId:'outside',customerId:'customer'},{critical:true,siteId:'site',customerId:'outside'}]){const tx=new ScheduleTransaction(),row=await existing(tx,'ACTIVE',{scope:{siteIds:['site'],customerIds:['customer']}}),before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event:{...event,data}})).rejects.toMatchObject({code:'ACCESS_DENIED',details:{reason:'AUTOMATION_EVENT_OUTSIDE_SCOPE'}});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);}});
 it('an order from another site/customer cannot be disguised by allowed event identifiers',async()=>{for(const orderData of [{siteId:'outside',customerId:'customer'},{siteId:'site',customerId:'outside'},{customerId:'customer'}]){const tx=new ScheduleTransaction(),row=await existing(tx,'ACTIVE',{scope:{siteIds:['site'],customerIds:['customer']}});await tx.add('order',orderData,'private-order');const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event:{...event,data:{critical:true,siteId:'site',customerId:'customer',orderId:'private-order'}}})).rejects.toMatchObject({code:'ACCESS_DENIED',details:{reason:'AUTOMATION_ORDER_OUTSIDE_SCOPE'}});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);}});
 it('even global rules require event identifiers to agree with the current referenced order',async()=>{const tx=new ScheduleTransaction(),row=await existing(tx);await tx.add('order',{siteId:'actual-site',customerId:'actual-customer'},'order');const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event:{...event,data:{critical:true,siteId:'invented-site',customerId:'actual-customer',orderId:'order'}}})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it('foreign-company orders remain unavailable even under an explicitly authorized synthetic owner',async()=>{const tx=new ScheduleTransaction(),row=await existing(tx),foreign=await tx.add('order',{siteId:'site',customerId:'customer'},'foreign-order');tx.rows.set('order:foreign-order',{...foreign,companyId:'foreign-company'});const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event:{...event,data:{critical:true,orderId:'foreign-order'}}})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it('malformed event reference IDs are rejected before any business write',async()=>{for(const data of [{critical:true,siteId:15},{critical:true,customerId:null},{critical:true,orderId:[]}]){const tx=new ScheduleTransaction(),row=await existing(tx),before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.run',{id:row.id,event:{...event,data}})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);}});
 it('a valid scoped order can create exactly one decision with the actual bound references',async()=>{const tx=new ScheduleTransaction(),row=await existing(tx,'ACTIVE',{scope:{siteIds:['site'],customerIds:['customer']}});await tx.add('order',{siteId:'site',customerId:'customer'},'order');const run=await command(tx,'automation_rule.run',{id:row.id,event:{...event,data:{critical:true,siteId:'site',customerId:'customer',orderId:'order'}}});expect(run.data.status).toBe('COMPLETED');const decisions=await tx.list('decision');expect(decisions).toHaveLength(1);expect(decisions[0]!.data).toMatchObject({siteId:'site',orderId:'order',ownerId:actor.userId,sources:[event.id]});});
 it('composes actual fresh-owner authority with commerce and denies permission/site removal before new effects or historical acknowledgement',async()=>{
  const tx=new ScheduleTransaction();await tx.add('site',{active:true,customerId:'customer'},'site');await tx.add('customer',{active:true},'customer');
  await tx.add('user',{active:true,roles:['OPERATIONS_MANAGER'],permissions:['automation.manage','automation.approve','automation.execute','scope.company'],siteIds:[],customerIds:[]},actor.userId);
  await tx.add('user',{active:true,roles:['OPERATIONS_MANAGER'],permissions:['automation.manage','decision.manage'],siteIds:['site'],customerIds:['customer']},'business-owner');
  const host:AutomationAuthorityHost<ScheduleTransaction>={actorIn:async(current,userId)=>{const user=await current.get('user',userId);return {...actor,userId,roles:user.data.roles,permissions:user.data.permissions,siteIds:user.data.siteIds,customerIds:user.data.customerIds};},scope:current=>current};
  let permission:AutomationPermission='automation.manage';const hook:SyntheticAutomationAuthorization=rule=>authorizeAutomationRule(tx,rule,host,{initiator:actor,initiatorPermission:permission,allowCandidate:permission==='automation.manage'&&rule.id==='automation-rule-candidate'});
  const row=await command(tx,'automation_rule.create',{...base,ownerId:'business-owner',scope:{siteIds:['site'],customerIds:['customer']}},hook);await command(tx,'automation_rule.preview',{id:row.id,events:[]},hook);permission='automation.approve';await command(tx,'automation_rule.activate',{id:row.id},hook);
  permission='automation.execute';const scopedEvent={...event,data:{critical:true,siteId:'site',customerId:'customer'}};const first=await command(tx,'automation_rule.run',{id:row.id,event:scopedEvent},hook);expect(first.data.status).toBe('COMPLETED');expect(await tx.list('decision')).toHaveLength(1);
  for(const change of [{permissions:['automation.manage']},{permissions:['automation.manage','decision.manage'],siteIds:[]},{permissions:['automation.manage','decision.manage'],siteIds:['site'],active:false}]){
   const owner=await tx.get('user','business-owner');await tx.save(owner,{...owner.data,...change});const before=structuredClone(tx.rows);tx.mutations=[];
   for(const currentEvent of [scopedEvent,{...scopedEvent,id:'new-event'}])await expect(command(tx,'automation_rule.run',{id:row.id,event:currentEvent},hook)).rejects.toMatchObject({code:'ACCESS_DENIED'});
   expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);expect(await tx.list('decision')).toHaveLength(1);expect(await tx.list('automation_run')).toHaveLength(1);
  }
 });
});

describe('actual automation create/preview/activation regression',()=>{
 it.each(reproducedUnsupported)('rejects reproduced unsupported %j before any aggregate or outbox write',async cron=>{const tx=new ScheduleTransaction();await expect(command(tx,'automation_rule.create',{...base,schedule:{cron}})).rejects.toMatchObject({code:'AUTOMATION_SCHEDULE_UNSUPPORTED'});expect(tx.rows.size).toBe(0);expect(tx.mutations).toEqual([]);});
 it('also guards direct create-handler callers before persistence',async()=>{const tx=new ScheduleTransaction();await expect(commerceCommands['automation_rule.create']!.handler(context(tx),{...base,schedule:{cron:'0 18 * * 9'}})).rejects.toMatchObject({code:'AUTOMATION_SCHEDULE_UNSUPPORTED'});expect(tx.mutations).toEqual([]);});
 it.each(reproducedUnsupported)('legacy DRAFT %j cannot enter PREVIEWED or produce effects',async cron=>{const tx=new ScheduleTransaction(),row=await tx.add('automation_rule',{...base,schedule:{timezone:'Europe/Berlin',cron},status:'DRAFT',ruleVersion:1});const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.preview',{id:row.id,events:[{id:'event',type:'synthetic.event',data:{critical:true}}]})).rejects.toMatchObject({code:'AUTOMATION_SCHEDULE_UNSUPPORTED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it.each(reproducedUnsupported)('legacy PREVIEWED %j cannot become ACTIVE despite prior preview metadata',async cron=>{const tx=new ScheduleTransaction(),row=await tx.add('automation_rule',{...base,schedule:{timezone:'Europe/Berlin',cron},status:'PREVIEWED',ruleVersion:1,previewedAt:now,previewResults:[]});const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.activate',{id:row.id})).rejects.toMatchObject({code:'AUTOMATION_SCHEDULE_UNSUPPORTED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it('valid create → preview → activate preserves a schedulable exact rule without preview business effects',async()=>{const tx=new ScheduleTransaction(),created=await command(tx,'automation_rule.create',{...base,schedule:{cron:' \t0 18 * * 1 '}});expect(created.data.schedule).toEqual({timezone:'Europe/Berlin',cron:'0 18 * * 1'});const preview=await command(tx,'automation_rule.preview',{id:created.id,events:[{id:'match',type:'synthetic.event',data:{critical:true}},{id:'ignored',type:'synthetic.event',data:{critical:false}}]});expect(preview.results.map((item:Data)=>({matched:item.matched,effects:item.sideEffectsExecuted}))).toEqual([{matched:true,effects:false},{matched:false,effects:false}]);expect(await tx.list('decision')).toEqual([]);expect(await tx.list('automation_run')).toEqual([]);const active=await command(tx,'automation_rule.activate',{id:created.id});expect(active.data).toMatchObject({status:'ACTIVE',approvedBy:actor.userId,schedule:{timezone:'Europe/Berlin',cron:'0 18 * * 1'}});expect(automationScheduleDue(active.data.schedule.cron,new Date('2026-07-06T16:00:00Z'))).toBe(true);expect(tx.mutations.some(item=>item.startsWith('outbox:'))).toBe(false);});
 it('revalidates schedule tampering between a valid preview and activation',async()=>{const tx=new ScheduleTransaction(),row=await command(tx,'automation_rule.create',{...base,schedule:{cron:'0 18 * * *'}});await command(tx,'automation_rule.preview',{id:row.id,events:[]});const previewed=await tx.get('automation_rule',row.id);await tx.save(previewed,{...previewed.data,schedule:{timezone:'UTC',cron:'0 18 * * *'}});const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.activate',{id:row.id})).rejects.toMatchObject({code:'AUTOMATION_SCHEDULE_UNSUPPORTED'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it('still requires preview and leaves a valid DRAFT unchanged when activation is premature',async()=>{const tx=new ScheduleTransaction(),row=await command(tx,'automation_rule.create',{...base,schedule:{cron:'59 23 * * 6'}});const before=structuredClone(tx.rows);tx.mutations=[];await expect(command(tx,'automation_rule.activate',{id:row.id})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});expect(tx.rows).toEqual(before);expect(tx.mutations).toEqual([]);});
 it('absent schedule remains an event-only rule through the entire lifecycle',async()=>{const tx=new ScheduleTransaction(),row=await command(tx,'automation_rule.create',base);await command(tx,'automation_rule.preview',{id:row.id,events:[]});const active=await command(tx,'automation_rule.activate',{id:row.id});expect(active.data.status).toBe('ACTIVE');expect(active.data.schedule).toBeUndefined();});
 it('publishes the bounded cron pattern and explanatory metadata in the actual command API schema',()=>{const schema=zodToJsonSchema(commerceCommands['automation_rule.create']!.schema) as any,cron=schema.properties.schedule.properties.cron;expect(cron.pattern).toBe(AUTOMATION_CRON_PATTERN.source);expect(cron.maxLength).toBe(100);expect(cron.description).toContain('Sunday=0');expect(new RegExp(cron.pattern).test('0 18 * * 9')).toBe(false);expect(new RegExp(cron.pattern).test('59 23 * * 6')).toBe(true);});
});
