import {test,expect,type Page,type Response,type APIRequestContext} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {writeXlsxWorkbook} from '../packages/storage/xlsx.ts';
import {translator} from '../packages/i18n/index.ts';

// Run only against an explicitly synthetic DEMO delivery database. Assertions
// exercise the rendered application, cookies, API, and persisted PostgreSQL data.
const runtimeFailures=new WeakMap<Page,string[]>();
test.beforeEach(async({page,request})=>{
 const failures:string[]=[];runtimeFailures.set(page,failures);
 page.on('pageerror',error=>failures.push(`JavaScript: ${error.stack||error.message}`));
 page.on('response',response=>{const request=response.request();if(['document','script','stylesheet'].includes(request.resourceType())&&!request.serviceWorker()&&request.frame()===page.mainFrame()&&response.status()>=400)failures.push(`HTTP ${response.status()}: ${request.url()}`);});
 page.on('requestfailed',request=>{if(['script','stylesheet'].includes(request.resourceType())&&!request.serviceWorker()&&request.frame()===page.mainFrame()&&request.failure()?.errorText!=='net::ERR_ABORTED')failures.push(`Asset request failed: ${request.url()} (${request.failure()?.errorText})`);});
 const config=await request.get('/api/v1/public/config',{timeout:10_000});expect(config.ok()).toBe(true);
 const body=await config.json();test.skip(body.mode!=='DEMO','Mutation E2E scenarios require an explicit isolated DEMO database.');
 await page.addInitScript(()=>localStorage.setItem('knaba-language','EN'));
});
test.afterEach(async({page},testInfo)=>{const failures=runtimeFailures.get(page)||[];if(failures.length)await testInfo.attach('browser-runtime-errors',{body:JSON.stringify(failures,null,2),contentType:'application/json'});expect(failures,'Navigation, required assets and JavaScript must load without runtime errors.').toEqual([]);});
function assertDocument(response:Response|null,target:string){expect(response,`Document navigation ${target} must return a response.`).not.toBeNull();if(!response)throw Error(`Missing document response: ${target}`);expect(response.ok()||response.status()===304,`Document navigation ${target} returned HTTP ${response.status()}.`).toBe(true);if(response.status()!==304)expect(response.headers()['content-type'],`Document navigation ${target} must serve the application HTML.`).toContain('text/html');}
async function openPage(page:Page,target:string){assertDocument(await page.goto(target),target);}
async function reloadPage(page:Page){assertDocument(await page.reload(),page.url());}
async function demo(page:Page,role:string){
 let response=await page.request.post('/api/v1/auth/demo',{data:{role},timeout:10_000});
 // The isolated suite deliberately signs in as many roles from one host. Honour
 // the real server's one-minute demo throttle rather than weakening it or
 // spoofing an IP. Only one bounded retry is allowed, and recorded in evidence.
 if(response.status()===429){
  const limited=await response.json();expect(limited.code).toBe('RATE_LIMITED');
  const retryAfter=limited.details?.retryAfterSeconds;
  expect(Number.isInteger(retryAfter)&&retryAfter>0&&retryAfter<=60,'A throttled demo login must provide a bounded retry interval.').toBe(true);
  const waitMs=retryAfter*1000+500;
  test.info().setTimeout(test.info().timeout+waitMs+10_000);
  test.info().annotations.push({type:'auth-rate-limit',description:`Honoured server demo-login cooldown: ${retryAfter}s before one retry (${role}).`});
  await new Promise(resolve=>setTimeout(resolve,waitMs));
  response=await page.request.post('/api/v1/auth/demo',{data:{role},timeout:10_000});
 }
 expect(response.ok(),await response.text()).toBe(true);const body=await response.json();await openPage(page,'/console');await expect(page.locator('.sidebar')).toBeVisible();return body;
}
async function command(request:APIRequestContext,name:string,input:unknown,expected_version?:number){const me=await request.get('/api/v1/me');expect(me.ok()).toBe(true);const session=await me.json();const r=await request.post(`/api/v1/commands/${name}`,{headers:{'X-CSRF-Token':session.csrfToken},data:{input,expected_version,idempotency_key:randomUUID()}});expect(r.ok(),`${name}: ${await r.text()}`).toBe(true);return r.json();}
async function navigate(page:Page,name:string){const toggle=page.locator('.topbar .mobile-only');if(await toggle.isVisible())await toggle.click();await page.locator('.sidebar nav').getByRole('button',{name,exact:true}).click();await expect(page.locator('.page-heading h1')).toHaveText(name);}
async function saveForm(page:Page){const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Review change',exact:true}).click();await dialog.getByRole('button',{name:'Confirm & execute',exact:true}).click();await expect(dialog.locator('.success-state')).toBeVisible();await dialog.getByRole('button',{name:'Completed',exact:true}).click();}
async function noOverflow(page:Page){
 const dimensions=await page.evaluate(()=>({width:window.innerWidth,scrollWidth:document.documentElement.scrollWidth,offenders:Array.from(document.querySelectorAll('body *')).flatMap(element=>{const r=element.getBoundingClientRect(),style=getComputedStyle(element);return style.display!=='none'&&style.visibility!=='hidden'&&r.width>0&&r.right>window.innerWidth+1?[{tag:element.tagName,className:element.getAttribute('class'),right:Math.round(r.right),width:Math.round(r.width)}]:[]}).slice(0,30)}));
 if(dimensions.scrollWidth>dimensions.width+1)await test.info().attach('document-overflow',{body:JSON.stringify(dimensions,null,2),contentType:'application/json'});
 expect(dimensions.scrollWidth,JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.width+1);
}

test('public entry supports all six languages at 360 px without document overflow',async({page})=>{
 await page.setViewportSize({width:360,height:800});await openPage(page,'/');
 for(const code of ['DE','UK','RU','PL','LT','EN']){await page.locator('.language-select select').selectOption(code);await expect(page.locator('html')).toHaveAttribute('lang',code.toLowerCase());await expect(page.locator('.public-copy h1')).not.toHaveText('');await noOverflow(page);}
 await page.screenshot({path:'docs/evidence/public-360.png',fullPage:true});
});
test('rendered demo login and canonical role landings are usable',async({page})=>{
 await openPage(page,'/login');await page.locator('.demo-login select').selectOption('EMPLOYEE');await page.locator('.demo-login').getByRole('button',{name:'Sign in · DEMO'}).click();await expect(page).toHaveURL(/\/console$/);await expect(page.locator('.shift-card')).toBeVisible();
 const roles=[['OWNER','Decision centre'],['DIRECTOR','Decision centre'],['INTERNAL_BAULEITER','Sites & locations'],['STOREKEEPER','Inventory & materials'],['ACCOUNTANT','Pay & payouts'],['CLIENT','My orders']];
 for(const [role,heading]of roles){await demo(page,role);await expect(page.locator('.page-heading h1')).toHaveText(heading);}
 const nav=page.locator('.sidebar nav');await expect(nav.getByRole('button',{name:'My orders',exact:true})).toBeVisible();await expect(nav.getByRole('button',{name:'Pay & payouts',exact:true})).toHaveCount(0);await expect(nav.getByRole('button',{name:'Administration',exact:true})).toHaveCount(0);
 await expect(nav.getByRole('button',{name:'Privacy & security',exact:true})).toBeVisible();expect((await nav.getByRole('button').allTextContents()).map(text=>text.trim()).sort()).toEqual(['My orders','Reports & media','Team communication','Privacy & security'].sort());
});
test('real credentials authenticate and logout revokes the cookie session',async({page})=>{
 await openPage(page,'/login');await page.getByLabel('Email',{exact:true}).fill('demo-employee@example.invalid');await page.getByLabel('Password',{exact:true}).fill('KNABA synthetic local demo password');await page.locator('.login-box form').getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/console$/);await expect(page.locator('.shift-card')).toBeVisible();
 await page.locator('.profile').click();await expect(page).toHaveURL(/\/login$/);expect((await page.request.get('/api/v1/me')).status()).toBe(401);
});
test('manual shift start, private break, resume and end persist after page reload',async({page})=>{
 await demo(page,'EMPLOYEE');const current=(await (await page.request.get('/api/v1/entities/shift')).json()).items.find((s:any)=>s.data.state==='ACTIVE');if(current)await command(page.request,'shift.end',{shiftId:current.id,description:'Synthetic QA cleanup'});
 await reloadPage(page);await page.locator('.shift-actions').getByRole('button',{name:'Start shift',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('combobox',{name:/^Site/}).selectOption('site-a');await saveForm(page);await expect(page.locator('.shift-actions').getByRole('button',{name:'End shift',exact:true})).toBeVisible();
 await page.locator('.shift-actions').getByRole('button',{name:'Break',exact:true}).click();await saveForm(page);await expect(page.locator('.shift-actions').getByRole('button',{name:'Resume work',exact:true})).toBeVisible();
 await page.locator('.shift-actions').getByRole('button',{name:'Resume work',exact:true}).click();await saveForm(page);await page.locator('.shift-actions').getByRole('button',{name:'End shift',exact:true}).click();await saveForm(page);await reloadPage(page);await expect(page.locator('.shift-actions').getByRole('button',{name:'Start shift',exact:true})).toBeVisible();
 const shifts=(await (await page.request.get('/api/v1/entities/shift')).json()).items;const latest=shifts.at(-1);expect(latest.data.state).toBe('ENDED');expect(latest.data.summary.breakSeconds).toBeGreaterThanOrEqual(0);
});
test('task form creates a persisted task and mobile modal fits 360 px',async({page})=>{
 await demo(page,'DIRECTOR');await page.setViewportSize({width:360,height:800});await navigate(page,'Tasks');await page.locator('.heading-actions').getByRole('button',{name:'Create new',exact:true}).click();const dialog=page.getByRole('dialog');const title=`QA browser task ${randomUUID()}`;await dialog.getByRole('combobox',{name:/^Site/}).selectOption('site-a');await dialog.locator('#field-title').fill(title);await noOverflow(page);await page.screenshot({path:'docs/evidence/task-form-360.png',fullPage:true});await saveForm(page);await reloadPage(page);await navigate(page,'Tasks');await page.locator('#global-search').fill(title);await expect(page.locator('.record-link').filter({hasText:title})).toBeVisible();
});
test('team chat sends original text and reads the persisted message after reload',async({page})=>{
 await demo(page,'EMPLOYEE');await navigate(page,'Team communication');await page.locator('.channel-list').getByRole('button',{name:/KNB-014/}).click();const text=`QA original EN ${randomUUID()}`;await page.getByRole('textbox',{name:'Message',exact:true}).fill(text);await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.message-bubble').filter({hasText:text})).toBeVisible();await reloadPage(page);await navigate(page,'Team communication');await page.locator('.channel-list').getByRole('button',{name:/KNB-014/}).click();await expect(page.locator('.message-bubble').filter({hasText:text})).toBeVisible();await page.screenshot({path:'docs/evidence/team-chat-desktop.png',fullPage:true});
});
test('private photo upload validates bytes, registers site context and permits file retrieval',async({page})=>{
 await demo(page,'EMPLOYEE');const png=(await sharp({create:{width:240,height:160,channels:3,background:{r:35,g:109,b:85}}}).png().toBuffer()).toString('base64');const me=await (await page.request.get('/api/v1/me')).json();const upload=await page.request.post('/api/v1/media/upload',{headers:{'X-CSRF-Token':me.csrfToken},data:{base64:png,mimeType:'image/png',fileName:'synthetic-test.png',redactionConfirmed:false}});expect(upload.ok(),await upload.text()).toBe(true);const u=await upload.json();expect(u.metadataStripped).toBe(true);
 const asset=await command(page.request,'media.register',{uploadId:u.uploadId,siteId:'site-a',stage:'AFTER',visibility:'INTERNAL',caption:'Synthetic QA image',retentionPurpose:'Synthetic release QA'});const image=await page.request.get(`/api/v1/media/${asset.id}/file`);expect(image.ok()).toBe(true);expect(image.headers()['content-type']).toMatch(/^image\/png/);expect((await image.body()).length).toBeGreaterThan(0);await navigate(page,'Reports & media');await page.getByRole('tab',{name:/Reports & media/}).last().click();await expect(page.locator('.record-link').filter({hasText:asset.id})).toBeVisible();
});
test('public contact and guest chat persist privately with honest manual fallback',async({page,browser})=>{
 await openPage(page,'/');await page.getByRole('button',{name:/New customer/}).click();const form=page.getByRole('dialog');const suffix=randomUUID();await form.getByLabel(/Your name/).fill(`QA guest ${suffix}`);await form.getByLabel(/Email/).fill(`qa-${suffix}@example.invalid`);await form.getByLabel(/How can we help/).fill('Synthetic QA request only');await form.getByRole('checkbox').check();await form.getByRole('button',{name:'Send',exact:true}).click();await expect(form.locator('.success-state')).toBeVisible();await form.getByRole('button',{name:'Completed',exact:true}).click();await page.getByRole('button',{name:'Start webchat',exact:true}).click();const text=`QA private guest ${randomUUID()}`;await page.getByRole('dialog').getByLabel('Message',{exact:true}).fill(text);
 const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/public/chat')&&r.request().method()==='POST');await page.getByRole('dialog').getByRole('button',{name:'Send',exact:true}).click();const body=await (await response).json();expect(['MANUAL_FALLBACK','HANDOFF_PENDING']).toContain(body.status);await expect(page.locator('.public-chat-message').filter({hasText:text})).toBeVisible();
 const other=await browser.newContext({baseURL:process.env.E2E_BASE_URL??'http://127.0.0.1:3000'});try{const denied=await other.request.get(`/api/v1/public/chat/${body.channelId}/messages`);expect([401,404]).toContain(denied.status());expect(await denied.text()).not.toContain(text);}finally{await other.close();}
});
test('transport fixture: guest lead draft requires current review and explicit CSRF-bound confirmation',async({page},testInfo)=>{
 // Guest creation and history authentication use the real isolated backend.
 // Only the AI proposal/history decoration and confirmation response are mocked;
 // this proves browser gating, not provider or backend draft authorization.
 testInfo.annotations.push({type:'transport-fixture',description:'AI draft and confirmation response mocked; real guest bootstrap/history authentication.'});
 await page.clock.install();
 const draftId=`qa-ui-draft-${randomUUID()}`;
 let draft={id:draftId,version:3,state:'DRAFT',previewHash:'a'.repeat(64),preview:{territory:'Berlin',contact:{name:'Synthetic draft guest',email:'ui-draft@example.invalid'},serviceIds:['synthetic-service'],language:'EN',facts:{description:'Synthetic UI review fixture',quantityMilli:100000}}};
 let confirmed=false,historyReads=0,expectedGuestCsrf:string|undefined;
 const confirmations:{url:string;method:string;body:unknown;csrfMatches:boolean}[]=[];
 await page.route('**/api/v1/public/chat/*/messages',async route=>{
  const actual=await route.fetch();expect(actual.ok(),'History must authenticate through the actual guest cookie.').toBe(true);
  const body=await actual.json();historyReads++;
  await route.fulfill({response:actual,json:{...body,pendingDrafts:confirmed?[]:[draft]}});
 });
 await page.route('**/api/v1/public/chat/*/drafts/*/confirm',async route=>{
  const req=route.request();confirmations.push({url:req.url(),method:req.method(),body:req.postDataJSON(),csrfMatches:typeof expectedGuestCsrf==='string'&&req.headers()['x-csrf-token']===expectedGuestCsrf});confirmed=true;
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({status:'CONFIRMED',leadId:'synthetic-ui-fixture-lead'})});
 });
 await openPage(page,'/');await page.getByRole('button',{name:'Start webchat',exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.getByLabel('Message',{exact:true}).fill('Synthetic UI draft test; no real AI provider.');
 const sent=page.waitForResponse(r=>r.url().endsWith('/api/v1/public/chat')&&r.request().method()==='POST');
 await dialog.getByRole('button',{name:'Send',exact:true}).click();const response=await sent;expect(response.ok(),await response.text()).toBe(true);const guest=await response.json();expect(guest.csrfToken).toEqual(expect.any(String));expectedGuestCsrf=guest.csrfToken;
 const card=dialog.locator('.public-lead-draft');await expect(card).toBeVisible();expect(historyReads).toBeGreaterThan(0);expect(confirmations).toEqual([]);await expect(card.getByRole('button',{name:'Confirm enquiry',exact:true})).toHaveCount(0);
 await card.getByRole('button',{name:'Review enquiry',exact:true}).click();await expect(card.locator('.public-draft-summary').first()).toContainText('Berlin');await expect(card).toContainText('Synthetic draft guest');await expect(card.getByRole('button',{name:'Confirm enquiry',exact:true})).toBeVisible();expect(confirmations).toEqual([]);
 draft={...draft,version:4,previewHash:'b'.repeat(64),preview:{...draft.preview,territory:'Potsdam'}};
 await page.clock.fastForward(10_001);
 await expect(card.getByRole('button',{name:'Confirm enquiry',exact:true})).toHaveCount(0);await expect(card.getByRole('button',{name:'Review enquiry',exact:true})).toBeVisible();expect(confirmations).toEqual([]);
 await card.getByRole('button',{name:'Review enquiry',exact:true}).click();await expect(card.locator('.public-draft-summary').first()).toContainText('Potsdam');expect(confirmations).toEqual([]);
 await card.getByRole('button',{name:'Confirm enquiry',exact:true}).click();await expect(dialog.locator('.public-draft-confirmed')).toBeVisible();await expect(card).toHaveCount(0);
 expect(confirmations).toHaveLength(1);const confirmation=confirmations[0]!;expect({url:confirmation.url,method:confirmation.method,body:confirmation.body}).toEqual({url:new URL(`/api/v1/public/chat/${guest.channelId}/drafts/${draftId}/confirm`,page.url()).href,method:'POST',body:{expectedVersion:4,previewHash:'b'.repeat(64)}});expect(confirmation.csrfMatches,'Confirmation must carry the current guest CSRF proof.').toBe(true);
 await testInfo.attach('mocked-draft-gating-scope',{body:JSON.stringify({transportFixture:true,historyReads,confirmationCount:confirmations.length,confirmedVersion:4,realProvider:'NOT_RUN',backendDraftConfirmation:'MOCKED_NOT_VERIFIED'},null,2),contentType:'application/json'});
});
test('mutations reject missing CSRF and CLIENT cannot read internal chat or payroll',async({page})=>{
 await demo(page,'CLIENT');const denied=await page.request.post('/api/v1/commands/report.ack',{data:{input:{},idempotency_key:randomUUID()}});expect(denied.status()).toBe(403);const payroll=await page.request.get('/api/v1/entities/payroll_calculation');expect((await payroll.json()).items).toEqual([]);const channels=await (await page.request.get('/api/v1/entities/channel')).json();expect(channels.items.some((c:any)=>c.data.type==='SITE_INTERNAL')).toBe(false);
});
test('published report PDF CSV XLSX match immutable snapshot and client access',async({page})=>{
 await demo(page,'CLIENT');const versions=await (await page.request.get('/api/v1/entities/report_version')).json();const version=process.env.E2E_REPORT_VERSION_ID?versions.items.find((v:any)=>v.id===process.env.E2E_REPORT_VERSION_ID):versions.items.find((v:any)=>v.data.snapshot.descriptionDe?.includes('SYNTHETISCHER TESTBERICHT'));expect(version,'Run canonical DEMO seed to create the reviewed and published synthetic fixture.').toBeDefined();const id=version.id,snapshot=version.data.snapshot;
 for(const [format,mime]of [['pdf','application/pdf'],['csv','text/csv'],['xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']]){const exported=await page.request.get(`/api/v1/reports/${id}/${format}`);expect(exported.ok(),await exported.text()).toBe(true);expect(exported.headers()['content-type']).toContain(mime);const bytes=await exported.body();expect(bytes.length).toBeGreaterThan(100);if(format==='pdf')expect(bytes.subarray(0,4).toString()).toBe('%PDF');if(format==='csv'){expect(bytes.toString()).toContain(String(snapshot.totalGrossCents));expect(bytes.toString()).toContain(version.data.sha256);}if(format==='xlsx')expect(bytes.subarray(0,2).toString()).toBe('PK');}
 await navigate(page,'Reports & media');await page.screenshot({path:'docs/evidence/client-reports-desktop.png',fullPage:true});
});
test('manual inventory SKU lookup works without camera and shows approved unit conversion',async({page})=>{
 await demo(page,'EMPLOYEE');await navigate(page,'Inventory & materials');await page.locator('.heading-actions').getByRole('button',{name:'Scan material',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Barcode, QR code or SKU',{exact:true}).fill('DEMO-CLEAN-01');await dialog.getByRole('button',{name:'Look up material',exact:true}).click();await expect(dialog.locator('.scan-result')).toBeVisible();await expect(dialog.locator('.scan-result')).toContainText('ml');await expect(dialog.locator('.scan-result code')).toContainText('knaba://material/material-clean');
});
test('client issue form references approved photo, persists original text and opens a review',async({page})=>{
 await demo(page,'CLIENT');await page.locator('.heading-actions').getByRole('button',{name:'Report an issue',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.locator('.issue-photo-grid input[type=checkbox]').first()).toBeVisible();await dialog.locator('.issue-photo-grid input[type=checkbox]').first().check();const text=`QA synthetic client clarification ${randomUUID()}`;await dialog.getByLabel('Description',{exact:false}).fill(text);await dialog.getByRole('button',{name:'Review change',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/commands/issue.create')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Submit',exact:true}).click();const r=await response;expect(r.ok(),await r.text()).toBe(true);const issue=await r.json();expect(issue.data.state).toBe('OPEN');expect(issue.data.description).toBe(text);await expect(dialog.locator('.success-state')).toBeVisible();const persisted=await command(page.request,'issue.get',{id:issue.id});expect(persisted.data.description).toBe(text);expect(JSON.stringify(persisted)).not.toContain('internalReason');
});
test('structure import rejects malformed files, previews CSV and XLSX without writes, and commits reviewed hierarchy',async({page})=>{
 await demo(page,'DIRECTOR');await page.setViewportSize({width:360,height:800});await navigate(page,'Sites & locations');await page.locator('.heading-actions').getByRole('button',{name:'Import structure',exact:true}).click();
 const dialog=page.getByRole('dialog'),form=dialog.locator('.location-import');await form.locator('select').selectOption('site-a');
 const before=(await (await page.request.get('/api/v1/entities/location')).json()).items;
 await form.locator('input[type=file]').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('name,nodeType\nMissing identifier,BUILDING\n')});await form.getByRole('button',{name:'Check file',exact:true}).click();await expect(form.getByRole('alert')).toBeVisible();await expect(form.getByRole('button',{name:'Save import',exact:true})).toHaveCount(0);
 const key=`qa-${randomUUID()}`,headers=['externalKey','parentExternalKey','nodeType','code','name','floorLevel','floorLabelDe'];
 const rows=[[`${key}-house`,'','BUILDING','QA-H','Synthetic QA house','',''],[`${key}-floor`,`${key}-house`,'FLOOR','UG','Synthetic QA basement',-1,'UG']];
 const xlsx=writeXlsxWorkbook({creator:'Synthetic QA',createdAt:new Date().toISOString(),title:'Synthetic hierarchy',subject:'QA fixture',description:'No real customer data',sheets:[{name:'Locations',rows:[headers,...rows]}]});
 await form.locator('input[type=file]').setInputFiles({name:'locations.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:xlsx});await form.getByRole('button',{name:'Check file',exact:true}).click();await expect(form.locator('.import-confirm')).toBeVisible();await expect(form.locator('.import-table tbody tr')).toHaveCount(2);await expect(form.getByRole('button',{name:'Save import',exact:true})).toBeDisabled();
 const csv=[headers,...rows].map(row=>row.join(',')).join('\n')+'\n';await form.locator('input[type=file]').setInputFiles({name:'locations.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await form.getByRole('button',{name:'Check file',exact:true}).click();await expect(form.locator('.import-confirm')).toBeVisible();await expect(form.locator('.import-table')).toContainText('(-1)');
 expect((await (await page.request.get('/api/v1/entities/location')).json()).items).toHaveLength(before.length);await noOverflow(page);await page.screenshot({path:'docs/evidence/location-import-360.png',fullPage:true});await form.locator('.import-confirm input').check();await form.getByRole('button',{name:'Save import',exact:true}).click();await expect(form.locator('.success-state')).toBeVisible();
 const after=(await (await page.request.get('/api/v1/entities/location')).json()).items;const house=after.find((e:any)=>e.data.externalKey===`${key}-house`),floor=after.find((e:any)=>e.data.externalKey===`${key}-floor`);expect(after).toHaveLength(before.length+2);expect(house.data.siteId).toBe('site-a');expect(floor.data).toMatchObject({siteId:'site-a',parentId:house.id,floorLevel:-1,floorLabelDe:'UG'});
});

test('a private guest handoff needs an explicit current operator claim before the original and reply are visible',async({page,browser})=>{
 await openPage(page,'/');await page.getByRole('button',{name:'Start webchat',exact:true}).click();
 const guestDialog=page.getByRole('dialog'),original=`QA private human handoff ${randomUUID()}`;
 await guestDialog.getByLabel('Message',{exact:true}).fill(original);await guestDialog.getByRole('checkbox',{name:'Speak to a person',exact:true}).check();
 const guestSent=page.waitForResponse(r=>r.url().endsWith('/api/v1/public/chat')&&r.request().method()==='POST');
 await guestDialog.getByRole('button',{name:'Send',exact:true}).click();const guestResponse=await guestSent;expect(guestResponse.ok()).toBe(true);const guestResult=await guestResponse.json();expect(guestResult.status).toBe('HANDOFF_PENDING');
 await expect(guestDialog.locator('.public-chat-message').filter({hasText:original})).toBeVisible();
 const operatorContext=await browser.newContext({baseURL:process.env.E2E_BASE_URL??'http://127.0.0.1:3000'});
 try{
  await operatorContext.addInitScript(()=>localStorage.setItem('knaba-language','EN'));const operator=await operatorContext.newPage();await demo(operator,'OWNER');
  const before=(await (await operator.request.get('/api/v1/entities/channel')).json()).items;expect(before.some((channel:any)=>channel.id===guestResult.channelId),'A pending claim cannot confer chat-history access.').toBe(false);
  await navigate(operator,'Operator inbox');const pending=operator.locator('.operator-pending li').filter({hasText:guestResult.channelId});await expect(pending).toBeVisible();await expect(operator.locator('.operator-pending')).not.toContainText(original);
  const inbox=await command(operator.request,'handoff.inbox',{});expect(JSON.stringify(inbox)).not.toContain(original);const offered=inbox.items.find((item:any)=>item.channel_id===guestResult.channelId);expect(offered.version).toEqual(expect.any(Number));
  await pending.getByRole('button',{name:'Claim request',exact:true}).click();const claimDialog=operator.getByRole('dialog');await expect(claimDialog).toContainText(guestResult.channelId);
  expect((await (await operator.request.get('/api/v1/entities/channel')).json()).items.some((channel:any)=>channel.id===guestResult.channelId),'Opening the claim preview performs no membership mutation.').toBe(false);
  const claimed=operator.waitForResponse(r=>r.url().endsWith('/api/v1/commands/handoff.take')&&r.request().method()==='POST');await claimDialog.getByRole('button',{name:'Claim request',exact:true}).click();const claimResponse=await claimed;expect(claimResponse.ok()).toBe(true);expect(claimResponse.request().postDataJSON()).toMatchObject({input:{channel_id:guestResult.channelId},expected_version:offered.version});const claimedChannel=await claimResponse.json();expect(claimedChannel.data.handoff.state).toBe('HUMAN_ACTIVE');
  await expect(claimDialog).toHaveCount(0);await expect(operator.locator('.chat-pane .message-bubble').filter({hasText:original})).toBeVisible();
  const reply=`QA human reply ${randomUUID()}`;await operator.locator('.chat-pane').getByRole('textbox',{name:'Message',exact:true}).fill(reply);const replied=operator.waitForResponse(r=>r.url().endsWith('/api/v1/commands/message.send')&&r.request().method()==='POST');await operator.locator('.chat-pane').getByRole('button',{name:'Send',exact:true}).click();expect((await replied).ok()).toBe(true);
  await expect(guestDialog.locator('.public-chat-message').filter({hasText:reply})).toBeVisible({timeout:15_000});
  const guestHistory=await page.request.get(`/api/v1/public/chat/${guestResult.channelId}/messages`);expect(guestHistory.ok()).toBe(true);const history=await guestHistory.json();expect(history.items.some((item:any)=>item.data.text===original)).toBe(true);expect(history.items.some((item:any)=>item.data.text===reply&&item.data.author_id===claimedChannel.data.handoff.owner_id)).toBe(true);
 }finally{await operatorContext.close();}
});

test('an owned assigned task stays UNSYNCED offline and changes only after an explicit original-key retry acknowledgement',async({page})=>{
 // Observe real UUID generation without replacing randomness or the transport.
 await page.addInitScript(()=>{const actual=crypto.randomUUID.bind(crypto),generated:string[]=[];(window as unknown as {__qaGeneratedCommandKeys:string[]}).__qaGeneratedCommandKeys=generated;crypto.randomUUID=()=>{const value=actual();generated.push(value);return value;};});
 await demo(page,'OWNER');const task=await command(page.request,'task.create',{siteId:'site-a',title:`QA offline owned task ${randomUUID()}`,unit:'UNIT',plannedQuantityMilli:1000,assigneeIds:['demo-employee'],billingScope:'INTERNAL'});expect(task.data.state).toBe('ASSIGNED');
 await demo(page,'EMPLOYEE');await navigate(page,'Tasks');await page.locator('#global-search').fill(task.data.title);await page.locator('.record-link').filter({hasText:task.data.title}).click();const t=translator('EN');await page.getByRole('dialog').locator('.detail-actions').getByRole('button',{name:`${t('start')} · ${t('tasks')}`,exact:true}).click();const dialog=page.getByRole('dialog');
 const taskStarts:unknown[]=[],retryReads:string[]=[];let observeRetry=false;page.on('request',request=>{const path=new URL(request.url()).pathname;if(observeRetry)retryReads.push(`${request.method()} ${path}`);if(path==='/api/v1/commands/task.start'&&request.method()==='POST')taskStarts.push(request.postDataJSON());});
 try{
  await page.context().setOffline(true);await expect(page.locator('.offline-strip')).toBeVisible();await dialog.getByRole('button',{name:'Review change',exact:true}).click();await expect(dialog).toContainText(`${t('version')} ${task.version}`);await dialog.getByRole('button',{name:'Keep as unsynced',exact:true}).click();await expect(dialog.getByRole('status')).toContainText('UNSYNCED');await expect(dialog.locator('.success-state')).toHaveCount(0);
  const generatedBeforeRetry=await page.evaluate(()=>(window as unknown as {__qaGeneratedCommandKeys:string[]}).__qaGeneratedCommandKeys.slice());await dialog.getByRole('button',{name:'Close',exact:true}).click();const queued=page.getByRole('region',{name:'Unsent actions',exact:true}).locator('li');await expect(queued).toHaveAttribute('data-queue-state','UNSYNCED');expect(taskStarts).toEqual([]);
  const unchanged=(await (await page.request.get('/api/v1/entities/task')).json()).items.find((item:any)=>item.id===task.id);expect(unchanged).toMatchObject({version:task.version,data:{state:'ASSIGNED'}});
  await page.context().setOffline(false);await expect(page.locator('.offline-strip')).toHaveCount(0);await expect(queued.getByRole('button',{name:'Retry manually',exact:true})).toBeEnabled();await expect(queued).toHaveAttribute('data-queue-state','UNSYNCED');expect(taskStarts).toEqual([]);
  observeRetry=true;const retryResponse=page.waitForResponse(r=>r.url().endsWith('/api/v1/commands/task.start')&&r.request().method()==='POST');await queued.getByRole('button',{name:'Retry manually',exact:true}).click();const response=await retryResponse;expect(response.ok()).toBe(true);const acknowledged=await response.json();expect(acknowledged).toMatchObject({id:task.id,kind:'task',data:{state:'IN_PROGRESS'}});await expect(queued).toHaveAttribute('data-queue-state','ACKNOWLEDGED');expect(taskStarts).toHaveLength(1);
  const envelope=taskStarts[0] as {input:unknown;expected_version:number;idempotency_key:string};expect(envelope.input).toEqual({taskId:task.id});expect(envelope.expected_version).toBe(task.version);expect(generatedBeforeRetry).toContain(envelope.idempotency_key);const sentIndex=retryReads.indexOf('POST /api/v1/commands/task.start');for(const preflight of ['GET /api/v1/me','GET /api/v1/commands','GET /api/v1/entities/task']){expect(retryReads).toContain(preflight);expect(retryReads.indexOf(preflight)).toBeLessThan(sentIndex);}
  const persisted=(await (await page.request.get('/api/v1/entities/task')).json()).items.find((item:any)=>item.id===task.id);expect(persisted.version).toBe(acknowledged.version);expect(persisted.data.state).toBe('IN_PROGRESS');
 }finally{await page.context().setOffline(false);}
});

test('the scoped empty route sketch fits360px and uses no external maps or browser GPS, including client deep-link denial',async({page})=>{
 await page.addInitScript(()=>{let calls=0;Object.defineProperty(window,'__qaLocationCalls',{get:()=>calls});const once=navigator.geolocation.getCurrentPosition.bind(navigator.geolocation),watch=navigator.geolocation.watchPosition.bind(navigator.geolocation);navigator.geolocation.getCurrentPosition=(...args)=>{calls++;return once(...args)};navigator.geolocation.watchPosition=(...args)=>{calls++;return watch(...args)};});
 await demo(page,'EMPLOYEE');await page.setViewportSize({width:360,height:800});const foreignRequests:string[]=[];const origin=new URL(page.url()).origin;page.on('request',request=>{const url=new URL(request.url());if(['http:','https:'].includes(url.protocol)&&url.origin!==origin)foreignRequests.push(url.origin);});
 await openPage(page,'/app/trips?map=1');const map=page.locator('.route-map');await expect(map).toBeVisible();const samples=await page.request.get('/api/v1/entities/location_sample');expect(samples.ok()).toBe(true);expect((await samples.json()).items).toEqual([]);await expect(map.locator('[data-route-marker="point"]')).toHaveCount(0);await expect(map).toContainText(translator('EN')('routeMap_noRoute'));await map.getByRole('button',{name:'Zoom in',exact:true}).click();await map.getByRole('button',{name:'Reset view',exact:true}).click();await noOverflow(page);const box=await map.locator('svg').boundingBox();expect(box).not.toBeNull();expect(box!.width).toBeGreaterThan(200);expect(box!.x+box!.width).toBeLessThanOrEqual(361);expect(foreignRequests).toEqual([]);expect(await page.evaluate(()=>(window as unknown as {__qaLocationCalls:number}).__qaLocationCalls)).toBe(0);await page.screenshot({path:'docs/evidence/route-map-360.png',fullPage:true});
 await demo(page,'CLIENT');await openPage(page,'/app/trips?map=1');await expect(page.locator('.page-heading h1')).toHaveText('My orders');await expect(page.locator('.route-map')).toHaveCount(0);const denied=await page.request.get('/api/v1/entities/location_sample');expect(denied.ok()).toBe(true);expect((await denied.json()).items).toEqual([]);expect(foreignRequests).toEqual([]);
});

test('an owned shift has an actual read-only working-time advisory with explicit policy and insufficient-history coverage',async({page})=>{
 await demo(page,'EMPLOYEE');const shifts=(await (await page.request.get('/api/v1/entities/shift')).json()).items;for(const current of shifts.filter((item:any)=>item.data.state==='ACTIVE'))await command(page.request,'shift.end',{shiftId:current.id,description:'Synthetic browser advisory cleanup'});
 const shift=await command(page.request,'shift.start',{siteId:'site-a'});
 try{
  await reloadPage(page);const panel=page.locator('.working-time-advisory');await expect(panel).toBeVisible();await panel.locator('select[name="working-time-subject"]').selectOption(`shift:${shift.id}`);const evaluated=page.waitForResponse(r=>r.url().endsWith('/api/v1/commands/shift.working_time_advisory')&&r.request().method()==='POST');await panel.getByTestId('working-time-evaluate').click();const response=await evaluated;expect(response.ok()).toBe(true);const advisory=await response.json();expect(advisory.status).toBe('ADVISORY_ONLY_REQUIRES_LEGAL_REVIEW');expect(advisory.policy.basis).toBe('UNAPPROVED_GENERAL_REGIME_DEFAULTS');expect(Object.values(advisory.effects).every(value=>value===false)).toBe(true);expect(advisory.averaging.every((window:any)=>window.coverage==='INSUFFICIENT_HISTORY'&&window.averageSecondsPerWorkingDay===null)).toBe(true);
  await expect(panel.getByTestId('working-time-result')).toBeVisible();await expect(panel.getByTestId('working-time-legal-review')).not.toHaveText('');await expect(panel.getByTestId('working-time-history')).toHaveCount(2);await expect(panel).toContainText(translator('EN')('advisory_missingHistory'));const after=(await (await page.request.get('/api/v1/entities/shift')).json()).items.find((item:any)=>item.id===shift.id);expect(after).toMatchObject({id:shift.id,version:shift.version,data:{state:'ACTIVE',activity:'WORKING'}});await page.screenshot({path:'docs/evidence/working-time-advisory.png',fullPage:true});
 }finally{await command(page.request,'shift.end',{shiftId:shift.id,description:'Synthetic read-only advisory acceptance complete'});}
});

test('authorized AI usage and explicit SIMULATED playground leave actual business records unchanged without provider execution',async({page})=>{
 await demo(page,'DIRECTOR');const config=await command(page.request,'assistant_config.create',{name:`QA simulated assistant ${randomUUID()}`,escalationContact:'Synthetic operator only',allowedServiceIds:[],territories:['Synthetic Berlin'],provider:'DISABLED',testOnly:true});expect(config.data.status).toBe('DRAFT');
 const businessKinds=['lead','task','material_request','report','quote','channel'];
 async function businessSnapshot(){const result:Record<string,{id:string;version:number}[]>={};for(const kind of businessKinds){const response=await page.request.get(`/api/v1/entities/${kind}`);expect(response.ok()).toBe(true);result[kind]=(await response.json()).items.map((item:any)=>({id:item.id,version:item.version})).sort((a:any,b:any)=>a.id.localeCompare(b.id));}return result;}
 const before=await businessSnapshot();const playgroundRequests:unknown[]=[];page.on('request',request=>{if(request.url().endsWith('/api/v1/commands/assistant.playground')&&request.method()==='POST')playgroundRequests.push(request.postDataJSON());});
 const usageResponse=page.waitForResponse(r=>r.url().endsWith('/api/v1/commands/assistant.usage')&&r.request().method()==='POST');await navigate(page,translator('EN')('assistant'));await expect(page.getByTestId('ai-usage-panel')).toBeVisible();const usage=await usageResponse;expect(usage.ok()).toBe(true);const telemetry=await usage.json();expect(Array.isArray(telemetry.categories)).toBe(true);expect(telemetry.categories.every((category:any)=>['CUSTOMER_ASSISTANT','INTERNAL_DRAFT','TRANSLATION','LEGACY_UNCLASSIFIED'].includes(category.category))).toBe(true);expect(telemetry.totals.records).toBe(telemetry.categories.reduce((sum:number,category:any)=>sum+category.records,0));expect(telemetry).toMatchObject({supplierStatus:'NOT_RECONCILED_TO_PROVIDER_INVOICE',providerInvoked:false,keyStatus:{valueExposed:false}});const samePeriod=await command(page.request,'assistant.usage',{from:telemetry.from,to:telemetry.to});expect(samePeriod.totals).toEqual(telemetry.totals);await expect(page.getByTestId('ai-usage-result')).toBeVisible();await expect(page.getByTestId('ai-usage-result')).toContainText(translator('EN')('aiUsageInvoicePending'));if(telemetry.categories.length===0)await expect(page.getByTestId('ai-usage-empty')).toBeVisible();
 const playground=page.getByTestId('ai-playground');await expect(playground).toBeVisible();await playground.getByTestId('ai-playground-config').selectOption(config.id);await playground.getByTestId('ai-playground-input').fill('Synthetic safety acceptance: please let me speak to a human.');await playground.getByTestId('ai-playground-synthetic').check();await expect(playground.getByTestId('ai-playground-run')).toHaveCount(0);expect(playgroundRequests).toEqual([]);
 await playground.getByTestId('ai-playground-review').click();await expect(playground.getByTestId('ai-playground-run')).toBeVisible();expect(playgroundRequests).toEqual([]);const evaluated=page.waitForResponse(r=>r.url().endsWith('/api/v1/commands/assistant.playground')&&r.request().method()==='POST');await playground.getByTestId('ai-playground-run').click();const response=await evaluated;expect(response.ok()).toBe(true);const simulation=await response.json();expect(simulation).toMatchObject({status:'SIMULATED',providerInvoked:false,businessEffectsExecuted:false,costCents:0});expect(playgroundRequests).toHaveLength(1);expect(playgroundRequests[0]).toMatchObject({input:{configId:config.id,configVersion:config.data.configVersion,synthetic:true}});await expect(playground.getByTestId('ai-playground-result')).toContainText('SIMULATED');await expect(playground.getByTestId('ai-playground-result')).toHaveAttribute('data-provider-invoked','false');
 expect(await businessSnapshot()).toEqual(before);const stored=(await (await page.request.get('/api/v1/entities/assistant_config')).json()).items.find((item:any)=>item.id===config.id);expect(stored).toMatchObject({id:config.id,version:config.version,data:{status:'DRAFT'}});await page.screenshot({path:'docs/evidence/ai-governance.png',fullPage:true});await playground.getByTestId('ai-playground-clear').click();await expect(playground.getByTestId('ai-playground-result')).toHaveCount(0);await expect(playground.getByTestId('ai-playground-input')).toHaveValue('');await expect(playground.getByTestId('ai-playground-synthetic')).not.toBeChecked();expect(playgroundRequests).toHaveLength(1);
});

test('an actual own-message internal draft request stays pending or provider-disabled without a draft confirmation or business changes',async({page},testInfo)=>{
 await demo(page,'OWNER');
 const config=await command(page.request,'assistant_config.create',{name:`QA disabled internal assistant ${randomUUID()}`,escalationContact:'Synthetic office only',allowedServiceIds:[],territories:['Synthetic Berlin'],provider:'DISABLED',testOnly:true});
 await command(page.request,'assistant_config.preview',{id:config.id});await command(page.request,'assistant_config.regression',{id:config.id});await command(page.request,'assistant_config.approve',{id:config.id});const active=await command(page.request,'assistant_config.activate',{id:config.id});expect(active.data).toMatchObject({status:'ACTIVE',provider:'DISABLED'});
 const sourceText=`Synthetic internal draft ${randomUUID()}: review window cleaning at KNB-014. No real model or business execution.`;
 const source=await command(page.request,'message.send',{channel_id:'channel-site',text:sourceText,language:'EN',source:'HUMAN'});expect(source.data).toMatchObject({author_id:'demo-owner',source:'HUMAN',message_version:1});
 async function businessSnapshot(){const snapshot:Record<string,{id:string;version:number}[]>={};for(const kind of ['task','report','material_request']){const response=await page.request.get(`/api/v1/entities/${kind}`);expect(response.ok()).toBe(true);snapshot[kind]=(await response.json()).items.map((item:any)=>({id:item.id,version:item.version})).sort((a:any,b:any)=>a.id.localeCompare(b.id));}return snapshot;}
 const before=await businessSnapshot();const submissions:unknown[]=[],confirmations:unknown[]=[];page.on('request',request=>{if(request.method()!=='POST')return;if(request.url().endsWith('/api/v1/commands/internal_assistant.request'))submissions.push(request.postDataJSON());if(request.url().endsWith('/api/v1/commands/internal_assistant.confirm'))confirmations.push(request.postDataJSON());});
 await navigate(page,translator('EN')('assistant'));const panel=page.getByTestId('internal-assistant-panel');await expect(panel).toBeVisible();await panel.getByTestId('internal-assistant-channel').selectOption('channel-site');await expect(panel.getByTestId('internal-assistant-message')).toBeEnabled();await panel.getByTestId('internal-assistant-message').selectOption(source.id);await panel.getByTestId('internal-assistant-config').selectOption(active.id);await expect(panel.getByTestId('internal-assistant-disabled-notice')).toBeVisible();await panel.getByTestId('internal-assistant-kind').selectOption('TASK_BATCH');await panel.getByTestId('internal-assistant-sites').selectOption(['site-a']);await expect(panel.locator('.internal-draft-original')).toContainText(sourceText);expect(submissions).toEqual([]);expect(confirmations).toEqual([]);await expect(panel.getByTestId('internal-assistant-confirm')).toHaveCount(0);
 const accepted=page.waitForResponse(response=>response.url().endsWith('/api/v1/commands/internal_assistant.request')&&response.request().method()==='POST');await panel.getByTestId('internal-assistant-request').click();const response=await accepted;expect(response.ok()).toBe(true);const request=await response.json();expect(request).toMatchObject({kind:'internal_assistant_request',data:{ownerUserId:'demo-owner',messageId:source.id,messageVersion:1,channelId:'channel-site',configId:active.id,configVersion:active.data.configVersion,kind:'TASK_BATCH',siteIds:['site-a'],status:'PENDING'}});expect(submissions).toHaveLength(1);expect(submissions[0]).toMatchObject({input:{messageId:source.id,messageVersion:1,channelId:'channel-site',configId:active.id,configVersion:active.data.configVersion,kind:'TASK_BATCH',siteIds:['site-a']}});
 const row=panel.locator(`[data-testid='internal-assistant-request-row'][data-request-id='${request.id}']`);await expect(row).toBeVisible();await expect(panel.getByTestId('internal-assistant-refresh')).toBeEnabled();await panel.getByTestId('internal-assistant-refresh').click();await expect(row).toHaveAttribute('data-request-status',/^(PENDING|FAILED)$/);await expect(panel.getByTestId('internal-assistant-preview')).toHaveCount(0);await expect(panel.getByTestId('internal-assistant-confirm')).toHaveCount(0);expect(confirmations).toEqual([]);
 let stored:any;await expect.poll(async()=>{const actual=await page.request.get('/api/v1/entities/internal_assistant_request');expect(actual.ok()).toBe(true);stored=(await actual.json()).items.find((item:any)=>item.id===request.id);return stored?.data.status;},{timeout:10_000}).toMatch(/^(PENDING|FAILED)$/);expect(stored.data).toMatchObject({messageId:source.id,messageVersion:1,configId:active.id,configVersion:active.data.configVersion});expect(stored.data.draftId).toBeUndefined();
 if(stored.data.status==='FAILED'){expect(stored.data.error).toBe('PROVIDER_DISABLED');await expect(panel.getByTestId('internal-assistant-refresh')).toBeEnabled();await panel.getByTestId('internal-assistant-refresh').click();await expect(row.getByTestId('internal-assistant-failure')).toContainText('PROVIDER_DISABLED');}
 testInfo.annotations.push({type:'actual-internal-request',description:stored.data.status==='PENDING'?'Actual authenticated request persisted PENDING; this browser phase does not prove worker execution.':'Actual worker recorded PROVIDER_DISABLED without invoking an external model.'});
 const drafts=await page.request.get('/api/v1/entities/internal_assistant_draft');expect(drafts.ok()).toBe(true);expect((await drafts.json()).items.filter((item:any)=>item.data.requestId===request.id)).toEqual([]);expect(await businessSnapshot()).toEqual(before);expect(confirmations).toEqual([]);await page.screenshot({path:'docs/evidence/internal-assistant-disabled.png',fullPage:true});
});
