import {test,expect,type Page,type Response,type APIRequestContext} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import {writeXlsxWorkbook} from '../packages/storage/xlsx.ts';

// Run only against an explicitly synthetic DEMO delivery database. Assertions
// exercise the rendered application, cookies, API, and persisted PostgreSQL data.
const runtimeFailures=new WeakMap<Page,string[]>();
test.beforeEach(async({page,request})=>{
 const failures:string[]=[];runtimeFailures.set(page,failures);
 page.on('pageerror',error=>failures.push(`JavaScript: ${error.stack||error.message}`));
 page.on('response',response=>{const request=response.request();if(['document','script','stylesheet'].includes(request.resourceType())&&!request.serviceWorker()&&request.frame()===page.mainFrame()&&response.status()>=400)failures.push(`HTTP ${response.status()}: ${request.url()}`);});
 page.on('requestfailed',request=>{if(['script','stylesheet'].includes(request.resourceType())&&!request.serviceWorker()&&request.frame()===page.mainFrame()&&request.failure()?.errorText!=='net::ERR_ABORTED')failures.push(`Asset request failed: ${request.url()} (${request.failure()?.errorText})`);});
 const config=await request.get('/api/v1/public/config',{timeout:10_000});expect(config.ok()).toBe(true);
 const body=await config.json();test.skip(body.mode!=='DEMO','Mutation E2E scenarios require an explicit isolated DEMO database.');
 await page.addInitScript(()=>localStorage.setItem('knaba-language','EN'));
});
test.afterEach(async({page},testInfo)=>{const failures=runtimeFailures.get(page)||[];if(failures.length)await testInfo.attach('browser-runtime-errors',{body:JSON.stringify(failures,null,2),contentType:'application/json'});expect(failures,'Navigation, required assets and JavaScript must load without runtime errors.').toEqual([]);});
function assertDocument(response:Response|null,target:string){expect(response,`Document navigation ${target} must return a response.`).not.toBeNull();if(!response)throw Error(`Missing document response: ${target}`);expect(response.ok()||response.status()===304,`Document navigation ${target} returned HTTP ${response.status()}.`).toBe(true);if(response.status()!==304)expect(response.headers()['content-type'],`Document navigation ${target} must serve the application HTML.`).toContain('text/html');}
async function openPage(page:Page,target:string){assertDocument(await page.goto(target),target);}
async function reloadPage(page:Page){assertDocument(await page.reload(),page.url());}
async function demo(page:Page,role:string){const response=await page.request.post('/api/v1/auth/demo',{data:{role},timeout:10_000});expect(response.ok(),await response.text()).toBe(true);const body=await response.json();await openPage(page,'/console');await expect(page.locator('.sidebar')).toBeVisible();return body;}
async function command(request:APIRequestContext,name:string,input:unknown,expected_version?:number){const me=await request.get('/api/v1/me');expect(me.ok()).toBe(true);const session=await me.json();const r=await request.post(`/api/v1/commands/${name}`,{headers:{'X-CSRF-Token':session.csrfToken},data:{input,expected_version,idempotency_key:randomUUID()}});expect(r.ok(),`${name}: ${await r.text()}`).toBe(true);return r.json();}
async function navigate(page:Page,name:string){const toggle=page.locator('.topbar .mobile-only');if(await toggle.isVisible())await toggle.click();await page.locator('.sidebar nav').getByRole('button',{name,exact:true}).click();await expect(page.locator('.page-heading h1')).toHaveText(name);}
async function saveForm(page:Page){const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Review change',exact:true}).click();await dialog.getByRole('button',{name:'Confirm & execute',exact:true}).click();await expect(dialog.locator('.success-state')).toBeVisible();await dialog.getByRole('button',{name:'Completed',exact:true}).click();}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);}

test('public entry supports all six languages at 360 px without document overflow',async({page})=>{
 await page.setViewportSize({width:360,height:800});await openPage(page,'/');
 for(const code of ['DE','UK','RU','PL','LT','EN']){await page.locator('.language-select select').selectOption(code);await expect(page.locator('html')).toHaveAttribute('lang',code.toLowerCase());await expect(page.locator('.public-copy h1')).not.toHaveText('');await noOverflow(page);}
 await page.screenshot({path:'docs/evidence/public-360.png',fullPage:true});
});
test('rendered demo login and canonical role landings are usable',async({page})=>{
 await openPage(page,'/login');await page.locator('.demo-login select').selectOption('EMPLOYEE');await page.locator('.demo-login').getByRole('button',{name:'Sign in · DEMO'}).click();await expect(page).toHaveURL(/\/console$/);await expect(page.locator('.shift-card')).toBeVisible();
 const roles=[['OWNER','Decision centre'],['DIRECTOR','Decision centre'],['INTERNAL_BAULEITER','Sites & locations'],['STOREKEEPER','Inventory & materials'],['ACCOUNTANT','Pay & payouts'],['CLIENT','My orders']];
 for(const [role,heading]of roles){await demo(page,role);await expect(page.locator('.page-heading h1')).toHaveText(heading);}
 const nav=page.locator('.sidebar nav');await expect(nav.getByRole('button',{name:'My orders',exact:true})).toBeVisible();await expect(nav.getByRole('button',{name:'Pay & payouts',exact:true})).toHaveCount(0);await expect(nav.getByRole('button',{name:'Administration',exact:true})).toHaveCount(0);
 await expect(nav.getByRole('button',{name:'Privacy & security',exact:true})).toBeVisible();expect((await nav.getByRole('button').allTextContents()).map(text=>text.trim()).sort()).toEqual(['My orders','Reports & media','Team communication','Privacy & security'].sort());
});
test('real credentials authenticate and logout revokes the cookie session',async({page})=>{
 await openPage(page,'/login');await page.getByLabel('Email',{exact:true}).fill('demo-employee@example.invalid');await page.getByLabel('Password',{exact:true}).fill('KNABA synthetic local demo password');await page.locator('.login-box form').getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/console$/);await expect(page.locator('.shift-card')).toBeVisible();
 await page.locator('.profile').click();await expect(page).toHaveURL(/\/login$/);expect((await page.request.get('/api/v1/me')).status()).toBe(401);
});
test('manual shift start, private break, resume and end persist after page reload',async({page})=>{
 await demo(page,'EMPLOYEE');const current=(await (await page.request.get('/api/v1/entities/shift')).json()).items.find((s:any)=>s.data.state==='ACTIVE');if(current)await command(page.request,'shift.end',{shiftId:current.id,description:'Synthetic QA cleanup'});
 await reloadPage(page);await page.locator('.shift-actions').getByRole('button',{name:'Start shift',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('#field-siteId').selectOption('site-a');await saveForm(page);await expect(page.locator('.shift-actions').getByRole('button',{name:'End shift',exact:true})).toBeVisible();
 await page.locator('.shift-actions').getByRole('button',{name:'Break',exact:true}).click();await saveForm(page);await expect(page.locator('.shift-actions').getByRole('button',{name:'Resume work',exact:true})).toBeVisible();
 await page.locator('.shift-actions').getByRole('button',{name:'Resume work',exact:true}).click();await saveForm(page);await page.locator('.shift-actions').getByRole('button',{name:'End shift',exact:true}).click();await saveForm(page);await reloadPage(page);await expect(page.locator('.shift-actions').getByRole('button',{name:'Start shift',exact:true})).toBeVisible();
 const shifts=(await (await page.request.get('/api/v1/entities/shift')).json()).items;const latest=shifts.at(-1);expect(latest.data.state).toBe('ENDED');expect(latest.data.summary.breakSeconds).toBeGreaterThanOrEqual(0);
});
test('task form creates a persisted task and mobile modal fits 360 px',async({page})=>{
 await demo(page,'DIRECTOR');await page.setViewportSize({width:360,height:800});await navigate(page,'Tasks');await page.locator('.heading-actions').getByRole('button',{name:'Create new',exact:true}).click();const dialog=page.getByRole('dialog');const title=`QA browser task ${randomUUID()}`;await dialog.locator('#field-siteId').selectOption('site-a');await dialog.locator('#field-title').fill(title);await noOverflow(page);await page.screenshot({path:'docs/evidence/task-form-360.png',fullPage:true});await saveForm(page);await reloadPage(page);await navigate(page,'Tasks');await page.locator('#global-search').fill(title);await expect(page.getByRole('button',{name:title,exact:false})).toBeVisible();
});
test('team chat sends original text and reads the persisted message after reload',async({page})=>{
 await demo(page,'EMPLOYEE');await navigate(page,'Team communication');await page.locator('.channel-list').getByRole('button',{name:/KNB-014/}).click();const text=`QA original EN ${randomUUID()}`;await page.getByRole('textbox',{name:'Message',exact:true}).fill(text);await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.message-bubble').filter({hasText:text})).toBeVisible();await reloadPage(page);await navigate(page,'Team communication');await page.locator('.channel-list').getByRole('button',{name:/KNB-014/}).click();await expect(page.locator('.message-bubble').filter({hasText:text})).toBeVisible();await page.screenshot({path:'docs/evidence/team-chat-desktop.png',fullPage:true});
});
test('private photo upload validates bytes, registers site context and permits file retrieval',async({page})=>{
 await demo(page,'EMPLOYEE');const png=(await sharp({create:{width:240,height:160,channels:3,background:{r:35,g:109,b:85}}}).png().toBuffer()).toString('base64');const me=await (await page.request.get('/api/v1/me')).json();const upload=await page.request.post('/api/v1/media/upload',{headers:{'X-CSRF-Token':me.csrfToken},data:{base64:png,mimeType:'image/png',fileName:'synthetic-test.png',redactionConfirmed:false}});expect(upload.ok(),await upload.text()).toBe(true);const u=await upload.json();expect(u.metadataStripped).toBe(true);
 const asset=await command(page.request,'media.register',{uploadId:u.uploadId,siteId:'site-a',stage:'AFTER',visibility:'INTERNAL',caption:'Synthetic QA image',retentionPurpose:'Synthetic release QA'});const image=await page.request.get(`/api/v1/media/${asset.id}/file`);expect(image.ok()).toBe(true);expect(image.headers()['content-type']).toMatch(/^image\/png/);expect((await image.body()).length).toBeGreaterThan(0);await navigate(page,'Reports & media');await page.getByRole('tab',{name:/Reports & media/}).last().click();await expect(page.locator('.record-link').filter({hasText:asset.id})).toBeVisible();
});
test('public contact and guest chat persist privately with honest manual fallback',async({page,browser})=>{
 await openPage(page,'/');await page.getByRole('button',{name:/New customer/}).click();const form=page.getByRole('dialog');const suffix=randomUUID();await form.getByLabel(/Your name/).fill(`QA guest ${suffix}`);await form.getByLabel(/Email/).fill(`qa-${suffix}@example.invalid`);await form.getByLabel(/How can we help/).fill('Synthetic QA request only');await form.getByRole('checkbox').check();await form.getByRole('button',{name:'Send',exact:true}).click();await expect(form.locator('.success-state')).toBeVisible();await form.getByRole('button',{name:'Completed',exact:true}).click();await page.getByRole('button',{name:'Start webchat',exact:true}).click();const text=`QA private guest ${randomUUID()}`;await page.getByRole('dialog').getByLabel('Message',{exact:true}).fill(text);
 const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/public/chat')&&r.request().method()==='POST');await page.getByRole('dialog').getByRole('button',{name:'Send',exact:true}).click();const body=await (await response).json();expect(['MANUAL_FALLBACK','HANDOFF_PENDING']).toContain(body.status);await expect(page.locator('.public-chat-message').filter({hasText:text})).toBeVisible();
 const other=await browser.newContext({baseURL:process.env.E2E_BASE_URL??'http://127.0.0.1:3000'});try{const denied=await other.request.get(`/api/v1/public/chat/${body.channelId}/messages`);expect([401,404]).toContain(denied.status());expect(await denied.text()).not.toContain(text);}finally{await other.close();}
});
test('mutations reject missing CSRF and CLIENT cannot read internal chat or payroll',async({page})=>{
 await demo(page,'CLIENT');const denied=await page.request.post('/api/v1/commands/report.ack',{data:{input:{},idempotency_key:randomUUID()}});expect(denied.status()).toBe(403);const payroll=await page.request.get('/api/v1/entities/payroll_calculation');expect((await payroll.json()).items).toEqual([]);const channels=await (await page.request.get('/api/v1/entities/channel')).json();expect(channels.items.some((c:any)=>c.data.type==='SITE_INTERNAL')).toBe(false);
});
test('published report PDF CSV XLSX match immutable snapshot and client access',async({page})=>{
 await demo(page,'CLIENT');const versions=await (await page.request.get('/api/v1/entities/report_version')).json();const version=process.env.E2E_REPORT_VERSION_ID?versions.items.find((v:any)=>v.id===process.env.E2E_REPORT_VERSION_ID):versions.items.find((v:any)=>v.data.snapshot.descriptionDe?.includes('SYNTHETISCHER TESTBERICHT'));expect(version,'Run canonical DEMO seed to create the reviewed and published synthetic fixture.').toBeDefined();const id=version.id,snapshot=version.data.snapshot;
 for(const [format,mime]of [['pdf','application/pdf'],['csv','text/csv'],['xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']]){const exported=await page.request.get(`/api/v1/reports/${id}/${format}`);expect(exported.ok(),await exported.text()).toBe(true);expect(exported.headers()['content-type']).toContain(mime);const bytes=await exported.body();expect(bytes.length).toBeGreaterThan(100);if(format==='pdf')expect(bytes.subarray(0,4).toString()).toBe('%PDF');if(format==='csv'){expect(bytes.toString()).toContain(String(snapshot.totalGrossCents));expect(bytes.toString()).toContain(version.data.sha256);}if(format==='xlsx')expect(bytes.subarray(0,2).toString()).toBe('PK');}
 await navigate(page,'Reports & media');await page.screenshot({path:'docs/evidence/client-reports-desktop.png',fullPage:true});
});
test('manual inventory SKU lookup works without camera and shows approved unit conversion',async({page})=>{
 await demo(page,'EMPLOYEE');await navigate(page,'Inventory & materials');await page.locator('.heading-actions').getByRole('button',{name:'Scan material',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Barcode, QR code or SKU',{exact:true}).fill('DEMO-CLEAN-01');await dialog.getByRole('button',{name:'Look up material',exact:true}).click();await expect(dialog.locator('.scan-result')).toBeVisible();await expect(dialog.locator('.scan-result')).toContainText('ml');await expect(dialog.locator('.scan-result code')).toContainText('knaba://material/material-clean');
});
test('client issue form references approved photo, persists original text and opens a review',async({page})=>{
 await demo(page,'CLIENT');await page.locator('.heading-actions').getByRole('button',{name:'Report an issue',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.locator('.issue-photo-grid input[type=checkbox]').first()).toBeVisible();await dialog.locator('.issue-photo-grid input[type=checkbox]').first().check();const text=`QA synthetic client clarification ${randomUUID()}`;await dialog.getByLabel('Description',{exact:false}).fill(text);await dialog.getByRole('button',{name:'Review change',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/commands/issue.create')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Submit',exact:true}).click();const r=await response;expect(r.ok(),await r.text()).toBe(true);const issue=await r.json();expect(issue.data.state).toBe('OPEN');expect(issue.data.description).toBe(text);await expect(dialog.locator('.success-state')).toBeVisible();const persisted=await command(page.request,'issue.get',{id:issue.id});expect(persisted.data.description).toBe(text);expect(JSON.stringify(persisted)).not.toContain('internalReason');
});
test('structure import rejects malformed files, previews CSV and XLSX without writes, and commits reviewed hierarchy',async({page})=>{
 await demo(page,'DIRECTOR');await page.setViewportSize({width:360,height:800});await navigate(page,'Sites & locations');await page.locator('.heading-actions').getByRole('button',{name:'Import structure',exact:true}).click();
 const dialog=page.getByRole('dialog'),form=dialog.locator('.location-import');await form.locator('select').selectOption('site-a');
 const before=(await (await page.request.get('/api/v1/entities/location')).json()).items;
 await form.locator('input[type=file]').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('name,nodeType\nMissing identifier,BUILDING\n')});await form.getByRole('button',{name:'Check file',exact:true}).click();await expect(form.getByRole('alert')).toBeVisible();await expect(form.getByRole('button',{name:'Save import',exact:true})).toHaveCount(0);
 const key=`qa-${randomUUID()}`,headers=['externalKey','parentExternalKey','nodeType','code','name','floorLevel','floorLabelDe'];
 const rows=[[`${key}-house`,'','BUILDING','QA-H','Synthetic QA house','',''],[`${key}-floor`,`${key}-house`,'FLOOR','UG','Synthetic QA basement',-1,'UG']];
 const xlsx=writeXlsxWorkbook({creator:'Synthetic QA',createdAt:new Date().toISOString(),title:'Synthetic hierarchy',subject:'QA fixture',description:'No real customer data',sheets:[{name:'Locations',rows:[headers,...rows]}]});
 await form.locator('input[type=file]').setInputFiles({name:'locations.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:xlsx});await form.getByRole('button',{name:'Check file',exact:true}).click();await expect(form.locator('.import-confirm')).toBeVisible();await expect(form.locator('.import-table tbody tr')).toHaveCount(2);await expect(form.getByRole('button',{name:'Save import',exact:true})).toBeDisabled();
 const csv=[headers,...rows].map(row=>row.join(',')).join('\n')+'\n';await form.locator('input[type=file]').setInputFiles({name:'locations.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await form.getByRole('button',{name:'Check file',exact:true}).click();await expect(form.locator('.import-confirm')).toBeVisible();await expect(form.locator('.import-table')).toContainText('(-1)');
 expect((await (await page.request.get('/api/v1/entities/location')).json()).items).toHaveLength(before.length);await noOverflow(page);await page.screenshot({path:'docs/evidence/location-import-360.png',fullPage:true});await form.locator('.import-confirm input').check();await form.getByRole('button',{name:'Save import',exact:true}).click();await expect(form.locator('.success-state')).toBeVisible();
 const after=(await (await page.request.get('/api/v1/entities/location')).json()).items;const house=after.find((e:any)=>e.data.externalKey===`${key}-house`),floor=after.find((e:any)=>e.data.externalKey===`${key}-floor`);expect(after).toHaveLength(before.length+2);expect(house.data.siteId).toBe('site-a');expect(floor.data).toMatchObject({siteId:'site-a',parentId:house.id,floorLevel:-1,floorLabelDe:'UG'});
});
