import {describe,it,expect} from 'vitest';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {assert,DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';
import {resourcesCommands} from '../packages/domain/resources.ts';
import {preparePrivateMedia} from '../packages/storage/media-ingest.ts';
import {applyClientRedaction,clientRedactionInput,clientRedactionVisible,redactClientImage,type ClientRedactionHost} from '../packages/storage/client-redaction.ts';
import type {PrivateBlobStore,PrivateBlob,BlobInput,BlobSql} from '../packages/storage/index.ts';

const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex'),now='2026-10-06T12:00:00.000Z';
const rect={x:2,y:3,width:5,height:4};
async function generated(format:'png'|'jpeg'|'webp'='png'){
 const bytes=Buffer.alloc(16*12*3);for(let y=0;y<12;y++)for(let x=0;x<16;x++){const p=(y*16+x)*3;bytes[p]=100+x*5;bytes[p+1]=30+y*7;bytes[p+2]=190;}
 return sharp(bytes,{raw:{width:16,height:12,channels:3}})[format]().toBuffer();
}
async function pixels(bytes:Buffer){return sharp(bytes).removeAlpha().raw().toBuffer({resolveWithObject:true});}
function pixel(data:Buffer,width:number,x:number,y:number){return [...data.subarray((y*width+x)*3,(y*width+x)*3+3)];}
class Tx implements Transaction,BlobSql {
 companyId='synthetic-media-qa';rows=new Map<string,Entity>();events:Data[]=[];sequence=0;
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const e=this.rows.get(kind+':'+id);assert(e&&e.companyId===this.companyId,'NOT_FOUND_SAFE');return structuredClone(e) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.rows.values()].filter(e=>e.kind===kind).map(e=>structuredClone(e) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=kind+'-'+(++this.sequence)):Promise<Entity<T>>{assert(!this.rows.has(kind+':'+id),'VERSION_CONFLICT');const e={id,kind,companyId:this.companyId,version:1,data:structuredClone(data),createdAt:now,updatedAt:now};this.rows.set(kind+':'+id,e);return structuredClone(e);}
 async save(e:Entity,data:Data,version=e.version){assert((await this.get(e.kind,e.id)).version===version,'VERSION_CONFLICT');const updated={...e,version:e.version+1,data:structuredClone(data)};this.rows.set(e.kind+':'+e.id,updated);return structuredClone(updated);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
 async query():Promise<{rows:any[]}>{throw new Error('CPU memory fixture must not execute SQL');}
}
// Explicit private-storage transaction double; image decoding/masking is real Sharp.
async function fixture(){
 const tx=new Tx(),blobs=new Map<string,PrivateBlob>();let reads=0,writes=0,onRead:(()=>Promise<void>)|undefined;
 const store:PrivateBlobStore={provider:'POSTGRES',put:async(i:BlobInput,t?:BlobSql)=>{assert(t===tx,'INVALID_STATE');writes++;assert(!blobs.has(i.id),'DUPLICATE_EFFECT');const sha256=hash(i.bytes);blobs.set(i.id,{id:i.id,companyId:i.companyId,ownerId:i.ownerId,bytes:Buffer.from(i.bytes),mimeType:i.mimeType,sha256,provider:'POSTGRES'});return {key:i.id,sha256,byteSize:i.bytes.length,mimeType:i.mimeType,provider:'POSTGRES',created:true};},get:async(companyId,id)=>{reads++;await onRead?.();const b=blobs.get(id);assert(b&&b.companyId===companyId,'NOT_FOUND_SAFE');return {...b,bytes:Buffer.from(b.bytes)};},delete:async()=>{throw new Error('Redaction must never delete a source');},probe:async()=>({provider:'POSTGRES',configured:true,available:true})};
 const original=await generated(),prepared=await preparePrivateMedia({bytes:original,mimeType:'image/png',fileName:'synthetic.png',sourceId:'synthetic-generated-image'});
 for(const [id,bytes,mimeType]of [['original',original,'image/png'],['sanitized',prepared.clean,prepared.clientMimeType]] as const)blobs.set(id,{id,companyId:tx.companyId,ownerId:'foreman',bytes:Buffer.from(bytes),mimeType,sha256:hash(bytes),provider:'POSTGRES'});
 await tx.add('user',{active:true,roles:['INTERNAL_BAULEITER'],permissions:['report.approve','media.read'],siteIds:['site']},'foreman');
 await tx.add('media_asset',{siteId:'site',visibility:'CLIENT_AFTER_APPROVAL',state:'APPROVED_FOR_CLIENT',approvedBy:'reviewer',approvedAt:now,approvalReason:'Previous copy reviewed',uploadedBy:'foreman',blobKey:'original',sha256:hash(original),mimeType:'image/png',clientBlobKey:'sanitized',clientSha256:hash(prepared.clean),clientMimeType:prepared.clientMimeType,clientByteSize:prepared.clean.length,metadataStripped:true,redactionConfirmed:true},'media');
 const host:ClientRedactionHost<Tx>={store,actorIn:async(t,userId)=>{const u=await t.get('user',userId);assert(u.data.active!==false,'ACCESS_DENIED');return {userId,companyId:t.companyId,roles:u.data.roles,permissions:u.data.permissions,siteIds:u.data.siteIds,warehouseIds:[],customerIds:[]};},scope:a=>a,visible:async(_t,a,e)=>e.companyId===a.companyId&&(a.permissions.includes('scope.company')||a.siteIds.includes(e.data.siteId))};
 const change=async(kind:string,id:string,patch:Data)=>{const e=await tx.get(kind,id);return tx.save(e,{...e.data,...patch});};
 async function command(input:Data={},expectedVersion?:number){const actor=await host.actorIn(tx,'foreman'),ctx:CommandContext={tx,actor,now,idempotencyKey:'synthetic-command-'+(writes+1),expectedVersion,requireSite:()=>{},requireOwn:()=>{}};const before=structuredClone({rows:tx.rows,events:tx.events,blobs});try{return await applyClientRedaction(ctx,clientRedactionInput.parse({mediaId:'media',clientCopyVersion:0,rectangles:[rect],reason:'Mask a synthetic identifier',...input}),host);}catch(error){tx.rows=before.rows;tx.events=before.events;blobs.clear();for(const [id,b]of before.blobs)blobs.set(id,{...b,bytes:Buffer.from(b.bytes)});throw error;}}
 return {tx,blobs,store,host,original,prepared,command,change,stats:()=>({reads,writes}),onRead:(fn:()=>Promise<void>)=>{onRead=fn;}};
}

describe('manual CLIENT-copy redaction (actual Sharp, CPU storage double, no provider/SQL claim)',()=>{
 it.each(['png','jpeg','webp'] as const)('masks exact opaque pixels in %s without changing other pixels or original bytes',async format=>{const original=await generated(format),before=Buffer.from(original),decoded=await pixels(original),masked=await redactClientImage(original,'image/'+(format==='jpeg'?'jpeg':format),[rect]),result=await pixels(masked.bytes);expect(original.equals(before)).toBe(true);expect(masked).toMatchObject({width:16,height:12,mimeType:'image/png',sha256:hash(masked.bytes)});for(let y=0;y<12;y++)for(let x=0;x<16;x++)expect(pixel(result.data,16,x,y)).toEqual(x>=2&&x<7&&y>=3&&y<7?[0,0,0]:pixel(decoded.data,16,x,y));const metadata=await sharp(masked.bytes).metadata();expect(metadata.exif).toBeUndefined();expect(metadata.icc).toBeUndefined();expect(metadata.orientation).toBeUndefined();});
 it('accepts overlapping and exact-edge rectangles with fully opaque black coverage',async()=>{const image=await generated(),masked=await redactClientImage(image,'image/png',[{x:0,y:0,width:16,height:12},rect]),decoded=await sharp(masked.bytes).ensureAlpha().raw().toBuffer();for(let i=0;i<decoded.length;i+=4)expect([...decoded.subarray(i,i+4)]).toEqual([0,0,0,255]);});
 it('bounds concurrent decoder work instead of allocating thirty image-sized overlays per request',async()=>{const image=await generated(),outcomes=await Promise.allSettled([redactClientImage(image,'image/png',Array(30).fill(rect)),redactClientImage(image,'image/png',[rect])]);expect(outcomes.filter(o=>o.status==='fulfilled')).toHaveLength(1);expect((outcomes.find(o=>o.status==='rejected') as PromiseRejectedResult).reason).toMatchObject({code:'RATE_LIMITED',details:{reason:'REDACTION_DECODER_BUSY'}});expect(await redactClientImage(image,'image/png',[rect])).toMatchObject({width:16,height:12});});
 it.each([{x:-1,y:0,width:1,height:1},{x:0.5,y:0,width:1,height:1},{x:0,y:0,width:0,height:1},{x:0,y:0,width:1,height:0},{x:15,y:0,width:2,height:1},{x:0,y:11,width:1,height:2},{x:0,y:0,width:1,height:1,opacity:0.5},{x:Number.MAX_SAFE_INTEGER,y:0,width:1,height:1}])('rejects invalid or out-of-image rectangle %j before producing a copy',async bad=>{await expect(redactClientImage(await generated(),'image/png',[bad])).rejects.toBeDefined();});
 it('rejects unsupported/fake MIME, malformed image, empty/oversized mask sets and extra command fields',async()=>{const b=await generated();await expect(redactClientImage(b,'application/pdf',[rect])).rejects.toMatchObject({code:'VALIDATION_ERROR'});await expect(redactClientImage(b,'image/jpeg',[rect])).rejects.toMatchObject({code:'VALIDATION_ERROR'});await expect(redactClientImage(Buffer.from('synthetic invalid bytes'),'image/png',[rect])).rejects.toMatchObject({code:'VALIDATION_ERROR'});for(const masks of [[],Array(31).fill(rect)])await expect(redactClientImage(b,'image/png',masks)).rejects.toBeDefined();expect(clientRedactionInput.safeParse({mediaId:'media',clientCopyVersion:0,rectangles:[rect],reason:'Synthetic reason',clientBlobKey:'evil'}).success).toBe(false);});
 it('creates a private immutable edit and minimal acknowledgment, preserves original/prior copies, and invalidates publication',async()=>{const f=await fixture(),before=Buffer.from(f.original),clean=Buffer.from(f.prepared.clean),ack=await f.command(),asset=await f.tx.get('media_asset','media'),edit=(await f.tx.list('media_client_edit'))[0]!;expect(ack).toMatchObject({id:'media',kind:'media_asset',version:2,data:{state:'RECEIVED',clientCopyVersion:1,clientWidth:16,clientHeight:12,requiresPublicationApproval:true}});for(const k of ['blobKey','sha256','clientBlobKey','uploadedBy','caption'])expect(ack.data).not.toHaveProperty(k);expect(asset.data).toMatchObject({blobKey:'original',sha256:hash(before),approvedBy:null,approvedAt:null,approvalReason:null,redactionConfirmed:true});expect(edit.data).toMatchObject({immutable:true,mediaId:'media',sourceClientBlobKey:'sanitized',clientBlobKey:asset.data.clientBlobKey,clientSha256:asset.data.clientSha256,clientCopyVersion:1,method:'MANUAL_OPAQUE_RECTANGLES',automaticDetection:false});expect(f.blobs.get('original')!.bytes.equals(before)).toBe(true);expect(f.blobs.get('sanitized')!.bytes.equals(clean)).toBe(true);expect(f.blobs).toHaveLength(3);expect(f.tx.events).toHaveLength(1);const actor=await f.host.actorIn(f.tx,'foreman');expect(await clientRedactionVisible(f.tx,actor,edit,f.host)).toBe(true);});
 it('a later edit retains the first masked copy and requires a separate explicit media approval',async()=>{const f=await fixture(),first=await f.command(),key=(await f.tx.get('media_asset','media')).data.clientBlobKey,copy=Buffer.from(f.blobs.get(key)!.bytes);const second=await f.command({clientCopyVersion:1,rectangles:[{x:10,y:8,width:2,height:2}]},first.version);expect(second.data.clientCopyVersion).toBe(2);expect(f.blobs.get(key)!.bytes.equals(copy)).toBe(true);expect(await f.tx.list('media_client_edit')).toHaveLength(2);const actor=await f.host.actorIn(f.tx,'foreman'),def=resourcesCommands['media.approve']!,approved=await def.handler({tx:f.tx,actor,now,idempotencyKey:'synthetic-approval',expectedVersion:second.version,requireSite:s=>assert(actor.siteIds.includes(s),'ACCESS_DENIED'),requireOwn:()=>{}},def.schema.parse({mediaId:'media',reason:'Manually reviewed masked CLIENT copy'}));expect(approved.data.state).toBe('APPROVED_FOR_CLIENT');});
 it('an authorized editor retains the original employee data subject as every copy blob owner for privacy deletion',async()=>{const f=await fixture();await f.tx.add('user',{active:true,roles:['EMPLOYEE'],permissions:['media.read'],siteIds:['site']},'uploader');await f.change('media_asset','media',{uploadedBy:'uploader'});for(const b of f.blobs.values())b.ownerId='uploader';await f.command();const asset=await f.tx.get('media_asset','media'),edit=(await f.tx.list('media_client_edit'))[0]!;expect(f.blobs.get(asset.data.clientBlobKey)!.ownerId).toBe('uploader');expect(edit.data).toMatchObject({uploadedBy:'uploader',editedBy:'foreman',ownerUserId:'foreman'});});
 it.each(['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','SERVICE_ACCOUNT','BOT_ADMIN'])('denies %s despite injected read/approval rights before any private storage read',async role=>{const f=await fixture();await f.change('user','foreman',{roles:[role]});await expect(f.command()).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(f.stats()).toEqual({reads:0,writes:0});});
 it.each(['SITE','PERMISSION','ACTIVE','STATE','CONFIDENTIAL','STALE_COPY','STALE_ENTITY','NOT_SANITIZED','ORIGINAL_POINTER'])('rejects fresh %s source/authority before writing',async condition=>{const f=await fixture();if(condition==='SITE')await f.change('user','foreman',{siteIds:[]});if(condition==='PERMISSION')await f.change('user','foreman',{permissions:['media.read']});if(condition==='ACTIVE')await f.change('user','foreman',{active:false});if(condition==='STATE')await f.change('media_asset','media',{state:'ERASED'});if(condition==='CONFIDENTIAL')await f.change('media_asset','media',{visibility:'CONFIDENTIAL'});if(condition==='STALE_COPY')await f.change('media_asset','media',{clientCopyVersion:2});if(condition==='NOT_SANITIZED')await f.change('media_asset','media',{metadataStripped:false});if(condition==='ORIGINAL_POINTER')await f.change('media_asset','media',{clientBlobKey:'original'});await expect(f.command({},condition==='STALE_ENTITY'?2:undefined)).rejects.toBeDefined();expect(f.stats().writes).toBe(0);expect(await f.tx.list('media_client_edit')).toEqual([]);});
 it('rechecks revoked source authority after storage read before any blob/edit write',async()=>{const f=await fixture();f.onRead(async()=>{await f.change('user','foreman',{roles:['CLIENT']});});await expect(f.command()).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(f.stats()).toEqual({reads:1,writes:0});expect(await f.tx.list('media_client_edit')).toEqual([]);});
 it('rejects a changed client checksum and blocks S3 instead of leaving an unjournaled orphan',async()=>{const f=await fixture();f.blobs.get('sanitized')!.sha256='a'.repeat(64);await expect(f.command()).rejects.toMatchObject({code:'INVALID_STATE'});expect(f.stats().writes).toBe(0);Object.defineProperty(f.store,'provider',{value:'S3'});await expect(f.command()).rejects.toMatchObject({code:'MISSING_CONFIGURATION',details:{reason:'ATOMIC_REDACTION_STORAGE_REQUIRED'}});expect(f.stats().writes).toBe(0);});
 it('failed metadata commit rolls back the CPU storage transaction and preserves every earlier copy',async()=>{const f=await fixture(),original=f.tx.save.bind(f.tx);f.tx.save=async(e,d,v)=>{if(e.kind==='media_asset')throw new DomainError('SIMULATED_METADATA_FAILURE');return original(e,d,v);};await expect(f.command()).rejects.toMatchObject({code:'SIMULATED_METADATA_FAILURE'});expect(f.blobs.size).toBe(2);expect(await f.tx.list('media_client_edit')).toEqual([]);expect(f.tx.events).toEqual([]);expect((await f.tx.get('media_asset','media')).version).toBe(1);});
 it('edit history loses visibility after current site/role/source removal without any storage read',async()=>{const f=await fixture();await f.command();const actor=await f.host.actorIn(f.tx,'foreman'),edit=(await f.tx.list('media_client_edit'))[0]!;await f.change('user','foreman',{siteIds:[]});expect(await clientRedactionVisible(f.tx,actor,edit,f.host)).toBe(false);await f.change('user','foreman',{siteIds:['site'],roles:['CLIENT']});expect(await clientRedactionVisible(f.tx,actor,edit,f.host)).toBe(false);expect(await clientRedactionVisible(f.tx,actor,{...edit,companyId:'foreign'},f.host)).toBe(false);expect(f.stats()).toEqual({reads:1,writes:1});});
});
