import { describe,it,expect } from 'vitest';
import { communicationsCommands, whatsAppPolicy, isQuietHour } from '../packages/domain/communications.ts';
import { DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction } from '../packages/domain/core.ts';

class MemoryTx implements Transaction {
  rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];sequence=0;now='2026-10-06T10:00:00.000Z';
  async get<T extends Data=Data>(kind:string,id:string){const entity=this.rows.get(`${kind}:${id}`);if(!entity)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(entity) as Entity<T>;}
  async list<T extends Data=Data>(kind:string){return [...this.rows.values()].filter(e=>e.kind===kind).map(e=>structuredClone(e) as Entity<T>);}
  async add<T extends Data=Data>(kind:string,data:T,id=`entity-${++this.sequence}`){const entity={id,kind,data:structuredClone(data),companyId:'company',version:1,createdAt:this.now,updatedAt:this.now};this.rows.set(`${kind}:${id}`,entity);return structuredClone(entity);}
  async save(entity:Entity,data:Data,version=entity.version){const old=await this.get(entity.kind,entity.id);if(old.version!==version)throw new DomainError('VERSION_CONFLICT');const saved={...entity,data:structuredClone(data),version:entity.version+1,updatedAt:this.now};this.rows.set(`${entity.kind}:${entity.id}`,saved);return structuredClone(saved);}
  async event(type:string,data:Data){this.events.push({type,data});}
}
const employee:Actor={userId:'employee',companyId:'company',roles:['EMPLOYEE'],permissions:['chat.read','chat.write','translation.use'],siteIds:['site'],customerIds:[],warehouseIds:[]};
const manager={...employee,userId:'owner',roles:['OWNER'],permissions:[...employee.permissions,'scope.company','media.read']};const service={...employee,userId:'worker',roles:['SERVICE_ACCOUNT']};
function context(tx:MemoryTx,actor=employee):CommandContext {return {tx,actor,now:tx.now,idempotencyKey:'test-command-key',requireSite:id=>{if(!actor.permissions.includes('scope.company')&&!actor.siteIds.includes(id))throw new DomainError('ACCESS_DENIED');},requireOwn:id=>{if(actor.userId!==id)throw new DomainError('ACCESS_DENIED');}};}
async function run(tx:MemoryTx,name:string,input:Data,actor=employee){const command=communicationsCommands[name]!;const before=structuredClone(tx.rows),events=structuredClone(tx.events);try{return await command.handler(context(tx,actor),command.schema.parse(input));}catch(error){tx.rows=before;tx.events=events;throw error;}}
async function setup(){const tx=new MemoryTx();await tx.add('user',{roles:['OWNER'],active:true,permissions:manager.permissions},'owner');await tx.add('user',{roles:['EMPLOYEE'],active:true,siteIds:['site']},'employee');await tx.add('user',{roles:['CLIENT'],active:true},'client');await tx.add('user',{roles:['EMPLOYEE'],active:true,siteIds:['site']},'other');await tx.add('site',{customerId:'customer'},'site');await tx.add('site',{customerId:'other-customer'},'other-site');await tx.add('customer_membership',{userId:'client',customerId:'customer',active:true,permissions:['VIEW'],siteIds:['site']},'client-view');const channel=await run(tx,'channel.create',{type:'SITE_INTERNAL',name:'Site internal',member_ids:['employee','other'],site_id:'site'},manager);const message=await run(tx,'message.send',{channel_id:channel.id,text:'Nicht 24 Stück auf Etage 2 verwenden.',language:'DE',important:true});return {tx,channel,message};}
const client:Actor={...employee,userId:'client',roles:['CLIENT'],siteIds:[],customerIds:['customer']};
async function setupClient(){const {tx}=await setup();const channel=await run(tx,'channel.create',{type:'SITE_CLIENT',name:'Client site',site_id:'site',customer_id:'customer',member_ids:['client'],external_member_ids:['client']},manager);const message=await run(tx,'message.send',{channel_id:channel.id,text:'Freigegebene Objektmeldung',language:'DE',important:true},manager);return {tx,channel,message,membership:await tx.get('customer_membership','client-view')};}

describe('WhatsApp outbound policy and quiet period',()=>{
 it('needs recorded consent even when a recent inbound exists',()=>{expect(whatsAppPolicy({now:'2026-10-06T10:00:00Z',last_inbound_at:'2026-10-06T09:00:00Z',consent:false})).toMatchObject({allowed:false,reason:'CHANNEL_CONSENT_REQUIRED'});});
 it('allows free text strictly inside 24 hours and requires approved template at the boundary',()=>{const base={now:'2026-10-06T10:00:00Z',consent:true};expect(whatsAppPolicy({...base,last_inbound_at:'2026-10-05T10:00:01Z'})).toMatchObject({allowed:true,kind:'TEXT'});expect(whatsAppPolicy({...base,last_inbound_at:'2026-10-05T10:00:00Z'})).toMatchObject({allowed:false,reason:'WHATSAPP_WINDOW_CLOSED'});expect(whatsAppPolicy({...base,approved_template:'report_ready',template_status:'APPROVED'})).toMatchObject({allowed:true,kind:'TEMPLATE'});});
 it('optout wins over approved templates and future inbound cannot open a window',()=>{expect(whatsAppPolicy({now:'2026-10-06T10:00:00Z',consent:true,opted_out:true,approved_template:'report_ready',template_status:'APPROVED'}).allowed).toBe(false);expect(whatsAppPolicy({now:'2026-10-06T10:00:00Z',last_inbound_at:'2026-10-06T11:00:00Z',consent:true}).allowed).toBe(false);});
 it('uses Berlin DST rather than UTC for quiet hours and disables equal hour ranges',()=>{expect(isQuietHour('2026-07-06T20:00:00Z',22,7)).toBe(true);expect(isQuietHour('2026-01-06T20:00:00Z',22,7)).toBe(false);expect(isQuietHour('2026-10-06T23:00:00Z',0,0)).toBe(false);});
});

describe('current channel scope and safe attachment boundaries',()=>{
 it('manager roles cannot list/read an unassigned site without an explicit company scope',async()=>{const {tx,channel}=await setup();const unscoped={...manager,siteIds:[],permissions:['chat.read','chat.write','chat.manage']};expect(await run(tx,'channel.list',{},unscoped)).toEqual([]);expect(await run(tx,'channel.unread',{},unscoped)).toEqual([]);await expect(run(tx,'message.read',{channel_id:channel.id},unscoped)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect((await run(tx,'channel.list',{},manager)).map((c:Entity)=>c.id)).toContain(channel.id);});
 it('task threads inherit the task site and remain scoped even when the caller omitted site_id',async()=>{const {tx}=await setup();await tx.add('task',{siteId:'other-site'},'other-task');const channel=await run(tx,'channel.create',{type:'TASK_THREAD',name:'Other task',task_id:'other-task',member_ids:['owner']},manager);expect(channel.data.site_id).toBe('other-site');const scoped={...manager,permissions:['chat.read'],siteIds:['site']};expect((await run(tx,'channel.list',{},scoped)).some((c:Entity)=>c.id===channel.id)).toBe(false);await expect(run(tx,'message.read',{channel_id:channel.id},scoped)).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it.each([{expires_at:'2026-10-06T10:00:00.000Z'},{left_at:'2026-10-06T09:00:00Z'},{removed_at:'2026-10-06T09:00:00Z'},{active:false}])('expired/left/removed/inactive channel membership blocks reads and existing callbacks: %j',async patch=>{const {tx,channel,message}=await setup();const callback=await run(tx,'callback.create',{message_id:message.id,action:'ACK'});await tx.save(channel,{...channel.data,members:channel.data.members.map((m:Data)=>m.user_id==='employee'?{...m,...patch}:m)});expect(await run(tx,'channel.list',{})).toEqual([]);await expect(run(tx,'message.read',{channel_id:channel.id})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(tx,'callback.consume',{action_id:callback.action_id})).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it.each([
  ['inactive',{active:false}],['revoked',{revokedAt:'2026-10-06T09:59:59Z'}],['expired',{expiresAt:'2026-10-06T10:00:00.000Z'}],['invalid expiry',{expiresAt:'invalid'}],['VIEW removed',{permissions:['ACK']}],['site removed',{siteIds:['other-site']}],['customer changed',{customerId:'other-customer'}],
 ] as [string,Data][])('%s customer rights block all historical/message/translation actions despite cached customerIds and channel membership',async(_reason,patch)=>{
  const {tx,channel,message,membership}=await setupClient();expect((await run(tx,'channel.list',{},client)).map((c:Entity)=>c.id)).toContain(channel.id);
  const translation=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'},client),callback=await run(tx,'callback.create',{message_id:message.id,action:'ACK'},client);
  await tx.save(membership,{...membership.data,...patch});
  expect(await run(tx,'channel.list',{},client)).toEqual([]);expect(await run(tx,'channel.unread',{},client)).toEqual([]);
  for(const [command,input] of [
   ['message.read',{channel_id:channel.id}],['message.send',{channel_id:channel.id,text:'Expired reply',language:'DE'}],['channel.mute',{channel_id:channel.id,muted:true}],['channel.mark_read',{channel_id:channel.id}],['translation.preferences',{channel_id:channel.id,mode:'BUTTON',target_language:'UK'}],['translation.read',{translation_id:translation.translation_id}],['message.ack',{message_id:message.id}],['callback.consume',{action_id:callback.action_id}],
  ] as [string,Data][])await expect(run(tx,command,input,client)).rejects.toMatchObject({code:'ACCESS_DENIED'});
 });
 it('queued translation/delivery/reminder rechecks VIEW and cancels after customer revocation',async()=>{
  const {tx,channel,message,membership}=await setupClient();const request=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'},client);
  const delivery=await run(tx,'delivery.prepare',{message_id:message.id,recipient_id:'client',channel:'WEB'},service);expect(delivery.data.status).toBe('PENDING');
  const notification=await run(tx,'notifications.schedule',{recipient_id:'client',event:'CHAT',category:'CHAT',scheduled_at:tx.now,dedup_key:'synthetic-client-reminder',message_id:message.id},manager);
  await tx.save(membership,{...membership.data,revokedAt:tx.now});
  await expect(run(tx,'delivery.prepare',{message_id:message.id,recipient_id:'client',channel:'WEB'},service)).rejects.toMatchObject({code:'ACCESS_DENIED'});
  await run(tx,'translation.result',{translation_id:request.translation_id,status:'SUCCEEDED',text:'Затверджене повідомлення',provider:'synthetic',model:'synthetic'},service);
  expect((await tx.get('translation_request',request.request_id)).data.status).toBe('CANCELLED');expect(tx.events.filter(e=>e.type==='translation.ready')).toEqual([]);
  expect(await run(tx,'notifications.prepare',{notification_id:notification.id},service)).toEqual({status:'CANCELLED'});expect((await tx.get('notification',notification.id)).data.reason).toBe('ACCESS_REVOKED');
  expect((await tx.get('channel',channel.id)).data.members.find((m:Data)=>m.user_id==='client').revoked_at).toBeUndefined();
 });
 it('does not create or restore an external site channel member without current VIEW for that site',async()=>{const {tx,channel,membership}=await setupClient();await run(tx,'channel.membership',{channel_id:channel.id,user_id:'client',action:'REVOKE'},manager);await tx.save(membership,{...membership.data,permissions:[]});await expect(run(tx,'channel.membership',{channel_id:channel.id,user_id:'client',action:'ADD',external:true},manager)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(tx,'channel.create',{type:'SITE_CLIENT',name:'Invalid site',site_id:'site',member_ids:['client'],external_member_ids:['client']},manager)).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('rejects employee/finance documents in regular channels even for the uploader with finance and media privileges',async()=>{const {tx,channel}=await setup();const finance={...manager,permissions:[...manager.permissions,'finance.payroll','finance.accountant']};for(const data of [{visibility:'CONFIDENTIAL',employeeId:'employee'},{visibility:'INTERNAL',employeeId:'employee'},{visibility:'CONFIDENTIAL'}]){const media=await tx.add('media_asset',{state:'RECEIVED',stage:'DOCUMENT',siteId:'site',uploadedBy:'owner',...data});await expect(run(tx,'message.send',{channel_id:channel.id,text:'Salary attachment',language:'DE',attachment_ids:[media.id]},finance)).rejects.toMatchObject({code:'ACCESS_DENIED'});}expect(await tx.list('message')).toHaveLength(1);});
 it('allows ordinary same-site internal media but denies cross-site and unbound-channel attachments',async()=>{const {tx,channel}=await setup();const same=await tx.add('media_asset',{siteId:'site',state:'RECEIVED',visibility:'INTERNAL',uploadedBy:'employee'});expect((await run(tx,'message.send',{channel_id:channel.id,text:'Site progress',language:'DE',attachment_ids:[same.id]})).data.attachment_ids).toEqual([same.id]);const other=await tx.add('media_asset',{siteId:'other-site',state:'RECEIVED',visibility:'INTERNAL',uploadedBy:'owner'});await expect(run(tx,'message.send',{channel_id:channel.id,text:'Wrong site',language:'DE',attachment_ids:[other.id]},manager)).rejects.toMatchObject({code:'ACCESS_DENIED'});const general=await run(tx,'channel.create',{type:'COMPANY_GENERAL',name:'General',member_ids:['employee']},manager);await expect(run(tx,'message.send',{channel_id:general.id,text:'Unbound site photo',language:'DE',attachment_ids:[same.id]},manager)).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('client channels require a reviewed distinct sanitized copy even when an internal operator owns the original',async()=>{const {tx,channel}=await setupClient();const media=await tx.add('media_asset',{siteId:'site',state:'RECEIVED',visibility:'CLIENT_AFTER_APPROVAL',uploadedBy:'owner',blobKey:'original'});await expect(run(tx,'message.send',{channel_id:channel.id,text:'Unsafe original',language:'DE',attachment_ids:[media.id]},manager)).rejects.toMatchObject({code:'CLIENT_COPY_REQUIRED'});const approved=await tx.save(media,{...media.data,state:'APPROVED_FOR_CLIENT',clientBlobKey:'separate-private-copy',clientSha256:'a'.repeat(64),metadataStripped:true,redactionConfirmed:true,approvedBy:'reviewer',approvedAt:tx.now});expect((await run(tx,'message.send',{channel_id:channel.id,text:'Reviewed image',language:'DE',attachment_ids:[approved.id]},client)).data.attachment_ids).toEqual([approved.id]);const wrong=await tx.add('media_asset',{...approved.data,siteId:'other-site',uploadedBy:'owner'});await expect(run(tx,'message.send',{channel_id:channel.id,text:'Other client image',language:'DE',attachment_ids:[wrong.id]},manager)).rejects.toMatchObject({code:'ACCESS_DENIED'});const reused=await tx.save(approved,{...approved.data,clientBlobKey:approved.data.blobKey});await expect(run(tx,'message.send',{channel_id:channel.id,text:'Original masquerading as copy',language:'DE',attachment_ids:[reused.id]},manager)).rejects.toMatchObject({code:'CLIENT_COPY_REQUIRED'});});
});

describe('durable conversation invariants',()=>{
 it('external customers cannot join internal channels or create an internal chat',async()=>{const {tx}=await setup();await expect(run(tx,'channel.create',{type:'SITE_INTERNAL',name:'leak',member_ids:['client'],external_member_ids:['client'],site_id:'site'},manager)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(tx,'channel.create',{type:'SITE_INTERNAL',name:'leak',member_ids:['client'],site_id:'site'},{...employee,userId:'client',roles:['CLIENT']})).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('revoked membership denies historical reads and cancels pending recipient translations',async()=>{const {tx,channel,message}=await setup();const request=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'});await run(tx,'channel.membership',{channel_id:channel.id,user_id:'employee',action:'REVOKE'},manager);await expect(run(tx,'message.read',{channel_id:channel.id})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect((await tx.get('translation_request',request.request_id)).data.status).toBe('CANCELLED');});
 it('joined users see only history after their membership boundary',async()=>{const {tx,channel}=await setup();tx.now='2026-10-06T11:00:00.000Z';await run(tx,'channel.membership',{channel_id:channel.id,user_id:'employee',action:'REVOKE'},manager);await run(tx,'channel.membership',{channel_id:channel.id,user_id:'employee',action:'ADD'},manager);expect(await run(tx,'message.read',{channel_id:channel.id})).toEqual([]);});
 it('translation requests share versioned cache, while message correction creates a new request',async()=>{const {tx,message}=await setup();const a=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'});const b=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'},{...employee,userId:'other'});expect(a.translation_id).toBe(b.translation_id);expect((await tx.list('translation')).length).toBe(1);await run(tx,'message.edit',{message_id:message.id,text:'Nicht 25 Stück verwenden.'});const c=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'});expect(c.translation_id).not.toBe(a.translation_id);expect((await tx.get('message',message.id)).data.revisions).toHaveLength(2);});
 it('late provider result cannot replace a corrected original or publish a stale translation',async()=>{const {tx,message}=await setup();const translation=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'});await run(tx,'message.edit',{message_id:message.id,text:'Nicht 25 Stück verwenden.'});expect(await run(tx,'translation.result',{translation_id:translation.translation_id,status:'SUCCEEDED',text:'Не використовувати 24 штук.',provider:'test',model:'test'},service)).toEqual({status:'CANCELLED'});expect((await tx.get('message',message.id)).data.text).toBe('Nicht 25 Stück verwenden.');expect(tx.events.filter(e=>e.type==='translation.ready')).toHaveLength(0);});
 it('provider failure preserves original and exposes a typed reason',async()=>{const {tx,message}=await setup();const request=await run(tx,'translation.request',{message_id:message.id,target_language:'UK'});await run(tx,'translation.result',{translation_id:request.translation_id,status:'FAILED',provider:'test',model:'test',error:'PROVIDER_DISABLED'},service);expect(await run(tx,'translation.read',{translation_id:request.translation_id})).toMatchObject({status:'FAILED',reason:'PROVIDER_DISABLED'});expect((await tx.get('message',message.id)).data.text).toBe('Nicht 24 Stück auf Etage 2 verwenden.');});
 it('callbacks bind opaque IDs to one recipient and message version and are consumed once',async()=>{const {tx,message}=await setup();const callback=await run(tx,'callback.create',{message_id:message.id,action:'ACK'});await expect(run(tx,'callback.consume',{action_id:callback.action_id},{...employee,userId:'other'})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});expect(await run(tx,'callback.consume',{action_id:callback.action_id})).toMatchObject({action:'ACK',message_id:message.id});await expect(run(tx,'callback.consume',{action_id:callback.action_id})).rejects.toMatchObject({code:'CALLBACK_EXPIRED'});});
 it('old callbacks are rejected after corrections or expiration',async()=>{const {tx,message}=await setup();const a=await run(tx,'callback.create',{message_id:message.id,action:'ACK'});await run(tx,'message.edit',{message_id:message.id,text:'Correction 25.'});await expect(run(tx,'callback.consume',{action_id:a.action_id})).rejects.toMatchObject({code:'VERSION_CONFLICT'});const b=await run(tx,'callback.create',{message_id:message.id,action:'ACK',ttl_seconds:30});tx.now='2026-10-06T11:00:00.000Z';await expect(run(tx,'callback.consume',{action_id:b.action_id})).rejects.toMatchObject({code:'CALLBACK_EXPIRED'});});
 it('internal copying requires preview confirmation and does not copy attachments automatically',async()=>{const {tx,message}=await setup();const clientChannel=await run(tx,'channel.create',{type:'SITE_CLIENT',name:'client',site_id:'site',member_ids:['client'],external_member_ids:['client']},manager);const preview=await run(tx,'message.copy_preview',{message_id:message.id,target_channel_id:clientChannel.id},manager);expect(await tx.list('message')).toHaveLength(1);const copy=await run(tx,'message.copy_confirm',{preview_id:preview.id},manager);expect(copy.data.visibility).toBe('EXTERNAL');expect(copy.data.attachment_ids).toEqual([]);await expect(run(tx,'message.copy_confirm',{preview_id:preview.id},manager)).rejects.toMatchObject({code:'INVALID_STATE'});});
 it('human ownership suppresses AI until an explicit authorized return',async()=>{const {tx,channel}=await setup();await run(tx,'handoff.take',{channel_id:channel.id},manager);await tx.save(await tx.get('channel',channel.id),{...(await tx.get('channel',channel.id)).data,members:[...channel.data.members,{user_id:'worker',history_from:tx.now}]});await expect(run(tx,'message.send',{channel_id:channel.id,text:'AI response',language:'DE',source:'AI'},service)).rejects.toMatchObject({code:'AI_SUPPRESSED'});await run(tx,'handoff.resume',{channel_id:channel.id,reason:'Authorized return'},manager);expect((await run(tx,'message.send',{channel_id:channel.id,text:'AI response',language:'DE',source:'AI'},service)).data.source).toBe('AI');});
 it('notification retry limit is three and resolution cancels remaining reminders',async()=>{const {tx}=await setup();await tx.add('location_incident',{status:'OPEN'},'incident');const notification=await run(tx,'notifications.schedule',{recipient_id:'employee',event:'ABSENCE',category:'WORK',scheduled_at:tx.now,dedup_key:'absence-1',related_kind:'location_incident',related_id:'incident',max_attempts:3},manager);for(let count=0;count<3;count++){await run(tx,'notifications.prepare',{notification_id:notification.id},service);const result=await run(tx,'notifications.complete',{notification_id:notification.id,succeeded:false,error:'PROVIDER_DISABLED'},service);tx.now=result.data.scheduled_at;}expect((await tx.get('notification',notification.id)).data).toMatchObject({status:'FAILED',attempts:3});const n=await run(tx,'notifications.schedule',{recipient_id:'employee',event:'ABSENCE',category:'WORK',scheduled_at:tx.now,dedup_key:'absence-2',related_kind:'location_incident',related_id:'incident'},manager);await tx.save(await tx.get('location_incident','incident'),{status:'RESOLVED'});expect(await run(tx,'notifications.prepare',{notification_id:n.id},service)).toEqual({status:'CANCELLED'});});
 it('quiet hours defer notifications without consuming an attempt',async()=>{const {tx}=await setup();tx.now='2026-10-06T21:00:00.000Z';const n=await run(tx,'notifications.schedule',{recipient_id:'employee',event:'REMINDER',category:'WORK',scheduled_at:tx.now,dedup_key:'quiet-1'},manager);expect(await run(tx,'notifications.prepare',{notification_id:n.id},service)).toMatchObject({status:'RETRY_SCHEDULED',reason:'QUIET_HOURS'});expect((await tx.get('notification',n.id)).data.attempts).toBe(0);});
});
