import {describe,expect,it} from 'vitest';
import {communicationsCommands} from '../packages/domain/communications.ts';
import {ROLE_PERMISSIONS} from '../packages/domain/permissions.ts';
import {DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';
import {addBusinessMinutes,businessCalendarSchema,handoffDeadlines,queueHandoffSla,handoffGeneration,handoffManagerAllowed,handoffReminderReadable,handoffQueueNotice,type BusinessCalendar} from '../packages/domain/handoff-calendar.ts';

const definition:BusinessCalendar={name:'Explicit pilot calendar',timezone:'Europe/Berlin',weekdays:[1,2,3,4,5],windows:[{start:'09:00',end:'17:00'}],holidays:[],managerUserId:'manager',siteIds:[]};
const makeCalendar=(data:Data={}):Entity=>({id:'calendar',kind:'business_calendar',companyId:'company',version:2,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-02T00:00:00Z',data:{...definition,status:'APPROVED',active:true,createdBy:'author',approvedBy:'approver',approvedAt:'2026-01-02T00:00:00Z',...data}});
class MemoryTx implements Transaction{
 rows=new Map<string,Entity>();events:Array<{type:string;data:Data}>=[];sequence=0;now='2026-10-06T08:00:00.000Z';
 async get<T extends Data=Data>(kind:string,id:string){const row=this.rows.get(kind+':'+id);if(!row)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(row) as Entity<T>;}
 async list<T extends Data=Data>(kind:string){return [...this.rows.values()].filter(row=>row.kind===kind).map(row=>structuredClone(row) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`synthetic-${++this.sequence}`){const row={id,kind,companyId:'company',version:1,createdAt:this.now,updatedAt:this.now,data:structuredClone(data)};this.rows.set(kind+':'+id,row);return structuredClone(row);}
 async save(row:Entity,data:Data,expectedVersion=row.version){const current=await this.get(row.kind,row.id);if(current.version!==expectedVersion)throw new DomainError('VERSION_CONFLICT');const saved={...row,data:structuredClone(data),version:current.version+1,updatedAt:this.now};this.rows.set(row.kind+':'+row.id,saved);return structuredClone(saved);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
}
function actor(id:string):Actor{return {userId:id,companyId:'company',roles:['OWNER'],permissions:[...ROLE_PERMISSIONS.OWNER!,'chat.manage','chat.read','chat.write'],siteIds:[],customerIds:[],warehouseIds:[],mfaVerified:true};}
function context(tx:MemoryTx,a=actor('author'),version?:number):CommandContext{return {tx,actor:a,now:tx.now,expectedVersion:version,idempotencyKey:'synthetic-key',requireOwn:id=>{if(id!==a.userId)throw new DomainError('ACCESS_DENIED');},requireSite:id=>{if(!a.permissions.includes('scope.company')&&!a.siteIds.includes(id))throw new DomainError('ACCESS_DENIED');}};}
async function command(tx:MemoryTx,name:string,input:Data,a=actor('author'),version?:number){const def=communicationsCommands[name]!,before=structuredClone(tx.rows),events=structuredClone(tx.events);try{return await def.handler(context(tx,a,version),def.schema.parse(input));}catch(error){tx.rows=before;tx.events=events;throw error;}}
async function setup(){const tx=new MemoryTx();for(const userId of ['author','approver','manager'])await tx.add('user',{active:true,roles:['OWNER'],permissions:['chat.manage','chat.read','chat.write'],siteIds:[]},userId);await tx.add('user',{active:true,roles:['SERVICE_ACCOUNT'],permissions:['integration.process','chat.read','chat.write']},'worker');const original=await tx.add('message',{channel_id:'private',text:'Private original, not a reminder title',language:'UK'},'original');const channel=await tx.add('channel',{type:'PRIVATE_CUSTOMER_ASSISTANT',created_by:'guest',members:[{user_id:'guest',external:true,joined_at:tx.now,history_from:tx.now},{user_id:'worker',external:false,joined_at:tx.now,history_from:tx.now}],handoff:{state:'HANDOFF_PENDING',owner_id:null,requested_at:tx.now,source_message_id:original.id}},'private');return {tx,channel};}
async function approved(tx:MemoryTx){tx.now='2026-10-06T07:00:00.000Z';const draft=await command(tx,'handoff.calendar.create',definition);tx.now='2026-10-06T07:01:00.000Z';const calendar=await command(tx,'handoff.calendar.approve',{calendar_id:draft.id},actor('approver'),draft.version);tx.now='2026-10-06T08:00:00.000Z';return calendar;}

describe('explicit Berlin handoff business minutes',()=>{
 it('requires actual timezone, weekdays, windows, holidays, routing scope and recipient without defaults',()=>{for(const field of ['timezone','weekdays','windows','holidays','managerUserId','siteIds']){const input={...definition};delete(input as Data)[field];expect(businessCalendarSchema.safeParse(input).success).toBe(false);}expect(businessCalendarSchema.safeParse({...definition,timezone:'UTC'}).success).toBe(false);});
 it.each([{weekdays:[1,1]},{windows:[{start:'09:00',end:'09:00'}]},{windows:[{start:'22:00',end:'07:00'}]},{windows:[{start:'09:00',end:'12:00'},{start:'11:00',end:'14:00'}]},{holidays:['2026-02-30']},{holidays:['2026-12-25','2026-12-25']}])('rejects an invalid explicit calendar%j',data=>{expect(businessCalendarSchema.safeParse({...definition,...data}).success).toBe(false);});
 it('keeps 15/30 pilot targets separate and makes no customer promise',()=>{expect(handoffDeadlines(makeCalendar(),'2026-10-06T08:00:00Z')).toEqual({status:'CALCULATED',responseDueAt:'2026-10-06T08:15:00.000Z',managerReminderAt:'2026-10-06T08:30:00.000Z'});});
 it('continues over a weekend instead of counting closed time',()=>{expect(addBusinessMinutes(definition,'2026-10-02T14:50:00Z',15)).toBe('2026-10-05T07:05:00.000Z');});
 it('uses explicitly supplied holidays rather than guessing national or regional holidays',()=>{expect(addBusinessMinutes({...definition,holidays:['2026-10-05']},'2026-10-02T14:50:00Z',30)).toBe('2026-10-06T07:20:00.000Z');expect(addBusinessMinutes(definition,'2026-12-25T08:00:00Z',15)).toBe('2026-12-25T08:15:00.000Z');});
 it('excludes a configured lunch closure',()=>{expect(addBusinessMinutes({...definition,windows:[{start:'09:00',end:'12:00'},{start:'13:00',end:'17:00'}]},'2026-01-06T10:55:00Z',15)).toBe('2026-01-06T12:10:00.000Z');});
 it('preserves partial seconds at an end boundary',()=>{expect(addBusinessMinutes(definition,'2026-10-02T14:59:50Z',15)).toBe('2026-10-05T07:14:50.000Z');});
 it.each([['2026-03-27T15:50:00Z','2026-03-30T07:05:00.000Z'],['2026-10-23T14:50:00Z','2026-10-26T08:05:00.000Z']])('uses real Berlin offset across weekend%s', (start,expected)=>{expect(addBusinessMinutes(definition,start,15)).toBe(expected);});
 it('counts both elapsed working hours of an explicitly open autumn Sunday fold',()=>{expect(addBusinessMinutes({...definition,weekdays:[7],windows:[{start:'02:00',end:'03:00'}]},'2026-10-25T00:10:00Z',90)).toBe('2026-10-25T01:40:00.000Z');});
 it('never invents a nonexistent spring working hour',()=>{expect(addBusinessMinutes({...definition,weekdays:[7],windows:[{start:'02:00',end:'03:00'}]},'2026-03-29T00:59:00Z',15)).toBe('2026-04-05T00:15:00.000Z');});
 it.each([undefined,makeCalendar({status:'DRAFT'}),makeCalendar({active:false}),makeCalendar({approvedBy:'author'}),makeCalendar({approvedAt:'2026-10-06T10:00:00Z'})])('calculates no deadline from an absent, unapproved, revoked, self-approved or later-approved source',calendar=>{expect(handoffDeadlines(calendar,'2026-10-06T08:00:00Z')).toEqual({status:'NO_APPROVED_CALENDAR'});});
});
describe('handoff calendar approval, queue authority and suppression (in-memory command doubles)',()=>{
 it('requires MFA, current active authority, independent approver and displayed version',async()=>{const {tx}=await setup();await expect(command(tx,'handoff.calendar.create',definition,{...actor('author'),mfaVerified:false})).rejects.toMatchObject({code:'NEEDS_REAUTH'});const draft=await command(tx,'handoff.calendar.create',definition);await expect(command(tx,'handoff.calendar.approve',{calendar_id:draft.id},actor('author'),draft.version)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(command(tx,'handoff.calendar.approve',{calendar_id:draft.id},actor('approver'),draft.version+1)).rejects.toMatchObject({code:'VERSION_CONFLICT'});const approver=await tx.get('user','approver');await tx.save(approver,{...approver.data,active:false});await expect(command(tx,'handoff.calendar.approve',{calendar_id:draft.id},actor('approver'),draft.version)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect((await tx.get('business_calendar',draft.id)).data.status).toBe('DRAFT');});
 it('stores canonical queue state but no guessed SLA or recipient when no approved calendar exists',async()=>{const {tx,channel}=await setup(),saved=await queueHandoffSla(tx,channel,tx.now);expect(saved.data.handoff).toMatchObject({state:'HANDOFF_PENDING',canonical_state:'HUMAN_QUEUED',sla:{status:'NO_APPROVED_CALENDAR',customer_promise:false}});expect(saved.data.handoff.sla.manager_user_id).toBeUndefined();expect(tx.events).toEqual([]);});
 it('durably binds exactly one 30-business-minute job to the same request and approved revision',async()=>{const {tx,channel}=await setup(),calendar=await approved(tx),saved=await queueHandoffSla(tx,channel,tx.now);await queueHandoffSla(tx,saved,tx.now);const jobs=tx.events.filter(e=>e.type==='handoff.manager_reminder');expect(jobs).toHaveLength(1);expect(jobs[0]!.data).toEqual({channelId:channel.id,generation:handoffGeneration(channel),calendarId:calendar.id,calendarVersion:calendar.version,managerUserId:'manager',requestedAt:channel.data.handoff.requested_at,not_before:'2026-10-06T08:30:00.000Z'});expect(JSON.stringify(jobs)).not.toContain('Private original');expect(saved.data.handoff.sla.responseDueAt).toBe('2026-10-06T08:15:00.000Z');});
 it('does not guess among overlapping approved routes',async()=>{const {tx,channel}=await setup(),calendar=await approved(tx);await tx.add('business_calendar',calendar.data,'duplicate-route');const saved=await queueHandoffSla(tx,channel,tx.now);expect(saved.data.handoff.sla.status).toBe('NO_APPROVED_CALENDAR');expect(tx.events.filter(e=>e.type==='handoff.manager_reminder')).toEqual([]);});
 it('claims atomically while retaining SLA provenance and cancelling the queued target',async()=>{const {tx,channel}=await setup();await approved(tx);const pending=await queueHandoffSla(tx,channel,tx.now),taken=await command(tx,'handoff.take',{channel_id:channel.id},actor('manager'),pending.version);expect(taken.version).toBe((await tx.get('channel',channel.id)).version);expect(taken.data.handoff).toMatchObject({state:'HUMAN_ACTIVE',owner_id:'manager',requested_at:channel.data.handoff.requested_at,sla:{reminder_state:'CANCELLED',cancellation_reason:'HUMAN_CLAIMED',responseDueAt:'2026-10-06T08:15:00.000Z'}});expect(taken.data.members.filter((m:Data)=>m.source==='OPERATOR_CLAIM')).toHaveLength(1);});
 it('exposes an explicit resolved state, suppresses AI, and requires an explicit owner return',async()=>{const {tx,channel}=await setup(),taken=await command(tx,'handoff.take',{channel_id:channel.id},actor('manager'),channel.version),resolved=await command(tx,'handoff.resolve',{channel_id:channel.id,reason:'Customer issue resolved.'},actor('manager'),taken.version);expect(resolved.data.handoff.state).toBe('RESOLVED');await expect(command(tx,'message.send',{channel_id:channel.id,text:'Sales prose after resolution',language:'DE',source:'AI'},{...actor('worker'),roles:['SERVICE_ACCOUNT']})).rejects.toMatchObject({code:'AI_SUPPRESSED'});await expect(command(tx,'handoff.resume',{channel_id:channel.id,reason:'Unauthorized return'},actor('approver'),resolved.version)).rejects.toMatchObject({code:'ACCESS_DENIED'});const returned=await command(tx,'handoff.resume',{channel_id:channel.id,reason:'Explicit owner return'},actor('manager'),resolved.version);expect(returned.data.handoff.state).toBe('AI_ACTIVE');});
 it('blocks queued AI sales while permitting only one deterministic service queue fact per generation',async()=>{const {tx,channel}=await setup(),service={...actor('worker'),roles:['SERVICE_ACCOUNT'],permissions:['integration.process','chat.read','chat.write']};await expect(command(tx,'message.send',{channel_id:channel.id,text:'Invented price or time',language:'UK',source:'AI'},service)).rejects.toMatchObject({code:'AI_SUPPRESSED'});const first=await command(tx,'handoff.queue_notice',{channel_id:channel.id},service),second=await command(tx,'handoff.queue_notice',{channel_id:channel.id},service);expect(first.id).toBe(second.id);expect(first.data).toMatchObject({source:'SYSTEM',language:'UK',text:handoffQueueNotice('UK'),customer_promise:false});expect(tx.events).toEqual([]);expect(communicationsCommands['handoff.queue_notice']!.schema.safeParse({channel_id:channel.id,text:'A promise'}).success).toBe(false);});
 it('checks fresh private-inbox manager scope and explicit membership revocation without granting history',async()=>{const {tx,channel}=await setup();expect(await handoffManagerAllowed(tx,'manager',channel,tx.now)).toBe(true);expect(channel.data.members.some((m:Data)=>m.user_id==='manager')).toBe(false);const revoked=await tx.save(channel,{...channel.data,members:[...channel.data.members,{user_id:'manager',revoked_at:tx.now,source:'MANUAL'}]});expect(await handoffManagerAllowed(tx,'manager',revoked,tx.now)).toBe(false);const manager=await tx.get('user','manager');await tx.save(manager,{...manager.data,roles:['EMPLOYEE'],permissions:[]});expect(await handoffManagerAllowed(tx,'manager',channel,tx.now)).toBe(false);});
 it('hides a historical reminder after a request generation changes or selected manager loses authority',async()=>{const {tx,channel}=await setup(),calendar=await approved(tx),pending=await queueHandoffSla(tx,channel,tx.now),available=await tx.save(pending,{...pending.data,handoff:{...pending.data.handoff,sla:{...pending.data.handoff.sla,reminder_state:'WEB_AVAILABLE'}}}),notice=await tx.add('notification',{event:'HANDOFF_MANAGER_REMINDER',recipient_id:'manager',handoff_channel_id:channel.id,handoff_generation:handoffGeneration(channel),handoff_calendar_id:calendar.id,handoff_calendar_version:calendar.version});expect(await handoffReminderReadable(tx,actor('manager'),notice,tx.now)).toBe(true);const manager=await tx.get('user','manager');await tx.save(manager,{...manager.data,active:false});expect(await handoffReminderReadable(tx,actor('manager'),notice,tx.now)).toBe(false);await tx.save(await tx.get('user','manager'),manager.data);await tx.save(available,{...available.data,handoff:{...available.data.handoff,requested_at:'2026-10-06T08:01:00Z'}});expect(await handoffReminderReadable(tx,actor('manager'),notice,tx.now)).toBe(false);});
});
