import {afterAll,afterEach,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Database} from '../apps/api/database.ts';
import {Engine} from '../apps/api/engine.ts';
import {WorkerRunner,leaseOutbox,serviceId,type OutboxJob} from '../apps/worker/runner.ts';
import {queueHandoffSla} from '../packages/domain/handoff-calendar.ts';
import type {Actor,Data} from '../packages/domain/core.ts';

// These cases require PostgreSQL. Synthetic scheduling advances only the test's
// lease availability/worker clock; no real elapsed pilot SLA/provider acceptance.
const postgres=process.env.DATABASE_URL?describe:describe.skip;
postgres('V4 handoff calendar: genuine PostgreSQL command, lease and recipient authority',()=>{
 let db:Database,engine:Engine,worker:WorkerRunner,company:string,author:Actor,approver:Actor,manager:Actor,workerClock:number;
 const execute=(a:Actor,name:string,input:Data,version?:number)=>engine.execute(a,name,{input,expected_version:version,idempotency_key:randomUUID()});
 const row=(kind:string,id:string)=>db.transaction(company,'SYNTHETIC_HANDOFF_CALENDAR_QA',tx=>tx.get(kind,id));
 const rows=(kind:string)=>db.transaction(company,'SYNTHETIC_HANDOFF_CALENDAR_QA',tx=>tx.list(kind));
 const patch=(kind:string,id:string,data:Data)=>db.transaction(company,'SYNTHETIC_HANDOFF_CALENDAR_QA',async tx=>{const value=await tx.get(kind,id);return tx.save(value,{...value.data,...data});});
 const definition=()=>({name:'Synthetic explicitly configured calendar',timezone:'Europe/Berlin',weekdays:[1,2,3,4,5,6,7],windows:[{start:'00:00',end:'23:59'}],holidays:[],managerUserId:'manager',siteIds:[]});
 async function approved(){const draft=await execute(author,'handoff.calendar.create',definition());return execute(approver,'handoff.calendar.approve',{calendar_id:draft.id},draft.version);}
 async function pending(withCalendar=true){const calendar=withCalendar?await approved():undefined;const channel=await db.transaction(company,'SYNTHETIC_QUEUE_SOURCE',async tx=>{const requested=new Date().toISOString(),original=await tx.add('message',{channel_id:'private',author_id:'guest',text:'Synthetic private original must not be disclosed in manager notice',language:'UK',message_version:1});const channel=await tx.add('channel',{type:'PRIVATE_CUSTOMER_ASSISTANT',name:'Synthetic private original channel',created_by:'guest',members:[{user_id:'guest',external:true,joined_at:requested,history_from:requested},{user_id:serviceId,external:false,joined_at:requested,history_from:requested}],handoff:{state:'HANDOFF_PENDING',owner_id:null,requested_at:requested,source_message_id:original.id}},'private');return queueHandoffSla(tx,channel,requested);});return {calendar,channel};}
 async function take(type='handoff.manager_reminder'){const candidates=(await db.query("SELECT id,data FROM outbox WHERE company_id=$1 AND type=$2 AND status='PENDING' ORDER BY created_at,id",[company,type])).rows;expect(candidates.length).toBeGreaterThan(0);const selected=candidates[0]!;workerClock=selected.data.not_before?Date.parse(selected.data.not_before):Date.now();await db.query("UPDATE outbox SET available_at=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND id=$2",[company,selected.id]);const job=(await leaseOutbox(db,100,120000,company)).find(job=>job.id===selected.id);expect(job).toBeDefined();return job!;}
 async function fallbackJob(){await approved();await db.transaction(company,'SYNTHETIC_CURRENT_AI_FALLBACK_SOURCE',async tx=>{const now=new Date().toISOString();await tx.add('assistant_config',{status:'ACTIVE',configVersion:1,provider:'DEEPSEEK',testOnly:true},'fallback-config');await tx.add('channel',{type:'PRIVATE_CUSTOMER_ASSISTANT',created_by:'guest',members:[{user_id:'guest',external:true,joined_at:now,history_from:now}],handoff:{state:'AI_ACTIVE',owner_id:null}},'fallback-channel');await tx.add('message',{channel_id:'fallback-channel',author_id:'guest',text:'Synthetic private AI original',language:'UK',message_version:1},'fallback-message');await tx.event('assistant.answer_requested',{channelId:'fallback-channel',messageId:'fallback-message',actorId:'guest',configId:'fallback-config',configVersion:1,language:'UK',sourceChannel:'WEB'});});return take('assistant.answer_requested');}
 const fallback=(job:OutboxJob)=>(worker as unknown as {fallback:(job:OutboxJob,reason:string)=>Promise<void>}).fallback(job,'SYNTHETIC_PROVIDER_FAILURE_NO_PROVIDER_CALL');
 async function fingerprint(){const result:Data={};for(const table of ['aggregates','aggregate_revisions','audit_log','outbox','command_receipts'])result[table]=(await db.query(`SELECT count(*)::int n,md5(coalesce(string_agg(to_jsonb(r)::text,E'\n' ORDER BY to_jsonb(r)::text),'')) hash FROM ${table} r WHERE company_id=$1`,[company])).rows[0];return result;}
 beforeAll(async()=>{db=new Database();await db.migrate();engine=new Engine(db,'TEST');});
 beforeEach(async()=>{company='synthetic-handoff-calendar-'+randomUUID();await db.transaction(company,'SYNTHETIC_SEED',async tx=>{await tx.add('company',{name:'Synthetic handoff calendar QA',operatingMode:'TEST',synthetic:true},company);for(const userId of ['author','approver','manager'])await tx.add('user',{active:true,roles:['OWNER'],permissions:['chat.manage','chat.read','chat.write'],siteIds:[],warehouseIds:[],customerIds:[]},userId);await tx.add('user',{active:true,roles:['GUEST'],permissions:['chat.read','chat.write'],siteIds:[],warehouseIds:[],customerIds:[]},'guest');await tx.add('notification_setting',{user_id:'manager',language:'UK',opted_out:false,quiet_start:20,quiet_end:7},'manager-setting');});author={...await engine.getActor('author',company),mfaVerified:true};approver={...await engine.getActor('approver',company),mfaVerified:true};manager=await engine.getActor('manager',company);workerClock=Date.now();worker=new WorkerRunner(db,engine,{companyId:company,appMode:'TEST',now:()=>new Date(workerClock)});await worker.initialize();});
 afterAll(async()=>{if(db)await db.pool.end();});
 afterEach(()=>vi.restoreAllMocks());

 it('uses real independent current approvals and leaves no receipt/effect for self-approval or missing MFA',async()=>{await expect(execute({...author,mfaVerified:false},'handoff.calendar.create',definition())).rejects.toMatchObject({code:'NEEDS_REAUTH'});const draft=await execute(author,'handoff.calendar.create',definition()),before=await fingerprint();await expect(execute(author,'handoff.calendar.approve',{calendar_id:draft.id},draft.version)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await fingerprint()).toEqual(before);const calendar=await execute(approver,'handoff.calendar.approve',{calendar_id:draft.id},draft.version);expect(calendar.data).toMatchObject({status:'APPROVED',active:true,createdBy:'author',approvedBy:'approver'});});
 it('stores no guessed calendar, manager, deadline or due job without an approved source',async()=>{const {channel}=await pending(false);expect(channel.data.handoff).toMatchObject({canonical_state:'HUMAN_QUEUED',sla:{status:'NO_APPROVED_CALENDAR',customer_promise:false}});expect(channel.data.handoff.sla.manager_user_id).toBeUndefined();expect((await db.query("SELECT id FROM outbox WHERE company_id=$1 AND type='handoff.manager_reminder'",[company])).rows).toEqual([]);});
 it('commits one exact queued generation/version/deadline and one durable due event atomically',async()=>{const {channel,calendar}=await pending();await db.transaction(company,'SYNTHETIC_IDEMPOTENT_QUEUE',tx=>queueHandoffSla(tx,channel,new Date().toISOString()));const jobs=(await db.query("SELECT data,available_at FROM outbox WHERE company_id=$1 AND type='handoff.manager_reminder'",[company])).rows;expect(jobs).toHaveLength(1);expect(jobs[0].data).toMatchObject({channelId:channel.id,calendarId:calendar!.id,calendarVersion:calendar!.version,managerUserId:'manager',requestedAt:channel.data.handoff.requested_at,not_before:channel.data.handoff.sla.managerReminderAt});expect(new Date(jobs[0].available_at).toISOString()).toBe(channel.data.handoff.sla.managerReminderAt);expect(JSON.stringify(jobs)).not.toContain('Synthetic private original');});
 it('under a real lease makes one minimal web notice available to the selected current manager without a membership grant',async()=>{const {channel}=await pending(),job=await take();await worker.handle(job);await worker.handle(job);const notices=await rows('notification');expect(notices).toHaveLength(1);expect(notices[0].data).toMatchObject({recipient_id:'manager',channel:'WEB',status:'WEB_AVAILABLE',provider_state:'NOT_APPLICABLE',language:'UK',customer_promise:false});expect(JSON.stringify(notices)).not.toContain('Synthetic private original');const current=await row('channel',channel.id);expect(current.data.members.some((m:Data)=>m.user_id==='manager')).toBe(false);expect(current.data.handoff.sla.reminder_state).toBe('WEB_AVAILABLE');expect((await engine.readEntities(manager,'notification')).map(n=>n.id)).toEqual([notices[0].id]);});
 it('rejects expired and stolen actual leases before revisions, audit, receipts, notices or extra outbox effects',async()=>{await pending();const job=await take(),before=await fingerprint();await expect(worker.handle({...job,lease_token:'SYNTHETIC_STOLEN_LEASE'})).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await fingerprint()).toEqual(before);await db.query("UPDATE outbox SET leased_until=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND id=$2",[company,job.id]);const expired=await fingerprint();await expect(worker.handle(job)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await fingerprint()).toEqual(expired);});
 it('rejects forged event inputs under a genuine lease without modifying current source bindings',async()=>{await pending();const job=await take(),before=await fingerprint();await expect(worker.handle({...job,data:{...job.data,managerUserId:'author'}})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await fingerprint()).toEqual(before);});
 it('suppresses the due notice after current selected-manager permission removal',async()=>{const {channel}=await pending(),job=await take();await patch('user','manager',{roles:['EMPLOYEE'],permissions:[]});await worker.process(job);expect(await rows('notification')).toEqual([]);expect((await row('channel',channel.id)).data.handoff.sla).toMatchObject({reminder_state:'CANCELLED',cancellation_reason:'OPERATOR_AUTHORITY_CHANGED'});});
 it('suppresses a due notice after explicit calendar retirement or optout',async()=>{const {channel,calendar}=await pending(),job=await take();await execute(approver,'handoff.calendar.retire',{calendar_id:calendar!.id,reason:'Explicit pilot calendar retirement'},calendar!.version);await worker.process(job);expect(await rows('notification')).toEqual([]);expect((await row('channel',channel.id)).data.handoff.sla.cancellation_reason).toBe('CALENDAR_CHANGED');});
 it('honours current manager optout without creating a substitute recipient',async()=>{const {channel}=await pending(),job=await take();await patch('notification_setting','manager-setting',{opted_out:true});await worker.process(job);expect(await rows('notification')).toEqual([]);expect((await row('channel',channel.id)).data.handoff.sla.cancellation_reason).toBe('OPTED_OUT');});
 it('cancels a queued reminder at actual atomic claim and never lets the already-running old lease notify',async()=>{const {channel}=await pending(),job=await take(),claimed=await execute(manager,'handoff.take',{channel_id:channel.id},channel.version);expect(claimed.data.handoff.sla.reminder_state).toBe('CANCELLED');await worker.process(job);expect(await rows('notification')).toEqual([]);const resolved=await execute(manager,'handoff.resolve',{channel_id:channel.id,reason:'Explicit reviewed completion'},claimed.version);expect(resolved.data.handoff.state).toBe('RESOLVED');const returned=await execute(manager,'handoff.resume',{channel_id:channel.id,reason:'Explicit reviewed return to AI'},resolved.version);expect(returned.data.handoff.state).toBe('AI_ACTIVE');});
 it('removes historical notification visibility when fresh private-inbox authority is revoked',async()=>{await pending();await worker.handle(await take());const notice=(await rows('notification'))[0]!;expect((await engine.readEntities(manager,'notification')).map(n=>n.id)).toContain(notice.id);await patch('user','manager',{active:false});const fresh={...manager,roles:['EMPLOYEE'],permissions:[]};expect(await db.transaction(company,'SYNTHETIC_READ_CHECK',tx=>engine.visible(tx,fresh,notice))).toBe(false);});
 it('stores exactly one deterministic queue fact with real service commands and no customer time/crew promise',async()=>{const {channel}=await pending(false),service=await engine.getActor(serviceId,company),first=await execute(service,'handoff.queue_notice',{channel_id:channel.id}),second=await execute(service,'handoff.queue_notice',{channel_id:channel.id});expect(first.id).toBe(second.id);expect(first.data).toMatchObject({source:'SYSTEM',language:'UK',customer_promise:false});await expect(execute(service,'message.send',{channel_id:channel.id,text:'Forbidden queued sales message',language:'UK',source:'AI'})).rejects.toMatchObject({code:'AI_SUPPRESSED'});expect((await rows('message')).filter(m=>m.data.handoff_queue_generation)).toHaveLength(1);});
 it('actual worker fallback binds one queued transition/decision/calendar job to the genuine canonical AI job',async()=>{const job=await fallbackJob();await fallback(job);await fallback(job);expect((await row('channel','fallback-channel')).data.handoff).toMatchObject({state:'HANDOFF_PENDING',canonical_state:'HUMAN_QUEUED',source_message_id:'fallback-message',sla:{status:'CALCULATED',customer_promise:false}});expect(await rows('decision')).toHaveLength(1);expect((await db.query("SELECT id FROM outbox WHERE company_id=$1 AND type='handoff.manager_reminder'",[company])).rows).toHaveLength(1);});
 it('actual fallback rejects stolen/expired leases and forged canonical config/actor payload before any effects',async()=>{const job=await fallbackJob(),before=await fingerprint();await expect(fallback({...job,lease_token:'SYNTHETIC_WRONG_LEASE'})).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await fingerprint()).toEqual(before);await expect(fallback({...job,data:{...job.data,actorId:'manager',configVersion:2}})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await fingerprint()).toEqual(before);await db.query("UPDATE outbox SET leased_until=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND id=$2",[company,job.id]);const expired=await fingerprint();await expect(fallback(job)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await fingerprint()).toEqual(expired);});
 it.each(['source-actor','service-actor'])('actual fallback rechecks revoked%s authority and rolls back all new source/SLA/decision effects',async kind=>{const job=await fallbackJob();if(kind==='source-actor')await patch('user','guest',{active:false});else await patch('user',serviceId,{roles:['EMPLOYEE'],permissions:[]});const before=await fingerprint();await expect(fallback(job)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await fingerprint()).toEqual(before);expect((await row('channel','fallback-channel')).data.handoff.state).toBe('AI_ACTIVE');});
 it('the final actual SQL fence rolls back source/revision/audit/decision/outbox writes after a lease expires inside the transaction (controlled SQL expiry)',async()=>{const job=await fallbackJob(),before=await fingerprint(),original=db.transaction.bind(db);let expired=false;vi.spyOn(db,'transaction').mockImplementation(async(companyId,actorId,fn,timeout,readOnly)=>original(companyId,actorId,async tx=>{if(actorId===serviceId){const save=tx.save.bind(tx);tx.save=(async(entity,data,version)=>{const saved=await save(entity,data,version);if(!expired&&entity.kind==='channel'&&entity.id==='fallback-channel'){expired=true;await tx.query("UPDATE outbox SET leased_until=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND id=$2",[company,job.id]);}return saved;}) as typeof tx.save;}return fn(tx);},timeout,readOnly));await expect(fallback(job)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});vi.restoreAllMocks();expect(expired).toBe(true);expect(await fingerprint()).toEqual(before);expect((await row('channel','fallback-channel')).data.handoff.state).toBe('AI_ACTIVE');});
});
