import { describe,it,expect } from 'vitest';
import * as OTPAuth from 'otpauth';
import type { Request,Response } from 'express';
import { hashPassword,verifyPassword,hashToken,opaqueToken,csrfFor,parseCookies,requireCsrf,sealSecret,openSecret,validateTotp,AuthService,RateLimiter,type DatabaseLike,type EngineLike,type SqlTransaction } from '../apps/api/auth.js';
import { identityCommands,activateInvitation,permissionsForRoles } from '../packages/domain/identity.js';
import { DomainError,type Actor,type Data,type Entity,type CommandContext } from '../packages/domain/core.js';
class FixtureDb implements DatabaseLike,SqlTransaction {
 rows=new Map<string,Entity>();sessions:Data[]=[];credentials:Data[]=[];events:Data[]=[];seq=0;companyId='company';
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const e=this.rows.get(`${kind}:${id}`);if(!e||e.companyId!==this.companyId)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(e) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.rows.values()].filter(e=>e.kind===kind&&e.companyId===this.companyId).map(e=>structuredClone(e) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`row-${++this.seq}`){const e={id,kind,data:structuredClone(data),companyId:this.companyId,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.rows.set(`${kind}:${id}`,e);return structuredClone(e);}
 async save<T extends Data=Data>(e:Entity<T>,data:T,version=e.version){const old=await this.get(e.kind,e.id);if(old.version!==version)throw new DomainError('VERSION_CONFLICT');const next={...old,version:old.version+1,data:structuredClone(data)};this.rows.set(`${e.kind}:${e.id}`,next);return structuredClone(next);}
 async event(type:string,data:Data){this.events.push({type,...data});}
 async transaction<T>(companyId:string,_actorId:string,fn:(tx:SqlTransaction)=>Promise<T>):Promise<T>{const old=this.companyId;this.companyId=companyId;const before={rows:structuredClone(this.rows),sessions:structuredClone(this.sessions),credentials:structuredClone(this.credentials),events:structuredClone(this.events)};try{return await fn(this);}catch(error){Object.assign(this,before);throw error;}finally{this.companyId=old;}}
 async query(statement:string,params:any[]=[]){if(statement.startsWith('INSERT INTO auth_sessions')){this.sessions.push({token_hash:params[0],user_id:params[1],company_id:params[2],expires_at:params[3],mfa_verified:params[4],created_at:new Date().toISOString()});return {rows:[]};}if(statement.startsWith('SELECT user_id,company_id,mfa_verified'))return {rows:this.sessions.filter(s=>s.token_hash===params[0]&&s.company_id===params[1]&&!s.revoked_at&&Date.parse(s.expires_at)>Date.now())};if(statement.startsWith('INSERT INTO auth_credentials')){this.credentials.push({user_id:params[0],company_id:params[1],password_hash:params[2],totp_secret:params[3],totp_last_counter:params[4]});return {rows:[]};}if(statement.startsWith('SELECT password_hash'))return {rows:this.credentials.filter(c=>c.user_id===params[0]&&c.company_id===params[1])};if(statement.startsWith('UPDATE auth_credentials SET totp_last_counter')){const row=this.credentials.find(c=>c.user_id===params[0]&&c.company_id===params[1]&&c.totp_last_counter<params[2]);if(row){row.totp_last_counter=params[2];return {rows:[{user_id:row.user_id}]};}return {rows:[]};}if(statement.startsWith('UPDATE auth_sessions')){for(const s of this.sessions)if((statement.includes('token_hash')?s.token_hash:s.user_id)===params[0]&&s.company_id===params[1])s.revoked_at=new Date().toISOString();return {rows:[]};}throw new Error(`Unexpected fixture SQL ${statement}`);}
}
const owner:Actor={userId:'owner',companyId:'company',roles:['OWNER'],permissions:['identity.manage','role.manage','legal.manage','company.manage','bot.manage','audit.read','scope.company'],siteIds:['*'],warehouseIds:['*'],customerIds:[],mfaVerified:true};
const engine=(db:FixtureDb):EngineLike=>({registry:{},execute:async()=>{},readEntities:async()=>[],getActor:async(userId,companyId)=>db.transaction(companyId,userId,async tx=>{const user=await tx.get('user',userId);if(!user.data.active)throw new DomainError('ACCESS_DENIED');return {...owner,userId,companyId,roles:user.data.roles,permissions:[...permissionsForRoles(user.data.roles),...(user.data.permissions??[])],siteIds:user.data.siteIds??[],mfaVerified:false};})});
const request=(headers:Record<string,string>={},ip='127.0.0.1')=>({get:(name:string)=>headers[name.toLowerCase()],ip,protocol:'https'} as unknown as Request);
function response(){const state:any={cookies:[],clear:[]};state.cookie=(name:string,token:string,options:Data)=>state.cookies.push({name,token,options});state.clearCookie=(name:string)=>state.clear.push(name);return state as Response & {cookies:any[];clear:string[]};}
function ctx(db:FixtureDb,actor=owner):CommandContext{return {tx:db,actor,now:new Date().toISOString(),idempotencyKey:'identity-test',requireSite:s=>{if(!actor.siteIds.includes('*')&&!actor.siteIds.includes(s))throw new DomainError('ACCESS_DENIED');},requireOwn:s=>{if(actor.userId!==s)throw new DomainError('ACCESS_DENIED');}};}
async function run(db:FixtureDb,name:string,input:Data,actor=owner){const def=identityCommands[name]!;return db.transaction(actor.companyId,actor.userId,tx=>def.handler({...ctx(db,actor),tx},def.schema.parse(input)));}

describe('identity credential boundaries',()=>{
 it('scrypt uses unique salts and verifies only the exact password',async()=>{const a=await hashPassword('Secure synthetic password 123!'),b=await hashPassword('Secure synthetic password 123!');expect(a).not.toBe(b);expect(a).not.toContain('Secure synthetic');expect(await verifyPassword('Secure synthetic password 123!',a)).toBe(true);expect(await verifyPassword('wrong',a)).toBe(false);expect(await verifyPassword('x','scrypt$v1$100000000$8$1$x$x')).toBe(false);});
 it('opaque tokens are stored by nonreversible hash and CSRF differs from authentication token',()=>{const token=opaqueToken();expect(token.length).toBeGreaterThanOrEqual(40);expect(hashToken(token)).toHaveLength(64);expect(csrfFor(token)).not.toBe(token);expect(parseCookies('knaba_session=abc; broken=%E0%A4%A')).toEqual({knaba_session:'abc'});});
 it('same-origin cookie mutations require the session-specific CSRF proof',()=>{const token=opaqueToken();expect(()=>requireCsrf(request({origin:'https://knaba.test','x-csrf-token':csrfFor(token)}),token,'https://knaba.test')).not.toThrow();expect(()=>requireCsrf(request({origin:'https://attacker.test','x-csrf-token':csrfFor(token)}),token,'https://knaba.test')).toThrow('ACCESS_DENIED');expect(()=>requireCsrf(request({origin:'https://knaba.test'}),token,'https://knaba.test')).toThrow('ACCESS_DENIED');});
 it('TOTP has bounded skew and encrypted secrets reject altered ciphertext',()=>{const secret='JBSWY3DPEHPK3PXP',now=1700000000000,t=new OTPAuth.TOTP({secret:OTPAuth.Secret.fromBase32(secret),digits:6,period:30});const token=t.generate({timestamp:now});expect(validateTotp(secret,token,now)).toBe(Math.floor(now/30000));expect(validateTotp(secret,token,now+120000)).toBeNull();const sealed=sealSecret(secret,'synthetic test encryption key 123');expect(sealed).not.toContain(secret);expect(openSecret(sealed,'synthetic test encryption key 123')).toBe(secret);expect(()=>openSecret(sealed,'different key')).toThrow('NEEDS_REAUTH');});
 it('issued cookie is HttpOnly Strict Secure and SQL stores only a token hash',async()=>{const db=new FixtureDb();await db.add('user',{active:true,roles:['EMPLOYEE'],name:'Synthetic'},'worker');const auth=new AuthService(db,engine(db),{companyId:'company',appMode:'DEMO',publicOrigin:'https://knaba.test'}),session=await auth.createSession('worker');const res=response();auth.cookie(res,session.token);expect(res.cookies[0].options).toMatchObject({httpOnly:true,sameSite:'strict',secure:true});expect(JSON.stringify(db.sessions)).not.toContain(session.token);expect(db.sessions[0]!.token_hash).toBe(hashToken(session.token));});
 it('every session rechecks current actor roles and immediately denies a disabled user',async()=>{const db=new FixtureDb();await db.add('user',{active:true,roles:['EMPLOYEE']},'worker');const auth=new AuthService(db,engine(db),{companyId:'company',appMode:'TEST'}),session=await auth.createSession('worker');const req=request({cookie:`knaba_session=${session.token}`});expect((await auth.authenticate(req)).actor.roles).toEqual(['EMPLOYEE']);await db.save(await db.get('user','worker'),{active:true,roles:['INTERNAL_BAULEITER']});expect((await auth.authenticate(req)).actor.roles).toEqual(['INTERNAL_BAULEITER']);await db.save(await db.get('user','worker'),{active:false,roles:['INTERNAL_BAULEITER']});await expect(auth.authenticate(req)).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('session token cannot be replayed in a different company',async()=>{const db=new FixtureDb();await db.add('user',{active:true,roles:['EMPLOYEE']},'worker');const auth=new AuthService(db,engine(db),{companyId:'company',appMode:'TEST'}),session=await auth.createSession('worker');const other=new AuthService(db,engine(db),{companyId:'other-company',appMode:'TEST'});await expect(other.authenticate(request({cookie:`knaba_session=${session.token}`}))).rejects.toMatchObject({code:'NEEDS_REAUTH'});});
 it('production never enables demo role login',async()=>{const db=new FixtureDb(),auth=new AuthService(db,engine(db),{companyId:'company',appMode:'PRODUCTION'});await expect(auth.demo(request(),response(),{role:'OWNER'})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});});
 it('privileged production login needs configured MFA and rejects a replayed OTP',async()=>{const db=new FixtureDb();await db.add('user',{active:true,roles:['OWNER'],email:'owner@example.test'},'owner');const secret='JBSWY3DPEHPK3PXP',key='synthetic auth encryption key',password='Secure synthetic password 123!';db.credentials.push({user_id:'owner',company_id:'company',password_hash:await hashPassword(password),totp_secret:sealSecret(secret,key),totp_last_counter:-1});const auth=new AuthService(db,engine(db),{companyId:'company',appMode:'PRODUCTION',encryptionKey:key});await expect(auth.login(request(),response(),{email:'owner@example.test',password})).rejects.toMatchObject({code:'NEEDS_REAUTH'});const otp=new OTPAuth.TOTP({secret:OTPAuth.Secret.fromBase32(secret),digits:6,period:30}).generate();const logged=await auth.login(request(),response(),{email:'owner@example.test',password,otp});expect(logged.actor.mfaVerified).toBe(true);await expect(auth.login(request(),response(),{email:'owner@example.test',password,otp})).rejects.toMatchObject({code:'NEEDS_REAUTH'});});
 it('rate limiter expires rather than silently accepting unlimited login attempts',()=>{const limiter=new RateLimiter(2,1000);limiter.check('subject',100);limiter.check('subject',100);expect(()=>limiter.check('subject',100)).toThrow('RATE_LIMITED');expect(()=>limiter.check('subject',1200)).not.toThrow();});
});
describe('invitation, role and owner authorization',()=>{
 it('one-time invitation creates a verified bounded identity and no password aggregate',async()=>{const db=new FixtureDb();await db.add('user',{roles:['OWNER'],active:true,email:'owner@example.test'},'owner');const invite=await run(db,'user.invite',{name:'Synthetic employee',email:'worker@example.test',roles:['EMPLOYEE']});const result=await db.transaction('company','ACTIVATE',tx=>activateInvitation(tx,'company',{token:invite.token,password:'Secure invited password 123!'}));const user=await db.get('user',result.userId);expect(user.data.roles).toEqual(['EMPLOYEE']);expect(user.data.passwordHash).toBeUndefined();expect(db.credentials[0]!.password_hash).toContain('scrypt$v1');expect((await db.list('contact_identity'))[0]!.data.verified).toBe(true);await expect(db.transaction('company','ACTIVATE',tx=>activateInvitation(tx,'company',{token:invite.token,password:'Secure invited password 123!'}))).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});});
 it('invitation expiry and foreign code return an equivalent safe error',async()=>{const db=new FixtureDb();const invite=await run(db,'user.invite',{name:'Employee',email:'worker@example.test',roles:['EMPLOYEE'],expiresHours:1});const future=new Date(Date.now()+7200000).toISOString();await expect(activateInvitation(db,'company',{token:invite.token,password:'Secure invited password 123!'},future)).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});await expect(activateInvitation(db,'company',{token:opaqueToken(),password:'Secure invited password 123!'})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});});
 it('self promotion and last-owner removal are denied before mutation',async()=>{const db=new FixtureDb();await db.add('user',{roles:['OWNER'],active:true},'owner');const input={userId:'owner',roles:['EMPLOYEE'],siteIds:[],reason:'Attempt self demotion'};await expect(run(db,'user.roles',input)).rejects.toMatchObject({code:'ACCESS_DENIED'});const other={...owner,userId:'other-owner'};await expect(run(db,'user.roles',input,other)).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'LAST_OWNER_PROTECTED'}});expect((await db.get('user','owner')).data.roles).toEqual(['OWNER']);});
 it('unprivileged inviter cannot grant privileged roles or unheld explicit permissions',async()=>{const db=new FixtureDb(),actor={...owner,userId:'foreman',roles:['INTERNAL_BAULEITER'],permissions:['identity.manage']};await expect(run(db,'user.invite',{name:'Unsafe',email:'unsafe@example.test',roles:['OWNER']},actor)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(db,'user.invite',{name:'Unsafe',email:'unsafe@example.test',roles:['EMPLOYEE'],permissions:['finance.payroll.approve']},actor)).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('role replacement revokes old sessions and prior role assignments atomically',async()=>{const db=new FixtureDb();await db.add('user',{roles:['EMPLOYEE'],active:true,siteIds:[]},'worker');await db.add('role_assignment',{userId:'worker',role:'DISPATCHER',active:true},'old-role');const auth=new AuthService(db,engine(db),{companyId:'company',appMode:'TEST'});await auth.createSession('worker');await run(db,'user.roles',{userId:'worker',roles:['EMPLOYEE'],siteIds:[],reason:'Expired substitute role removed'});expect((await db.get('role_assignment','old-role')).data.active).toBe(false);expect(db.sessions.every(s=>s.revoked_at)).toBe(true);});
});

describe('canonical role and bootstrap boundaries',()=>{
 it('OWNER gets only explicit V4 payroll approval without wildcard finance execution or automatic GPS policy authority',()=>{const rights=permissionsForRoles(['OWNER']);expect(rights).not.toContain('*');expect(rights.filter(p=>p.startsWith('finance.'))).toEqual(['finance.payroll.approve']);for(const denied of ['finance.payroll','finance.payout','finance.payout.approve','finance.accountant','location.policy.manage','location.history.read'])expect(rights).not.toContain(denied);});
 it('wildcard explicit grants are rejected by the invitation schema',()=>{expect(()=>identityCommands['user.invite']!.schema.parse({name:'Unsafe',email:'unsafe@example.test',roles:['EMPLOYEE'],permissions:['*']})).toThrow();});
 it('demo UI aliases resolve to canonical roles without creating another role definition',async()=>{const db=new FixtureDb();await db.add('user',{active:true,roles:['INTERNAL_BAULEITER'],synthetic:true,name:'Synthetic foreman'},'foreman');const auth=new AuthService(db,engine(db),{companyId:'company',appMode:'DEMO'});const session=await auth.demo(request(),response(),{role:'FOREMAN'});expect(session.actor.roles).toEqual(['INTERNAL_BAULEITER']);});
 it('production cookie cannot be downgraded by an insecure runtime override',()=>{const db=new FixtureDb(),auth=new AuthService(db,engine(db),{companyId:'company',appMode:'PRODUCTION',cookieSecure:false});const res=response();auth.cookie(res,opaqueToken());expect(res.cookies[0].options.secure).toBe(true);});
 it('offline bootstrap closes after one owner and creates no wildcard or unapproved financial rights',async()=>{const db=new FixtureDb(),auth=new AuthService(db,engine(db),{companyId:'company',appMode:'PRODUCTION',encryptionKey:'synthetic offline bootstrap encryption key'});const input={name:'Authorized fixture owner',email:'owner@example.test',password:'Secure bootstrap password 123!',totpSecret:'JBSWY3DPEHPK3PXP',evidence:'Synthetic authorization fixture, not company approval'};const created=await auth.bootstrapOwner(input);const user=await db.get('user',created.userId);expect(user.data.permissions).not.toContain('*');expect(user.data.permissions.some((p:string)=>p.startsWith('finance.'))).toBe(false);await expect(auth.bootstrapOwner(input)).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'BOOTSTRAP_CLOSED'}});});
});
