import { describe, expect, it } from 'vitest';
import { deflateRawSync } from 'node:zlib';
import { parseLocationImport } from '../packages/imports/locations.ts';
import { writeXlsxWorkbook } from '../packages/storage/xlsx.ts';
import { operationsCommands } from '../packages/domain/operations.ts';
const xlsxMime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
const csv = (text: string) => parseLocationImport(Buffer.from(text, 'utf8'), 'text/csv;charset=utf-8');
const header = ['externalKey', 'parentExternalKey', 'nodeType', 'code', 'name', 'floorLevel', 'floorLabelDe', 'sortOrder'];
function workbook(rows: (string | number | boolean | null)[][] = [header, ['house', '', 'BUILDING', 'HA', 'Haus A', null, null, 0], ['floor', 'house', 'FLOOR', 'EG', 'Eingangsebene', 0, 'EG', 1]]) {
  return writeXlsxWorkbook({ creator: 'SYNTHETIC_TEST_ONLY', createdAt: '2026-10-06T12:00:00Z', title: 'Synthetic location import', subject: 'Location data', description: 'Independent real OOXML writer fixture', sheets: [{ name: 'Locations', rows }] });
}
// Independent stored/deflate ZIP fixture constructor (bitwise CRC reference, not production ZIP code).
function crc(bytes: Buffer): number { let n = 0xffffffff; for (const byte of bytes) { n ^= byte; for (let bit = 0; bit < 8; bit++) n = n & 1 ? (n >>> 1) ^ 0xedb88320 : n >>> 1; } return (n ^ 0xffffffff) >>> 0; }
function zip(entries: [string, string][], method: 0 | 8 = 0, descriptor?: 'signed' | 'plain'): Buffer {
  const local: Buffer[] = [], central: Buffer[] = []; let offset = 0;
  for (const [name, text] of entries) {
    const path = Buffer.from(name), bytes = Buffer.from(text), packed = method ? deflateRawSync(bytes) : bytes, checksum = crc(bytes), flags = descriptor ? 8 : 0;
    const h = Buffer.alloc(30); h.writeUInt32LE(0x04034b50); h.writeUInt16LE(20, 4); h.writeUInt16LE(flags, 6); h.writeUInt16LE(method, 8);
    if (!descriptor) { h.writeUInt32LE(checksum, 14); h.writeUInt32LE(packed.length, 18); h.writeUInt32LE(bytes.length, 22); }
    h.writeUInt16LE(path.length, 26); local.push(h, path, packed);
    const d = Buffer.alloc(descriptor === 'signed' ? 16 : descriptor ? 12 : 0);
    if (descriptor) { const at = descriptor === 'signed' ? 4 : 0; if (at) d.writeUInt32LE(0x08074b50); d.writeUInt32LE(checksum, at); d.writeUInt32LE(packed.length, at + 4); d.writeUInt32LE(bytes.length, at + 8); local.push(d); }
    const c = Buffer.alloc(46); c.writeUInt32LE(0x02014b50); c.writeUInt16LE(20, 4); c.writeUInt16LE(20, 6); c.writeUInt16LE(flags, 8); c.writeUInt16LE(method, 10); c.writeUInt32LE(checksum, 16); c.writeUInt32LE(packed.length, 20); c.writeUInt32LE(bytes.length, 24); c.writeUInt16LE(path.length, 28); c.writeUInt32LE(offset, 42); central.push(c, path); offset += h.length + path.length + packed.length + d.length;
  }
  const directory = Buffer.concat(central), end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(directory.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...local, directory, end]);
}
const xmlHeader = '<?xml version="1.0" encoding="UTF-8"?>';
const main = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main', office = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships', rel = 'http://schemas.openxmlformats.org/package/2006/relationships';
function fixture(sheet: string, shared?: string): [string, string][] {
  return [
    ['[Content_Types].xml', `${xmlHeader}<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/></Types>`],
    ['_rels/.rels', `${xmlHeader}<Relationships xmlns="${rel}"><Relationship Id="book" Type="${office}/officeDocument" Target="xl/workbook.xml"/></Relationships>`],
    ['xl/workbook.xml', `${xmlHeader}<workbook xmlns="${main}" xmlns:r="${office}"><sheets><sheet name="Locations" sheetId="1" r:id="sheet"/></sheets></workbook>`],
    ['xl/_rels/workbook.xml.rels', `${xmlHeader}<Relationships xmlns="${rel}"><Relationship Id="sheet" Type="${office}/worksheet" Target="worksheets/sheet1.xml"/>${shared ? `<Relationship Id="strings" Type="${office}/sharedStrings" Target="sharedStrings.xml"/>` : ''}</Relationships>`],
    ['xl/worksheets/sheet1.xml', sheet],
    ...(shared ? [['xl/sharedStrings.xml', shared] as [string, string]] : []),
  ];
}
function inline(value: string, address: string): string { return `<c r="${address}" t="inlineStr"><is><t>${value}</t></is></c>`; }
function plainSheet(secondRow: string): string { return `${xmlHeader}<worksheet xmlns="${main}"><sheetData><row r="1">${['externalKey', 'nodeType', 'code', 'name'].map((s, i) => inline(s, `${String.fromCharCode(65 + i)}1`)).join('')}</row><row r="2">${secondRow}</row></sheetData></worksheet>`; }
const ordinaryRow = inline('house', 'A2') + inline('BUILDING', 'B2') + inline('HA', 'C2') + inline('Haus A', 'D2');
const codes = (result: ReturnType<typeof parseLocationImport>) => result.errors.map(e => e.code);

describe('bounded CSV location ingestion', () => {
  it('parses BOM, CRLF, semicolons, empty parent and explicitly signed German floors', () => { const result = csv('\ufeffexternalKey;parentExternalKey;nodeType;code;name;floorLevel;floorLabelDe\r\nhouse;;BUILDING;HA;Haus A;;\r\nfloor;house;FLOOR;EG;Eingang;0;EG\r\n'); expect(result.errors).toEqual([]); expect(result.rows).toHaveLength(2); expect(result.rows[1]).toMatchObject({ externalKey: 'floor', parentExternalKey: 'house', floorLevel: 0, floorLabelDe: 'EG', names: {}, sortOrder: 0 }); });
  it('handles comma CSV, escaped quotes and embedded CRLF without splitting the location row', () => { const result = csv('externalKey,nodeType,code,name\r\nx,BUILDING,A,"Haus, A ""Nord""\r\nEingang"\r\n'); expect(result.errors).toEqual([]); expect(result.rows[0]!.name).toBe('Haus, A "Nord"\nEingang'); });
  it('supports the explicit Excel sep directive and declared aliases without inventing labels', () => { const result = csv('sep=;\r\nexternal_key;node_type;code;name;floorNumber;floorLabel\r\nlevel;FLOOR;3OG;Ebene;3;3. OG'); expect(result.errors).toEqual([]); expect(result.rows[0]).toMatchObject({ floorLevel: 3, floorLabelDe: '3. OG' }); });
  it('keeps source physical row labels aligned after multiline text, empty rows and an invalid row', () => { const result = csv('sep=;\r\nexternalKey;nodeType;code;name\r\n\r\nx;BUILDING;A;"Haus\r\nA"\r\nbad;UNKNOWN;B;Bad\r\n\r\ny;BUILDING;Y;Haus Y'); expect(result.rows.map(r => r.externalKey)).toEqual(['x', 'y']); expect(result.sourceRows).toEqual([4, 8]); expect(result.errors.some(e => e.row === 6)).toBe(true); });
  it.each(['externalKey,nodeType,code,name\nx,BUILDING,A,"not closed', 'externalKey,nodeType,code,name\nx,BUILDING,A,"closed"tail', 'externalKey,nodeType,code,name\nx,BUILDING,A,un"quoted'])('reports malformed quoting before any domain command', text => { expect(codes(csv(text))).toContain('CSV_SYNTAX'); });
  it('rejects duplicate aliases, unknown active column and missing required headers', () => { expect(codes(csv('externalKey,nodeType,code,name,floorLevel,floorNumber\nx,BUILDING,A,Name,,')).includes('HEADER_DUPLICATE')).toBe(true); expect(codes(csv('externalKey,nodeType,code,name,active\nx,BUILDING,A,Name,false'))).toContain('HEADER_UNKNOWN'); expect(codes(csv('externalKey,name\nx,Name'))).toContain('HEADER_REQUIRED'); });
  it('reports invalid row numbers/units/custom approvals and never guesses an ambiguous first floor', () => { const result = csv('externalKey,nodeType,code,name,floorLevel,floorLabelDe,measurementValueMilli,unitType,measurementSource\nbad,FLOOR,X,First,1.5,,1000,m2,approved\ngood,FLOOR,EG,Ground,0,EG,1000,m2,approved'); expect(result.rows).toHaveLength(1); expect(result.rows[0]).toMatchObject({ measurement: { valueMilli: 1000, unit: 'm2', source: 'approved' } }); expect(result.errors.some(e => e.row === 2 && e.column === 'floorLevel')).toBe(true); expect(codes(result)).toContain('FLOOR_LABEL_REQUIRED'); expect(codes(csv('externalKey,nodeType,code,name\nx,CUSTOM,A,Custom'))).toContain('CUSTOM_TYPE_APPROVAL_REQUIRED'); });
  it('validates localized JSON, field/row/file bounds and strict UTF-8', () => { expect(csv('externalKey,nodeType,code,name,names\nx,BUILDING,A,Name,"{""de"":""Haus"",""uk"":""Будинок""}"').rows[0]!.names).toEqual({ de: 'Haus', uk: 'Будинок' }); expect(codes(csv('externalKey,nodeType,code,name\nx,BUILDING,A,' + 'x'.repeat(32768)))).toContain('FILE_CELL_SIZE'); expect(codes(csv('externalKey,nodeType,code,name\n' + Array.from({ length: 1001 }, (_, i) => `${i},BUILDING,A${i},Name`).join('\n')))).toContain('FILE_ROWS'); expect(codes(parseLocationImport(Buffer.alloc(8 * 1024 * 1024 + 1), 'text/csv'))).toContain('FILE_TOO_LARGE'); expect(codes(parseLocationImport(Buffer.from([255, 254, 0, 0]), 'text/csv'))).toContain('FILE_ENCODING'); });
});

describe('real XLSX ZIP/XML ingestion and integrity', () => {
  it('roundtrips the product OOXML writer into exact normalized import rows', () => { const result = parseLocationImport(workbook(), xlsxMime); expect(result.errors).toEqual([]); expect(result.rows).toHaveLength(2); expect(result.rows[1]).toMatchObject({ externalKey: 'floor', parentExternalKey: 'house', floorLevel: 0, floorLabelDe: 'EG', sortOrder: 1 }); const schema = operationsCommands['location.import.preview']!.schema; expect(schema.parse({ siteId: 'synthetic-site', rows: result.rows }).rows).toEqual(result.rows); });
  it.each([0, 8] as const)('reads an independent method-%s ZIP with shared strings/rich text and sparse numeric cells', method => { const sst = `${xmlHeader}<sst xmlns="${main}"><si><t>externalKey</t></si><si><t>nodeType</t></si><si><t>code</t></si><si><t>name</t></si><si><t>123</t></si><si><t>BUILDING</t></si><si><t>A&amp;B</t></si><si><r><t>Haus </t></r><r><t>&#x41; &lt;Nord&gt;</t></r></si></sst>`; const cells = Array.from({ length: 4 }, (_, i) => `<c r="${String.fromCharCode(65 + i)}1" t="s"><v>${i}</v></c>`).join(''), second = `<c r="A2" t="n"><v>123</v></c>` + Array.from({ length: 3 }, (_, i) => `<c r="${String.fromCharCode(66 + i)}2" t="s"><v>${i + 5}</v></c>`).join(''); const sheet = `${xmlHeader}<worksheet xmlns="${main}"><sheetData><row r="1">${cells}</row><row r="2">${second}</row></sheetData></worksheet>`; const result = parseLocationImport(zip(fixture(sheet, sst), method), xlsxMime); expect(result.errors).toEqual([]); expect(result.rows[0]).toMatchObject({ externalKey: '123', code: 'A&B', name: 'Haus A <Nord>' }); });
  it.each(['signed', 'plain'] as const)('validates method-8 ZIP %s data descriptors and actual sparse Excel row labels', descriptor => { const sheet = plainSheet(ordinaryRow).replaceAll('r="2"', 'r="7"').replaceAll(/([A-D])2/g, '$17'); const result = parseLocationImport(zip(fixture(sheet), 8, descriptor), xlsxMime); expect(result.errors).toEqual([]); expect(result.sourceRows).toEqual([7]); expect(result.rows[0]!.externalKey).toBe('house'); });
  it('rejects decimal rounding/underflow and noncanonical row references while accepting exact integer exponent text', () => {
    for (const raw of ['9007199254740991.1', '1e-999', '1.25']) { const row = ordinaryRow.replace(inline('house', 'A2'), `<c r="A2"><v>${raw}</v></c>`); expect(codes(parseLocationImport(zip(fixture(plainSheet(row))), xlsxMime))).toContain('XLSX_NUMERIC_PRECISION'); }
    const exact = ordinaryRow.replace(inline('house', 'A2'), '<c r="A2"><v>123.000e0</v></c>'); expect(parseLocationImport(zip(fixture(plainSheet(exact))), xlsxMime).rows[0]!.externalKey).toBe('123');
    expect(codes(parseLocationImport(zip(fixture(plainSheet(ordinaryRow).replace('row r="2"', 'row r="2e0"'))), xlsxMime))).toContain('XLSX_CELL_REFERENCE');
    expect(codes(parseLocationImport(zip([['C:outside.xml', '<x/>']]), xlsxMime))).toContain('XLSX_ZIP_UNSAFE_PATH');
  });
  it('rejects CRC corruption, truncation, changed local sizes and overlapping directory/header claims', () => { const broken = zip(fixture(plainSheet(ordinaryRow))); broken[30 + broken.readUInt16LE(26) + 5] ^= 1; expect(codes(parseLocationImport(broken, xlsxMime))).toContain('XLSX_ZIP_CRC'); const valid = workbook(); expect(parseLocationImport(valid.subarray(0, valid.length - 1), xlsxMime).rows).toEqual([]); const disagree = Buffer.from(valid); disagree.writeUInt32LE(disagree.readUInt32LE(22) + 1, 22); expect(codes(parseLocationImport(disagree, xlsxMime))).toContain('XLSX_ZIP_INVALID'); });
  it('rejects path traversal, duplicate names, macros, encrypted entries and excessive expansion', () => { expect(codes(parseLocationImport(zip([['../outside.xml', '<x/>']]), xlsxMime))).toContain('XLSX_ZIP_UNSAFE_PATH'); expect(codes(parseLocationImport(zip([['same.xml', '<x/>'], ['same.xml', '<x/>']]), xlsxMime))).toContain('XLSX_ZIP_INVALID'); expect(codes(parseLocationImport(zip([...fixture(plainSheet(ordinaryRow)), ['xl/vbaProject.bin', 'not executed']]), xlsxMime))).toContain('XLSX_UNSUPPORTED'); const encrypted = workbook(); encrypted.writeUInt16LE(encrypted.readUInt16LE(6) | 1, 6); const eocd = encrypted.length - 22, directory = encrypted.readUInt32LE(eocd + 16); encrypted.writeUInt16LE(encrypted.readUInt16LE(directory + 8) | 1, directory + 8); expect(codes(parseLocationImport(encrypted, xlsxMime))).toContain('XLSX_UNSUPPORTED'); expect(codes(parseLocationImport(zip([['bomb.xml', 'a'.repeat(200000)]], 8), xlsxMime))).toContain('XLSX_ZIP_BOMB'); });
  it('rejects DTD/entities/external relationships and formulas instead of evaluating them', () => { const unsafe = plainSheet(ordinaryRow).replace(xmlHeader, `${xmlHeader}<!DOCTYPE worksheet [<!ENTITY secret SYSTEM "file:///etc/passwd">]>`); expect(codes(parseLocationImport(zip(fixture(unsafe)), xlsxMime))).toContain('XLSX_XML_UNSAFE'); const external = fixture(plainSheet(ordinaryRow)); external[3]![1] = `${xmlHeader}<Relationships xmlns="${rel}"><Relationship Id="sheet" Type="${office}/worksheet" TargetMode="External" Target="https://example.test/private"/></Relationships>`; expect(codes(parseLocationImport(zip(external), xlsxMime))).toContain('XLSX_EXTERNAL_RELATIONSHIP'); const formula = plainSheet(ordinaryRow.replace(inline('house', 'A2'), '<c r="A2"><f>HYPERLINK("https://example.test")</f><v>1</v></c>')); expect(codes(parseLocationImport(zip(fixture(formula)), xlsxMime))).toContain('XLSX_FORMULA'); expect(codes(parseLocationImport(zip(fixture(plainSheet(ordinaryRow.replace('Haus A', '&unapproved;')))), xlsxMime))).toContain('XLSX_XML_UNSAFE'); });
  it('rejects multiple sheets and inexact numeric IDs; requires correct MIME rather than legacy XLS', () => { const input = writeXlsxWorkbook({ creator: 'TEST', createdAt: '2026-10-06T12:00:00Z', title: 'TEST', subject: '', description: '', sheets: [{ name: 'One', rows: [header] }, { name: 'Two', rows: [header] }] }); expect(codes(parseLocationImport(input, xlsxMime))).toContain('XLSX_UNSUPPORTED'); const numeric = ordinaryRow.replace(inline('house', 'A2'), '<c r="A2" t="n"><v>9007199254740993</v></c>'); expect(codes(parseLocationImport(zip(fixture(plainSheet(numeric))), xlsxMime))).toContain('XLSX_NUMERIC_PRECISION'); expect(codes(parseLocationImport(workbook(), 'application/vnd.ms-excel'))).toContain('FILE_TYPE'); });
});
