import {afterAll,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Database} from '../apps/api/database.ts';
import {Engine} from '../apps/api/engine.ts';
import {internalAssistantCommands,internalAssistantHost} from '../apps/api/internal-assistant.ts';
import {prepareInternalAssistant,persistInternalAssistantDraft,type InternalAssistantHost} from '../packages/integrations/internal-assistant.ts';
import {DeepSeekAdapter} from '../packages/integrations/deepseek.ts';
import {parseInternalDraftProposal,type InternalAssistantProviderResult} from '../packages/integrations/internal-assistant-provider.ts';
import {assert,DomainError,type Actor,type Data} from '../packages/domain/core.ts';
import type {SqlTransaction} from '../apps/api/auth.ts';
import {WorkerRunner,leaseOutbox} from '../apps/worker/runner.ts';

// Genuine PostgreSQL + Engine + canonical domain handlers. Provider I/O is a
// synthetic request fixture. Discovery without DATABASE_URL is NOT SQL PASS.
const postgres=process.env.DATABASE_URL?describe:describe.skip;
const source='Haus A 3. OG Fenster reinigen; Haus A 5. OG Flur fegen; Haus B EG Müll entfernen.';
const raw={kind:'TASK_BATCH',needsClarification:false,clarification:null,input:{tasks:[
 {siteId:'a',locationId:'a3',title:'Fenster reinigen',sourceQuote:'Haus A 3. OG Fenster reinigen',assigneeIds:['worker'],checklist:[{id:'clean',label:'Fenster gereinigt',checked:false}]},
 {siteId:'a',locationId:'a5',title:'Flur fegen',sourceQuote:'Haus A 5. OG Flur fegen'},
 {siteId:'b',locationId:'b0',title:'Müll entfernen',sourceQuote:'Haus B EG Müll entfernen'},
]}};

postgres('internal draft PostgreSQL/Engine atomic workflows with synthetic provider',()=>{
 let db:Database,engine:Engine,company:string,actor:Actor;
 beforeAll(async()=>{db=new Database();await db.migrate();});
 beforeEach(async()=>{
  company='internal-assistant-qa-'+randomUUID();engine=new Engine(db,'TEST');Object.assign(engine.registry,internalAssistantCommands(db,engine,'TEST'));
  await db.transaction(company,'SYNTHETIC_INTERNAL_AI_QA',async tx=>{
   await tx.add('company',{legalName:'Synthetic internal QA',address:'Teststraße 24',operatingMode:'TEST',synthetic:true},company);
   for(const id of ['foreman','other'])await tx.add('user',{name:'Synthetic '+id,active:true,roles:['INTERNAL_BAULEITER'],siteIds:['a','b']},id);
   await tx.add('user',{name:'Synthetic worker',active:true,roles:['EMPLOYEE'],siteIds:['a']},'worker');
   for(const [id,name]of [['a','Haus A'],['b','Haus B']])await tx.add('site',{active:true,code:id.toUpperCase(),name,customerId:'customer'},id);
   for(const [id,siteId,floor]of [['a3','a','3. OG'],['a5','a','5. OG'],['b0','b','EG']])await tx.add('location',{siteId,active:true,name:floor,code:floor,parentId:null,floorLabelDe:floor,nodeType:'FLOOR',revision:1},id);
   await tx.add('channel',{type:'COMPANY_GENERAL',members:[{user_id:'foreman',history_from:'2020-01-01T00:00:00Z'},{user_id:'other',history_from:'2020-01-01T00:00:00Z'}]},'channel');
   await tx.add('message',{channel_id:'channel',author_id:'foreman',message_version:1,source:'HUMAN',text:source,language:'DE'},'message');
   await tx.add('assistant_config',{status:'ACTIVE',configVersion:1,model:'synthetic-internal-model',timeoutMs:1000,tone:'PROFESSIONAL',addressForm:'Sie',humanHours:[],testOnly:true,provider:'DEEPSEEK',budgetCents:1000},'config');
  });actor=await engine.getActor('foreman',company);
 });
 afterAll(async()=>{await db?.close();});
 const input={messageId:'message',messageVersion:1,channelId:'channel',configId:'config',configVersion:1,kind:'TASK_BATCH',siteIds:['a','b'],context:{locationIds:['a3','a5','b0'],assigneeIds:['worker']}};
 const rows=(kind:string)=>db.transaction(company,'SYNTHETIC_INTERNAL_AI_READ',tx=>tx.list(kind));
 const row=(kind:string,id:string)=>db.transaction(company,'SYNTHETIC_INTERNAL_AI_READ',tx=>tx.get(kind,id));
 async function update(kind:string,id:string,patch:Data){return db.transaction(company,'SYNTHETIC_INTERNAL_AI_CHANGE',async tx=>{const e=await tx.get(kind,id);return tx.save(e,{...e.data,...patch});});}
 async function queued(){
  const request=await engine.execute(actor,'internal_assistant.request',{input,idempotency_key:randomUUID()});
  const token=randomUUID(),claimed=await db.query("UPDATE outbox SET status='RUNNING',attempts=1,lease_token=$3,leased_until=clock_timestamp()+interval '5 minutes' WHERE company_id=$1 AND type='internal_assistant.requested' AND data->>'requestId'=$2 RETURNING id",[company,request.id,token]);expect(claimed.rows).toHaveLength(1);const jobId=claimed.rows[0]!.id;
  const host:InternalAssistantHost<SqlTransaction>=internalAssistantHost(db,engine,'TEST',undefined,async tx=>{assert(tx.query,'MISSING_CONFIGURATION');const lease=await tx.query("SELECT id FROM outbox WHERE company_id=$1 AND id=$2 AND status='RUNNING' AND lease_token=$3 AND leased_until>clock_timestamp() FOR UPDATE",[company,jobId,token]);assert(lease.rows.length===1,'WORKER_LEASE_LOST');});
  const prepared=await prepareInternalAssistant(company,request.id,host);assert(!prepared.done,'INVALID_STATE');return {request,host,prepared,jobId,token};
 }
 async function ready(){const f=await queued(),proposal=parseInternalDraftProposal(raw,f.prepared.providerInput),result:InternalAssistantProviderResult={proposal,provider:'synthetic-provider-fixture',model:'synthetic-internal-model',usage:{input_tokens:100,output_tokens:50,cost_cents:1}};return {...f,result,draft:await persistInternalAssistantDraft(company,f.request.id,f.prepared.contextHash,result,f.host)};}
 async function runtime(onRequest?:()=>Promise<void>,missingProvider=false){
  const fetcher=vi.fn(async()=>{await onRequest?.();return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(raw)}}],usage:{prompt_tokens:100,completion_tokens:50}}));});
  const ai=new DeepSeekAdapter({baseUrl:'https://synthetic-internal.example/v1',apiKey:'SYNTHETIC_FIXTURE_ONLY',model:'adapter-default',timeoutMs:1000,inputPricePerMillionCents:1,outputPricePerMillionCents:1,maxOutputTokens:1000,syntheticOnly:true},fetcher as typeof fetch);
  const worker=new WorkerRunner(db,engine,{companyId:company,appMode:'TEST',ai:missingProvider?undefined:ai,leaseMs:120000,maxAttempts:1});await worker.initialize();
  const request=await engine.execute(actor,'internal_assistant.request',{input,idempotency_key:randomUUID()}),jobs=await leaseOutbox(db,1,120000,company);expect(jobs).toHaveLength(1);expect(jobs[0]!.type).toBe('internal_assistant.requested');return {request,worker,job:jobs[0]!,fetcher};
 }
 const confirmInput=(d:Data)=>({draftId:d.draftId,expectedVersion:d.draftVersion,previewHash:d.previewHash,confirmed:true});

 it('exact parallel receipt replay creates one atomic three-task batch and one confirmation outbox/audit event',async()=>{const f=await ready();expect(await rows('task')).toHaveLength(0);const key=randomUUID(),envelope={input:confirmInput(f.draft),idempotency_key:key};const [first,second]=await Promise.all([engine.execute(actor,'internal_assistant.confirm',envelope),engine.execute(actor,'internal_assistant.confirm',envelope)]);expect(second).toEqual(first);expect(first.entityIds).toHaveLength(3);expect(await engine.execute(actor,'internal_assistant.confirm',{input:confirmInput(f.draft),idempotency_key:randomUUID()})).toEqual(first);expect(await rows('task')).toHaveLength(3);expect(await rows('task_batch')).toHaveLength(1);expect((await row('internal_assistant_draft',f.draft.draftId)).data.state).toBe('CONFIRMED');expect((await db.query('SELECT count(*)::int n FROM command_receipts WHERE company_id=$1 AND idempotency_key=$2',[company,key])).rows[0].n).toBe(1);expect((await db.query("SELECT count(*)::int n FROM outbox WHERE company_id=$1 AND type='internal_assistant.confirmed'",[company])).rows[0].n).toBe(1);expect((await db.query("SELECT count(*)::int n FROM audit_log WHERE company_id=$1 AND action='CREATE' AND aggregate_kind='task'",[company])).rows[0].n).toBe(3);});
 it('changed source after provider claim prevents any usable draft, tasks or prepared event',async()=>{const f=await queued(),result={proposal:parseInternalDraftProposal(raw,f.prepared.providerInput),provider:'synthetic-provider-fixture',model:'synthetic-internal-model'};await update('message','message',{message_version:2,text:'Changed instruction'});await expect(persistInternalAssistantDraft(company,f.request.id,f.prepared.contextHash,result,f.host)).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(await rows('internal_assistant_draft')).toHaveLength(0);expect(await rows('task')).toHaveLength(0);expect((await db.query("SELECT count(*)::int n FROM outbox WHERE company_id=$1 AND type='internal_assistant.draft_prepared'",[company])).rows[0].n).toBe(0);});
 it('expired exact SQL worker lease prevents draft persistence after a provider response',async()=>{const f=await queued(),result={proposal:parseInternalDraftProposal(raw,f.prepared.providerInput),provider:'synthetic-provider-fixture',model:'synthetic-internal-model'};await db.query("UPDATE outbox SET leased_until=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND id=$2",[company,f.jobId]);await expect(persistInternalAssistantDraft(company,f.request.id,f.prepared.contextHash,result,f.host)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await rows('internal_assistant_draft')).toHaveLength(0);expect(await rows('task')).toHaveLength(0);expect((await row('internal_assistant_request',f.request.id)).data.status).toBe('RUNNING');});
 it('canonical handler failure rolls back tasks, batch, draft confirmation, receipts, audit and outbox together',async()=>{const f=await ready(),definition=engine.registry['task.bulk.commit']!,original=definition.handler;engine.registry['task.bulk.commit']={...definition,handler:async(ctx,args)=>{await original(ctx,args);throw new DomainError('SIMULATED_CANONICAL_FAILURE');}};const key=randomUUID();await expect(engine.execute(actor,'internal_assistant.confirm',{input:confirmInput(f.draft),idempotency_key:key})).rejects.toMatchObject({code:'SIMULATED_CANONICAL_FAILURE'});expect(await rows('task')).toHaveLength(0);expect(await rows('task_batch')).toHaveLength(0);expect((await row('internal_assistant_draft',f.draft.draftId)).data.state).toBe('DRAFT');expect((await row('internal_assistant_request',f.request.id)).data.status).toBe('READY');expect((await db.query('SELECT count(*)::int n FROM command_receipts WHERE company_id=$1 AND idempotency_key=$2',[company,key])).rows[0].n).toBe(0);expect((await db.query("SELECT count(*)::int n FROM audit_log WHERE company_id=$1 AND aggregate_kind='task'",[company])).rows[0].n).toBe(0);expect((await db.query("SELECT count(*)::int n FROM outbox WHERE company_id=$1 AND type IN('task.created','internal_assistant.confirmed')",[company])).rows[0].n).toBe(0);});
 it('private draft is unreadable to another internal author and fresh role revocation blocks confirmation',async()=>{const f=await ready(),other=await engine.getActor('other',company);expect(await engine.readEntities(other,'internal_assistant_draft')).toHaveLength(0);await expect(engine.execute(other,'internal_assistant.preview',{input:{draftId:f.draft.draftId},idempotency_key:randomUUID()})).rejects.toMatchObject({code:'ACCESS_DENIED'});await update('user','foreman',{roles:['EMPLOYEE']});await expect(engine.execute(actor,'internal_assistant.confirm',{input:confirmInput(f.draft),idempotency_key:randomUUID()})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await rows('task')).toHaveLength(0);});
 it('actual adapter response becomes only a private PostgreSQL preview until human confirmation',async()=>{const f=await queued(),fetcher=vi.fn(async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(raw)}}],usage:{prompt_tokens:100,completion_tokens:50}}))),ai=new DeepSeekAdapter({baseUrl:'https://synthetic-internal.example/v1',apiKey:'SYNTHETIC_FIXTURE_ONLY',model:'adapter-default',timeoutMs:1000,inputPricePerMillionCents:1,outputPricePerMillionCents:1,maxOutputTokens:1000,syntheticOnly:true},fetcher as typeof fetch);const result=await ai.proposeInternalDraft({...f.prepared.providerInput,budgetRemainingCents:100});expect(fetcher).toHaveBeenCalledTimes(1);expect(result.model).toBe('synthetic-internal-model');const draft=await persistInternalAssistantDraft(company,f.request.id,f.prepared.contextHash,result,f.host);expect(draft.preview.tasks).toHaveLength(3);expect(draft.requiresUserConfirmation).toBe(true);expect(await rows('task')).toHaveLength(0);expect(await rows('report')).toHaveLength(0);expect(await rows('material_request')).toHaveLength(0);expect((await row('internal_assistant_request',f.request.id)).data.status).toBe('READY');});
 it('actual WorkerRunner leases, reserves INTERNAL_DRAFT, invokes configured adapter once, prepares private preview and settles measured usage',async()=>{const f=await runtime();await f.worker.process(f.job);expect(f.fetcher).toHaveBeenCalledTimes(1);const draft=(await rows('internal_assistant_draft'))[0]!;expect(draft.data).toMatchObject({ownerUserId:'foreman',state:'DRAFT',model:'synthetic-internal-model'});expect(draft.data.preview.tasks).toHaveLength(3);expect((await row('internal_assistant_request',f.request.id)).data.status).toBe('READY');expect(await rows('task')).toHaveLength(0);expect(await rows('report')).toHaveLength(0);expect(await rows('material_request')).toHaveLength(0);expect((await rows('ai_usage'))[0]!.data).toMatchObject({category:'INTERNAL_DRAFT',status:'SUCCEEDED',input_tokens:100,output_tokens:50,actual_cents:1});expect((await db.query('SELECT status FROM outbox WHERE company_id=$1 AND id=$2',[company,f.job.id])).rows[0].status).toBe('SUCCEEDED');const preview=await engine.execute(actor,'internal_assistant.preview',{input:{draftId:draft.id},idempotency_key:randomUUID()});expect(preview.requiresUserConfirmation).toBe(true);const confirmed=await engine.execute(actor,'internal_assistant.confirm',{input:confirmInput(preview),idempotency_key:randomUUID()});expect(confirmed.entityIds).toHaveLength(3);expect(await rows('task')).toHaveLength(3);});
 it('actual disabled-provider worker records a typed FAILED request with no cost, fake draft or business effect',async()=>{const f=await runtime(undefined,true);await f.worker.process(f.job);expect(f.fetcher).not.toHaveBeenCalled();expect((await row('internal_assistant_request',f.request.id)).data).toMatchObject({status:'FAILED',error:'PROVIDER_DISABLED'});for(const kind of ['ai_usage','internal_assistant_draft','task','report','material_request'])expect(await rows(kind),kind).toHaveLength(0);});
 it('revocation after actual reservation is caught before provider I/O and releases only the unspent reservation',async()=>{const f=await runtime(),worker=f.worker as any,original=worker.reserveBudget.bind(worker);worker.reserveBudget=async(...args:any[])=>{const budget=await original(...args);await update('user','foreman',{roles:['EMPLOYEE']});return budget;};await f.worker.process(f.job);expect(f.fetcher).not.toHaveBeenCalled();expect((await row('internal_assistant_request',f.request.id)).data).toMatchObject({status:'FAILED',error:'ACCESS_DENIED'});expect((await rows('ai_usage'))[0]!.data).toMatchObject({category:'INTERNAL_DRAFT',status:'CANCELLED',actual_cents:0,reserved_cents:0});expect(await rows('internal_assistant_draft')).toHaveLength(0);expect(await rows('task')).toHaveLength(0);});
 it('known returned provider output after source change is discarded, records measured cost, and creates no usable draft',async()=>{const f=await runtime(async()=>{await update('message','message',{message_version:2,text:'Changed source while provider was running'});});await f.worker.process(f.job);expect(f.fetcher).toHaveBeenCalledTimes(1);expect((await row('internal_assistant_request',f.request.id)).data).toMatchObject({status:'FAILED',error:'VERSION_CONFLICT'});expect((await rows('ai_usage'))[0]!.data).toMatchObject({category:'INTERNAL_DRAFT',status:'SUCCEEDED',actual_cents:1,input_tokens:100});expect(await rows('internal_assistant_draft')).toHaveLength(0);expect(await rows('task')).toHaveLength(0);});
 it('unknown actual provider I/O retains RUNNING privacy/budget markers even after a failed outbox and never automatically reissues',async()=>{const f=await runtime(async()=>{throw new Error('Synthetic network interruption after request reached provider');});await f.worker.process(f.job);expect(f.fetcher).toHaveBeenCalledTimes(1);expect((await row('internal_assistant_request',f.request.id)).data).toMatchObject({status:'RUNNING',providerOutcome:'UNKNOWN',error:'PROVIDER_UNAVAILABLE'});const usage=(await rows('ai_usage'))[0]!;expect(usage.data).toMatchObject({category:'INTERNAL_DRAFT',status:'RUNNING'});expect(usage.data.reserved_cents).toBeGreaterThan(0);expect((await db.query('SELECT status FROM outbox WHERE company_id=$1 AND id=$2',[company,f.job.id])).rows[0].status).toBe('FAILED');expect(await rows('internal_assistant_draft')).toHaveLength(0);const retryToken=randomUUID();const retry=(await db.query("UPDATE outbox SET status='RUNNING',attempts=1,lease_token=$3,leased_until=clock_timestamp()+interval '5 minutes' WHERE company_id=$1 AND id=$2 RETURNING *",[company,f.job.id,retryToken])).rows[0]!;await f.worker.process(retry);expect(f.fetcher).toHaveBeenCalledTimes(1);expect((await row('internal_assistant_request',f.request.id)).data.status).toBe('RUNNING');expect(await rows('ai_usage')).toHaveLength(1);});
});
