import {describe,it,expect} from 'vitest';
import {assert,DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';
import {ROLE_PERMISSIONS} from '../packages/domain/permissions.ts';
import {operationsCommands} from '../packages/domain/operations.ts';
import {resourcesCommands} from '../packages/domain/resources.ts';
import {createInternalAssistantCommands,prepareInternalAssistant,revalidateInternalAssistant,persistInternalAssistantDraft,failInternalAssistant,markInternalAssistantUnknown,type InternalAssistantHost} from '../packages/integrations/internal-assistant.ts';
import {parseInternalDraftProposal,type InternalAssistantProviderResult} from '../packages/integrations/internal-assistant-provider.ts';

const NOW='2026-10-06T10:00:00.000Z';
class Tx implements Transaction{
 rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];seq=0;companyId='company';
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const e=this.rows.get(kind+':'+id);assert(e&&e.companyId===this.companyId,'NOT_FOUND_SAFE');return structuredClone(e) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.rows.values()].filter(e=>e.kind===kind&&e.companyId===this.companyId).map(e=>structuredClone(e) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=kind+'-'+(++this.seq)):Promise<Entity<T>>{assert(!this.rows.has(kind+':'+id),'VERSION_CONFLICT');const e={kind,id,version:1,companyId:this.companyId,data:structuredClone(data),createdAt:NOW,updatedAt:NOW};this.rows.set(kind+':'+id,e);return structuredClone(e);}
 async save(e:Entity,data:Data,version=e.version){const current=await this.get(e.kind,e.id);assert(current.version===version,'VERSION_CONFLICT');const result={...current,version:current.version+1,data:structuredClone(data)};this.rows.set(e.kind+':'+e.id,result);return structuredClone(result);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
}
async function fixture(){
 const tx=new Tx();let lease=true,tail=Promise.resolve(),requestSeq=0;
 const denied=new Set<string>(),invocations:{actor:string;permission:string}[]=[];
 const host:InternalAssistantHost<Tx>={mode:'TEST',now:()=>new Date(NOW),registry:{...operationsCommands,...resourcesCommands},
  transaction:async(companyId,_actor,fn)=>{assert(companyId===tx.companyId,'ACCESS_DENIED');const previous=tail;let release!:()=>void;tail=new Promise(r=>release=r);await previous;const before=structuredClone({rows:tx.rows,events:tx.events,seq:tx.seq});try{return await fn(tx);}catch(e){tx.rows=before.rows;tx.events=before.events;tx.seq=before.seq;throw e;}finally{release();}},
  actorIn:async(tx,userId)=>{const u=await tx.get('user',userId);assert(u.data.active!==false,'ACCESS_DENIED');return {userId,companyId:tx.companyId,roles:u.data.roles,permissions:[...new Set([...(u.data.roles??[]).flatMap((r:string)=>ROLE_PERMISSIONS[r]??[]),...(u.data.permissions??[])])],siteIds:u.data.siteIds??[],customerIds:[],warehouseIds:[]};},
  context:(tx,a,key,version,now,permission):CommandContext=>{assert(a.permissions.includes(permission),'ACCESS_DENIED');invocations.push({actor:a.userId,permission});return {tx,actor:a,idempotencyKey:key,expectedVersion:version,now,requireSite:s=>assert(a.permissions.includes('scope.company')||a.siteIds.includes(s),'ACCESS_DENIED'),requireOwn:u=>assert(u===a.userId,'ACCESS_DENIED')};},
  visible:async(_tx,a,e)=>{if(e.companyId!==a.companyId||denied.has(e.kind+':'+e.id))return false;if(['channel','message','assistant_config'].includes(e.kind))return true;if(e.kind==='user')return e.id===a.userId||a.permissions.includes('task.assign')&&(e.data.siteIds??[]).some((s:string)=>a.siteIds.includes(s));if(e.kind==='material')return a.permissions.includes('inventory.read');return a.permissions.includes('scope.company')||a.siteIds.includes(e.kind==='site'?e.id:e.data.siteId);},
  assertWorkerLease:async()=>assert(lease,'WORKER_LEASE_LOST')};
 Object.assign(host.registry,createInternalAssistantCommands(host));
 await tx.add('company',{legalName:'Synthetic KNABA',address:'Teststraße 24'},'company');
 for(const id of ['foreman','other'])await tx.add('user',{active:true,roles:['INTERNAL_BAULEITER'],siteIds:['a','b'],name:id},id);
 await tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['a'],name:'worker'},'worker');
 await tx.add('site',{active:true,code:'KNB-A',name:'Haus A',customerId:'customer'},'a');await tx.add('site',{active:true,code:'KNB-B',name:'Haus B',customerId:'customer'},'b');
 await tx.add('location',{siteId:'a',active:true,code:'A',name:'Haus A',parentId:null,nodeType:'BUILDING'},'building-a');await tx.add('location',{siteId:'b',active:true,code:'B',name:'Haus B',parentId:null,nodeType:'BUILDING'},'building-b');
 for(const [id,siteId,parentId,floor]of [['a3','a','building-a','3. OG'],['a5','a','building-a','5. OG'],['b0','b','building-b','EG'],['b3','b','building-b','3. OG']])await tx.add('location',{siteId,parentId,active:true,code:floor,name:floor,floorLabelDe:floor,nodeType:'FLOOR',revision:1},id);
 await tx.add('channel',{type:'COMPANY_GENERAL',members:[{user_id:'foreman',history_from:NOW},{user_id:'other',history_from:NOW}]},'channel');
 const source='Haus A 3. OG Fenster reinigen; Haus A 5. OG Flur fegen; Haus B EG Müll entfernen.';
 await tx.add('message',{channel_id:'channel',author_id:'foreman',message_version:1,source:'HUMAN',text:source,language:'DE'},'message');
 await tx.add('assistant_config',{status:'ACTIVE',configVersion:1,model:'synthetic-model',timeoutMs:1000,tone:'PROFESSIONAL',addressForm:'Sie',humanHours:[],testOnly:true,provider:'DEEPSEEK'},'config');
 await tx.add('material',{active:true,name:'Cleaning liquid',baseUnit:'ml',conversions:[{unit:'l',numerator:1000,denominator:1}]},'material');
 await tx.add('customer',{name:'Synthetic customer',address:'Teststraße 24'},'customer');await tx.add('order',{siteId:'a',customerId:'customer',finalNetCents:10000,baseNetCents:10000,approvedChangesNetCents:0,pricingModel:'FIXED',status:'ACTIVE',tax:{rateBps:1900}},'order');
 const input={messageId:'message',messageVersion:1,channelId:'channel',configId:'config',configVersion:1,kind:'TASK_BATCH' as const,siteIds:['a','b'],context:{locationIds:['a3','a5','b0','b3'],assigneeIds:['worker']}};
 const raw={kind:'TASK_BATCH' as const,needsClarification:false,clarification:null,input:{tasks:[{siteId:'a',locationId:'a3',title:'Fenster reinigen',description:'Original instruction 3. OG',assigneeIds:['worker'],sourceQuote:'Haus A 3. OG Fenster reinigen',checklist:[{id:'clean',label:'Fenster sind gereinigt',required:true,checked:false as const}],acceptanceCriteria:['Keine sichtbaren Rückstände']},{siteId:'a',locationId:'a5',title:'Flur fegen',sourceQuote:'Haus A 5. OG Flur fegen'},{siteId:'b',locationId:'b0',title:'Müll entfernen',sourceQuote:'Haus B EG Müll entfernen'}]}};
 const command=async(name:string,data:Data,userId='foreman')=>host.transaction('company',userId,async tx=>{const actor=await host.actorIn(tx,userId);const def=host.registry[name]!;return def.handler(host.context(tx,actor,'command-'+(++requestSeq),undefined,NOW,def.permission),def.schema.parse(data));});
 const change=async(kind:string,id:string,data:Data)=>{const e=await tx.get(kind,id);return tx.save(e,{...e.data,...data});};
 const request=async(data:Data={})=>command('internal_assistant.request',{...input,...data});
 const prepare=async(data:Data={})=>{const r=await request(data),p=await prepareInternalAssistant('company',r.id,host);assert(!p.done,'INVALID_STATE');return {request:r,prepared:p};};
 const store=async(rawProposal:unknown=raw,data:Data={})=>{const p=await prepare(data);const proposal=parseInternalDraftProposal(rawProposal,p.prepared.providerInput);const result:InternalAssistantProviderResult={proposal,provider:'synthetic-fixture',model:'synthetic-model',usage:{input_tokens:100,output_tokens:50,cost_cents:1}};return {...p,result,draft:await persistInternalAssistantDraft('company',p.request.id,p.prepared.contextHash,result,host)};};
 const confirm=(draft:Data,userId='foreman')=>command('internal_assistant.confirm',{draftId:draft.draftId,expectedVersion:draft.draftVersion,previewHash:draft.previewHash,confirmed:true},userId);
 return {tx,host,input,raw,source,denied,invocations,command,change,request,prepare,store,confirm,setLease:(v:boolean)=>lease=v};
}

describe('scoped private internal AI drafts (CPU/domain, no SQL/provider acceptance)',()=>{
 it('three explicit floor/site instructions remain private previews until one human confirmation creates exactly three canonical tasks',async()=>{const f=await fixture(),d=await f.store();expect(await f.tx.list('task')).toEqual([]);expect(d.draft.preview.tasks).toHaveLength(3);expect(d.draft.preview.tasks[0]).toMatchObject({fullPath:['A · Haus A','3. OG · 3. OG'],executors:[{id:'worker',label:'worker',siteIds:['a']}],checklist:[{id:'clean',checked:false}],billingScope:'INTERNAL',clientVisible:false});const result=await f.confirm(d.draft);expect(result.entityIds).toHaveLength(3);const tasks=await f.tx.list('task');expect(tasks.map(t=>[t.data.siteId,t.data.locationId])).toEqual([['a','a3'],['a','a5'],['b','b0']]);expect(tasks[0]!.data.state).toBe('ASSIGNED');expect(tasks[1]!.data.state).toBe('DRAFT');expect(tasks.every(t=>t.data.createdBy==='foreman'&&t.data.clientVisible===false&&t.data.billingScope==='INTERNAL')).toBe(true);expect(f.invocations.some(i=>i.permission==='task.create'&&i.actor==='foreman')).toBe(true);expect(await f.tx.list('report_version')).toEqual([]);});
 it('parallel confirmations and later new command keys return the existing immutable draft receipt without additional tasks',async()=>{const f=await fixture(),d=await f.store();const [a,b]=await Promise.all([f.confirm(d.draft),f.confirm(d.draft)]);expect(a).toEqual(b);expect(await f.confirm(d.draft)).toEqual(a);expect(await f.tx.list('task')).toHaveLength(3);expect(await f.tx.list('task_batch')).toHaveLength(1);expect(f.tx.events.filter(e=>e.type==='internal_assistant.confirmed')).toHaveLength(1);});
 it.each(['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','EMPLOYEE','STOREKEEPER'])('denies %s even with injected draft/create permissions',async role=>{const f=await fixture();await f.change('user','foreman',{roles:[role],permissions:['assistant.read','chat.read','task.create','task.assign']});await expect(f.request()).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.tx.list('internal_assistant_request')).toEqual([]);});
 it.each(['FOREIGN_AUTHOR','CLIENT_CHANNEL','REVOKED_MEMBER','HISTORY','OTHER_SITE','FOREIGN_CONTEXT'])('checks %s before any private draft request is saved',async condition=>{const f=await fixture();if(condition==='FOREIGN_AUTHOR')await f.change('message','message',{author_id:'other'});if(condition==='CLIENT_CHANNEL')await f.change('channel','channel',{type:'SITE_CLIENT'});if(condition==='REVOKED_MEMBER')await f.change('channel','channel',{members:[{user_id:'foreman',revoked_at:NOW}]});if(condition==='HISTORY')await f.change('channel','channel',{members:[{user_id:'foreman',history_from:'2026-10-07T00:00:00Z'}]});if(condition==='OTHER_SITE')await f.change('user','foreman',{siteIds:['a']});if(condition==='FOREIGN_CONTEXT')f.denied.add('location:a3');await expect(f.request()).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.tx.list('internal_assistant_request')).toEqual([]);});
 it('site-channel requests cannot pull another assigned site into the AI context',async()=>{const f=await fixture();await f.change('channel','channel',{type:'SITE_INTERNAL',site_id:'a'});await expect(f.request()).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('provider retrieval exposes only selected paths and label/ID metadata, never salary, bank, stock or full employee records',async()=>{const f=await fixture();await f.change('user','worker',{bank:'BANK_CANARY',salaryCents:99999,privateAddress:'PRIVATE_CANARY'});await f.tx.add('material',{name:'OTHER_MATERIAL_CANARY',baseUnit:'ml'},'hidden');await f.tx.add('payout',{employeeId:'other',amountCents:99999,bank:'PAYROLL_CANARY'});const p=await f.prepare();const json=JSON.stringify(p.prepared.providerInput);for(const canary of ['BANK_CANARY','PRIVATE_CANARY','OTHER_MATERIAL_CANARY','PAYROLL_CANARY','salaryCents'])expect(json).not.toContain(canary);expect(p.prepared.providerInput.context.locations).toHaveLength(4);expect((await f.tx.get('internal_assistant_request',p.request.id)).data.status).toBe('RUNNING');});
 it.each(['message','channel','config','location','user'])('changed %s during the provider round prevents a usable draft',async kind=>{const f=await fixture(),p=await f.prepare();const target={message:'message',channel:'channel',config:'config',location:'a3',user:'worker'}[kind]!;await f.change(kind==='config'?'assistant_config':kind,target,{changed:true});const proposal=parseInternalDraftProposal(f.raw,p.prepared.providerInput);await expect(persistInternalAssistantDraft('company',p.request.id,p.prepared.contextHash,{proposal,provider:'synthetic-fixture',model:'synthetic-model'},f.host)).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(await f.tx.list('internal_assistant_draft')).toEqual([]);expect(await f.tx.list('task')).toEqual([]);});
 it('lease loss before a claim or after provider response writes no draft/business effects',async()=>{const f=await fixture(),r=await f.request();f.setLease(false);await expect(prepareInternalAssistant('company',r.id,f.host)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect((await f.tx.get('internal_assistant_request',r.id)).data.status).toBe('PENDING');f.setLease(true);const p=await prepareInternalAssistant('company',r.id,f.host);assert(!p.done,'INVALID_STATE');f.setLease(false);await expect(persistInternalAssistantDraft('company',r.id,p.contextHash,{proposal:parseInternalDraftProposal(f.raw,p.providerInput),provider:'synthetic-fixture',model:'synthetic-model'},f.host)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await f.tx.list('internal_assistant_draft')).toEqual([]);});
 it('uncertain RUNNING requests never cause another provider round; typed terminal failure releases the current inflight marker',async()=>{const f=await fixture(),p=await f.prepare();await expect(prepareInternalAssistant('company',p.request.id,f.host)).rejects.toMatchObject({code:'PROVIDER_OUTCOME_UNKNOWN'});await failInternalAssistant('company',p.request.id,'PROVIDER_UNAVAILABLE',f.host);expect((await f.tx.get('internal_assistant_request',p.request.id)).data).toMatchObject({status:'FAILED',error:'PROVIDER_UNAVAILABLE'});expect(await prepareInternalAssistant('company',p.request.id,f.host)).toMatchObject({done:true});expect(await f.tx.list('task')).toEqual([]);});
 it('revalidates selected context and current rights after reservation, immediately before any provider call',async()=>{const f=await fixture(),p=await f.prepare();await revalidateInternalAssistant('company',p.request.id,p.prepared.contextHash,f.host);await f.change('user','foreman',{roles:['EMPLOYEE']});await expect(revalidateInternalAssistant('company',p.request.id,p.prepared.contextHash,f.host)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.tx.list('internal_assistant_draft')).toEqual([]);});
 it('checks current specific AI transfer approval and exact lease again at the provider boundary',async()=>{const f=await fixture();await f.change('assistant_config','config',{testOnly:false,transferApprovalId:'approval'});await f.tx.add('legal_approval',{subject:'AI_TRANSFER',status:'APPROVED',active:true,expiresAt:'2026-10-07T00:00:00Z'},'approval');const p=await f.prepare();await revalidateInternalAssistant('company',p.request.id,p.prepared.contextHash,f.host);await f.change('legal_approval','approval',{active:false});await expect(revalidateInternalAssistant('company',p.request.id,p.prepared.contextHash,f.host)).rejects.toMatchObject({code:'NEEDS_APPROVAL'});await f.change('legal_approval','approval',{active:true});f.setLease(false);await expect(revalidateInternalAssistant('company',p.request.id,p.prepared.contextHash,f.host)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});});
 it('unknown actual provider outcomes retain the RUNNING privacy hold and refuse automatic second provider rounds',async()=>{const f=await fixture(),p=await f.prepare();await markInternalAssistantUnknown('company',p.request.id,'PROVIDER_OUTCOME_UNKNOWN',f.host);await markInternalAssistantUnknown('company',p.request.id,'PROVIDER_OUTCOME_UNKNOWN',f.host);expect((await f.tx.get('internal_assistant_request',p.request.id)).data).toMatchObject({status:'RUNNING',providerOutcome:'UNKNOWN',error:'PROVIDER_OUTCOME_UNKNOWN'});expect(f.tx.events.filter(e=>e.type==='internal_assistant.outcome_unknown')).toHaveLength(1);await expect(prepareInternalAssistant('company',p.request.id,f.host)).rejects.toMatchObject({code:'PROVIDER_OUTCOME_UNKNOWN'});await expect(failInternalAssistant('company',p.request.id,'PROVIDER_UNAVAILABLE',f.host)).rejects.toMatchObject({code:'PROVIDER_OUTCOME_UNKNOWN'});f.setLease(false);await expect(markInternalAssistantUnknown('company',p.request.id,'WORKER_LEASE_LOST',f.host)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect((await f.tx.get('internal_assistant_request',p.request.id)).data.status).toBe('RUNNING');});
 it('an ambiguous floor yields a private clarification with no confirmable command',async()=>{const f=await fixture();const d=await f.store({kind:'TASK_BATCH',needsClarification:true,clarification:'Welches Gebäude und EG oder 1. OG?',input:null});expect(d.draft).toMatchObject({needsClarification:true,requiresUserConfirmation:false,status:'NEEDS_CLARIFICATION'});await expect(f.confirm(d.draft)).rejects.toMatchObject({code:'INVALID_STATE'});expect(await f.tx.list('task')).toEqual([]);});
 it('other authors, stale preview hashes and tampered canonical plans cannot confirm a private draft',async()=>{const f=await fixture(),d=await f.store();await expect(f.confirm(d.draft,'other')).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(f.confirm({...d.draft,previewHash:'0'.repeat(64)})).rejects.toMatchObject({code:'VERSION_CONFLICT'});await f.change('internal_assistant_draft',d.draft.draftId,{canonicalInput:{batchKey:'evil',tasks:[]}});await expect(f.confirm(d.draft)).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(await f.tx.list('task')).toEqual([]);});
 it('revoked assignment rights and changed selected full paths block confirmation',async()=>{const f=await fixture(),d=await f.store();await f.change('location','a3',{name:'Changed target'});await expect(f.confirm(d.draft)).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(await f.tx.list('task')).toEqual([]);await f.change('user','foreman',{roles:['TEAM_LEADER']});await expect(f.confirm(d.draft)).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('a failure on a later canonical task rolls back the whole batch, draft receipt and business events',async()=>{const f=await fixture(),d=await f.store();const original=f.tx.add.bind(f.tx);let taskCount=0;f.tx.add=async(kind,data,id)=>{if(kind==='task'&&++taskCount===2)throw new DomainError('SIMULATED_BATCH_FAILURE');return original(kind,data,id);};await expect(f.confirm(d.draft)).rejects.toMatchObject({code:'SIMULATED_BATCH_FAILURE'});expect(await f.tx.list('task')).toEqual([]);expect(await f.tx.list('task_batch')).toEqual([]);expect((await f.tx.get('internal_assistant_draft',d.draft.draftId)).data.state).toBe('DRAFT');expect(f.tx.events.some(e=>e.type==='task.created')).toBe(false);});
 it('confirmed material creates an exact own DRAFT only, with no submit, order, approval or stock movement',async()=>{const f=await fixture();await f.change('message','message',{text:'2.5 l Cleaning liquid due 2026-10-07T08:00:00Z'});const d=await f.store({kind:'MATERIAL_REQUEST',needsClarification:false,clarification:null,input:{siteId:'a',materialId:'material',quantity:'2.5',unit:'l',dueAt:'2026-10-07T08:00:00Z',reason:'Für Fenster Haus A.'}},{kind:'MATERIAL_REQUEST',siteIds:['a'],context:{materialIds:['material']}});expect(await f.tx.list('material_request')).toEqual([]);await f.confirm(d.draft);expect((await f.tx.list('material_request'))[0]!.data).toMatchObject({state:'DRAFT',employeeId:'foreman',quantityBase:2500});for(const kind of ['purchase_order','stock_movement','payout','trip'])expect(await f.tx.list(kind)).toEqual([]);});
 it('confirmed task-based report creates canonical DRAFT, without publication, delivery, timesheet or legal work acceptance',async()=>{const f=await fixture();await f.change('message','message',{text:'Leistungsnachweis für Haus A 2026-10-06T08:00:00Z bis 2026-10-06T10:00:00Z'});const d=await f.store({kind:'REPORT',needsClarification:false,clarification:null,input:{siteId:'a',customerId:'customer',orderId:'order',periodStart:'2026-10-06T08:00:00Z',periodEnd:'2026-10-06T10:00:00Z',documentType:'Leistungsnachweis',taskIds:[],descriptionDe:'Arbeitsstand ist zur Prüfung vorbereitet.'}},{kind:'REPORT',siteIds:['a'],context:{orderIds:['order']}});expect(await f.tx.list('report')).toEqual([]);await f.confirm(d.draft);expect((await f.tx.list('report'))[0]!.data).toMatchObject({state:'DRAFT',createdBy:'foreman'});expect(await f.tx.list('report_version')).toEqual([]);expect(await f.tx.list('delivery')).toEqual([]);});
});
