import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,describe,it,expect,vi} from 'vitest';
import {DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';
import {integrationCommands,integrationEnvelopeSchema,integrationOutboundPreview,type IntegrationEnvelope} from '../packages/domain/integrations.ts';
import {INTEGRATION_MAX_BODY_BYTES,parseIntegrationCredentials,parseSignedIntegrationJson,selectIntegrationCredential,signIntegrationEvent,verifyIntegrationEventSignature,type IntegrationCredential} from '../packages/integrations/generic-events.ts';
import {acceptIntegrationEvent,integrationEventError} from '../apps/api/integration-events.ts';
import {Database} from '../apps/api/database.ts';

const NOW='2026-10-09T10:00:00.000Z',NOW_MS=Date.parse(NOW),STAMP=String(NOW_MS/1000),SECRET='synthetic-test-secret-never-a-live-key-123456789',SOURCE='synthetic_crm';
const credential:IntegrationCredential={source:SOURCE,companyId:'company',keyId:'key_1',secret:SECRET,enabled:true};
const actor:Actor={companyId:'company',userId:'owner',roles:['OWNER'],permissions:['bot.settings.manage'],siteIds:[],warehouseIds:[],customerIds:[],mfaVerified:true};
function event(overrides:Partial<IntegrationEnvelope>={}):IntegrationEnvelope{return integrationEnvelopeSchema.parse({schema_version:'1',event_id:'event_1',event_type:'lead.upsert',source:SOURCE,occurred_at:NOW,external_id:'external_1',payload:{contact:{name:'Synthetic contact',email:'synthetic@example.test'},serviceIds:['service_1'],facts:{quantityMilli:1000,measurementSource:'CUSTOMER_STATED'},source:{campaign:'Actual received synthetic campaign'}},...overrides});}
function headers(body:Buffer,secret=SECRET,timestamp=STAMP){return {keyId:'key_1',timestamp,signature:signIntegrationEvent(body,timestamp,secret)};}
class MemoryTransaction implements Transaction{
 rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];sequence=0;constructor(public companyId='company'){}
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const row=this.rows.get(`${kind}:${id}`);if(!row||row.companyId!==this.companyId)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(row) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.rows.values()].filter(row=>row.companyId===this.companyId&&row.kind===kind).map(row=>structuredClone(row) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`row_${++this.sequence}`):Promise<Entity<T>>{if(this.rows.has(`${kind}:${id}`))throw new DomainError('VERSION_CONFLICT');const row={companyId:this.companyId,kind,id,data:structuredClone(data),version:1,createdAt:NOW,updatedAt:NOW};this.rows.set(`${kind}:${id}`,row);return structuredClone(row);}
 async save(entity:Entity,data:Data,expectedVersion=entity.version){const row=await this.get(entity.kind,entity.id);if(row.version!==expectedVersion)throw new DomainError('VERSION_CONFLICT');const result={...row,data:structuredClone(data),version:row.version+1,updatedAt:NOW};this.rows.set(`${entity.kind}:${entity.id}`,result);return structuredClone(result);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
}
function context(tx:Transaction,now=NOW):CommandContext{return {tx,actor,now,idempotencyKey:'synthetic-integration-command',requireOwn(){throw new Error('Unexpected own access');},requireSite(){throw new Error('Unexpected site access');}};}
async function command(tx:Transaction,name:string,input:Data,now=NOW){const def=integrationCommands[name]!;return def.handler(context(tx,now),def.schema.parse(input));}
async function prepare(tx:Transaction){await tx.add('user',{roles:['OWNER'],active:true},'owner');await tx.add('service',{active:true},'service_1');const config=await command(tx,'integration_config.create',{source:SOURCE,ownerUserId:'owner',allowedServiceIds:['service_1'],credentialKeyIds:['key_1']});const preview=await command(tx,'integration_config.preview',{id:config.id,example:event()});const active=await command(tx,'integration_config.activate',{id:config.id,command_hash:preview.command_hash,expected_version:preview.expected_version});return {config,preview,active};}
function memoryDb(tx:MemoryTransaction){return {transaction:vi.fn(async(companyId:string,_actorId:string,fn:(current:Transaction)=>Promise<unknown>)=>{expect(companyId).toBe(tx.companyId);const rows=structuredClone(tx.rows),events=structuredClone(tx.events),sequence=tx.sequence;try{return await fn(tx);}catch(error){tx.rows=rows;tx.events=events;tx.sequence=sequence;throw error;}})} as unknown as Pick<Database,'transaction'>;}
async function submit(db:Pick<Database,'transaction'>,envelope:IntegrationEnvelope,credentials=[credential]){const body=Buffer.from(JSON.stringify(envelope));return acceptIntegrationEvent(db,credentials,SOURCE,body,headers(body),NOW_MS);}

describe('generic connector raw-byte authentication and server-side credentials',()=>{
 it('authenticates exact timestamp and bytes and rejects independent body/timestamp/key tampering',()=>{const body=Buffer.from(JSON.stringify(event())),signature=signIntegrationEvent(body,STAMP,SECRET);expect(verifyIntegrationEventSignature(body,STAMP,signature,SECRET,NOW_MS)).toBe(true);expect(verifyIntegrationEventSignature(Buffer.from(body.toString().replace('Synthetic contact','Different contact')),STAMP,signature,SECRET,NOW_MS)).toBe(false);expect(verifyIntegrationEventSignature(body,String(Number(STAMP)+1),signature,SECRET,NOW_MS)).toBe(false);expect(verifyIntegrationEventSignature(body,STAMP,signature,SECRET+'changed',NOW_MS)).toBe(false);});
 it.each([-301,301])('rejects timestamp outside the five-minute replay window (%s sec)',offset=>{const body=Buffer.from(JSON.stringify(event())),timestamp=String(Number(STAMP)+offset);expect(verifyIntegrationEventSignature(body,timestamp,signIntegrationEvent(body,timestamp,SECRET),SECRET,NOW_MS)).toBe(false);});
 it.each([-300,300])('accepts valid signed replay boundary (%s sec)',offset=>{const body=Buffer.from(JSON.stringify(event())),timestamp=String(Number(STAMP)+offset);expect(verifyIntegrationEventSignature(body,timestamp,signIntegrationEvent(body,timestamp,SECRET),SECRET,NOW_MS)).toBe(true);});
 it.each([undefined,[],['1','2'],'NaN','1.0','+1791530000'])('rejects malformed or duplicate timestamp values %#',timestamp=>{const body=Buffer.from('{}');expect(verifyIntegrationEventSignature(body,timestamp,'sha256='+'a'.repeat(64),SECRET,NOW_MS)).toBe(false);});
 it.each(['sha256='+ 'a'.repeat(63),'sha256='+ 'A'.repeat(64),'sha512='+ 'a'.repeat(64),['sha256='+ 'a'.repeat(64)]])('rejects malformed signature without an unsafe timing comparison %#',signature=>{expect(verifyIntegrationEventSignature(Buffer.from('{}'),STAMP,signature,SECRET,NOW_MS)).toBe(false);});
 it('rejects oversized/empty raw bodies before parsing',()=>{expect(verifyIntegrationEventSignature(Buffer.alloc(INTEGRATION_MAX_BODY_BYTES+1),STAMP,'sha256='+'a'.repeat(64),SECRET,NOW_MS)).toBe(false);expect(()=>parseSignedIntegrationJson(Buffer.alloc(0))).toThrow('VALIDATION_ERROR');});
 it.each(['{"payload":{"__proto__":{"admin":true}}}','{"payload":{"nested":{"constructor":"x"}}}','{"prototype":{}}'])('rejects nested prototype keys without pollution %#',body=>{expect(()=>parseSignedIntegrationJson(Buffer.from(body))).toThrow('VALIDATION_ERROR');expect(({} as any).admin).toBeUndefined();});
 it('rejects invalid UTF-8 and bounded JSON depth before schema coercion',()=>{expect(()=>parseSignedIntegrationJson(Buffer.from([0xc0,0xaf]))).toThrow('VALIDATION_ERROR');expect(()=>parseSignedIntegrationJson(Buffer.from('['.repeat(22)+'0'+']'.repeat(22)))).toThrow('VALIDATION_ERROR');});
 it('rotates credential versions via bounded windows; expired and disabled keys deny access',()=>{const old={...credential,notAfter:'2026-10-09T10:00:00.000Z'},next={...credential,keyId:'key_2',secret:SECRET+'2',notBefore:NOW};const keys=parseIntegrationCredentials(JSON.stringify([old,next]));expect(selectIntegrationCredential(keys,SOURCE,'key_2',NOW_MS)).toMatchObject({keyId:'key_2'});expect(()=>selectIntegrationCredential(keys,SOURCE,'key_1',NOW_MS)).toThrow('ACCESS_DENIED');expect(()=>selectIntegrationCredential([{...credential,enabled:false}],SOURCE,'key_1',NOW_MS)).toThrow('ACCESS_DENIED');});
 it('prevents ambiguous key identities or mapping one source to different companies',()=>{expect(()=>parseIntegrationCredentials(JSON.stringify([credential,credential]))).toThrow('MISSING_CONFIGURATION');expect(()=>parseIntegrationCredentials(JSON.stringify([credential,{...credential,keyId:'other',companyId:'other_company'}]))).toThrow('MISSING_CONFIGURATION');});
 it('never authenticates an unknown route/key by falling back to another source credential',()=>{expect(()=>selectIntegrationCredential([credential],'unknown','key_1',NOW_MS)).toThrow('ACCESS_DENIED');expect(()=>selectIntegrationCredential([credential],SOURCE,'unknown',NOW_MS)).toThrow('ACCESS_DENIED');expect(parseIntegrationCredentials(undefined)).toEqual([]);});
 it('invalid signatures never open the company transaction',async()=>{const db={transaction:vi.fn()};const body=Buffer.from(JSON.stringify(event()));await expect(acceptIntegrationEvent(db as any,[credential],SOURCE,body,{...headers(body),signature:'sha256='+'a'.repeat(64)},NOW_MS)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(db.transaction).not.toHaveBeenCalled();});
 it('forbids caller-defined envelope company and mismatched source before touching the DB',async()=>{const db={transaction:vi.fn()};for(const envelope of [{...event(),company_id:'other_company'},{...event(),source:'other_source'}]){const body=Buffer.from(JSON.stringify(envelope));await expect(acceptIntegrationEvent(db as any,[credential],SOURCE,body,headers(body),NOW_MS)).rejects.toMatchObject({code:'VALIDATION_ERROR'});}expect(db.transaction).not.toHaveBeenCalled();});
});

describe('connector approval, durable deduplication and conservative mapping',()=>{
 it('requires a successful effect-free dry run and exact single-use activation preview',async()=>{const tx=new MemoryTransaction();const {config,preview}=await prepare(tx);expect(preview.dryRun).toMatchObject({businessEffects:0,providerInvoked:false,targetKind:'lead'});expect(await tx.list('lead')).toHaveLength(0);await expect(command(tx,'integration_config.activate',{id:config.id,command_hash:preview.command_hash,expected_version:preview.expected_version})).rejects.toMatchObject({code:'VERSION_CONFLICT'});});
 it('rejects a preview at ten minutes and changed parameters/version',async()=>{const tx=new MemoryTransaction();await tx.add('user',{roles:['OWNER'],active:true},'owner');await tx.add('service',{active:true},'service_1');const config=await command(tx,'integration_config.create',{source:SOURCE,ownerUserId:'owner',allowedServiceIds:['service_1'],credentialKeyIds:['key_1']});const preview=await command(tx,'integration_config.preview',{id:config.id,example:event()});await expect(command(tx,'integration_config.activate',{id:config.id,command_hash:preview.command_hash,expected_version:preview.expected_version},'2026-10-09T10:10:00.000Z')).rejects.toMatchObject({code:'NEEDS_REAUTH'});await expect(command(tx,'integration_config.activate',{id:config.id,command_hash:'a'.repeat(64),expected_version:preview.expected_version})).rejects.toMatchObject({code:'VERSION_CONFLICT'});const row=await tx.get('integration_config',config.id);row.data.originChannel='AD';tx.rows.set(`integration_config:${row.id}`,row);await expect(command(tx,'integration_config.activate',{id:config.id,command_hash:preview.command_hash,expected_version:preview.expected_version})).rejects.toMatchObject({code:'VERSION_CONFLICT'});});
 it('ten identical events produce one lead, one durable event and one business outbox effect',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx);const receipts=[];for(let n=0;n<10;n++)receipts.push(await submit(db,event()));expect(receipts.filter(receipt=>!receipt.duplicate)).toHaveLength(1);expect(new Set(receipts.map(receipt=>receipt.effect_id)).size).toBe(1);expect(await tx.list('lead')).toHaveLength(1);expect(await tx.list('integration_event')).toHaveLength(1);expect(tx.events.filter(receipt=>receipt.type==='lead.created')).toHaveLength(1);expect((await tx.list('lead'))[0]!.data).toMatchObject({status:'NEW',review_state:'NONE',marketingConsent:false});});
 it('signs different JSON formatting independently and deduplicates the same semantic event',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx);await submit(db,event());const body=Buffer.from(JSON.stringify(event(),null,2));expect(await acceptIntegrationEvent(db,[credential],SOURCE,body,headers(body),NOW_MS)).toMatchObject({duplicate:true,status:'APPLIED'});expect(await tx.list('lead')).toHaveLength(1);});
 it('upserts source/external identity without duplicate leads or changed lifecycle/review/consent',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx),first=await submit(db,event());const next=event({event_id:'event_2',occurred_at:'2026-10-09T10:01:00.000Z',payload:{...event().payload,contact:{name:'Changed imported contact',email:'synthetic@example.test'}}});expect(await submit(db,next)).toMatchObject({effect_id:first.effect_id,status:'APPLIED'});const lead=(await tx.list('lead'))[0]!;expect(await tx.list('lead')).toHaveLength(1);expect(lead.data).toMatchObject({status:'NEW',review_state:'NONE',ownership:'AI_ACTIVE',marketingConsent:false,contact:{name:'Changed imported contact'}});});
 it('unchanged new event IDs do not repeat business updates; independent external IDs remain independent',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx);const initial=await submit(db,event());const version=(await tx.get('lead',initial.effect_id!)).version;await submit(db,event({event_id:'another_delivery'}));expect((await tx.get('lead',initial.effect_id!)).version).toBe(version);expect(tx.events.filter(item=>item.type==='lead.integration_updated')).toHaveLength(0);await submit(db,event({event_id:'other_external_event',external_id:'other_external'}));expect(await tx.list('lead')).toHaveLength(2);});
 it('quarantines internally modified lead facts/lifecycle while preserving authoritative data',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx),accepted=await submit(db,event());const lead=await tx.get('lead',accepted.effect_id!);await tx.save(lead,{...lead.data,status:'QUALIFIED',review_state:'HUMAN_REVIEW_REQUIRED',facts:{quantityMilli:2000,measurementSource:'VERIFIED'}});const receipt=await submit(db,event({event_id:'event_2',occurred_at:'2026-10-09T10:01:00.000Z'}));expect(receipt).toMatchObject({status:'QUARANTINED',reason:'INTERNAL_RECORD_CHANGED'});expect((await tx.get('lead',lead.id)).data).toMatchObject({status:'QUALIFIED',review_state:'HUMAN_REVIEW_REQUIRED',facts:{quantityMilli:2000,measurementSource:'VERIFIED'}});});
 it('same event ID with changed content quarantines once and retains the first accepted effect',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx);const original=await submit(db,event());const conflict=event({payload:{...event().payload,language:'UK'}});const first=await submit(db,conflict),repeat=await submit(db,conflict);expect(first).toMatchObject({status:'QUARANTINED',reason:'EVENT_ID_PAYLOAD_CONFLICT',duplicate:false});expect(repeat).toMatchObject({status:'QUARANTINED',duplicate:true,quarantine_id:first.quarantine_id});expect((await tx.get('lead',original.effect_id!)).data.language).toBe('DE');expect(await tx.list('integration_quarantine')).toHaveLength(1);expect(await submit(db,event())).toMatchObject({status:'APPLIED',duplicate:true});});
 it.each([
  ['unmapped event',{event_type:'payroll.approve'},'UNMAPPED_EVENT'],
  ['unmapped service',{payload:{...event().payload,serviceIds:['foreign_service']}},'SERVICE_NOT_MAPPED'],
  ['caller company',{payload:{...event().payload,company_id:'other_company'}},'INVALID_FIELD_MAPPING'],
  ['verified measurement',{payload:{...event().payload,facts:{measurementSource:'VERIFIED'}}},'INVALID_FIELD_MAPPING'],
  ['granting consent',{payload:{...event().payload,marketingConsent:true}},'INVALID_FIELD_MAPPING']
 ] as const)('durably quarantines %s mapping without business effects',async(_label,override,reason)=>{const tx=new MemoryTransaction();await prepare(tx);const receipt=await submit(memoryDb(tx),event(override as any));expect(receipt).toMatchObject({status:'QUARANTINED',reason});expect(await tx.list('lead')).toHaveLength(0);expect(await tx.list('integration_event')).toHaveLength(1);expect(await tx.list('integration_quarantine')).toHaveLength(1);});
 it('older events and equal-time conflicting facts cannot overwrite a newer external record',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx);await submit(db,event());const changed={...event().payload,language:'UK'};expect(await submit(db,event({event_id:'older',occurred_at:'2026-10-09T09:59:00.000Z',payload:changed}))).toMatchObject({status:'QUARANTINED',reason:'STALE_EXTERNAL_EVENT'});expect(await submit(db,event({event_id:'equal_time',payload:changed}))).toMatchObject({status:'QUARANTINED',reason:'EXTERNAL_ORDER_CONFLICT'});expect((await tx.list('lead'))[0]!.data.language).toBe('DE');});
 it('a paused or changed active mapping cannot accept or silently rewrite events',async()=>{const tx=new MemoryTransaction();const {active}=await prepare(tx);await command(tx,'integration_config.pause',{id:active.id,reason:'Explicit synthetic maintenance'});await expect(submit(memoryDb(tx),event())).rejects.toMatchObject({code:'NEEDS_APPROVAL'});expect(await tx.list('lead')).toHaveLength(0);});
 it('server credential company determines the transaction and no payload field can switch it',async()=>{const tx=new MemoryTransaction('server_mapped_company');await prepare(tx);const keys=[{...credential,companyId:tx.companyId}];const result=await submit(memoryDb(tx),event(),keys);expect((await tx.get('lead',result.effect_id!)).companyId).toBe('server_mapped_company');});
 it('rotating credential key IDs preserves the approved business mapping and existing external identity',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx),initial=await submit(db,event());const draft=await command(tx,'integration_config.create',{source:SOURCE,ownerUserId:'owner',allowedServiceIds:['service_1'],credentialKeyIds:['key_1','key_2']});const preview=await command(tx,'integration_config.preview',{id:draft.id,example:event()});await command(tx,'integration_config.activate',{id:draft.id,command_hash:preview.command_hash,expected_version:preview.expected_version});const key={...credential,keyId:'key_2',secret:SECRET+'new'},body=Buffer.from(JSON.stringify(event({event_id:'rotated_key_event',occurred_at:'2026-10-09T10:01:00.000Z',payload:{...event().payload,language:'UK'}})));expect(await acceptIntegrationEvent(db,[key],SOURCE,body,{...headers(body,key.secret),keyId:key.keyId},NOW_MS)).toMatchObject({status:'APPLIED',effect_id:initial.effect_id});expect(await tx.list('lead')).toHaveLength(1);});
 it('changed business mapping creates a durable review instead of remapping an existing lead',async()=>{const tx=new MemoryTransaction();await prepare(tx);const db=memoryDb(tx);await submit(db,event());const draft=await command(tx,'integration_config.create',{source:SOURCE,ownerUserId:'owner',allowedServiceIds:['service_1'],credentialKeyIds:['key_1'],originChannel:'AD'});const preview=await command(tx,'integration_config.preview',{id:draft.id,example:event()});await command(tx,'integration_config.activate',{id:draft.id,command_hash:preview.command_hash,expected_version:preview.expected_version});expect(await submit(db,event({event_id:'new_mapping_event',occurred_at:'2026-10-09T10:01:00.000Z'}))).toMatchObject({status:'QUARANTINED',reason:'EXTERNAL_MAPPING_CONFLICT'});expect((await tx.list('lead'))[0]!.data.source.channel).toBe('WEB');});
 it('a configured but unapproved credential key cannot create an inbox or business effect',async()=>{const tx=new MemoryTransaction();await prepare(tx);const key={...credential,keyId:'unapproved'},body=Buffer.from(JSON.stringify(event()));await expect(acceptIntegrationEvent(memoryDb(tx),[key],SOURCE,body,{...headers(body),keyId:key.keyId},NOW_MS)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await tx.list('integration_event')).toHaveLength(0);expect(await tx.list('lead')).toHaveLength(0);});
 it('DB commit failure returns a dependency error, never a durable acknowledgement',async()=>{const body=Buffer.from(JSON.stringify(event())),db={transaction:vi.fn(async()=>{throw new Error('Synthetic dependency outage');})};let caught:unknown;try{await acceptIntegrationEvent(db as any,[credential],SOURCE,body,headers(body),NOW_MS);}catch(error){caught=error;}expect(integrationEventError(caught)).toEqual({status:503,body:{code:'DEPENDENCY_UNAVAILABLE'}});expect(integrationEventError(new DomainError('ACCESS_DENIED',{secret:SECRET}))).toEqual({status:401,body:{code:'ACCESS_DENIED'}});});
 it('outbound preview applies a fixed minimized allowlist rather than copying a business aggregate',()=>{const row:Entity={companyId:'company',id:'lead',kind:'lead',version:1,createdAt:NOW,updatedAt:NOW,data:{status:'NEW',review_state:'NONE',language:'DE',contact:{email:'private@example.test'},payroll:50000,gps:{latitude:52},secret:SECRET,notesInternal:'private'}};expect(integrationOutboundPreview(SOURCE,'outbound_1',row,NOW).payload).toEqual({id:'lead',status:'NEW',review_state:'NONE',language:'DE'});});
});

const postgres=process.env.DATABASE_URL?describe:describe.skip;
postgres('real PostgreSQL generic connector atomicity and concurrency',()=>{
 let db:Database;const company=`integration-qa-${randomUUID()}`;let keys:IntegrationCredential[];
 beforeAll(async()=>{db=new Database();await db.migrate();keys=[{...credential,companyId:company}];await db.transaction(company,'QA_FIXTURE',tx=>prepare(tx));});
 afterAll(async()=>{await db?.close();});
 it('ten concurrent signed deliveries commit one authoritative lead/event/outbox effect',async()=>{const receipts=await Promise.all(Array.from({length:10},()=>submit(db,event({event_id:'concurrent_event',external_id:'concurrent_external'}),keys)));expect(receipts.filter(receipt=>!receipt.duplicate)).toHaveLength(1);expect(new Set(receipts.map(receipt=>receipt.effect_id)).size).toBe(1);expect((await db.query("SELECT count(*)::int AS count FROM aggregates WHERE company_id=$1 AND kind='integration_event' AND data->>'eventId'='concurrent_event'",[company])).rows[0].count).toBe(1);expect((await db.query("SELECT count(*)::int AS count FROM outbox WHERE company_id=$1 AND type='lead.created' AND data->>'leadId'=$2",[company,receipts[0]!.effect_id])).rows[0].count).toBe(1);});
 it('conflicting concurrent payloads commit one effect and one durable quarantine without overwriting',async()=>{const original=event({event_id:'conflict_event',external_id:'conflict_external'}),conflict=event({...original,payload:{...original.payload,language:'UK'}});const receipts=await Promise.all([submit(db,original,keys),submit(db,conflict,keys)]);expect(receipts.map(item=>item.status).sort()).toEqual(['APPLIED','QUARANTINED']);const accepted=receipts.find(item=>item.status==='APPLIED')!;expect((await db.query("SELECT data FROM aggregates WHERE company_id=$1 AND kind='lead' AND id=$2",[company,accepted.effect_id])).rows[0].data.language).toBe(receipts[0]!.status==='APPLIED'?'DE':'UK');expect((await db.query("SELECT count(*)::int AS count FROM aggregates WHERE company_id=$1 AND kind='integration_quarantine' AND data->>'eventId'='conflict_event'",[company])).rows[0].count).toBe(1);});
 it('transaction rollback removes business effect, dedup key, audit and outbox together',async()=>{let provisionalId:string|undefined;const broken={transaction:(companyId:string,actorId:string,fn:(tx:Transaction)=>Promise<unknown>)=>db.transaction(companyId,actorId,async tx=>{const result=await fn(tx);provisionalId=(result as {effect_id:string}).effect_id;throw new Error('Synthetic precommit failure');})} as unknown as Pick<Database,'transaction'>;await expect(submit(broken,event({event_id:'rollback_event',external_id:'rollback_external'}),keys)).rejects.toThrow('Synthetic precommit failure');expect(provisionalId).toBeTruthy();expect((await db.query("SELECT count(*)::int AS count FROM aggregates WHERE company_id=$1 AND (id=$2 OR kind IN('integration_event','integration_record') AND (data->>'eventId'='rollback_event' OR data->>'externalId'='rollback_external'))",[company,provisionalId])).rows[0].count).toBe(0);expect((await db.query('SELECT count(*)::int AS count FROM audit_log WHERE company_id=$1 AND aggregate_id=$2',[company,provisionalId])).rows[0].count).toBe(0);expect((await db.query("SELECT count(*)::int AS count FROM outbox WHERE company_id=$1 AND data->>'leadId'=$2",[company,provisionalId])).rows[0].count).toBe(0);const receipt=await submit(db,event({event_id:'rollback_event',external_id:'rollback_external'}),keys);expect(receipt).toMatchObject({status:'APPLIED',duplicate:false});expect((await db.query("SELECT count(*)::int AS count FROM outbox WHERE company_id=$1 AND type='lead.created' AND data->>'leadId'=$2",[company,receipt.effect_id])).rows[0].count).toBe(1);});
 it('identical source/event/external IDs in separately credential-mapped companies cannot collide',async()=>{const otherCompany=`integration-qa-other-${randomUUID()}`;await db.transaction(otherCompany,'QA_FIXTURE',tx=>prepare(tx));const same=event({event_id:'company_scoped_event',external_id:'company_scoped_external'});const [left,right]=await Promise.all([submit(db,same,keys),submit(db,same,[{...credential,companyId:otherCompany}])]);expect(left.status).toBe('APPLIED');expect(right.status).toBe('APPLIED');expect(left.effect_id).not.toBe(right.effect_id);expect((await db.query("SELECT company_id FROM aggregates WHERE kind='lead' AND id=ANY($1::text[]) ORDER BY company_id",[[left.effect_id,right.effect_id]])).rows.map(row=>row.company_id).sort()).toEqual([company,otherCompany].sort());});
});
