import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,describe,it,expect,vi} from 'vitest';
import {DomainError,assert,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';
import {integrationCommands,applyIntegrationEnvelope,integrationEnvelopeSchema} from '../packages/domain/integrations.ts';
import {integrationOutboundCommands} from '../packages/domain/integration-outbound.ts';
import {IntegrationWebhookAdapter,publicIntegrationAddress,validateIntegrationWebhookUrl,type IntegrationWebhookTransport} from '../packages/integrations/outbound-webhook.ts';
import {verifyIntegrationEventSignature,type IntegrationCredential} from '../packages/integrations/generic-events.ts';
import {processIntegrationOutbound,type IntegrationOutboundJob} from '../apps/api/integration-outbound.ts';
import {Database} from '../apps/api/database.ts';
import {Engine} from '../apps/api/engine.ts';
import {leaseOutbox} from '../apps/worker/runner.ts';

const NOW='2026-10-09T10:00:00.000Z',NOW_MS=Date.parse(NOW),SOURCE='synthetic_crm',ENDPOINT='https://hooks.synthetic.example.com/events';
const credential:IntegrationCredential={source:SOURCE,companyId:'company',keyId:'key_1',secret:'synthetic-test-secret-never-a-live-key-123456789',enabled:true};
const actor:Actor={companyId:'company',userId:'owner',roles:['OWNER'],permissions:['bot.settings.manage'],siteIds:[],warehouseIds:[],customerIds:[],mfaVerified:true};
const envelope=(eventId='event_1',serviceId='service_1')=>integrationEnvelopeSchema.parse({schema_version:'1',event_id:eventId,event_type:'lead.upsert',source:SOURCE,external_id:'external_1',occurred_at:NOW,payload:{contact:{name:'Synthetic contact',email:'private@example.test'},serviceIds:[serviceId],language:'DE',facts:{quantityMilli:1000,measurementSource:'CUSTOMER_STATED'}}});
class MemoryTransaction implements Transaction{
 rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];sequence=0;held=true;job?:IntegrationOutboundJob;constructor(public companyId='company'){}
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const row=this.rows.get(kind+':'+id);if(!row||row.companyId!==this.companyId)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(row) as Entity<T>;}
 async list<T extends Data=Data>(kind:string){return [...this.rows.values()].filter(row=>row.kind===kind).map(row=>structuredClone(row) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id='row_'+ ++this.sequence):Promise<Entity<T>>{if(this.rows.has(kind+':'+id))throw new DomainError('VERSION_CONFLICT');const row={id,kind,data:structuredClone(data),companyId:this.companyId,version:1,createdAt:NOW,updatedAt:NOW};this.rows.set(kind+':'+id,row);return structuredClone(row);}
 async save(row:Entity,data:Data,version=row.version){const saved=await this.get(row.kind,row.id);assert(saved.version===version,'VERSION_CONFLICT');const next={...saved,data:structuredClone(data),version:version+1};this.rows.set(row.kind+':'+row.id,next);return structuredClone(next);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
 async query(_sql:string,params:unknown[]){return {rows:this.held&&this.job&&params[0]===this.companyId&&params[1]===this.job.id&&params[2]===this.job.lease_token?[{id:this.job.id,type:this.job.type,data:this.job.data}]:[]};}
}
const commands={...integrationCommands,...integrationOutboundCommands};
function context(tx:Transaction,now=NOW):CommandContext{return {tx,actor,now,idempotencyKey:'synthetic-command-key',requireSite(){throw new Error('Unexpected site');},requireOwn(){throw new Error('Unexpected own');}};}
async function command(tx:Transaction,name:string,input:Data,now=NOW){const def=commands[name]!;return def.handler(context(tx,now),def.schema.parse(input));}
async function config(tx:Transaction,services=['service_1'],outbound=true){const draft=await command(tx,'integration_config.create',{source:SOURCE,ownerUserId:'owner',allowedServiceIds:services,credentialKeyIds:['key_1'],...outbound?{outbound:{url:ENDPOINT,credentialKeyId:'key_1',approvalReference:'synthetic-privacy-approval'}}:{}});const preview=await command(tx,'integration_config.preview',{id:draft.id,example:envelope('preview',services[0])});return command(tx,'integration_config.activate',{id:draft.id,command_hash:preview.command_hash,expected_version:preview.expected_version});}
async function setup(tx:Transaction){await tx.add('user',{active:true,roles:['OWNER']},'owner');await tx.add('service',{active:true},'service_1');await tx.add('legal_approval',{subject:'PRIVACY',status:'APPROVED',active:true,approvedAt:'2026-10-01T00:00:00.000Z',expiresAt:'2026-10-10T00:00:00.000Z',evidenceReference:'Synthetic recorded review reference, not a real legal clearance',approvalType:'RECORDED_EXTERNAL_REVIEW',scope:{integrationOutbound:{sources:[SOURCE],endpoints:[ENDPOINT],allowedFields:['id','status','review_state','language'],allowedEventTypes:['lead.status']}}},'synthetic-privacy-approval');return config(tx);}
async function outbound(tx:Transaction){const active=await setup(tx);const accepted=await applyIntegrationEnvelope(tx,active,envelope(),'key_1',NOW);const preview=await command(tx,'integration_outbound.preview',{config_id:active.id,external_id:'external_1'});await command(tx,'integration_outbound.enqueue',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version});return {active,accepted,preview};}
function adapter(transport:IntegrationWebhookTransport,options:Partial<ConstructorParameters<typeof IntegrationWebhookAdapter>[1]>={}){return new IntegrationWebhookAdapter([credential],{liveSendAllowed:true,now:()=>NOW_MS,resolve:async()=>[{address:'8.8.8.8',family:4}],transport,...options});}
function dbFixture(tx:MemoryTransaction){return {transaction:async(_company:string,_actor:string,fn:(tx:MemoryTransaction)=>Promise<unknown>)=>fn(tx)} as unknown as Pick<Database,'transaction'>;}
const host={actorIn:async(tx:any,userId:string)=>{const user=await tx.get('user',userId);assert(user.data.active!==false,'ACCESS_DENIED');return {...actor,companyId:tx.companyId,permissions:user.data.roles.includes('OWNER')?['bot.settings.manage']:[]};},scope:(current:Actor)=>current};

describe('explicit quarantine review and immutable decisions',()=>{
 it('retries the original authenticated envelope only after updated mapping approval',async()=>{const tx=new MemoryTransaction(),active=await setup(tx);const quarantined=await applyIntegrationEnvelope(tx,active,envelope('quarantined','service_2'),'key_1',NOW);expect(quarantined.status).toBe('QUARANTINED');await tx.add('service',{active:true},'service_2');await config(tx,['service_1','service_2']);const preview=await command(tx,'integration_quarantine.preview',{id:quarantined.quarantine_id,action:'RETRY',reason:'Reviewed original mapped service after approval'});expect(preview.businessEffects).toBe(0);const decision=await command(tx,'integration_quarantine.resolve',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version});expect(decision).toMatchObject({status:'RESOLVED',businessEffects:1});expect((await tx.get('integration_quarantine',preview.id)).data.status).toBe('RESOLVED');expect(await tx.list('integration_decision')).toHaveLength(1);expect(await tx.list('lead')).toHaveLength(1);await expect(command(tx,'integration_quarantine.resolve',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version})).rejects.toMatchObject({code:'VERSION_CONFLICT'});});
 it('retains an unresolved internally modified lead and records review without forced overwrite',async()=>{const tx=new MemoryTransaction(),active=await setup(tx);const accepted=await applyIntegrationEnvelope(tx,active,envelope(),'key_1',NOW),lead=await tx.get('lead',accepted.effect_id!);await tx.save(lead,{...lead.data,status:'QUALIFIED',facts:{quantityMilli:9000,measurementSource:'VERIFIED'}});const quarantined=await applyIntegrationEnvelope(tx,active,{...envelope('updated'),occurred_at:'2026-10-09T10:01:00.000Z'},'key_1',NOW),preview=await command(tx,'integration_quarantine.preview',{id:quarantined.quarantine_id,action:'RETRY',reason:'Human review cannot replace verified company facts'});const decision=await command(tx,'integration_quarantine.resolve',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version});expect(decision).toMatchObject({status:'UNRESOLVED',businessEffects:0,reason:'INTERNAL_RECORD_CHANGED'});expect((await tx.get('integration_quarantine',preview.id)).data.status).toBe('OPEN');expect((await tx.get('lead',lead.id)).data.facts.measurementSource).toBe('VERIFIED');expect(await tx.list('integration_decision')).toHaveLength(1);});
 it('cannot retry a conflict over an originally applied event; discard is an explicit separate decision',async()=>{const tx=new MemoryTransaction(),active=await setup(tx);await applyIntegrationEnvelope(tx,active,envelope(),'key_1',NOW);const quarantined=await applyIntegrationEnvelope(tx,active,{...envelope(),payload:{...envelope().payload,language:'UK'}},'key_1',NOW);let preview=await command(tx,'integration_quarantine.preview',{id:quarantined.quarantine_id,action:'RETRY',reason:'Inspect conflicting replay without replacing original'});expect(await command(tx,'integration_quarantine.resolve',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version})).toMatchObject({status:'UNRESOLVED',reason:'ORIGINAL_EVENT_ALREADY_APPLIED'});preview=await command(tx,'integration_quarantine.preview',{id:quarantined.quarantine_id,action:'DISCARD',reason:'Company reviewed conflicting duplicate and discarded it'});expect(await command(tx,'integration_quarantine.resolve',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version})).toMatchObject({status:'DISCARDED',businessEffects:0});expect((await tx.list('lead'))[0]!.data.language).toBe('DE');expect(await tx.list('integration_decision')).toHaveLength(2);});
 it('binds review to current target/config versions and a ten-minute single-use preview',async()=>{const tx=new MemoryTransaction(),active=await setup(tx),quarantined=await applyIntegrationEnvelope(tx,active,envelope('missing','service_2'),'key_1',NOW),preview=await command(tx,'integration_quarantine.preview',{id:quarantined.quarantine_id,action:'RETRY',reason:'Review current mapping version'});await expect(command(tx,'integration_quarantine.resolve',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version},'2026-10-09T10:10:00.000Z')).rejects.toMatchObject({code:'NEEDS_REAUTH'});await tx.save(active,{...active.data,status:'PAUSED'});await expect(command(tx,'integration_quarantine.resolve',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version})).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(await tx.list('integration_decision')).toHaveLength(0);});
});

describe('minimized outbound preview/approval and guarded public HTTPS adapter',()=>{
 it.each(['http://8.8.8.8/x','https://127.1/x','https://[::1]/x','https://user:pass@public.example.com/x','https://public.example.com:444/x','https://public.example.com/x?token=secret','https://public.example.com/#redirect','https://metadata.google.internal/x'])('rejects unsafe endpoint %s',url=>{expect(()=>validateIntegrationWebhookUrl(url)).toThrow('VALIDATION_ERROR');});
 it.each(['0.1.2.3','10.1.2.3','100.64.0.1','127.0.0.1','169.254.169.254','172.16.0.1','192.168.0.1','192.0.2.1','192.88.99.1','198.18.0.1','198.51.100.1','203.0.113.1','224.0.0.1','::ffff:127.0.0.1','2001:db8::1','2001:0db8:0:0:0:0:0:1','2002:7f00:1::1','3ffe::1','fc00::1','fe80::1'])('rejects private/reserved/alias address %s',address=>{expect(publicIntegrationAddress(address)).toBe(false);});
 it('sends only minimal approved payload with exact raw-byte HMAC and pinned public DNS address',async()=>{const tx=new MemoryTransaction(),{preview}=await outbound(tx),delivery=await tx.get('integration_outbound',preview.id);const transport=vi.fn(async request=>{expect(request.address).toEqual({address:'8.8.8.8',family:4});expect(request.url.href).toBe(ENDPOINT);expect(verifyIntegrationEventSignature(request.body,request.headers['x-knaba-timestamp'],request.headers['x-knaba-signature'],credential.secret,NOW_MS)).toBe(true);expect(JSON.parse(request.body.toString()).payload).toEqual({id:delivery.data.leadId,status:'NEW',review_state:'NONE',language:'DE'});expect(request.body.toString()).not.toContain('private@example.test');return {status:202,receiptId:'synthetic_receipt'};});expect(await adapter(transport).send('company',SOURCE,'key_1',ENDPOINT,delivery.data.envelope)).toMatchObject({status:'API_ACCEPTED',providerReceiptId:'synthetic_receipt'});expect(transport).toHaveBeenCalledTimes(1);});
 it('blocks mixed public/private DNS answers and credential company mismatch before transport',async()=>{const transport=vi.fn(async()=>({status:200}));expect(await adapter(transport,{resolve:async()=>[{address:'8.8.8.8',family:4},{address:'127.0.0.1',family:4}]}).send('company',SOURCE,'key_1',ENDPOINT,{})).toMatchObject({status:'FAILED',error:'OUTBOUND_PREFLIGHT_REJECTED'});expect(await adapter(transport).send('other_company',SOURCE,'key_1',ENDPOINT,{})).toMatchObject({status:'FAILED'});expect(transport).not.toHaveBeenCalled();});
 it('disabled live gate and failed exact lease preflight perform no external request',async()=>{const transport=vi.fn(async()=>({status:200}));expect(await adapter(transport,{liveSendAllowed:false}).send('company',SOURCE,'key_1',ENDPOINT,{})).toEqual({status:'FAILED',error:'PROVIDER_DISABLED'});expect(await adapter(transport).send('company',SOURCE,'key_1',ENDPOINT,{},async()=>{throw new DomainError('WORKER_LEASE_LOST');})).toMatchObject({status:'FAILED',error:'OUTBOUND_PREFLIGHT_REJECTED'});expect(transport).not.toHaveBeenCalled();});
 it('key expiry during DNS lookup is rechecked before signing or transport',async()=>{let clock=NOW_MS;const transport=vi.fn(async()=>({status:200})),rotating=new IntegrationWebhookAdapter([{...credential,notAfter:new Date(NOW_MS+1000).toISOString()}],{liveSendAllowed:true,now:()=>clock,resolve:async()=>{clock=NOW_MS+2000;return [{address:'8.8.8.8',family:4}];},transport});expect(await rotating.send('company',SOURCE,'key_1',ENDPOINT,{})).toMatchObject({status:'FAILED',error:'OUTBOUND_PREFLIGHT_REJECTED'});expect(transport).not.toHaveBeenCalled();});
 it.each([301,400,401,403,409,422])('does not follow redirects or retry a definitive HTTP %s rejection',async status=>{const transport=vi.fn(async()=>({status}));expect(await adapter(transport).send('company',SOURCE,'key_1',ENDPOINT,{})).toMatchObject({status:'FAILED',responseStatus:status});expect(transport).toHaveBeenCalledTimes(1);});
 it.each([429,500,503])('retains ambiguous HTTP %s as UNKNOWN without a blind retry',async status=>{const transport=vi.fn(async()=>({status}));expect(await adapter(transport).send('company',SOURCE,'key_1',ENDPOINT,{})).toMatchObject({status:'UNKNOWN'});expect(transport).toHaveBeenCalledTimes(1);});
 it('timeout/network error after invoking transport stays UNKNOWN and is never resent',async()=>{const transport=vi.fn(async()=>{throw new Error('Ambiguous synthetic timeout after provider accepted bytes');});expect(await adapter(transport).send('company',SOURCE,'key_1',ENDPOINT,{})).toMatchObject({status:'UNKNOWN',error:'PROVIDER_OUTCOME_UNKNOWN'});expect(transport).toHaveBeenCalledTimes(1);});
 it('changed business source invalidates outbound confirmation; duplicate enqueue has no second outbox effect',async()=>{const tx=new MemoryTransaction(),active=await setup(tx),accepted=await applyIntegrationEnvelope(tx,active,envelope(),'key_1',NOW);const preview=await command(tx,'integration_outbound.preview',{config_id:active.id,external_id:'external_1'}),lead=await tx.get('lead',accepted.effect_id!);await tx.save(lead,{...lead.data,status:'QUALIFIED'});await expect(command(tx,'integration_outbound.enqueue',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version})).rejects.toMatchObject({code:'VERSION_CONFLICT'});const fresh=await command(tx,'integration_outbound.preview',{config_id:active.id,external_id:'external_1'});await command(tx,'integration_outbound.enqueue',{id:fresh.id,command_hash:fresh.command_hash,expected_version:fresh.expected_version});await expect(command(tx,'integration_outbound.enqueue',{id:fresh.id,command_hash:fresh.command_hash,expected_version:fresh.expected_version})).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(tx.events.filter(item=>item.type==='integration.outbound_requested')).toHaveLength(1);});
 it.each([
  ['revoked',{active:false}],['expired',{expiresAt:NOW}],['unreviewed',{approvalType:'UNVERIFIED'}],['wrong subject',{subject:'PAYROLL'}],
  ['foreign target',{scope:{integrationOutbound:{sources:[SOURCE],endpoints:['https://other.example.com/events'],allowedFields:['id','status','review_state','language'],allowedEventTypes:['lead.status']}}}],
  ['unapproved fields',{scope:{integrationOutbound:{sources:[SOURCE],endpoints:[ENDPOINT],allowedFields:['id','status'],allowedEventTypes:['lead.status']}}}]
 ] as const)('blocks %s legal approval before preview/enqueue',async(_label,changes)=>{const tx=new MemoryTransaction(),active=await setup(tx);await applyIntegrationEnvelope(tx,active,envelope(),'key_1',NOW);const approval=await tx.get('legal_approval','synthetic-privacy-approval');await tx.save(approval,{...approval.data,...changes});await expect(command(tx,'integration_outbound.preview',{config_id:active.id,external_id:'external_1'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});expect(await tx.list('integration_outbound')).toHaveLength(0);});
 it('checks current approval expiry at enqueue rather than the old preview timestamp',async()=>{const tx=new MemoryTransaction(),active=await setup(tx);await applyIntegrationEnvelope(tx,active,envelope(),'key_1',NOW);const approval=await tx.get('legal_approval','synthetic-privacy-approval');await tx.save(approval,{...approval.data,expiresAt:'2026-10-09T10:00:05.000Z'});const preview=await command(tx,'integration_outbound.preview',{config_id:active.id,external_id:'external_1'});await expect(command(tx,'integration_outbound.enqueue',{id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version},'2026-10-09T10:00:06.000Z')).rejects.toMatchObject({code:'NEEDS_APPROVAL'});expect(tx.events.filter(item=>item.type==='integration.outbound_requested')).toHaveLength(0);});
});

describe('outbound worker exact lease, authorization and crash recovery with explicit transaction double',()=>{
 async function fixture(){const tx=new MemoryTransaction(),setup=await outbound(tx);tx.job={id:'job_1',company_id:'company',type:'integration.outbound_requested',data:{deliveryId:setup.preview.id},lease_token:'private-lease-capability'};return {tx,job:tx.job,db:dbFixture(tx),...setup};}
 it('requires an exact current lease and durably records provider outcome once',async()=>{const {tx,job,db,preview}=await fixture(),transport=vi.fn(async()=>({status:202}));expect(await processIntegrationOutbound(db,host as any,job,adapter(transport),()=>new Date(NOW))).toMatchObject({status:'API_ACCEPTED'});const delivery=await tx.get('integration_outbound',preview.id);expect(JSON.stringify(delivery.data)).not.toContain(job.lease_token);expect(delivery.data.status).toBe('API_ACCEPTED');await processIntegrationOutbound(db,host as any,job,adapter(transport),()=>new Date(NOW));expect(transport).toHaveBeenCalledTimes(1);});
 it('a duplicate call on the same still-current claim does not erase an in-flight result',async()=>{const {tx,job,db,preview}=await fixture();let release!:(value:{status:number})=>void,started!:()=>void;const began=new Promise<void>(resolve=>{started=resolve;}),transport=vi.fn(async()=>{started();return new Promise<{status:number}>(resolve=>{release=resolve;});});const sender=adapter(transport),first=processIntegrationOutbound(db,host as any,job,sender,()=>new Date(NOW));await began;expect(await processIntegrationOutbound(db,host as any,job,sender,()=>new Date(NOW))).toEqual({status:'NO_SEND'});expect((await tx.get('integration_outbound',preview.id)).data.status).toBe('SENDING');release({status:202});expect(await first).toMatchObject({status:'API_ACCEPTED'});expect(transport).toHaveBeenCalledTimes(1);});
 it('stale lease never reaches transport',async()=>{const {tx,job,db}=await fixture(),transport=vi.fn(async()=>({status:202}));tx.held=false;await expect(processIntegrationOutbound(db,host as any,job,adapter(transport),()=>new Date(NOW))).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(transport).not.toHaveBeenCalled();});
 it('revoked approver or changed source cancels before send',async()=>{const {tx,job,db,preview}=await fixture(),transport=vi.fn(async()=>({status:202})),owner=await tx.get('user','owner');await tx.save(owner,{...owner.data,active:false});expect(await processIntegrationOutbound(db,host as any,job,adapter(transport),()=>new Date(NOW))).toEqual({status:'NO_SEND'});expect((await tx.get('integration_outbound',preview.id)).data.status).toBe('CANCELLED');expect(transport).not.toHaveBeenCalled();});
 it('legal revocation during DNS preflight blocks transport despite an earlier valid claim',async()=>{const {tx,job,db,preview}=await fixture(),transport=vi.fn(async()=>({status:202}));const guarded=adapter(transport,{resolve:async()=>{const approval=await tx.get('legal_approval','synthetic-privacy-approval');await tx.save(approval,{...approval.data,active:false});return [{address:'8.8.8.8',family:4}];}});expect(await processIntegrationOutbound(db,host as any,job,guarded,()=>new Date(NOW))).toMatchObject({status:'FAILED',error:'OUTBOUND_PREFLIGHT_REJECTED'});expect(transport).not.toHaveBeenCalled();expect((await tx.get('integration_outbound',preview.id)).data.status).toBe('FAILED');});
 it('crashed SENDING state becomes UNKNOWN; an ambiguous response has no retry',async()=>{const {tx,job,db,preview}=await fixture(),transport=vi.fn(async()=>{throw new Error('Synthetic timeout');});expect(await processIntegrationOutbound(db,host as any,job,adapter(transport),()=>new Date(NOW))).toMatchObject({status:'UNKNOWN'});await processIntegrationOutbound(db,host as any,job,adapter(transport),()=>new Date(NOW));expect(transport).toHaveBeenCalledTimes(1);const row=await tx.get('integration_outbound',preview.id);await tx.save(row,{...row.data,status:'SENDING'});job.lease_token='recovered-distinct-private-lease';await processIntegrationOutbound(db,host as any,job,adapter(transport),()=>new Date(NOW));expect((await tx.get('integration_outbound',row.id)).data.status).toBe('UNKNOWN');expect(transport).toHaveBeenCalledTimes(1);});
 it('explicit UNKNOWN reconciliation records evidence and requires a fresh preview before retry',async()=>{const {tx,job,db,preview}=await fixture();await processIntegrationOutbound(db,host as any,job,adapter(async()=>{throw new Error('Synthetic timeout');}),()=>new Date(NOW));const result=await command(tx,'integration_outbound.reconcile',{id:preview.id,status:'CONFIRMED_NOT_APPLIED',evidence_reference:'Synthetic operator provider-side reconciliation record',reason:'Operator verified event did not apply'});expect(result).toMatchObject({status:'FAILED'});expect(tx.events.filter(item=>item.type==='integration.outbound_requested')).toHaveLength(1);expect(await tx.list('integration_decision')).toHaveLength(1);const fresh=await command(tx,'integration_outbound.preview',{config_id:(await tx.get('integration_outbound',preview.id)).data.configId,external_id:'external_1'});expect(fresh).toMatchObject({status:'PREVIEW',providerInvoked:false});});
});

const postgres=process.env.DATABASE_URL?describe:describe.skip;
postgres('real PostgreSQL outbound fencing and quarantine decision idempotency',()=>{
 let db:Database,engine:Engine;const company=`outbound-qa-${randomUUID()}`;
 beforeAll(async()=>{db=new Database();await db.migrate();engine=new Engine(db,'TEST');});afterAll(async()=>{await db?.close();});
 async function fixture(){const scoped=company+'-'+randomUUID();const result=await db.transaction(scoped,'QA_FIXTURE',tx=>outbound(tx));const jobs=await leaseOutbox(db,100,120000,scoped);const job=jobs.find(row=>row.type==='integration.outbound_requested')!;expect(job).toBeTruthy();const transport=vi.fn(async()=>({status:202}));const realAdapter=new IntegrationWebhookAdapter([{...credential,companyId:scoped}],{liveSendAllowed:true,now:()=>NOW_MS,resolve:async()=>[{address:'8.8.8.8',family:4}],transport});return {scoped,result,job,transport,realAdapter};}
 it('actual SQL lease token gates one transport invocation and atomic final audit/outbox',async()=>{const {scoped,result,job,transport,realAdapter}=await fixture();await processIntegrationOutbound(db,engine,job,realAdapter,()=>new Date(NOW));await processIntegrationOutbound(db,engine,job,realAdapter,()=>new Date(NOW));expect(transport).toHaveBeenCalledTimes(1);const row=await db.transaction(scoped,'QA_CHECK',tx=>tx.get('integration_outbound',result.preview.id));expect(row.data.status).toBe('API_ACCEPTED');expect(JSON.stringify(row.data)).not.toContain(job.lease_token);expect((await db.query("SELECT count(*)::int AS count FROM outbox WHERE company_id=$1 AND type='integration.outbound_finished' AND data->>'deliveryId'=$2",[scoped,row.id])).rows[0].count).toBe(1);});
 it('actual expired SQL lease prevents network effects and retains pending delivery',async()=>{const {scoped,result,job,transport,realAdapter}=await fixture();await db.query("UPDATE outbox SET leased_until=clock_timestamp()-interval '1 second' WHERE id=$1",[job.id]);await expect(processIntegrationOutbound(db,engine,job,realAdapter,()=>new Date(NOW))).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(transport).not.toHaveBeenCalled();expect((await db.transaction(scoped,'QA_CHECK',tx=>tx.get('integration_outbound',result.preview.id))).data.status).toBe('PENDING');});
 it('concurrent duplicate invocation with the real same lease keeps one in-flight provider effect',async()=>{const {scoped,result,job,transport,realAdapter}=await fixture();let release!:(value:{status:number})=>void,started!:()=>void;const began=new Promise<void>(resolve=>{started=resolve;});transport.mockImplementation(async()=>{started();return new Promise<{status:number}>(resolve=>{release=resolve;});});const first=processIntegrationOutbound(db,engine,job,realAdapter,()=>new Date(NOW));await began;expect(await processIntegrationOutbound(db,engine,job,realAdapter,()=>new Date(NOW))).toEqual({status:'NO_SEND'});release({status:202});expect(await first).toMatchObject({status:'API_ACCEPTED'});expect(transport).toHaveBeenCalledTimes(1);expect((await db.transaction(scoped,'QA_CHECK',tx=>tx.get('integration_outbound',result.preview.id))).data.status).toBe('API_ACCEPTED');});
 it('real SQL SENDING recovery preserves UNKNOWN without repeating the provider request',async()=>{const {scoped,result,job,transport,realAdapter}=await fixture();await db.transaction(scoped,'QA_FIXTURE',async tx=>{const row=await tx.get('integration_outbound',result.preview.id);await tx.save(row,{...row.data,status:'SENDING'});});await processIntegrationOutbound(db,engine,job,realAdapter,()=>new Date(NOW));expect(transport).not.toHaveBeenCalled();expect((await db.transaction(scoped,'QA_CHECK',tx=>tx.get('integration_outbound',result.preview.id))).data.status).toBe('UNKNOWN');});
 it('repeated same Engine discard command creates one append-only decision and one audit effect',async()=>{const scoped=company+'-'+randomUUID();const quarantine=await db.transaction(scoped,'QA_FIXTURE',async tx=>{const active=await setup(tx);return applyIntegrationEnvelope(tx,active,envelope('bad','service_2'),'key_1',NOW);});const current=await engine.getActor('owner',scoped),preview=await engine.execute(current,'integration_quarantine.preview',{input:{id:quarantine.quarantine_id,action:'DISCARD',reason:'Synthetic company review rejected invalid field mapping'},idempotency_key:randomUUID()});const input={id:preview.id,command_hash:preview.command_hash,expected_version:preview.expected_version},idempotency_key=randomUUID();const first=await engine.execute(current,'integration_quarantine.resolve',{input,idempotency_key}),second=await engine.execute(current,'integration_quarantine.resolve',{input,idempotency_key});expect(second.decisionId).toBe(first.decisionId);expect((await db.query("SELECT count(*)::int AS count FROM aggregates WHERE company_id=$1 AND kind='integration_decision' AND data->>'quarantineId'=$2",[scoped,preview.id])).rows[0].count).toBe(1);});
});
