import {describe,it,expect,vi} from 'vitest';
import type {Request} from 'express';
import sharp from 'sharp';
import {ApiController} from '../apps/api/http.ts';
import {mediaUploadSchema} from '../apps/api/media-upload.ts';
import {v4OpenApiPaths} from '../apps/api/v4-rest.ts';
import {zodToJsonSchema} from 'zod-to-json-schema';
import {PostgresPrivateBlobStore,type PrivateBlobStore} from '../packages/storage/index.ts';
import {DomainError,type Actor,type Entity} from '../packages/domain/core.ts';
import type {DatabaseLike,EngineLike,SqlTransaction} from '../apps/api/auth.ts';

// Explicit serialized, rollback-capable SQL transport fixture; this is CPU evidence,
// not PostgreSQL execution. Actual SQL tests are in the adjacent integration file.
function fixture(company='synthetic-upload-company',user='synthetic-uploader'){
 let state={uploads:new Map<string,Entity>(),blobs:new Map<string,any>(),receipts:new Map<string,any>(),events:[] as any[],audit:[] as any[]};
 let mutex=Promise.resolve(),transactions=0,receiptReads=0;let failReceipt=false;
 const actor:Actor={companyId:company,userId:user,roles:['EMPLOYEE'],permissions:['media.upload'],siteIds:['synthetic-site'],customerIds:[],warehouseIds:[]};
 let current={...actor},beforeTransaction:((number:number)=>void)|undefined;
 const database:DatabaseLike={query:vi.fn(async()=>{throw new Error('Fixture forbids out-of-transaction SQL');}),transaction:async<T>(companyId:string,userId:string,fn:(tx:SqlTransaction)=>Promise<T>)=>{
  const prior=mutex;let release!:()=>void;mutex=new Promise<void>(resolve=>{release=resolve;});await prior;
  try{beforeTransaction?.(++transactions);const draft=structuredClone(state),compound=(kind:string,id:string)=>JSON.stringify([companyId,kind,id]);
   const tx:SqlTransaction={get:async(kind,id)=>{const found=draft.uploads.get(compound(kind,id));if(!found)throw new DomainError('NOT_FOUND_SAFE');return found as any;},list:async()=>[],save:async()=>{throw new Error('Unexpected save');},add:async(kind,data,id)=>{if(draft.uploads.has(compound(kind,id!)))throw new DomainError('VERSION_CONFLICT');const entity={id:id!,kind,companyId,version:1,data,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};draft.uploads.set(compound(kind,id!),entity);return entity as any;},event:async(type,data)=>{draft.events.push({companyId,type,data});},query:async(sql,params=[])=>{
    if(sql.startsWith('SELECT command,input_hash,result,authorization_hash')){receiptReads++;const row=draft.receipts.get(JSON.stringify(params));return {rows:row?[row]:[]};}
    if(sql.startsWith('INSERT INTO command_receipts')){if(failReceipt)throw new Error('Synthetic receipt write failure');const key=JSON.stringify(params.slice(0,3));if(draft.receipts.has(key))throw new Error('Duplicate SQL receipt');draft.receipts.set(key,{command:params[3],input_hash:params[4],result:JSON.parse(params[5]),authorization_hash:params[6]});return {rows:[]};}
    if(sql.startsWith('INSERT INTO audit_log')){draft.audit.push({companyId:params[0],actorId:params[1],action:params[2],detail:JSON.parse(params[3])});return {rows:[]};}
    if(sql.startsWith('INSERT INTO media_blobs')){if(draft.blobs.has(params[0]))return {rows:[]};draft.blobs.set(params[0],{id:params[0],company_id:params[1],owner_id:params[2],bytes:Buffer.from(params[3]),mime_type:params[4],sha256:params[5]});return {rows:[{id:params[0]}]};}
    if(sql.startsWith('SELECT company_id,owner_id,bytes')){const row=draft.blobs.get(params[0]);return {rows:row?[row]:[]};}
    if(sql.startsWith('SELECT id,owner_id,sha256,mime_type,octet_length(bytes)'))return {rows:[...draft.blobs.values()].filter(blob=>blob.company_id===params[0]&&params[1].includes(blob.id)).map(blob=>({...blob,byte_size:blob.bytes.length}))};
    throw new Error('Unhandled explicit SQL fixture: '+sql);
   }};
   const result=await fn(tx);state=draft;return result;
  }finally{release();}
 }};
 const engine={actorIn:vi.fn(async()=>current),scope:vi.fn((fresh:Actor,permission:string)=>{expect(permission).toBe('media.upload');return fresh;}),registry:{},execute:vi.fn(),readEntities:vi.fn(),getActor:vi.fn(async()=>current)} as EngineLike;
 const storage=new PostgresPrivateBlobStore(database),put=vi.spyOn(storage,'put');
 const controller=(store:PrivateBlobStore=storage,acting=actor)=>{const c=new ApiController({db:database,engine,companyId:acting.companyId,appMode:'TEST',buildSha:'cpu-fixture-uncommitted',storage:store});(c as any).actor=async()=>({actor:acting});return c;};
 return {actor,database,engine,storage,put,controller,state:()=>state,revoke:()=>{current={...current,permissions:[]};},rescope:()=>{current={...current,siteIds:[]};},current:(value:Actor)=>{current=value;},before:(fn:(number:number)=>void)=>{beforeTransaction=fn;},fail:(value:boolean)=>{failReceipt=value;},reads:()=>receiptReads};
}
const request=(...args:[unknown?,string?])=>({originalUrl:args[1]??'/api/v1/media/uploads',get:(name:string)=>name.toLowerCase()==='idempotency-key'?(args.length?args[0]:'synthetic-upload-key'):undefined}) as unknown as Request;
async function image(color='red'){return sharp({create:{width:2,height:2,channels:3,background:color}}).png().toBuffer();}
const body=(bytes:Buffer,extra={})=>({base64:bytes.toString('base64'),mimeType:'image/png',fileName:'synthetic-image.png',redactionConfirmed:false,...extra});
describe('Named media upload durable idempotency through actual controller and PG-store SQL fixture',()=>{
 it('requires a printable8..200-character header on named route before SQL/storage effects',async()=>{const h=fixture(),input=body(await image());for(const key of [undefined,'short','synthetic-key\n',['synthetic-key','second-key'],'k'.repeat(201)])await expect(h.controller().upload(request(key),input)).rejects.toThrow();expect(h.reads()).toBe(0);expect(h.put).not.toHaveBeenCalled();expect(h.state().receipts.size).toBe(0);});
 it('same original SHA/MIME/name/redaction returns the same receipt and two retained private blob IDs without new effects',async()=>{
  const h=fixture(),bytes=await image(),input=body(bytes),first=await h.controller().upload(request(),input),second=await h.controller().upload(request(),input);
  expect(second).toEqual(first);expect(h.put).toHaveBeenCalledTimes(2);expect(h.state().uploads.size).toBe(1);expect(h.state().blobs.size).toBe(2);expect(h.state().receipts.size).toBe(1);expect(h.state().events).toHaveLength(1);expect(h.state().audit).toHaveLength(1);
  const upload=[...h.state().uploads.values()][0]!;expect(Buffer.from(h.state().blobs.get(upload.data.blobKey).bytes)).toEqual(bytes);expect((await sharp(Buffer.from(h.state().blobs.get(upload.data.clientBlobKey).bytes)).metadata()).format).toBe('jpeg');expect(upload.data).toMatchObject({uploadedBy:h.actor.userId,originalPreserved:true,metadataStripped:true,scanState:'CLEAN'});
 });
 for(const field of ['original','mimeType','fileName','redactionConfirmed'])it(`same key with changed ${field} yields IDEMPOTENCY_CONFLICT before new blob writes`,async()=>{
  const h=fixture(),input=body(await image());await h.controller().upload(request(),input);const changed=field==='original'?body(await image('blue')):field==='mimeType'?{...input,mimeType:'image/jpeg'}:field==='fileName'?{...input,fileName:'changed.png'}:{...input,redactionConfirmed:true};await expect(h.controller().upload(request(),changed)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});expect(h.put).toHaveBeenCalledTimes(2);expect(h.state().receipts.size).toBe(1);expect(h.state().events).toHaveLength(1);
 });
 it('revoked fresh permission denies stale authenticated actor before even looking up a cached receipt',async()=>{const h=fixture(),input=body(await image());await h.controller().upload(request(),input);const reads=h.reads();h.revoke();await expect(h.controller().upload(request(),input)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(h.reads()).toBe(reads);expect(h.put).toHaveBeenCalledTimes(2);});
 it('changed current scoped authority denies cached receipt instead of treating stale scopes as valid',async()=>{const h=fixture(),input=body(await image());await h.controller().upload(request(),input);h.rescope();await expect(h.controller().upload(request(),input)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(h.put).toHaveBeenCalledTimes(2);});
 it('permission revoked between initial receipt probe and prepared commit leaves no effects',async()=>{const h=fixture();h.before(number=>{if(number===2)h.revoke();});await expect(h.controller().upload(request(),body(await image()))).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(h.put).not.toHaveBeenCalled();expect(h.state().uploads.size+h.state().blobs.size+h.state().receipts.size).toBe(0);});
 it('concurrent identical uploads commit one metadata/outbox/audit/receipt and the same two IDs',async()=>{const h=fixture(),input=body(await image()),[first,second]=await Promise.all([h.controller().upload(request(),input),h.controller().upload(request(),input)]);expect(first).toEqual(second);expect(h.put).toHaveBeenCalledTimes(2);expect(h.state().uploads.size).toBe(1);expect(h.state().receipts.size).toBe(1);expect(h.state().events).toHaveLength(1);expect(h.state().audit).toHaveLength(1);});
 it('receipt failure rolls back both PG blobs, metadata, outbox and audit; later retry succeeds once',async()=>{const h=fixture(),input=body(await image());h.fail(true);await expect(h.controller().upload(request(),input)).rejects.toThrow('Synthetic receipt write failure');expect(h.state().uploads.size+h.state().blobs.size+h.state().receipts.size).toBe(0);expect(h.state().events).toEqual([]);expect(h.state().audit).toEqual([]);h.fail(false);const result=await h.controller().upload(request(),input);expect(result.uploadId).toBeTruthy();expect(h.state().blobs.size).toBe(2);expect(h.state().receipts.size).toBe(1);});
 for(const kind of ['metadata','blob'])it(`erased ${kind} cannot be recreated or replayed from a retained receipt`,async()=>{const h=fixture(),input=body(await image()),first=await h.controller().upload(request(),input);if(kind==='metadata')h.state().uploads.clear();else h.state().blobs.delete(first.uploadId);await expect(h.controller().upload(request(),input)).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});expect(h.put).toHaveBeenCalledTimes(2);expect(h.state().events).toHaveLength(1);});
 it('same actor/key is scoped to company and same company/key is scoped to actor',async()=>{
  const h=fixture(),input=body(await image()),first=await h.controller().upload(request(),input),other={...h.actor,userId:'second-synthetic-user'};h.current(other);const second=await h.controller(undefined,other).upload(request(),input);const foreign={...h.actor,companyId:'second-synthetic-company'};h.current(foreign);const third=await h.controller(undefined,foreign).upload(request(),input);expect(new Set([first.uploadId,second.uploadId,third.uploadId]).size).toBe(3);expect(h.state().receipts.size).toBe(3);expect(h.state().uploads.size).toBe(3);expect(h.state().blobs.size).toBe(6);
 });
 it('a receipt key already used by another command cannot be overwritten',async()=>{const h=fixture(),input=body(await image());h.state().receipts.set(JSON.stringify([h.actor.companyId,h.actor.userId,'synthetic-upload-key']),{command:'task.start',input_hash:'unrelated',authorization_hash:'unrelated',result:{private:'unrelated'}});await expect(h.controller().upload(request(),input)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});expect(h.put).not.toHaveBeenCalled();expect(h.state().receipts.size).toBe(1);});
 it('named S3 idempotency fails explicitly before any write while legacy unkeyed S3 compatibility remains',async()=>{const h=fixture(),put=vi.fn(async(input:any)=>({key:input.id,sha256:input.sha256,byteSize:input.bytes.length,mimeType:input.mimeType,provider:'S3' as const,created:true})),s3={provider:'S3',put,get:vi.fn(),delete:vi.fn(),probe:vi.fn()} as PrivateBlobStore,input=body(await image());await expect(h.controller(s3).upload(request(),input)).rejects.toMatchObject({code:'MISSING_CONFIGURATION',details:{reason:'ATOMIC_MEDIA_UPLOAD_REQUIRES_POSTGRES_BLOBS'}});expect(put).not.toHaveBeenCalled();await h.controller(s3).upload(request(undefined,'/api/v1/media/upload'),input);expect(put).toHaveBeenCalledTimes(2);expect(h.state().receipts.size).toBe(0);});
 it('legacy unkeyed upload keeps distinct uploads and default201 while an optional header enables durable reuse',async()=>{const h=fixture(),input=body(await image()),status=vi.fn(),first=await h.controller().upload(request(undefined,'/api/v1/media/upload'),input,{status} as any),second=await h.controller().upload(request(undefined,'/api/v1/media/upload'),input);expect(status).not.toHaveBeenCalled();expect(first.uploadId).not.toBe(second.uploadId);const keyed=await h.controller().upload(request('legacy-key-123','/api/v1/media/upload'),input);expect(await h.controller().upload(request('legacy-key-123','/api/v1/media/upload'),input)).toEqual(keyed);expect(h.state().uploads.size).toBe(3);expect(h.state().receipts.size).toBe(1);});
 it('accepts a maximum200-character key, selects named200 and exports actual upload schema plus required header',async()=>{const h=fixture(),input=body(await image()),key='k'.repeat(200),status=vi.fn();expect(await h.controller().upload(request(key),input,{status} as any)).toEqual(await h.controller().upload(request(key),input));expect(status).toHaveBeenCalledExactlyOnceWith(200);const route=v4OpenApiPaths({}, {mediaUpload:zodToJsonSchema(mediaUploadSchema,{$refStrategy:'none'})})['/api/v1/media/uploads'].post;expect(route.parameters).toEqual([{in:'header',name:'Idempotency-Key',required:true,schema:{type:'string',minLength:8,maxLength:200,pattern:'^[!-~]+$'}}]);expect(route.requestBody.content['application/json'].schema.additionalProperties).toBe(false);});
});
