import {describe,it,expect} from 'vitest';
import sharp from 'sharp';
import {createHash} from 'node:crypto';
import {preparePrivateMedia,ingestPrivateMedia} from '../packages/storage/media-ingest.ts';
import type {Actor,Entity} from '../packages/domain/core.ts';
const actor:Actor={companyId:'synthetic',userId:'worker',roles:['EMPLOYEE'],permissions:['media.upload'],siteIds:['site'],warehouseIds:[],customerIds:[]};
async function fixture(){const bytes=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer();return {bytes,mimeType:'image/png',fileName:'synthetic.png',sourceId:'wamid.synthetic',expectedSha256:createHash('sha256').update(bytes).digest('base64')};}
describe('Inbound private media quarantine and durable upload',()=>{
 it('checks provider checksum, decodes actual bytes and produces stripped private JPEG while preserving original',async()=>{const input=await fixture(),p=await preparePrivateMedia(input);expect(p.original).toEqual(input.bytes);expect(p.clientMimeType).toBe('image/jpeg');expect((await sharp(p.clean).metadata()).format).toBe('jpeg');expect(p.metadataStripped).toBe(true);});
 it('refuses checksum mismatch and declared MIME mismatch',async()=>{const i=await fixture();await expect(preparePrivateMedia({...i,expectedSha256:'00'.repeat(32)})).rejects.toMatchObject({code:'VALIDATION_ERROR',details:{reason:'PROVIDER_MEDIA_CHECKSUM_MISMATCH'}});await expect(preparePrivateMedia({...i,mimeType:'image/jpeg'})).rejects.toMatchObject({code:'VALIDATION_ERROR',details:{reason:'MIME_SIGNATURE_MISMATCH'}});});
 it('refuses invalid or unsupported bytes before private storage',async()=>{await expect(preparePrivateMedia({bytes:Buffer.from('malformed'),mimeType:'image/png',sourceId:'bad',fileName:'bad.png'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});const i=await fixture();await expect(preparePrivateMedia({...i,mimeType:'audio/ogg'})).rejects.toMatchObject({code:'VALIDATION_ERROR',details:{reason:'UNSUPPORTED_MEDIA'}});});
 it('retries the signed event as one private upload and refuses missing permission or changed payload',async()=>{const i=await fixture(),prepared=await preparePrivateMedia(i),rows:Entity[]=[],stored:any[]=[],events:any[]=[];const tx:any={query:async()=>({rows:[]}),list:async()=>rows,add:async(kind:string,data:any,id:string)=>{const row={kind,id,companyId:actor.companyId,data,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};rows.push(row);return row;},event:async(...e:any[])=>{events.push(e);}};const store:any={put:async(input:any)=>{stored.push(input);}};const first=await ingestPrivateMedia(tx,store,actor,i,prepared);expect(await ingestPrivateMedia(tx,store,actor,i,prepared)).toEqual(first);expect(rows).toHaveLength(1);expect(stored).toHaveLength(2);expect(events).toHaveLength(1);expect(first.data).toMatchObject({scanState:'CLEAN',redactionConfirmed:false,originalPreserved:true});expect('siteId' in first.data).toBe(false);await expect(ingestPrivateMedia(tx,store,{...actor,permissions:[]},i,prepared)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(ingestPrivateMedia(tx,store,actor,{...i,bytes:Buffer.from('changed')},prepared)).rejects.toMatchObject({code:'VALIDATION_ERROR'});});
});
