import {beforeAll,beforeEach,afterAll,describe,it,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
import type {Request} from 'express';
import {Database} from '../apps/api/database.ts';
import {Engine} from '../apps/api/engine.ts';
import {ApiController} from '../apps/api/http.ts';
import {AuthService,SESSION_COOKIE} from '../apps/api/auth.ts';
import {PostgresPrivateBlobStore} from '../packages/storage/index.ts';

// Genuine PostgreSQL/controller/Sharp/private-store/session/CSRF tests. No fixture SQL
// substitute and no live company data. Missing DATABASE_URL is NOT_RUN, never PASS.
const postgres=process.env.DATABASE_URL?describe:describe.skip;
postgres('V4 media upload atomic SQL receipts and current authorization',()=>{
 let db:Database,engine:Engine,company:string,controller:ApiController,storage:PostgresPrivateBlobStore,session:{token:string;csrfToken:string;expiresAt:string},bytes:Buffer;
 const user='synthetic-media-owner';
 beforeAll(async()=>{db=new Database();await db.migrate();engine=new Engine(db,'TEST');bytes=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer();});
 beforeEach(async()=>{company='qa-v4-upload-'+randomUUID();await db.transaction(company,'SYNTHETIC_MEDIA_UPLOAD_FIXTURE',async tx=>{await tx.add('company',{legalName:'Synthetic private media tenant',synthetic:true},company);await tx.add('user',{name:'Synthetic media owner',active:true,roles:[],permissions:['media.upload'],siteIds:['synthetic-site'],synthetic:true},user);});storage=new PostgresPrivateBlobStore(db);controller=new ApiController({db,engine,companyId:company,appMode:'TEST',publicOrigin:'https://synthetic-upload.test',storage,buildSha:'uncommitted-media-upload-candidate'});session=await new AuthService(db,engine,{companyId:company,appMode:'TEST'}).createSession(user);});
 afterAll(async()=>{await db?.close();});
 const request=(key='synthetic-upload-key',validCsrf=true)=>({originalUrl:'/api/v1/media/uploads',protocol:'https',get:(name:string)=>({cookie:`${SESSION_COOKIE}=${session.token}`,origin:'https://synthetic-upload.test','x-csrf-token':validCsrf?session.csrfToken:'invalid','idempotency-key':key} as Record<string,string>)[name.toLowerCase()]}) as unknown as Request;
 const input=(extra={})=>({base64:bytes.toString('base64'),mimeType:'image/png',fileName:'synthetic-upload.png',redactionConfirmed:false,...extra});
 async function effects(){const counts=(await db.query('SELECT (SELECT count(*)::int FROM aggregates WHERE company_id=$1 AND kind=$2) AS uploads,(SELECT count(*)::int FROM media_blobs WHERE company_id=$1) AS blobs,(SELECT count(*)::int FROM command_receipts WHERE company_id=$1) AS receipts,(SELECT count(*)::int FROM outbox WHERE company_id=$1 AND type=$3) AS events,(SELECT count(*)::int FROM audit_log WHERE company_id=$1 AND action=$4) AS command_audit',[company,'media_upload','media.uploaded','COMMAND:media.upload'])).rows[0];return counts;}
 it('real authenticated controller exact replay commits one receipt/upload/event/audit and preserves original plus sanitized bytes',async()=>{const first=await controller.upload(request(),input()),second=await controller.upload(request(),input());expect(second).toEqual(first);expect(await effects()).toEqual({uploads:1,blobs:2,receipts:1,events:1,command_audit:1});const row=await db.transaction(company,user,tx=>tx.get('media_upload',first.uploadId));expect((await storage.get(company,row.data.blobKey)).bytes).toEqual(bytes);expect((await sharp((await storage.get(company,row.data.clientBlobKey)).bytes).metadata()).format).toBe('jpeg');});
 for(const field of ['original','mimeType','fileName','redactionConfirmed'])it(`actual SQL same-key changed ${field} conflicts without extra rows`,async()=>{await controller.upload(request(),input());const changed=field==='original'?input({base64:(await sharp({create:{width:2,height:2,channels:3,background:'blue'}}).png().toBuffer()).toString('base64')}):field==='mimeType'?input({mimeType:'image/jpeg'}):field==='fileName'?input({fileName:'different.png'}):input({redactionConfirmed:true});await expect(controller.upload(request(),changed)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});expect(await effects()).toEqual({uploads:1,blobs:2,receipts:1,events:1,command_audit:1});});
 it('concurrent actual SQL uploads with one key converge to one result and two blobs',async()=>{const [first,second]=await Promise.all([controller.upload(request(),input()),controller.upload(request(),input())]);expect(second).toEqual(first);expect(await effects()).toEqual({uploads:1,blobs:2,receipts:1,events:1,command_audit:1});});
 it('same receipt is denied after actual permission revocation and after current scope change',async()=>{const original=await controller.upload(request(),input());await db.transaction(company,'SYNTHETIC_PERMISSION_CHANGE',async tx=>{const actor=await tx.get('user',user);await tx.save(actor,{...actor.data,siteIds:[]});});await expect(controller.upload(request(),input())).rejects.toMatchObject({code:'ACCESS_DENIED'});await db.transaction(company,'SYNTHETIC_PERMISSION_REVOCATION',async tx=>{const actor=await tx.get('user',user);await tx.save(actor,{...actor.data,permissions:[]});});await expect(controller.upload(request(),input())).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await effects()).toEqual({uploads:1,blobs:2,receipts:1,events:1,command_audit:1});expect(original.uploadId).toBeTruthy();});
 it('missing erased original blob fails replay and never recreates it',async()=>{const result=await controller.upload(request(),input());await storage.delete(company,result.uploadId);await expect(controller.upload(request(),input())).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});expect(await effects()).toEqual({uploads:1,blobs:1,receipts:1,events:1,command_audit:1});});
 it('failure after both blob writes rolls back blobs, aggregate revisions/audit, outbox and receipt',async()=>{const put=vi.spyOn(storage,'put'),original=storage.put.bind(storage);let calls=0;put.mockImplementation(async(value,tx)=>{const receipt=await original(value,tx);if(++calls===2)throw new Error('Synthetic error after sanitized SQL blob write');return receipt;});try{await expect(controller.upload(request(),input())).rejects.toThrow('Synthetic error after sanitized SQL blob write');}finally{put.mockRestore();}expect(await effects()).toEqual({uploads:0,blobs:0,receipts:0,events:0,command_audit:0});expect((await db.query('SELECT id FROM aggregate_revisions WHERE company_id=$1 AND kind=$2',[company,'media_upload'])).rows).toHaveLength(0);});
 it('actual receipt-stage failure rolls back already written private blobs, metadata, revision/audit and outbox together',async()=>{
  const original=db.transaction.bind(db),wrapped:typeof db.transaction=async(companyId,actorId,fn,timeout,readOnly)=>original(companyId,actorId,async tx=>{
   const query=tx.query.bind(tx);tx.query=async(statement,params=[])=>{if(statement.startsWith('INSERT INTO command_receipts')&&params[3]==='media.upload'){
    const observed=(await query('SELECT (SELECT count(*)::int FROM media_blobs WHERE company_id=$1) AS blobs,(SELECT count(*)::int FROM aggregates WHERE company_id=$1 AND kind=$2) AS uploads,(SELECT count(*)::int FROM outbox WHERE company_id=$1 AND type=$3) AS events',[company,'media_upload','media.uploaded'])).rows[0];expect(observed).toEqual({blobs:2,uploads:1,events:1});throw new Error('Synthetic SQL receipt-stage failure');
   }return query(statement,params);};return fn(tx);
  },timeout,readOnly);
  const mutation=vi.spyOn(db,'transaction').mockImplementation(wrapped);try{await expect(controller.upload(request(),input())).rejects.toThrow('Synthetic SQL receipt-stage failure');}finally{mutation.mockRestore();}
  expect(await effects()).toEqual({uploads:0,blobs:0,receipts:0,events:0,command_audit:0});expect((await db.query('SELECT id FROM aggregate_revisions WHERE company_id=$1 AND kind=$2',[company,'media_upload'])).rows).toHaveLength(0);expect((await db.query('SELECT id FROM audit_log WHERE company_id=$1 AND aggregate_kind=$2',[company,'media_upload'])).rows).toHaveLength(0);
 });
 it('actual mutation CSRF rejection precedes upload receipt and private storage effects',async()=>{await expect(controller.upload(request('synthetic-upload-key',false),input())).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await effects()).toEqual({uploads:0,blobs:0,receipts:0,events:0,command_audit:0});});
});
