import {afterAll,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Database} from '../apps/api/database.ts';
import {Engine} from '../apps/api/engine.ts';
import {WorkerRunner,leaseOutbox,type OutboxJob} from '../apps/worker/runner.ts';
import {WhatsAppCloudAdapter} from '../packages/integrations/whatsapp.ts';
import {cancelPendingAbsenceNotices} from '../packages/domain/notification-policy.ts';
import type {Actor,Data,Entity} from '../packages/domain/core.ts';

// Real PostgreSQL leases, domain commands, revisions, receipts and worker.
// Provider HTTP replies are explicit synthetic fixtures; no real Meta/GPS acceptance.
const postgres=process.env.DATABASE_URL?describe:describe.skip;
postgres('V4 notification policies: genuine PostgreSQL and leased workers',()=>{
 let db:Database,engine:Engine,worker:WorkerRunner,company:string,manager:Actor,employee:Actor,fetcher:ReturnType<typeof vi.fn>;
 const execute=(actor:Actor,name:string,input:Data)=>engine.execute(actor,name,{input,idempotency_key:randomUUID()});
 const rows=(kind:string)=>db.transaction(company,'SYNTHETIC_V4_NOTIFICATION_QA',tx=>tx.list(kind));
 const row=(kind:string,id:string)=>db.transaction(company,'SYNTHETIC_V4_NOTIFICATION_QA',tx=>tx.get(kind,id));
 const patch=(kind:string,id:string,data:Data)=>db.transaction(company,'SYNTHETIC_V4_NOTIFICATION_QA',async tx=>{const e=await tx.get(kind,id);return tx.save(e,{...e.data,...data});});
 async function take(type:string,notificationId?:string){
  const candidates=(await db.query("SELECT id,data FROM outbox WHERE company_id=$1 AND type=$2 AND status IN ('PENDING','RETRY_SCHEDULED') ORDER BY created_at,id",[company,type])).rows;expect(candidates.length).toBeGreaterThan(0);const selected=notificationId?candidates.find(r=>r.data.notification_id===notificationId):candidates[0];expect(selected).toBeDefined();
  // This advances only the synthetic fixture's scheduling, never claims that real minutes elapsed.
  await db.query("UPDATE outbox SET available_at=now()-interval '1 second',data=jsonb_set(data,'{not_before}',to_jsonb((now()-interval '1 second')::text)) WHERE company_id=$1 AND id=$2",[company,selected!.id]);
  const jobs=await leaseOutbox(db,100,120000,company),job=jobs.find(j=>j.id===selected!.id);expect(job).toBeDefined();return job!;
 }
 async function notice(){
  const channel=await execute(manager,'channel.create',{type:'SITE_INTERNAL',name:'Synthetic notification thread',site_id:'site',member_ids:['employee']});
  const message=await execute(manager,'message.send',{channel_id:channel.id,text:'Synthetic notification contract',language:'DE'});
  return execute(manager,'notifications.schedule',{recipient_id:'employee',event:'CHAT',category:'CHAT',channel:'WHATSAPP',message_id:message.id,scheduled_at:new Date().toISOString(),dedup_key:randomUUID()});
 }
 async function linked(){const n=await notice();await worker.process(await take('notification.scheduled'));expect((await row('notification',n.id)).data.status).toBe('AWAITING_DELIVERY');const delivery=(await rows('delivery')).find(d=>d.data.channel==='WHATSAPP')!;expect(delivery).toBeDefined();return {n,delivery};}
 async function routerReply(){return db.transaction(company,'SYNTHETIC_ROUTER_SOURCE_FIXTURE',async tx=>{const session=await tx.add('whatsapp_router_session',{user_id:'employee',sender:'49123456789',generation:1,language:'UK'});const response=await tx.add('whatsapp_router_response',{user_id:'employee',recipient_id:'employee',sender:'49123456789',session_id:session.id,session_generation:1,language:'UK',output:{kind:'TEXT',text:'Synthetic personal router response'},internal:true,required_permissions:['chat.read'],access_refs:[],status:'PENDING',expires_at:new Date(Date.now()+900000).toISOString()});await tx.event('whatsapp.router_response',{response_id:response.id});return response;});}
 async function fingerprint(){const result:Data={};for(const table of ['aggregates','aggregate_revisions','audit_log','outbox','command_receipts'])result[table]=(await db.query(`SELECT count(*)::int n,md5(coalesce(string_agg(to_jsonb(r)::text,E'\n' ORDER BY to_jsonb(r)::text),'')) hash FROM ${table} r WHERE company_id=$1`,[company])).rows[0];return result;}
 beforeAll(async()=>{db=new Database();await db.migrate();});
 beforeEach(async()=>{
  company='v4-notification-qa-'+randomUUID();engine=new Engine(db,'TEST');fetcher=vi.fn(async()=>new Response(JSON.stringify({messages:[{id:'synthetic-accepted-id'}]}),{status:200}));
  await db.transaction(company,'SYNTHETIC_V4_NOTIFICATION_QA',async tx=>{
   await tx.add('company',{operatingMode:'TEST',synthetic:true},company);
   await tx.add('site',{name:'Synthetic notification site',code:'V4-NOTICE',active:true,geoResponsibleUserId:'manager',managerIds:['manager']},'site');
   await tx.add('user',{active:true,roles:['OPERATIONS_MANAGER'],permissions:['notifications.manage'],siteIds:['site']},'manager');
   await tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['site']},'employee');
   await tx.add('notification_setting',{user_id:'employee',language:'UK',whatsapp_consent:true,opted_out:false,quiet_start:0,quiet_end:0,last_inbound_at:new Date().toISOString()},'employee-settings');
   await tx.add('notification_setting',{user_id:'manager',language:'DE',whatsapp_consent:false,opted_out:false,quiet_start:0,quiet_end:0},'manager-settings');
   await tx.add('contact_identity',{userId:'employee',type:'WHATSAPP',value:'49123456789',verified:true,active:true},'employee-identity');
  });
  manager=await engine.getActor('manager',company);employee=await engine.getActor('employee',company);
  const adapter=new WhatsAppCloudAdapter({accessToken:'SYNTHETIC_QA_ONLY',phoneNumberId:'123456',apiVersion:'v24.0',accountCapabilitiesVerified:true},fetcher as typeof fetch);
  worker=new WorkerRunner(db,engine,{companyId:company,appMode:'TEST',whatsapp:adapter,testRecipients:['49123456789']});await worker.initialize();
 });
 afterAll(async()=>{await db?.close();});

 it('one logical notification links one delivery; actual leased provider worker projects accepted status and restart never sends twice',async()=>{const {n,delivery}=await linked();const job=await take('delivery.requested');await worker.process(job);expect(fetcher).toHaveBeenCalledTimes(1);expect((await row('delivery',delivery.id)).data).toMatchObject({status:'API_ACCEPTED',attempts:1,provider_message_id:'synthetic-accepted-id'});expect((await row('notification',n.id)).data).toMatchObject({status:'SUCCEEDED',attempts:1,delivery_id:delivery.id});await db.transaction(company,'SYNTHETIC_RESTART_EVENT',tx=>tx.event('delivery.requested',{delivery_id:delivery.id}));const restarted=new WorkerRunner(db,engine,worker.options);await restarted.process(await take('delivery.requested'));expect(fetcher).toHaveBeenCalledTimes(1);expect((await rows('notification')).filter(e=>e.id===n.id)).toHaveLength(1);});
 it('explicit transient rejection schedules1/5/15minutes only, then one dead-letter decision without notification scheduler duplication',async()=>{fetcher.mockImplementation(async()=>new Response(JSON.stringify({error:{code:130429,message:'Synthetic rate limit'}}),{status:429}));const {n,delivery}=await linked();for(let attempt=1;attempt<=4;attempt++){if(attempt>1)await patch('delivery',delivery.id,{scheduled_at:new Date(Date.now()-1000).toISOString()});const start=Date.now();await worker.process(await take('delivery.requested'));const current=await row('delivery',delivery.id);expect(current.data.attempts).toBe(attempt);if(attempt<4){expect(current.data.status).toBe('RETRY_SCHEDULED');expect(Date.parse(current.data.scheduled_at)-start).toBeGreaterThanOrEqual([60_000,300_000,900_000][attempt-1]!);expect(Date.parse(current.data.scheduled_at)-start).toBeLessThan([60_000,300_000,900_000][attempt-1]!+5000);}else expect(current.data.status).toBe('DEAD_LETTER');}expect(fetcher).toHaveBeenCalledTimes(4);expect((await row('notification',n.id)).data).toMatchObject({status:'DEAD_LETTER',attempts:4});expect(await rows('decision')).toHaveLength(1);expect((await db.query("SELECT count(*)::int n FROM outbox WHERE company_id=$1 AND type='notification.scheduled'",[company])).rows[0].n).toBe(1);});
 it('network uncertainty isUNKNOWN with no retry, and a genuinely leased duplicate cannot reissue the send',async()=>{fetcher.mockImplementation(async()=>{throw new Error('Synthetic ambiguous provider timeout');});const {n,delivery}=await linked();await worker.process(await take('delivery.requested'));expect((await row('delivery',delivery.id)).data).toMatchObject({status:'UNKNOWN',failure_class:'UNKNOWN',attempts:1});expect((await row('notification',n.id)).data.status).toBe('UNKNOWN');await db.transaction(company,'SYNTHETIC_RESTART_EVENT',tx=>tx.event('delivery.requested',{delivery_id:delivery.id}));await worker.process(await take('delivery.requested'));expect(fetcher).toHaveBeenCalledTimes(1);expect(await rows('decision')).toHaveLength(1);});
 it('a recovered abandonedSENDING marker becomesUNKNOWN without provider I/O rather than attempting another send',async()=>{const {n,delivery}=await linked();await patch('delivery',delivery.id,{status:'SENDING',attempts:1,sending_job_id:'abandoned-job',sending_lease_hash:'a'.repeat(64),sending_started_at:new Date().toISOString()});await worker.process(await take('delivery.requested'));expect((await row('delivery',delivery.id)).data.status).toBe('UNKNOWN');expect((await row('notification',n.id)).data.status).toBe('UNKNOWN');expect(fetcher).not.toHaveBeenCalled();});
 it('an expired or stolen lease fails before provider I/O or aggregate/audit/outbox writes',async()=>{const {delivery}=await linked(),job=await take('delivery.requested'),before=await fingerprint();await expect(worker.handle({...job,lease_token:'STOLEN_SYNTHETIC_TOKEN'})).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await fingerprint()).toEqual(before);await db.query("UPDATE outbox SET leased_until=clock_timestamp()-interval '1 second' WHERE company_id=$1 AND id=$2",[company,job.id]);const expired=await fingerprint();await expect(worker.handle(job)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await fingerprint()).toEqual(expired);expect((await row('delivery',delivery.id)).data.status).toBe('PENDING');expect(fetcher).not.toHaveBeenCalled();});
 it('router timeout and abandonedSENDING remainUNKNOWN after a genuinely leased restart, with no repeated provider call',async()=>{fetcher.mockImplementation(async()=>{throw new Error('Synthetic ambiguous router timeout');});const response=await routerReply();await worker.process(await take('whatsapp.router_response'));expect((await row('whatsapp_router_response',response.id)).data).toMatchObject({status:'UNKNOWN',failure_class:'UNKNOWN'});await db.transaction(company,'SYNTHETIC_ROUTER_RESTART',tx=>tx.event('whatsapp.router_response',{response_id:response.id}));await worker.process(await take('whatsapp.router_response'));expect(fetcher).toHaveBeenCalledTimes(1);const abandoned=await routerReply();await patch('whatsapp_router_response',abandoned.id,{status:'SENDING',sending_job_id:'abandoned-router-job',sending_lease_hash:'a'.repeat(64)});await worker.process(await take('whatsapp.router_response'));expect((await row('whatsapp_router_response',abandoned.id)).data.status).toBe('UNKNOWN');expect(fetcher).toHaveBeenCalledTimes(1);});
 it('router recipient/window/source guards execute within a fresh leased claim, and stolen lease creates no status/audit changes',async()=>{const response=await routerReply(),job=await take('whatsapp.router_response'),before=await fingerprint();await expect(worker.handle({...job,lease_token:'STOLEN_ROUTER_LEASE'})).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});expect(await fingerprint()).toEqual(before);await patch('notification_setting','employee-settings',{opted_out:true});await worker.process(job);expect((await row('whatsapp_router_response',response.id)).data).toMatchObject({status:'BLOCKED',error:'CHANNEL_CONSENT_REQUIRED'});expect(fetcher).not.toHaveBeenCalled();});
 it('safe router failures use1/5/15minutes then dead-letter while revalidating the exact session/recipient on every claim',async()=>{fetcher.mockImplementation(async()=>new Response(JSON.stringify({error:{code:130429,message:'Synthetic router rate limit'}}),{status:429}));const response=await routerReply();for(let attempt=1;attempt<=4;attempt++){if(attempt>1)await patch('whatsapp_router_response',response.id,{scheduled_at:new Date(Date.now()-1000).toISOString()});const start=Date.now();await worker.process(await take('whatsapp.router_response'));const current=await row('whatsapp_router_response',response.id);expect(current.data.attempts).toBe(attempt);if(attempt<4){expect(current.data.status).toBe('RETRY_SCHEDULED');expect(Date.parse(current.data.scheduled_at)-start).toBeGreaterThanOrEqual([60_000,300_000,900_000][attempt-1]!);expect(Date.parse(current.data.scheduled_at)-start).toBeLessThan([60_000,300_000,900_000][attempt-1]!+5000);}else expect(current.data.status).toBe('DEAD_LETTER');}expect(fetcher).toHaveBeenCalledTimes(4);expect(await rows('decision')).toHaveLength(1);});
 it('validated inbox callbacks bind knownrouter providerID+recipient+account and cannot regressREAD with old/lower/failed states',async()=>{const response=await routerReply();await worker.process(await take('whatsapp.router_response'));expect((await row('whatsapp_router_response',response.id)).data).toMatchObject({status:'API_ACCEPTED',provider_account_id:'123456',provider_recipient_phone:'49123456789'});
  const emit=async(status:'READ'|'SENT'|'FAILED',patch:Data={})=>{const payload={kind:'STATUS',id:'synthetic-accepted-id',phone_number_id:'123456',recipient:'49123456789',received_at:new Date().toISOString(),status,...patch},eventId=randomUUID();await db.transaction(company,'SYNTHETIC_VALIDATED_INBOX_FIXTURE',async tx=>{await tx.query("INSERT INTO webhook_inbox(provider,event_id,company_id,payload) VALUES('WHATSAPP',$1,$2,$3)",[eventId,company,JSON.stringify(payload)]);await tx.event('whatsapp.inbound',{provider:'WHATSAPP',event_id:eventId});});await worker.process(await take('whatsapp.inbound'));};
  const before=await row('whatsapp_router_response',response.id);await emit('READ',{phone_number_id:'999999'});expect(await row('whatsapp_router_response',response.id)).toEqual(before);await emit('READ',{recipient:'49999999999'});expect(await row('whatsapp_router_response',response.id)).toEqual(before);await emit('READ');const read=await row('whatsapp_router_response',response.id);expect(read.data.status).toBe('READ');await emit('SENT');await emit('FAILED');expect(await row('whatsapp_router_response',response.id)).toEqual(read);expect(fetcher).toHaveBeenCalledTimes(1);
 });
 it.each(['opt-out','membership','inactive'])('fresh%s revocation before provider execution cancels/blocks the queued copy and projects notice state',async(revocation)=>{const {n,delivery}=await linked();if(revocation==='opt-out')await patch('notification_setting','employee-settings',{opted_out:true});if(revocation==='inactive')await patch('user','employee',{active:false});if(revocation==='membership'){const channel=await row('channel',delivery.data.channel_id);await patch('channel',channel.id,{members:channel.data.members.map((m:Data)=>m.user_id==='employee'?{...m,revoked_at:new Date().toISOString()}:m)});}await worker.process(await take('delivery.requested'));expect(['FAILED','CANCELLED']).toContain((await row('notification',n.id)).data.status);expect(fetcher).not.toHaveBeenCalled();});
 it('a canonical syntheticgeo incident produces3employee/1explicitresponsible schedules, deduplicates restart and cancels pending reminders atomically',async()=>{
  const confirmedAt=new Date().toISOString();await db.transaction(company,'SYNTHETIC_GEO_SOURCE_FIXTURE',async tx=>{await tx.add('shift',{state:'ACTIVE',activity:'AWAY_PENDING_REASON',employeeId:'employee',siteId:'site'},'shift');await tx.add('location_incident',{state:'OPEN',reason:'GEOFENCE_EXIT',employeeId:'employee',siteId:'site',shiftId:'shift',confirmedAt},'incident');await tx.event('absence.explanation_requested',{incidentId:'incident',shiftId:'shift',employeeId:'employee',siteId:'site'});});
  const job=await take('absence.explanation_requested');await worker.process(job);const notices=(await rows('notification')).filter(e=>e.data.work_cause?.type==='absence.explanation_requested');expect(notices.filter(e=>e.data.recipient_id==='employee').map(e=>Date.parse(e.data.scheduled_at)-Date.parse(confirmedAt)).sort((a,b)=>a-b)).toEqual([0,300_000,900_000]);expect(notices.filter(e=>e.data.recipient_id==='manager')).toHaveLength(1);
  await db.transaction(company,'SYNTHETIC_RESTART_EVENT',tx=>tx.event(job.type,job.data));await worker.process(await take(job.type));expect((await rows('notification')).filter(e=>e.data.work_cause)).toHaveLength(4);
  await db.transaction(company,'SYNTHETIC_END_SOURCE_FIXTURE',async tx=>{const shift=await tx.get('shift','shift');await tx.save(shift,{...shift.data,state:'ENDED'});expect(await cancelPendingAbsenceNotices(tx,shift.id,'SHIFT_ENDED',new Date().toISOString())).toBe(4);});expect((await rows('notification')).every(n=>n.data.status==='CANCELLED')).toBe(true);expect(await engine.readEntities(employee,'notification')).toEqual([]);expect(fetcher).not.toHaveBeenCalled();
 });
 it('changing duty ownership after one genuinely completedWEB manager notice cannot produce a second manager copy for the sameincident',async()=>{const source={incidentId:'incident',shiftId:'shift',employeeId:'employee',siteId:'site'};await db.transaction(company,'SYNTHETIC_GEO_SOURCE_FIXTURE',async tx=>{await tx.add('shift',{state:'ACTIVE',activity:'AWAY_PENDING_REASON',employeeId:'employee',siteId:'site'},'shift');await tx.add('location_incident',{state:'OPEN',reason:'GEOFENCE_EXIT',employeeId:'employee',siteId:'site',shiftId:'shift',confirmedAt:new Date().toISOString()},'incident');await tx.event('absence.explanation_requested',source);});await worker.process(await take('absence.explanation_requested'));const managerNotice=(await rows('notification')).find(n=>n.data.recipient_id==='manager')!;await worker.process(await take('notification.scheduled',managerNotice.id));expect((await row('notification',managerNotice.id)).data.status).toBe('SUCCEEDED');await db.transaction(company,'SYNTHETIC_EXPLICIT_DUTY_CHANGE',async tx=>{await tx.add('user',{active:true,roles:['OPERATIONS_MANAGER'],siteIds:['site']},'replacement-manager');const site=await tx.get('site','site');await tx.save(site,{...site.data,onCallUserId:'replacement-manager'});await tx.event('absence.explanation_requested',source);});await worker.process(await take('absence.explanation_requested'));expect((await rows('notification')).filter(n=>n.data.event==='absence.responsible_review_required')).toHaveLength(1);expect(fetcher).not.toHaveBeenCalled();});
});
