import {describe,it,expect,vi} from 'vitest';
import {communicationsCommands} from '../packages/domain/communications.ts';
import {activeOperationalNotice,nextQuietWindowEnd,quietHour,safeRetryDelayMs} from '../packages/domain/notification-policy.ts';
import {WhatsAppCloudAdapter} from '../packages/integrations/whatsapp.ts';
import {DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';

/** Explicit transaction double. These cases establish domain/adapter policy, not SQL/provider acceptance. */
class Tx implements Transaction {
 companyId='policy-test';now='2026-10-08T10:00:00.000Z';rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];sequence=0;
 async get<T extends Data=Data>(kind:string,id:string){const row=this.rows.get(kind+':'+id);if(!row)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(row) as Entity<T>;}
 async list<T extends Data=Data>(kind:string){return [...this.rows.values()].filter(r=>r.kind===kind).map(r=>structuredClone(r) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=kind+'-'+ ++this.sequence){const row={kind,id,companyId:this.companyId,data:structuredClone(data),version:1,createdAt:this.now,updatedAt:this.now};this.rows.set(kind+':'+id,row);return structuredClone(row);}
 async save(row:Entity,data:Data,version=row.version){const current=await this.get(row.kind,row.id);if(current.version!==version)throw new DomainError('VERSION_CONFLICT');const saved={...current,data:structuredClone(data),version:version+1,updatedAt:this.now};this.rows.set(row.kind+':'+row.id,saved);return structuredClone(saved);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
}
const service:Actor={userId:'service',companyId:'policy-test',roles:['SERVICE_ACCOUNT'],permissions:['integration.process'],siteIds:[],customerIds:[],warehouseIds:[]};
const employee:Actor={...service,userId:'employee',roles:['EMPLOYEE'],permissions:['chat.read'],siteIds:['site']};
async function command(tx:Tx,name:string,input:Data,actor=service){const definition=communicationsCommands[name]!;const ctx:CommandContext={tx,actor,now:tx.now,idempotencyKey:'explicit-cpu-policy',requireSite:()=>{},requireOwn:userId=>{if(userId!==actor.userId)throw new DomainError('ACCESS_DENIED');}};return definition.handler(ctx,definition.schema.parse(input));}
async function pending(tx:Tx,id='notification'){return tx.add('notification',{recipient_id:'employee',event:'REMINDER',channel:'WEB',category:'WORK',status:'PENDING',scheduled_at:tx.now,attempts:0,max_attempts:4},id);}

describe('V4 notification delivery policy (CPU transaction doubles)',()=>{
 it('new settings default to 20:00–07:00 Berlin, while explicit chosen hours remain configurable',async()=>{const tx=new Tx();expect((await command(tx,'notifications.configure',{language:'UK',whatsapp_consent:false},employee)).data).toMatchObject({quiet_start:20,quiet_end:7,timezone:'Europe/Berlin'});expect((await command(tx,'notifications.configure',{language:'UK',whatsapp_consent:false,quiet_start:19,quiet_end:6},employee)).data).toMatchObject({quiet_start:19,quiet_end:6});});
 it('a queued own work notice uses the current language and deterministic title at preparation',async()=>{const tx=new Tx();await tx.add('notification',{recipient_id:'employee',event:'task.assigned',category:'WORK',channel:'WEB',status:'PENDING',attempts:0,scheduled_at:tx.now,language:'UK',title:'Вам призначено завдання',work_cause:{schema:1,type:'task.assigned'}},'notification');await command(tx,'notifications.configure',{language:'PL',whatsapp_consent:false},employee);expect((await command(tx,'notifications.prepare',{notification_id:'notification'})).data).toMatchObject({status:'RUNNING',language:'PL',title:'Przydzielono Ci zadanie'});});
 it.each([
  ['summer','2026-07-06T18:00:00.000Z','2026-07-07T05:00:00.000Z'],
  ['winter','2026-01-06T19:00:00.000Z','2026-01-07T06:00:00.000Z'],
  ['spring DST change','2026-03-28T19:00:00.000Z','2026-03-29T05:00:00.000Z'],
  ['autumn DST change','2026-10-24T18:00:00.000Z','2026-10-25T06:00:00.000Z'],
 ])('%s defers exactly to the next real Berlin 07:00 without consuming an attempt',async(_name,now,end)=>{expect(quietHour(now)).toBe(true);expect(nextQuietWindowEnd(now)).toBe(end);const tx=new Tx();tx.now=now;await pending(tx);expect(await command(tx,'notifications.prepare',{notification_id:'notification'})).toMatchObject({reason:'QUIET_HOURS'});expect((await tx.get('notification','notification')).data).toMatchObject({status:'RETRY_SCHEDULED',scheduled_at:end,attempts:0});expect(tx.events).toEqual([{type:'notification.scheduled',data:{notification_id:'notification',not_before:end}}]);});
 it('quiet boundaries are inclusive at20:00/exclusive at07:00, disabled equal ranges and ordinary metadata cannot grant incident exemption',()=>{expect(quietHour('2026-07-06T17:59:59.999Z')).toBe(false);expect(quietHour('2026-07-07T05:00:00.000Z')).toBe(false);expect(nextQuietWindowEnd('2026-07-06T23:15:30Z',0,0)).toBe('2026-07-06T23:15:30Z');expect(activeOperationalNotice({operational_incident:true,event:'REMINDER'})).toBe(false);expect(()=>communicationsCommands['notifications.schedule']!.schema.parse({recipient_id:'employee',event:'ABSENCE',category:'WORK',scheduled_at:'2026-10-08T10:00:00Z',dedup_key:'forged',operational_incident:true})).toThrow();});
 it('confirmed safe failures retry after1/5/15minutes then dead-letter one logical notice and one decision',async()=>{const tx=new Tx();await pending(tx);const observed:number[]=[];for(let attempt=1;attempt<=4;attempt++){await command(tx,'notifications.prepare',{notification_id:'notification'});const start=Date.parse(tx.now),result=await command(tx,'notifications.complete',{notification_id:'notification',succeeded:false,error:'PROVIDER_UNAVAILABLE',failure_class:'CONFIRMED_TRANSIENT'});if(attempt<4){observed.push(Date.parse(result.data.scheduled_at)-start);tx.now=result.data.scheduled_at;}else expect(result.data).toMatchObject({status:'DEAD_LETTER',attempts:4});}expect(observed).toEqual([60_000,300_000,900_000]);expect(tx.events.filter(e=>e.type==='notification.scheduled')).toHaveLength(3);expect(await tx.list('notification')).toHaveLength(1);expect(await tx.list('decision')).toHaveLength(1);expect([1,2,3].map(safeRetryDelayMs)).toEqual(observed);});
 it.each(['DEFINITIVE','UNKNOWN'] as const)('%s does not enqueue an automatic send and unknown remains distinct from failed/delivered',async(failure)=>{const tx=new Tx();await pending(tx);await command(tx,'notifications.prepare',{notification_id:'notification'});expect((await command(tx,'notifications.complete',{notification_id:'notification',succeeded:false,error:'PROVIDER_UNAVAILABLE',failure_class:failure})).data.status).toBe(failure==='UNKNOWN'?'UNKNOWN':'FAILED');expect(tx.events.filter(e=>e.type==='notification.scheduled')).toEqual([]);expect(await tx.list('decision')).toHaveLength(failure==='UNKNOWN'?1:0);});
 it('one delivery owns provider retries, projects linked state, and a later verified provider outcome reconciles UNKNOWN without another send',async()=>{const tx=new Tx();await tx.add('notification',{recipient_id:'employee',message_id:'message',channel:'WHATSAPP',status:'RUNNING',attempts:0},'notification');await tx.add('delivery',{recipient_id:'employee',message_id:'message',channel:'WHATSAPP',status:'PENDING',attempts:0},'delivery');expect((await command(tx,'notifications.delivery_link',{notification_id:'notification',delivery_id:'delivery'})).data.status).toBe('AWAITING_DELIVERY');await command(tx,'delivery.status',{delivery_id:'delivery',status:'UNKNOWN',failure_class:'UNKNOWN'});expect((await tx.get('notification','notification')).data.status).toBe('UNKNOWN');await command(tx,'delivery.status',{delivery_id:'delivery',status:'API_ACCEPTED',provider_message_id:'verified-provider-id'});expect((await tx.get('notification','notification')).data).toMatchObject({status:'SUCCEEDED',provider_message_id:'verified-provider-id'});expect((await tx.get('delivery','delivery')).data).toMatchObject({status:'API_ACCEPTED',provider_state:'ACCEPTED_BY_PROVIDER'});expect(tx.events.filter(e=>e.type==='delivery.requested'||e.type==='notification.scheduled')).toEqual([]);});
 it('an explicitly enabledWEB fallback retains the provider failure instead of claiming WhatsApp delivered',async()=>{const tx=new Tx();await tx.add('notification_setting',{user_id:'employee',allowed_fallback:'WEB',opted_out:false});await tx.add('notification',{recipient_id:'employee',message_id:'message',channel:'WHATSAPP',status:'RUNNING'},'notification');await tx.add('delivery',{recipient_id:'employee',message_id:'message',channel:'WHATSAPP',status:'PENDING',attempts:0},'delivery');await command(tx,'notifications.delivery_link',{notification_id:'notification',delivery_id:'delivery'});await command(tx,'delivery.status',{delivery_id:'delivery',status:'FAILED',failure_class:'DEFINITIVE',error:'TEMPLATE_REJECTED'});expect((await tx.get('notification','notification')).data).toMatchObject({channel:'WEB',status:'SUCCEEDED',delivery_status:'FAILED',reason:'WHATSAPP_PROVIDER_FALLBACK',error:'TEMPLATE_REJECTED'});expect((await tx.get('delivery','delivery')).data.status).toBe('FAILED');});
 it('repeated unknown status creates one decision, provider ID cannot change and late failure cannot overwriteREAD',async()=>{const tx=new Tx();await tx.add('delivery',{status:'SENDING',attempts:1},'delivery');for(let i=0;i<2;i++)await command(tx,'delivery.status',{delivery_id:'delivery',status:'UNKNOWN',failure_class:'UNKNOWN'});expect(await tx.list('decision')).toHaveLength(1);await command(tx,'delivery.status',{delivery_id:'delivery',status:'READ',provider_message_id:'provider-id'});expect((await command(tx,'delivery.status',{delivery_id:'delivery',status:'FAILED'})).data.status).toBe('READ');await expect(command(tx,'delivery.status',{delivery_id:'delivery',status:'DELIVERED',provider_message_id:'foreign-id'})).rejects.toMatchObject({code:'VERSION_CONFLICT'});});
 it('link cannot bind another recipient/message and only service accounts can record delivery outcomes',async()=>{const tx=new Tx();await tx.add('notification',{recipient_id:'employee',message_id:'message',channel:'WHATSAPP',status:'RUNNING'},'notification');await tx.add('delivery',{recipient_id:'other',message_id:'message',channel:'WHATSAPP',status:'PENDING'},'delivery');await expect(command(tx,'notifications.delivery_link',{notification_id:'notification',delivery_id:'delivery'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(command(tx,'delivery.status',{delivery_id:'delivery',status:'READ'},employee)).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('provider acceptance/delivery cannot be fabricated without a provider receipt, and failure classification cannot accompany success',async()=>{const tx=new Tx();await tx.add('delivery',{channel:'WHATSAPP',status:'UNKNOWN',attempts:1},'delivery');for(const status of ['API_ACCEPTED','SENT','DELIVERED','READ'])await expect(command(tx,'delivery.status',{delivery_id:'delivery',status})).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'PROVIDER_RECEIPT_REQUIRED'}});await expect(command(tx,'delivery.status',{delivery_id:'delivery',status:'API_ACCEPTED',provider_message_id:'provider-id',failure_class:'UNKNOWN'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});expect((await tx.get('delivery','delivery')).data.status).toBe('UNKNOWN');expect(tx.events).toEqual([]);});
});

describe('WhatsApp send certainty (synthetic HTTP responses; no real Meta acceptance)',()=>{
 const adapter=(fetcher:typeof fetch)=>new WhatsAppCloudAdapter({accessToken:'synthetic',phoneNumberId:'123456',apiVersion:'v24.0',accountCapabilitiesVerified:true},fetcher);
 it.each([
  ['explicit transient rejection',429,{error:{code:130429,message:'Rate limit'}},'CONFIRMED_TRANSIENT',true],
  ['explicit permanent rejection',400,{error:{code:100,message:'Invalid argument'}},'DEFINITIVE',false],
  ['ambiguous server response',503,{status:'unavailable'},'UNKNOWN',false],
  ['malformed success',200,{accepted:true},'UNKNOWN',false],
 ])('%s classifies outcome without inventing accepted/delivered',async(_name,status,body,failure,retryable)=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify(body),{status}));await expect(adapter(fetcher as typeof fetch).send('49123456789',{kind:'TEXT',text:'Synthetic policy test'},{kind:'TEXT'})).rejects.toMatchObject({code:'PROVIDER_UNAVAILABLE',details:{failure_class:failure,retryable}});expect(fetcher).toHaveBeenCalledTimes(1);});
 it('network timeout isUNKNOWN and cannot safely auto-retry',async()=>{const fetcher=vi.fn(async()=>{throw new Error('Synthetic timeout after request reached provider');});await expect(adapter(fetcher as typeof fetch).send('49123456789',{kind:'TEXT',text:'Synthetic policy test'},{kind:'TEXT'})).rejects.toMatchObject({details:{failure_class:'UNKNOWN',retryable:false}});expect(fetcher).toHaveBeenCalledTimes(1);});
});
