import {afterEach,describe,expect,it,vi} from 'vitest';
import {Engine} from '../apps/api/engine.js';
import type {Database,PgTransaction} from '../apps/api/database.js';
import {createOperationsDigestCommands} from '../apps/api/operations-digest.js';
import {berlinDigestMidnight,digestSlot,latestDigestSlot,operationsDigestHash,operationsDigestVisible,policyDue,type OperationsDigestHost} from '../packages/domain/operations-digest.js';
import {DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.js';

// Actual Engine row ACL/projection, canonical communications handlers and digest
// handlers; transaction storage/rollback below are explicit CPU doubles, not SQL.
const NOW='2026-03-30T06:15:00.000Z';
class MemoryTransaction implements Transaction {
 companyId='synthetic-digest';rows=new Map<string,Entity>();events:Data[]=[];readKinds:string[]=[];sequence=0;readOnly=false;
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const row=this.rows.get(`${kind}:${id}`);if(!row||row.companyId!==this.companyId)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(row) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{this.readKinds.push(kind);return [...this.rows.values()].filter(e=>e.companyId===this.companyId&&e.kind===kind).map(e=>structuredClone(e) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`${kind}-${++this.sequence}`):Promise<Entity<T>>{if(this.readOnly)throw Error('READ_ONLY_WRITE_ATTEMPT');if(this.rows.has(`${kind}:${id}`))throw new DomainError('VERSION_CONFLICT');const entity={kind,id,companyId:this.companyId,data:structuredClone(data),version:1,createdAt:NOW,updatedAt:NOW};this.rows.set(`${kind}:${id}`,entity);return structuredClone(entity);}
 async save(entity:Entity,data:Data,version=entity.version):Promise<Entity>{if(this.readOnly)throw Error('READ_ONLY_WRITE_ATTEMPT');const old=await this.get(entity.kind,entity.id);if(old.version!==version)throw new DomainError('VERSION_CONFLICT');const next={...old,data:structuredClone(data),version:old.version+1};this.rows.set(`${entity.kind}:${entity.id}`,next);return structuredClone(next);}
 async event(type:string,data:Data){if(this.readOnly)throw Error('READ_ONLY_WRITE_ATTEMPT');this.events.push({type,data:structuredClone(data)});}
 async atomic<T>(action:()=>Promise<T>){const rows=structuredClone(this.rows),events=structuredClone(this.events);try{return await action();}catch(error){this.rows=rows;this.events=events;throw error;}}
}
async function fixture(){
 const tx=new MemoryTransaction(),db={transaction:async(_company:string,_actor:string,fn:(tx:MemoryTransaction)=>Promise<unknown>)=>fn(tx)} as unknown as Database,engine=new Engine(db,'TEST');
 await tx.add('user',{active:true,roles:['DIRECTOR'],permissions:[],siteIds:['site'],warehouseIds:[]},'owner');
 await tx.add('user',{active:true,roles:['INTERNAL_BAULEITER'],permissions:['notifications.manage'],siteIds:['site']},'another-owner');await tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['site']},'worker');await tx.add('user',{active:true,roles:['SERVICE_ACCOUNT'],permissions:[],siteIds:[]},'service');
 await tx.add('site',{name:'Synthetic site',active:true,customerId:'customer'},'site');await tx.add('site',{active:true,customerId:'other-customer'},'outside');await tx.add('customer',{active:true},'customer');await tx.add('customer',{active:true},'other-customer');
 await tx.add('crew_assignment',{siteId:'site',orderId:'order',employeeIds:['worker'],status:'ASSIGNED',startAt:'2026-03-30T07:00:00Z',endAt:'2026-03-30T09:00:00Z',phone:'PHONE_CANARY'},'crew');
 await tx.add('task',{siteId:'site',title:'PRIVATE_TASK_TEXT_CANARY',state:'ACCEPTED',unit:'M2',plannedQuantityMilli:2000,reportedQuantityMilli:1500,acceptedQuantityMilli:1200,assigneeIds:['worker']},'task-area');
 await tx.add('task',{siteId:'site',state:'SUBMITTED_FOR_REVIEW',unit:'HOUR',plannedQuantityMilli:3000,reportedQuantityMilli:2000,acceptedQuantityMilli:0},'task-hour');await tx.add('task',{siteId:'site',state:'ASSIGNED',unit:'UNIT',plannedQuantityMilli:1000,reportedQuantityMilli:0,acceptedQuantityMilli:0},'task-unit');
 const segments=[['work','WORKING','2026-03-29T00:00:00Z','2026-03-29T01:00:00Z'],['travel','TRAVELLING','2026-03-29T01:00:00Z','2026-03-29T02:00:00Z'],['break','ON_BREAK','2026-03-29T02:00:00Z','2026-03-29T02:30:00Z'],['pending','AWAY_PENDING_REASON','2026-03-29T02:30:00Z','2026-03-29T02:35:00Z']].map(([id,activity,startAt,endAt])=>({id,activity,startAt:new Date(startAt!).toISOString(),endAt:new Date(endAt!).toISOString(),shiftId:'synthetic-shift',siteId:'site',employeeId:'worker',privateReason:'PRIVATE_REASON_CANARY'}));
 for(const segment of segments)await tx.add('time_segment',{...segment,payrollRateCents:999999},segment.id!);
 await tx.add('timesheet',{state:'APPROVED',employeeId:'worker',approvedBy:'owner',approvedAt:'2026-03-30T00:00:00Z',segmentSnapshot:segments,payableSeconds:777777,bank:'BANK_CANARY',periodStart:'2026-03-28T23:00:00Z',periodEnd:'2026-03-29T22:00:00Z'},'sheet');
 await tx.add('trip',{siteId:'site',employeeId:'worker',approvalState:'APPROVED',state:'ARRIVED'},'trip');
 await tx.add('trip_approval',{tripId:'trip',decision:'APPROVE',employeeId:'worker',approvedBy:'owner',approvedAt:'2026-03-30T00:00:00Z',segmentSnapshot:[segments[1]],snapshot:{siteId:'site'},totals:{payableSeconds:999999},gps:'GPS_CANARY'},'trip-approval');
 await tx.add('material',{baseUnit:'ML',internalCostCents:999999},'paint');await tx.add('material_usage',{siteId:'site',materialId:'paint',unit:'ML',quantityBase:250,confirmedAt:'2026-03-29T12:00:00Z',internalCostCents:987654321},'usage');await tx.add('material_request',{siteId:'site',materialId:'paint',state:'APPROVED',approvedBase:100,receivedBase:40,employeeId:'worker',reason:'PRIVATE_MATERIAL_REASON_CANARY'},'request');
 const lead=await tx.add('lead',{siteId:'site',customerId:'customer',status:'NEW',contact:{email:'PRIVATE_CONTACT_CANARY'},text:'PRIVATE_LEAD_CANARY'},'lead');tx.rows.set('lead:lead',{...lead,createdAt:'2026-03-29T12:00:00Z'});
 await tx.add('decision',{siteId:'site',ownerId:'owner',status:'OPEN',amountCents:12000,summaryDE:'PRIVATE_DECISION_CANARY'},'action');await tx.add('decision',{siteId:'site',ownerId:'owner',status:'OPEN'},'unpriced');await tx.add('decision',{siteId:'site',ownerId:'another-owner',status:'OPEN',amountCents:900000},'other-action');await tx.add('decision',{siteId:'site',ownerId:'owner',status:'OPEN',approvalDomain:'FINANCE',amountCents:987654321,notes:'FINANCE_CANARY'},'finance-action');
 await tx.add('task',{siteId:'outside',state:'ACCEPTED',unit:'M2',plannedQuantityMilli:999999,reportedQuantityMilli:999999,acceptedQuantityMilli:999999},'outside-task');await tx.add('payroll_calculation',{employeeId:'worker',payableCents:999999,notes:'PAYROLL_CANARY'},'payroll');await tx.add('location_sample',{latitude:52.52,longitude:13.4,employeeId:'worker',route:'RAW_GPS_CANARY'},'gps');await tx.add('media_asset',{visibility:'CONFIDENTIAL',bank:'CONFIDENTIAL_MEDIA_CANARY'},'media');
 const projected:string[]=[],visible:string[]=[];const host:OperationsDigestHost<MemoryTransaction>={registry:engine.registry,actorIn:(current,id)=>engine.actorIn(current as unknown as PgTransaction,id),scope:(actor,permission)=>engine.scope(actor,permission),visible:async(current,actor,entity)=>{visible.push(`${entity.kind}:${entity.id}`);return engine.visible(current as unknown as PgTransaction,actor,entity);},project:async(current,actor,entity)=>{projected.push(`${entity.kind}:${entity.id}`);return engine.project(current as unknown as PgTransaction,actor,entity);}};
 const commands=createOperationsDigestCommands(host);Object.assign(engine.registry,commands);
 async function invoke(name:string,input:Data,options:{userId?:string;now?:string;version?:number}={}){const userId=options.userId??'owner',actor=await host.actorIn(tx,userId),definition=commands[name]??engine.registry[name]!;const c=engine.context(tx as unknown as PgTransaction,host.scope(actor,definition.permission),'explicit-cpu-case',options.version,options.now??NOW,['worker'],definition.permission);return tx.atomic(()=>definition.handler(c,definition.schema.parse(input)));}
 const input={name:'Synthetic morning review',kind:'MORNING',ownerId:'owner',scope:{siteIds:['site'],customerIds:[]},cron:'0 8 * * *',activeFrom:'2026-01-01T00:00:00Z'};
 const configure=(patch:Data={})=>invoke('digest.configure',{...input,...patch});const actor=()=>host.actorIn(tx,'owner');const snapshot=()=>structuredClone({rows:tx.rows,events:tx.events});const update=async(kind:string,id:string,patch:Data)=>{const entity=await tx.get(kind,id);return tx.save(entity,{...entity.data,...patch});};
 return {tx,engine,host,commands,invoke,input,configure,actor,snapshot,update,projected,visible};
}
afterEach(()=>{vi.unstubAllEnvs();vi.restoreAllMocks();});

describe('actual scoped deterministic operational digest composition',()=>{
 it('reports canonical submitted backlog separately from half-open period worklog and net accept/reopen event quantities',async()=>{
  const f=await fixture(),policy=await f.configure();
  for(const [id,siteId,reportedAt,quantityMilli] of [['start','site','2026-03-28T23:00:00Z',1500],['end','site','2026-03-29T22:00:00Z',900000],['foreign','outside','2026-03-29T12:00:00Z',900000]] as const)await f.tx.add('worklog',{taskId:siteId==='site'?'task-area':'outside-task',siteId,unit:'M2',reportedAt,quantityMilli,employeeIds:['worker'],groupResultKey:id,description:'PRIVATE_PERIOD_CANARY'},id);
  await f.tx.add('task_review',{taskId:'task-area',siteId:'site',decision:'ACCEPT',quantityMilli:1500,reviewedAt:'2026-03-29T12:00:00Z',snapshot:{siteId:'site',unit:'M2'},reason:'PRIVATE_REVIEW_CANARY'},'accept');
  await f.tx.add('task_review',{taskId:'task-area',decision:'REOPEN',reviewedAt:'2026-03-29T13:00:00Z',snapshot:{siteId:'site',unit:'M2',acceptedQuantityMilli:500}},'reopen');
  await f.tx.add('task_review',{taskId:'task-hour',decision:'REOPEN',reviewedAt:'2026-03-29T13:00:00Z',snapshot:{siteId:'site',unit:'HOUR',acceptedQuantityMilli:700}},'reopen-hour');
  const preview=await f.invoke('digest.preview',{policyId:policy.id});expect(preview.sections.tasks.counts).toEqual({accepted:1,submitted:1,incomplete:1});expect(preview.sections.tasks.byUnit.M2.acceptedQuantityMilli).toBe(1200);expect(preview.sections.tasks.periodProgress).toMatchObject({counts:{worklogs:1,acceptedReviews:1,reopenedReviews:2},byUnit:{M2:{reportedQuantityMilli:1500,grossAcceptedQuantityMilli:1500,revokedAcceptedQuantityMilli:500,acceptedQuantityMilli:1000},HOUR:{acceptedQuantityMilli:-700}}});expect(JSON.stringify(preview)).not.toContain('PRIVATE_PERIOD_CANARY');expect(preview.coverage.sourceReferences.map((r:Data)=>r.id)).toContain('accept');expect(preview.coverage.sourceReferences.map((r:Data)=>r.id)).not.toContain('end');
 });
 it('applies actual approved closed-period corrections in canonical sequence and invalidates old snapshots when new adjustments appear',async()=>{
  const f=await fixture(),policy=await f.configure(),before=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1});expect(before.data.snapshot.sections.time.byActivity.WORKING).toBe(3600);
  const correction=await f.invoke('timesheet.correction',{timesheetId:'sheet',segmentId:'work',activity:'SERVICE_TASK',reason:'Synthetic correction'},{userId:'worker'});await f.invoke('timesheet.correction.review',{correctionId:correction.id,decision:'APPROVE',reason:'Synthetic independently reviewed'});const adjustment=(await f.tx.list('timesheet_adjustment'))[0]!;
  expect((await f.tx.get('timesheet','sheet')).data.segmentSnapshot[0].activity).toBe('WORKING');const preview=await f.invoke('digest.preview',{policyId:policy.id});expect(preview.sections.time.approvedSeconds).toBe(9300);expect(preview.sections.time.byActivity.WORKING).toBeUndefined();expect(preview.sections.time.byActivity.SERVICE_TASK).toBe(3600);expect(preview.coverage.sourceReferences).toContainEqual({kind:'timesheet_adjustment',id:adjustment.id,version:adjustment.version,permission:'timesheet.read'});expect(await operationsDigestVisible(f.tx,await f.actor(),before,f.host)).toBe(false);
  const next=await f.invoke('timesheet.correction',{timesheetId:'sheet',segmentId:'work',activity:'WAITING_WORK',reason:'Synthetic second correction'},{userId:'worker'});await f.invoke('timesheet.correction.review',{correctionId:next.id,decision:'APPROVE',reason:'Synthetic second approval'});const latest=await f.invoke('digest.preview',{policyId:policy.id});expect(latest.sections.time.byActivity.SERVICE_TASK).toBeUndefined();expect(latest.sections.time.byActivity.WAITING_WORK).toBe(3600);expect(await f.tx.list('payroll_calculation')).toHaveLength(1);
 });
 it('never presents stale original hours when an approved adjustment falls outside current source authority',async()=>{
  const f=await fixture(),policy=await f.configure(),sheet=await f.tx.get('timesheet','sheet');await f.tx.add('timesheet_adjustment',{timesheetId:sheet.id,employeeId:'worker',state:'APPROVED',sequence:1,approvedBy:'owner',approvedAt:NOW,originalSnapshots:[sheet.data.segmentSnapshot[0]],proposedSnapshots:[{...sheet.data.segmentSnapshot[0],siteId:'outside',activity:'SERVICE_TASK'}]},'outside-adjustment');const preview=await f.invoke('digest.preview',{policyId:policy.id});expect(preview.sections.time).toEqual({status:'UNAVAILABLE',reason:'APPROVED_CORRECTION_NOT_AUTHORIZED_OR_INVALID'});
 });
 it('selects the current latest approved trip snapshot once and suppresses superseded approval after a dispute',async()=>{
  const f=await fixture(),policy=await f.configure(),first=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1}),approval=await f.tx.get('trip_approval','trip-approval');await f.tx.add('trip_approval',{...approval.data,approvedAt:'2026-03-30T02:00:00Z',segmentSnapshot:[{...approval.data.segmentSnapshot[0],endAt:'2026-03-29T01:30:00Z'}]},'latest-trip');await f.update('trip','trip',{approvalState:'APPROVED'});expect((await f.invoke('digest.preview',{policyId:policy.id})).sections.travel).toMatchObject({approvedRecordedSeconds:1800,tripCount:1});expect(await operationsDigestVisible(f.tx,await f.actor(),first,f.host)).toBe(false);await f.tx.add('trip_approval',{...approval.data,decision:'DISPUTE',approvedAt:'2026-03-30T03:00:00Z'},'dispute');await f.update('trip','trip',{approvalState:'DISPUTED'});expect((await f.invoke('digest.preview',{policyId:policy.id})).sections.travel).toMatchObject({approvedRecordedSeconds:0,tripCount:0});
 });
 it('marks invalid approved intervals unknown with known subtotal instead of fabricating a zero total',async()=>{
  const f=await fixture(),policy=await f.configure(),sheet=await f.tx.get('timesheet','sheet');await f.update('timesheet',sheet.id,{segmentSnapshot:sheet.data.segmentSnapshot.map((s:Data)=>s.id==='work'?{...s,startAt:'malformed'}:s)});const preview=await f.invoke('digest.preview',{policyId:policy.id});expect(preview.sections.time).toMatchObject({approvedSeconds:null,knownApprovedSeconds:5700,incompleteRecords:1});
 });
 it('uses canonical director inventory.read only within assigned current sites and hides old snapshots after capability or customer binding changes',async()=>{
  const f=await fixture(),actor=await f.actor();expect(actor.roles).toEqual(['DIRECTOR']);expect(actor.permissions).toContain('inventory.read');expect(actor.permissions).not.toContain('scope.company');const policy=await f.configure(),digest=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1});expect(digest.data.snapshot.sections.materials.byMaterialUnit['paint:ML'].quantityBase).toBe(250);await expect(f.configure({scope:{siteIds:['outside'],customerIds:[]}})).rejects.toMatchObject({code:'ACCESS_DENIED'});await f.update('site','site',{customerId:'other-customer'});expect(await operationsDigestVisible(f.tx,await f.actor(),digest,f.host)).toBe(false);expect((await f.invoke('digest.preview',{policyId:policy.id})).sections.leads.count).toBe(0);await f.update('user','owner',{roles:['QUALITY_CONTROL'],permissions:['notifications.manage']});expect((await f.invoke('digest.preview',{policyId:policy.id})).sections.materials.status).toBe('UNAVAILABLE');
 });
 it('combines authorized current crews/tasks/materials/shortages/leads/owned decisions with explicit integer unit totals',async()=>{const f=await fixture(),policy=await f.configure(),result=await f.invoke('digest.preview',{policyId:policy.id});expect(result).toMatchObject({policyId:policy.id,policyVersion:1,providerInvoked:false,businessEffectsExecuted:false,scheduledSlot:true});expect(result.sections.crews.count).toBe(1);expect(result.sections.tasks.counts).toEqual({accepted:1,submitted:1,incomplete:1});expect(result.sections.tasks.byUnit.M2.acceptedQuantityMilli).toBe(1200);expect(result.sections.tasks.byUnit.HOUR.reportedQuantityMilli).toBe(2000);expect(result.sections.materials.byMaterialUnit['paint:ML'].quantityBase).toBe(250);expect(result.sections.shortages.items[0]).toMatchObject({unit:'ML',unreceivedBase:60});expect(result.sections.leads.count).toBe(1);expect(result.sections.decisions).toMatchObject({count:2,knownActionCents:12000,unpricedCount:1,currency:'EUR',financeExcluded:true});});
 it('clips approved recorded UTC intervals through the23-hour Berlin day without deducting break/pending or using payable totals',async()=>{const f=await fixture(),policy=await f.configure(),result=await f.invoke('digest.preview',{policyId:policy.id});expect(Date.parse(result.periodEnd)-Date.parse(result.periodStart)).toBe(23*3600000);expect(result.sections.time).toMatchObject({approvedSeconds:9300,byActivity:{WORKING:3600,TRAVELLING:3600,ON_BREAK:1800,AWAY_PENDING_REASON:300}});expect(result.sections.travel).toMatchObject({approvedRecordedSeconds:3600,tripCount:1});expect(result.asOf).toBe(NOW);expect(result.slotAt).toBe('2026-03-30T06:00:00.000Z');});
 it('uses previous complete Berlin calendar week and real167-hour DST boundaries',async()=>{const f=await fixture(),policy=await f.configure({kind:'WEEK',cron:'0 0 * * 1'}),result=await f.invoke('digest.preview',{policyId:policy.id});expect(result.periodStart).toBe('2026-03-22T23:00:00.000Z');expect(result.periodEnd).toBe('2026-03-29T22:00:00.000Z');expect(Date.parse(result.periodEnd)-Date.parse(result.periodStart)).toBe(167*3600000);expect(result.sections.time.approvedSeconds).toBe(9300);});
 it('preview runs with writes forbidden and never invokes LLM/network/notification or changes business data',async()=>{const f=await fixture(),policy=await f.configure(),before=f.snapshot(),network=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('NETWORK_FORBIDDEN'));f.tx.readOnly=true;await f.invoke('digest.preview',{policyId:policy.id});expect(f.snapshot()).toEqual(before);expect(network).not.toHaveBeenCalled();for(const kind of ['payroll_calculation','rate_history','official_payslip','location_sample','media_asset','message'])expect(f.tx.readKinds).not.toContain(kind);});
 it('never projects private prose/contact/payroll/GPS or sums finance decisions even when owner explicitly has finance authority',async()=>{const f=await fixture();await f.update('user','owner',{permissions:['notifications.manage','dispatch.read','dispatch.manage','lead.read','lead.manage','finance.payout.approve']});const policy=await f.configure(),result=await f.invoke('digest.preview',{policyId:policy.id}),json=JSON.stringify(result);for(const canary of ['PRIVATE_TASK_TEXT_CANARY','PRIVATE_REASON_CANARY','PRIVATE_CONTACT_CANARY','PRIVATE_LEAD_CANARY','PRIVATE_DECISION_CANARY','PHONE_CANARY','BANK_CANARY','PAYROLL_CANARY','FINANCE_CANARY','GPS_CANARY','RAW_GPS_CANARY','PRIVATE_MATERIAL_REASON_CANARY','987654321','777777'])expect(json).not.toContain(canary);expect(result.sections.decisions.knownActionCents).toBe(12000);});
 it('each captured source has passed actual Engine visibility and projection under its section capability',async()=>{const f=await fixture(),policy=await f.configure(),result=await f.invoke('digest.preview',{policyId:policy.id});for(const ref of result.coverage.sourceReferences){expect(f.visible).toContain(`${ref.kind}:${ref.id}`);expect(f.projected).toContain(`${ref.kind}:${ref.id}`);}expect(result.coverage.sourceReferences.some((ref:Data)=>ref.id==='outside-task')).toBe(false);});
 it('missing capabilities are explicitly unavailable without invented zero totals',async()=>{const f=await fixture();await f.update('user','owner',{roles:['BOT_ADMIN'],permissions:[],siteIds:['site']});const policy=await f.configure(),result=await f.invoke('digest.preview',{policyId:policy.id});for(const key of ['crews','tasks','time','travel','materials','shortages','leads','decisions'])expect(result.sections[key]).toEqual({status:'UNAVAILABLE',reason:'CURRENT_CAPABILITY_UNAVAILABLE'});});
 it('site scopes never include unbound rows or rows at other sites, even for an owner with company scope',async()=>{const f=await fixture();await f.update('user','owner',{permissions:['notifications.manage','dispatch.read','dispatch.manage','lead.read','lead.manage','scope.company']});const unbound=await f.tx.add('lead',{status:'NEW',contact:{email:'UNBOUND_PRIVATE_CANARY'}},'unbound');f.tx.rows.set('lead:unbound',{...unbound,createdAt:'2026-03-29T12:00:00Z'});const policy=await f.configure(),result=await f.invoke('digest.preview',{policyId:policy.id});expect(result.sections.leads.count).toBe(1);expect(result.sections.tasks.counts.accepted).toBe(1);expect(JSON.stringify(result)).not.toContain('unbound');});
 it('closed site/current-customer scopes reject outside configuration and global empty scope requires explicit company authority',async()=>{const f=await fixture();for(const scope of [{siteIds:['outside'],customerIds:[]},{siteIds:[],customerIds:[]},{siteIds:['site'],customerIds:['other-customer']}])await expect(f.configure({scope})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.tx.list('digest_policy')).toEqual([]);});
 it('cannot assign another human recipient or accept external/service owners despite manually retained rights',async()=>{const f=await fixture();await expect(f.configure({ownerId:'another-owner'})).rejects.toMatchObject({code:'ACCESS_DENIED'});for(const roles of [['CLIENT','INTERNAL_BAULEITER'],['SERVICE_ACCOUNT']]){await f.update('user','owner',{roles,permissions:['notifications.manage','scope.company']});await expect(f.configure()).rejects.toMatchObject({code:'ACCESS_DENIED'});}expect(await f.tx.list('digest_policy')).toEqual([]);});
 it('generation calls canonical notification scheduling in the same transaction and exact local slot deduplicates retries',async()=>{const f=await fixture(),policy=await f.configure(),first=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1}),before=f.snapshot(),second=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1});expect(second.id).toBe(first.id);expect(f.snapshot()).toEqual(before);expect(first.data).toMatchObject({ownerId:'owner',recipientId:'owner',policyVersion:1,immutable:true,deliveryStatus:'QUEUED'});expect(first.data.sha256).toBe(operationsDigestHash(first.data.snapshot));const notifications=await f.tx.list('notification');expect(notifications).toHaveLength(1);expect(notifications[0]!.data).toMatchObject({recipient_id:'owner',event:'OPERATIONS_DIGEST_READY',related_kind:'operations_digest',related_id:first.id,channel:'WEB',status:'PENDING'});expect(f.tx.events.filter(event=>event.type==='notification.scheduled')).toHaveLength(1);expect(f.tx.events.some(event=>event.type.startsWith('payroll.'))).toBe(false);});
 it('capability loss blocks reading/replaying an immutable captured digest while exposing only unavailable sections in a fresh preview',async()=>{const f=await fixture(),policy=await f.configure(),digest=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1});expect(await operationsDigestVisible(f.tx,await f.actor(),digest,f.host)).toBe(true);await f.update('user','owner',{roles:['DEVELOPER_SUPPORT'],permissions:['notifications.manage'],siteIds:['site']});expect(await operationsDigestVisible(f.tx,await f.actor(),digest,f.host)).toBe(false);const before=f.snapshot();await expect(f.invoke('digest.generate',{policyId:policy.id,policyVersion:1})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(f.snapshot()).toEqual(before);const preview=await f.invoke('digest.preview',{policyId:policy.id});expect(preview.sections.time.status).toBe('UNAVAILABLE');});
 it('policy edits and captured source revisions prevent stale copies from becoming readable or replayed',async()=>{const f=await fixture(),policy=await f.configure(),digest=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1});await f.update('task','task-area',{acceptedQuantityMilli:1100});expect(await operationsDigestVisible(f.tx,await f.actor(),digest,f.host)).toBe(false);await expect(f.invoke('digest.generate',{policyId:policy.id,policyVersion:1})).rejects.toMatchObject({code:'ACCESS_DENIED'});const revised=await f.configure({id:policy.id,name:'Revised review'});expect(revised.version).toBe(2);await expect(f.invoke('digest.generate',{policyId:policy.id,policyVersion:1})).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(await operationsDigestVisible(f.tx,await f.actor(),digest,f.host)).toBe(false);});
 it('other recipients, disabled owner, or forged snapshot checksum cannot read a generated digest',async()=>{const f=await fixture(),policy=await f.configure(),digest=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1}),other=await f.host.actorIn(f.tx,'another-owner');expect(await operationsDigestVisible(f.tx,other,digest,f.host)).toBe(false);await f.update('operations_digest',digest.id,{sha256:'0'.repeat(64)});expect(await operationsDigestVisible(f.tx,await f.actor(),await f.tx.get('operations_digest',digest.id),f.host)).toBe(false);await f.update('user','owner',{active:false});expect(await operationsDigestVisible(f.tx,{...other,userId:'owner'},await f.tx.get('operations_digest',digest.id),f.host)).toBe(false);});
 it('a canonical notification failure rolls back the new immutable digest in the explicit CPU transaction fixture',async()=>{const f=await fixture(),policy=await f.configure(),before=f.snapshot(),scheduler=f.host.registry['notifications.schedule']!;f.host.registry['notifications.schedule']={...scheduler,handler:async()=>{throw new DomainError('ACCESS_DENIED');}};await expect(f.invoke('digest.generate',{policyId:policy.id,policyVersion:1})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(f.snapshot()).toEqual(before);});
 it('preview/generation obey bounded dates, activation, exact schedule and current policy version',async()=>{const f=await fixture(),policy=await f.configure();await expect(f.invoke('digest.preview',{policyId:policy.id,at:'2026-04-01T00:00:00Z'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});await expect(f.invoke('digest.generate',{policyId:policy.id,policyVersion:1,slotAt:'2026-03-30T06:01:00Z'})).rejects.toMatchObject({code:'NOT_DUE'});await expect(f.invoke('digest.generate',{policyId:policy.id,policyVersion:1,slotAt:'2026-03-01T07:00:00Z'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});const notDue=await f.configure({activeFrom:NOW});expect((await f.invoke('digest.preview',{policyId:notDue.id})).scheduledSlot).toBe(false);await expect(f.invoke('digest.generate',{policyId:notDue.id,policyVersion:1})).rejects.toMatchObject({code:'NOT_DUE'});});
 it('bounded daily/weekly kinds reject unsupported cron before writes',async()=>{const f=await fixture();for(const patch of [{cron:'* * * * *'},{cron:'0 8 * * 9'},{kind:'WEEK',cron:'0 8 * * *'},{kind:'DAY',cron:'0 8 * * 1'}])await expect(f.configure(patch)).rejects.toThrow();expect(await f.tx.list('digest_policy')).toEqual([]);});
 it('scope-bound approved intervals are counted once when identical approved snapshots are duplicated',async()=>{const f=await fixture(),sheet=await f.tx.get('timesheet','sheet');await f.tx.add('timesheet',sheet.data,'duplicate');const policy=await f.configure(),preview=await f.invoke('digest.preview',{policyId:policy.id});expect(preview.sections.time.approvedSeconds).toBe(9300);});
 it('WHATSAPP requires private DIRECT ownership/current consent/approved window or template and a real configured HTTPS origin',async()=>{const f=await fixture();await f.tx.add('channel',{type:'DIRECT',created_by:'owner',members:[{user_id:'owner',history_from:'2026-01-01T00:00:00Z'},{user_id:'service',history_from:'2026-01-01T00:00:00Z'}]},'private');await expect(f.configure({channel:'WHATSAPP',channelId:'private'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});await f.tx.add('notification_setting',{user_id:'owner',language:'DE',whatsapp_consent:true,last_inbound_at:NOW},'settings');vi.stubEnv('PUBLIC_ORIGIN','http://example.invalid');await expect(f.configure({channel:'WHATSAPP',channelId:'private'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});expect(await f.tx.list('digest_policy')).toEqual([]);});
 it('configured WhatsApp creates a canonical private link message and notification, never copying digest amounts or business text',async()=>{const f=await fixture();vi.stubEnv('PUBLIC_ORIGIN','https://example.invalid');await f.tx.add('notification_setting',{user_id:'owner',language:'UK',whatsapp_consent:true,last_inbound_at:NOW},'settings');await f.tx.add('channel',{type:'DIRECT',created_by:'owner',members:[{user_id:'owner',history_from:'2026-01-01T00:00:00Z'},{user_id:'service',history_from:'2026-01-01T00:00:00Z'}]},'private');const policy=await f.configure({channel:'WHATSAPP',channelId:'private'}),digest=await f.invoke('digest.generate',{policyId:policy.id,policyVersion:1});const message=(await f.tx.list('message'))[0]!,notification=(await f.tx.list('notification'))[0]!;expect(message.data.language).toBe('UK');expect(message.data.text).toContain(`https://example.invalid/console?digest=${digest.id}`);expect(message.data.text).not.toContain('12000');expect(message.data.text).not.toContain('PRIVATE_');expect(notification.data).toMatchObject({channel:'WHATSAPP',message_id:message.id,related_kind:'operations_digest',related_id:digest.id,status:'PENDING'});expect(notification.data.status).not.toBe('SUCCEEDED');});
 it('WhatsApp refuses another human, external member or revoked owner membership without creating private copied messages',async()=>{const f=await fixture();vi.stubEnv('PUBLIC_ORIGIN','https://example.invalid');await f.tx.add('notification_setting',{user_id:'owner',whatsapp_consent:true,last_inbound_at:NOW},'settings');for(const members of [[{user_id:'owner'},{user_id:'another-owner'}],[{user_id:'owner',external:true},{user_id:'service'}],[{user_id:'owner',revoked_at:NOW},{user_id:'service'}]]){const channel=await f.tx.add('channel',{type:'DIRECT',members});await expect(f.configure({channel:'WHATSAPP',channelId:channel.id})).rejects.toMatchObject({code:'ACCESS_DENIED'});}expect(await f.tx.list('message')).toEqual([]);expect(await f.tx.list('digest_policy')).toEqual([]);});
});

describe('pure Berlin digest schedule/period boundaries',()=>{
 function policy(kind:string,cron:string):Entity{return {id:'policy',kind:'digest_policy',companyId:'synthetic',version:1,createdAt:NOW,updatedAt:NOW,data:{name:'Synthetic',kind,cron,ownerId:'owner',scope:{siteIds:['site'],customerIds:[]},activeFrom:'2025-01-01T00:00:00Z',enabled:true,policyVersion:1,createdBy:'owner',configuredAt:NOW}};}
 it('matches current daily/weekly Berlin minutes with ordinary persisted metadata',()=>{expect(policyDue(policy('MORNING','0 8 * * *'),new Date('2026-03-30T06:00:32Z'))?.slotKey).toBe('2026-03-30:08:00');expect(policyDue(policy('WEEK','0 8 * * 1'),new Date('2026-03-31T06:00:00Z'))).toBeNull();expect(policyDue(policy('MORNING','0 8 * * *'),new Date('2026-03-30T06:01:00Z'))).toBeNull();});
 it('midnight day summary means previous complete day and fall day has25actual hours',()=>{const slot=digestSlot(policy('DAY','0 0 * * *'),new Date('2025-10-26T23:00:00Z'));expect(Date.parse(slot.periodEnd)-Date.parse(slot.periodStart)).toBe(25*3600000);expect(berlinDigestMidnight('2025-10-26')).toBe('2025-10-25T22:00:00.000Z');});
 it('DAY afternoon uses currentlocalday→scheduledcutoff while weekly delivery onWednesday still covers previouscomplete calendarweek',()=>{const day=digestSlot(policy('DAY','0 18 * * *'),new Date('2026-03-30T16:00:00Z'));expect(day.periodStart).toBe('2026-03-29T22:00:00.000Z');expect(day.periodEnd).toBe('2026-03-30T16:00:00.000Z');const week=digestSlot(policy('WEEK','0 18 * * 3'),new Date('2026-04-01T16:00:00Z'));expect(week.periodStart).toBe('2026-03-22T23:00:00.000Z');expect(week.periodEnd).toBe('2026-03-29T22:00:00.000Z');});
 it('DST overlap has one local slot and missing spring scheduledhour is skipped by latestdue resolver',()=>{const repeat=policy('MORNING','30 2 * * *');expect(policyDue(repeat,new Date('2025-10-26T00:30:00Z'))?.slotKey).toBe(policyDue(repeat,new Date('2025-10-26T01:30:00Z'))?.slotKey);expect(latestDigestSlot(repeat,new Date('2026-03-29T03:00:00Z'))?.localDate).toBe('2026-03-28');});
 it('does not reconstruct a pre-activation occurrence or infer tracking authorization from a schedule',()=>{const record=policy('MORNING','0 8 * * *');record.data.activeFrom='2026-03-30T06:00:01Z';expect(policyDue(record,new Date('2026-03-30T06:00:30Z'))).toBeNull();expect(latestDigestSlot(record,new Date('2026-03-30T06:15:00Z'))).toBeNull();expect(JSON.stringify(digestSlot(record,new Date(NOW)))).not.toContain('GPS');});
});
