import { describe, expect, it, afterEach, vi } from 'vitest';
import { effectiveTimesheet, operationsCommands } from '../packages/domain/operations.ts';
import { Actor, CommandContext, Data, DomainError, Entity, Transaction, ownScope, siteScope } from '../packages/domain/core.ts';
import { Engine } from '../apps/api/engine.ts';
import { type Database, type PgTransaction } from '../apps/api/database.ts';

class OperationsTransaction implements Transaction {
  rows = new Map<string, Entity>(); events: { type: string; data: Data }[] = []; sequence = 0;
  async get<T extends Data = Data>(kind: string, id: string): Promise<Entity<T>> { const e = this.rows.get(`${kind}:${id}`); if (!e || e.companyId !== 'company') throw new DomainError('NOT_FOUND_SAFE'); return structuredClone(e) as Entity<T>; }
  async list<T extends Data = Data>(kind: string): Promise<Entity<T>[]> { return [...this.rows.values()].filter(e => e.kind === kind && e.companyId === 'company').map(e => structuredClone(e)) as Entity<T>[]; }
  async add<T extends Data = Data>(kind: string, data: T, id = `${kind}_${++this.sequence}`): Promise<Entity<T>> { if (this.rows.has(`${kind}:${id}`)) throw new DomainError('VERSION_CONFLICT'); const e = { id, companyId: 'company', kind, data: structuredClone(data), version: 1, createdAt: '2026-10-05T08:00:00.000Z', updatedAt: '2026-10-05T08:00:00.000Z' }; this.rows.set(`${kind}:${id}`, e); return structuredClone(e); }
  async save<T extends Data = Data>(entity: Entity<T>, data: T, expectedVersion = entity.version): Promise<Entity<T>> { const current = await this.get<T>(entity.kind, entity.id); if (current.version !== expectedVersion) throw new DomainError('VERSION_CONFLICT'); const result = { ...current, data: structuredClone(data), version: current.version + 1 }; this.rows.set(`${entity.kind}:${entity.id}`, result); return structuredClone(result); }
  async event(type: string, data: Data): Promise<void> { this.events.push({ type, data: structuredClone(data) }); }
}
const owner: Actor = { userId: 'owner', companyId: 'company', roles: ['OWNER'], permissions: ['*'], siteIds: [], warehouseIds: [], customerIds: [], mfaVerified: true };
const worker: Actor = { ...owner, userId: 'worker', roles: ['EMPLOYEE'], siteIds: ['A', 'B'], permissions: ['shift.manage', 'task.work'] };
function context(tx: OperationsTransaction, actor = worker, now = '2026-10-05T16:00:00.000Z'): CommandContext { return { tx, actor, now, idempotencyKey: `synthetic-${++tx.sequence}`, requireSite: s => siteScope(actor, s), requireOwn: u => ownScope(actor, u) }; }
async function run(tx: OperationsTransaction, name: string, input: Data, actor = worker, now?: string): Promise<any> { const def = operationsCommands[name]!; return def.handler(context(tx, actor, now), def.schema.parse(input)); }
async function setup(): Promise<OperationsTransaction> { const tx = new OperationsTransaction(); await tx.add('company', { operatingMode: 'TEST' }, 'company'); for (const siteId of ['A', 'B']) await tx.add('site', { code: siteId, name: `Synthetic Site ${siteId}`, address: 'Synthetic address', active: true, revision: 1 }, siteId); for (const employeeId of ['worker', 'second', 'third', 'owner']) await tx.add('user', { active: true, siteIds: ['A', 'B'], roles: employeeId === 'owner' ? ['OWNER'] : ['EMPLOYEE'] }, employeeId); return tx; }
async function gpsSetup(tx: OperationsTransaction): Promise<{ policy: Entity; device: Entity; s: Entity }> { const policy = await tx.add('tracking_policy', { state: 'APPROVED', enabled: true, revision: 1, allowPresence: true, allowBusinessRoute: true, allowMinimalReturn: true, retentionDays: 7, maxSessionHours: 12, expiresAt: '2027-01-01T00:00:00.000Z', approvedAt: '2026-10-01T00:00:00.000Z', legalApprovalReference: 'SYNTHETIC_TEST_ONLY' }); const device = await tx.add('device', { employeeId: 'worker', active: true, platform: 'ANDROID' }); await run(tx, 'geofence.configure', { siteId: 'A', latitude: 52.52, longitude: 13.4, radiusEnterM: 150, radiusExitM: 200, dwellSeconds: 120, maxAccuracyM: 50, maxPointAgeSeconds: 300, autoPause: true, autoReturn: true }, owner); const s = await run(tx, 'shift.start', { siteId: 'A', deviceId: device.id, occurredAt: '2026-10-05T08:00:00.000Z' }); return { policy, device, s }; }
async function presence(tx: OperationsTransaction, g: { policy: Entity; device: Entity; s: Entity }, at: string, distanceM: number, sequence: number, accuracyM: number | undefined = 5): Promise<any> { return run(tx, 'presence.ingest', { eventId: `synthetic-event-${sequence}`, deviceId: g.device.id, shiftId: g.s.id, siteId: 'A', sequenceNumber: sequence, observedAt: at, distanceM, accuracyM, source: 'NATIVE_LOCATION', policyVersionId: g.policy.id }, worker, at); }

describe('operations exact interval arithmetic and approval controls', () => {
  it('acceptance day preserves eight hours, seven site hours, travel/break half hours, paid travel separately', async () => { const tx = await setup(); const s = await run(tx, 'shift.start', { siteId: 'A', occurredAt: '2026-10-05T08:00:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'ON_BREAK', occurredAt: '2026-10-05T12:00:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'WAITING_WORK', siteId: 'A', occurredAt: '2026-10-05T12:30:00Z' }); const trip = await run(tx, 'trip.start', { shiftId: s.id, destination: { kind: 'SITE', id: 'B' }, purpose: 'Synthetic business transfer', occurredAt: '2026-10-05T12:30:00Z' }); await run(tx, 'trip.arrive', { tripId: trip.id, occurredAt: '2026-10-05T13:00:00Z', startWork: true }); await run(tx, 'shift.end', { shiftId: s.id, occurredAt: '2026-10-05T16:00:00Z' }); const totals = await run(tx, 'shift.summary', { shiftId: s.id }); expect(totals).toMatchObject({ totalSeconds: 28800, workSeconds: 25200, travelSeconds: 1800, breakSeconds: 1800, pendingSeconds: 0 }); const sheet = await run(tx, 'timesheet.submit', { periodStart: '2026-10-05T00:00:00Z', periodEnd: '2026-10-05T16:00:00Z' }); const approved = await run(tx, 'timesheet.review', { timesheetId: sheet.id, decision: 'APPROVE', paidActivities: ['WORKING', 'TRAVELLING'] }, owner); expect(approved.data).toMatchObject({ payableSeconds: 27000, totalMinutes: 450, state: 'APPROVED' }); expect(approved.data.segmentSnapshot.reduce((sum: number, s: Data) => sum + s.seconds, 0)).toBe(28800); });
  it('full geo-day retains five unexplained minutes, rather than losing them or charging payroll automatically', async () => { const tx = await setup(); const s = await run(tx, 'shift.start', { siteId: 'A', occurredAt: '2026-10-05T08:00:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'AWAY_PENDING_REASON', siteId: 'A', occurredAt: '2026-10-05T10:00:00Z', reason: 'Synthetic geofence event' }); const trip = await run(tx, 'trip.start', { shiftId: s.id, destination: { kind: 'SITE', id: 'B' }, purpose: 'Synthetic transfer', occurredAt: '2026-10-05T10:05:00Z' }); await run(tx, 'trip.arrive', { tripId: trip.id, occurredAt: '2026-10-05T10:35:00Z', startWork: true }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'ON_BREAK', occurredAt: '2026-10-05T12:30:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'WORKING', siteId: 'B', occurredAt: '2026-10-05T13:00:00Z' }); await run(tx, 'shift.end', { shiftId: s.id, occurredAt: '2026-10-05T16:00:00Z' }); expect(await run(tx, 'shift.summary', { shiftId: s.id })).toMatchObject({ totalSeconds: 28800, workSeconds: 24900, pendingSeconds: 300, travelSeconds: 1800, breakSeconds: 1800 }); const sheet = await run(tx, 'timesheet.submit', { periodStart: '2026-10-05T00:00:00Z', periodEnd: '2026-10-05T16:00:00Z' }); const approved = await run(tx, 'timesheet.review', { timesheetId: sheet.id, decision: 'APPROVE', paidActivities: ['WORKING', 'TRAVELLING'], reason: 'Synthetic policy excludes pending until decision' }, owner); expect(approved.data.payableSeconds).toBe(26700); expect(approved.data.pendingSecondsPayability).toBe('EXPLICIT_HUMAN_POLICY'); });
  it('repeat start, historical overlap, out-of-order event, foreign shift and self approval are denied', async () => { const tx = await setup(); const s = await run(tx, 'shift.start', { siteId: 'A', occurredAt: '2026-10-05T08:00:00Z' }); await expect(run(tx, 'shift.start', { siteId: 'A' })).rejects.toMatchObject({ code: 'INVALID_STATE' }); await expect(run(tx, 'shift.activity', { shiftId: s.id, activity: 'ON_BREAK', occurredAt: '2026-10-05T07:59:00Z' })).rejects.toMatchObject({ code: 'INVALID_STATE' }); await expect(run(tx, 'shift.end', { shiftId: s.id }, { ...worker, userId: 'second' })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); await run(tx, 'shift.end', { shiftId: s.id }); await expect(run(tx, 'shift.start', { siteId: 'A', occurredAt: '2026-10-05T07:00:00Z' })).rejects.toMatchObject({ code: 'INVALID_STATE' }); const t = await run(tx, 'timesheet.submit', { periodStart: '2026-10-05T00:00:00Z', periodEnd: '2026-10-05T16:00:00Z' }); await expect(run(tx, 'timesheet.review', { timesheetId: t.id, decision: 'APPROVE' })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); expect(await tx.list('shift')).toHaveLength(1); });
  it.each([['spring', '2026-03-29T01:30:00+01:00', '2026-03-29T03:30:00+02:00', 3600], ['autumn', '2026-10-25T02:30:00+02:00', '2026-10-25T02:30:00+01:00', 3600], ['night-month', '2026-10-31T23:00:00+01:00', '2026-11-01T03:00:00+01:00', 14400]] as const)('UTC arithmetic handles %s without wall clock errors', async (_name, start, end, expected) => { const tx = await setup(); const s = await run(tx, 'shift.start', { siteId: 'A', occurredAt: start }, worker, '2026-11-02T00:00:00Z'); await run(tx, 'shift.end', { shiftId: s.id, occurredAt: end }, worker, '2026-11-02T00:00:00Z'); expect((await run(tx, 'shift.summary', { shiftId: s.id }, worker, '2026-11-02T00:00:00Z')).totalSeconds).toBe(expected); });
  it('closed-period correction creates a separate approved adjustment and keeps locked snapshot intact', async () => { const tx = await setup(); const s = await run(tx, 'shift.start', { siteId: 'A', occurredAt: '2026-10-05T08:00:00Z' }); await run(tx, 'shift.end', { shiftId: s.id, occurredAt: '2026-10-05T10:00:00Z' }); const sheet = await run(tx, 'timesheet.submit', { periodStart: '2026-10-05T00:00:00Z', periodEnd: '2026-10-05T16:00:00Z' }); await run(tx, 'timesheet.review', { timesheetId: sheet.id, decision: 'APPROVE' }, owner); const locked = await run(tx, 'timesheet.lock', { timesheetId: sheet.id }, owner); const c = await run(tx, 'timesheet.correction', { timesheetId: sheet.id, segmentId: locked.data.segmentSnapshot[0].id, activity: 'ON_BREAK', reason: 'Synthetic forgotten personal interval correction' }); await expect(run(tx, 'timesheet.correction.review', { correctionId: c.id, decision: 'APPROVE', reason: 'Self approval attempt' })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); await run(tx, 'timesheet.correction.review', { correctionId: c.id, decision: 'APPROVE', reason: 'Supervisor verified correction' }, owner); expect((await tx.get('timesheet', sheet.id)).data).toEqual(locked.data); expect((await tx.list('timesheet_adjustment'))[0]!.data.deltaPayableSeconds).toBe(-7200); expect((await tx.list('time_segment'))[0]!.data.activity).toBe('WORKING'); });
  it('coordinated correction moves a lunch boundary without losing time and closed corrections compute deltas against effective history', async () => { const tx = await setup(); const s = await run(tx, 'shift.start', { siteId: 'A', occurredAt: '2026-10-05T08:00:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'ON_BREAK', occurredAt: '2026-10-05T09:00:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'WORKING', siteId: 'A', occurredAt: '2026-10-05T09:30:00Z' }); await run(tx, 'shift.end', { shiftId: s.id, occurredAt: '2026-10-05T10:00:00Z' }); const sheet = await run(tx, 'timesheet.submit', { periodStart: '2026-10-05T00:00:00Z', periodEnd: '2026-10-05T16:00:00Z' }); await run(tx, 'timesheet.review', { timesheetId: sheet.id, decision: 'APPROVE' }, owner); const first = sheet.data.segmentSnapshot[0], lunch = sheet.data.segmentSnapshot[1]; const correction = await run(tx, 'timesheet.correction.bulk', { timesheetId: sheet.id, reason: 'Synthetic lunch actually started ten minutes sooner', changes: [{ segmentId: first.id, endAt: '2026-10-05T08:50:00Z' }, { segmentId: lunch.id, startAt: '2026-10-05T08:50:00Z' }] }); await run(tx, 'timesheet.correction.review', { correctionId: correction.id, decision: 'APPROVE', reason: 'Supervisor accepted source evidence' }, owner); expect((await tx.list('timesheet_adjustment'))[0]!.data.deltaPayableSeconds).toBe(-600); const revert = await run(tx, 'timesheet.correction.bulk', { timesheetId: sheet.id, reason: 'Synthetic subsequent verified correction', changes: [{ segmentId: first.id, endAt: '2026-10-05T09:00:00Z' }, { segmentId: lunch.id, startAt: '2026-10-05T09:00:00Z' }] }); await run(tx, 'timesheet.correction.review', { correctionId: revert.id, decision: 'APPROVE', reason: 'Supervisor verified latest evidence' }, owner); expect((await tx.list('timesheet_adjustment')).map(a => a.data.deltaPayableSeconds)).toEqual([-600, 600]); expect((await tx.get('timesheet', sheet.id)).data.payableSeconds).toBe(5400); });
  it('coordinated boundary correction preserves the whole chronology and computes only its new delta', async () => { const tx = await setup(); const s = await run(tx, 'shift.start', { siteId: 'A', occurredAt: '2026-10-05T08:00:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'ON_BREAK', occurredAt: '2026-10-05T09:00:00Z' }); await run(tx, 'shift.activity', { shiftId: s.id, activity: 'WORKING', siteId: 'A', occurredAt: '2026-10-05T09:30:00Z' }); await run(tx, 'shift.end', { shiftId: s.id, occurredAt: '2026-10-05T10:00:00Z' }); const t = await run(tx, 'timesheet.submit', { periodStart: '2026-10-05T00:00:00Z', periodEnd: '2026-10-05T16:00:00Z' }); await run(tx, 'timesheet.review', { timesheetId: t.id, decision: 'APPROVE' }, owner); const locked = await run(tx, 'timesheet.lock', { timesheetId: t.id }, owner); const first = locked.data.segmentSnapshot[0], second = locked.data.segmentSnapshot[1]; await expect(run(tx, 'timesheet.correction', { timesheetId: t.id, segmentId: first.id, endAt: '2026-10-05T09:10:00Z', reason: 'Invalid isolated boundary' })).rejects.toMatchObject({ code: 'INVALID_STATE' }); const c = await run(tx, 'timesheet.correction.bulk', { timesheetId: t.id, reason: 'Synthetic supervisor-verified lunch began ten minutes later', changes: [{ segmentId: first.id, endAt: '2026-10-05T09:10:00Z' }, { segmentId: second.id, startAt: '2026-10-05T09:10:00Z' }] }); await run(tx, 'timesheet.correction.review', { correctionId: c.id, decision: 'APPROVE', reason: 'Matched original worker facts' }, owner); expect((await tx.list('timesheet_adjustment'))[0]!.data.deltaPayableSeconds).toBe(600); const effective = await effectiveTimesheet(context(tx, owner), locked); expect(effective.reduce((sum, s) => sum + s.seconds, 0)).toBe(7200); expect(effective[0]!.endAt).toBe('2026-10-05T09:10:00.000Z'); await expect(run(tx, 'timesheet.correction', { timesheetId: t.id, segmentId: first.id, endAt: '2026-10-05T09:10:00Z', reason: 'Duplicate correction already reflected' })).rejects.toMatchObject({ code: 'INVALID_STATE' }); });
});

describe('route sample acknowledgement and strict retention',()=>{
  async function fixture(){const tx=await setup(),g=await gpsSetup(tx),trip=await run(tx,'trip.start',{shiftId:g.s.id,destination:{kind:'SITE',id:'B'},purpose:'Synthetic approved business route',occurredAt:'2026-10-05T10:00:00Z'});const input={eventId:'synthetic-gps-retention',deviceId:g.device.id,shiftId:g.s.id,tripId:trip.id,sequenceNumber:1,observedAt:'2026-10-05T10:05:00Z',latitude:52.520123,longitude:13.400456,accuracyM:6,policyVersionId:g.policy.id};return {tx,g,trip,input};}
  it('returns the same coordinate-free acknowledgement for first acceptance and duplicate event IDs',async()=>{const {tx,input}=await fixture();const first=await run(tx,'trip.sample',input),repeat=await run(tx,'trip.sample',{...input,latitude:52.53,longitude:13.41});expect(first).toEqual({eventId:input.eventId,sampleId:input.eventId,accepted:true,expiresAt:'2026-10-12T10:05:00.000Z'});expect(repeat).toEqual(first);expect(Object.keys(first).sort()).toEqual(['accepted','eventId','expiresAt','sampleId']);expect(JSON.stringify(first)).not.toMatch(/latitude|longitude|accuracy|52\.520123|13\.400456/);const raw=await tx.get('location_sample',first.sampleId);expect(raw.data).toMatchObject({latitude:input.latitude,longitude:input.longitude,accuracyM:6,siteIds:['A','B']});expect(await tx.list('location_sample')).toHaveLength(1);expect(tx.events.some(e=>JSON.stringify(e.data).includes('52.520123'))).toBe(false);});
  it('binds permanent metadata to route origin/destination and event-time segment, excluding unrelated actor sites',async()=>{const {tx,g,input}=await fixture();const broad={...worker,siteIds:['A','B','C','unrelated-site']};await tx.add('site',{active:true,name:'Synthetic intermediate context'},'C');const travel=(await tx.list('time_segment')).find(e=>e.data.tripId===input.tripId)!;await tx.save(travel,{...travel.data,siteId:'C'});const ack=await run(tx,'trip.sample',input,broad);expect((await tx.get('location_sample',ack.sampleId)).data.siteIds).toEqual(['A','B','C']);expect((await tx.get('shift',g.s.id)).data.siteId).toBe('A');expect((await tx.get('location_sample',ack.sampleId)).data.siteIds).not.toContain('unrelated-site');});
  it('deduplicates identical origin/destination/segment sites without storing empty or warehouse IDs',async()=>{const {tx,input,trip}=await fixture();await tx.save(trip,{...trip.data,destination:{kind:'SITE',id:'A'}});const ack=await run(tx,'trip.sample',input);expect((await tx.get('location_sample',ack.sampleId)).data.siteIds).toEqual(['A']);const metadata=await tx.get('location_sample',ack.sampleId);await tx.save(metadata,{...metadata.data,eventId:'separate-event'});await tx.save(await tx.get('trip',trip.id),{...trip.data,origin:{kind:'SITE',id:''},destination:{kind:'WAREHOUSE',id:'not-a-site'}});const next=await run(tx,'trip.sample',{...input,eventId:'synthetic-warehouse-route',sequenceNumber:2});expect((await tx.get('location_sample',next.sampleId)).data.siteIds).toEqual(['A']);});
  it('accepts just before TTL, rejects the exact boundary and prevents an expired metadata tombstone being recreated',async()=>{const {tx,g,trip,input}=await fixture();await run(tx,'trip.arrive',{tripId:trip.id,occurredAt:'2026-10-05T10:30:00Z',startWork:true});await run(tx,'shift.end',{shiftId:g.s.id,occurredAt:'2026-10-05T11:00:00Z'});const before='2026-10-12T10:04:59.999Z',boundary='2026-10-12T10:05:00.000Z';const ack=await run(tx,'trip.sample',input,worker,before);expect(await run(tx,'trip.sample',input,worker,before)).toEqual(ack);await expect(run(tx,'trip.sample',{...input,eventId:'not-created-at-boundary'},worker,boundary)).rejects.toMatchObject({code:'ACCESS_DENIED',details:{reason:'GPS_RETENTION_EXPIRED'}});await expect(run(tx,'trip.sample',input,worker,boundary)).rejects.toMatchObject({code:'ACCESS_DENIED'});const stored=await tx.get('location_sample',input.eventId),{latitude:_latitude,longitude:_longitude,accuracyM:_accuracy,...metadata}=stored.data;await tx.save(stored,metadata);await expect(run(tx,'trip.sample',{...input,observedAt:'2026-10-05T10:06:00Z'},worker,boundary)).rejects.toMatchObject({code:'ACCESS_DENIED',details:{reason:'GPS_RETENTION_EXPIRED'}});expect(await tx.list('location_sample')).toHaveLength(1);expect((await tx.get('location_sample',input.eventId)).data).not.toHaveProperty('latitude');expect((await tx.get('location_sample',input.eventId)).data).not.toHaveProperty('longitude');});
});

describe('location, team quantities, quality and allocations', () => {
  it('explicit floors and acyclic site tree preserve task historical breadcrumb after rename', async () => { const tx = await setup(); const house = await run(tx, 'location.create', { siteId: 'A', nodeType: 'BUILDING', code: 'HA', name: 'Haus A' }, owner); await expect(run(tx, 'location.create', { siteId: 'A', parentId: house.id, nodeType: 'FLOOR', code: 'FIRST', name: 'First floor' }, owner)).rejects.toMatchObject({ code: 'VALIDATION_ERROR' }); const floor = await run(tx, 'location.create', { siteId: 'A', parentId: house.id, nodeType: 'FLOOR', code: '3OG', name: '3. OG', floorLevel: 3, floorLabelDe: '3. OG' }, owner); const t = await run(tx, 'task.create', { siteId: 'A', locationId: floor.id, title: 'Synthetic clean floor', assigneeIds: ['worker'] }, owner); await expect(run(tx, 'location.update', { locationId: house.id, parentId: floor.id }, owner)).rejects.toMatchObject({ code: 'INVALID_STATE' }); await run(tx, 'location.update', { locationId: house.id, name: 'Haus A renamed' }, owner); expect((await tx.get('task', t.id)).data.locationSnapshot[0].name).toBe('Haus A'); expect((await run(tx, 'location.breadcrumb', { locationId: floor.id }, owner)).path[0].name).toBe('Haus A renamed'); });
  it('3 people ×2 hours count 100m² once and six person hours; cannot overallocate a segment', async () => { const tx = await setup(); const t = await run(tx, 'task.create', { siteId: 'A', title: 'Synthetic 100 square meters', unit: 'M2', plannedQuantityMilli: 100000, assigneeIds: ['worker', 'second', 'third'] }, owner); await run(tx, 'task.start', { taskId: t.id }); const log = await run(tx, 'task.worklog', { taskId: t.id, quantityMilli: 100000, description: 'One synthetic team result', groupResultKey: 'team-result-1', employeeIds: ['worker', 'second', 'third'] }); const duplicate = await run(tx, 'task.worklog', { taskId: t.id, quantityMilli: 100000, description: 'Same result second worker sync', groupResultKey: 'team-result-1' }, { ...worker, userId: 'second' }); expect(duplicate.id).toBe(log.id); let total = 0; for (const employeeId of ['worker', 'second', 'third']) { const actor = { ...worker, userId: employeeId }; const s = await run(tx, 'shift.start', { siteId: 'A', taskId: t.id, occurredAt: '2026-10-05T08:00:00Z' }, actor); await run(tx, 'shift.end', { shiftId: s.id, occurredAt: '2026-10-05T10:00:00Z' }, actor); const seg = (await tx.list('time_segment')).find(seg => seg.data.shiftId === s.id)!; await run(tx, 'time.allocate', { segmentId: seg.id, taskId: t.id, worklogId: log.id, seconds: 7200 }, actor); await expect(run(tx, 'time.allocate', { segmentId: seg.id, taskId: t.id, seconds: 1 }, actor)).rejects.toMatchObject({ code: 'INVALID_STATE' }); total += (await run(tx, 'shift.summary', { shiftId: s.id }, actor)).totalSeconds; } expect(total).toBe(21600); expect((await tx.get('task', t.id)).data.reportedQuantityMilli).toBe(100000); await run(tx, 'task.submit', { taskId: t.id }); expect((await tx.get('task', t.id)).data.state).toBe('SUBMITTED_FOR_REVIEW'); await run(tx, 'task.review', { taskId: t.id, decision: 'ACCEPT' }, owner); expect((await run(tx, 'task.progress', { siteId: 'A' }, owner)).byUnit.M2.acceptedQuantityMilli).toBe(100000); });
  it('worker submit is review pending; duplicate defect produces one linked internal rework and preserves primary evidence', async () => { const tx = await setup(); const t = await run(tx, 'task.create', { siteId: 'A', title: 'Synthetic cleaning', assigneeIds: ['worker'] }, owner); await run(tx, 'task.start', { taskId: t.id }); await run(tx, 'task.worklog', { taskId: t.id, quantityMilli: 1000, description: 'Original evidence' }); await run(tx, 'task.submit', { taskId: t.id }); await expect(run(tx, 'task.review', { taskId: t.id, decision: 'ACCEPT' })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); await run(tx, 'task.review', { taskId: t.id, decision: 'ACCEPT' }, owner); const original = await tx.get('task', t.id); const d = await run(tx, 'defect.create', { taskId: t.id, externalKey: 'synthetic-defect-1', description: 'Synthetic dust remains' }, owner); expect((await run(tx, 'defect.create', { taskId: t.id, externalKey: 'synthetic-defect-1', description: 'Duplicate webhook' }, owner)).id).toBe(d.id); const rework = await run(tx, 'defect.rework', { defectId: d.id, assigneeIds: ['worker'], responsibilityDecision: 'Human synthetic decision' }, owner); expect((await run(tx, 'defect.rework', { defectId: d.id, assigneeIds: ['worker'], responsibilityDecision: 'Repeat' }, owner)).id).toBe(rework.id); expect(rework.data).toMatchObject({ completionKind: 'REWORK', sourceTaskId: t.id, billingScope: 'INTERNAL' }); expect((await tx.get('task', t.id)).data).toEqual(original.data); expect(await tx.list('worklog')).toHaveLength(1); expect(await tx.list('rework_link')).toHaveLength(1); });
  it('templates dedupe occurrence by stable key and do not rewrite past accepted results', async () => { const tx = await setup(); const template = await run(tx, 'task_template.create', { name: 'Synthetic regular cleaning', task: { siteId: 'A', title: 'Original template' }, recurrence: 'DAILY' }, owner); const t = await run(tx, 'task_template.occurrence', { templateId: template.id, scheduledPeriod: '2026-10-05', assigneeIds: ['worker'] }, owner); await run(tx, 'task_template.update', { templateId: template.id, task: { siteId: 'A', title: 'Future template' } }, owner); const same = await run(tx, 'task_template.occurrence', { templateId: template.id, scheduledPeriod: '2026-10-05', assigneeIds: ['worker'] }, owner); expect(same.id).toBe(t.id); expect(same.data.title).toBe('Original template'); expect(await tx.list('task_occurrence')).toHaveLength(1); });
  it('one confirmed three-task preview creates three effects across repeated confirms', async () => { const tx = await setup(); const input = { batchKey: 'synthetic-ai-confirm-1', tasks: ['Kitchen', 'Bathroom', 'Corridor'].map(title => ({ siteId: 'A', title })) }; const preview = await run(tx, 'task.bulk.preview', input, owner); expect(await tx.list('task')).toHaveLength(0); const created = await run(tx, 'task.bulk.commit', { ...input, previewHash: preview.previewHash, confirmed: true }, owner); const repeat = await run(tx, 'task.bulk.commit', { ...input, previewHash: preview.previewHash, confirmed: true }, owner); expect(created.map((t: Entity) => t.id)).toEqual(repeat.map((t: Entity) => t.id)); expect(await tx.list('task')).toHaveLength(3); expect(await tx.list('task_batch')).toHaveLength(1); });
  it('rejected result remains in immutable review cycle and final task quantity is not doubled', async () => { const tx = await setup(); const t = await run(tx, 'task.create', { siteId: 'A', title: 'Synthetic cycle result', assigneeIds: ['worker'] }, owner); await run(tx, 'task.start', { taskId: t.id }); await run(tx, 'task.worklog', { taskId: t.id, quantityMilli: 1000, description: 'Original failed cycle' }); await run(tx, 'task.submit', { taskId: t.id }); await run(tx, 'task.review', { taskId: t.id, decision: 'REJECT', reason: 'Synthetic required quality correction' }, owner); await run(tx, 'task.start', { taskId: t.id }); await run(tx, 'task.worklog', { taskId: t.id, quantityMilli: 1000, description: 'Corrected cycle' }); await run(tx, 'task.submit', { taskId: t.id }); const accepted = await run(tx, 'task.review', { taskId: t.id, decision: 'ACCEPT' }, owner); expect(accepted.data.acceptedQuantityMilli).toBe(1000); expect(await tx.list('worklog')).toHaveLength(2); expect((await tx.list('task_review')).map(r => r.data.worklogIds.length)).toEqual([1, 1]); });
  it('bulk import requires exact current preview and repeated stable external keys upsert', async () => { const tx = await setup(); const input = { siteId: 'A', rows: [{ externalKey: 'house', nodeType: 'BUILDING', code: 'HA', name: 'Haus A' }, { externalKey: 'floor', parentExternalKey: 'house', nodeType: 'FLOOR', code: 'EG', name: 'EG', floorLevel: 0, floorLabelDe: 'EG' }] }; const preview = await run(tx, 'location.import.preview', input, owner); expect(preview.errors).toEqual([]); await run(tx, 'location.import.commit', { ...input, previewHash: preview.previewHash, confirmed: true }, owner); await expect(run(tx, 'location.import.commit', { ...input, previewHash: preview.previewHash, confirmed: true }, owner)).rejects.toMatchObject({ code: 'VERSION_CONFLICT' }); const fresh = await run(tx, 'location.import.preview', input, owner); await run(tx, 'location.import.commit', { ...input, previewHash: fresh.previewHash, confirmed: true }, owner); expect(await tx.list('location')).toHaveLength(2); });
  it('site access, revoked assignee and arbitrary schema injection are denied', async () => { const tx = await setup(); await expect(run(tx, 'task.create', { siteId: 'A', title: 'Unauthorized' }, { ...worker, siteIds: [] })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); await tx.save(await tx.get('user', 'second'), { active: false, siteIds: ['A'] }); await expect(run(tx, 'task.create', { siteId: 'A', title: 'Revoked assignee', assigneeIds: ['second'] }, owner)).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); expect(() => operationsCommands['shift.start']!.schema.parse({ siteId: 'A', payrollRate: 999 })).toThrow(); });
});

describe('GPS conservative classification, event-time privacy and explicit trips', () => {
  it('legal gate defaults closed and no coordinates enter presence schema', async () => { const tx = await setup(); const device = await tx.add('device', { employeeId: 'worker', active: true }); const s = await run(tx, 'shift.start', { siteId: 'A', deviceId: device.id }); await expect(run(tx, 'presence.ingest', { eventId: 'e', deviceId: device.id, shiftId: s.id, siteId: 'A', sequenceNumber: 1, observedAt: '2026-10-05T16:00:00Z', source: 'NATIVE_LOCATION', policyVersionId: 'missing' })).rejects.toMatchObject({ code: 'MISSING_CONFIGURATION' }); expect(() => operationsCommands['presence.ingest']!.schema.parse({ latitude: 52.5 })).toThrow(); });
  it('policy activation requires actual legal approval records and MFA; plain references cannot enable GPS', async () => { const tx = await setup(); const p = await run(tx, 'tracking_policy.create', { purpose: 'Synthetic test legal process', retentionDays: 7, accessRoles: ['OPERATIONS_MANAGER'] }, owner); const input = { policyId: p.id, legalApprovalReference: 'legal', necessityApprovalReference: 'necessity', worksCouncilReference: 'council', employeeNoticeReference: 'notice', expiresAt: '2026-11-01T00:00:00Z', enabled: true }; await expect(run(tx, 'tracking_policy.approve', input, { ...owner, mfaVerified: false })).rejects.toMatchObject({ code: 'NEEDS_REAUTH' }); await expect(run(tx, 'tracking_policy.approve', input, owner)).rejects.toMatchObject({ code: 'NOT_FOUND_SAFE' }); expect((await tx.get('tracking_policy', p.id)).data.enabled).toBe(false); for (const [approvalId, subject] of [['legal', 'GPS_LEGAL_PROCESS'], ['necessity', 'GPS_NECESSITY'], ['council', 'GPS_WORKS_COUNCIL'], ['notice', 'GPS_EMPLOYEE_NOTICE']]) await tx.add('legal_approval', { status: 'APPROVED', active: true, subject, testOnly: true, expiresAt: '2026-12-01T00:00:00Z' }, approvalId); expect((await run(tx, 'tracking_policy.approve', input, owner)).data.state).toBe('APPROVED'); });
  it('device enrollment is one-use and binding a new tracker revokes old access', async () => { const tx = await setup(); const enroll = await run(tx, 'device.enroll', { employeeId: 'worker' }, owner); const old = await run(tx, 'device.bind', { enrollmentId: enroll.enrollmentId, token: enroll.token, platform: 'ANDROID', deviceName: 'Synthetic test phone', publicKey: 'synthetic-public-key-000001' }); await expect(run(tx, 'device.bind', { enrollmentId: enroll.enrollmentId, token: enroll.token, platform: 'ANDROID', deviceName: 'Replay', publicKey: 'synthetic-public-key-000001' })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); const next = await run(tx, 'device.enroll', { employeeId: 'worker' }, owner); const device = await run(tx, 'device.bind', { enrollmentId: next.enrollmentId, token: next.token, platform: 'IOS', deviceName: 'Synthetic replacement', publicKey: 'synthetic-public-key-000002' }); expect(device.data.active).toBe(true); expect((await tx.get('device', old.id)).data.active).toBe(false); });
  it('inaccurate border and one distant point cannot pause; stable dwell produces one visible pending interval', async () => { const tx = await setup(); const g = await gpsSetup(tx); await presence(tx, g, '2026-10-05T09:00:00Z', 210, 1, 100); expect((await tx.get('shift', g.s.id)).data.activity).toBe('WORKING'); await presence(tx, g, '2026-10-05T09:10:00Z', 300, 2); expect((await tx.get('shift', g.s.id)).data.activity).toBe('WORKING'); await presence(tx, g, '2026-10-05T09:12:00Z', 300, 3); expect((await tx.get('shift', g.s.id)).data.activity).toBe('AWAY_PENDING_REASON'); await presence(tx, g, '2026-10-05T09:13:00Z', 300, 4); expect((await tx.list('time_segment')).filter(s => s.data.activity === 'AWAY_PENDING_REASON')).toHaveLength(1); await run(tx, 'shift.end', { shiftId: g.s.id, occurredAt: '2026-10-05T10:00:00Z' }); const totals = await run(tx, 'shift.summary', { shiftId: g.s.id }); expect(totals).toMatchObject({ totalSeconds: 7200, workSeconds: 4320, pendingSeconds: 2880 }); });
  it('late/reordered events do not rewrite history and missing GPS means unknown without pause', async () => { const tx = await setup(); const g = await gpsSetup(tx); await presence(tx, g, '2026-10-05T09:00:00Z', 20, 3); await presence(tx, g, '2026-10-05T09:02:00Z', 20, 4); const late = await presence(tx, g, '2026-10-05T08:50:00Z', 400, 2); expect(late.data.late).toBe(true); const unknown = await run(tx, 'presence.ingest', { eventId: 'unknown-event', deviceId: g.device.id, shiftId: g.s.id, siteId: 'A', sequenceNumber: 5, observedAt: '2026-10-05T09:03:00Z', source: 'NATIVE_GEOFENCE', trackerState: 'PERMISSION_DENIED', policyVersionId: g.policy.id }, worker, '2026-10-05T09:03:00Z'); expect(unknown.presence.data.state).toBe('UNKNOWN'); expect((await tx.get('shift', g.s.id)).data.activity).toBe('WORKING'); });
  it('ENTER restores only matching geopause; manual lunch remains manual and rejects late private events', async () => { const tx = await setup(); const g = await gpsSetup(tx); await presence(tx, g, '2026-10-05T09:00:00Z', 400, 1); await presence(tx, g, '2026-10-05T09:02:00Z', 400, 2); await presence(tx, g, '2026-10-05T09:10:00Z', 20, 3); await presence(tx, g, '2026-10-05T09:12:00Z', 20, 4); expect((await tx.get('shift', g.s.id)).data.activity).toBe('WORKING'); await run(tx, 'shift.activity', { shiftId: g.s.id, activity: 'ON_BREAK', occurredAt: '2026-10-05T09:15:00Z' }); await expect(presence(tx, g, '2026-10-05T09:20:00Z', 20, 5)).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); expect((await tx.get('shift', g.s.id)).data.activity).toBe('ON_BREAK'); });
  it('permitted late travel sample survives END; private stop and post-END points are rejected by event time', async () => { const tx = await setup(); const g = await gpsSetup(tx); const trip = await run(tx, 'trip.start', { shiftId: g.s.id, destination: { kind: 'SITE', id: 'B' }, purpose: 'Synthetic legal travel', occurredAt: '2026-10-05T10:00:00Z' }); await run(tx, 'trip.stop', { tripId: trip.id, kind: 'PRIVATE_BREAK', reason: 'Synthetic lunch', occurredAt: '2026-10-05T10:10:00Z' }); await run(tx, 'trip.resume', { tripId: trip.id, occurredAt: '2026-10-05T10:20:00Z' }); await run(tx, 'trip.arrive', { tripId: trip.id, occurredAt: '2026-10-05T10:30:00Z', startWork: true }); await run(tx, 'shift.end', { shiftId: g.s.id, occurredAt: '2026-10-05T11:00:00Z' }); const base = { deviceId: g.device.id, shiftId: g.s.id, tripId: trip.id, latitude: 52.52, longitude: 13.4, accuracyM: 5, policyVersionId: g.policy.id }; await expect(run(tx, 'trip.sample', { ...base, eventId: 'private', sequenceNumber: 2, observedAt: '2026-10-05T10:15:00Z' })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); await expect(run(tx, 'trip.sample', { ...base, eventId: 'after-end', sequenceNumber: 3, observedAt: '2026-10-05T11:01:00Z' })).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); const sample = await run(tx, 'trip.sample', { ...base, eventId: 'lawful-late', sequenceNumber: 1, observedAt: '2026-10-05T10:05:00Z' }); expect(sample).toEqual({eventId:'lawful-late',sampleId:'lawful-late',accepted:true,expiresAt:'2026-10-12T10:05:00.000Z'});expect((await tx.get('location_sample',sample.sampleId)).data.mode).toBe('BUSINESS_TRAVEL'); expect(await tx.list('location_sample')).toHaveLength(1); expect((await tx.get('trip', trip.id)).data.distanceMeters).toBeNull(); });
});


// Executes actual Engine/operations handlers. This fixture models atomic rollback;
// it deliberately does not claim PostgreSQL SQL, locking or worker-provider verification.
class CalendarAtomicDatabase extends OperationsTransaction {
  companyId = 'company'; actorId = 'owner';
  receipts = new Map<string, Data>(); audits: Data[] = [];
  failOccurrence = 0; private occurrenceAttempts = 0;
  async add<T extends Data = Data>(kind: string, data: T, id?: string): Promise<Entity<T>> {
    if (kind === 'task_occurrence' && this.failOccurrence && ++this.occurrenceAttempts === this.failOccurrence) throw new Error('Synthetic occurrence storage failure');
    return super.add(kind, data, id);
  }
  async query(sql: string, params: any[] = []) {
    const receiptKey = `${params[1]}:${params[2]}`;
    if (sql.startsWith('SELECT command,input_hash')) return { rows: this.receipts.has(receiptKey) ? [this.receipts.get(receiptKey)!] : [] };
    if (sql.startsWith('INSERT INTO command_receipts')) { this.receipts.set(receiptKey, { command: params[3], input_hash: params[4], result: JSON.parse(params[5]), authorization_hash: params[6], created_at: new Date() }); return { rows: [] }; }
    if (sql.startsWith('INSERT INTO audit_log')) { this.audits.push({ actor: params[1], action: params[2] }); return { rows: [] }; }
    throw new Error(`Unexpected calendar fixture query: ${sql}`);
  }
  async transaction<T>(companyId: string, actorId: string, fn: (tx: PgTransaction) => Promise<T>): Promise<T> {
    if (companyId !== this.companyId) throw new DomainError('NOT_FOUND_SAFE');
    this.actorId = actorId;
    const snapshot = structuredClone({ rows: this.rows, events: this.events, sequence: this.sequence, receipts: this.receipts, audits: this.audits });
    try { return await fn(this as unknown as PgTransaction); }
    catch (error) { this.rows = snapshot.rows; this.events = snapshot.events; this.sequence = snapshot.sequence; this.receipts = snapshot.receipts; this.audits = snapshot.audits; throw error; }
  }
}
afterEach(() => vi.useRealTimers());
async function scheduledFixture(patch: Data = {}) {
  vi.useFakeTimers(); vi.setSystemTime(new Date('2026-10-01T05:00:00.000Z'));
  const initial = await setup(), tx = new CalendarAtomicDatabase(); tx.rows = initial.rows; tx.sequence = initial.sequence;
  const engine = new Engine(tx as unknown as Database, 'TEST'), actor = await engine.getActor('owner', tx.companyId);
  let key = 0;
  const command = (name: string, input: Data, who = actor, extra: { idempotency_key?: string; expected_version?: number } = {}) => engine.execute(who, name, { input, idempotency_key: `calendar-engine-${++key}`, ...extra });
  const template = await command('task_template.create', { name: 'Calendar template', task: { siteId: 'A', title: 'Original recurring task', unit: 'M2', plannedQuantityMilli: 1000 }, recurrence: 'DAILY', schedule: { startsOn: '2026-10-01', localTime: '08:00', catchupLimit: 2 }, scheduledAssigneeIds: ['worker'], ...patch });
  vi.setSystemTime(new Date('2026-10-05T08:00:00.000Z'));
  const generate = (extra: { idempotency_key?: string; expected_version?: number } = {}, who = actor, templateVersion = template.version) => command('task_template.generate_due', { templateId: template.id, templateVersion }, who, extra);
  return { tx, engine, actor, template, command, generate };
}

describe('actual Engine scheduled task-template batch regressions', () => {
  it('T-TASK-07 catchup commits capped calendar tasks and cursor together; exact command replay and fresh ticks cannot duplicate', async () => {
    const s = await scheduledFixture(), first = await s.generate({ idempotency_key: 'calendar-first-tick' });
    expect(first).toMatchObject({ cursor: '2026-10-02', hasMore: true }); expect(first.createdTaskIds).toHaveLength(2);
    expect(await s.generate({ idempotency_key: 'calendar-first-tick' })).toEqual(first);
    expect(await s.tx.list('task')).toHaveLength(2); expect(await s.tx.list('task_calendar_cursor')).toHaveLength(1);
    const second = await s.generate(), third = await s.generate(), settled = await s.generate();
    expect(second).toMatchObject({ cursor: '2026-10-04', hasMore: true }); expect(third).toMatchObject({ cursor: '2026-10-05', hasMore: false }); expect(settled.createdTaskIds).toEqual([]);
    const occurrences = await s.tx.list('task_occurrence'); expect(occurrences.map(o => o.data.scheduledPeriod)).toEqual(['2026-10-01', '2026-10-02', '2026-10-03', '2026-10-04', '2026-10-05']); expect(new Set(occurrences.map(o => o.data.occurrenceKey)).size).toBe(5);
    expect((await s.tx.list('task')).every(t => t.data.state === 'ASSIGNED' && t.data.assigneeIds[0] === 'worker' && t.data.dueAt.endsWith('T06:00:00.000Z'))).toBe(true);
    expect((await s.tx.list('task_calendar_cursor'))[0]!.data.cursor).toBe('2026-10-05');
  });
  it('a failed second occurrence rolls back the whole real handler batch, cursor, task events and receipt before safe retry', async () => {
    const s = await scheduledFixture(), rowsBefore = structuredClone(s.tx.rows), eventsBefore = structuredClone(s.tx.events), receiptsBefore = structuredClone(s.tx.receipts);
    s.tx.failOccurrence = 2;
    await expect(s.generate({ idempotency_key: 'calendar-atomic-failure' })).rejects.toThrow('Synthetic occurrence storage failure');
    expect(s.tx.rows).toEqual(rowsBefore); expect(s.tx.events).toEqual(eventsBefore); expect(s.tx.receipts).toEqual(receiptsBefore); expect(await s.tx.list('task_calendar_cursor')).toEqual([]);
    s.tx.failOccurrence = 0;
    const retried = await s.generate({ idempotency_key: 'calendar-atomic-failure' }); expect(retried.createdTaskIds).toHaveLength(2); expect(await s.tx.list('task_occurrence')).toHaveLength(2); expect((await s.tx.list('task_calendar_cursor'))[0]!.data.cursor).toBe('2026-10-02');
  });
  it('template edits preserve accepted historical task and occurrence snapshots while new due tasks use the current revision', async () => {
    const s = await scheduledFixture(), first = await s.generate(), taskId = first.createdTaskIds[0], workerActor = await s.engine.getActor('worker', s.tx.companyId);
    await s.command('task.start', { taskId }, workerActor); await s.command('task.worklog', { taskId, quantityMilli: 1000, description: 'Actual synthetic calendar work' }, workerActor); await s.command('task.submit', { taskId }, workerActor); await s.command('task.review', { taskId, decision: 'ACCEPT' });
    const historicalTask = await s.tx.get('task', taskId), historicalOccurrence = (await s.tx.list('task_occurrence')).find(o => o.data.taskId === taskId)!;
    const updated = await s.command('task_template.update', { templateId: s.template.id, task: { siteId: 'A', title: 'Changed future template', unit: 'M2', plannedQuantityMilli: 2000 } });
    const fresh = await s.generate({}, s.actor, updated.version); expect(fresh.createdTaskIds).toHaveLength(2);
    expect(await s.tx.get('task', taskId)).toEqual(historicalTask); expect(await s.tx.get('task_occurrence', historicalOccurrence.id)).toEqual(historicalOccurrence);
    expect((await s.tx.get('task', fresh.createdTaskIds[0])).data).toMatchObject({ title: 'Changed future template', plannedQuantityMilli: 2000 });
    const newOccurrence = (await s.tx.list('task_occurrence')).find(o => o.data.taskId === fresh.createdTaskIds[0])!; expect(newOccurrence.data.templateRevision).toBe(2); expect(newOccurrence.data.templateSnapshot.task.title).toBe('Changed future template'); expect(historicalOccurrence.data.templateSnapshot.task.title).toBe('Original recurring task');
  });
  it('schedule edits use a new revision cursor and activation boundary instead of replaying or skipping past periods', async () => {
    const s = await scheduledFixture(); await s.generate(); const originalCursor = (await s.tx.list('task_calendar_cursor'))[0]!;
    const updated = await s.command('task_template.update', { templateId: s.template.id, recurrence: 'MONTHLY', schedule: { startsOn: '2026-10-31', localTime: '08:00', monthlyDay: 31 } });
    expect((await s.generate({}, s.actor, updated.version)).createdTaskIds).toEqual([]);
    vi.setSystemTime(new Date('2026-11-30T08:00:00.000Z'));
    const fresh = await s.generate({}, s.actor, updated.version); expect(fresh.createdTaskIds).toHaveLength(2);
    expect((await s.tx.list('task_occurrence')).map(o => o.data.scheduledPeriod)).toEqual(['2026-10-01', '2026-10-02', '2026-10-31', '2026-11-30']);
    expect(await s.tx.get('task_calendar_cursor', originalCursor.id)).toEqual(originalCursor); expect(await s.tx.list('task_calendar_cursor')).toHaveLength(2);
  });
  it('saving active:true on an already active template preserves missed periods rather than inventing a new activation', async () => {
    const s = await scheduledFixture(); await s.generate();
    await s.tx.add('user', { active: true, roles: ['OWNER'], siteIds: [] }, 'calendar-editor'); const editor = await s.engine.getActor('calendar-editor', s.tx.companyId);
    const updated = await s.command('task_template.update', { templateId: s.template.id, name: 'Renamed active template', active: true }, editor);
    expect(updated.data.activatedAt).toBe(s.template.data.activatedAt); expect(updated.data.scheduleOwnerId).toBe(s.template.data.scheduleOwnerId);
    const next = await s.generate({}, s.actor, updated.version); expect(next.createdTaskIds).toHaveLength(2);
    expect((await s.tx.list('task_occurrence')).map(o => o.data.scheduledPeriod)).toEqual(['2026-10-01', '2026-10-02', '2026-10-03', '2026-10-04']);
  });
  it('manual, inactive and missing-schedule configurations create no task or invented activation', async () => {
    const s = await scheduledFixture({ recurrence: 'MANUAL' }); expect((await s.generate()).createdTaskIds).toEqual([]);
    const noSchedule = await s.command('task_template.create', { name: 'Missing configuration', task: { siteId: 'A', title: 'No invented schedule' }, recurrence: 'DAILY' });
    const blocked = await s.command('task_template.generate_due', { templateId: noSchedule.id, templateVersion: noSchedule.version }); expect(blocked).toMatchObject({ createdTaskIds: [], blockedReason: 'MISSING_SCHEDULE_OR_ACTIVATION' }); expect(noSchedule.data.activatedAt).toBeUndefined();
    const inactive = await s.command('task_template.update', { templateId: s.template.id, active: false }); expect((await s.generate({}, s.actor, inactive.version)).createdTaskIds).toEqual([]); expect(await s.tx.list('task')).toEqual([]);
  });
  it('stale input/envelope template versions and a different authorized owner fail before any task or cursor', async () => {
    const s = await scheduledFixture(); await s.command('task_template.update', { templateId: s.template.id, name: 'New version' });
    await expect(s.generate()).rejects.toMatchObject({ code: 'VERSION_CONFLICT' });
    const current = await s.tx.get('task_template', s.template.id); await expect(s.generate({ expected_version: s.template.version }, s.actor, current.version)).rejects.toMatchObject({ code: 'VERSION_CONFLICT' });
    await s.tx.add('user', { active: true, roles: ['OWNER'], siteIds: [] }, 'other-calendar-owner'); const other = await s.engine.getActor('other-calendar-owner', s.tx.companyId);
    await expect(s.generate({}, other, current.version)).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); expect(await s.tx.list('task')).toEqual([]); expect(await s.tx.list('task_calendar_cursor')).toEqual([]);
  });
  it('fresh creator/assignee revocation and lost site assignment cannot reuse an old valid scheduling actor', async () => {
    const s = await scheduledFixture(); await s.tx.save(await s.tx.get('user', 'worker'), { active: false, roles: ['EMPLOYEE'], siteIds: ['A'] });
    await expect(s.generate()).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); expect(await s.tx.list('task')).toEqual([]); expect(await s.tx.list('task_calendar_cursor')).toEqual([]);
    await s.tx.save(await s.tx.get('user', 'worker'), { active: true, roles: ['EMPLOYEE'], siteIds: ['B'] }); await expect(s.generate()).rejects.toMatchObject({ code: 'ACCESS_DENIED' });
    await s.tx.save(await s.tx.get('user', 'owner'), { active: false, roles: ['OWNER'], siteIds: [] }); await expect(s.generate()).rejects.toMatchObject({ code: 'ACCESS_DENIED' }); expect(await s.tx.list('task_occurrence')).toEqual([]);
  });
  it('legacy occurrence key serialization is deduplicated by exact structured template/date/location without rewriting the task', async () => {
    const s = await scheduledFixture(), first = await s.generate(), occurrence = (await s.tx.list('task_occurrence'))[0]!, task = await s.tx.get('task', occurrence.data.taskId);
    await s.tx.save(occurrence, { ...occurrence.data, occurrenceKey: `${s.template.id}:${occurrence.data.scheduledPeriod}:-` });
    const template = await s.tx.get('task_template', s.template.id); await s.tx.save(template, { ...template.data, revision: template.data.revision + 1 }); const current = await s.tx.get('task_template', template.id);
    const restart = await s.generate({}, s.actor, current.version); expect(restart.createdTaskIds).toHaveLength(2); expect(await s.tx.get('task', task.id)).toEqual(task);
    expect((await s.tx.list('task_occurrence')).filter(o => o.data.scheduledPeriod === occurrence.data.scheduledPeriod)).toHaveLength(1); expect(first.createdTaskIds).toContain(task.id);
  });
});
