import {describe,it,expect} from 'vitest';
import {commerceCommands,authorizeCommerceEmployeeCommand} from '../packages/domain/commerce.ts';
import {startOrderFromWorkSegment} from '../packages/domain/order-lifecycle.ts';
import {registry} from '../apps/api/registry.ts';
import {reportSnapshotHash} from '../packages/domain/resources.ts';
import {DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';

// Explicit CPU transaction double. PostgreSQL atomic rollback is tested separately;
// this fixture does not attest real employee ACK, provider delivery or legal approval.
const NOW='2026-10-08T10:00:00.000Z';
class Tx implements Transaction {
 rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];seq=0;
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const e=this.rows.get(`${kind}:${id}`);if(!e)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(e) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.rows.values()].filter(e=>e.kind===kind).map(e=>structuredClone(e) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`${kind}-${++this.seq}`):Promise<Entity<T>>{if(this.rows.has(kind+':'+id))throw new DomainError('VERSION_CONFLICT');const e={kind,id,companyId:'company',data:structuredClone(data),version:1,createdAt:NOW,updatedAt:NOW};this.rows.set(kind+':'+id,e);return structuredClone(e);}
 async save(e:Entity,data:Data,expectedVersion=e.version){const current=await this.get(e.kind,e.id);if(current.version!==expectedVersion)throw new DomainError('VERSION_CONFLICT');const next={...current,data:structuredClone(data),version:current.version+1};this.rows.set(e.kind+':'+e.id,next);return structuredClone(next);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
}
const owner:Actor={userId:'owner',companyId:'company',roles:['OWNER'],permissions:['*','scope.company'],siteIds:[],customerIds:[],warehouseIds:[]};
const worker:Actor={...owner,userId:'worker',roles:['EMPLOYEE'],permissions:['dispatch.acknowledge','shift.manage','task.work'],siteIds:['site']};
function context(tx:Tx,actor=owner):CommandContext{return {tx,actor,now:NOW,idempotencyKey:'CPU_ORDER_TEST',requireSite:id=>{if(!actor.roles.includes('OWNER')&&!actor.siteIds.includes(id))throw new DomainError('ACCESS_DENIED');},requireOwn:id=>{if(actor.userId!==id&&!actor.roles.includes('OWNER'))throw new DomainError('ACCESS_DENIED');}};}
async function run(c:CommandContext,name:string,input:Data){const def=commerceCommands[name]!;return def.handler(c,def.schema.parse(input));}
async function fixture(status='SCHEDULED') {
 const tx=new Tx(),c=context(tx);await tx.add('company',{operatingMode:'TEST'},'company');await tx.add('user',{active:true,roles:['OWNER'],siteIds:[]},'owner');await tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['site']},'worker');await tx.add('site',{active:true,customerId:'customer'},'site');await tx.add('employee',{active:true,userId:'worker',skills:[],absences:[]},'employee');
 const commercial={id:'quote',quoteVersion:1,scope:'Synthetic agreed work',included:[],excluded:[],pricingModel:'FIXED',certainty:'CONTRACT_PRICE',currency:'EUR',lines:[{serviceId:'service',serviceName:'Synthetic work',quantityMilli:1000,unit:'FIXED',rateCents:10000,netCents:10000,included:false,rounding:'HALF_UP_TO_CENT'}],subtotalNetCents:10000,discountCents:0,totalNetCents:10000,totalTaxCents:1900,totalGrossCents:11900,tax:{mode:'VAT',rateBps:1900,display:'GROSS'},expiresAt:'2027-01-01T00:00:00.000Z',priceBookId:'book',priceBookVersion:1};
 await tx.add('lead',{status:'CONVERTED',review_state:'NONE',currentQuoteId:'quote'},'lead');await tx.add('quote',{...commercial,status:'ACCEPTED',orderId:'order',leadId:'lead',customerId:'customer',acceptanceId:'acceptance'},'quote');await tx.add('quote_acceptance',{quoteId:'quote',quoteVersion:1,orderId:'order',customerId:'customer',commercialSnapshot:commercial},'acceptance');await tx.add('dispatch_request',{orderId:'order'},'dispatch');
 const order=await tx.add('order',{status,siteId:'site',customerId:'customer',leadId:'lead',quoteId:'quote',quoteVersion:1,scope:commercial.scope,baseNetCents:10000,finalNetCents:10000,billing:{paidCents:0},responsibleUserId:'owner',dispatchId:'dispatch',assignmentId:'assignment',scheduleVersion:1,schedulePublishedVersion:1,confirmedAt:'2026-10-08T09:00:00.000Z',confirmedStartAt:'2026-10-09T08:00:00.000Z',confirmedEndAt:'2026-10-09T10:00:00.000Z'},'order');
 await tx.add('crew_assignment',{orderId:'order',siteId:'site',employeeIds:['employee'],acknowledgedIds:['employee'],requireEmployeeAck:true,status:'ACKNOWLEDGED',scheduleVersion:1,startAt:'2026-10-09T08:00:00.000Z',endAt:'2026-10-09T10:00:00.000Z'},'assignment');
 const task=await tx.add('task',{orderId:'order',siteId:'site',sourceQuoteId:'quote',sourceQuoteVersion:1,quoteLineIndex:0,state:'ASSIGNED',assigneeIds:['worker'],billingScope:'CONTRACT',completionKind:'ORIGINAL',unit:'UNIT',plannedQuantityMilli:1000,reportedQuantityMilli:0,acceptedQuantityMilli:0,checklist:[],requiredPhotoCount:0,reviewCycle:0},'task');
 const segment=await tx.add('time_segment',{shiftId:'shift',employeeId:'worker',siteId:'site',taskId:'task',activity:'WORKING',startAt:NOW,endAt:null},'segment');await tx.add('shift',{employeeId:'worker',siteId:'site',state:'ACTIVE',activeSegmentId:'segment',startAt:NOW,endAt:null},'shift');return {tx,c,wc:context(tx,worker),order,task,segment};
}
async function patch(f:Awaited<ReturnType<typeof fixture>>,kind:string,id:string,data:Data){const e=await f.tx.get(kind,id);return f.tx.save(e,{...e.data,...data});}
async function internallyReviewed(){
 const f=await fixture();await startOrderFromWorkSegment(f.wc,f.segment);await patch(f,'task','task',{state:'SUBMITTED_FOR_REVIEW',submittedBy:'worker',submittedAt:NOW});await run(f.c,'order.submit',{id:'order',reason:'Whole current scope submitted',remainingTaskIds:[]});
 await patch(f,'task','task',{state:'ACCEPTED',reviewedBy:'owner',reviewedAt:NOW,acceptedQuantityMilli:1000});await f.tx.add('task_review',{taskId:'task',decision:'ACCEPT',reviewedBy:'owner',reviewedAt:NOW},'task-review');
 const review=await run(f.c,'order.review',{id:'order',reason:'Independent internal QC completed',remainingTaskIds:[]});
 const snapshot={documentType:'Abnahmeprotokoll',order:{id:'order',quoteId:'quote',quoteVersion:1},totalNetCents:10000,taskRows:[{taskId:'task',state:'ACCEPTED',reviewId:'task-review',quantityMilli:1000,unit:'UNIT'}]};await f.tx.add('report',{state:'PUBLISHED',currentVersionId:'report-version',orderId:'order'},'report');await f.tx.add('report_version',{reportId:'report',customerId:'customer',siteId:'site',immutable:true,publishedAt:NOW,sha256:reportSnapshotHash(snapshot),snapshot},'report-version');
 return {...f,review};
}

describe('V4 D07 actual order lifecycle: CPU transaction double',()=>{
 it('only internal operations may confirm an accepted current scope with an active responsible person',async()=>{const f=await fixture('PENDING_OPERATIONS');const dispatcher=context(f.tx,{...owner,userId:'dispatcher',roles:['DISPATCHER'],siteIds:['site']});await expect(run(dispatcher,'order.confirm',{id:'order',responsibleUserId:'owner',reason:'Dispatcher attempts confirmation'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await patch(f,'user','owner',{active:false});await expect(run(f.c,'order.confirm',{id:'order',responsibleUserId:'owner',reason:'Inactive responsible'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});await patch(f,'user','owner',{active:true});const confirmed=await run(f.c,'order.confirm',{id:'order',responsibleUserId:'owner',reason:'Synthetic responsible confirmed scope'});expect(confirmed.data).toMatchObject({status:'CONFIRMED',responsibleUserId:'owner',confirmedBy:'owner'});});
 it('a changed accepted commercial scope cannot be confirmed',async()=>{const f=await fixture('PENDING_OPERATIONS');await patch(f,'quote','quote',{totalNetCents:90000});await expect(run(f.c,'order.confirm',{id:'order',responsibleUserId:'owner',reason:'Altered after acceptance'})).rejects.toMatchObject({code:'NEEDS_APPROVAL',details:{reason:'ACCEPTED_ORDER_SCOPE_CHANGED'}});expect((await f.tx.get('order','order')).data.status).toBe('PENDING_OPERATIONS');});
 it('requireEmployeeAck:false cannot bypass scheduling',async()=>{const f=await fixture('CONFIRMED');await f.tx.add('schedule_reservation',{orderId:'order',employeeIds:['employee'],status:'ACTIVE',startAt:'2026-10-09T08:00:00.000Z',endAt:'2026-10-09T10:00:00.000Z',expiresAt:'2026-10-08T10:15:00.000Z'},'reservation');await expect(run(f.c,'dispatch.assign',{orderId:'order',reservationId:'reservation',siteId:'site',requireEmployeeAck:false})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});expect((await f.tx.get('schedule_reservation','reservation')).data.status).toBe('ACTIVE');});
 it('a formerly held slot with a new employee conflict cannot publish a customer schedule at ACK time',async()=>{const f=await fixture('CONFIRMED');await patch(f,'crew_assignment','assignment',{acknowledgedIds:[],status:'ASSIGNED'});await f.tx.add('crew_assignment',{orderId:'other-order',employeeIds:['employee'],status:'ACKNOWLEDGED',startAt:'2026-10-09T08:30:00.000Z',endAt:'2026-10-09T09:30:00.000Z'},'other');await expect(run(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'VERSION_CONFLICT',details:{reason:'SCHEDULE_CONFLICT'}});expect((await f.tx.get('order','order')).data.status).toBe('CONFIRMED');expect(f.tx.events.some(e=>e.type==='dispatch.schedule_confirmed')).toBe(false);});
 it('operations cannot fabricate another employee acceptance using managerial own-scope privileges',async()=>{const f=await fixture('CONFIRMED');await patch(f,'crew_assignment','assignment',{acknowledgedIds:[],status:'ASSIGNED'});await expect(run(f.c,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'ACCESS_DENIED',details:{reason:'EMPLOYEE_MUST_ACCEPT_OWN_ASSIGNMENT'}});expect((await f.tx.get('crew_assignment','assignment')).data.acknowledgedIds).toEqual([]);const accepted=await run(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'});expect(accepted.data.acknowledgedIds).toEqual(['employee']);});
 it('an old assignment ACK or canceled-order reschedule cannot replace the current schedule',async()=>{const f=await fixture();await patch(f,'order','order',{scheduleVersion:2});await expect(run(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'INVALID_STATE'});await patch(f,'order','order',{status:'CANCELLED',scheduleVersion:1});await expect(run(f.c,'dispatch.reschedule',{id:'assignment',startAt:'2026-10-10T08:00:00.000Z',endAt:'2026-10-10T10:00:00.000Z',reason:'Invalid terminal edit'})).rejects.toMatchObject({code:'INVALID_STATE'});});
 it('the actual permitted first task segment starts the order once and retains its source fact',async()=>{const f=await fixture();const first=await startOrderFromWorkSegment(f.wc,f.segment);expect(first?.data).toMatchObject({status:'IN_PROGRESS',firstWorkSegmentId:'segment',startedAt:NOW});expect((await f.tx.get('crew_assignment','assignment')).data).toMatchObject({status:'STARTED',firstWorkSegmentId:'segment'});const repeat=await startOrderFromWorkSegment(f.wc,f.segment);expect(repeat?.version).toBe(first?.version);expect(f.tx.events.filter(e=>e.type==='order.status_changed')).toHaveLength(1);});
 it('starting a shift without an order-bound task never guesses an order from the site',async()=>{const f=await fixture();const unbound=await patch(f,'task','task',{orderId:undefined});expect(await startOrderFromWorkSegment(f.wc,f.segment)).toBeUndefined();expect((await f.tx.get('order','order')).data.status).toBe('SCHEDULED');expect(unbound.data.siteId).toBe('site');});
 it.each(['PAUSED','CLOSED','CANCELLED','CONFIRMED'])('a task segment cannot start an order in %s',async status=>{const f=await fixture(status);await expect(startOrderFromWorkSegment(f.wc,f.segment)).rejects.toMatchObject({code:'INVALID_STATE'});expect((await f.tx.get('order','order')).data.status).toBe(status);});
 it.each([{kind:'shift',id:'shift',data:{state:'ENDED'}},{kind:'shift',id:'shift',data:{activeSegmentId:'other'}},{kind:'shift',id:'shift',data:{siteId:'other-site'}},{kind:'site',id:'site',data:{customerId:'other-customer'}},{kind:'time_segment',id:'segment',data:{endAt:NOW}},{kind:'task',id:'task',data:{state:'ACCEPTED'}},{kind:'crew_assignment',id:'assignment',data:{acknowledgedIds:[]}},{kind:'crew_assignment',id:'assignment',data:{scheduleVersion:2}}])('rejects missing actual current work permission: $kind $data',async row=>{const f=await fixture();await patch(f,row.kind,row.id,row.data);const current=await f.tx.get('time_segment','segment');await expect(startOrderFromWorkSegment(f.wc,current)).rejects.toBeInstanceOf(DomainError);expect((await f.tx.get('order','order')).data.status).toBe('SCHEDULED');});
 it('crew_assignment.start without an actual active work segment cannot advance a schedule',async()=>{const f=await fixture();await patch(f,'time_segment','segment',{activity:'ON_BREAK',taskId:null});await expect(run(f.wc,'crew_assignment.start',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'INVALID_STATE'});expect((await f.tx.get('order','order')).data.status).toBe('SCHEDULED');});
 it('direct SCHEDULED→IN_PROGRESS and paused scheduled→IN_PROGRESS transitions are forbidden',async()=>{const f=await fixture();await expect(run(f.c,'order.transition',{id:'order',status:'IN_PROGRESS',reason:'Manual bypass'})).rejects.toMatchObject({code:'INVALID_STATE'});const paused=await run(f.c,'order.transition',{id:'order',status:'PAUSED',reason:'Access unavailable'});expect(paused.data.resume_state).toBe('SCHEDULED');await expect(run(f.c,'order.transition',{id:'order',status:'IN_PROGRESS',reason:'Wrong resume stage',resolutionEvidence:'Resolved access'})).rejects.toMatchObject({code:'INVALID_STATE'});});
 it('submission requires explicit truthful remaining scope and an internal foreman',async()=>{const f=await fixture();await startOrderFromWorkSegment(f.wc,f.segment);await expect(run(f.c,'order.submit',{id:'order',reason:'Omits unfinished tasks',remainingTaskIds:[]})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});await expect(run(f.wc,'order.submit',{id:'order',reason:'Worker attempts internal submission',remainingTaskIds:['task']})).rejects.toMatchObject({code:'ACCESS_DENIED'});const foreman=context(f.tx,{...owner,userId:'foreman',roles:['INTERNAL_BAULEITER'],siteIds:['site']});const result=await run(foreman,'order.submit',{id:'order',reason:'Unfinished painting explicitly listed',remainingTaskIds:['task']});expect(result.data).toMatchObject({status:'WORK_SUBMITTED',submission:{submittedBy:'foreman',remainingTaskIds:['task']}});});
 it('client review requires actual internal QC and the current published customer report',async()=>{const f=await internallyReviewed();await expect(run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'No report supplied'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});const result=await run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Internal review and publication complete',reviewId:f.review.id,reportVersionId:'report-version'});expect(result.data).toMatchObject({status:'CLIENT_REVIEW',internalReviewId:f.review.id,clientReportVersionId:'report-version'});});
 it('task changes after internal review or a superseded report reject before client publication stage',async()=>{const f=await internallyReviewed();await patch(f,'task','task',{description:'Altered after review'});await expect(run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Stale review',reportVersionId:'report-version'})).rejects.toMatchObject({code:'NEEDS_APPROVAL',details:{reason:'CURRENT_INTERNAL_REVIEW_REQUIRED'}});const g=await internallyReviewed();await patch(g,'report','report',{currentVersionId:'new-version'});await expect(run(g.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Superseded report',reportVersionId:'report-version'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});});
 it('document receipt does not count as work acceptance; documented closure requires evidence and does not mark payment',async()=>{const f=await internallyReviewed();await run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Client review begins',reportVersionId:'report-version'});await f.tx.add('customer_acknowledgment',{immutable:true,reportVersionId:'report-version',reportSha256:(await f.tx.get('report_version','report-version')).data.sha256,customerId:'customer',siteId:'site',type:'DOCUMENT_RECEIPT',decision:'CONFIRMED'},'ack');await expect(run(f.c,'order.transition',{id:'order',status:'CLOSED',reason:'Receipt only',closureBasis:'CONTRACTUAL_ACCEPTANCE',acknowledgmentId:'ack'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});await expect(run(f.c,'order.transition',{id:'order',status:'CLOSED',reason:'Undocumented',closureBasis:'DOCUMENTED_REASON'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});const closed=await run(f.c,'order.transition',{id:'order',status:'CLOSED',reason:'Recorded contractual closure basis',closureBasis:'DOCUMENTED_REASON',closureEvidence:'SYNTHETIC_EVIDENCE_NOT_REAL_LEGAL_APPROVAL'});expect(closed.data).toMatchObject({status:'CLOSED',billing:{paidCents:0},closure:{basis:'DOCUMENTED_REASON'}});await expect(run(f.c,'order.transition',{id:'order',status:'IN_PROGRESS',reason:'New work after closed'})).rejects.toMatchObject({code:'INVALID_STATE'});});
 it('actual contractual acceptance closes only its exact published immutable report',async()=>{const f=await internallyReviewed();await run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Client review',reportVersionId:'report-version'});await f.tx.add('customer_acknowledgment',{immutable:true,reportVersionId:'report-version',reportSha256:(await f.tx.get('report_version','report-version')).data.sha256,customerId:'customer',siteId:'site',type:'WORK_ACCEPTANCE',decision:'CONFIRMED'},'ack');const result=await run(f.c,'order.transition',{id:'order',status:'CLOSED',reason:'Exact work acceptance on current report',closureBasis:'CONTRACTUAL_ACCEPTANCE',acknowledgmentId:'ack'});expect(result.data.closure.acknowledgmentId).toBe('ack');});
 it('an open blocking defect prevents closure even with a documented basis',async()=>{const f=await internallyReviewed();await run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Client review',reportVersionId:'report-version'});await f.tx.add('defect',{taskId:'task',siteId:'site',state:'OPEN',severity:'HIGH'},'defect');await expect(run(f.c,'order.transition',{id:'order',status:'CLOSED',reason:'Blocked',closureBasis:'DOCUMENTED_REASON',closureEvidence:'Explicit record'})).rejects.toMatchObject({code:'NEEDS_APPROVAL',details:{reason:'OPEN_BLOCKING_DEFECTS'}});expect((await f.tx.get('task','task')).data.state).toBe('ACCEPTED');});
 it('pause/resume retains the exact stage and records an explicit resolution without inventing work',async()=>{const f=await fixture();const paused=await run(f.c,'order.transition',{id:'order',status:'PAUSED',reason:'Temporary access restriction'});expect(paused.data.resume_state).toBe('SCHEDULED');await expect(run(f.c,'order.transition',{id:'order',status:'SCHEDULED',reason:'No resolution evidence'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});const resumed=await run(f.c,'order.transition',{id:'order',status:'SCHEDULED',reason:'Access restored',resolutionEvidence:'Explicit synthetic access approval'});expect(resumed.data).toMatchObject({status:'SCHEDULED',resume_state:null,resolution:{from:'PAUSED',to:'SCHEDULED'}});expect(resumed.data.firstWorkSegmentId).toBeUndefined();});
 it('disputes preserve their source stage and subject and require an explicit stage decision',async()=>{const f=await fixture();await expect(run(f.c,'order.transition',{id:'order',status:'DISPUTED',reason:'No subject'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});const disputed=await run(f.c,'order.transition',{id:'order',status:'DISPUTED',reason:'Access terms disputed',disputeSubject:'Agreed customer site access'});expect(disputed.data).toMatchObject({disputed_from:'SCHEDULED',dispute:{subject:'Agreed customer site access'}});await expect(run(f.c,'order.transition',{id:'order',status:'SCHEDULED',reason:'No explicit resolution'})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});const resolved=await run(f.c,'order.transition',{id:'order',status:'CONFIRMED',reason:'New scheduling required',resolutionEvidence:'Recorded operations decision'});expect(resolved.data).toMatchObject({status:'CONFIRMED',disputed_from:null,resolution:{from:'DISPUTED',to:'CONFIRMED'}});});
 it('cancellation releases future reservations and pending reminders while retaining worked facts',async()=>{const f=await fixture();await f.tx.add('schedule_reservation',{orderId:'order',status:'ACTIVE',endAt:'2026-10-09T10:00:00.000Z'},'future');await f.tx.add('notification',{orderId:'order',status:'PENDING'},'reminder');await f.tx.add('worklog',{taskId:'task',employeeId:'worker',reportedQuantityMilli:1000},'work-fact');const facts=await f.tx.list('time_segment'),logs=await f.tx.list('worklog');const cancelled=await run(f.c,'order.transition',{id:'order',status:'CANCELLED',reason:'Customer withdrew before the visit'});expect(cancelled.data.status).toBe('CANCELLED');expect((await f.tx.get('schedule_reservation','future')).data.status).toBe('CANCELLED');expect((await f.tx.get('crew_assignment','assignment')).data.status).toBe('CANCELLED');expect((await f.tx.get('notification','reminder')).data.status).toBe('CANCELLED');expect(await f.tx.list('time_segment')).toEqual(facts);expect(await f.tx.list('worklog')).toEqual(logs);expect(f.tx.events.some(e=>e.type==='dispatch.order_cancelled')).toBe(true);});
 it('reassigning a confirmed order reuses identical generated task and material request scope',async()=>{const f=await fixture('CONFIRMED');await f.tx.add('material',{name:'Synthetic paint',baseUnit:'ML'},'paint');for(let index=0;index<2;index++){const held=await run(f.c,'dispatch.reserve',{orderId:'order',employeeIds:['employee'],startAt:'2026-10-10T08:00:00.000Z',endAt:'2026-10-10T10:00:00.000Z'});await run(f.c,'dispatch.assign',{orderId:'order',reservationId:held.id,siteId:'site',materialRequirements:[{materialId:'paint',quantityBase:1000,unit:'ML'}]});}expect((await f.tx.list('task')).filter(t=>t.data.orderId==='order')).toHaveLength(1);expect((await f.tx.list('material_requirement')).filter(r=>r.data.orderId==='order')).toHaveLength(1);expect(f.tx.events.filter(e=>e.type==='material_requirement.created')).toHaveLength(1);});
 it('crew replacement releases the old unstarted assignment and updates the same unfinished task to the new accepted crew scope',async()=>{const f=await fixture('CONFIRMED');await f.tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:[]},'replacement-worker');await f.tx.add('employee',{active:true,userId:'replacement-worker',skills:[],absences:[]},'replacement-employee');await f.tx.add('notification',{orderId:'order',status:'PENDING',scheduleVersion:1},'old-reminder');const held=await run(f.c,'dispatch.reserve',{orderId:'order',employeeIds:['replacement-employee'],startAt:'2026-10-10T08:00:00.000Z',endAt:'2026-10-10T10:00:00.000Z'}),assigned=await run(f.c,'dispatch.assign',{orderId:'order',reservationId:held.id,siteId:'site'});expect((await f.tx.get('crew_assignment','assignment')).data).toMatchObject({status:'CANCELLED',replacedByAssignmentId:assigned.assignment.id});expect(assigned.assignment.data.replacesAssignmentId).toBe('assignment');expect((await f.tx.get('task','task')).data.assigneeIds).toEqual(['replacement-worker']);expect((await f.tx.list('task')).filter(t=>t.data.orderId==='order')).toHaveLength(1);expect(assigned.assignment.data.acknowledgedIds).toEqual([]);expect(assigned.order.data.status).toBe('CONFIRMED');expect((await f.tx.get('notification','old-reminder')).data.status).toBe('CANCELLED');expect(f.tx.events.find(e=>e.type==='dispatch.assigned')?.data.supersededAssignmentId).toBe('assignment');});
 it('reservation TTL is exactly fifteen minutes, and a caller cannot extend it',async()=>{const f=await fixture('CONFIRMED');await expect(run(f.c,'dispatch.reserve',{orderId:'order',employeeIds:['employee'],startAt:'2026-10-10T08:00:00.000Z',endAt:'2026-10-10T10:00:00.000Z',ttlMinutes:120})).rejects.toThrow();const held=await run(f.c,'dispatch.reserve',{orderId:'order',employeeIds:['employee'],startAt:'2026-10-10T08:00:00.000Z',endAt:'2026-10-10T10:00:00.000Z'});expect(held.data.expiresAt).toBe('2026-10-08T10:15:00.000Z');});
 it('a stored published snapshot with an invalid hash cannot authorize client review',async()=>{const f=await internallyReviewed();await patch(f,'report_version','report-version',{sha256:'INVALID_PUBLISHED_SNAPSHOT_HASH'});await expect(run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Cannot trust altered snapshot',reportVersionId:'report-version'})).rejects.toMatchObject({code:'NEEDS_APPROVAL',details:{reason:'PUBLISHED_REPORT_SNAPSHOT_HASH_MISMATCH'}});});
 it('a hash-consistent report with different accepted quantity cannot substitute for current QC',async()=>{const f=await internallyReviewed(),report=await f.tx.get('report_version','report-version'),snapshot={...report.data.snapshot,taskRows:[{taskId:'task',state:'ACCEPTED',reviewId:'task-review',quantityMilli:9999,unit:'UNIT'}]};await patch(f,'report_version','report-version',{snapshot,sha256:reportSnapshotHash(snapshot)});await expect(run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Published quantity is stale',reportVersionId:'report-version'})).rejects.toMatchObject({code:'NEEDS_APPROVAL',details:{reason:'REPORT_MUST_MATCH_CURRENT_REVIEWED_SCOPE'}});});
 it('cancelling another task does not hide its open blocking defect from closure',async()=>{const f=await internallyReviewed();await run(f.c,'order.transition',{id:'order',status:'CLIENT_REVIEW',reason:'Client review',reportVersionId:'report-version'});await f.tx.add('task',{orderId:'order',siteId:'site',state:'CANCELLED'},'cancelled-task');await f.tx.add('defect',{taskId:'cancelled-task',siteId:'site',state:'OPEN',severity:'HIGH'},'retained-defect');await expect(run(f.c,'order.transition',{id:'order',status:'CLOSED',reason:'Cannot hide defect',closureBasis:'DOCUMENTED_REASON',closureEvidence:'Explicit record'})).rejects.toMatchObject({code:'NEEDS_APPROVAL',details:{reason:'OPEN_BLOCKING_DEFECTS'}});});
 it('the actual operations shift.start hook starts only an order-bound permitted task',async()=>{const f=await fixture();f.tx.rows.delete('shift:shift');f.tx.rows.delete('time_segment:segment');const def=registry['shift.start']!;const shift=await def.handler(f.wc,def.schema.parse({siteId:'site',taskId:'task'}));expect((await f.tx.get('order','order')).data).toMatchObject({status:'IN_PROGRESS',firstWorkSegmentId:shift.data.activeSegmentId});});
});


describe('Critical dispatch current employee/user/site scopes: CPU double',()=>{
 const actor=(userId='dispatcher',siteIds=['site']):Actor=>({...owner,userId,roles:['DISPATCHER'],permissions:['dispatch.manage','dispatch.read'],siteIds});
 const availability={employeeId:'employee',availabilityWindows:[],absences:[],validUntil:'2026-11-01T00:00:00.000Z',source:'Explicit synthetic availability assessment'};
 const slot={orderId:'order',employeeIds:['employee'],startAt:'2026-10-10T08:00:00.000Z',endAt:'2026-10-10T10:00:00.000Z'};
 function fingerprint(tx:Tx){return JSON.stringify({rows:[...tx.rows],events:tx.events});}
 it('a revoked own site cannot ACK while another required peer is still pending',async()=>{const f=await fixture('CONFIRMED');await patch(f,'crew_assignment','assignment',{employeeIds:['employee','peer'],acknowledgedIds:[],status:'ASSIGNED'});const before=fingerprint(f.tx),revoked=context(f.tx,{...worker,siteIds:[]});await expect(run(revoked,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(fingerprint(f.tx)).toBe(before);});
 it('the current canonical user site overrides a stale cached actor site and misleading HR site',async()=>{const f=await fixture('CONFIRMED');await patch(f,'user','worker',{siteIds:[]});await patch(f,'employee','employee',{siteIds:['site']});await patch(f,'crew_assignment','assignment',{acknowledgedIds:[],status:'ASSIGNED'});const before=fingerprint(f.tx);await expect(run(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(fingerprint(f.tx)).toBe(before);});
 it('inactive HR employee cannot ACK before a pending peer causes schedule short circuit',async()=>{const f=await fixture('CONFIRMED');await patch(f,'employee','employee',{active:false});await patch(f,'crew_assignment','assignment',{employeeIds:['employee','peer'],acknowledgedIds:[],status:'ASSIGNED'});const before=fingerprint(f.tx);await expect(run(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'EMPLOYEE_INACTIVE'}});expect(fingerprint(f.tx)).toBe(before);});
 it('a revoked site prevents crew.start before assignment or order effects',async()=>{const f=await fixture(),before=fingerprint(f.tx);await expect(run(context(f.tx,{...worker,siteIds:[]}),'crew_assignment.start',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(fingerprint(f.tx)).toBe(before);});
 it('a mixed external role cannot accept an internal crew assignment',async()=>{const f=await fixture('CONFIRMED');await patch(f,'crew_assignment','assignment',{acknowledgedIds:[],status:'ASSIGNED'});const before=fingerprint(f.tx);await expect(run(context(f.tx,{...worker,roles:['EMPLOYEE','CLIENT']}),'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(fingerprint(f.tx)).toBe(before);});
 it('read-only receipt authorization allows a successful post-transition ACK replay but rejects current inactive or foreign-site subject',async()=>{const f=await fixture('SCHEDULED'),before=fingerprint(f.tx);await expect(authorizeCommerceEmployeeCommand(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).resolves.toBeUndefined();expect(fingerprint(f.tx)).toBe(before);await patch(f,'employee','employee',{active:false});const inactive=fingerprint(f.tx);await expect(authorizeCommerceEmployeeCommand(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'INVALID_STATE'});expect(fingerprint(f.tx)).toBe(inactive);await patch(f,'employee','employee',{active:true});await patch(f,'user','worker',{siteIds:[]});const revoked=fingerprint(f.tx);await expect(authorizeCommerceEmployeeCommand(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(fingerprint(f.tx)).toBe(revoked);});
 it('the canonical legacy user_id alias is accepted only for its actual active internal user',async()=>{const f=await fixture('CONFIRMED');await patch(f,'employee','employee',{userId:undefined,user_id:'worker'});await patch(f,'crew_assignment','assignment',{acknowledgedIds:[],status:'ASSIGNED'});const result=await run(f.wc,'crew_assignment.acknowledge',{id:'assignment',employeeId:'employee'});expect(result.data.acknowledgedIds).toEqual(['employee']);expect((await f.tx.get('order','order')).data.status).toBe('SCHEDULED');});
 it('a site-scoped dispatcher cannot edit foreign-site availability or reserve its canonical employee',async()=>{const f=await fixture('CONFIRMED');await patch(f,'user','worker',{siteIds:['foreign-site']});await patch(f,'employee','employee',{siteIds:['site']});const scoped=context(f.tx,actor()),before=fingerprint(f.tx);await expect(run(scoped,'employee.availability',availability)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(scoped,'dispatch.reserve',slot)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(fingerprint(f.tx)).toBe(before);});
 it('recommendation omits foreign-site and inactive people from both available and excluded outputs',async()=>{const f=await fixture('CONFIRMED');await f.tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['foreign-site']},'foreign-user');await f.tx.add('employee',{active:true,userId:'foreign-user',businessCode:'PRIVATE_FOREIGN_PERSON',skills:[{id:'PRIVATE_FOREIGN_SKILL',verified:true}]},'foreign-employee');await f.tx.add('user',{active:false,roles:['EMPLOYEE'],siteIds:['site']},'inactive-user');await f.tx.add('employee',{active:true,userId:'inactive-user'},'inactive-employee');const result=await run(context(f.tx,actor()),'dispatch.recommend',{orderId:'order',startAt:slot.startAt,endAt:slot.endAt});expect(result.available.map((e:Data)=>e.employeeId)).toEqual(['employee']);expect(JSON.stringify(result)).not.toContain('PRIVATE_FOREIGN');expect(result.excluded.map((e:Data)=>e.employeeId)).not.toContain('foreign-employee');expect(result.excluded.map((e:Data)=>e.employeeId)).not.toContain('inactive-employee');});
 it('fresh actor site revocation denies availability and reserve, while explicit company scope can manage unassigned people',async()=>{const f=await fixture('CONFIRMED'),revoked=context(f.tx,actor('dispatcher',[])),before=fingerprint(f.tx);await expect(run(revoked,'employee.availability',availability)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(revoked,'dispatch.reserve',slot)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(fingerprint(f.tx)).toBe(before);await patch(f,'user','worker',{siteIds:[]});await expect(run(f.c,'employee.availability',availability)).resolves.toMatchObject({data:{availabilityReviewedBy:'owner'}});await expect(run(f.c,'dispatch.reserve',slot)).resolves.toMatchObject({data:{status:'ACTIVE'}});});
});
