import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Database} from '../apps/api/database.ts';
import {Engine} from '../apps/api/engine.ts';
import type {Actor,Data,Entity} from '../packages/domain/core.ts';

// Genuine PostgreSQL transactions and fresh Engine authorization. All people,
// ACKs, work quantities and legal references are explicitly synthetic fixtures;
// these tests do not attest real company/employee/customer acceptance.
const postgres=process.env.DATABASE_URL?describe:describe.skip;
postgres('V4 D07 PostgreSQL actual order transitions and rollback',()=>{
 let db:Database,engine:Engine,company:string,owner:Actor,client:Actor,worker:Actor,foreman:Actor,order:Entity,assignment:Entity,task:Entity;
 beforeAll(async()=>{db=new Database();await db.migrate();});afterAll(async()=>{await db?.close();});
 const execute=(actor:Actor,name:string,input:Data,key=randomUUID())=>engine.execute(actor,name,{input,idempotency_key:key});
 const row=(kind:string,id:string)=>db.transaction(company,'SYNTHETIC_D07_ASSERT',tx=>tx.get(kind,id));
 const rows=(kind:string)=>db.transaction(company,'SYNTHETIC_D07_ASSERT',tx=>tx.list(kind));
 async function fingerprint(){const result:Record<string,Data>={};for(const table of ['aggregates','aggregate_revisions','audit_log','command_receipts','outbox'])result[table]=(await db.query(`SELECT count(*)::int AS count,md5(coalesce(string_agg(to_jsonb(r)::text,E'\n' ORDER BY to_jsonb(r)::text),'')) AS hash FROM ${table} r WHERE company_id=$1`,[company])).rows[0];return result;}
 beforeEach(async()=>{
  company='order-v4-'+randomUUID();engine=new Engine(db,'TEST');await db.transaction(company,'SYNTHETIC_D07_SETUP',async tx=>{
   await tx.add('company',{name:'Synthetic D07 isolated QA',legalName:'SYNTHETIC QA COMPANY',address:'Synthetic address',operatingMode:'TEST',synthetic:true},company);
   for(const [id,roles] of [['owner',['OWNER']],['client',['CLIENT']],['worker',['EMPLOYEE']],['foreman',['INTERNAL_BAULEITER']]] as const)await tx.add('user',{active:true,roles,siteIds:id==='foreman'?['site']:[],synthetic:true},id);
   await tx.add('employee',{active:true,userId:'worker',skills:[],absences:[],synthetic:true},'employee');
  });owner=await engine.getActor('owner',company);client=await engine.getActor('client',company);
  const service=await execute(owner,'service.create',{name:'Synthetic fixed service',description:'Synthetic agreed work',unit:'FIXED',model:'FIXED',active:true});
  let book=await execute(owner,'price_book.create',{name:'Synthetic D07 pricebook',validFrom:'2026-01-01T00:00:00.000Z',tax:{mode:'VAT',rateBps:1900,display:'GROSS',testOnly:true},rules:[{serviceId:service.id,rateCents:10000}]});await execute(owner,'price_book.approve',{id:book.id});book=await execute(owner,'price_book.activate',{id:book.id});
  let lead=await execute(client,'lead.create',{contact:{name:'Synthetic customer',email:'d07@example.test'},serviceIds:[service.id],source:{channel:'WEB'},facts:{customerType:'B2C',propertyType:'BUILDING',address:'Synthetic site',desiredPeriod:'October',quantityMilli:1000}});lead=await execute(client,'lead.own_qualify',{id:lead.id,facts:{}});
  let quote=await execute(owner,'quote.create',{leadId:lead.id,priceBookId:book.id,lines:[{serviceId:service.id,quantityMilli:1000}],expiresAt:'2027-01-01T00:00:00.000Z',scope:'Synthetic D07 agreed work',legalTemplateId:'SYNTHETIC_TEMPLATE',pricingModel:'FIXED',certainty:'CONTRACT_PRICE'});await execute(owner,'quote.approve',{id:quote.id,reviewReason:'Explicit synthetic review'});quote=await execute(owner,'quote.send',{id:quote.id});const accepted=await execute(client,'quote.accept',{id:quote.id,quoteVersion:1});order=accepted.order;
  await db.transaction(company,'SYNTHETIC_D07_SITE',tx=>tx.add('site',{name:'Synthetic D07 site',code:'D07',address:'Synthetic site address',customerId:order.data.customerId,active:true,synthetic:true},'site'));
  const startAt=new Date(Date.now()+86400000).toISOString(),endAt=new Date(Date.now()+90000000).toISOString(),reservation=await execute(owner,'dispatch.reserve',{orderId:order.id,employeeIds:['employee'],startAt,endAt});
  const assigned=await execute(owner,'dispatch.assign',{orderId:order.id,reservationId:reservation.id,siteId:'site'});order=assigned.order;assignment=assigned.assignment;task=(await rows('task')).find(t=>t.data.orderId===order.id)!;worker=await engine.getActor('worker',company);foreman=await engine.getActor('foreman',company);
 });
 async function scheduled(){await execute(worker,'crew_assignment.acknowledge',{id:assignment.id,employeeId:'employee'});return row('order',order.id);}
 async function started(){await scheduled();return execute(worker,'shift.start',{siteId:'site',taskId:task.id});}
 async function submittedAndReviewed(){await started();await execute(worker,'task.start',{taskId:task.id});await execute(worker,'task.worklog',{taskId:task.id,quantityMilli:1000,description:'Explicit synthetic completed work'});await execute(worker,'task.submit',{taskId:task.id});await execute(foreman,'order.submit',{id:order.id,reason:'Synthetic foreman submits complete current scope',remainingTaskIds:[]});await execute(owner,'task.review',{taskId:task.id,decision:'ACCEPT'});return execute(owner,'order.review',{id:order.id,reason:'Independent synthetic QC',remainingTaskIds:[]});}
 async function publishedReport(){await submittedAndReviewed();await db.transaction(company,'SYNTHETIC_LEGAL_FIXTURE_NOT_COMPANY_APPROVAL',tx=>tx.add('legal_approval',{subject:'WORK_ACCEPTANCE_TEMPLATE',status:'APPROVED',active:true,synthetic:true},'synthetic-legal'));
  const report=await execute(foreman,'report.create',{siteId:'site',customerId:order.data.customerId,orderId:order.id,periodStart:new Date(Date.now()-3600000).toISOString(),periodEnd:new Date(Date.now()+3600000).toISOString(),documentType:'Abnahmeprotokoll',taskIds:[task.id],descriptionDe:'Synthetischer Leistungsstand fuer isolierte QA.',legalApprovalId:'synthetic-legal'});await execute(owner,'report.review',{reportId:report.id,decision:'PASS',reason:'Independent synthetic report review'});await execute(owner,'report.approve',{reportId:report.id,reason:'Synthetic publication approved'});const version=await execute(owner,'report.publish',{reportId:report.id});await execute(owner,'order.transition',{id:order.id,status:'CLIENT_REVIEW',reason:'Actual internal review and immutable report publication complete',reportVersionId:version.id});return version;
 }
 it('manual advancement produces no SQL effect; the real first shift segment atomically starts its bound order once',async()=>{await scheduled();const before=await fingerprint();await expect(execute(owner,'order.transition',{id:order.id,status:'IN_PROGRESS',reason:'Cannot invent a segment'})).rejects.toMatchObject({code:'INVALID_STATE'});expect(await fingerprint()).toEqual(before);const key=randomUUID(),shift=await execute(worker,'shift.start',{siteId:'site',taskId:task.id},key),current=await row('order',order.id);expect(current.data).toMatchObject({status:'IN_PROGRESS',firstWorkSegmentId:shift.data.activeSegmentId});const repeated=await execute(worker,'shift.start',{siteId:'site',taskId:task.id},key);expect(repeated.id).toBe(shift.id);expect((await row('order',order.id)).version).toBe(current.version);expect((await db.query("SELECT id FROM outbox WHERE company_id=$1 AND type='order.status_changed' AND data->>'source'='FIRST_PERMITTED_WORK_SEGMENT'",[company])).rows).toHaveLength(1);});
 it('employee eligibility failure after the ACK save rolls back ACK, revisions, audit, receipt and outbox',async()=>{await execute(owner,'employee.availability',{employeeId:'employee',availabilityWindows:[],absences:[{startAt:assignment.data.startAt,endAt:assignment.data.endAt,reason:'UNAVAILABLE'}],validUntil:new Date(Date.now()+172800000).toISOString(),source:'Explicit synthetic updated absence after assignment'});const before=await fingerprint();await expect(execute(worker,'crew_assignment.acknowledge',{id:assignment.id,employeeId:'employee'})).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'EMPLOYEE_ABSENT'}});expect(await fingerprint()).toEqual(before);expect((await row('crew_assignment',assignment.id)).data.acknowledgedIds).toEqual([]);expect((await row('order',order.id)).data.status).toBe('CONFIRMED');});
 it('generic Engine ACK by a site-revoked worker with a pending peer creates no ACK/version/audit/outbox/receipt, including replay',async()=>{await db.transaction(company,'SYNTHETIC_REQUIRED_PEER_AND_SCOPE_REVOCATION',async tx=>{await tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['site'],synthetic:true},'peer');await tx.add('employee',{active:true,userId:'peer',synthetic:true},'peer-employee');const current=await tx.get('crew_assignment',assignment.id);await tx.save(current,{...current.data,employeeIds:['employee','peer-employee']},current.version);const user=await tx.get('user','worker');await tx.save(user,{...user.data,siteIds:[]},user.version);});const before=await fingerprint(),key=randomUUID();for(let count=0;count<2;count++)await expect(execute(worker,'crew_assignment.acknowledge',{id:assignment.id,employeeId:'employee'},key)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await fingerprint()).toEqual(before);expect((await row('crew_assignment',assignment.id)).data.acknowledgedIds).toEqual([]);});
 it('current employee deactivation blocks generic cached ACK and crew.start before effects despite unchanged actor sites',async()=>{const key=randomUUID();await execute(worker,'crew_assignment.acknowledge',{id:assignment.id,employeeId:'employee'},key);await db.transaction(company,'SYNTHETIC_CURRENT_HR_DEACTIVATION',async tx=>{const employee=await tx.get('employee','employee');return tx.save(employee,{...employee.data,active:false},employee.version);});const before=await fingerprint();await expect(execute(worker,'crew_assignment.acknowledge',{id:assignment.id,employeeId:'employee'},key)).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'EMPLOYEE_INACTIVE'}});await expect(execute(worker,'crew_assignment.start',{id:assignment.id,employeeId:'employee'})).rejects.toMatchObject({code:'INVALID_STATE'});expect(await fingerprint()).toEqual(before);});
 it('generic dispatcher writes and cached availability deny a canonical foreign-site employee while recommendation omits that employee entirely',async()=>{await db.transaction(company,'SYNTHETIC_SCOPED_DISPATCHER',tx=>tx.add('user',{active:true,roles:['DISPATCHER'],siteIds:['site'],synthetic:true},'dispatcher'));const dispatcher=await engine.getActor('dispatcher',company),key=randomUUID(),input={employeeId:'employee',availabilityWindows:[],validUntil:new Date(Date.now()+172800000).toISOString(),source:'Synthetic site-scoped availability'};await execute(dispatcher,'employee.availability',input,key);await db.transaction(company,'SYNTHETIC_CANONICAL_EMPLOYEE_SITE_CHANGE',async tx=>{await tx.add('site',{active:true,customerId:order.data.customerId,synthetic:true},'foreign-site');const user=await tx.get('user','worker');await tx.save(user,{...user.data,siteIds:['foreign-site']},user.version);const employee=await tx.get('employee','employee');await tx.save(employee,{...employee.data,siteIds:['site'],businessCode:'PRIVATE_FOREIGN_EMPLOYEE',skills:[{id:'PRIVATE_FOREIGN_SKILL',verified:true}]},employee.version);});const before=await fingerprint();await expect(execute(dispatcher,'employee.availability',input,key)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(execute(dispatcher,'employee.availability',input)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(execute(dispatcher,'dispatch.reserve',{orderId:order.id,employeeIds:['employee'],startAt:new Date(Date.now()+259200000).toISOString(),endAt:new Date(Date.now()+262800000).toISOString()})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await fingerprint()).toEqual(before);const recommendation=await execute(dispatcher,'dispatch.recommend',{orderId:order.id,startAt:new Date(Date.now()+259200000).toISOString(),endAt:new Date(Date.now()+262800000).toISOString()});expect(recommendation.available).toEqual([]);expect(recommendation.excluded).toEqual([]);expect(JSON.stringify(recommendation)).not.toContain('PRIVATE_FOREIGN');});
 it('generic availability and cached receipt reject the dispatcher after its site is revoked without changing the target employee',async()=>{await db.transaction(company,'SYNTHETIC_DISPATCHER_SCOPE',tx=>tx.add('user',{active:true,roles:['DISPATCHER'],siteIds:['site'],synthetic:true},'dispatcher'));const dispatcher=await engine.getActor('dispatcher',company),key=randomUUID(),input={employeeId:'employee',availabilityWindows:[],validUntil:new Date(Date.now()+172800000).toISOString(),source:'Synthetic initial allowed availability'};await execute(dispatcher,'employee.availability',input,key);await db.transaction(company,'SYNTHETIC_ACTOR_SITE_REVOCATION',async tx=>{const user=await tx.get('user','dispatcher');return tx.save(user,{...user.data,siteIds:[]},user.version);});const before=await fingerprint();await expect(execute(dispatcher,'employee.availability',input,key)).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(execute(dispatcher,'employee.availability',input)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await fingerprint()).toEqual(before);});
 it('pausing rejects new order work and preserves its original stage; cancellation keeps actual segments and work logs',async()=>{const shift=await started();await execute(worker,'task.start',{taskId:task.id});await execute(worker,'task.worklog',{taskId:task.id,quantityMilli:500,description:'Synthetic actual command work fact'});const paused=await execute(owner,'order.transition',{id:order.id,status:'PAUSED',reason:'Synthetic access restriction'});expect(paused.data.resume_state).toBe('IN_PROGRESS');const before=await fingerprint();await expect(execute(worker,'shift.activity',{shiftId:shift.id,activity:'SERVICE_TASK',siteId:'site',taskId:task.id})).rejects.toMatchObject({code:'INVALID_STATE'});expect(await fingerprint()).toEqual(before);const segments=await rows('time_segment'),logs=await rows('worklog');await execute(owner,'order.transition',{id:order.id,status:'CANCELLED',reason:'Synthetic recorded cancellation'});expect(await rows('time_segment')).toEqual(segments);expect(await rows('worklog')).toEqual(logs);expect((await row('crew_assignment',assignment.id)).data.status).toBe('STARTED');});
 it('a real report receipt cannot close the order, but actual exact report work acceptance can, without changing payment',async()=>{const version=await publishedReport(),receipt=await execute(client,'report.ack',{reportVersionId:version.id,type:'DOCUMENT_RECEIPT',decision:'CONFIRMED',statement:'Synthetic receipt only'}),before=await fingerprint();await expect(execute(owner,'order.transition',{id:order.id,status:'CLOSED',reason:'Receipt cannot mean acceptance',closureBasis:'CONTRACTUAL_ACCEPTANCE',acknowledgmentId:receipt.id})).rejects.toMatchObject({code:'NEEDS_APPROVAL'});expect(await fingerprint()).toEqual(before);const acceptance=await execute(client,'report.ack',{reportVersionId:version.id,type:'WORK_ACCEPTANCE',decision:'CONFIRMED',statement:'Explicit synthetic QA work acceptance, not actual customer approval'}),closed=await execute(owner,'order.transition',{id:order.id,status:'CLOSED',reason:'Exact synthetic work acceptance',closureBasis:'CONTRACTUAL_ACCEPTANCE',acknowledgmentId:acceptance.id});expect(closed.data).toMatchObject({status:'CLOSED',billing:{paidCents:0},closure:{acknowledgmentId:acceptance.id,reportVersionId:version.id}});expect((await rows('order_transition')).every(t=>t.data.immutable===true)).toBe(true);});
 it('a real open defect blocks closure atomically and keeps the original accepted task immutable',async()=>{await publishedReport();const accepted=await row('task',task.id);await execute(owner,'defect.create',{taskId:task.id,externalKey:'SYNTHETIC_DEFECT',description:'Synthetic blocking defect',severity:'HIGH'});const before=await fingerprint();await expect(execute(owner,'order.transition',{id:order.id,status:'CLOSED',reason:'Cannot bypass blocking defect',closureBasis:'DOCUMENTED_REASON',closureEvidence:'Synthetic documented basis'})).rejects.toMatchObject({code:'NEEDS_APPROVAL',details:{reason:'OPEN_BLOCKING_DEFECTS'}});expect(await fingerprint()).toEqual(before);expect(await row('task',task.id)).toEqual(accepted);});
});
