import {afterAll,beforeAll,beforeEach,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Database} from '../apps/api/database.ts';
import {Engine} from '../apps/api/engine.ts';
import type {Actor,Data,Entity} from '../packages/domain/core.ts';

// Real PostgreSQL only. Missing DATABASE_URL is NOT_RUN, never a synthetic SQL pass.
const sql=process.env.DATABASE_URL?describe:describe.skip;
sql('V4 payroll and payout PostgreSQL atomic contracts',()=>{
 let db:Database,engine:Engine,company:string,creator:Actor,approver:Actor,employee:Actor,reconciler:Actor,other:Actor;
 const ids={creator:'v4-accountant-create',approver:'v4-finance-reviewer',employee:'v4-payee',reconciler:'v4-accountant-reconcile',other:'v4-other-payee',timesheet:'v4-approved-timesheet',payslip:'v4-payslip'};
 const call=(a:Actor,name:string,input:Data,key=randomUUID(),version?:number)=>engine.execute(a,name,{input,idempotency_key:key,expected_version:version});
 const list=(kind:string)=>db.transaction(company,ids.creator,tx=>tx.list(kind));
 const get=(kind:string,id:string)=>db.transaction(company,ids.creator,tx=>tx.get(kind,id));
 beforeAll(async()=>{db=new Database();await db.query('SELECT 1');engine=new Engine(db,'TEST');});
 beforeEach(async()=>{
  company=`qa-payroll-v4-${randomUUID()}`;
  await db.transaction(company,'QA_FIXTURE',async tx=>{
   await tx.add('company',{legalName:'Synthetic KNABA payroll contract GmbH',address:'Synthetic Berlin',synthetic:true},company);
   await tx.add('site',{active:true,name:'Synthetic assigned site'},'site');
   await tx.add('user',{name:'Synthetic preparing accountant',active:true,roles:['ACCOUNTANT'],siteIds:['site'],permissions:['scope.company']},ids.creator);
   await tx.add('user',{name:'Synthetic separate finance director',active:true,roles:['DIRECTOR'],siteIds:['site'],permissions:['finance.payroll.approve','finance.payout.approve']},ids.approver);
   await tx.add('user',{name:'Synthetic beneficiary',active:true,roles:['EMPLOYEE'],siteIds:['site'],permissions:[]},ids.employee);
   await tx.add('user',{name:'Synthetic different accountant',active:true,roles:['ACCOUNTANT'],siteIds:['site'],permissions:[]},ids.reconciler);
   await tx.add('user',{name:'Synthetic other beneficiary',active:true,roles:['EMPLOYEE'],siteIds:['site'],permissions:[]},ids.other);
   await tx.add('timesheet',{employeeId:ids.employee,state:'APPROVED',approvedBy:ids.approver,periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z',payableSeconds:27000,segmentSnapshot:[{id:'approved-work',activity:'WORKING',siteId:'site',startAt:'2026-10-01T08:00:00.000Z',endAt:'2026-10-01T15:30:00.000Z',seconds:27000}]},ids.timesheet);
   await tx.add('media_asset',{employeeId:ids.employee,visibility:'CONFIDENTIAL',stage:'DOCUMENT',state:'RECEIVED'},ids.payslip);
  });
  [creator,approver,employee,reconciler,other]=await Promise.all(Object.values(ids).slice(0,5).map(id=>engine.getActor(id,company)));
 });
 afterAll(async()=>{await db?.close();});
 const rate=()=>call(creator,'payroll.rate',{employeeId:ids.employee,type:'HOURLY',rateCents:2000,effectiveAt:'2026-01-01T00:00:00.000Z',reason:'Synthetic approved hourly contract'});
 async function verified(approve=true){const r=await rate(),c=await call(creator,'payroll.calculation',{timesheetId:ids.timesheet,rateId:r.id,reason:'Actual SQL approved source fixture'});await call(creator,'payroll.official',{calculationId:c.id,documentMediaId:ids.payslip,netCents:100000,grossCents:120000,providerReference:'synthetic-verified-net-v1',verificationReference:'Synthetic checked accountant source'});if(approve)await call(approver,'payroll.approve',{calculationId:c.id,reason:'Different explicit authorized finance approver'});return get('payroll_calculation',c.id);}
 const create=(c:Entity,amountCents=40000)=>call(creator,'payout.create',{calculationId:c.id,amountCents,method:'CASH',reason:'Synthetic cash allocation'});
 async function recorded(c:Entity){const p=await create(c);await call(creator,'payout.submit',{payoutId:p.id,reason:'Submit for different financial approver'});await call(approver,'payout.approve',{payoutId:p.id,reason:'Different payout approver'});await call(creator,'payout.record',{payoutId:p.id,transferredAt:'2026-10-05T09:00:00.000Z',evidenceReference:'synthetic-recorded-cash-doc'});return get('payout',p.id);}

 it('AC-44 actual approved segment splits into frozen effective rates; command replay has one calculation, audit and outbox',async()=>{
  const r=await rate(),later=await call(creator,'payroll.rate',{employeeId:ids.employee,type:'HOURLY',rateCents:2500,effectiveAt:'2026-10-01T12:00:00.000Z',reason:'Synthetic approved midday wage version'}),before=await get('timesheet',ids.timesheet),key=randomUUID(),input={timesheetId:ids.timesheet,rateId:r.id,reason:'SQL exact automatic split'};
  const c=await call(creator,'payroll.calculation',input,key),replay=await call(creator,'payroll.calculation',input,key);expect(replay).toEqual(c);expect(c.data.baseCents).toBe(16750);expect(c.data.rateTotals.map((row:Data)=>[row.rateId,row.amountCents])).toEqual([[r.id,8000],[later.id,8750]]);expect(c.data.remunerationLines.map((line:Data)=>line.eligibleMilliseconds)).toEqual([14400000,12600000]);expect(await get('timesheet',ids.timesheet)).toEqual(before);expect(await list('payroll_calculation')).toHaveLength(1);
  expect((await db.query('SELECT id FROM outbox WHERE company_id=$1 AND type=$2',[company,'payroll.preliminary_calculated'])).rows).toHaveLength(1);expect((await db.query('SELECT id FROM audit_log WHERE company_id=$1 AND action=$2',[company,'COMMAND:payroll.calculation'])).rows).toHaveLength(1);
 });
 it('decimal EUR rate uses exact persisted rational cents and rounds only the employee/rate/period total',async()=>{
  const r=await call(creator,'payroll.rate',{employeeId:ids.employee,type:'HOURLY',rate:'20.125',effectiveAt:'2026-01-01T00:00:00.000Z',reason:'Synthetic exact decimal wage contract'}),c=await call(creator,'payroll.calculation',{timesheetId:ids.timesheet,rateId:r.id,reason:'No early cent rounding'});expect((await get('rate_history',r.id)).data).toMatchObject({rateDecimalEuros:'20.125',rateCentsNumerator:'4025',rateCentsDenominator:'2'});expect(c.data.rateTotals[0].unroundedCents).toEqual({numerator:'108675000000',denominator:'7200000'});expect(c.data.baseCents).toBe(15094);await expect(call(creator,'payroll.rate',{employeeId:ids.employee,type:'HOURLY',rate:'2.00',rateCents:200,effectiveAt:'2026-09-01T00:00:00.000Z',reason:'Ambiguous boundary'})).rejects.toBeDefined();expect(await list('rate_history')).toHaveLength(1);
 });
 it('verified monthly accountant import stores exact source facts, needs independent approval and survives replay without duplicated official documents',async()=>{
  const key=randomUUID(),input={timesheetId:ids.timesheet,documentMediaId:ids.payslip,netCents:185000,grossCents:260000,providerReference:'synthetic-monthly-import-v4',verificationReference:'Synthetic verified accountant source',reason:'No invented monthly proration'};const c=await call(creator,'payroll.import',input,key);expect(await call(creator,'payroll.import',input,key)).toEqual(c);expect(c.data).toMatchObject({baseCents:null,calculationType:'ACCOUNTANT_IMPORTED_PAYROLL',pricingSource:'VERIFIED_ACCOUNTANT_IMPORT',payableCents:185000,approvalState:'CALCULATED'});expect(await list('official_payslip')).toHaveLength(1);await expect(create(c)).rejects.toMatchObject({code:'PAYROLL_APPROVAL_REQUIRED'});await call(approver,'payroll.approve',{calculationId:c.id,reason:'Independent monthly payroll approval'});await call(approver,'payroll.lock',{calculationId:c.id,reason:'Close approved imported period'});expect((await get('payroll_calculation',c.id)).data.approvalState).toBe('LOCKED');expect(await list('payroll_lock')).toHaveLength(1);expect((await create(c)).data.amountCents).toBe(40000);
 });
 it('generic domain payout path refuses unapproved verified payroll and own payroll approval, atomically',async()=>{
  const c=await verified(false);await expect(create(c)).rejects.toMatchObject({code:'PAYROLL_APPROVAL_REQUIRED'});await expect(call(creator,'payroll.approve',{calculationId:c.id,reason:'Preparing accountant self approval'})).rejects.toMatchObject({code:'SELF_APPROVAL_DENIED'});expect(await list('payout')).toEqual([]);expect(await list('payout_allocation')).toEqual([]);expect(await list('payroll_approval')).toEqual([]);await call(approver,'payroll.approve',{calculationId:c.id,reason:'Explicit different scoped director'});expect((await create(c)).data.amountCents).toBe(40000);
 });
 it('AC-47 concurrent approved allocations cannot reserve EUR1400 from EUR1000 net',async()=>{
  const c=await verified(),a=await create(c,70000),b=await create(c,70000);for(const payout of [a,b])await call(creator,'payout.submit',{payoutId:payout.id,reason:'Concurrent pending allocation'});const results=await Promise.allSettled([call(approver,'payout.approve',{payoutId:a.id,reason:'Concurrent first approval'}),call(approver,'payout.approve',{payoutId:b.id,reason:'Concurrent second approval'})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason).toMatchObject({code:'PAYOUT_EXCEEDS_BALANCE'});expect((await list('payout')).filter(p=>p.data.state==='APPROVED')).toHaveLength(1);expect((await call(creator,'payroll.balance',{calculationId:c.id})).uncommittedCents).toBe(30000);
 });
 it('actual pending approval lifecycle prevents beneficiary approval and cancellation of recorded facts',async()=>{
  const c=await verified(),p=await create(c);await expect(call(approver,'payout.approve',{payoutId:p.id,reason:'Skip pending transition'})).rejects.toMatchObject({code:'INVALID_STATE'});await call(creator,'payout.submit',{payoutId:p.id,reason:'Explicit pending payout request'});await db.transaction(company,ids.creator,async tx=>{const user=await tx.get('user',ids.employee);await tx.save(user,{...user.data,permissions:['finance.payout.approve']});});await expect(call(employee,'payout.approve',{payoutId:p.id,reason:'Own beneficiary cannot approve'})).rejects.toMatchObject({code:'SELF_APPROVAL_DENIED'});await call(approver,'payout.approve',{payoutId:p.id,reason:'Different creator and recipient'});expect((await call(creator,'payroll.balance',{calculationId:c.id})).uncommittedCents).toBe(60000);await call(creator,'payout.cancel',{payoutId:p.id,reason:'Responsible person confirms not executed',notExecutedConfirmed:true});expect((await call(creator,'payroll.balance',{calculationId:c.id})).uncommittedCents).toBe(100000);expect((await get('payout',p.id)).data).toMatchObject({state:'CANCELLED',cancelledFromState:'APPROVED'});expect((await db.query('SELECT version,data FROM aggregate_revisions WHERE company_id=$1 AND kind=$2 AND id=$3 ORDER BY version',[company,'payout',p.id])).rows.map(r=>r.data.state)).toEqual(['DRAFT','PENDING_APPROVAL','APPROVED','CANCELLED']);const actual=await recorded(c);await expect(call(creator,'payout.cancel',{payoutId:actual.id,reason:'Actual transfer cannot disappear',notExecutedConfirmed:true})).rejects.toMatchObject({code:'INVALID_STATE'});expect((await get('payout',actual.id)).data.state).toBe('RECORDED');
 });
 it('AC-46 recorded EUR400, own EUR300 statement and controlled reconciliation preserve EUR100 dispute without another payout',async()=>{
  const c=await verified(),p=await recorded(c),key=randomUUID(),input={payoutId:p.id,decision:'PARTIAL',receivedCents:30000,statement:'Synthetic beneficiary confirms only EUR300.'};const [first,retry]=await Promise.all([call(employee,'payout.ack',input,key),call(employee,'payout.ack',input,key)]);expect(retry).toEqual(first);expect(await list('payout_receipt')).toHaveLength(1);await call(reconciler,'payout.reconcile',{payoutId:p.id,receiptId:first.id,outcome:'DISCREPANCY_RECORDED',evidenceReference:'synthetic-document-and-statement-review',reason:'Record discrepancy; no automatic repeat issuance'});expect((await get('payout',p.id)).data).toMatchObject({state:'RECONCILED',amountCents:40000,employeeStatedReceivedCents:30000,ackState:'PARTIALLY_RECEIVED'});expect(await call(creator,'payroll.balance',{calculationId:c.id})).toMatchObject({recordedCents:40000,employeeAcknowledgedCents:30000,disputedCents:10000,outstandingCents:60000,uncommittedCents:60000});expect(await list('payout')).toHaveLength(1);
 });
 it('append-only statement amendment reopens reconciliation and cannot alter original signed receipt/history',async()=>{
  const c=await verified(),p=await recorded(c),first=await call(employee,'payout.ack',{payoutId:p.id,decision:'PARTIAL',receivedCents:30000,statement:'Synthetic first statement.',signature:'Synthetic current signature'}),rec=await call(reconciler,'payout.reconcile',{payoutId:p.id,receiptId:first.id,outcome:'DISCREPANCY_RECORDED',evidenceReference:'synthetic-first-review',reason:'Keep original discrepancy'}),before=await get('payout',p.id),second=await call(employee,'payout.ack_amend',{payoutId:p.id,previousReceiptId:first.id,decision:'FULL',statement:'Synthetic correction: full EUR400 received.'},randomUUID(),before.version);expect(second.data).toMatchObject({statementVersion:2,previousReceiptId:first.id,receivedCents:40000,confirmedBy:ids.employee,immutable:true});expect(second.data.signature).toBeUndefined();expect(await get('payout_receipt',first.id)).toEqual(first);expect(await get('payout_reconciliation',rec.id)).toEqual(rec);expect((await get('payout',p.id)).data).toMatchObject({state:'RECORDED',receiptId:second.id,reconciliationId:null,previousReconciliationId:rec.id});await expect(call(employee,'payout.ack_amend',{payoutId:p.id,previousReceiptId:first.id,decision:'DISPUTED',statement:'Stale first statement'})).rejects.toMatchObject({code:'VERSION_CONFLICT'});expect(await list('payout_receipt')).toHaveLength(2);
  for(const kind of ['payout_receipt','payout_reconciliation','payroll_approval','payout_allocation','official_payslip','rate_history']){const row=(await list(kind))[0]!;await expect(db.transaction(company,ids.creator,tx=>tx.save(row,{...row.data,syntheticTampered:true}))).rejects.toThrow();expect(await get(kind,row.id)).toEqual(row);}
 });
 it('concurrent stale reconciliation and statement amendment produce one atomic effect, no stale full-match',async()=>{
  const c=await verified(),p=await recorded(c),first=await call(employee,'payout.ack',{payoutId:p.id,decision:'FULL',statement:'First synthetic full receipt.'}),version=(await get('payout',p.id)).version,results=await Promise.allSettled([call(reconciler,'payout.reconcile',{payoutId:p.id,receiptId:first.id,outcome:'MATCHED',evidenceReference:'synthetic-current-source',reason:'Current full-match review'},randomUUID(),version),call(employee,'payout.ack_amend',{payoutId:p.id,previousReceiptId:first.id,decision:'PARTIAL',receivedCents:30000,statement:'Concurrent correction to EUR300.'},randomUUID(),version)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((results.find(r=>r.status==='rejected') as PromiseRejectedResult).reason).toMatchObject({code:'VERSION_CONFLICT'});const saved=await get('payout',p.id);if(saved.data.state==='RECONCILED'){expect(saved.data.receiptId).toBe(first.id);expect(await list('payout_receipt')).toHaveLength(1);expect(await list('payout_reconciliation')).toHaveLength(1);}else{expect(saved.data.ackState).toBe('PARTIALLY_RECEIVED');expect(await list('payout_receipt')).toHaveLength(2);expect(await list('payout_reconciliation')).toEqual([]);}
 });
 it('other employee and finance administrator cannot acknowledge/amend another beneficiary; read ACLs protect all new finance facts',async()=>{
  const c=await verified(),p=await recorded(c),first=await call(employee,'payout.ack',{payoutId:p.id,decision:'FULL',statement:'Own synthetic full receipt.'});await expect(call(other,'payout.ack_amend',{payoutId:p.id,previousReceiptId:first.id,decision:'FULL',statement:'Another beneficiary statement'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await db.transaction(company,ids.creator,async tx=>{const user=await tx.get('user',ids.creator);await tx.save(user,{...user.data,permissions:[...user.data.permissions,'finance.payout.ack']});});await expect(call(creator,'payout.ack_amend',{payoutId:p.id,previousReceiptId:first.id,decision:'FULL',statement:'Administrator cannot impersonate employee'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await call(reconciler,'payout.reconcile',{payoutId:p.id,receiptId:first.id,outcome:'MATCHED',evidenceReference:'synthetic-read-scope',reason:'Authorized current match'});for(const kind of ['payroll_approval','payout_receipt','payout_reconciliation']){expect(await engine.readEntities(other,kind)).toEqual([]);expect(await engine.readEntities(employee,kind)).toHaveLength(1);}
 });
 it('old actor and idempotent receipt replay are denied immediately after payout authorization revocation',async()=>{
  const c=await verified(),p=await recorded(c),key=randomUUID(),input={payoutId:p.id,decision:'FULL',statement:'Own synthetic confirmed receipt.'};await call(employee,'payout.ack',input,key);await db.transaction(company,ids.creator,async tx=>{const user=await tx.get('user',ids.employee);await tx.save(user,{...user.data,roles:['AUDITOR'],permissions:[]});});await expect(call(employee,'payout.ack',input,key)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await list('payout_receipt')).toHaveLength(1);
 });
 it('a reconciled transfer reversed by a distinct authorized person keeps its original transfer/receipt/reconciliation evidence',async()=>{
  const c=await verified(),p=await recorded(c),receipt=await call(employee,'payout.ack',{payoutId:p.id,decision:'FULL',statement:'Synthetic original paid amount.'}),reconciliation=await call(reconciler,'payout.reconcile',{payoutId:p.id,receiptId:receipt.id,outcome:'MATCHED',evidenceReference:'synthetic-original-reconciliation',reason:'Original matches'});await expect(call(approver,'payout.reverse',{payoutId:p.id,reason:'Same approver reversal not allowed',evidenceReference:'synthetic-reversal'})).rejects.toMatchObject({code:'SELF_APPROVAL_DENIED'});const reversal=await call(reconciler,'payout.reverse',{payoutId:p.id,reason:'Synthetic correction with separately verified evidence',evidenceReference:'synthetic-correcting-entry'});expect(reversal.data).toMatchObject({payoutId:p.id,amountCents:40000,immutable:true});expect((await get('payout',p.id)).data).toMatchObject({state:'REVERSED',amountCents:40000,evidenceReference:'synthetic-recorded-cash-doc'});expect(await get('payout_receipt',receipt.id)).toEqual(receipt);expect(await get('payout_reconciliation',reconciliation.id)).toEqual(reconciliation);expect((await call(creator,'payroll.balance',{calculationId:c.id})).uncommittedCents).toBe(100000);
 });
});
