import { describe, expect, it } from 'vitest';
import { resourcesCommands, exactBaseQuantity, stockBalance, reportSnapshotHash } from '../packages/domain/resources';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { Readable } from 'node:stream';
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { PostgresPrivateBlobStore, S3PrivateBlobStore, createPrivateBlobStore } from '../packages/storage/index.ts';
import { archiveReportArtifact, exportReportXlsx, renderReportCsv, renderReportPdf, reportExportSnapshot } from '../apps/api/exporters.ts';
import { DomainError, type Actor, type CommandContext, type Data, type Entity, type Transaction } from '../packages/domain/core';

// Independent reader: Python openpyxl reads actual OOXML rather than mirroring our writer.
function readWorkbook(bytes:Buffer):any {const folder=mkdtempSync(join(tmpdir(),'knaba-xlsx-')),path=join(folder,'report.xlsx');writeFileSync(path,bytes);try{return JSON.parse(execFileSync('python3',['-c',`
import sys,io,json,zipfile,hashlib,posixpath,warnings,xml.etree.ElementTree as ET
from openpyxl import load_workbook
data=open(sys.argv[1],'rb').read()
with zipfile.ZipFile(io.BytesIO(data)) as archive:
 assert archive.testzip() is None
 names=archive.namelist()
 assert len(names)==len(set(names))
 assert {'[Content_Types].xml','_rels/.rels','xl/workbook.xml','xl/styles.xml','docProps/core.xml'}.issubset(names)
 for path in names:
  if path.endswith('.xml') or path.endswith('.rels'): ET.fromstring(archive.read(path))
  if path.endswith('.rels'):
   base='' if path=='_rels/.rels' else posixpath.dirname(posixpath.join(posixpath.dirname(posixpath.dirname(path)),posixpath.basename(path)[:-5]))
   for rel in ET.fromstring(archive.read(path)):
    if rel.attrib.get('TargetMode')!='External':
     target=posixpath.normpath(posixpath.join(base,rel.attrib['Target'].lstrip('/'))) if not rel.attrib['Target'].startswith('/') else rel.attrib['Target'].lstrip('/')
     assert target in names,(path,target)
with warnings.catch_warnings(record=True) as caught:
 warnings.simplefilter('always')
 workbook=load_workbook(io.BytesIO(data),data_only=False)
 assert not caught,[str(w.message) for w in caught]
sheets={}
for sheet in workbook:
 rows=[[{'value':c.value,'type':c.data_type,'numberFormat':c.number_format} for c in row] for row in sheet.iter_rows()]
 assert not any(c['type']=='f' for row in rows for c in row)
 images=[{'sha256':hashlib.sha256(image._data()).hexdigest(),'row':image.anchor._from.row,'column':image.anchor._from.col} for image in sheet._images]
 sheets[sheet.title]={'rows':rows,'images':images,'freeze':sheet.freeze_panes,'filter':sheet.auto_filter.ref,'headerBold':sheet['A1'].font.bold,'headerFill':sheet['A1'].fill.fgColor.rgb,'headerColor':sheet['A1'].font.color.rgb,'wrap':sheet['A2'].alignment.wrap_text,'vertical':sheet['A2'].alignment.vertical}
# A second independent load/save/load also exercises drawing/image relationships.
copy=load_workbook(io.BytesIO(data)); saved=io.BytesIO(); copy.save(saved); restored=load_workbook(io.BytesIO(saved.getvalue()))
assert restored.sheetnames==workbook.sheetnames
assert sum(len(s._images) for s in restored)==sum(len(s._images) for s in workbook)
print(json.dumps({'sheets':sheets,'description':workbook.properties.description,'created':workbook.properties.created.isoformat(),'modified':workbook.properties.modified.isoformat()},ensure_ascii=False))
`,path],{timeout:10000,maxBuffer:5*1024*1024,stdio:['ignore','pipe','pipe']}).toString('utf8'));}finally{rmSync(folder,{recursive:true,force:true});}}

// Company-filtered transactional fixture; PostgreSQL concurrency/outbox integration is tested separately.
class MemoryTransaction implements Transaction {
 rows=new Map<string,Entity>();events:{type:string,data:Data}[]=[];sequence=0;
 constructor(public companyId='company'){}
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>> {const e=this.rows.get(`${kind}:${id}`);if(!e||e.companyId!==this.companyId)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(e) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]> {return [...this.rows.values()].filter(e=>e.kind===kind&&e.companyId===this.companyId).map(e=>structuredClone(e) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`${kind}_${++this.sequence}`):Promise<Entity<T>> {if(this.rows.has(`${kind}:${id}`))throw new DomainError('VERSION_CONFLICT');const e={id,kind,companyId:this.companyId,data:structuredClone(data),version:1,createdAt:'2026-10-05T10:00:00.000Z',updatedAt:'2026-10-05T10:00:00.000Z'};this.rows.set(`${kind}:${id}`,e);return structuredClone(e) as Entity<T>;}
 async save<T extends Data=Data>(entity:Entity<T>,data:T,expectedVersion=entity.version):Promise<Entity<T>> {const current=await this.get<T>(entity.kind,entity.id);if(current.version!==expectedVersion)throw new DomainError('VERSION_CONFLICT');const next={...current,version:current.version+1,data:structuredClone(data)};this.rows.set(`${entity.kind}:${entity.id}`,next);return structuredClone(next);}
 async event(type:string,data:Data) {this.events.push({type,data:structuredClone(data)});}
}
const owner:Actor={userId:'owner',companyId:'company',roles:['OWNER'],permissions:['*','scope.company'],siteIds:[],customerIds:[],warehouseIds:[],mfaVerified:true};
const manager:Actor={...owner,userId:'manager',roles:['DIRECTOR']};
const employee:Actor={...owner,userId:'employee',roles:['EMPLOYEE'],permissions:['inventory.request','inventory.use','finance.payout.ack'],siteIds:['site']};
const accountant:Actor={...owner,userId:'accountant',roles:['ACCOUNTANT'],permissions:['finance.accountant','finance.payroll']};
const customer:Actor={...owner,userId:'customer-user',roles:['CUSTOMER'],permissions:['report.ack'],customerIds:['customer'],siteIds:['site']};
function context(tx:MemoryTransaction,actor=owner,now='2026-10-05T10:00:00.000Z'):CommandContext {return {tx,actor,now,idempotencyKey:'test',requireSite:(siteId)=>{if(!actor.roles.some(r=>['OWNER','DIRECTOR','OPERATIONS_MANAGER'].includes(r))&&!actor.siteIds.includes(siteId))throw new DomainError('ACCESS_DENIED');},requireOwn:(userId)=>{if(actor.userId!==userId&&!actor.roles.some(r=>['OWNER','DIRECTOR','OPERATIONS_MANAGER','ACCOUNTANT'].includes(r)))throw new DomainError('ACCESS_DENIED');}};}
async function run(ctx:CommandContext,name:string,input:Data) {const def=resourcesCommands[name];const tx=ctx.tx as MemoryTransaction,rows=structuredClone(tx.rows),events=structuredClone(tx.events);try{return await def.handler(ctx,def.schema.parse(input));}catch(error){tx.rows=rows;tx.events=events;throw error;}}
async function fixture(){const tx=new MemoryTransaction();for(const actor of [owner,manager,employee,accountant])await tx.add('user',{employeeCode:actor.userId==='employee'?'KNB-E-001':'KNB-M-001',active:true},actor.userId);await tx.add('company',{legalName:'KNABA DE TEST GmbH',address:'Synthetic Berlin address',operatingMode:'TEST'},'company');await tx.add('customer',{name:'Synthetic Customer',address:'Synthetic address'},'customer');await tx.add('site',{code:'KNB-014',name:'Synthetic Site',customerId:'customer',address:'Synthetic Berlin'},'site');await tx.add('task',{siteId:'site',locationId:'location',titleDe:'Bodenreinigung',state:'ACCEPTED',acceptedQuantityMilli:100000,unit:'m2'},'task');await tx.add('task_review',{taskId:'task',decision:'ACCEPT',quantityMilli:100000},'review');await tx.add('location',{siteId:'site',active:true},'location');await tx.add('worklog',{taskId:'task',siteId:'site'},'worklog');await tx.add('customer_membership',{customerId:'customer',userId:customer.userId,siteIds:['site'],permissions:['VIEW','REPORT_ACK'],active:true},'membership');await tx.add('order',{siteId:'site',customerId:'customer',quoteId:'quote',quoteVersion:1,pricingModel:'FIXED',baseNetCents:120000,approvedChangesNetCents:0,finalNetCents:120000,tax:{rateBps:1900,display:'Brutto'},status:'CLOSED'},'order');const ctx=context(tx);const material=await run(ctx,'material.create',{sku:'FLOOR-5L',name:'Bodenreiniger',baseUnit:'ml',packagingBase:5000});const main=await run(ctx,'stock_location.create',{name:'Main',type:'WAREHOUSE'}),site=await run(ctx,'stock_location.create',{name:'Site store',type:'SITE',siteId:'site'});return {tx,ctx,material,main,site};}
async function received(quantity='10'){const f=await fixture();await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.main.id,quantity,unit:'l',reference:'delivery-1',actualCostCents:2000});return f;}
async function approvedRequest(f:Awaited<ReturnType<typeof fixture>>,quantity='5'){let request=await run(context(f.tx,employee),'request.create',{materialId:f.material.id,siteId:'site',taskId:'task',quantity,unit:'l',dueAt:'2026-10-06T12:00:00.000Z',reason:'Bodenreinigung erforderlich'});await run(context(f.tx,employee),'request.submit',{requestId:request.id});request=await run(f.ctx,'request.approve',{requestId:request.id,decision:'APPROVE'});return request;}
async function payrollFixture(){const f=await fixture();await f.tx.add('timesheet',{employeeId:'employee',periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z',state:'APPROVED',payableSeconds:36000,segmentSnapshot:[{siteId:'site',activity:'WORKING',startAt:'2026-10-01T08:00:00.000Z',endAt:'2026-10-01T10:00:00.000Z'}]},'timesheet');const rate=await run(f.ctx,'payroll.rate',{employeeId:'employee',type:'HOURLY',rateCents:10000,effectiveAt:'2026-01-01T00:00:00.000Z',reason:'Synthetic verified wage'});let calculation=await run(f.ctx,'payroll.calculation',{timesheetId:'timesheet',rateId:rate.id,reason:'Synthetic test period'});await f.tx.add('media_asset',{employeeId:'employee',visibility:'CONFIDENTIAL',stage:'DOCUMENT',state:'RECEIVED'},'payslip');await run(context(f.tx,accountant),'payroll.official',{calculationId:calculation.id,documentMediaId:'payslip',netCents:100000,grossCents:120000,providerReference:'synthetic-payslip-1',verificationReference:'Synthetic accountant verification'});await run(context(f.tx,manager),'payroll.approve',{calculationId:calculation.id,reason:'Synthetic independent finance approval'});calculation=await f.tx.get('payroll_calculation',calculation.id);return {...f,rate,calculation};}

describe('exact quantity and inventory',()=>{
 it('converts package and partial liters exactly, rejects density and fractional base units',async()=>{const f=await fixture();expect(exactBaseQuantity(f.material.data,'1','package')).toBe(5000);expect(exactBaseQuantity(f.material.data,'1.5','l')).toBe(1500);expect(()=>exactBaseQuantity(f.material.data,'0.0001','l')).toThrow();expect(()=>exactBaseQuantity(f.material.data,'1','kg')).toThrow();expect(()=>resourcesCommands['stock.receive'].schema.parse({materialId:'m',locationId:'l',quantity:1.5,unit:'l',reference:'r'})).toThrow();});
 it('T-STOCK-01 receipt -> ship -> accept -> use -> return preserves physical and transit quantities',async()=>{const f=await received();const transfer=await run(f.ctx,'stock.ship',{materialId:f.material.id,sourceId:f.main.id,targetId:f.site.id,quantity:'4',unit:'l'});expect(await run(f.ctx,'stock.balance',{materialId:f.material.id,locationId:f.main.id})).toMatchObject({physicalBase:6000,transitBase:4000});expect((await stockBalance(f.ctx,f.material.id,f.site.id)).physicalBase).toBe(0);await run(f.ctx,'stock.accept',{transferId:transfer.id,quantity:'4',unit:'l'});await run(context(f.tx,employee),'stock.use',{materialId:f.material.id,locationId:f.site.id,quantity:'1.5',unit:'l',taskId:'task',worklogId:'worklog',locationNodeId:'location',reference:'usage-1'});const returned=await run(f.ctx,'stock.return',{materialId:f.material.id,sourceId:f.site.id,targetId:f.main.id,quantity:'0.5',unit:'l'});await run(f.ctx,'stock.accept',{transferId:returned.id,quantity:'0.5',unit:'l'});expect((await stockBalance(f.ctx,f.material.id,f.main.id)).physicalBase).toBe(6500);expect((await stockBalance(f.ctx,f.material.id,f.site.id)).physicalBase).toBe(2000);const movements=await f.tx.list('stock_movement');expect(movements).toHaveLength(6);expect((await f.tx.list('material_usage'))[0].data).toMatchObject({quantityBase:1500,internalCostCents:300,clientVisible:false});await expect(run(f.ctx,'stock.use',{materialId:f.material.id,locationId:f.site.id,quantity:'1.5',unit:'l',taskId:'task',reference:'usage-1'})).rejects.toMatchObject({code:'DUPLICATE_EFFECT'});expect(await f.tx.list('stock_movement')).toHaveLength(6);});
 it('partial receive leaves true physical transit and records a discrepancy',async()=>{const f=await received();const t=await run(f.ctx,'stock.ship',{materialId:f.material.id,sourceId:f.main.id,targetId:f.site.id,quantity:'4',unit:'l'});await run(f.ctx,'stock.accept',{transferId:t.id,quantity:'1',unit:'l',discrepancyReason:'Remaining quantity pending'});expect((await f.tx.get('transfer',t.id)).data.state).toBe('DISCREPANCY');expect((await run(f.ctx,'stock.balance',{materialId:f.material.id,locationId:f.site.id}))).toMatchObject({physicalBase:1000,transitBase:3000});await expect(run(f.ctx,'stock.accept',{transferId:t.id,quantity:'4',unit:'l'})).rejects.toMatchObject({code:'RECEIPT_EXCEEDS_SHIPMENT'});});
 it('a duplicate receipt reference cannot add another physical receipt',async()=>{const f=await received();await expect(run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.main.id,quantity:'10',unit:'l',reference:'delivery-1'})).rejects.toMatchObject({code:'DUPLICATE_EFFECT'});expect((await stockBalance(f.ctx,f.material.id,f.main.id)).physicalBase).toBe(10000);});
 it('blocked and expired batches cannot be reserved or used',async()=>{const f=await fixture();const batch=await run(f.ctx,'batch.create',{materialId:f.material.id,code:'damaged',status:'BLOCKED'});await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.site.id,batchId:batch.id,quantity:'5',unit:'l',reference:'blocked-delivery'});expect(await stockBalance(f.ctx,f.material.id,f.site.id)).toMatchObject({physicalBase:5000,blockedBase:5000,freeBase:0});await expect(run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.site.id,batchId:batch.id,quantity:'1',unit:'l',expiresAt:'2026-10-06T00:00:00.000Z'})).rejects.toMatchObject({code:'STOCK_BLOCKED'});await expect(run(f.ctx,'stock.use',{materialId:f.material.id,locationId:f.site.id,batchId:batch.id,quantity:'1',unit:'l',taskId:'task',reference:'x'})).rejects.toMatchObject({code:'STOCK_BLOCKED'});});
 it('two claims cannot reserve the same last two liters',async()=>{const f=await received('2');await run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.main.id,quantity:'2',unit:'l',expiresAt:'2026-10-06T00:00:00.000Z'});await expect(run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.main.id,quantity:'2',unit:'l',expiresAt:'2026-10-06T00:00:00.000Z'})).rejects.toMatchObject({code:'INSUFFICIENT_STOCK'});expect((await stockBalance(f.ctx,f.material.id,f.main.id)).freeBase).toBe(0);});
 it('reservations expire without consumption and release the request commitment',async()=>{const f=await received('4');const request=await approvedRequest(f);await run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.main.id,requestId:request.id,quantity:'3',unit:'l',expiresAt:'2026-10-06T00:00:00.000Z'});expect((await stockBalance(context(f.tx,owner,'2026-10-06T01:00:00.000Z'),f.material.id,f.main.id)).freeBase).toBe(4000);});
 it('inventory custody is not material consumption',async()=>{const f=await fixture();const mop=await run(f.ctx,'material.create',{sku:'MOP',name:'Mop',baseUnit:'pcs',materialType:'INVENTORY'});await run(f.ctx,'stock.receive',{materialId:mop.id,locationId:f.site.id,quantity:'1',unit:'pcs',reference:'mop-1'});await expect(run(f.ctx,'stock.use',{materialId:mop.id,locationId:f.site.id,quantity:'1',unit:'pcs',taskId:'task',reference:'mop-use'})).rejects.toMatchObject({code:'INVENTORY_IS_NOT_CONSUMPTION'});});
 it('stock count preserves subsequent movements and supports counted zero',async()=>{const f=await received();const count=await run(f.ctx,'stock.count.create',{materialId:f.material.id,locationId:f.main.id,quantity:'9',unit:'l',reason:'Physical count discrepancy'});await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.main.id,quantity:'2',unit:'l',reference:'post-count-delivery'});await run(context(f.tx,manager),'stock.count.apply',{countId:count.id,reason:'Verified physical recount'});expect((await stockBalance(f.ctx,f.material.id,f.main.id)).physicalBase).toBe(11000);const zero=await run(f.ctx,'stock.count.create',{materialId:f.material.id,locationId:f.main.id,quantity:'0',unit:'l',reason:'Physical empty count'});await run(context(f.tx,manager),'stock.count.apply',{countId:zero.id,reason:'Verified zero count'});expect((await stockBalance(f.ctx,f.material.id,f.main.id)).physicalBase).toBe(0);});
 it('warehouse role alone never grants another warehouse access',async()=>{const f=await received();await expect(run(context(f.tx,{...employee,roles:['STOREKEEPER']}),'stock.balance',{materialId:f.material.id,locationId:f.main.id})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(context(f.tx,{...employee,roles:['STOREKEEPER'],warehouseIds:[f.main.id]}),'stock.balance',{materialId:f.material.id,locationId:f.main.id})).resolves.toMatchObject({physicalBase:10000});});
});

describe('request and explained procurement',()=>{
 it('T-STOCK-02 a partial reserve does not count the same demand twice',async()=>{const f=await received('4');await run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.main.id,quantity:'1',unit:'l',expiresAt:'2026-10-06T12:00:00.000Z'});const request=await approvedRequest(f);const input={materialId:f.material.id,locationIds:[f.main.id],horizonAt:'2026-10-06T12:00:00.000Z'};expect(await run(f.ctx,'procurement.calculate',input)).toMatchObject({newUnreservedDemand:5000,freeUsableStock:3000,purchaseNeedBase:2000,plannedBase:5000,excessBase:3000});await run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.main.id,requestId:request.id,quantity:'3',unit:'l',expiresAt:'2026-10-06T12:00:00.000Z'});expect(await run(f.ctx,'procurement.calculate',input)).toMatchObject({newUnreservedDemand:2000,freeUsableStock:0,purchaseNeedBase:2000});});
 it('future orders are not physical and overdue inbound is not guaranteed; partial actual receipt is physical',async()=>{const f=await fixture();await approvedRequest(f);const supplier=await run(f.ctx,'supplier.create',{name:'Approved synthetic supplier',approved:true});const request=await run(f.ctx,'procurement.create',{materialId:f.material.id,locationIds:[f.main.id],destinationId:f.main.id,horizonAt:'2026-10-06T12:00:00.000Z',supplierId:supplier.id,unitPriceCents:1000,reason:'Confirmed demand'});const duplicate=await run(f.ctx,'procurement.create',{materialId:f.material.id,locationIds:[f.main.id],destinationId:f.main.id,horizonAt:'2026-10-06T12:00:00.000Z',supplierId:supplier.id,unitPriceCents:1000,reason:'Refreshed demand'});expect(duplicate.id).toBe(request.id);await run(context(f.tx,manager),'procurement.approve',{requisitionId:request.id,budgetCents:1000,reason:'Approved purchase budget'});const order=await run(f.ctx,'procurement.order',{requisitionId:request.id,dueAt:'2026-10-04T12:00:00.000Z',supplierReference:'supplier-order-1',deliveryConfirmed:true});expect(order.data.externalOrderExecuted).toBe(false);expect((await stockBalance(f.ctx,f.material.id,f.main.id)).physicalBase).toBe(0);expect((await run(f.ctx,'procurement.calculate',{materialId:f.material.id,locationIds:[f.main.id],horizonAt:'2026-10-06T12:00:00.000Z'})).freeConfirmedInbound).toBe(0);await run(f.ctx,'procurement.receive',{orderId:order.id,quantity:'2',unit:'l',reference:'receipt-1',actualCents:400});expect((await stockBalance(f.ctx,f.material.id,f.main.id)).physicalBase).toBe(2000);expect((await f.tx.get('purchase_order',order.id)).data.state).toBe('PARTIALLY_RECEIVED');await expect(run(f.ctx,'procurement.receive',{orderId:order.id,quantity:'2',unit:'l',reference:'receipt-1',actualCents:400})).rejects.toMatchObject({code:'DUPLICATE_EFFECT'});});
 it('self request approvals and duplicate location counts are rejected',async()=>{const f=await fixture();const r=await run(context(f.tx,employee),'request.create',{materialId:f.material.id,siteId:'site',quantity:'1',unit:'l',dueAt:'2026-10-06T00:00:00.000Z',reason:'Requested floor cleaner'});await run(context(f.tx,employee),'request.submit',{requestId:r.id});await expect(run(context(f.tx,employee),'request.approve',{requestId:r.id,decision:'APPROVE'})).rejects.toMatchObject({code:'SELF_APPROVAL_DENIED'});await expect(run(f.ctx,'procurement.calculate',{materialId:f.material.id,locationIds:[f.main.id,f.main.id],horizonAt:'2026-10-06T00:00:00.000Z'})).rejects.toThrow();});
});

describe('payroll and actual payout evidence',()=>{
 it('approved seconds calculate cents; pending timesheets cannot become pay',async()=>{const f=await payrollFixture();expect(f.calculation.data).toMatchObject({baseCents:100000,notGermanNetPayroll:true,state:'ACCOUNTANT_VERIFIED'});const t=await f.tx.get('timesheet','timesheet');await f.tx.save(t,{...t.data,state:'SUBMITTED'},t.version);await expect(run(f.ctx,'payroll.calculation',{timesheetId:'timesheet',rateId:f.rate.id,reason:'Unapproved period'})).rejects.toMatchObject({code:'TIMESHEET_NOT_APPROVED'});});
 it('T-PAY-01 EUR 400 + 600 actual partial payouts settle EUR 1000 without fabricated receipt',async()=>{const f=await payrollFixture();for(const amountCents of [40000,60000]){const p=await run(f.ctx,'payout.create',{calculationId:f.calculation.id,amountCents,method:'CASH',reason:'Synthetic partial actual payout'});await run(f.ctx,'payout.submit',{payoutId:p.id,reason:'Submit actual prepared payout for separate approval'});await run(context(f.tx,manager),'payout.approve',{payoutId:p.id,reason:'Checked actual payment'});await run(f.ctx,'payout.record',{payoutId:p.id,transferredAt:'2026-10-05T09:00:00.000Z',evidenceReference:`cash-${amountCents}`});expect((await f.tx.get('payout',p.id)).data.ackState).toBe('UNCONFIRMED');await expect(run(f.ctx,'payout.ack',{payoutId:p.id,decision:'FULL',statement:'Administrator says employee received'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await run(context(f.tx,employee),'payout.ack',{payoutId:p.id,decision:'FULL',statement:'Employee confirms actual receipt'});await expect(run(context(f.tx,employee),'payout.ack',{payoutId:p.id,decision:'FULL',statement:'Duplicate receipt'})).rejects.toMatchObject({code:'INVALID_STATE'});}expect(await run(f.ctx,'payroll.balance',{calculationId:f.calculation.id})).toMatchObject({recordedCents:100000,employeeAcknowledgedCents:100000,outstandingCents:0,employeeUnsettledCents:0});expect(await f.tx.list('payout_receipt')).toHaveLength(2);await expect(run(f.ctx,'payout.create',{calculationId:f.calculation.id,amountCents:1,method:'CASH',reason:'Exceeds fully paid balance'})).rejects.toMatchObject({code:'PAYOUT_EXCEEDS_BALANCE'});});
 it('employee partial/dispute statements remain separate from administrator recorded amount',async()=>{const f=await payrollFixture();const p=await run(f.ctx,'payout.create',{calculationId:f.calculation.id,amountCents:40000,method:'CASH',reason:'Actual partial payout'});await run(f.ctx,'payout.submit',{payoutId:p.id,reason:'Submit actual prepared payout for separate approval'});await run(context(f.tx,manager),'payout.approve',{payoutId:p.id,reason:'Payment checked'});await run(f.ctx,'payout.record',{payoutId:p.id,transferredAt:'2026-10-05T09:00:00.000Z',evidenceReference:'Cash receipt test'});await run(context(f.tx,employee),'payout.ack',{payoutId:p.id,decision:'PARTIAL',receivedCents:20000,statement:'Only EUR 200 received'});expect(await run(f.ctx,'payroll.balance',{calculationId:f.calculation.id})).toMatchObject({recordedCents:40000,employeeAcknowledgedCents:20000,unconfirmedCents:20000,outstandingCents:60000,employeeUnsettledCents:80000});});
 it('concurrent prepared payouts cannot both exceed the period when approved serially',async()=>{const f=await payrollFixture();const payouts=[];for(let i=0;i<2;i++)payouts.push(await run(f.ctx,'payout.create',{calculationId:f.calculation.id,amountCents:100000,method:'CASH',reason:'Prepared payment'}));for(const payout of payouts)await run(f.ctx,'payout.submit',{payoutId:payout.id,reason:'Prepared payout submitted for separate approval'});await run(context(f.tx,manager),'payout.approve',{payoutId:payouts[0].id,reason:'First actual approval'});await expect(run(context(f.tx,manager),'payout.approve',{payoutId:payouts[1].id,reason:'Second actual approval'})).rejects.toMatchObject({code:'PAYOUT_EXCEEDS_BALANCE'});});
 it('official payslip requires accountant and is not implied by preliminary calculation',async()=>{const f=await fixture();await expect(run(f.ctx,'payroll.official',{calculationId:'unknown',documentMediaId:'unknown',netCents:100,grossCents:120,providerReference:'test',verificationReference:'Unapproved provider'})).rejects.toMatchObject({code:'ACCESS_DENIED'});});
});

async function reportFixture(){const f=await payrollFixture();const r=await run(f.ctx,'report.create',{siteId:'site',customerId:'customer',orderId:'order',periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-06T00:00:00.000Z',documentType:'Leistungsnachweis',taskIds:['task'],timesheetIds:['timesheet'],descriptionDe:'Die Bodenreinigung wurde abgeschlossen.'});await run(context(f.tx,manager),'report.review',{reportId:r.id,decision:'PASS',reason:'Gepruefte Leistungen'});await run(context(f.tx,manager),'report.approve',{reportId:r.id,reason:'Freigabe fuer Kunden'});const version=await run(context(f.tx,manager),'report.publish',{reportId:r.id});return {...f,report:r,version};}
describe('immutable customer reports and media',()=>{
 it('T-REPORT-01 snapshot derives confirmed work/hours and fixed contractual price without payroll or GPS',async()=>{const f=await reportFixture();expect(f.version.data.snapshot).toMatchObject({language:'de',totalSeconds:7200,totalNetCents:120000,totalTaxCents:22800,totalGrossCents:142800,contractIncludedMaterials:true});expect(f.version.data.snapshot.hoursRows[0].workerCode).toBe('KNB-E-001');const content=JSON.stringify(f.version.data.snapshot);expect(content).not.toMatch(/payroll|payableCents|rateCents|GPS|bankAccount|internalCost/);expect(f.version.data.sha256).toHaveLength(64);});
 it('T-REPORT-02 correction creates a new issued version and preserves old checksum and amount',async()=>{const f=await reportFixture(),original=structuredClone(f.version);await run(f.ctx,'report.revise',{reportId:f.report.id,reason:'German description corrected',descriptionDe:'Bodenreinigung und dokumentierte Kontrolle abgeschlossen.'});await run(context(f.tx,manager),'report.review',{reportId:f.report.id,decision:'PASS',reason:'Corrected content checked'});await run(context(f.tx,manager),'report.approve',{reportId:f.report.id,reason:'Corrected version approved'});const next=await run(context(f.tx,manager),'report.publish',{reportId:f.report.id});expect(next.data.version).toBe(2);expect(next.data.previousVersionId).toBe(original.id);expect(next.data.sha256).not.toBe(original.data.sha256);expect(await f.tx.get('report_version',original.id)).toEqual(original);});
 it('T-REPORT-03 delivery, document receipt, hour confirmation and work acceptance are separate',async()=>{const f=await reportFixture();await run(f.ctx,'report.delivered',{reportVersionId:f.version.id,channel:'PORTAL',providerReference:'delivery-1'});expect(await f.tx.list('customer_acknowledgment')).toHaveLength(0);await run(context(f.tx,customer),'report.ack',{reportVersionId:f.version.id,type:'DOCUMENT_RECEIPT',decision:'CONFIRMED',statement:'Dokument erhalten'});await run(context(f.tx,customer),'report.ack',{reportVersionId:f.version.id,type:'HOURS_CONFIRMATION',decision:'COMMENT',statement:'Rueckfrage zu zwei Stunden'});await expect(run(context(f.tx,customer),'report.ack',{reportVersionId:f.version.id,type:'WORK_ACCEPTANCE',decision:'CONFIRMED',statement:'Abnahme behauptet'})).rejects.toMatchObject({code:'LEGAL_ACCEPTANCE_DOCUMENT_REQUIRED'});expect(await f.tx.list('customer_acknowledgment')).toHaveLength(2);});
 it('revoked membership immediately blocks old customer acknowledgments and new delivery',async()=>{const f=await reportFixture();const m=await f.tx.get('customer_membership','membership');await f.tx.save(m,{...m.data,active:false},m.version);await expect(run(context(f.tx,customer),'report.ack',{reportVersionId:f.version.id,type:'DOCUMENT_RECEIPT',decision:'CONFIRMED',statement:'Stale callback'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(f.ctx,'report.delivered',{reportVersionId:f.version.id,channel:'PORTAL',providerReference:'delivery-2'})).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('source changes during review invalidate approval',async()=>{const f=await fixture();const r=await run(f.ctx,'report.create',{siteId:'site',customerId:'customer',orderId:'order',periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-06T00:00:00.000Z',documentType:'Leistungsnachweis',taskIds:['task'],descriptionDe:'Bodenreinigung abgeschlossen.'});await run(context(f.tx,manager),'report.review',{reportId:r.id,decision:'PASS',reason:'Reviewed results'});const o=await f.tx.get('order','order');await f.tx.save(o,{...o.data,finalNetCents:132000},o.version);await expect(run(context(f.tx,manager),'report.approve',{reportId:r.id,reason:'Stale data approval'})).rejects.toMatchObject({code:'REPORT_SOURCE_CHANGED'});expect(await f.tx.list('report_version')).toHaveLength(0);});
 it('rejects unverified browser media and approves only a separate sanitized client copy',async()=>{const f=await fixture();await f.tx.add('media_upload',{uploadedBy:'employee',blobKey:'private/original',sha256:'a'.repeat(64),mimeType:'image/jpeg',byteSize:1024,scanState:'CLEAN'},'upload');const media=await run(context(f.tx,employee),'media.register',{uploadId:'upload',siteId:'site',taskId:'task',stage:'AFTER',visibility:'CLIENT_AFTER_APPROVAL',retentionPurpose:'Work completion evidence'});await expect(run(f.ctx,'media.approve',{mediaId:media.id,reason:'Customer copy checked'})).rejects.toMatchObject({code:'CLIENT_COPY_REQUIRED'});const m=await f.tx.get('media_asset',media.id);await f.tx.save(m,{...m.data,clientBlobKey:'private/client-copy',clientSha256:'b'.repeat(64),metadataStripped:true,redactionConfirmed:true},m.version);expect((await run(f.ctx,'media.approve',{mediaId:media.id,reason:'Metadata and redaction checked'})).data.state).toBe('APPROVED_FOR_CLIENT');await expect(run(context(f.tx,employee),'media.register',{uploadId:'absent',siteId:'site',stage:'AFTER',retentionPurpose:'Missing original evidence'})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});});
});

describe('historical corrections and shortage evidence',()=>{
 it('approved closed corrections are folded once and preserve prior official document/payment balance',async()=>{const f=await payrollFixture();await f.tx.add('timesheet_adjustment',{timesheetId:'timesheet',employeeId:'employee',state:'APPROVED',deltaPayableSeconds:3600,sequence:1,approvedBy:'manager',approvedAt:'2026-10-05T10:00:00.000Z'},'adjustment');const updated=await run(f.ctx,'payroll.recalculate',{calculationId:f.calculation.id,reason:'Approved additional hour'});expect(updated.data).toMatchObject({payableSeconds:39600,baseCents:110000,payableCents:100000,state:'PRELIMINARY',officialDocumentCurrent:false});expect(updated.data.adjustmentIds).toEqual(['adjustment']);await expect(run(f.ctx,'payroll.recalculate',{calculationId:f.calculation.id,reason:'Retry same approved adjustment'})).rejects.toMatchObject({code:'NO_NEW_ADJUSTMENTS'});expect(await f.tx.list('payroll_calculation_revision')).toHaveLength(1);expect(await f.tx.list('official_payslip')).toHaveLength(1);});
 it('offset expiration is normalized to UTC and already-expired reservation is rejected',async()=>{const f=await received();await expect(run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.main.id,quantity:'1',unit:'l',expiresAt:'2026-10-05T11:00:00+02:00'})).rejects.toMatchObject({code:'INVALID_DEADLINE'});});
 it('blocking a previously reserved batch releases demand and produces a shortage rather than phantom coverage',async()=>{const f=await fixture();const batch=await run(f.ctx,'batch.create',{materialId:f.material.id,code:'usable'});await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.main.id,batchId:batch.id,quantity:'5',unit:'l',reference:'lot-1'});const request=await approvedRequest(f);await run(f.ctx,'reservation.create',{materialId:f.material.id,locationId:f.main.id,batchId:batch.id,requestId:request.id,quantity:'5',unit:'l',expiresAt:'2026-10-06T12:00:00.000Z'});await run(f.ctx,'batch.status',{batchId:batch.id,status:'BLOCKED',reason:'Safety quarantine'});expect((await stockBalance(f.ctx,f.material.id,f.main.id)).freeBase).toBe(0);expect((await f.tx.list('stock_reservation'))[0].data.state).toBe('RELEASED');expect(await run(f.ctx,'procurement.calculate',{materialId:f.material.id,locationIds:[f.main.id],horizonAt:'2026-10-06T12:00:00.000Z'})).toMatchObject({newUnreservedDemand:5000,purchaseNeedBase:5000});});
 it('moving weighted average accounts for prior consumption before a later expensive receipt',async()=>{const f=await fixture();await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.site.id,quantity:'10',unit:'l',reference:'cheap',actualCostCents:1000});await run(f.ctx,'stock.use',{materialId:f.material.id,locationId:f.site.id,quantity:'9',unit:'l',taskId:'task',reference:'consume-cheap'});await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.site.id,quantity:'1',unit:'l',reference:'expensive',actualCostCents:1000});const use=await run(f.ctx,'stock.use',{materialId:f.material.id,locationId:f.site.id,quantity:'1',unit:'l',taskId:'task',reference:'consume-averaged'});expect(use.data.internalCostCents).toBe(550);});
 it('daily report automation creates one draft and never publishes itself',async()=>{const f=await fixture();const t=await f.tx.get('task','task');await f.tx.save(t,{...t.data,reviewedAt:'2026-10-04T10:00:00.000Z'},t.version);const first=await run(f.ctx,'report.daily_draft',{siteId:'site',orderId:'order',day:'2026-10-04'});const retry=await run(f.ctx,'report.daily_draft',{siteId:'site',orderId:'order',day:'2026-10-04'});expect(retry.id).toBe(first.id);expect(first.data.state).toBe('DRAFT');expect(await f.tx.list('report_version')).toHaveLength(0);});
});

class BlobDatabaseFixture {
 rows=new Map<string,any>();
 async query(sql:string,params:any[]=[]){if(sql.startsWith('INSERT')){const [id,company_id,owner_id,bytes,mime_type,sha256]=params;if(this.rows.has(id))return {rows:[]};this.rows.set(id,{id,company_id,owner_id,bytes:Buffer.from(bytes),mime_type,sha256});return {rows:[{id}]};}if(sql.startsWith('DELETE')){if(this.rows.get(params[0])?.company_id===params[1])this.rows.delete(params[0]);return {rows:[]};}if(sql.includes('FROM media_blobs')){const row=this.rows.get(params[0]);return {rows:row&&(params.length===1||row.company_id===params[1])?[structuredClone(row)]:[]};}return {rows:[{value:1}]};}
}
class S3Fixture {
 objects=new Map<string,any>();commands:any[]=[];
 async send(command:any){const input=command.input;this.commands.push(command);switch(command.constructor.name){case 'PutObjectCommand':if(this.objects.has(input.Key))throw Object.assign(new Error('exists'),{name:'PreconditionFailed'});this.objects.set(input.Key,{...input,Body:Buffer.from(input.Body),Metadata:{...input.Metadata}});return {};case 'GetObjectCommand':{const found=this.objects.get(input.Key);if(!found)throw Object.assign(new Error('missing'),{name:'NoSuchKey'});return {...found,ContentLength:found.Body.length,Body:Readable.from([found.Body])};}case 'DeleteObjectCommand':this.objects.delete(input.Key);return {};case 'HeadBucketCommand':return {};default:throw new Error('Unexpected fixture command');}}
}
describe('private storage adapter contracts (synthetic provider fixtures)',()=>{
 it('PostgreSQL fallback stores exact bytes atomically through the supplied transaction and rejects tenant/key conflicts',async()=>{const db=new BlobDatabaseFixture(),tx=new BlobDatabaseFixture(),store=new PostgresPrivateBlobStore(db),input={id:'blob1',companyId:'company',ownerId:'employee',bytes:Buffer.from('synthetic bytes'),mimeType:'image/png'};const first=await store.put(input,tx);expect(first.created).toBe(true);expect(db.rows.size).toBe(0);const txStore=new PostgresPrivateBlobStore(tx);expect((await txStore.get('company','blob1')).bytes).toEqual(input.bytes);expect((await txStore.put(input)).created).toBe(false);await expect(txStore.get('other','blob1')).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});await expect(txStore.put({...input,companyId:'other'})).rejects.toMatchObject({code:'DUPLICATE_EFFECT'});expect(createPrivateBlobStore(db,{APP_MODE:'TEST'}).provider).toBe('POSTGRES');});
 it('S3 requests remain private, use encrypted company-scoped keys, and checksum each downloaded stream',async()=>{const client=new S3Fixture(),store=new S3PrivateBlobStore({bucket:'knaba-private-test',region:'eu-central-1'},client),input={id:'blob1',companyId:'company',ownerId:'employee',bytes:Buffer.from('synthetic S3 bytes'),mimeType:'image/png'};const first=await store.put(input);expect(first.created).toBe(true);const put=client.commands[0].input;expect(put.Key).toMatch(/^companies\/[a-f0-9]{64}\/blobs\/blob1$/);expect(put.ACL).toBeUndefined();expect(put.ServerSideEncryption).toBe('AES256');expect(put.IfNoneMatch).toBe('*');expect((await store.get('company','blob1')).bytes).toEqual(input.bytes);expect((await store.put(input)).created).toBe(false);await expect(store.get('other','blob1')).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});await expect(store.put({...input,bytes:Buffer.from('different bytes')})).rejects.toMatchObject({code:'DUPLICATE_EFFECT'});const object=client.objects.get(put.Key);object.Body=Buffer.from('tampered stored data');await expect(store.get('company','blob1')).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'STORAGE_CHECKSUM_MISMATCH'}});});
 it('S3 configuration never silently downgrades an external endpoint to plain HTTP',()=>{expect(()=>new S3PrivateBlobStore({bucket:'knaba-private-test',region:'eu-central-1',endpoint:'http://external.example',allowInsecureLocalTest:true},new S3Fixture())).toThrow();expect(()=>new S3PrivateBlobStore({bucket:'knaba-private-test',region:'eu-central-1',endpoint:'http://127.0.0.1:9000',allowInsecureLocalTest:true},new S3Fixture())).not.toThrow();expect(()=>createPrivateBlobStore(new BlobDatabaseFixture(),{APP_MODE:'PRODUCTION',S3_BUCKET:'knaba-private-test',S3_ENDPOINT:'http://127.0.0.1:9000',S3_ALLOW_INSECURE_LOCAL_TEST:'true'})).toThrow();});
});

describe('real report export artifacts',()=>{
 it('a different authorized requester can recover identical S3 artifact bytes after metadata rollback',async()=>{const f=await reportFixture(),client=new S3Fixture(),store=new S3PrivateBlobStore({bucket:'knaba-private-test',region:'eu-central-1'},client);let fail=true;const tx:Transaction={get:f.tx.get.bind(f.tx),list:f.tx.list.bind(f.tx),save:f.tx.save.bind(f.tx),event:f.tx.event.bind(f.tx),add:async<T extends Data=Data>(kind:string,data:T,id?:string)=>{if(kind==='report_artifact'&&fail){fail=false;throw new DomainError('SIMULATED_METADATA_ROLLBACK');}return f.tx.add<T>(kind,data,id);}};await expect(archiveReportArtifact({tx,store,version:f.version,format:'CSV',ownerId:owner.userId,now:f.ctx.now})).rejects.toMatchObject({code:'SIMULATED_METADATA_ROLLBACK'});expect(client.objects.size).toBe(1);const retry=await archiveReportArtifact({tx,store,version:f.version,format:'CSV',ownerId:manager.userId,now:f.ctx.now});expect(retry.createdBlob!.created).toBe(false);expect(retry.artifact.data.createdBy).toBe(manager.userId);expect((await store.get(f.version.companyId,retry.artifact.data.blobKey)).ownerId).toBe(`report_version:${f.version.id}`);});
 it('each published version and format archives private bytes once and later downloads return identical evidence',async()=>{const f=await reportFixture(),db=new BlobDatabaseFixture(),store=new PostgresPrivateBlobStore(db),tx=Object.assign(f.tx,{query:db.query.bind(db)});for(const format of ['PDF','XLSX','CSV'] as const){const first=await archiveReportArtifact({tx,store,version:f.version,format,ownerId:owner.userId,now:f.ctx.now}),second=await archiveReportArtifact({tx,store,version:f.version,format,ownerId:manager.userId,now:'2026-10-06T12:00:00.000Z'});expect(first.createdBlob!.created).toBe(true);expect(second.createdBlob).toBeUndefined();expect(second.bytes).toEqual(first.bytes);expect(second.artifact.id).toBe(first.artifact.id);expect(second.artifact.data.sourceSha256).toBe(f.version.data.sha256);expect(second.artifact.data.sha256).toBe(createHash('sha256').update(first.bytes).digest('hex'));}expect(db.rows.size).toBe(3);expect(await tx.list('report_artifact')).toHaveLength(3);expect(tx.events.filter(e=>e.type==='report.artifact_archived')).toHaveLength(3);});
 it('canonical report SHA survives PostgreSQL JSONB object key reordering',async()=>{const f=await reportFixture();function reordered(value:any):any {if(Array.isArray(value))return value.map(reordered);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).reverse().map(([key,data])=>[key,reordered(data)]));return value;}const reorderedVersion={...f.version,data:{...f.version.data,snapshot:reordered(f.version.data.snapshot)}};expect(reportSnapshotHash(reorderedVersion.data.snapshot)).toBe(f.version.data.sha256);expect(reportExportSnapshot(reorderedVersion).totalGrossCents).toBe(142800);});
 it('XLSX round-trip and CSV preserve published exact totals, worker seconds and source SHA; PDF embeds the same source SHA',async()=>{const f=await reportFixture();const xlsx=await exportReportXlsx(f.version),workbook=readWorkbook(xlsx);const values=new Map<string,any>();for(const row of workbook.sheets.Bericht.rows)values.set(String(row[1].value),row[2].value);expect(workbook.sheets.Bericht.freeze).toBe('A2');expect(workbook.sheets.Bericht.headerBold).toBe(true);expect(workbook.sheets.Bericht.headerFill).toBe('FF163E34');expect(workbook.sheets.Bericht.headerColor).toBe('FFFFFFFF');expect(workbook.sheets.Bericht.wrap).toBe(true);expect(workbook.sheets.Bericht.vertical).toBe('top');expect(workbook.description).toContain(f.version.data.sha256);expect(values.get('Netto')).toBe(120000);expect(values.get('Steuer')).toBe(22800);expect(values.get('Gesamt')).toBe(142800);expect(values.get('Gesamt (exakt)')).toBe(7200);expect(values.get('KNB-E-001')).toBe('2.00');expect(values.get('Quell-SHA256')).toBe(f.version.data.sha256);const csv=renderReportCsv(f.version);expect(csv).toContain('"Preis";"Gesamt";"142800";"EUR Cent"');expect(csv).toContain(f.version.data.sha256);const pdf=await renderReportPdf(f.version);expect(pdf.subarray(0,5).toString()).toBe('%PDF-');expect(pdf.toString('latin1')).toContain(`Quell-SHA256: ${f.version.data.sha256}`);await mkdir('/tmp/knaba-de-test-artifacts',{recursive:true});await Promise.all([writeFile('/tmp/knaba-de-test-artifacts/report-v1.xlsx',xlsx),writeFile('/tmp/knaba-de-test-artifacts/report-v1.csv',csv),writeFile('/tmp/knaba-de-test-artifacts/report-v1.pdf',pdf)]);});
 it('spreadsheet content is literal text and exports reject snapshot tampering',async()=>{const f=await reportFixture(),version=structuredClone(f.version);version.data.snapshot.descriptionDe='=HYPERLINK("https://example.invalid","Literal text")';version.data.sha256=reportSnapshotHash(version.data.snapshot);const workbook=readWorkbook(await exportReportXlsx(version)),cell=workbook.sheets.Bericht.rows.find((row:any[])=>row[1].value==='Beschreibung'&&row[0].value==='Leistung')[2];expect(cell.value).toBe(version.data.snapshot.descriptionDe);expect(cell.type).toBe('s');expect(renderReportCsv(version)).toContain('"\'=HYPERLINK');version.data.snapshot.totalGrossCents++;await expect(exportReportXlsx(version)).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'REPORT_CHECKSUM_MISMATCH'}});});
});

describe('configured barcode and QR inventory workflows',()=>{
 it('an exact barcode/QR resolves within the company and creates a structured draft request',async()=>{const f=await fixture();await run(f.ctx,'material.update',{materialId:f.material.id,barcodes:['4006381333931'],reason:'Approved supplier barcode'});const resolved=await run(context(f.tx,employee),'material.lookup',{code:'4006381333931',locationIds:[f.site.id]});expect(resolved.material.id).toBe(f.material.id);expect(resolved.photoIdentificationVerified).toBe(false);const request=await run(context(f.tx,employee),'request.from_scan',{code:resolved.qr,siteId:'site',quantity:'2',unit:'l',dueAt:'2026-10-06T12:00:00.000Z',reason:'Confirmed site need'});expect(request.data).toMatchObject({state:'DRAFT',quantityBase:2000,employeeId:'employee'});await expect(run(context(f.tx,employee),'material.lookup',{code:'4006381333931',locationIds:[f.main.id]})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(f.ctx,'material.lookup',{code:`knaba://material/${f.material.id}?role=OWNER`})).rejects.toMatchObject({code:'VALIDATION_ERROR'});await expect(run(f.ctx,'material.lookup',{code:'unknown scan'})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});});
 it('scan confirmation consumes the canonical ledger exactly once and rejects unchecked UI input',async()=>{const f=await fixture();await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.site.id,quantity:'3',unit:'l',reference:'scan-delivery'});const input={code:`knaba://material/${f.material.id}`,locationId:f.site.id,quantity:'1.5',unit:'l',taskId:'task',worklogId:'worklog',reference:'scan-use-1'};await expect(run(context(f.tx,employee),'stock.use_from_scan',{...input,confirmed:false})).rejects.toThrow();expect((await stockBalance(f.ctx,f.material.id,f.site.id)).physicalBase).toBe(3000);await run(context(f.tx,employee),'stock.use_from_scan',{...input,confirmed:true});expect((await stockBalance(f.ctx,f.material.id,f.site.id)).physicalBase).toBe(1500);await expect(run(context(f.tx,employee),'stock.use_from_scan',{...input,confirmed:true})).rejects.toMatchObject({code:'DUPLICATE_EFFECT'});expect((await stockBalance(f.ctx,f.material.id,f.site.id)).physicalBase).toBe(1500);});
});

describe('resource privacy and catalog edge cases',()=>{
 it('client issue photos use fresh VIEW membership and only a self-owned image with allowed site context',async()=>{const f=await reportFixture(),client={...customer,roles:['CLIENT'],permissions:['media.upload'],siteIds:[],customerIds:[],warehouseIds:[]};await f.tx.add('media_upload',{uploadedBy:client.userId,blobKey:'client-original',sha256:'a'.repeat(64),byteSize:64,mimeType:'image/png',scanState:'CLEAN'},'client-upload');const media=await run(context(f.tx,client),'media.register',{uploadId:'client-upload',siteId:'site',taskId:'task',reportVersionId:f.version.id,locationNodeId:'location',stage:'DEFECT',caption:'Vom Kunden gemeldeter Mangel',retentionPurpose:'Document reported issue'});expect(media.data).toMatchObject({externalIssuePhoto:true,customerId:'customer',visibility:'INTERNAL',stage:'DEFECT',uploadedBy:client.userId});await expect(run(context(f.tx,client),'media.register',{uploadId:'client-upload',siteId:'site',taskId:'task',stage:'DEFECT',retentionPurpose:'Unpublished task lookup'})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});});
 it('external uploads cannot link payslips, staff originals, hidden tasks or expired customer scopes',async()=>{const f=await reportFixture(),client={...customer,roles:['EXTERNAL_BAULEITER'],permissions:['media.upload'],siteIds:[],customerIds:[],warehouseIds:[]};await f.tx.add('media_upload',{uploadedBy:client.userId,blobKey:'client-original',sha256:'a'.repeat(64),byteSize:64,mimeType:'image/png',scanState:'CLEAN'},'client-upload');await f.tx.add('media_upload',{uploadedBy:owner.userId,blobKey:'staff-original',sha256:'b'.repeat(64),byteSize:64,mimeType:'image/png',scanState:'CLEAN'},'staff-upload');const input={uploadId:'client-upload',siteId:'site',stage:'DEFECT',retentionPurpose:'Reported customer issue'};await expect(run(context(f.tx,client),'media.register',{...input,employeeId:'employee',stage:'DOCUMENT',visibility:'CONFIDENTIAL'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(context(f.tx,client),'media.register',{...input,uploadId:'staff-upload'})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(context(f.tx,client),'media.register',{...input,taskId:'hidden-task',reportVersionId:f.version.id})).rejects.toMatchObject({code:'NOT_FOUND_SAFE'});const membership=await f.tx.get('customer_membership','membership');await f.tx.save(membership,{...membership.data,expiresAt:'2026-10-05T09:00:00.000Z'},membership.version);await expect(run(context(f.tx,client),'media.register',input)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.tx.list('media_asset')).toHaveLength(1);});
 it('expired customer membership blocks historical callbacks even when the actor retains a static customer ID',async()=>{const f=await reportFixture();const membership=await f.tx.get('customer_membership','membership');await f.tx.save(membership,{...membership.data,expiresAt:'2026-10-05T09:00:00.000Z'},membership.version);await expect(run(context(f.tx,customer),'report.ack',{reportVersionId:f.version.id,type:'DOCUMENT_RECEIPT',decision:'CONFIRMED',statement:'Expired customer callback'})).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('an accountant cannot attach another employee confidential document as this payslip',async()=>{const f=await payrollFixture(),calculation=await f.tx.get('payroll_calculation',f.calculation.id);await f.tx.save(calculation,{...calculation.data,state:'PRELIMINARY'},calculation.version);await f.tx.add('media_asset',{employeeId:'other-employee',visibility:'CONFIDENTIAL',state:'RECEIVED',stage:'DOCUMENT'},'other-payslip');await expect(run(context(f.tx,accountant),'payroll.official',{calculationId:calculation.id,documentMediaId:'other-payslip',netCents:100000,grossCents:120000,providerReference:'Synthetic wrong document',verificationReference:'Mismatched employee document'})).rejects.toMatchObject({code:'PAYSLIP_DOCUMENT_REQUIRED'});});
 it('case-insensitive duplicate SKUs and repeated configured barcodes cannot make scans ambiguous',async()=>{const f=await fixture();await expect(run(f.ctx,'material.create',{sku:'floor-5l',name:'Duplicate SKU',baseUnit:'ml'})).rejects.toMatchObject({code:'DUPLICATE_SKU'});await run(f.ctx,'material.update',{materialId:f.material.id,barcodes:['4006381333931'],reason:'Configured supplier code'});await expect(run(f.ctx,'material.create',{sku:'OTHER',name:'Other material',baseUnit:'ml',barcodes:['4006381333931']})).rejects.toMatchObject({code:'DUPLICATE_BARCODE'});});
});

describe('precision and integrity regression checks',()=>{
 it('German text, XML punctuation and CRLF round-trip exactly; unsupported XML controls fail explicitly',async()=>{const f=await reportFixture(),version=structuredClone(f.version),description='Ä Ö Ü ß & < > " \'\r\nZweite Zeile\tEnde';version.data.snapshot.descriptionDe=description;version.data.sha256=reportSnapshotHash(version.data.snapshot);const workbook=readWorkbook(await exportReportXlsx(version)),cell=workbook.sheets.Bericht.rows.find((row:any[])=>row[0].value==='Leistung'&&row[1].value==='Beschreibung')[2];expect(cell.value).toBe(description);expect(workbook.created).toBe(f.version.data.publishedAt.slice(0,19));version.data.snapshot.descriptionDe='Invalid\u000bXML control';version.data.sha256=reportSnapshotHash(version.data.snapshot);await expect(exportReportXlsx(version)).rejects.toMatchObject({code:'VALIDATION_ERROR',details:{reason:'XLSX_XML_TEXT'}});});
 it('a pending payout cannot obtain approval after its source payroll requires corrected accountant verification',async()=>{const f=await payrollFixture(),payout=await run(f.ctx,'payout.create',{calculationId:f.calculation.id,amountCents:10000,method:'CASH',reason:'Pending synthetic payout'});await run(f.ctx,'payout.submit',{payoutId:payout.id,reason:'Submit before payroll correction'});await f.tx.add('timesheet_adjustment',{timesheetId:'timesheet',employeeId:'employee',state:'APPROVED',deltaPayableSeconds:3600,sequence:1,approvedBy:'manager',approvedAt:f.ctx.now},'payment-source-adjustment');await run(f.ctx,'payroll.recalculate',{calculationId:f.calculation.id,reason:'Accountant correction needed'});await expect(run(context(f.tx,manager),'payout.approve',{payoutId:payout.id,reason:'Stale pending payment approval'})).rejects.toMatchObject({code:'OFFICIAL_PAYROLL_REQUIRED'});expect((await f.tx.get('payout',payout.id)).data.state).toBe('PENDING_APPROVAL');});
 it('one approved remuneration supplement cannot be replayed into another period',async()=>{const f=await fixture(),rate=await run(f.ctx,'payroll.rate',{employeeId:'employee',type:'HOURLY',rateCents:1000,effectiveAt:'2026-01-01T00:00:00.000Z',reason:'Synthetic rate'}),decision=await run(f.ctx,'payroll.supplement_request',{employeeId:'employee',amountCents:1000,reason:'Single approved bonus'});await run(context(f.tx,manager),'payroll.supplement_approve',{decisionId:decision.id,reason:'Single supplement approved'});for(const day of [1,2])await f.tx.add('timesheet',{employeeId:'employee',periodStart:`2026-10-0${day}T00:00:00.000Z`,periodEnd:`2026-10-0${day+1}T00:00:00.000Z`,state:'APPROVED',payableSeconds:3600,segmentSnapshot:[]},`supplement-period-${day}`);const input={rateId:rate.id,approvedSupplementCents:1000,supplementApprovalId:decision.id,reason:'Apply one approved supplement'};const calculation=await run(f.ctx,'payroll.calculation',{...input,timesheetId:'supplement-period-1'});expect(calculation.data.supplementApprovalId).toBe(decision.id);await expect(run(f.ctx,'payroll.calculation',{...input,timesheetId:'supplement-period-2'})).rejects.toMatchObject({code:'DUPLICATE_EFFECT',details:{reason:'SUPPLEMENT_ALREADY_APPLIED'}});expect(await f.tx.list('payroll_calculation')).toHaveLength(1);});
 it('site metadata on a warehouse or employee location never bypasses its primary custody scope',async()=>{const f=await fixture(),warehouse=await run(f.ctx,'stock_location.create',{name:'On-site restricted warehouse',type:'WAREHOUSE',siteId:'site'}),personal=await run(f.ctx,'stock_location.create',{name:'Other employee custody',type:'EMPLOYEE',siteId:'site',employeeId:'manager'});await expect(run(context(f.tx,employee),'stock.balance',{materialId:f.material.id,locationId:warehouse.id})).rejects.toMatchObject({code:'ACCESS_DENIED'});await expect(run(context(f.tx,employee),'stock.balance',{materialId:f.material.id,locationId:personal.id})).rejects.toMatchObject({code:'ACCESS_DENIED'});});
 it('a material use at midnight belongs only to the following half-open report period',async()=>{const f=await fixture();await f.tx.add('material_usage',{siteId:'site',taskId:'task',materialId:f.material.id,quantityBase:500,confirmedAt:'2026-10-02T00:00:00.000Z',clientVisible:true},'midnight-use');const input={siteId:'site',customerId:'customer',orderId:'order',documentType:'Leistungsnachweis',taskIds:['task'],descriptionDe:'Abgegrenzter Tagesbericht.'};const before=await run(f.ctx,'report.create',{...input,periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z'}),after=await run(f.ctx,'report.create',{...input,periodStart:'2026-10-02T00:00:00.000Z',periodEnd:'2026-10-03T00:00:00.000Z'});expect(before.data.draftSnapshot.materialRows).toHaveLength(0);expect(after.data.draftSnapshot.materialRows.map((r:Data)=>r.usageId)).toEqual(['midnight-use']);});
 it('same-site reports reject another order tasks and photos, and exclude its approved time',async()=>{const f=await fixture(),task=await f.tx.get('task','task');await f.tx.save(task,{...task.data,orderId:'other-order'},task.version);const input={siteId:'site',customerId:'customer',orderId:'order',periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z',documentType:'Leistungsnachweis',descriptionDe:'Auftragsbezogener Nachweis.'};await expect(run(f.ctx,'report.create',{...input,taskIds:['task']})).rejects.toMatchObject({code:'INVALID_REFERENCE'});await f.tx.add('media_asset',{siteId:'site',orderId:'other-order',visibility:'CLIENT_AFTER_APPROVAL',state:'APPROVED_FOR_CLIENT'},'wrong-order-photo');await expect(run(f.ctx,'report.create',{...input,mediaIds:['wrong-order-photo']})).rejects.toMatchObject({code:'MEDIA_NOT_APPROVED'});await f.tx.add('timesheet',{employeeId:'employee',periodStart:input.periodStart,periodEnd:input.periodEnd,state:'APPROVED',payableSeconds:7200,segmentSnapshot:[{siteId:'site',taskId:'task',activity:'WORKING',startAt:'2026-10-01T08:00:00.000Z',endAt:'2026-10-01T10:00:00.000Z'}]},'wrong-order-time');const report=await run(f.ctx,'report.create',{...input,timesheetIds:['wrong-order-time']});expect(report.data.draftSnapshot.totalSeconds).toBe(0);expect(report.data.draftSnapshot.priceStatus).toBe('FINAL');});
 it('weekly timesheet segments outside a daily report are skipped and the intersecting segment is clipped',async()=>{const f=await fixture();await f.tx.add('timesheet',{employeeId:'employee',periodStart:'2026-09-28T00:00:00.000Z',periodEnd:'2026-10-05T00:00:00.000Z',state:'APPROVED',payableSeconds:14400,segmentSnapshot:[{siteId:'site',activity:'WORKING',startAt:'2026-09-29T08:00:00.000Z',endAt:'2026-09-29T10:00:00.000Z'},{siteId:'site',activity:'WORKING',startAt:'2026-10-01T23:00:00.000Z',endAt:'2026-10-02T01:00:00.000Z'}]},'weekly');const report=await run(f.ctx,'report.create',{siteId:'site',customerId:'customer',orderId:'order',periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z',documentType:'Stundennachweis',timesheetIds:['weekly'],descriptionDe:'Zeitlich begrenzte Leistungen.'});expect(report.data.draftSnapshot.totalSeconds).toBe(3600);expect(report.data.draftSnapshot.hoursRows[0].workerCode).toBe('KNB-E-001');});
 it('cross-SKU barcode collisions are rejected in both directions and reserved QR syntax stays reserved',async()=>{const f=await fixture();await expect(run(f.ctx,'material.create',{sku:'OTHER',name:'Other',baseUnit:'ml',barcodes:['floor-5l']})).rejects.toMatchObject({code:'DUPLICATE_BARCODE'});await run(f.ctx,'material.update',{materialId:f.material.id,barcodes:['SUPPLIER-123'],reason:'Supplier identifier'});await expect(run(f.ctx,'material.create',{sku:'supplier-123',name:'Other',baseUnit:'ml'})).rejects.toMatchObject({code:'DUPLICATE_SKU'});const other=await run(f.ctx,'material.create',{sku:'OTHER',name:'Other',baseUnit:'ml'});await expect(run(f.ctx,'material.update',{materialId:other.id,barcodes:['FLOOR-5L'],reason:'Conflicting supplier code'})).rejects.toMatchObject({code:'DUPLICATE_BARCODE'});await expect(run(f.ctx,'material.create',{sku:'knaba://material/m',name:'Reserved',baseUnit:'ml'})).rejects.toThrow();});
 it('a repeated PostgreSQL upload cannot conceal damaged stored bytes behind the original checksum',async()=>{const db=new BlobDatabaseFixture(),store=new PostgresPrivateBlobStore(db),input={id:'integrity',companyId:'company',ownerId:'employee',bytes:Buffer.from('verified original bytes'),mimeType:'image/png'};await store.put(input);db.rows.get(input.id).bytes=Buffer.from('corrupted disk bytes');await expect(store.put(input)).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'STORAGE_CHECKSUM_MISMATCH'}});});
 it('approved report photos are bound to immutable byte hashes before embedding',async()=>{const f=await reportFixture(),version=structuredClone(f.version),png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jP1sAAAAASUVORK5CYII=','base64');version.data.snapshot.mediaRows=[{mediaId:'photo-1',sha256:createHash('sha256').update(png).digest('hex'),mimeType:'image/png',caption:'Freigegebenes Testfoto',stage:'AFTER'}];version.data.sha256=reportSnapshotHash(version.data.snapshot);const media=[{id:'photo-1',bytes:png,mimeType:'image/png' as const}],workbook=readWorkbook(await exportReportXlsx(version,{media}));expect(workbook.sheets.Fotodokumentation.images).toHaveLength(1);expect(workbook.sheets.Fotodokumentation.images[0]).toMatchObject({sha256:createHash('sha256').update(png).digest('hex'),row:2,column:1});const altered=[{...media[0],bytes:Buffer.from('substituted bytes')}];await expect(exportReportXlsx(version,{media:altered})).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'REPORT_PHOTO_CHECKSUM_MISMATCH'}});await expect(renderReportPdf(version,{media:altered})).rejects.toMatchObject({code:'INVALID_STATE',details:{reason:'REPORT_PHOTO_CHECKSUM_MISMATCH'}});});
 it('16-digit safe integer amounts remain exact strings when Excel numeric cells would truncate them',async()=>{const f=await reportFixture(),version=structuredClone(f.version),exact=8_000_000_000_000_001;Object.assign(version.data.snapshot,{baseNetCents:exact,approvedChangesNetCents:0,totalNetCents:exact,totalTaxCents:0,totalGrossCents:exact});version.data.sha256=reportSnapshotHash(version.data.snapshot);const workbook=readWorkbook(await exportReportXlsx(version)),total=workbook.sheets.Bericht.rows.find((row:any[])=>row[1].value==='Gesamt')[2];expect(total.type).toBe('s');expect(total.value).toBe(String(exact));expect(renderReportCsv(version)).toContain(String(exact));});
 it('incoming stock and taxed contract totals reject unsafe integer overflow without committing effects',async()=>{const f=await fixture();await run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.main.id,quantity:String(Number.MAX_SAFE_INTEGER),unit:'ml',reference:'maximum-safe-stock'});await expect(run(f.ctx,'stock.receive',{materialId:f.material.id,locationId:f.main.id,quantity:'1',unit:'ml',reference:'overflow-stock'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});expect(await f.tx.list('stock_movement')).toHaveLength(1);const order=await f.tx.get('order','order');await f.tx.save(order,{...order.data,baseNetCents:Number.MAX_SAFE_INTEGER,finalNetCents:Number.MAX_SAFE_INTEGER},order.version);await expect(run(f.ctx,'report.create',{siteId:'site',customerId:'customer',orderId:'order',periodStart:'2026-10-01T00:00:00.000Z',periodEnd:'2026-10-02T00:00:00.000Z',documentType:'Leistungsnachweis',descriptionDe:'Unzulässig großer Betrag.'})).rejects.toMatchObject({code:'VALIDATION_ERROR'});expect(await f.tx.list('report')).toHaveLength(0);});
});
