import {afterEach,describe,it,expect,vi} from 'vitest';
import {z} from 'zod';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {freshMfa} from '../apps/api/auth.ts';
import {Engine} from '../apps/api/engine.ts';
import type {Database} from '../apps/api/database.ts';
import {ApiController,type ApiRuntime} from '../apps/api/http.ts';
import {parseV4PageQuery,paginateV4Entities,compareV4Boundary} from '../apps/api/v4-rest.ts';
import {operationsCommands} from '../packages/domain/operations.ts';
import {resourcesCommands} from '../packages/domain/resources.ts';
import {assertMediaSize,mediaByteLimit,PHOTO_BYTE_LIMIT,PDF_BYTE_LIMIT} from '../packages/storage/media-limits.ts';
import {preparePrivateMedia} from '../packages/storage/media-ingest.ts';
import {assert,DomainError,type Actor,type CommandContext,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';
import type {Request} from 'express';

// CPU tests use an explicit transaction/SQL transport double. No PostgreSQL claim is made here.
class CoreTransaction implements Transaction {
 rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];sequence=0;
 async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const row=this.rows.get(`${kind}:${id}`);if(!row)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(row) as Entity<T>;}
 async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.rows.values()].filter(row=>row.kind===kind).map(row=>structuredClone(row) as Entity<T>);}
 async add<T extends Data=Data>(kind:string,data:T,id=`${kind}-${++this.sequence}`):Promise<Entity<T>>{assert(!this.rows.has(`${kind}:${id}`),'VERSION_CONFLICT');const row={id,kind,companyId:'core-company',version:1,data:structuredClone(data),createdAt:'2026-10-08T10:00:00.000Z',updatedAt:'2026-10-08T10:00:00.000Z'};this.rows.set(`${kind}:${id}`,row);return structuredClone(row) as Entity<T>;}
 async save(entity:Entity,data:Data,expected=entity.version):Promise<Entity>{const current=await this.get(entity.kind,entity.id);assert(expected===current.version,'VERSION_CONFLICT');const row={...current,version:current.version+1,data:structuredClone(data)};this.rows.set(`${entity.kind}:${entity.id}`,row);return structuredClone(row);}
 async event(type:string,data:Data){this.events.push({type,data:structuredClone(data)});}
 async query(_sql:string,_params?:unknown[]){return {rows:[] as Data[]};}
}
const reviewer:Actor={userId:'reviewer',companyId:'core-company',roles:['INTERNAL_BAULEITER'],permissions:['task.review','task.read','operations.read','media.upload'],siteIds:['site-a'],customerIds:[],warehouseIds:[]};
const worker:Actor={...reviewer,userId:'worker',roles:['EMPLOYEE'],permissions:['task.work','task.read','media.upload']};
function context(tx:CoreTransaction,actor=reviewer,key='review-command-12345',expectedVersion?:number):CommandContext{return {tx,actor,idempotencyKey:key,expectedVersion,now:'2026-10-08T12:00:00.000Z',requireSite:siteId=>assert(actor.siteIds.includes(siteId),'ACCESS_DENIED'),requireOwn:userId=>assert(userId===actor.userId,'ACCESS_DENIED')};}
async function run(tx:CoreTransaction,name:string,input:Data,actor=reviewer,key?:string,version?:number){const command=operationsCommands[name]!;assert(actor.permissions.includes(command.permission),'ACCESS_DENIED');const rows=structuredClone(tx.rows),events=structuredClone(tx.events);try{return await command.handler(context(tx,actor,key,version),command.schema.parse(input));}catch(error){tx.rows=rows;tx.events=events;throw error;}}
async function acceptedFixture(){const tx=new CoreTransaction();await tx.add('site',{active:true,name:'Synthetic scoped site'},'site-a');await tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['site-a']},'worker');await tx.add('user',{active:true,roles:['INTERNAL_BAULEITER'],siteIds:['site-a']},'reviewer');const original=await tx.add('task',{siteId:'site-a',title:'Synthetic original accepted 100 m2',state:'ACCEPTED',completionKind:'ORIGINAL',billingScope:'CONTRACT',unit:'M2',plannedQuantityMilli:100000,reportedQuantityMilli:100000,acceptedQuantityMilli:100000,assigneeIds:['worker'],reviewCycle:1,requiredPhotoCount:0,checklist:[],dependencyIds:[],locationSnapshot:[],submittedBy:'worker',submittedAt:'2026-10-07T11:00:00.000Z',reviewedBy:'reviewer',reviewedAt:'2026-10-07T12:00:00.000Z'},'accepted-original');return {tx,original};}
afterEach(()=>vi.restoreAllMocks());

describe('V4 root core contracts — CPU transaction and explicit transport doubles',()=>{
 it('AC-21 accepted reopen preserves the entire original/version and creates one linked internal REWORK on retry',async()=>{const {tx,original}=await acceptedFixture(),key='same-synthetic-reopen-key',rework=await run(tx,'task.reopen',{taskId:original.id,reason:'Verified defect requires separate remediation'},reviewer,key,original.version),retry=await run(tx,'task.reopen',{taskId:original.id,reason:'Verified defect requires separate remediation'},reviewer,key,original.version);expect(retry).toEqual(rework);expect(await tx.get('task',original.id)).toEqual(original);expect(rework.data).toMatchObject({completionKind:'REWORK',sourceTaskId:original.id,billingScope:'INTERNAL',acceptedQuantityMilli:0,reportedQuantityMilli:0,reviewCycle:0,state:'ASSIGNED'});expect(await tx.list('task')).toHaveLength(2);expect(await tx.list('defect')).toHaveLength(1);expect((await tx.list('rework_link'))[0]!.data).toMatchObject({originalTaskId:original.id,reworkTaskId:rework.id,originalSnapshot:original.data});expect(await tx.list('task_review')).toEqual([]);});
 it('accepted original quantity is counted once in progress even after the linked REWORK is accepted',async()=>{const {tx,original}=await acceptedFixture(),rework=await run(tx,'task.reopen',{taskId:original.id,reason:'Separate verified remediation'},reviewer,'rework-completion-123');await run(tx,'task.start',{taskId:rework.id},worker);await run(tx,'task.worklog',{taskId:rework.id,quantityMilli:100000,description:'Actual separate remediation completed'},worker);await run(tx,'task.submit',{taskId:rework.id},worker);await run(tx,'task.review',{taskId:rework.id,decision:'ACCEPT'},reviewer);const progress=await run(tx,'task.progress',{siteId:'site-a'});expect(progress).toMatchObject({tasks:1,byUnit:{M2:{plannedQuantityMilli:100000,acceptedQuantityMilli:100000,acceptedRatio:1,taskIds:[original.id]}}});expect((await tx.get('task',rework.id)).data.state).toBe('ACCEPTED');expect(await tx.get('task',original.id)).toEqual(original);expect((await tx.list('defect'))[0]!.data.state).toBe('CLOSED');});
 it('stale accepted source version and unassigned replacement worker reject atomically before a defect or rework exists',async()=>{const {tx,original}=await acceptedFixture();await expect(run(tx,'task.reopen',{taskId:original.id,reason:'Stale accepted source'},reviewer,'stale-reopen-command',original.version+1)).rejects.toMatchObject({code:'VERSION_CONFLICT'});await tx.add('user',{active:true,roles:['EMPLOYEE'],siteIds:['site-b']},'outside-worker');await expect(run(tx,'task.reopen',{taskId:original.id,assigneeIds:['outside-worker'],reason:'Unauthorized worker assignment'},reviewer,'wrong-worker-command',original.version)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await tx.list('defect')).toEqual([]);expect(await tx.list('rework_link')).toEqual([]);expect(await tx.get('task',original.id)).toEqual(original);});
 it('a valid maximum200-character command key can create a separate REWORK without overflowing the defect external key',async()=>{const {tx,original}=await acceptedFixture();const rework=await run(tx,'task.reopen',{taskId:original.id,reason:'Valid maximum transport idempotency key'},reviewer,'k'.repeat(200),original.version);expect(rework.data.sourceTaskId).toBe(original.id);expect(await tx.list('defect')).toHaveLength(1);expect(await tx.get('task',original.id)).toEqual(original);});
 it('fresh MFA is accepted through exactly10 minutes, rejects one millisecond beyond, malformed/absent dates and excessive future skew',()=>{const now=Date.parse('2026-10-08T12:00:00.000Z');expect(freshMfa(true,new Date(now-600000).toISOString(),now)).toBe(true);expect(freshMfa(true,new Date(now-600001).toISOString(),now)).toBe(false);expect(freshMfa(true,new Date(now+30000).toISOString(),now)).toBe(true);expect(freshMfa(true,new Date(now+30001).toISOString(),now)).toBe(false);for(const date of [undefined,null,'not-a-date'])expect(freshMfa(true,date,now)).toBe(false);expect(freshMfa('true',new Date(now).toISOString(),now)).toBe(false);expect(freshMfa(false,new Date(now).toISOString(),now)).toBe(false);});
 it('PRODUCTION Engine rechecks an old authenticated actor timestamp instead of trusting cached mfaVerified=true',async()=>{const now=Date.parse('2026-10-08T12:00:00.000Z'),clock=vi.spyOn(Date,'now').mockReturnValue(now),tx=new CoreTransaction(),db={transaction:async<T>(_company:string,_user:string,fn:(tx:any)=>Promise<T>)=>fn(tx)} as unknown as Database,engine=new Engine(db,'PRODUCTION');engine.actorIn=async()=>({...reviewer});const action=vi.fn(async(ctx:CommandContext)=>ctx.tx.add('mfa_probe',{approvedBy:ctx.actor.userId}));engine.registry['qa.v4.high_risk']={permission:'task.review',highRisk:true,schema:z.object({}).strict(),handler:action};const authenticated={...reviewer,mfaVerified:true,mfaVerifiedAt:new Date(now).toISOString()};await engine.execute(authenticated,'qa.v4.high_risk',{input:{},idempotency_key:'fresh-mfa-command'});clock.mockReturnValue(now+600001);await expect(engine.execute(authenticated,'qa.v4.high_risk',{input:{},idempotency_key:'cached-mfa-command'})).rejects.toMatchObject({code:'NEEDS_REAUTH'});expect(action).toHaveBeenCalledOnce();expect(await tx.list('mfa_probe')).toHaveLength(1);expect(authenticated.mfaVerified).toBe(true);});
 it('photo and PDF boundary limits are MIME-specific and reject fractional/empty/unsupported ingress',()=>{for(const mime of ['image/jpeg','image/png','image/webp']){expect(mediaByteLimit(mime)).toBe(PHOTO_BYTE_LIMIT);expect(()=>assertMediaSize(PHOTO_BYTE_LIMIT,mime)).not.toThrow();expect(()=>assertMediaSize(PHOTO_BYTE_LIMIT+1,mime)).toThrowError('MEDIA_TOO_LARGE');}expect(mediaByteLimit('application/pdf')).toBe(PDF_BYTE_LIMIT);expect(()=>assertMediaSize(PDF_BYTE_LIMIT,'application/pdf')).not.toThrow();expect(()=>assertMediaSize(PDF_BYTE_LIMIT+1,'application/pdf')).toThrowError('MEDIA_TOO_LARGE');for(const size of [0,-1,1.1,NaN,Infinity])expect(()=>assertMediaSize(size,'image/png')).toThrow();expect(()=>assertMediaSize(1,'image/gif')).toThrowError('VALIDATION_ERROR');});
 it('actual image decode ingress accepts exactly10MiB, keeps original bytes and strips the private customer copy',async()=>{const png=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer(),bytes=Buffer.concat([png,Buffer.alloc(PHOTO_BYTE_LIMIT-png.length)]),prepared=await preparePrivateMedia({bytes,mimeType:'image/png',fileName:'synthetic-boundary.png',sourceId:'synthetic-boundary'});expect(prepared.original).toBe(bytes);expect(prepared.sha256).toBe(createHash('sha256').update(bytes).digest('hex'));expect(prepared.metadataStripped).toBe(true);expect(prepared.clean.length).toBeLessThan(1024);expect((await sharp(prepared.clean).metadata()).format).toBe('jpeg');});
 it('both provider-media preparation and actual HTTP upload entry reject oversized photos/PDF before decoder/scanner/storage effects',async()=>{const tx=new CoreTransaction(),transaction=vi.fn(async<T>(_company:string,_user:string,fn:(tx:any)=>Promise<T>)=>fn(tx)),put=vi.fn(),runtime={companyId:'core-company',appMode:'TEST',buildSha:'explicit-http-double',db:{query:async()=>({rows:[]}),transaction},engine:{registry:{},execute:async()=>null,getActor:async()=>worker,readEntities:async()=>[]},storage:{provider:'POSTGRES',targetFingerprint:'explicit-double',put,get:vi.fn(),delete:vi.fn(),probe:vi.fn()}} as unknown as ApiRuntime,controller=new ApiController(runtime);(controller as any).actor=async()=>({actor:worker});for(const [mimeType,size] of [['image/png',PHOTO_BYTE_LIMIT+1],['application/pdf',PDF_BYTE_LIMIT+1]] as const){const bytes=Buffer.alloc(size);await expect(preparePrivateMedia({bytes,mimeType,fileName:'synthetic-over-limit',sourceId:'synthetic-over-limit'})).rejects.toMatchObject({code:'MEDIA_TOO_LARGE'});await expect(controller.upload({} as Request,{base64:bytes.toString('base64'),mimeType,fileName:'synthetic-over-limit'})).rejects.toMatchObject({code:'MEDIA_TOO_LARGE'});}expect(transaction).not.toHaveBeenCalled();expect(put).not.toHaveBeenCalled();expect(await tx.list('media_upload')).toEqual([]);});
 it('media.register applies the same MIME caps to a purportedly scanned upload and preserves a permitted20MiB PDF',async()=>{const {tx}=await acceptedFixture(),command=resourcesCommands['media.register']!;for(const [mimeType,size] of [['image/png',PHOTO_BYTE_LIMIT+1],['application/pdf',PDF_BYTE_LIMIT+1]] as const){const upload=await tx.add('media_upload',{uploadedBy:'worker',scanState:'CLEAN',byteSize:size,mimeType,blobKey:'synthetic-private',sha256:'a'.repeat(64)});await expect(command.handler(context(tx,worker),command.schema.parse({uploadId:upload.id,siteId:'site-a',stage:'AFTER',visibility:'INTERNAL',retentionPurpose:'Synthetic completion evidence'}))).rejects.toMatchObject({code:'MEDIA_NOT_VERIFIED'});}expect(await tx.list('media_asset')).toEqual([]);const pdf=await tx.add('media_upload',{uploadedBy:'worker',scanState:'CLEAN',byteSize:PDF_BYTE_LIMIT,mimeType:'application/pdf',blobKey:'synthetic-private-pdf',sha256:'b'.repeat(64)});const registered=await command.handler(context(tx,worker),command.schema.parse({uploadId:pdf.id,siteId:'site-a',stage:'DOCUMENT',visibility:'INTERNAL',retentionPurpose:'Synthetic approved document'}));expect(registered.data).toMatchObject({byteSize:PDF_BYTE_LIMIT,mimeType:'application/pdf',state:'RECEIVED'});});
 it('keyset default50/max100 traverses tied timestamps in UTF8 PostgreSQL C order without duplicates',()=>{const binding={companyId:'core-company',userId:'worker',resource:'entities:task'},secret='explicit-test-cursor-key-32-bytes-at-least',now=Date.parse('2026-10-08T12:00:00.000Z'),createdAt='2026-10-08T11:00:00.123Z',ids=[...Array.from({length:104},(_,i)=>'task-'+String(i).padStart(3,'0')),'\uE000','\u{10000}','é','Z'],rows=ids.map(id=>({id,createdAt})).reverse(),expected=[...ids].sort((a,b)=>Buffer.compare(Buffer.from(a),Buffer.from(b)));let request=parseV4PageQuery({},binding,secret,now),page=paginateV4Entities(rows,request,binding,secret),seen=page.items.map(row=>row.id);expect(page.items).toHaveLength(50);while(page.next_cursor){request=parseV4PageQuery({cursor:page.next_cursor},binding,secret,now);page=paginateV4Entities(rows,request,binding,secret);seen.push(...page.items.map(row=>row.id));}expect(seen).toEqual(expected);expect(new Set(seen).size).toBe(ids.length);expect(paginateV4Entities(rows,parseV4PageQuery({limit:100},binding,secret,now),binding,secret).items).toHaveLength(100);expect(compareV4Boundary({id:'\u{10000}',createdAt},{id:'\uE000',createdAt})).toBeGreaterThan(0);expect(()=>parseV4PageQuery({limit:101},binding,secret,now)).toThrow();});
});
