import {describe,it,expect} from 'vitest';
import {percentile,summarizeHttp,evaluateCoreLoad,loadConfiguration,type LoadInputs} from '../scripts/v4-load-metrics.ts';

const complete=():LoadInputs=>({profile:'full',elapsedMs:900000,employees:100,sites:20,sessions:100,activeSessions:100,timeSegments:100000,plannedCommands:9000,offeredCommands:9000,acknowledgedCommands:9000,verifiedCommands:9000,invalidAcknowledgements:0,droppedOffers:0,aborted:false,sourceStayedPinned:true,samples:[...Array.from({length:9000},()=>({kind:'COMMAND' as const,durationMs:750,status:200})),...Array.from({length:100},()=>({kind:'READ' as const,durationMs:800,status:200}))]});
const env=()=>({KNABA_LOAD_ACK:'SYNTHETIC_ISOLATED_DATABASE',APP_MODE:'TEST',EXPECTED_GIT_SHA:'a'.repeat(40),KNABA_LOAD_COMPANY_ID:'knaba-v4-load-synthetic-fixture',KNABA_LOAD_BASE_URL:'http://127.0.0.1:3000',KNABA_LOAD_ALLOWED_ORIGINS:'http://127.0.0.1:3000',LIVE_SEND_ALLOWED:'false',LIVE_INTEGRATION_SEND_ALLOWED:'false',DATABASE_URL:'postgresql://synthetic.invalid/isolated'});
describe('V4 load measurement calculations and explicit synthetic guards (CPU, no load run)',()=>{
 it('uses deterministic nearest-rank p95/p99 without mutation or interpolation hiding the slow tail',()=>{const values=Array.from({length:100},(_,i)=>100-i),before=[...values];expect(percentile(values,.95)).toBe(95);expect(percentile(values,.99)).toBe(99);expect(values).toEqual(before);expect(percentile([3001],.99)).toBe(3001);});
 it('empty measurements have no percentile and cannot pass',()=>{expect(percentile([],.95)).toBeNull();const input=complete();input.samples=[];expect(evaluateCoreLoad(input).status).toBe('NOT_RUN');});
 for(const value of [-1,NaN,Infinity])it(`rejects invalid latency ${String(value)} rather than silently dropping it`,()=>{expect(()=>percentile([1,value],.95)).toThrow('INVALID_METRIC');});
 it('counts transport timeouts and HTTP rejections in the measured tail and error denominator',()=>{expect(summarizeHttp([{kind:'COMMAND',durationMs:10000,status:null},{kind:'READ',durationMs:100,status:503},{kind:'COMMAND',durationMs:1,status:429}])).toMatchObject({requests:3,successful:0,transportErrors:1,fiveXx:1,fiveXxRatio:1/3,nonSuccess:3,p95Ms:10000,p99Ms:10000});});
 it('permits only a complete full workload satisfying every threshold',()=>{expect(evaluateCoreLoad(complete()).status).toBe('PASSED');});
 it('exactly one percent5xx fails the strict less-than target',()=>{const input=complete();input.samples=Array.from({length:100},(_,i)=>({kind:i===99?'READ':'COMMAND',durationMs:1,status:i===0?500:200}));expect(evaluateCoreLoad(input).gates.fiveXxBelowOnePercent).toBe(false);expect(evaluateCoreLoad(input).status).toBe('FAILED');});
 it('one missing acknowledged DB effect fails even with fast HTTP and no5xx',()=>{const input=complete();input.verifiedCommands--;expect(evaluateCoreLoad(input)).toMatchObject({status:'FAILED',lostAcknowledgements:1,gates:{zeroAcknowledgedLoss:false}});});
 it('fast429-only responses never masquerade as sustained accepted command throughput',()=>{const input=complete();input.acknowledgedCommands=0;input.verifiedCommands=0;input.samples=input.samples.map(s=>({...s,status:429}));expect(evaluateCoreLoad(input)).toMatchObject({status:'FAILED',gates:{acknowledgedThroughput:false}});});
 it('missing HTTP observations cannot be filled by a claimed offered or active-session count',()=>{const input=complete();input.samples=input.samples.slice(1);expect(evaluateCoreLoad(input)).toMatchObject({status:'FAILED',gates:{observationsMatchWorkload:false}});});
 for(const [field,value] of [['elapsedMs',899999],['activeSessions',99],['timeSegments',99999],['droppedOffers',1],['offeredCommands',8999],['invalidAcknowledgements',1],['aborted',true],['sourceStayedPinned',false]] as const)it(`fails incomplete or unpinned full input ${field}`,()=>{const input=complete();(input as any)[field]=value;if(field==='offeredCommands'){input.acknowledgedCommands=8999;input.verifiedCommands=8999;}expect(evaluateCoreLoad(input).status).toBe('FAILED');});
 it('smoke evidence stays partial even if all full-target arithmetic would pass',()=>{const input=complete();input.profile='smoke';expect(evaluateCoreLoad(input).status).toBe('PARTIAL_SMOKE_MEASURED');});
 it('rejects impossible verified/acknowledged counts',()=>{const input=complete();input.verifiedCommands++;expect(()=>evaluateCoreLoad(input)).toThrow('INVALID_METRIC');});
 it('accepts only the explicitly allowlisted origin and fixes the full target to900s/10commands per second',()=>{expect(loadConfiguration(env(),'full')).toMatchObject({baseOrigin:'http://127.0.0.1:3000',durationMs:900000,commandsPerSecond:10,timeSegments:100000,sessions:100});expect(loadConfiguration(env(),'smoke').durationMs).toBe(15000);});
 for(const change of [{APP_MODE:'PRODUCTION'},{EXPECTED_GIT_SHA:'main'},{KNABA_LOAD_ACK:''},{KNABA_LOAD_COMPANY_ID:'knaba-demo'},{KNABA_LOAD_ALLOWED_ORIGINS:'https://other.invalid'},{LIVE_SEND_ALLOWED:'true'},{LIVE_INTEGRATION_SEND_ALLOWED:'true'},{WHATSAPP_ACCESS_TOKEN:'synthetic-forbidden'},{DEEPSEEK_API_KEY:'synthetic-forbidden'},{DATABASE_URL:''}])it(`refuses unsafe load setup ${Object.keys(change)[0]}`,()=>{expect(()=>loadConfiguration({...env(),...change},'full')).toThrow();});
 for(const [index,url] of ['http://remote.invalid','https://user:secret@fixture.invalid','https://fixture.invalid/path','https://fixture.invalid?token=secret','https://fixture.invalid#fragment'].entries())it(`rejects unsafe origin variant ${index} without publishing its credential-shaped input`,()=>{expect(()=>loadConfiguration({...env(),KNABA_LOAD_BASE_URL:url,KNABA_LOAD_ALLOWED_ORIGINS:url},'full')).toThrow();});
});
