import {describe,it,expect} from 'vitest';
import {WhatsAppRouter,parseReceiptCents,type RouterPrecondition} from '../packages/integrations/whatsapp-router.ts';
import {parseRouterCommand} from '../packages/integrations/whatsapp-router-text.ts';
import {renderWhatsAppMessage,type WhatsAppOutput} from '../packages/integrations/whatsapp.ts';
import {communicationsCommands} from '../packages/domain/communications.ts';
import {operationsCommands} from '../packages/domain/operations.ts';
import {resourcesCommands} from '../packages/domain/resources.ts';
import {ROLE_PERMISSIONS} from '../packages/domain/permissions.ts';
import {DomainError,assert,type Actor,type Data,type Entity,type Transaction} from '../packages/domain/core.ts';

class MemoryTx implements Transaction {
  constructor(public db:MemoryDb,public companyId:string){}
  async get<T extends Data=Data>(kind:string,id:string):Promise<Entity<T>>{const found=this.db.rows.get(`${kind}:${id}`);if(!found||found.companyId!==this.companyId)throw new DomainError('NOT_FOUND_SAFE');return structuredClone(found) as Entity<T>;}
  async list<T extends Data=Data>(kind:string):Promise<Entity<T>[]>{return [...this.db.rows.values()].filter(r=>r.kind===kind&&r.companyId===this.companyId).map(r=>structuredClone(r) as Entity<T>);}
  async add<T extends Data=Data>(kind:string,data:T,id=`id-${++this.db.sequence}`):Promise<Entity<T>>{assert(!this.db.rows.has(`${kind}:${id}`),'VERSION_CONFLICT');const entity={id,kind,companyId:this.companyId,version:1,data:structuredClone(data),createdAt:this.db.now.toISOString(),updatedAt:this.db.now.toISOString()};this.db.rows.set(`${kind}:${id}`,entity);return structuredClone(entity);}
  async save<T extends Data=Data>(entity:Entity,data:T,version=entity.version):Promise<Entity<T>>{const current=await this.get(entity.kind,entity.id);assert(current.version===version,'VERSION_CONFLICT');const saved={...current,version:current.version+1,data:structuredClone(data),updatedAt:this.db.now.toISOString()};this.db.rows.set(`${entity.kind}:${entity.id}`,saved);return structuredClone(saved) as Entity<T>;}
  async event(type:string,data:Data){this.db.events.push({type,data:structuredClone(data)});}
}
class MemoryDb {
  rows=new Map<string,Entity>();events:{type:string;data:Data}[]=[];sequence=0;now=new Date('2026-10-06T10:00:00.000Z');tail=Promise.resolve();
  async transaction<T>(companyId:string,_actorId:string,operation:(tx:MemoryTx)=>Promise<T>):Promise<T>{const previous=this.tail;let unlock:()=>void=()=>{};this.tail=new Promise(resolve=>unlock=resolve);await previous;const snapshot=structuredClone(this.rows),events=structuredClone(this.events);try{return await operation(new MemoryTx(this,companyId));}catch(error){this.rows=snapshot;this.events=events;throw error;}finally{unlock();}}
  async add(kind:string,data:Data,id?:string){return this.transaction('company','fixture',tx=>tx.add(kind,data,id));}
  async get(kind:string,id:string){return this.transaction('company','fixture',tx=>tx.get(kind,id));}
  async list(kind:string){return this.transaction('company','fixture',tx=>tx.list(kind));}
  async change(kind:string,id:string,patch:Data){return this.transaction('company','fixture',async tx=>{const e=await tx.get(kind,id);return tx.save(e,{...e.data,...patch});});}
}
class MemoryEngine {
  registry={...communicationsCommands,...operationsCommands,...resourcesCommands};
  calls:{name:string;actor:string;input:Data;preconditions?:RouterPrecondition[]}[]=[];
  receipts=new Map<string,{hash:string;result:any}>();loseResponseOnce=false;failBeforeCommandOnce=false;
  constructor(public db:MemoryDb){}
  async actorIn(tx:MemoryTx,userId:string):Promise<Actor>{const user=await tx.get('user',userId);assert(user.data.active!==false,'ACCESS_DENIED');return {userId,companyId:tx.companyId,roles:user.data.roles,permissions:[...new Set([...user.data.roles.flatMap((r:string)=>ROLE_PERMISSIONS[r]??[]),...(user.data.permissions??[])])],siteIds:user.data.siteIds??[],warehouseIds:user.data.warehouseIds??[],customerIds:[]};}
  async getActor(userId:string,companyId:string){return this.db.transaction(companyId,userId,tx=>this.actorIn(tx,userId));}
  async visible(tx:MemoryTx,actor:Actor,e:Entity):Promise<boolean>{if(e.companyId!==actor.companyId)return false;const d=e.data;const site=(id:string)=>actor.permissions.includes('scope.company')||actor.siteIds.includes(id);
    if(e.kind==='site')return site(e.id);
    if(e.kind==='task')return site(d.siteId)&&actor.permissions.includes('task.read');
    if(['shift','trip','time_segment','device'].includes(e.kind))return d.employeeId===actor.userId;
    if(e.kind==='payout'||e.kind==='payout_receipt')return d.employeeId===actor.userId;
    if(e.kind==='media_upload')return d.uploadedBy===actor.userId;
    if(e.kind==='media_asset')return d.uploadedBy===actor.userId||site(d.siteId);
    if(e.kind==='material')return actor.permissions.includes('inventory.read');
    if(e.kind==='material_request')return d.employeeId===actor.userId&&site(d.siteId);
    if(e.kind==='stock_location')return actor.warehouseIds.includes(e.id)||actor.permissions.includes('scope.company');
    if(e.kind==='channel')return actor.permissions.includes('chat.read')&&d.members.some((m:Data)=>m.user_id===actor.userId&&!m.revoked_at)&&(!d.site_id||site(d.site_id));
    if(e.kind==='message')return this.visible(tx,actor,await tx.get('channel',d.channel_id));
    return false;
  }
  async execute(actor:Actor,name:string,envelope:{input?:Data;expected_version?:number;idempotency_key?:string;preconditions?:RouterPrecondition[]}){
    if(this.failBeforeCommandOnce){this.failBeforeCommandOnce=false;throw new Error('SIMULATED_FAILURE_BEFORE_COMMAND');}
    const result=await this.db.transaction(actor.companyId,actor.userId,async tx=>{const fresh=await this.actorIn(tx,actor.userId);const def=this.registry[name];assert(def&&fresh.permissions.includes(def.permission),'ACCESS_DENIED');const input=def.schema.parse(envelope.input??{}),hash=JSON.stringify({name,input,version:envelope.expected_version,guards:envelope.preconditions});const receiptKey=`${fresh.userId}:${envelope.idempotency_key}`;const previous=this.receipts.get(receiptKey);if(previous){assert(hash===previous.hash,'VERSION_CONFLICT');return structuredClone(previous.result);}
      for(const guard of envelope.preconditions??[]){const e=await tx.get(guard.kind,guard.id);assert(e.version===guard.version,'VERSION_CONFLICT');if(e.kind==='whatsapp_router_action'){
        assert(e.data.status==='CLAIMED'&&e.data.expires_at>this.db.now.toISOString(),'CALLBACK_EXPIRED');
        const identities=(await tx.list('contact_identity')).filter(i=>i.data.active!==false&&i.data.verified===true&&!i.data.revokedAt&&!i.data.revoked_at&&(!i.data.expiresAt||Date.parse(i.data.expiresAt)>this.db.now.getTime())&&(!i.data.expires_at||Date.parse(i.data.expires_at)>this.db.now.getTime())&&['WHATSAPP','PHONE'].includes(i.data.type)&&String(i.data.value??'').replace(/[^\d]/g,'')===e.data.sender);
        assert(e.data.user_id===fresh.userId&&identities.length>0&&new Set(identities.map(i=>i.data.userId)).size===1&&identities.every(i=>i.data.userId===fresh.userId),'ACCESS_DENIED');
      }}
      const result=await def.handler({tx,actor:fresh,now:this.db.now.toISOString(),idempotencyKey:envelope.idempotency_key!,expectedVersion:envelope.expected_version,requireSite:id=>assert(fresh.permissions.includes('scope.company')||fresh.siteIds.includes(id),'ACCESS_DENIED'),requireOwn:id=>assert(id===fresh.userId||fresh.permissions.includes('scope.company'),'ACCESS_DENIED')},input);
      this.receipts.set(receiptKey,{hash,result:structuredClone(result)});this.calls.push({name,actor:fresh.userId,input:structuredClone(input),preconditions:envelope.preconditions});return result;
    });if(this.loseResponseOnce){this.loseResponseOnce=false;throw new Error('SIMULATED_CONNECTION_LOST_AFTER_COMMIT');}return result;
  }
}
async function setup(options:Data={}){const db=new MemoryDb();const engine=new MemoryEngine(db);const sender='4915700000001';
  await db.add('user',{roles:['EMPLOYEE'],siteIds:['site-a','site-b'],warehouseIds:['warehouse'],active:true},'employee');
  await db.add('user',{roles:['EMPLOYEE'],siteIds:['site-a'],active:true},'other');
  await db.add('user',{roles:['CLIENT'],siteIds:[],active:true},'client');
  for(const [userId,value]of [['employee',sender],['other','4915700000002'],['client','4915700000003']])await db.add('contact_identity',{type:'WHATSAPP',value,userId,active:true,verified:true});
  await db.add('site',{code:'KNB-A',name:'Haus A',active:true},'site-a');await db.add('site',{code:'KNB-B',name:'Haus B',active:true},'site-b');await db.add('site',{code:'KNB-SECRET',name:'Secret site',active:true},'secret');
  await db.add('stock_location',{type:'WAREHOUSE',name:'Warehouse',active:true},'warehouse');
  await db.add('notification_setting',{user_id:'employee',language:'UK',whatsapp_consent:true,opted_out:false,last_inbound_at:db.now.toISOString(),quiet_start:22,quiet_end:7,allowed_fallback:'WEB'});
  await db.add('material',{sku:'LIQUID',name:'Cleaning liquid',baseUnit:'ml',packagingBase:1000,conversions:[{unit:'ml',numerator:1,denominator:1},{unit:'l',numerator:1000,denominator:1},{unit:'package',numerator:1000,denominator:1}],active:true},'material');
  const router=new WhatsAppRouter(db,engine,{mode:'TEST',testRecipients:[sender],publicOrigin:'https://knaba.example.com',capabilities:{accountVerified:true,buttons:true,lists:true},now:()=>db.now,...options});
  let event=0;
  async function input(text?:string,actionId?:string,userId='employee',data:Data={}){const sender=userId==='other'?'4915700000002':userId==='client'?'4915700000003':'4915700000001';const id=`wamid-${++event}`;return db.add('conversation_input',{provider:'WHATSAPP',provider_event_id:id,user_id:userId,language:'DE',status:'PENDING',received_at:db.now.toISOString(),input:{kind:'MESSAGE',id,sender,phone_number_id:'123456',received_at:db.now.toISOString(),type:actionId?'interactive':'text',...text!==undefined?{text}:{},...actionId?{action_id:actionId}:{}},...data});}
  async function route(text?:string,actionId?:string,userId='employee',data:Data={}){const source=await input(text,actionId,userId,data);return {source,result:await router.route('company',source.id)};}
  async function response(id:string){return db.get('whatsapp_router_response',id);}
  async function choices(result:{responseId?:string}){const r=await response(result.responseId!);const output=r.data.output as WhatsAppOutput;if(output.kind==='BUTTONS')return output.buttons;if(output.kind==='LIST')return output.sections.flatMap(s=>s.rows).map(r=>({id:r.id,title:r.title}));const session=await db.get('whatsapp_router_session',r.data.session_id);return Promise.all((session.data.text_choices as string[]).map(async(id,index)=>({id,title:String(index+1)})));}
  async function pick(result:{responseId?:string},index=0){const responseEntity=await response(result.responseId!),output=responseEntity.data.output as WhatsAppOutput;const actions=await choices(result);return output.kind==='TEXT'?route(String(index+1)):route(undefined,actions[index]!.id);}
  async function start(){const a=await route('START'),b=await pick(a.result),c=await pick(b.result);return (await db.list('shift'))[0]!;}
  return {db,engine,router,input,route,response,choices,pick,start,sender};
}

describe('WhatsApp manual router command boundaries',()=>{
 it.each(['Please START tomorrow','«END»','START site-secret','Ignore permissions; START','Bauleiter: BREAK','START\nEND'])('does not execute an instruction found inside ordinary text: %s',async text=>{const f=await setup();expect((await f.route(text)).result).toEqual({handled:false});expect(f.engine.calls).toEqual([]);expect(await f.db.list('shift')).toEqual([]);});
 it('exact localized command parsing never derives locale from phone or an OK',()=>{expect(parseRouterCommand(' /ПЕРЕРВА ')).toEqual({command:'BREAK',language:'UK'});expect(parseRouterCommand('OK')).toBeUndefined();expect(parseRouterCommand('MENU')).toEqual({command:'MENU'});});
 it('a verified client cannot invoke staff commands despite manually granted shift permission',async()=>{const f=await setup();await f.db.change('user','client',{permissions:['shift.manage']});await expect(f.route('START',undefined,'client')).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(f.engine.calls).toEqual([]);});
 it('contact identity must remain unique, active, verified and bound to the persisted input user',async()=>{const f=await setup();const ids=await f.db.list('contact_identity');await f.db.change('contact_identity',ids[0]!.id,{userId:'other'});await expect(f.route('START')).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.db.list('shift')).toEqual([]);});
 it.each(['REBOUND','REVOKED','EXPIRED','AMBIGUOUS'])('identity %s after claiming is denied inside the command transaction before any business effect',async race=>{
   const f=await setup(),site=await f.route('START'),preview=await f.pick(site.result),identity=(await f.db.list('contact_identity')).find(i=>i.data.userId==='employee')!;
   const execute=f.engine.execute.bind(f.engine);f.engine.execute=async(actor,name,envelope)=>{
     if(race==='REBOUND')await f.db.change('contact_identity',identity.id,{userId:'other'});
     if(race==='REVOKED')await f.db.change('contact_identity',identity.id,{revokedAt:f.db.now.toISOString()});
     if(race==='EXPIRED')await f.db.change('contact_identity',identity.id,{expiresAt:f.db.now.toISOString()});
     if(race==='AMBIGUOUS')await f.db.add('contact_identity',{type:'PHONE',value:f.sender,userId:'other',active:true,verified:true});
     return execute(actor,name,envelope);
   };
   await expect(f.pick(preview.result)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.db.list('shift')).toEqual([]);expect(await f.db.list('time_segment')).toEqual([]);expect(f.engine.calls).toEqual([]);expect(f.engine.receipts.size).toBe(0);
 });
 it('renders the saved UK preference, shows only scoped sites, and mutates only after preview confirmation',async()=>{const f=await setup();const first=await f.route('START');expect((await f.response(first.result.responseId!)).data.output.text).toContain('Виберіть');expect((await f.choices(first.result)).map(x=>x.title)).toEqual(['KNB-A','KNB-B','MENU']);expect(await f.db.list('shift')).toEqual([]);const preview=await f.pick(first.result);expect((await f.response(preview.result.responseId!)).data.output.text).toContain('Попередній перегляд');expect(await f.db.list('shift')).toEqual([]);const confirmation=await f.pick(preview.result);expect(confirmation.result.command).toBe('shift.start');const [shift]=await f.db.list('shift');expect(shift!.data.employeeId).toBe('employee');expect(shift!.data.siteId).toBe('site-a');expect(f.engine.calls[0]!.actor).toBe('employee');expect(f.engine.calls[0]!.preconditions).toEqual(expect.arrayContaining([{kind:'site',id:'site-a',version:1},{kind:'whatsapp_router_action',id:expect.any(String),version:2}]));expect(f.db.events.some(e=>e.type==='tracking.policy_approved')).toBe(false);});
 it('cancel/back expires old buttons and does not perform a business effect',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);const confirm=(await f.choices(b.result))[0]!.id;await f.route('CANCEL');expect((await f.route(undefined,confirm)).result.state).toBe('EXPIRED');expect(await f.db.list('shift')).toEqual([]);});
 it('expired confirmation and modified site snapshots cannot start shifts',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);f.db.now=new Date(f.db.now.getTime()+300000);expect((await f.pick(b.result)).result.state).toBe('EXPIRED');expect(await f.db.list('shift')).toEqual([]);const c=await f.route('START'),d=await f.pick(c.result);await f.db.change('site','site-a',{name:'Changed address/context'});expect((await f.pick(d.result)).result.error).toBe('VERSION_CONFLICT');expect(await f.db.list('shift')).toEqual([]);});
 it('foreign callback substitution is rejected without revealing a preview or mutating the owner',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);const token=(await f.choices(b.result))[0]!.id;expect((await f.route(undefined,token,'other')).result.state).toBe('EXPIRED');expect(await f.db.list('shift')).toEqual([]);});
 it('same provider input and concurrent different inputs produce one confirmed shift',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);const token=(await f.choices(b.result))[0]!.id;const one=await f.input(undefined,token),two=await f.input(undefined,token);const [r1,r2]=await Promise.all([f.router.route('company',one.id),f.router.route('company',two.id)]);expect([r1.command,r2.command].filter(Boolean)).toEqual(['shift.start']);expect(await f.db.list('shift')).toHaveLength(1);expect(f.engine.calls.filter(c=>c.name==='shift.start')).toHaveLength(1);expect((await f.router.route('company',one.id)).handled).toBe(true);expect(await f.db.list('shift')).toHaveLength(1);});
 it('a repeated confirmation from a new provider event reports the previous effect instead of claiming failure',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);const token=(await f.choices(b.result))[0]!.id;await f.route(undefined,token);const repeated=await f.route(undefined,token);expect(repeated.result.state).toBe('ALREADY_PROCESSED');expect((await f.response(repeated.result.responseId!)).data.output.text).toContain('вже оброблено');expect(await f.db.list('shift')).toHaveLength(1);expect(f.engine.calls.filter(c=>c.name==='shift.start')).toHaveLength(1);});
 it('lost response after actual command commit retries the same receipt instead of inventing failure or starting twice',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);const token=(await f.choices(b.result))[0]!.id;const input=await f.input(undefined,token);f.engine.loseResponseOnce=true;await expect(f.router.route('company',input.id)).rejects.toThrow('SIMULATED_CONNECTION_LOST_AFTER_COMMIT');expect(await f.db.list('shift')).toHaveLength(1);expect((await f.db.get('conversation_input',input.id)).data.status).toBe('PENDING');f.db.now=new Date(f.db.now.getTime()+301000);expect((await f.router.route('company',input.id)).command).toBe('shift.start');expect(await f.db.list('shift')).toHaveLength(1);expect(f.engine.calls.filter(c=>c.name==='shift.start')).toHaveLength(1);});
 it('a claimed action that never executed cannot run after TTL on worker recovery',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);const token=(await f.choices(b.result))[0]!.id;const input=await f.input(undefined,token);f.engine.failBeforeCommandOnce=true;await expect(f.router.route('company',input.id)).rejects.toThrow('SIMULATED_FAILURE_BEFORE_COMMAND');expect(await f.db.list('shift')).toEqual([]);f.db.now=new Date(f.db.now.getTime()+300000);expect(await f.router.route('company',input.id)).toMatchObject({handled:true,state:'REJECTED',error:'CALLBACK_EXPIRED'});expect(await f.db.list('shift')).toEqual([]);});
 it('current permissions/site revoke block an old confirmation',async()=>{const f=await setup();const a=await f.route('START'),b=await f.pick(a.result);await f.db.change('user','employee',{roles:['QUALITY_CONTROL'],siteIds:[]});await expect(f.pick(b.result)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.db.list('shift')).toEqual([]);});
 it('unverified interactive capability uses durable numbered text choices with the same guarded command',async()=>{const f=await setup({capabilities:{accountVerified:false,buttons:true,lists:true}});const a=await f.route('START');expect((await f.response(a.result.responseId!)).data.output.kind).toBe('TEXT');expect((await f.response(a.result.responseId!)).data.output.text).toContain('1) KNB-A');const b=await f.pick(a.result);const c=await f.pick(b.result);expect(c.result.command).toBe('shift.start');expect(await f.db.list('shift')).toHaveLength(1);});
});

describe('shared canonical work/material/financial/message commands',()=>{
 it('START → BREAK → explicit RESUME → END retains all segments and never auto-starts from a one-time location',async()=>{const f=await setup();await f.start();f.db.now=new Date('2026-10-06T11:00:00Z');const pause=await f.route('BREAK');await f.pick(pause.result);expect((await f.db.list('shift'))[0]!.data.activity).toBe('ON_BREAK');f.db.now=new Date('2026-10-06T11:30:00Z');const resume=await f.route('RESUME');await f.pick(resume.result);expect((await f.db.list('shift'))[0]!.data.activity).toBe('WORKING');f.db.now=new Date('2026-10-06T12:00:00Z');const end=await f.route('END');await f.pick(end.result);const shift=(await f.db.list('shift'))[0]!;expect(shift.data.state).toBe('ENDED');expect(shift.data.summary).toMatchObject({workSeconds:5400,breakSeconds:1800});const location=await f.input(undefined,undefined,'employee',{input:{kind:'MESSAGE',id:'manual',sender:f.sender,received_at:f.db.now.toISOString(),phone_number_id:'123456',type:'location',location:{latitude:52,longitude:13}},provider_event_id:'manual'});expect(await f.router.route('company',location.id)).toEqual({handled:false});expect(await f.db.list('shift')).toHaveLength(1);});
 it('an explicit destination and original purpose create canonical travel; break and resume use trip commands',async()=>{const f=await setup();await f.start();const travel=await f.route('TRAVEL');expect((await f.choices(travel.result)).map(x=>x.title)).toContain('KNB-B');expect((await f.choices(travel.result)).map(x=>x.title)).not.toContain('KNB-SECRET');await f.pick(travel.result);const purpose='Доставити матеріали прорабу; не їхати додому.';const preview=await f.route(purpose);expect(await f.db.list('trip')).toEqual([]);await f.pick(preview.result);const trip=(await f.db.list('trip'))[0]!;expect(trip.data.destination).toEqual({kind:'SITE',id:'site-b'});expect(trip.data.purpose).toBe(purpose);expect((await f.db.list('shift'))[0]!.data.activity).toBe('TRAVELLING');f.db.now=new Date('2026-10-06T10:05:00Z');const pause=await f.route('BREAK');await f.pick(pause.result);expect((await f.db.list('shift'))[0]!.data.activity).toBe('ON_BREAK');f.db.now=new Date('2026-10-06T10:10:00Z');const resume=await f.route('RESUME');await f.pick(resume.result);expect(f.engine.calls.slice(-2).map(c=>c.name)).toEqual(['trip.stop','trip.resume']);expect(await f.db.list('location_sample')).toEqual([]);});
 it('material wizard validates exact units, preserves reason, creates draft then explicitly submits',async()=>{const f=await setup();const menu=await f.route('MATERIALS'),site=await f.pick(menu.result),material=await f.pick(site.result);await f.pick(material.result);const invalid=await f.route('2 kg');expect(invalid.result.error).toBe('UNIT_INCOMPATIBLE');expect(await f.db.list('material_request')).toEqual([]);const quantity=await f.route('2,5 l');expect(quantity.result.state).toBe('MATERIAL_REASON');await f.route('Для вікон Haus A; залишок не перевірений.');const preview=await f.route('2026-10-07T08:00:00+02:00');expect(await f.db.list('material_request')).toEqual([]);const created=await f.pick(preview.result);const draft=(await f.db.list('material_request'))[0]!;expect(draft.data.quantityBase).toBe(2500);expect(draft.data.state).toBe('DRAFT');expect(draft.data.reason).toContain('не перевірений');expect((await f.response(created.result.responseId!)).data.output.text).toContain('Чернетка');const submitPreview=await f.pick(created.result);await f.pick(submitPreview.result);expect((await f.db.get('material_request',draft.id)).data.state).toBe('SUBMITTED');expect(f.engine.calls.map(c=>c.name)).toEqual(['request.create','request.submit']);expect(await f.db.list('stock_movement')).toEqual([]);});
 it('durable draft can be suspended by MENU and resumed after constructing a new router instance',async()=>{const f=await setup();const menu=await f.route('MATERIALS'),site=await f.pick(menu.result),material=await f.pick(site.result);await f.pick(material.result);await f.route('3 pcs').then(r=>expect(r.result.error).toBe('UNIT_INCOMPATIBLE'));await f.route('2 l');await f.route('/MENU');const router=new WhatsAppRouter(f.db,f.engine,{mode:'TEST',now:()=>f.db.now});const input=await f.input('CONTINUE');expect((await router.route('company',input.id)).state).toBe('MATERIAL_REASON');});
 it('typed numeric financial amount does not collide with fallback text menu choices and money remains exact',async()=>{const f=await setup({capabilities:{accountVerified:false,buttons:false,lists:false}});await f.db.add('payout',{employeeId:'employee',state:'RECORDED',ackState:'UNCONFIRMED',amountCents:10001,currency:'EUR',method:'CASH',transferredAt:f.db.now.toISOString()},'pay-own');await f.db.add('payout',{employeeId:'other',state:'RECORDED',ackState:'UNCONFIRMED',amountCents:987654,method:'CASH',transferredAt:f.db.now.toISOString()},'pay-other');const list=await f.route('PAYROLL');expect((await f.response(list.result.responseId!)).data.output.text).not.toContain('pay-other');const view=await f.pick(list.result);expect((await f.response(view.result.responseId!)).data.output.text).toContain('100.01 EUR');await f.pick(view.result,1);const amount=await f.route('1');expect(amount.result.state).toBe('PAYOUT_STATEMENT');const preview=await f.route('Отримав лише один євро готівкою.');expect((await f.db.get('payout','pay-own')).data.ackState).toBe('UNCONFIRMED');await f.pick(preview.result);expect((await f.db.get('payout','pay-own')).data).toMatchObject({ackState:'PARTIALLY_RECEIVED',employeeStatedReceivedCents:100});expect((await f.db.get('payout','pay-other')).data.ackState).toBe('UNCONFIRMED');const receipt=(await f.db.list('payout_receipt'))[0]!;expect(receipt.data).toMatchObject({decision:'PARTIAL',receivedCents:100,confirmedBy:'employee',immutable:true});});
 it('changed payout amount after preview rejects receipt confirmation rather than silently accepting the new amount',async()=>{const f=await setup();await f.db.add('payout',{employeeId:'employee',state:'RECORDED',ackState:'UNCONFIRMED',amountCents:10000,method:'BANK',transferredAt:f.db.now.toISOString()},'payout');const list=await f.route('PAYROLL'),view=await f.pick(list.result);await f.pick(view.result);const preview=await f.route('I received the full amount.');await f.db.change('payout','payout',{amountCents:20000});expect((await f.pick(preview.result)).result.error).toBe('VERSION_CONFLICT');expect(await f.db.list('payout_receipt')).toEqual([]);});
 it('named channel preserves START as original corporate text; no financial/work action is inferred',async()=>{const f=await setup();await f.db.add('channel',{type:'SITE_INTERNAL',name:'Bauleiter · Haus A',site_id:'site-a',created_by:'employee',members:[{user_id:'employee',history_from:f.db.now.toISOString(),joined_at:f.db.now.toISOString()}],handoff:{state:'AI_ACTIVE'}},'channel');const list=await f.route('CHATS');await f.pick(list.result);const sent=await f.route('START');expect(sent.result.command).toBe('message.send');expect((await f.db.list('message'))[0]!.data).toMatchObject({text:'START',channel_id:'channel',language:'UK',source:'HUMAN'});expect(await f.db.list('shift')).toEqual([]);});
 it('message original language is distinct from the saved interface preference',async()=>{const f=await setup();const setting=(await f.db.list('notification_setting'))[0]!;await f.db.change('notification_setting',setting.id,{language:'DE'});await f.db.add('channel',{type:'SITE_INTERNAL',name:'A',site_id:'site-a',members:[{user_id:'employee',history_from:f.db.now.toISOString(),joined_at:f.db.now.toISOString()}],handoff:{state:'AI_ACTIVE'}},'channel');const list=await f.route('CHATS');await f.pick(list.result);const original='Щойно укладену підлогу не мийте мокрим способом.';await f.route(original);expect((await f.db.list('message'))[0]!.data).toMatchObject({text:original,language:'UK'});expect((await f.db.get('notification_setting',setting.id)).data.language).toBe('DE');});
 it('task result submission uses exact task and original description, creates review state without accepting work',async()=>{const f=await setup();await f.db.add('task',{title:'Fenster reinigen',siteId:'site-a',assigneeIds:['employee'],state:'IN_PROGRESS',dependencyIds:[],checklist:[],description:'Den Boden nicht nass wischen.'},'task');const list=await f.route('TASKS'),task=await f.pick(list.result);await f.pick(task.result);const original='Вікна вимито. Підлогу не чіпав.';const preview=await f.route(original);expect((await f.db.get('task','task')).data.state).toBe('IN_PROGRESS');await f.pick(preview.result);expect((await f.db.get('task','task')).data).toMatchObject({state:'SUBMITTED_FOR_REVIEW',submissionDescription:original,submittedBy:'employee'});expect(f.engine.calls.map(c=>c.name)).toEqual(['task.submit']);});
 it('arrival itself does not start work; arrival+work requires its own explicit selected preview',async()=>{const f=await setup();await f.start();const travel=await f.route('TRAVEL');await f.pick(travel.result);const preview=await f.route('Dienstfahrt für bestätigte Arbeiten.');await f.pick(preview.result);f.db.now=new Date('2026-10-06T10:30:00Z');const status=await f.route('TRAVEL'),arrival=await f.pick(status.result,0);await f.pick(arrival.result);expect((await f.db.list('trip'))[0]!.data.state).toBe('ARRIVED');expect((await f.db.list('shift'))[0]!.data.activity).toBe('WAITING_WORK');expect(f.engine.calls.at(-1)!.input.startWork).toBe(false);});
 it('revoked channel membership and ambiguous reply context cannot publish to another crew',async()=>{const f=await setup();const members=[{user_id:'employee',history_from:f.db.now.toISOString(),joined_at:f.db.now.toISOString()}];await f.db.add('channel',{type:'SITE_INTERNAL',name:'A',site_id:'site-a',members,handoff:{state:'AI_ACTIVE'}},'a');await f.db.add('channel',{type:'SITE_INTERNAL',name:'B',site_id:'site-b',members,handoff:{state:'AI_ACTIVE'}},'b');const list=await f.route('CHATS');await f.pick(list.result);await f.db.add('message',{channel_id:'b',text:'Wrong reply'},'wrong');await expect(f.route('Відповідь',undefined,'employee',{reply_to_id:'wrong'})).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.db.list('message')).toHaveLength(1);await f.db.change('channel','a',{members:[{...members[0],revoked_at:f.db.now.toISOString()}]});await expect(f.route('Відповідь')).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(await f.db.list('message')).toHaveLength(1);});
 it('prepared media requires explicit site and stage confirmation; retains caption and stays internal',async()=>{const f=await setup();await f.db.add('media_upload',{uploadedBy:'employee',scanState:'CLEAN',blobKey:'private/key',sha256:'a'.repeat(64),byteSize:100,mimeType:'image/png',metadataStripped:true},'upload');const input=await f.input(undefined,undefined,'employee',{upload_id:'upload',input:{kind:'MESSAGE',id:'media-event',sender:f.sender,received_at:f.db.now.toISOString(),phone_number_id:'123456',type:'image',media:{id:'meta-image',mime_type:'image/png',sha256:'providerhash',caption:'До: Haus A · вікна; роботу ще не виконано.'}},provider_event_id:'media-event'});const site=await f.router.route('company',input.id);expect(await f.db.list('media_asset')).toEqual([]);const task=await f.pick(site);const stages=await f.pick(task.result);const preview=await f.pick(stages.result,0);expect(await f.db.list('media_asset')).toEqual([]);await f.pick(preview.result);const asset=(await f.db.list('media_asset'))[0]!;expect(asset.data).toMatchObject({siteId:'site-a',stage:'BEFORE',visibility:'INTERNAL',state:'RECEIVED',caption:'До: Haus A · вікна; роботу ще не виконано.'});expect(asset.data.taskId).toBeUndefined();expect(asset.data.photoTakenAtVerified).toBe(false);});
 it('unscanned/foreign upload never creates evidence or reveals an unrelated site',async()=>{const f=await setup();await f.db.add('media_upload',{uploadedBy:'other',scanState:'PENDING'},'upload');const result=await f.route(undefined,undefined,'employee',{upload_id:'upload'});expect(result.result.state).toBe('MEDIA_MANUAL');expect(await f.db.list('media_asset')).toEqual([]);});
 it('non-administrative employee cannot execute raw server/admin code; authorized bot admin receives secure links only',async()=>{const f=await setup();await expect(f.route('ADMIN')).rejects.toMatchObject({code:'ACCESS_DENIED'});expect((await f.route('deploy rm -rf /')).result.handled).toBe(false);await f.db.change('user','employee',{roles:['BOT_ADMIN'],siteIds:[]});const result=await f.route('ADMIN');const output=(await f.response(result.result.responseId!)).data.output;expect(output.text).toContain('https://knaba.example.com/app');expect(f.engine.calls).toEqual([]);});
});

describe('durable replies and outbound channel policy',()=>{
 it('reply is an outbox job, not a claimed actual provider delivery',async()=>{const f=await setup();const {result}=await f.route('MENU');const response=await f.response(result.responseId!);expect(response.data.status).toBe('PENDING');expect(f.db.events.filter(e=>e.type==='whatsapp.router_response')).toHaveLength(1);const prepared=await f.router.prepareResponse('company',response.id);expect(prepared.allowed).toBe(true);if(prepared.allowed)expect(()=>renderWhatsAppMessage(prepared.to!,prepared.output!)).not.toThrow();expect((await f.response(response.id)).data.status).toBe('PENDING');});
 it.each([{whatsapp_consent:false,last_inbound_at:'2026-10-06T10:00:00Z'}, {whatsapp_consent:true,opted_out:true,last_inbound_at:'2026-10-06T10:00:00Z'}, {whatsapp_consent:true,last_inbound_at:'2026-10-05T10:00:00.000Z'}])('fresh consent/optout/exact 24h boundary blocks menus: %j',async patch=>{const f=await setup();const setting=(await f.db.list('notification_setting'))[0]!;await f.db.change('notification_setting',setting.id,patch);const {result}=await f.route('MENU');expect((await f.router.prepareResponse('company',result.responseId!)).allowed).toBe(false);expect((await f.response(result.responseId!)).data.status).toBe('BLOCKED');});
 it('OPTIN is an explicit signed own input, STOP revokes delivery without ending a shift or granting marketing consent',async()=>{const f=await setup();await f.start();const setting=(await f.db.list('notification_setting'))[0]!;await f.db.change('notification_setting',setting.id,{whatsapp_consent:false,opted_out:true});const optin=await f.route('OPTIN');expect((await f.db.get('notification_setting',setting.id)).data).toMatchObject({whatsapp_consent:true,opted_out:false});expect((await f.router.prepareResponse('company',optin.result.responseId!)).allowed).toBe(true);const stop=await f.route('STOP');expect((await f.router.prepareResponse('company',stop.result.responseId!)).allowed).toBe(false);expect((await f.db.list('shift'))[0]!.data.state).toBe('ACTIVE');expect((await f.db.get('notification_setting',setting.id)).data.marketingConsent).toBeUndefined();});
 it('superseded menu delivery and current permission/subject revocation are checked again at sending',async()=>{const f=await setup();const first=await f.route('MENU');await f.route('LANGUAGE');expect(await f.router.prepareResponse('company',first.result.responseId!)).toMatchObject({allowed:false,reason:'SUPERSEDED_OR_EXPIRED'});const menu=await f.route('MENU');await f.db.change('user','employee',{roles:['QUALITY_CONTROL']});expect(await f.router.prepareResponse('company',menu.result.responseId!)).toMatchObject({allowed:false,reason:'ACCESS_REVOKED'});});
 it('test recipients are explicit and HTTP/provider success is never fabricated',async()=>{const f=await setup({testRecipients:[]});const {result}=await f.route('MENU');expect(await f.router.prepareResponse('company',result.responseId!)).toMatchObject({allowed:false,reason:'TEST_RECIPIENT_NOT_ALLOWED'});expect((await f.response(result.responseId!)).data.provider_message_id).toBeUndefined();});
 it('language choice is persisted, does not alter source text, and does not infer consent from an inbound',async()=>{const f=await setup();const language=await f.route('LANGUAGE');const sourceBefore=await f.db.get('conversation_input',language.source.id);await f.pick(language.result,3);const setting=(await f.db.list('notification_setting'))[0]!;expect(setting.data.language).toBe('PL');expect(setting.data.language_source).toBe('EXPLICIT');expect((await f.db.get('conversation_input',language.source.id)).data.input).toEqual(sourceBefore.data.input);expect((await f.response((await f.route('MENU')).result.responseId!)).data.output.text).toContain('Menu pracy');});
 it('decimal receipt parsing is integer EUR cents and excludes exponent/negative/more-than-two-digit amounts',()=>{expect(parseReceiptCents('100,01')).toBe(10001);expect(parseReceiptCents('1')).toBe(100);for(const amount of ['1e3','-2','1.001','1,2,3','NaN'])expect(()=>parseReceiptCents(amount)).toThrow();});
});

describe('WhatsApp safe media and local test origin',()=>{
 it('returns a manual media path without binding unscanned bytes to a site or task',async()=>{
  const f=await setup();const input=await f.input(undefined);await f.db.change('conversation_input',input.id,{input:{...input.data.input,type:'image',media:{id:'unscanned-provider-object',mime_type:'image/jpeg',sha256:'unknown'}},media_state:'MANUAL_REVIEW_REQUIRED',media_error:'SCANNER_UNAVAILABLE'});
  expect(await f.router.route('company',input.id)).toMatchObject({handled:true,state:'MEDIA_MANUAL'});
  expect(await f.db.list('media_asset')).toHaveLength(0);expect(f.engine.calls).toHaveLength(0);
 });
 it('supports a loopback TEST console while refusing insecure external or PRODUCTION origins',async()=>{
  const f=await setup({publicOrigin:'http://127.0.0.1:3100'});expect((await f.route('MENU')).result.handled).toBe(true);
  await expect(setup({mode:'PRODUCTION',publicOrigin:'http://127.0.0.1:3100'})).rejects.toMatchObject({code:'MISSING_CONFIGURATION'});
  await expect(setup({publicOrigin:'http://external.example.test'})).rejects.toMatchObject({code:'MISSING_CONFIGURATION'});
 });
});
