import {describe,it,expect} from 'vitest';
import type {Actor,Data,Entity} from '../packages/domain/core.ts';
import {DomainError} from '../packages/domain/core.ts';
import type {Database,PgTransaction} from '../apps/api/database.ts';
import {deriveWorkNotices,processWorkNotifications,workNotificationRelevant,workNoticeLabel,type WorkNotificationHost,type WorkNotificationJob} from '../packages/domain/work-notifications.ts';

const NOW='2026-10-06T10:00:00.000Z',COMPANY='synthetic-work-notifications';
function fixture(){
 const entities=new Map<string,Entity>(),actors=new Map<string,Actor>();let seq=0;
 const row=(kind:string,id:string,data:Data,version=1):Entity=>{const e={kind,id,data,version,companyId:COMPANY,createdAt:'2026-10-06T09:00:00.000Z',updatedAt:NOW};entities.set(kind+'/'+id,e);return e;};
 const actor=(id:string,permissions:string[],roles=['EMPLOYEE'],siteIds=['site'])=>actors.set(id,{userId:id,companyId:COMPANY,permissions,roles,siteIds,warehouseIds:[],customerIds:[]});
 actor('worker',['task.read','chat.read','inventory.read','finance.payout.ack','shift.read','site.read']);actor('peer',['task.read','chat.read','site.read']);actor('manager',['task.read','task.review','chat.read','issue.read','decision.manage','report.publish','inventory.approve','inventory.read','timesheet.approve'],['INTERNAL_BAULEITER']);actor('service',['integration.process'],['SERVICE_ACCOUNT']);actors.set('knaba-integration-service',actors.get('service')!);actors.get('knaba-integration-service')!.userId='knaba-integration-service';
 actor('client',['task.read','chat.read','customer.portal','report.read'],['CLIENT']);
 row('site','site',{managerIds:['manager'],customerId:'customer'});
 const tx={companyId:COMPANY,get:async(kind:string,id:string)=>{const e=entities.get(kind+'/'+id);if(!e)throw new DomainError('NOT_FOUND_SAFE');return e;},list:async(kind:string)=>[...entities.values()].filter(e=>e.kind===kind),add:async(kind:string,data:Data)=>row(kind,'new-'+(++seq),data),event:async()=>{},query:async()=>({rows:[]})} as unknown as PgTransaction;
 const host:WorkNotificationHost={actorIn:async(_tx,id)=>{const a=actors.get(id);if(!a)throw new DomainError('ACCESS_DENIED');return a;},scope:a=>a,visible:async(_tx,a,e)=>{
  if(e.companyId!==a.companyId)return false;
  if(e.kind==='message'){const c=entities.get('channel/'+e.data.channel_id);return a.permissions.includes('chat.read')&&c?.data.members.some((m:Data)=>m.user_id===a.userId&&!m.revoked_at&&m.active!==false)&&(!c?.data.site_id||a.siteIds.includes(c.data.site_id));}
  if(e.kind==='payout')return a.userId===e.data.employeeId;
  if(e.kind==='order'||e.kind==='report_version')return a.roles.includes('CLIENT')&&entities.get('customer_membership/client')?.data.active===true;
  return !a.roles.includes('CLIENT')&&(!e.data.siteId||a.siteIds.includes(e.data.siteId));
 }};
 const derive=(type:string,data:Data)=>deriveWorkNotices(tx,host,{type,data},NOW);
 const notice=(n:Awaited<ReturnType<typeof derive>>[number]):Entity=>row('notification','notice',{...n,work_cause:n.cause});
 return {row,actor,actors,entities,tx,host,derive,notice};
}

describe('work notifications: CPU current-source resolver (no PostgreSQL/provider acceptance)',()=>{
 it('assigned task follows canonical fresh assignees, never payload recipients or a client with injected task rights',async()=>{
  const f=fixture();f.row('task','task',{siteId:'site',state:'ASSIGNED',assigneeIds:['worker','client'],title:'PRIVATE_TASK_TEXT'});
  const notices=await f.derive('task.assigned',{taskId:'task',employeeIds:['worker','client'],recipient_id:'peer'});
  expect(notices.map(n=>n.recipient_id)).toEqual(['worker']);expect(JSON.stringify(notices)).not.toContain('PRIVATE_TASK_TEXT');
  expect(await f.derive('task.assigned',{taskId:'task',employeeIds:['peer']})).toEqual([]);
 });
 it('created-with-assignees and assigned events share a stable cause dedup identity',async()=>{
  const f=fixture();f.row('task','task',{siteId:'site',state:'ASSIGNED',assigneeIds:['worker']});
  expect((await f.derive('task.created',{taskId:'task'}))[0]!.cause.key).toBe((await f.derive('task.assigned',{taskId:'task',employeeIds:['worker']}))[0]!.cause.key);
 });
 it.each(['site','permission','inactive','reassignment','version'])('fresh %s change invalidates a queued assignment cause',async(change)=>{
  const f=fixture(),task=f.row('task','task',{siteId:'site',state:'ASSIGNED',assigneeIds:['worker']});const n=f.notice((await f.derive('task.assigned',{taskId:'task',employeeIds:['worker']}))[0]!);
  expect(await workNotificationRelevant(f.tx,f.host,n,NOW)).toBe(true);
  if(change==='site')f.actors.get('worker')!.siteIds=[];
  if(change==='permission')f.actors.get('worker')!.permissions=[];
  if(change==='inactive')f.actors.delete('worker');
  if(change==='reassignment')task.data.assigneeIds=['peer'];
  if(change==='version')task.version++;
  expect(await workNotificationRelevant(f.tx,f.host,n,NOW)).toBe(false);
 });
 it('submitted task targets only configured current managers with review rights, without guessing a company manager',async()=>{
  const f=fixture();f.row('task','task',{siteId:'site',state:'SUBMITTED_FOR_REVIEW',assigneeIds:['worker'],reviewCycle:2});
  expect((await f.derive('task.state_changed',{taskId:'task',to:'SUBMITTED_FOR_REVIEW'})).map(n=>n.recipient_id)).toEqual(['manager']);
  f.entities.get('site/site')!.data.managerIds=[];expect(await f.derive('task.state_changed',{taskId:'task',to:'SUBMITTED_FOR_REVIEW'})).toEqual([]);
 });
 it('REWORK requires actual defect link and rework task, never ordinary task label',async()=>{
  const f=fixture();f.row('task','task',{siteId:'site',state:'ASSIGNED',assigneeIds:['worker'],completionKind:'REWORK'});const d=f.row('defect','defect',{reworkTaskId:'task'});
  expect((await f.derive('defect.rework_created',{taskId:'task',defectId:'defect'}))[0]?.event).toBe('task.rework_assigned');d.data.reworkTaskId='other';expect(await f.derive('defect.rework_created',{taskId:'task',defectId:'defect'})).toEqual([]);
 });
 it('chat distinguishes explicit mention, important instruction and foreman reply; revoked members receive none',async()=>{
  const f=fixture();const channel=f.row('channel','channel',{site_id:'site',members:[{user_id:'worker'},{user_id:'peer',revoked_at:NOW},{user_id:'manager'}]});
  f.row('message','parent',{channel_id:'channel',author_id:'worker'});f.row('message','message',{channel_id:'channel',author_id:'manager',message_version:1,text:'PRIVATE_ORIGINAL',mention_ids:['worker','peer'],important:true,reply_to_id:'parent'});
  const n=await f.derive('message.created',{message_id:'message',version:1});expect(n.map(x=>x.event).sort()).toEqual(['chat.foreman_reply','chat.important_instruction','chat.mention']);expect(n.every(x=>x.recipient_id==='worker')).toBe(true);expect(JSON.stringify(n)).not.toContain('PRIVATE_ORIGINAL');
  channel.data.members[0].revoked_at=NOW;expect(await f.derive('message.created',{message_id:'message',version:1})).toEqual([]);
 });
 it('stale message version cannot create notices; own and service recipients are suppressed',async()=>{
  const f=fixture();f.row('channel','channel',{members:[{user_id:'worker'},{user_id:'knaba-integration-service'}]});f.row('message','message',{channel_id:'channel',author_id:'worker',message_version:2,important:true,mention_ids:['worker','knaba-integration-service']});expect(await f.derive('message.created',{message_id:'message',version:1})).toEqual([]);expect(await f.derive('message.created',{message_id:'message',version:2})).toEqual([]);
 });
 it('customer issue follows canonical owner and review cycle',async()=>{
  const f=fixture();f.row('issue','issue',{siteId:'site',state:'OPEN',cycle:2,ownerId:'manager'});expect((await f.derive('issue.opened',{issueId:'issue',cycle:2,ownerId:'peer'}))[0]?.recipient_id).toBe('manager');expect(await f.derive('issue.opened',{issueId:'issue',cycle:1})).toEqual([]);
 });
 it('accepted offer without crew uses the real decision owner and stops once an assignment exists',async()=>{
  const f=fixture();f.row('decision','decision',{status:'OPEN',reason:'CUSTOMER_ACCEPTED_NO_CREW',ownerId:'manager',orderId:'order'});const order=f.row('order','order',{status:'PENDING_OPERATIONS'});
  expect((await f.derive('decision.opened',{decisionId:'decision'}))[0]?.event).toBe('quote.accepted_without_crew');order.data.assignmentId='assigned';expect(await f.derive('decision.opened',{decisionId:'decision'})).toEqual([]);
 });
 it('schedule derives employee user binding and customer VIEW membership without exposing the commercial order to crew',async()=>{
  const f=fixture();f.row('employee','employee',{userId:'worker'});f.row('crew_assignment','assignment',{siteId:'site',scheduleVersion:3,status:'ASSIGNED',employeeIds:['employee']});const order=f.row('order','order',{status:'SCHEDULED',customerId:'customer',siteId:'site',assignmentId:'assignment',schedulePublishedVersion:3});f.row('customer_membership','client',{active:true,userId:'client',customerId:'customer',siteIds:['site'],permissions:['VIEW']});
  const n=await f.derive('dispatch.schedule_confirmed',{orderId:'order',assignmentId:'assignment',scheduleVersion:3});expect(n.map(x=>[x.recipient_id,x.related_kind])).toEqual([['worker','site'],['client','order']]);order.data.schedulePublishedVersion=4;expect(await f.derive('dispatch.schedule_confirmed',{orderId:'order',assignmentId:'assignment',scheduleVersion:3})).toEqual([]);
 });
 function cancelledOrder(){const f=fixture();f.actors.get('worker')!.permissions.push('dispatch.acknowledge');f.actors.get('client')!.permissions.push('commerce.read');f.actor('other-client',['commerce.read'],['CLIENT'],[]);f.row('employee','employee',{userId:'worker',active:true});f.row('crew_assignment','assignment',{orderId:'order',siteId:'site',status:'CANCELLED',employeeIds:['employee']});const order=f.row('order','order',{status:'CANCELLED',customerId:'customer',siteId:'site',assignmentId:'assignment',quoteId:'quote',quoteVersion:3,cancelledAt:NOW,cancellationReason:'PRIVATE_INTERNAL_CANCELLATION_REASON',amountCents:987654});f.row('quote','quote',{status:'ACCEPTED',orderId:'order',customerId:'customer',quoteVersion:3,acceptanceId:'acceptance',ownerUserId:'client',portalPublication:{recipient:{ownerUserId:'client'}}});f.row('quote_acceptance','acceptance',{orderId:'order',customerId:'customer',quoteId:'quote',quoteVersion:3});for(const id of ['client','other-client'])f.row('customer_membership',id,{active:true,userId:id,customerId:'customer',siteIds:['site'],permissions:['VIEW']});return {...f,order,event:{orderId:'order',customerId:'customer',siteId:'site',assignmentId:'assignment',reason:'PRIVATE_INTERNAL_CANCELLATION_REASON'}};}
 it('cancelled order notifies only canonical affected crew and the addressed accepted-quote customer, without copying reason or commercial values',async()=>{const f=cancelledOrder(),notices=await f.derive('dispatch.order_cancelled',{...f.event,recipient_id:'peer',employeeIds:['peer']});expect(notices.map(n=>[n.recipient_id,n.event,n.related_kind])).toEqual([['worker','dispatch.order_cancelled','crew_assignment'],['client','customer.order_cancelled','order']]);expect(JSON.stringify(notices)).not.toContain('PRIVATE_INTERNAL_CANCELLATION_REASON');expect(JSON.stringify(notices)).not.toContain('987654');for(const n of notices)expect(await workNotificationRelevant(f.tx,f.host,f.notice(n),NOW)).toBe(true);});
 it.each([{assignmentId:'injected-assignment'},{customerId:'other-customer'},{siteId:'other-site'},{reason:'forged reason'}])('cancellation rejects a mismatched canonical source binding%j',async data=>{const f=cancelledOrder();expect(await f.derive('dispatch.order_cancelled',{...f.event,...data})).toEqual([]);});
 it('cancellation rechecks current own crew, recipient permissions and exact customer membership/version before delivery',async()=>{const f=cancelledOrder(),notices=await f.derive('dispatch.order_cancelled',f.event),crew=f.notice(notices[0]!),customer=f.notice(notices[1]!);f.actors.get('worker')!.permissions=[];expect(await workNotificationRelevant(f.tx,f.host,crew,NOW)).toBe(false);f.entities.get('customer_membership/client')!.data.active=false;expect(await workNotificationRelevant(f.tx,f.host,customer,NOW)).toBe(false);f.entities.get('customer_membership/client')!.data.active=true;f.entities.get('quote/quote')!.data.quoteVersion=4;expect(await workNotificationRelevant(f.tx,f.host,customer,NOW)).toBe(false);});
 it('does not substitute unrelated customer members when the addressed recipient is inactive or missing',async()=>{const f=cancelledOrder();f.actors.delete('client');expect((await f.derive('dispatch.order_cancelled',f.event)).map(n=>n.recipient_id)).toEqual(['worker']);});
 function replacedAssignment(){const f=fixture();f.actors.get('worker')!.permissions.push('dispatch.acknowledge');f.actors.get('peer')!.permissions.push('dispatch.acknowledge');f.row('employee','old-employee',{userId:'worker',active:true});f.row('employee','new-employee',{userId:'peer',active:true});const previous=f.row('crew_assignment','old-assignment',{orderId:'order',siteId:'site',employeeIds:['old-employee'],scheduleVersion:1,status:'CANCELLED',cancelledAt:NOW,cancellationReason:'ASSIGNMENT_SUPERSEDED',replacedByAssignmentId:'current-assignment'}),current=f.row('crew_assignment','current-assignment',{orderId:'order',siteId:'site',employeeIds:['new-employee'],scheduleVersion:2,status:'ASSIGNED',replacesAssignmentId:previous.id});f.row('order','order',{status:'CONFIRMED',siteId:'site',assignmentId:current.id,scheduleVersion:2});return {...f,previous,current,event:{orderId:'order',siteId:'site',assignmentId:current.id,employeeIds:['new-employee'],scheduleVersion:2,supersededAssignmentId:previous.id,supersededScheduleVersion:1}};}
 it('reassignment gives only canonical previous crew a minimal notice from the exact reciprocal supersession links',async()=>{const f=replacedAssignment(),notices=await f.derive('dispatch.assigned',{...f.event,recipient_id:'manager'});expect(notices.map(n=>[n.recipient_id,n.event,n.related_id])).toEqual([['worker','dispatch.assignment_replaced',f.previous.id]]);expect(await workNotificationRelevant(f.tx,f.host,f.notice(notices[0]!),NOW)).toBe(true);expect(notices[0]!.required_permission).toBe('dispatch.acknowledge');expect(JSON.stringify(notices)).not.toContain('cancellationReason');});
 it.each(['old-link','new-link','current-order','current-crew','old-version'])('reassignment suppresses a forged or stale%s binding',async field=>{const f=replacedAssignment();if(field==='old-link')f.previous.data.replacedByAssignmentId='different';if(field==='new-link')f.current.data.replacesAssignmentId='different';if(field==='current-order')f.entities.get('order/order')!.data.assignmentId='different';if(field==='current-crew')f.current.data.employeeIds=['old-employee'];const event=field==='old-version'?{...f.event,supersededScheduleVersion:9}:f.event;expect(await f.derive('dispatch.assigned',event)).toEqual([]);});
 it.each(['report.approved','material_request.approved','payout.approved'])('%s demands exact source version and appropriate current state',async(type)=>{
  const f=fixture();const kind=type==='report.approved'?'report':type==='payout.approved'?'payout':'material_request';const source=f.row(kind,'source',{state:'APPROVED',siteId:'site',employeeId:'worker'},3);const data=type==='report.approved'?{reportId:'source'}:type==='payout.approved'?{payoutId:'source'}:{requestId:'source'};
  expect(await f.derive(type,{...data,sourceVersion:2})).toEqual([]);expect(await f.derive(type,{...data,sourceVersion:3})).toHaveLength(1);source.data.state='REJECTED';expect(await f.derive(type,{...data,sourceVersion:3})).toEqual([]);
 });
 it('payout receipt reminder goes only to its subject and stops after acknowledgment without copying amounts',async()=>{
  const f=fixture();const p=f.row('payout','payout',{state:'RECORDED',ackState:'UNCONFIRMED',employeeId:'worker',amountCents:987654});const n=await f.derive('payout.transfer_recorded',{payoutId:'payout',employeeId:'peer'});expect(n.map(x=>x.recipient_id)).toEqual(['worker']);expect(JSON.stringify(n)).not.toContain('987654');p.data.ackState='RECEIVED';expect(await f.derive('payout.transfer_recorded',{payoutId:'payout'})).toEqual([]);
 });
 it.each(['ON_BREAK','TRAVELLING','SERVICE_TASK','WORKING'])('absence reminder is suppressed while %s',async(activity)=>{const f=fixture();f.row('shift','shift',{employeeId:'worker',siteId:'site',state:'ACTIVE',activity});f.row('location_incident','incident',{employeeId:'worker',siteId:'site',shiftId:'shift',state:'OPEN',reason:'GEOFENCE_EXIT'});expect(await f.derive('absence.explanation_requested',{shiftId:'shift'})).toEqual([]);});
 it('absence cause binds one canonical incident and stops on submitted explanation',async()=>{const f=fixture();f.row('shift','shift',{employeeId:'worker',siteId:'site',state:'ACTIVE',activity:'AWAY_PENDING_REASON'});f.row('location_incident','incident',{employeeId:'worker',siteId:'site',shiftId:'shift',state:'OPEN',reason:'GEOFENCE_EXIT'});expect(await f.derive('absence.explanation_requested',{shiftId:'shift'})).toHaveLength(3);f.row('absence_explanation','explanation',{shiftId:'shift',state:'SUBMITTED'});expect(await f.derive('absence.explanation_requested',{shiftId:'shift'})).toEqual([]);});
 it('one exact incident schedulesinitial/+5/+15 employee notices and one expliciton-call recipient, never every site manager',async()=>{const f=fixture();f.row('shift','shift',{employeeId:'worker',siteId:'site',state:'ACTIVE',activity:'AWAY_PENDING_REASON'});f.row('location_incident','older',{employeeId:'worker',siteId:'site',shiftId:'shift',state:'OPEN',reason:'GEOFENCE_EXIT'});f.row('location_incident','incident',{employeeId:'worker',siteId:'site',shiftId:'shift',state:'OPEN',reason:'GEOFENCE_EXIT',confirmedAt:NOW});f.entities.get('site/site')!.data.onCallUserId='manager';const items=await f.derive('absence.explanation_requested',{incidentId:'incident',shiftId:'shift',employeeId:'worker',siteId:'site'});expect(items.filter(n=>n.recipient_id==='worker').map(n=>n.scheduled_at)).toEqual([NOW,'2026-10-06T10:05:00.000Z','2026-10-06T10:15:00.000Z']);expect(items.filter(n=>n.recipient_id==='manager')).toMatchObject([{event:'absence.responsible_review_required',related_id:'incident',required_permission:'timesheet.approve'}]);expect(new Set(items.map(n=>n.cause.key)).size).toBe(4);expect(items.every(n=>n.operational_incident===true)).toBe(true);expect(await f.derive('absence.explanation_requested',{incidentId:'incident',shiftId:'shift',employeeId:'peer'})).toEqual([]);f.entities.get('site/site')!.data.onCallUserId=undefined;expect((await f.derive('absence.explanation_requested',{incidentId:'incident',shiftId:'shift'})).map(n=>n.recipient_id)).toEqual(['worker','worker','worker']);});
 it.each(['EXPLANATION','DISPUTED','RESOLVED','END','ON_BREAK','TRAVELLING'])('%s invalidates every queuedgeo reminder before delivery',async(change)=>{const f=fixture(),shift=f.row('shift','shift',{employeeId:'worker',siteId:'site',state:'ACTIVE',activity:'AWAY_PENDING_REASON'}),incident=f.row('location_incident','incident',{employeeId:'worker',siteId:'site',shiftId:'shift',state:'OPEN',reason:'GEOFENCE_EXIT'});const notice=f.notice((await f.derive('absence.explanation_requested',{incidentId:'incident',shiftId:'shift'}))[1]!);expect(await workNotificationRelevant(f.tx,f.host,notice,NOW)).toBe(true);if(change==='EXPLANATION')f.row('absence_explanation','explanation',{shiftId:'shift',state:'SUBMITTED'});else if(['DISPUTED','RESOLVED'].includes(change))incident.data.state=change;else if(change==='END')shift.data.state='ENDED';else shift.data.activity=change;expect(await workNotificationRelevant(f.tx,f.host,notice,NOW)).toBe(false);});
 it('unknown events and corrupt work causes fail closed without creating notices',async()=>{const f=fixture();expect(await f.derive('arbitrary.provider_action',{recipient_id:'worker'})).toEqual([]);expect(await workNotificationRelevant(f.tx,f.host,f.row('notification','bad',{work_cause:{schema:9,type:'task.assigned',key:'bad'}}),NOW)).toBe(false);});
 it('six-language reason labels remain static and contain no source content',()=>{const values=['DE','UK','RU','PL','LT','EN'].map(lang=>workNoticeLabel('chat.mention',lang));expect(new Set(values).size).toBe(6);expect(values.every(v=>v.length>8&&!v.includes('chat.mention'))).toBe(true);expect(workNoticeLabel('task.assigned','INVALID')).toBe(workNoticeLabel('task.assigned','DE'));});
 it('warehouse reservation and shipment follow canonical request references and stop after the cause closes',async()=>{const f=fixture();const r=f.row('material_request','request',{siteId:'site',state:'RESERVED',employeeId:'worker'});f.row('stock_reservation','reservation',{requestId:'request',state:'ACTIVE',expiresAt:'2026-10-07T10:00:00.000Z'});expect((await f.derive('stock.reserved',{reservationId:'reservation',requestId:'ATTACKER_REFERENCE'}))[0]?.event).toBe('warehouse.reserved');f.row('transfer','transfer',{requestId:'request'});f.row('stock_movement','movement',{type:'SHIPMENT',transferId:'transfer'});expect((await f.derive('stock.movement_confirmed',{movementId:'movement'}))[0]?.event).toBe('warehouse.actual_issue');r.data.state='CLOSED';expect(await f.derive('stock.reserved',{reservationId:'reservation'})).toEqual([]);expect(await f.derive('stock.movement_confirmed',{movementId:'movement'})).toEqual([]);});
 it('foreign source rejects before recipient resolution or any projected content',async()=>{const f=fixture();const t=f.row('task','task',{siteId:'site',state:'ASSIGNED',assigneeIds:['worker']});t.companyId='unrelated-company';await expect(f.derive('task.assigned',{taskId:'task',employeeIds:['worker']})).rejects.toMatchObject({code:'ACCESS_DENIED'});});

 it('CPU orchestration double binds lease/type/data, stable dedup and explicit audit/outbox; it does not prove SQL',async()=>{
  const f=fixture();f.row('task','task',{siteId:'site',state:'ASSIGNED',assigneeIds:['worker']});const job:WorkNotificationJob={id:'job',company_id:COMPANY,type:'task.assigned',data:{taskId:'task',employeeIds:['worker']},lease_token:'actual-token'};const emitted:Data[]=[];let audit=0;
  f.tx.query=async(_sql:any,args:any)=>({rows:args[2]==='actual-token'?[{id:args[1],type:job.type,data:job.data}]:[]}) as any;f.tx.event=async(type,data)=>{emitted.push({type,data});};(f.tx as any).audit=async()=>{audit++;};const db={transaction:async(_c:any,_a:any,fn:any)=>fn(f.tx)} as Database;
  expect(await processWorkNotifications(db,f.host,job,NOW)).toMatchObject({created:1,status:'PRODUCED'});expect(await processWorkNotifications(db,f.host,{...job,id:'different-restart-job'},NOW)).toMatchObject({created:0,deduplicated:1});expect(audit).toBe(1);expect(emitted).toHaveLength(1);const stored=[...f.entities.values()].find(e=>e.kind==='notification')!;expect(stored.data.channel).toBe('WEB');expect(stored.data.template).toBeNull();
  await expect(processWorkNotifications(db,f.host,{...job,lease_token:'stolen'},NOW)).rejects.toMatchObject({code:'WORKER_LEASE_LOST'});f.tx.query=async()=>({rows:[{type:'message.created',data:job.data}]}) as any;await expect(processWorkNotifications(db,f.host,job,NOW)).rejects.toMatchObject({code:'ACCESS_DENIED'});expect(emitted).toHaveLength(1);
 });
});
