import {useEffect,useRef,useState} from 'react';
import {Camera,ScanLine,X} from './icons';
import {Button} from '../../../packages/ui/index';
import type {Translate} from './CommandForm';
export default function BarcodeInput({value,onChange,t}:{value:string;onChange:(value:string)=>void;t:Translate}){const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),mounted=useRef(true);const [active,setActive]=useState(false),[busy,setBusy]=useState(false),[hint,setHint]=useState('');const callback=useRef(onChange);callback.current=onChange;const supported=Boolean((window as any).BarcodeDetector&&navigator.mediaDevices?.getUserMedia);function stop(){if(timeout.current)clearTimeout(timeout.current);stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(mounted.current)setActive(false);}
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stop()}},[]);
 async function start(){setHint('');if(!supported){setHint('cameraUnavailable');return;}setBusy(true);try{const Detector=(window as any).BarcodeDetector,formats:string[]=typeof Detector.getSupportedFormats==='function'?await Detector.getSupportedFormats():['qr_code','ean_13','ean_8','code_128'];const usable=formats.filter(format=>['qr_code','ean_13','ean_8','code_128','code_39','upc_a','upc_e','data_matrix'].includes(format));if(!usable.length)throw Error('UNSUPPORTED');const detector=new Detector({formats:usable});const camera=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});if(!mounted.current){camera.getTracks().forEach(track=>track.stop());return;}stream.current=camera;setActive(true);const detect=async()=>{if(!mounted.current||!stream.current)return;if(video.current){if(video.current.srcObject!==camera){video.current.srcObject=camera;await video.current.play();}if(video.current.readyState>=2){const codes=await detector.detect(video.current);const found=codes.find((code:any)=>typeof code.rawValue==='string'&&code.rawValue.length<=256);if(found){callback.current(found.rawValue);stop();setHint('codeDetected');return;}}}timeout.current=setTimeout(()=>{void detect().catch(()=>{stop();setHint('cameraUnavailable')})},300)};timeout.current=setTimeout(()=>{void detect().catch(()=>{stop();setHint('cameraUnavailable')})},100);}catch{stop();setHint('cameraUnavailable')}finally{if(mounted.current)setBusy(false)}}
 return <div className="barcode-input"><label className="field"><span>{t('barcodeLabel')}</span><div className="barcode-value"><ScanLine size={18}/><input required minLength={1} maxLength={256} autoComplete="off" value={value} placeholder="SKU / EAN / knaba://material/…" onChange={e=>onChange(e.target.value)}/></div></label><Button variant="secondary" type="button" disabled={busy} onClick={active?stop:start}>{active?<X size={16}/>:<Camera size={16}/>} {busy?t('loading'):active?t('stopCamera'):t('startCamera')}</Button>{active&&<div className="camera-preview"><video ref={video} muted playsInline autoPlay aria-label={t('barcodeLabel')}/><span>{t('pointAtCode')}</span></div>}<small className="barcode-note">{hint?t(hint):supported?t('cameraOptional'):t('cameraUnavailable')}</small></div>
}
