import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {Badge,Button,Empty} from '../../../packages/ui/index';
import {languages,type Language} from '../../../packages/i18n/index';
import {api,ApiError,type Entity,type Session} from './api';
import {errorText,type Translate} from './CommandForm';
import {Check,ShieldCheck,X} from './icons';
import {rectangleFromDrag,validRectangle,type ImageSize,type PixelRectangle} from './redactionGeometry';

const copy:Record<string,string[]>={
 title:['Kundenkopie manuell verdecken','Ручне приховування на клієнтській копії','Ручное скрытие на клиентской копии','Ręczne zasłanianie kopii klienta','Rankinis kliento kopijos uždengimas','Manually conceal client photo copy'],
 description:['Markieren Sie vertrauliche Bildbereiche mit vollständig deckenden Rechtecken. Das Original bleibt unverändert.','Виділіть приватні ділянки повністю непрозорими прямокутниками. Оригінал залишається незмінним.','Выделите приватные области полностью непрозрачными прямоугольниками. Оригинал остаётся неизменным.','Zasłoń prywatne obszary całkowicie nieprzezroczystymi prostokątami. Oryginał pozostaje bez zmian.','Privačias sritis uždenkite visiškai nepermatomais stačiakampiais. Originalas nepakeičiamas.','Cover private areas with fully opaque rectangles. The original remains unchanged.'],
 photo:['Kundenfoto auswählen','Вибрати клієнтське фото','Выбрать клиентское фото','Wybierz zdjęcie klienta','Pasirinkite kliento nuotrauką','Select client photo'],
 select:['Foto auswählen','Виберіть фото','Выберите фото','Wybierz zdjęcie','Pasirinkite nuotrauką','Select photo'],
 empty:['Keine freigabefähige separate Kundenkopie vorhanden','Немає окремої клієнтської копії для погодження','Нет отдельной клиентской копии для согласования','Brak oddzielnej kopii klienta do zatwierdzenia','Nėra atskiros kliento kopijos tvirtinimui','No separate client copy available for review'],
 drag:['Ziehen Sie über die Kundenkopie oder geben Sie Pixelkoordinaten ein. Maximal 30 Bereiche; keine automatische Erkennung.','Проведіть по клієнтській копії або введіть координати пікселів. До 30 ділянок; автоматичного визначення немає.','Проведите по клиентской копии или введите координаты пикселей. До 30 областей; автоматического распознавания нет.','Przeciągnij po kopii klienta lub wpisz współrzędne pikseli. Do 30 obszarów; bez automatycznego wykrywania.','Vilkite kliento kopijoje arba įveskite pikselių koordinates. Iki 30 sričių; automatinio aptikimo nėra.','Drag over the client copy or enter pixel coordinates. Up to 30 areas; no automatic detection.'],
 preview:['Maskenvorschau','Попередній вигляд масок','Предварительный вид масок','Podgląd masek','Kaukių peržiūra','Mask preview'],
 width:['Breite','Ширина','Ширина','Szerokość','Plotis','Width'],height:['Höhe','Висота','Высота','Wysokość','Aukštis','Height'],
 add:['Bereich hinzufügen','Додати ділянку','Добавить область','Dodaj obszar','Pridėti sritį','Add rectangle'],remove:['Bereich entfernen','Видалити ділянку','Удалить область','Usuń obszar','Pašalinti sritį','Remove rectangle'],
 invalid:['Der Bereich muss vollständig innerhalb des Bildes liegen und ganzzahlige Pixel verwenden.','Ділянка має бути повністю в межах зображення та задана цілими пікселями.','Область должна быть полностью внутри изображения и задана целыми пикселями.','Obszar musi mieścić się w obrazie i używać całkowitych pikseli.','Sritis turi būti vaizdo ribose ir nurodyta sveikais pikseliais.','The rectangle must use integral pixels and fit entirely within the image.'],
 limit:['Maximal 30 Bereiche','Максимум 30 ділянок','Максимум 30 областей','Maksymalnie 30 obszarów','Daugiausia 30 sričių','Maximum 30 rectangles'],
 reason:['Grund für die Verdeckung','Причина приховування','Причина скрытия','Powód zasłonięcia','Uždengimo priežastis','Reason for concealment'],
 review:['Masken prüfen','Перевірити маски','Проверить маски','Sprawdź maski','Peržiūrėti kaukes','Review masks'],
 confirm:['Ich habe alle privaten Bildbereiche geprüft und bestätige diese vollständig deckenden Masken.','Я перевірив усі приватні ділянки та підтверджую ці повністю непрозорі маски.','Я проверил все приватные области и подтверждаю эти полностью непрозрачные маски.','Sprawdzono wszystkie prywatne obszary; potwierdzam te nieprzezroczyste maski.','Peržiūrėjau visas privačias sritis ir patvirtinu šias nepermatomas kaukes.','I reviewed the private areas and explicitly confirm these fully opaque masks.'],
 save:['Neue Kundenkopie speichern','Зберегти нову клієнтську копію','Сохранить новую клиентскую копию','Zapisz nową kopię klienta','Išsaugoti naują kliento kopiją','Save new client copy'],
 saved:['Neue Kundenkopie gespeichert. Eine separate Freigabe ist weiterhin erforderlich.','Нову клієнтську копію збережено. Окреме погодження все ще потрібне.','Новая клиентская копия сохранена. Отдельное согласование всё ещё требуется.','Nowa kopia klienta zapisana. Nadal wymagane jest osobne zatwierdzenie.','Nauja kliento kopija išsaugota. Vis dar reikia atskiro patvirtinimo.','New client copy saved. Separate publication approval is still required.'],
 approve:['Freigabe separat prüfen','Окремо перевірити погодження','Отдельно проверить согласование','Sprawdź osobne zatwierdzenie','Peržiūrėti atskirą patvirtinimą','Review separate publication approval'],
 imageError:['Kundenkopie konnte nicht sicher geladen werden. Auswahl erneut laden.','Не вдалося безпечно завантажити клієнтську копію. Повторно виберіть фото.','Не удалось безопасно загрузить клиентскую копию. Повторно выберите фото.','Nie udało się bezpiecznie wczytać kopii klienta. Wybierz zdjęcie ponownie.','Nepavyko saugiai įkelti kliento kopijos. Pasirinkite nuotrauką iš naujo.','Could not safely load the client copy. Select the photo again.'],
 original:['Privates Original öffnen','Відкрити приватний оригінал','Открыть приватный оригинал','Otwórz prywatny oryginał','Atverti privatų originalą','Open private original'],
 version:['Kopienversion','Версія копії','Версия копии','Wersja kopii','Kopijos versija','Copy version']
};
const label=(language:Language,key:string)=>copy[key]?.[languages.indexOf(language)]||key;
type Props={session:Session;records:Record<string,Entity[]>;language:Language;t:Translate;onSaved:()=>void;onApprove:(id:string,version:number)=>void};
export default function ClientRedactionPanel({session,records,language,t,onSaved,onApprove}:Props){
 const c=(key:string)=>label(language,key),[assetId,setAssetId]=useState(''),[size,setSize]=useState<ImageSize>(),[rectangles,setRectangles]=useState<PixelRectangle[]>([]),[dragRect,setDragRect]=useState<PixelRectangle>(),[numeric,setNumeric]=useState({x:'0',y:'0',width:'20',height:'20'}),[reason,setReason]=useState(''),[review,setReview]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[saved,setSaved]=useState<Entity>();
 const [blocked,setBlocked]=useState(false);const imageIdentity=useRef('');const sequence=useRef(0),controller=useRef<AbortController|undefined>(undefined),key=useRef<string>(crypto.randomUUID()),start=useRef<{x:number;y:number}|undefined>(undefined);
 const assets=(records.media_asset||[]).filter(row=>row.data.visibility==='CLIENT_AFTER_APPROVAL'&&row.data.metadataStripped===true&&/^image\/(png|jpeg|webp)$/.test(row.data.clientMimeType||'')&&['RECEIVED','APPROVED_FOR_CLIENT'].includes(row.data.state)),asset=assets.find(row=>row.id===assetId),copyVersion=Number(asset?.data.clientCopyVersion??0);
 useEffect(()=>()=>{sequence.current++;controller.current?.abort()},[]);
 useEffect(()=>{sequence.current++;controller.current?.abort();setBusy(false);setSize(undefined);setRectangles([]);setDragRect(undefined);start.current=undefined;setReview(false);setConfirmed(false);setError(undefined);setReason('');key.current=crypto.randomUUID();},[assetId,asset?.version,session.actor.userId]);
 function changed(){setReview(false);setConfirmed(false);setSaved(undefined);setError(undefined);key.current=crypto.randomUUID();}
 function add(rect:PixelRectangle){if(!size||busy)return;if(rectangles.length>=30){setError(new Error(c('limit')));return;}if(!validRectangle(rect,size)){setError(new Error(c('invalid')));return;}changed();setRectangles(rows=>[...rows,rect]);}
 function pointerRect(event:PointerEvent<SVGSVGElement>){if(!start.current||!size)return undefined;const bounds=event.currentTarget.getBoundingClientRect();return rectangleFromDrag(start.current,{x:event.clientX,y:event.clientY},{left:bounds.left,top:bounds.top,width:bounds.width,height:bounds.height},size);}
 async function save(){if(blocked||!asset||!size||!review||!confirmed||busy||!rectangles.length||!navigator.onLine)return;const own=sequence.current,abort=new AbortController();controller.current=abort;const timeout=setTimeout(()=>abort.abort(),20_000);setBusy(true);setError(undefined);try{const result=await api<Entity>('/api/v1/commands/media.redact',{method:'POST',signal:abort.signal,body:JSON.stringify({input:{mediaId:asset.id,clientCopyVersion:copyVersion,rectangles,reason},expected_version:asset.version,idempotency_key:key.current})});if(own!==sequence.current)return;if(result.id!==asset.id||result.kind!=='media_asset'||result.data.clientCopyVersion!==copyVersion+1||result.data.state!=='RECEIVED'||!Number.isSafeInteger(result.version))throw new ApiError('INVALID_RESPONSE',502);setSaved(result);setRectangles([]);setReview(false);setConfirmed(false);onSaved();}catch(e){if(own===sequence.current){if(e instanceof ApiError&&[401,403].includes(e.status)){setBlocked(true);setSize(undefined);setRectangles([]);setSaved(undefined);setReview(false);setConfirmed(false);setReason('');}setError(e);}}finally{clearTimeout(timeout);if(own===sequence.current)setBusy(false);}}
 const identity=`${assetId}:${asset?.version}:${copyVersion}`;imageIdentity.current=identity;
 const imageUrl=asset?`/api/v1/media/${encodeURIComponent(asset.id)}/file?copy=client&version=${copyVersion}`:'';
 if(blocked)return <div className="notice danger" role="alert">{error instanceof Error&&!(error instanceof ApiError)?error.message:errorText(error,t)}</div>;
 return <section className="content-panel client-redaction-panel" data-testid="client-redaction-panel" style={{minWidth:0,overflowWrap:'anywhere',padding:'clamp(16px,3vw,24px)',marginTop:24}}><h2><ShieldCheck size={20}/> {c('title')}</h2><p>{c('description')}</p>{Boolean(error)&&<div className="notice danger" role="alert">{error instanceof Error&&!(error instanceof ApiError)?error.message:errorText(error,t)}{error instanceof ApiError&&<small>{error.code}</small>}</div>}
 {saved&&<div className="notice" role="status"><p>{c('saved')}</p><Button variant="secondary" onClick={()=>onApprove(saved.id,saved.version)}>{c('approve')}</Button></div>}
 {!assets.length?<Empty title={c('empty')}/>:<><label className="field"><span>{c('photo')}</span><select disabled={busy} data-testid="redaction-photo" value={assetId} onChange={e=>{setAssetId(e.target.value);setSaved(undefined)}}><option value="">{c('select')}</option>{assets.map(row=><option key={row.id} value={row.id}>{row.data.caption||row.id} · {row.id}</option>)}</select></label>
 {asset&&<><p>{c('drag')}</p><Badge>{c('version')}: {copyVersion}</Badge><div style={{position:'relative',width:'100%',maxWidth:900,margin:'16px 0',lineHeight:0}}>
 <img key={imageUrl} src={imageUrl} alt={c('preview')} data-testid="redaction-image" style={{display:'block',width:'100%',height:'auto'}} onLoad={event=>{if(imageIdentity.current!==identity)return;const image=event.currentTarget;if(!image.naturalWidth||!image.naturalHeight||image.naturalWidth*image.naturalHeight>24_000_000||(asset.data.clientWidth&&asset.data.clientWidth!==image.naturalWidth)||(asset.data.clientHeight&&asset.data.clientHeight!==image.naturalHeight)){setSize(undefined);setError(new Error(c('imageError')));return;}setSize({width:image.naturalWidth,height:image.naturalHeight});}} onError={()=>{if(imageIdentity.current!==identity)return;setBlocked(true);setSize(undefined);setRectangles([]);setDragRect(undefined);setSaved(undefined);setReview(false);setConfirmed(false);setReason('');setError(new Error(c('imageError')));}}/>
 {size&&<svg data-testid="redaction-canvas" aria-label={c('preview')} viewBox={`0 0 ${size.width} ${size.height}`} style={{position:'absolute',inset:0,width:'100%',height:'100%',touchAction:'none',cursor:busy?'wait':'crosshair'}} onPointerDown={event=>{if(busy||review||rectangles.length>=30)return;start.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(start.current)setDragRect(pointerRect(event));}} onPointerUp={event=>{const rect=pointerRect(event);start.current=undefined;setDragRect(undefined);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);if(rect)add(rect);}} onPointerCancel={()=>{start.current=undefined;setDragRect(undefined);}}>{rectangles.map((rect,index)=><rect key={index} {...rect} fill="#000000" fillOpacity={1}/>)}{dragRect&&<rect {...dragRect} fill="#000000" fillOpacity={1}/>}</svg>}
 </div>{size&&<p>{size.width} × {size.height} px · {rectangles.length}/30</p>}
 <div className="form-grid">{(['x','y','width','height'] as const).map(field=><label key={field} className="field"><span>{field==='x'?'X':field==='y'?'Y':c(field)} (px)</span><input data-testid={`redaction-${field}`} type="number" required min={field==='x'||field==='y'?0:1} step={1} disabled={busy||review} value={numeric[field]} onChange={e=>setNumeric(old=>({...old,[field]:e.target.value}))}/></label>)}</div><Button variant="secondary" disabled={!size||busy||review||rectangles.length>=30} onClick={()=>add({x:Number(numeric.x),y:Number(numeric.y),width:Number(numeric.width),height:Number(numeric.height)})}>{c('add')}</Button>
 <ul style={{paddingLeft:20}}>{rectangles.map((rect,index)=><li key={index}><code>{index+1}: ({rect.x}, {rect.y}) · {rect.width} × {rect.height} px</code><Button variant="ghost" disabled={busy||review} aria-label={`${c('remove')} ${index+1}`} onClick={()=>{changed();setRectangles(rows=>rows.filter((_,i)=>i!==index));}}><X size={14}/></Button></li>)}</ul>
 <label className="field"><span>{c('reason')}</span><textarea required minLength={3} maxLength={2000} disabled={busy} value={reason} onChange={e=>{changed();setReason(e.target.value)}}/></label>
 {!review?<Button disabled={!size||!rectangles.length||reason.trim().length<3||busy||!navigator.onLine} onClick={()=>setReview(true)}>{c('review')}</Button>:<div className="notice"><label className="checkbox-field"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>{c('confirm')}</label><Button disabled={!confirmed||busy||!navigator.onLine} onClick={()=>void save()}><Check size={16}/>{c('save')}</Button><Button variant="ghost" disabled={busy} onClick={()=>{setReview(false);setConfirmed(false)}}>{t('back')}</Button></div>}
 <a className="text-link" style={{marginTop:16}} href={`/api/v1/media/${encodeURIComponent(asset.id)}/file`} target="_blank" rel="noopener noreferrer">{c('original')}</a>
 </>}
 </>}
 </section>;
}
