import {useEffect,useRef,useState} from 'react';
import {Badge,Button,Empty} from '../../../packages/ui/index';
import {languages,statusLabel,type Language} from '../../../packages/i18n/index';
import {api,ApiError,type Entity,type Session} from './api';
import {errorText,type Translate} from './CommandForm';
import {Check,Clock3,FileText,RefreshCw} from './icons';

const copy:Record<string,string[]>={
 title:['Betriebsübersichten','Операційні дайджести','Операционные дайджесты','Podsumowania operacyjne','Veiklos suvestinės','Operations digests'],
 description:['Ihre geplanten Übersichten mit aktuellem Berechtigungsumfang.','Ваші заплановані огляди з актуальними правами доступу.','Ваши запланированные обзоры с актуальными правами доступа.','Twoje zaplanowane podsumowania z bieżącym zakresem uprawnień.','Jūsų suplanuotos suvestinės pagal dabartines prieigos teises.','Your scheduled summaries within your current permissions.'],
 policy:['Gespeicherter Zeitplan','Збережений розклад','Сохранённое расписание','Zapisany harmonogram','Išsaugotas tvarkaraštis','Saved schedule'],
 new:['Neuer Zeitplan','Новий розклад','Новое расписание','Nowy harmonogram','Naujas tvarkaraštis','New schedule'],
 name:['Name','Назва','Название','Nazwa','Pavadinimas','Name'],
 kind:['Übersicht','Тип огляду','Тип обзора','Rodzaj podsumowania','Suvestinės tipas','Digest type'],
 MORNING:['Morgens','Ранковий','Утренний','Poranny','Rytinė','Morning'],
 DAY:['Täglich','Денний','Дневной','Dzienny','Dieninė','Daily'],
 WEEK:['Wöchentlich','Тижневий','Недельный','Tygodniowy','Savaitinė','Weekly'],
 time:['Uhrzeit in Berlin','Час у Берліні','Время в Берлине','Czas w Berlinie','Laikas Berlyne','Time in Berlin'],activeFrom:['Aktiv ab (UTC)','Діє з (UTC)','Действует с (UTC)','Aktywne od (UTC)','Aktyvu nuo (UTC)','Active from (UTC)'],
 weekday:['Wochentag (0 = Sonntag)','День тижня (0 = неділя)','День недели (0 = воскресенье)','Dzień tygodnia (0 = niedziela)','Savaitės diena (0 = sekmadienis)','Weekday (0 = Sunday)'],
 channel:['Kanal','Канал','Канал','Kanał','Kanalas','Channel'],channelId:['Eigener privater Direktchat','Власний приватний чат','Собственный приватный чат','Własny prywatny czat','Savo privatus pokalbis','Own private direct chat'],
 sites:['Objekte im Umfang','Об’єкти в межах доступу','Объекты в рамках доступа','Obiekty w zakresie','Objektai pagal prieigą','Sites in scope'],
 customers:['Kunden im Umfang','Клієнти в межах доступу','Клиенты в рамках доступа','Klienci w zakresie','Klientai pagal prieigą','Customers in scope'],
 template:['WhatsApp-Vorlagenname','Назва шаблону WhatsApp','Название шаблона WhatsApp','Nazwa szablonu WhatsApp','WhatsApp šablono pavadinimas','WhatsApp template name'],
 whatsapp:['WhatsApp benötigt eine tatsächlich genehmigte Vorlage und freigegebene Anbindung. Ausstehend bestätigt keine Zustellung.','Для WhatsApp потрібні реально погоджений шаблон та дозволене підключення. Очікування не підтверджує доставку.','Для WhatsApp нужны реально согласованный шаблон и разрешённое подключение. Ожидание не подтверждает доставку.','WhatsApp wymaga zatwierdzonego szablonu i połączenia. Oczekiwanie nie potwierdza dostarczenia.','WhatsApp reikia patvirtinto šablono ir ryšio. Laukimo būsena nepatvirtina pristatymo.','WhatsApp requires an approved template and connection. Pending does not confirm delivery.'],
 enabled:['Aktiviert','Увімкнено','Включено','Włączone','Įjungta','Enabled'],
 disabled:['Deaktiviert','Вимкнено','Выключено','Wyłączone','Išjungta','Disabled'],
 review:['Zeitplan prüfen','Перевірити розклад','Проверить расписание','Sprawdź harmonogram','Peržiūrėti tvarkaraštį','Review schedule'],
 save:['Zeitplan bestätigen und speichern','Підтвердити та зберегти розклад','Подтвердить и сохранить расписание','Potwierdź i zapisz harmonogram','Patvirtinti ir išsaugoti tvarkaraštį','Confirm and save schedule'],
 saved:['Zeitplan gespeichert','Розклад збережено','Расписание сохранено','Harmonogram zapisany','Tvarkaraštis išsaugotas','Schedule saved'],
 preview:['Vorschau laden','Завантажити попередній огляд','Загрузить предварительный обзор','Wczytaj podgląd','Įkelti peržiūrą','Load preview'],
 previewTitle:['Vorschau ohne Ausführung','Огляд без виконання дій','Обзор без выполнения действий','Podgląd bez wykonania','Peržiūra be vykdymo','Preview without execution'],
 noEffects:['Keine Anbindung aufgerufen, keine Geschäftsvorgänge oder Zustellung ausgeführt.','Провайдер не викликався, бізнес-дії та доставка не виконувалися.','Провайдер не вызывался, бизнес-действия и доставка не выполнялись.','Nie wywołano dostawcy ani działań biznesowych lub dostarczenia.','Teikėjas nekviestas, verslo veiksmai ir pristatymas neatlikti.','No provider call, business action or delivery was executed.'],
 confirm:['Diese Übersicht für den fälligen Zeitraum ausdrücklich erstellen.','Я явно підтверджую створення огляду за належний період.','Я явно подтверждаю создание обзора за положенный период.','Potwierdzam utworzenie podsumowania za należny okres.','Aiškiai patvirtinu suvestinės sukūrimą už reikiamą laikotarpį.','I explicitly confirm creating this digest for the due period.'],
 generate:['Fällige Übersicht erstellen','Створити належний дайджест','Создать положенный дайджест','Utwórz należne podsumowanie','Sukurti reikiamą suvestinę','Generate due digest'],
 generated:['Übersicht erstellt; Zustellung separat prüfen.','Дайджест створено; доставку перевіряйте окремо.','Дайджест создан; доставку проверяйте отдельно.','Podsumowanie utworzone; dostarczenie sprawdź osobno.','Suvestinė sukurta; pristatymą tikrinkite atskirai.','Digest created; verify delivery separately.'],
 history:['Gespeicherte Übersichten','Збережені дайджести','Сохранённые дайджесты','Zapisane podsumowania','Išsaugotos suvestinės','Saved digests'],
 unavailable:['Nicht verfügbar','Недоступно','Недоступно','Niedostępne','Nepasiekiama','Unavailable'],
 available:['Verfügbar','Доступно','Доступно','Dostępne','Pasiekiama','Available'],
 empty:['Keine eigenen Zeitpläne gespeichert','Немає власних збережених розкладів','Нет собственных сохранённых расписаний','Brak własnych zapisanych harmonogramów','Savo tvarkaraščių dar nėra','No own schedules saved'],
 period:['Zeitraum','Період','Период','Okres','Laikotarpis','Period'],
 crews:['Teams','Бригади','Бригады','Zespoły','Komandos','Crews'],tasks:['Aufgaben','Завдання','Задачи','Zadania','Užduotys','Tasks'],timeSection:['Zeit','Час','Время','Czas','Laikas','Time'],travel:['Fahrten','Поїздки','Поездки','Podróże','Kelionės','Travel'],materials:['Material','Матеріали','Материалы','Materiały','Medžiagos','Materials'],shortages:['Fehlbestände','Нестачі','Недостачи','Niedobory','Trūkumai','Shortages'],leads:['Anfragen','Заявки','Заявки','Zapytania','Užklausos','Leads'],decisions:['Entscheidungen','Рішення','Решения','Decyzje','Sprendimai','Decisions'],
 count:['Einträge','Записи','Записи','Wpisy','Įrašai','Records'],scopeNote:['Leere Auswahl bedeutet keinen zusätzlichen Filter innerhalb Ihrer aktuellen Rechte.','Порожній вибір не додає фільтрів у межах ваших поточних прав.','Пустой выбор не добавляет фильтров в рамках ваших текущих прав.','Pusty wybór nie dodaje filtra w ramach bieżących uprawnień.','Tuščias pasirinkimas neprideda filtro pagal dabartines teises.','An empty selection adds no filter within your current permissions.'],
 notDue:['Dieser Zeitplan hat noch keinen fälligen Zeitraum. Die Vorschau erstellt keine Übersicht.','Для розкладу ще немає належного періоду. Попередній огляд не створює дайджест.','Для расписания ещё нет положенного периода. Предварительный обзор не создаёт дайджест.','Harmonogram nie ma jeszcze należnego okresu. Podgląd nie tworzy podsumowania.','Tvarkaraštis dar neturi reikiamo laikotarpio. Peržiūra nesukuria suvestinės.','This schedule has no due period yet. Preview does not create a digest.'],
 approvedTime:['Genehmigte aufgezeichnete Zeit','Погоджений зафіксований час','Согласованное записанное время','Zatwierdzony zarejestrowany czas','Patvirtintas užregistruotas laikas','Approved recorded time'],
 timeNotice:['Aufgezeichnete Chronologie einschließlich Pausen und ungeklärter Aktivitäten; keine Lohnberechnung.','Зафіксована хронологія разом із перервами та нез’ясованими активностями; не розрахунок зарплати.','Записанная хронология с перерывами и неуточнёнными активностями; не расчёт зарплаты.','Zarejestrowany przebieg z przerwami i nieustalonymi aktywnościami; bez naliczania płac.','Užregistruota eiga su pertraukomis ir neišaiškinta veikla; tai ne atlyginimo skaičiavimas.','Recorded chronology includes breaks and unresolved activities; it is not payroll.'],
 approvedTravel:['Genehmigte aufgezeichnete Fahrtzeit','Погоджений зафіксований час поїздок','Согласованное записанное время поездок','Zatwierdzony zarejestrowany czas podróży','Patvirtintas užregistruotas kelionės laikas','Approved recorded travel time'],
 hours:['Stunden','Години','Часы','Godziny','Valandos','Hours'],accepted:['Abgenommen','Прийнято','Принято','Przyjęte','Priimta','Accepted'],submitted:['Eingereicht','Подано','Подано','Przesłane','Pateikta','Submitted'],incomplete:['Unvollständig','Незавершено','Незавершено','Nieukończone','Nebaigta','Incomplete'],planned:['Geplant','Заплановано','Запланировано','Planowane','Suplanuota','Planned'],reported:['Gemeldet','Заявлено','Заявлено','Zgłoszone','Pranešta','Reported'],pendingReason:['Abwesenheit, Grund ungeklärt','Відсутність, причина не з’ясована','Отсутствие, причина не уточнена','Nieobecność, powód nieustalony','Nebuvimas, priežastis neišaiškinta','Absence, reason unresolved'],unknownActivity:['Aktivität ungeklärt','Активність не з’ясована','Активность не уточнена','Aktywność nieustalona','Veikla neišaiškinta','Unresolved activity'],
 actionAmount:['Bekannte Aktionsbeträge','Відомі суми дій','Известные суммы действий','Znane kwoty działań','Žinomos veiksmų sumos','Known action amounts'],unpriced:['Ohne bekannten Betrag','Без відомої суми','Без известной суммы','Bez znanej kwoty','Be žinomos sumos','Without a known amount'],unresolved:['Unvollständige Quelldaten','Неповні дані джерел','Неполные данные источников','Niepełne dane źródłowe','Nepilni šaltinių duomenys','Incomplete source records'],
 currentTasks:['Aktueller Aufgabenstand und Mengen','Поточний стан та обсяги завдань','Текущее состояние и объёмы задач','Bieżący stan i ilości zadań','Dabartinė užduočių būklė ir kiekiai','Current task status and quantities'],
 currentNotice:['Aktueller Gesamtstand; keine im Berichtszeitraum erledigte Menge.','Поточний загальний стан; не обсяг виконання за звітний період.','Текущее общее состояние; не объём выполнения за отчётный период.','Bieżący stan ogółem; nie ilość wykonana w okresie raportu.','Dabartinė bendra būklė; tai ne ataskaitinio laikotarpio atliktas kiekis.','Current totals; these are not quantities completed during the reporting period.'],
 periodProgress:['Erfasste Ergebnisse im Zeitraum','Зафіксовані результати за період','Зафиксированные результаты за период','Zarejestrowane wyniki w okresie','Užregistruoti laikotarpio rezultatai','Recorded results within the period'],
 worklogs:['Arbeitsberichte im Zeitraum','Записи роботи за період','Записи работы за период','Wpisy pracy w okresie','Laikotarpio darbo įrašai','Worklogs in period'],
 acceptedReviews:['Abnahmeprüfungen im Zeitraum','Приймання за період','Приёмки за период','Odbiory w okresie','Laikotarpio priėmimo peržiūros','Acceptance reviews in period'],
 reopenedReviews:['Wiedereröffnungen im Zeitraum','Повторні відкриття за період','Повторные открытия за период','Ponowne otwarcia w okresie','Laikotarpio pakartotiniai atvėrimai','Reopening reviews in period'],
 grossAccepted:['Im Zeitraum abgenommen','Прийнято за період','Принято за период','Przyjęte w okresie','Priimta per laikotarpį','Accepted within period'],
 revokedAccepted:['Im Zeitraum zurückgenommen','Приймання скасовано за період','Приёмка отменена за период','Odbiory cofnięte w okresie','Laikotarpio atšaukti priėmimai','Acceptance revoked within period'],
 netAccepted:['Nettoänderung der abgenommenen Menge','Чиста зміна прийнятого обсягу','Чистое изменение принятого объёма','Zmiana netto przyjętej ilości','Priimto kiekio grynasis pokytis','Net change in accepted quantity'],
 unknownTime:['Gesamte genehmigte Zeit unbekannt: Quelldaten unvollständig.','Загальний погоджений час невідомий: дані джерел неповні.','Общее согласованное время неизвестно: данные источников неполные.','Całkowity zatwierdzony czas nieznany: niepełne dane źródłowe.','Visas patvirtintas laikas nežinomas: nepilni šaltinių duomenys.','Total approved time is unknown: source records are incomplete.'],
 knownTime:['Bekannter Anteil der genehmigten Zeit','Відома частина погодженого часу','Известная часть согласованного времени','Znana część zatwierdzonego czasu','Žinoma patvirtinto laiko dalis','Known portion of approved time']
};
export const digestLabel=(language:Language,key='title')=>copy[key]?.[languages.indexOf(language)]||key;
type Section={status:string;count?:number;approvedSeconds?:number|null;knownApprovedSeconds?:number;approvedRecordedSeconds?:number;byActivity?:Record<string,number>;counts?:Record<string,number>;byUnit?:Record<string,{plannedQuantityMilli:number;reportedQuantityMilli:number;acceptedQuantityMilli:number}>;periodProgress?:{counts:{worklogs:number;acceptedReviews:number;reopenedReviews:number};byUnit:Record<string,{reportedQuantityMilli:number;grossAcceptedQuantityMilli:number;revokedAcceptedQuantityMilli:number;acceptedQuantityMilli:number}>};byMaterialUnit?:Record<string,{materialId:string;unit:string;quantityBase:number}>;knownActionCents?:number;unpricedCount?:number;incompleteRecords?:number;unresolvedQuantityCount?:number};
type Snapshot={policyId:string;policyVersion:number;kind:string;slotAt:string;scheduledSlot:boolean;periodStart:string;periodEnd:string;asOf:string;sections:Record<string,Section>;providerInvoked:false;businessEffectsExecuted:false;coverage?:unknown};
type Form={name:string;kind:'MORNING'|'DAY'|'WEEK';time:string;activeFrom:string;weekday:string;channel:'WEB'|'WHATSAPP';channelId:string;template:string;enabled:boolean;siteIds:string[];customerIds:string[]};
const initial:Form={name:'',kind:'MORNING',time:'07:00',activeFrom:new Date().toISOString().slice(0,16),weekday:'1',channel:'WEB',channelId:'',template:'',enabled:true,siteIds:[],customerIds:[]};
export default function DigestPanel({session,records,language,t,onSaved}:{session:Session;records:Record<string,Entity[]>;language:Language;t:Translate;onSaved:()=>void}){
 const c=(key:string)=>digestLabel(language,key),[policyId,setPolicyId]=useState(''),[form,setForm]=useState<Form>(initial),[review,setReview]=useState(false),[preview,setPreview]=useState<Snapshot>(),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[blocked,setBlocked]=useState(false);
 const generation=useRef(0),controller=useRef<AbortController|undefined>(undefined),writeKey=useRef<string>(crypto.randomUUID());
 const policies=(records.digest_policy||[]).filter(row=>row.data.ownerId===session.actor.userId),history=(records.operations_digest||[]).filter(row=>row.data.ownerId===session.actor.userId),policy=policies.find(row=>row.id===policyId);
 useEffect(()=>()=>{generation.current++;controller.current?.abort()},[]);
 useEffect(()=>{generation.current++;controller.current?.abort();setBusy(false);setPreview(undefined);setConfirmed(false);setReview(false);setError(undefined);setNotice('');writeKey.current=crypto.randomUUID();if(!policy){setForm(initial);return;}const cron=String(policy.data.cron||'0 7 * * *').split(' ');setForm({name:policy.data.name||'',kind:policy.data.kind,time:`${String(cron[1]).padStart(2,'0')}:${String(cron[0]).padStart(2,'0')}`,activeFrom:policy.data.activeFrom?new Date(policy.data.activeFrom).toISOString().slice(0,16):initial.activeFrom,weekday:cron[4]==='*'?'1':cron[4],channel:policy.data.channel||'WEB',channelId:policy.data.channelId||'',template:policy.data.template||'',enabled:policy.data.enabled===true,siteIds:policy.data.scope?.siteIds||[],customerIds:policy.data.scope?.customerIds||[]});},[policyId,policy?.version]);
 function change<K extends keyof Form>(key:K,value:Form[K]){generation.current++;controller.current?.abort();setBusy(false);setForm(old=>({...old,[key]:value}));setReview(false);setPreview(undefined);setConfirmed(false);setNotice('');writeKey.current=crypto.randomUUID();}
 async function run(name:string,input:unknown,expectedVersion?:number,key?:string){if(blocked)return;const own=++generation.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;const timeout=setTimeout(()=>abort.abort(),15_000);setBusy(true);setError(undefined);try{const result=await api<any>(`/api/v1/commands/${name}`,{method:'POST',signal:abort.signal,body:JSON.stringify({input,expected_version:expectedVersion,idempotency_key:key||crypto.randomUUID()})});return own===generation.current?result:undefined;}catch(e){if(own===generation.current){if(e instanceof ApiError&&[401,403].includes(e.status)){setPreview(undefined);setForm(initial);setReview(false);setConfirmed(false);setNotice('');setBlocked(true);}setError(e);}}finally{clearTimeout(timeout);if(own===generation.current)setBusy(false);}}
 function input(){const [hour,minute]=form.time.split(':').map(Number);return {...(policy?{id:policy.id}:{}),name:form.name,kind:form.kind,ownerId:session.actor.userId,scope:{siteIds:form.siteIds,customerIds:form.customerIds},cron:`${minute} ${hour} * * ${form.kind==='WEEK'?form.weekday:'*'}`,timezone:'Europe/Berlin',activeFrom:new Date(form.activeFrom+'Z').toISOString(),channel:form.channel,...(form.channel==='WHATSAPP'?{channelId:form.channelId,...(form.template?{template:form.template,templateStatus:'PENDING'}:{})}:{}),enabled:form.enabled};}
 async function save(){const result=await run('digest.configure',input(),policy?.version,writeKey.current);if(result?.id){setPolicyId(result.id);setReview(false);setNotice(c('saved'));writeKey.current=crypto.randomUUID();onSaved();}}
 async function previewPolicy(){if(!policy)return;setPreview(undefined);setConfirmed(false);const result=await run('digest.preview',{policyId:policy.id});if(result){if(result.providerInvoked!==false||result.businessEffectsExecuted!==false||result.policyId!==policy.id||result.policyVersion!==policy.version){setError(new ApiError('INVALID_RESPONSE',502));return;}setPreview(result);writeKey.current=crypto.randomUUID();}}
 async function generate(){if(!policy||!preview||!confirmed||!preview.scheduledSlot||preview.policyVersion!==policy.version)return;const result=await run('digest.generate',{policyId:policy.id,policyVersion:preview.policyVersion,slotAt:preview.slotAt},policy.version,writeKey.current);if(result?.kind==='operations_digest'){setNotice(c('generated'));setConfirmed(false);writeKey.current=crypto.randomUUID();onSaved();}}
 const metric=(value:Section)=><>
  {typeof value.approvedSeconds==='number'&&<><p>{c('approvedTime')}: {(value.approvedSeconds/3600).toLocaleString(language==='UK'?'uk-UA':language.toLowerCase(),{maximumFractionDigits:2})} {c('hours')}</p><small>{c('timeNotice')}</small></>}
  {value.approvedSeconds===null&&<><p className="notice warning">{c('unknownTime')}</p>{typeof value.knownApprovedSeconds==='number'&&<p>{c('knownTime')}: {(value.knownApprovedSeconds/3600).toLocaleString(language==='UK'?'uk-UA':language.toLowerCase(),{maximumFractionDigits:2})} {c('hours')}</p>}<small>{c('timeNotice')}</small></>}
  {typeof value.approvedRecordedSeconds==='number'&&<p>{c('approvedTravel')}: {(value.approvedRecordedSeconds/3600).toLocaleString(language==='UK'?'uk-UA':language.toLowerCase(),{maximumFractionDigits:2})} {c('hours')}</p>}
  {value.byActivity&&Object.entries(value.byActivity).map(([activity,seconds])=><p key={activity}>{activity==='TRAVELLING'?t('travel'):activity==='AWAY_PENDING_REASON'?c('pendingReason'):activity==='UNKNOWN'?c('unknownActivity'):statusLabel(activity,t)}: {(seconds/3600).toFixed(2)} {c('hours')}</p>)}
  {(value.counts||value.byUnit)&&<div data-testid="digest-current-tasks"><h4>{c('currentTasks')}</h4><small>{c('currentNotice')}</small>
   {value.counts&&Object.entries(value.counts).map(([key,count])=><p key={key}>{c(key)}: {count}</p>)}
   {value.byUnit&&Object.entries(value.byUnit).map(([unit,values])=><p key={unit}>{unit}: {c('planned')} {values.plannedQuantityMilli/1000} · {c('reported')} {values.reportedQuantityMilli/1000} · {c('accepted')} {values.acceptedQuantityMilli/1000}</p>)}
  </div>}
  {value.periodProgress&&<div data-testid="digest-period-progress"><h4>{c('periodProgress')}</h4>
   {Object.entries(value.periodProgress.counts).map(([key,count])=><p key={key}>{c(key)}: {count}</p>)}
   {Object.entries(value.periodProgress.byUnit).map(([unit,values])=><div key={unit}><b>{unit}</b><p>{c('reported')}: {values.reportedQuantityMilli/1000}</p><p>{c('grossAccepted')}: {values.grossAcceptedQuantityMilli/1000}</p><p>{c('revokedAccepted')}: {values.revokedAcceptedQuantityMilli/1000}</p><p>{c('netAccepted')}: {values.acceptedQuantityMilli/1000}</p></div>)}
  </div>}
  {value.byMaterialUnit&&Object.values(value.byMaterialUnit).map(row=><p key={`${row.materialId}:${row.unit}`}>{records.material?.find(material=>material.id===row.materialId)?.data.name||row.materialId}: {row.quantityBase} {row.unit}</p>)}
  {typeof value.knownActionCents==='number'&&<p>{c('actionAmount')}: {new Intl.NumberFormat(language==='UK'?'uk-UA':language.toLowerCase(),{style:'currency',currency:'EUR'}).format(value.knownActionCents/100)}</p>}
  {typeof value.unpricedCount==='number'&&<p>{c('unpriced')}: {value.unpricedCount}</p>}
  {Boolean(value.incompleteRecords||value.unresolvedQuantityCount)&&<p>{c('unresolved')}: {value.incompleteRecords??value.unresolvedQuantityCount}</p>}
 </>;
 if(blocked)return <div className="notice danger" role="alert">{errorText(error,t)}</div>;
 const ownChannels=(records.channel||[]).filter(row=>row.data.type==='DIRECT'&&(row.data.members||[]).every((member:{user_id:string;revoked_at?:string})=>Boolean(member.revoked_at)||member.user_id===session.actor.userId||(records.user||[]).some(user=>user.id===member.user_id&&user.data.active!==false&&user.data.roles?.includes('SERVICE_ACCOUNT'))));
 return <section className="content-panel digest-panel" data-testid="digest-panel" style={{minWidth:0,overflowWrap:'anywhere',padding:'clamp(16px,3vw,24px)'}}><div className="panel-heading"><div><h2><Clock3 size={19}/> {c('title')}</h2><p>{c('description')}</p></div><Button variant="secondary" onClick={onSaved}><RefreshCw size={16}/>{t('refresh')}</Button></div>
 {Boolean(error)&&<div className="notice danger" role="alert">{errorText(error,t)}{error instanceof ApiError&&<small>{error.code}</small>}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
 <label className="field"><span>{c('policy')}</span><select data-testid="digest-policy" value={policyId} disabled={busy} onChange={e=>setPolicyId(e.target.value)}><option value="">{c('new')}</option>{policies.map(row=><option key={row.id} value={row.id}>{row.data.name} · v{row.version}</option>)}</select></label>
 <form onSubmit={e=>{e.preventDefault();setReview(true)}}><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><div className="form-grid"><label className="field"><span>{c('name')}</span><input required minLength={3} maxLength={150} value={form.name} onChange={e=>change('name',e.target.value)}/></label><label className="field"><span>{c('kind')}</span><select value={form.kind} onChange={e=>change('kind',e.target.value as Form['kind'])}>{['MORNING','DAY','WEEK'].map(kind=><option key={kind} value={kind}>{c(kind)}</option>)}</select></label><label className="field"><span>{c('time')}</span><input type="time" required value={form.time} onChange={e=>change('time',e.target.value)}/></label><label className="field"><span>{c('activeFrom')}</span><input type="datetime-local" required value={form.activeFrom} onChange={e=>change('activeFrom',e.target.value)}/></label>{form.kind==='WEEK'&&<label className="field"><span>{c('weekday')}</span><select value={form.weekday} onChange={e=>change('weekday',e.target.value)}>{Array.from({length:7},(_,day)=><option key={day} value={day}>{day}</option>)}</select></label>}<label className="field"><span>{c('channel')}</span><select value={form.channel} onChange={e=>change('channel',e.target.value as Form['channel'])}><option>WEB</option><option>WHATSAPP</option></select></label>{form.channel==='WHATSAPP'&&<><label className="field"><span>{c('channelId')}</span><select required value={form.channelId} onChange={e=>change('channelId',e.target.value)}><option value="">{t('selectChannel')}</option>{ownChannels.map(row=><option key={row.id} value={row.id}>{row.data.name||row.id}</option>)}</select></label><label className="field"><span>{c('template')}</span><input minLength={1} maxLength={100} value={form.template} onChange={e=>change('template',e.target.value)}/></label><p className="notice warning full">{c('whatsapp')}</p></>}<label className="checkbox-field"><input type="checkbox" checked={form.enabled} onChange={e=>change('enabled',e.target.checked)}/>{c('enabled')}</label><fieldset className="field full"><legend>{c('sites')}</legend>{(records.site||[]).map(row=><label className="checkbox-field" key={row.id}><input type="checkbox" checked={form.siteIds.includes(row.id)} onChange={e=>change('siteIds',e.target.checked?[...form.siteIds,row.id]:form.siteIds.filter(id=>id!==row.id))}/>{row.data.name||row.id}</label>)}</fieldset><fieldset className="field full"><legend>{c('customers')}</legend>{(records.customer||[]).map(row=><label className="checkbox-field" key={row.id}><input type="checkbox" checked={form.customerIds.includes(row.id)} onChange={e=>change('customerIds',e.target.checked?[...form.customerIds,row.id]:form.customerIds.filter(id=>id!==row.id))}/>{row.data.name||row.id}</label>)}</fieldset></div><p className="muted">{c('scopeNote')}</p>
 {!review?<Button disabled={busy||!navigator.onLine}>{c('review')}</Button>:<div className="notice"><p><b>{form.name}</b> · {c(form.kind)} · {form.time} Europe/Berlin · {form.channel} · {c(form.enabled?'enabled':'disabled')}</p><Button type="button" disabled={busy||!navigator.onLine} onClick={()=>void save()}><Check size={15}/>{c('save')}</Button><Button variant="ghost" type="button" onClick={()=>setReview(false)}>{t('back')}</Button></div>}</fieldset></form>
 {policy&&<div style={{marginTop:24}}><Button variant="secondary" disabled={busy||!navigator.onLine} onClick={()=>void previewPolicy()}><FileText size={16}/>{c('preview')}</Button></div>}
 {preview&&<section data-testid="digest-preview" style={{marginTop:20}}><h3>{c('previewTitle')}</h3><p className="notice">{c('noEffects')}</p><p>{c('period')}: {preview.periodStart} — {preview.periodEnd}</p><div className="decision-grid">{Object.entries(preview.sections).map(([section,value])=><article className="decision-card" key={section}><h3>{c(section==='time'?'timeSection':section)}</h3><Badge tone={value.status==='AVAILABLE'?'green':'amber'}>{c(value.status==='AVAILABLE'?'available':'unavailable')}</Badge>{value.status==='AVAILABLE'&&typeof value.count==='number'&&<p>{c('count')}: {value.count}</p>}{value.status==='AVAILABLE'&&metric(value)}</article>)}</div>{!preview.scheduledSlot&&<p className="notice warning">{c('notDue')}</p>}<label className="checkbox-field" style={{marginTop:16}}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{c('confirm')}</label><Button disabled={!confirmed||!preview.scheduledSlot||busy||!navigator.onLine||policy?.version!==preview.policyVersion} onClick={()=>void generate()}>{c('generate')}</Button></section>}
 <h3>{c('history')}</h3>{!history.length?<Empty title={policies.length?t('empty'):c('empty')}/>:history.map(row=><article className="decision-card" key={row.id}><h4>{c(row.data.kind||row.data.snapshot?.kind||'DAY')}</h4><p>{row.data.snapshot?.periodStart} — {row.data.snapshot?.periodEnd}</p><code>{row.id}</code><p>{row.data.createdAt||row.createdAt}</p></article>)}
 </section>;
}
