import {describe,expect,it} from 'vitest';
import type {Entity,Session} from './api';
import {eligibleInternalChannel,ownOriginalMessage,validateInternalPreview,internalConfirmationInput,validInternalReceipt,type InternalPreview} from './internalAssistantModel';
const row=(kind:string,data:Record<string,any>,id=kind):Entity=>({id,kind,version:1,createdAt:'2026-10-06T10:00:00Z',updatedAt:'2026-10-06T10:00:00Z',data});
const session={actor:{userId:'u'}} as Session;
const channel=row('channel',{type:'SITE_INTERNAL',members:[{user_id:'u',history_from:'2026-10-06T09:00:00Z'}]});
const original=row('message',{channel_id:'channel',author_id:'u',source:'HUMAN',message_version:2,text:'Clean UG.'});
const request=row('internal_assistant_request',{draftId:'draft',kind:'TASK_BATCH',messageId:'message',messageVersion:2,channelId:'channel'});
const task={siteId:'site',locationId:'room',title:'Clean UG',sourceQuote:'Clean UG.',fullPath:['S · Site','UG · Untergeschoss','R · Room'],description:'',plannedQuantityMilli:1000,unit:'ROOM',assigneeIds:['u'],executors:[{id:'u',label:'Worker'}],checklist:[{id:'c',label:'Clean room',required:true,checked:false}],acceptanceCriteria:['Clean surfaces'],billingScope:'INTERNAL',clientVisible:false};
const preview:InternalPreview={draftId:'draft',draftVersion:7,requestId:request.id,kind:'TASK_BATCH',status:'DRAFT',previewHash:'a'.repeat(64),source:{messageId:'message',messageVersion:2,channelId:'channel'},needsClarification:false,preview:{kind:'TASK_BATCH',tasks:[task],sideEffectsExecuted:false},requiresUserConfirmation:true,sideEffectsExecuted:false};
describe('internal assistant review boundaries',()=>{
 it('accepts only a current own HUMAN original in a permitted internal channel',()=>{expect(ownOriginalMessage(original,channel,session)).toBe(true);for(const data of [{author_id:'other'},{source:'AI'},{deleted_at:'now'},{channel_id:'other'},{message_version:0},{text:'x'.repeat(4001)}])expect(ownOriginalMessage({...original,data:{...original.data,...data}},channel,session)).toBe(false)});
 it('excludes private customers, confidential, revoked and expired memberships',()=>{for(const data of [{type:'PRIVATE_CUSTOMER_ASSISTANT'},{confidential:true},{members:[{user_id:'u',revoked_at:'now'}]},{members:[{user_id:'u',expires_at:'2020-01-01'}]},{members:[{user_id:'u',external:true}]}])expect(eligibleInternalChannel({...channel,data:{...channel.data,...data}},'u')).toBe(false)});
 it('does not offer a source before the permitted history boundary',()=>expect(ownOriginalMessage({...original,createdAt:'2026-10-05T10:00:00Z'},channel,session)).toBe(false));
 it('binds preview to exact original message, request and source version',()=>{expect(validateInternalPreview(preview,request)).toBe(true);for(const changes of [{requestId:'other'},{draftId:'other'},{previewHash:'bad'},{source:{...preview.source,messageVersion:3}},{sideEffectsExecuted:true},{requiresUserConfirmation:false},{preview:{kind:'REPORT'}}])expect(validateInternalPreview({...preview,...changes},request)).toBe(false)});
 it('rejects a missing floor path, false quantity or incomplete executors before offering confirmation',()=>{for(const changes of [{fullPath:[]},{plannedQuantityMilli:-1},{executors:[]},{checklist:[{id:'c',label:'Clean room',checked:true}]},{clientVisible:true},{sourceQuote:''}])expect(validateInternalPreview({...preview,preview:{...preview.preview,tasks:[{...task,...changes}]}},request)).toBe(false)});
 it('requires a separate checked current DRAFT and preserves server version/hash',()=>{expect(internalConfirmationInput(preview,true)).toEqual({draftId:'draft',expectedVersion:7,previewHash:'a'.repeat(64),confirmed:true});expect(()=>internalConfirmationInput(preview,false)).toThrow('REVIEW_REQUIRED');for(const changes of [{status:'NEEDS_CLARIFICATION'},{status:'CONFIRMED'},{sideEffectsExecuted:true},{draftVersion:0}])expect(()=>internalConfirmationInput({...preview,...changes} as InternalPreview,true)).toThrow()});
 it('accepts only an actual receipt for the requested business command without publication',()=>{const receipt={draftId:'draft',command:'task.bulk.commit',entityIds:['t'],result:[{id:'t',kind:'task',version:1,state:'DRAFT'}],sideEffectsExecuted:true,automaticPublication:false};expect(validInternalReceipt(receipt,preview)).toBe(true);for(const changes of [{automaticPublication:true},{command:'payout.create'},{entityIds:[]},{sideEffectsExecuted:false},{result:[{id:'wrong',kind:'task',version:1}]}])expect(validInternalReceipt({...receipt,...changes},preview)).toBe(false)});
});
