import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Badge,Button,Empty} from '../../../packages/ui/index';
import {languageNames,type Language} from '../../../packages/i18n/index';
import {AlertTriangle,Check,RefreshCw,Sparkles} from './icons';
import {api,command,entities,ApiError,type Command,type Entity,type Session} from './api';
import {entityName,errorText} from './CommandForm';
import {eligibleInternalChannel,ownOriginalMessage,validateInternalPreview,internalConfirmationInput,validInternalReceipt,type InternalContext,type InternalDraftKind,type InternalPreview,type InternalRequestInput} from './internalAssistantModel';
import './InternalAssistantPanel.css';

type Props={session:Session;records:Record<string,Entity[]>;allowed:Command[];t:(key:string)=>string;language:Language;onManual:(name:string,input?:any)=>void;onRefresh:()=>void};
const emptyContext=():InternalContext=>({locationIds:[],assigneeIds:[],taskIds:[],materialIds:[],orderIds:[],reportIds:[]});
const kinds:InternalDraftKind[]=['TASK_BATCH','REPORT','MATERIAL_REQUEST'];
const permissions:Record<InternalDraftKind,string>={TASK_BATCH:'task.create',REPORT:'report.create',MATERIAL_REQUEST:'inventory.request'};
const locales={DE:'de-DE',UK:'uk-UA',RU:'ru-RU',PL:'pl-PL',LT:'lt-LT',EN:'en-GB'};
const internalRoles=['OWNER','DIRECTOR','OPERATIONS_MANAGER','INTERNAL_BAULEITER','TEAM_LEADER'];
function extractedMessages(value:any):Entity[]{const rows=Array.isArray(value)?value:value?.items??value?.messages??value?.result?.items??value?.result?.messages??value?.result;return Array.isArray(rows)?rows:[];}
function uncertain(error:unknown){return !(error instanceof ApiError)||error.status>=500||error.status===408;}
async function boundedCommand(name:string,input:unknown,key:string=crypto.randomUUID()) {
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
 try{return await api(`/api/v1/commands/${encodeURIComponent(name)}`,{method:'POST',signal:controller.signal,body:JSON.stringify({input,idempotency_key:key})})}finally{clearTimeout(timer)}
}
export default function InternalAssistantPanel({session,records,allowed,t,language,onManual,onRefresh}:Props){
 const actorKey=JSON.stringify([session.actor.userId,session.actor.roles,session.actor.permissions]);
 const channels=useMemo(()=>(records.channel||[]).filter(c=>eligibleInternalChannel(c,session.actor.userId)),[records.channel,session.actor.userId]);
 const configs=useMemo(()=>(records.assistant_config||[]).filter(c=>c.data.status==='ACTIVE'&&['DEEPSEEK','DISABLED'].includes(c.data.provider)&&Number.isSafeInteger(c.data.configVersion)),[records.assistant_config]);
 const offeredKinds=kinds.filter(kind=>session.actor.permissions.includes(permissions[kind]));
 const enabled=internalRoles.some(role=>session.actor.roles.includes(role))&&allowed.some(c=>c.name==='internal_assistant.request')&&session.actor.permissions.includes('chat.read')&&offeredKinds.length>0;
 const [channelId,setChannelId]=useState(''),[messageId,setMessageId]=useState(''),[configId,setConfigId]=useState(''),[kind,setKind]=useState<InternalDraftKind>('TASK_BATCH'),[siteIds,setSiteIds]=useState<string[]>([]),[context,setContext]=useState<InternalContext>(emptyContext);
 const [messages,setMessages]=useState<Entity[]>([]),[requests,setRequests]=useState<Entity[]>([]),[drafts,setDrafts]=useState<Entity[]>([]),[preview,setPreview]=useState<InternalPreview>(),[reviewed,setReviewed]=useState(false),[receipt,setReceipt]=useState<Record<string,any>>(),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[reading,setReading]=useState(false),[unknownIntent,setUnknownIntent]=useState<{input:InternalRequestInput;key:string}>(),[confirmationUnknown,setConfirmationUnknown]=useState(false);
 const generation=useRef(0),messageSequence=useRef(0),refreshSequence=useRef(0),mutating=useRef(false),confirmKey=useRef(''),active=useRef(false),intent=useRef<{input:InternalRequestInput;key:string}|undefined>(undefined);
 const channel=channels.find(c=>c.id===channelId),source=messages.find(m=>m.id===messageId),config=configs.find(c=>c.id===configId);
 const channelSite=channel?.data.site_id||(channel?.data.task_id?(records.task||[]).find(task=>task.id===channel.data.task_id)?.data.siteId:undefined);
 const sites=(records.site||[]).filter(site=>site.data.active!==false&&(!channelSite||site.id===channelSite));
 const scoped=(rows:Entity[])=>rows.filter(row=>siteIds.includes(row.data.siteId));
 const options:Record<keyof InternalContext,Entity[]>={locationIds:scoped(records.location||[]).filter(row=>row.data.active===true),assigneeIds:session.actor.permissions.includes('task.assign')?(records.user||[]).filter(row=>row.data.active!==false&&!row.data.roles?.some((role:string)=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(role))&&(row.data.siteIds||[]).some((id:string)=>siteIds.includes(id))):[],taskIds:scoped(records.task||[]),materialIds:session.actor.permissions.includes('inventory.read')?(records.material||[]).filter(row=>row.data.active!==false):[],orderIds:scoped(records.order||[]),reportIds:scoped(records.report||[])};
 const labels:Record<keyof InternalContext,string>={locationIds:'internalDraftLocations',assigneeIds:'internalDraftAssignees',taskIds:'internalDraftTasks',materialIds:'internalDraftMaterials',orderIds:'internalDraftOrders',reportIds:'internalDraftReports'};
 const lookup=(entityId:string,entityKind?:string)=>{const row=(entityKind?records[entityKind]||[]:Object.values(records).flat()).find(entity=>entity.id===entityId);return row?entityName(row):t('internalDraftUnavailableReference')};
 const locationName=(node:Entity)=>{const path:string[]=[],seen=new Set<string>();let cursor:Entity|undefined=node;while(cursor&&!seen.has(cursor.id)&&seen.size<20){seen.add(cursor.id);path.unshift(`${cursor.data.code||''} · ${cursor.data.floorLabelDe||cursor.data.name||''}`);cursor=cursor.data.parentId?(records.location||[]).find(row=>row.id===cursor!.data.parentId):undefined}return path.join(' / ')};
 const display=(row:Entity)=>row.kind==='location'?locationName(row):entityName(row);
 const currentPreviewRequest=preview&&requests.find(row=>row.id===preview.requestId);
 const sourceChanged=Boolean(preview&&preview.status==='DRAFT'&&(!currentPreviewRequest||currentPreviewRequest.data.status!=='READY'||!configs.some(c=>c.id===currentPreviewRequest.data.configId&&c.data.configVersion===currentPreviewRequest.data.configVersion)||drafts.some(d=>d.id===preview.draftId&&d.version!==preview.draftVersion)));

 const refresh=useCallback(async()=>{
  if(!enabled||!active.current)return;const epoch=generation.current,sequence=++refreshSequence.current;setReading(true);
  try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);let rows:Entity[][];try{rows=await Promise.all([entities('internal_assistant_request',{signal:controller.signal}),entities('internal_assistant_draft',{signal:controller.signal})])}finally{clearTimeout(timer)}
   if(!active.current||epoch!==generation.current||sequence!==refreshSequence.current)return;setRequests(rows[0].filter(row=>row.data.ownerUserId===session.actor.userId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setDrafts(rows[1].filter(row=>row.data.ownerUserId===session.actor.userId));
  }catch(err){if(active.current&&epoch===generation.current&&sequence===refreshSequence.current){setError(err);if(err instanceof ApiError&&[401,403,404].includes(err.status)){setRequests([]);setDrafts([]);setPreview(undefined);setReceipt(undefined)}}}
  finally{if(active.current&&epoch===generation.current&&sequence===refreshSequence.current)setReading(false)}
 },[enabled,session.actor.userId]);
 useEffect(()=>{active.current=true;generation.current++;setChannelId('');setMessageId('');setConfigId('');setSiteIds([]);setContext(emptyContext());setMessages([]);setRequests([]);setDrafts([]);setPreview(undefined);setReceipt(undefined);setUnknownIntent(undefined);setConfirmationUnknown(false);setReviewed(false);setError(undefined);intent.current=undefined;mutating.current=false;setBusy(false);void refresh();return()=>{active.current=false;generation.current++;messageSequence.current++;refreshSequence.current++}},[actorKey,enabled,refresh]);
 useEffect(()=>{if(!enabled||!requests.some(row=>['PENDING','RUNNING'].includes(row.data.status)))return;const timer=setInterval(()=>{if(navigator.onLine&&document.visibilityState==='visible'&&!mutating.current)void refresh()},10000);return()=>clearInterval(timer)},[enabled,requests,refresh]);
 useEffect(()=>{if(sourceChanged&&!confirmationUnknown){setPreview(undefined);setReviewed(false)}},[sourceChanged,confirmationUnknown]);
 useEffect(()=>{setMessages([]);setMessageId('');if(!channel||!enabled)return;const sequence=++messageSequence.current,epoch=generation.current;setReading(true);command('message.read',{channel_id:channel.id,limit:100}).then(value=>{if(active.current&&epoch===generation.current&&sequence===messageSequence.current)setMessages(extractedMessages(value).filter(m=>ownOriginalMessage(m,channel,session)))}).catch(err=>{if(active.current&&epoch===generation.current&&sequence===messageSequence.current)setError(err)}).finally(()=>{if(active.current&&epoch===generation.current&&sequence===messageSequence.current)setReading(false)});return()=>{messageSequence.current++}},[channelId,channel?.version,enabled,actorKey]);
 useEffect(()=>{if(configId&&!configs.some(c=>c.id===configId)){setConfigId('');intent.current=undefined}if(channelId&&!channels.some(c=>c.id===channelId)){messageSequence.current++;setChannelId('');setMessages([]);setMessageId('');setPreview(undefined);setReceipt(undefined)}},[configs,channels,channelId,configId]);

 function edit(change:()=>void){if(busy||unknownIntent||confirmationUnknown)return;change();intent.current=undefined;setPreview(undefined);setReceipt(undefined);setReviewed(false);setError(undefined)}
 async function submitRequest(){
  if(mutating.current||!enabled)return;let pending=unknownIntent||intent.current;
  if(!pending){if(!channel||!source||!config||!ownOriginalMessage(source,channel,session)||!siteIds.length||siteIds.length>10||!offeredKinds.includes(kind))return;
   const visibleSites=siteIds.filter(id=>sites.some(site=>site.id===id));if(visibleSites.length!==siteIds.length)return;
   if(Object.entries(context).some(([key,ids])=>ids.some((id:string)=>!options[key as keyof InternalContext].some(row=>row.id===id)))){setError(new ApiError('VERSION_CONFLICT',409));return;}
   const selectedContext=structuredClone(context);
   pending={input:{messageId:source.id,messageVersion:source.data.message_version,channelId:channel.id,configId:config.id,configVersion:config.data.configVersion,kind,siteIds:[...siteIds],context:selectedContext},key:crypto.randomUUID()};intent.current=pending;
  }
  mutating.current=true;setBusy(true);setError(undefined);const epoch=generation.current;
  try{const result:Entity=await boundedCommand('internal_assistant.request',pending.input,pending.key);if(!active.current||epoch!==generation.current)return;
   if(result?.kind!=='internal_assistant_request'||result.data?.ownerUserId!==session.actor.userId||result.data?.messageId!==pending.input.messageId||result.data?.kind!==pending.input.kind||!['PENDING','RUNNING','READY','NEEDS_CLARIFICATION','FAILED','CONFIRMED'].includes(result.data.status))throw new ApiError('REQUEST_FAILED',502);
   setRequests(rows=>[result,...rows.filter(row=>row.id!==result.id)]);setUnknownIntent(undefined);intent.current=pending;setReceipt(undefined);setPreview(undefined);setReviewed(false);await refresh();onRefresh();
  }catch(err){if(active.current&&epoch===generation.current){setError(err);if(uncertain(err))setUnknownIntent(pending);else{setUnknownIntent(undefined);intent.current=undefined}}}
  finally{if(active.current&&epoch===generation.current){mutating.current=false;setBusy(false)}}
 }
 async function loadPreview(request:Entity){
  if(mutating.current||!request.data.draftId)return;mutating.current=true;setBusy(true);setPreview(undefined);setReceipt(undefined);setReviewed(false);setConfirmationUnknown(false);setError(undefined);const epoch=generation.current;
  try{const value=await boundedCommand('internal_assistant.preview',{draftId:request.data.draftId});if(!active.current||epoch!==generation.current)return;if(!validateInternalPreview(value,request))throw new ApiError('REQUEST_FAILED',502);setPreview(value);confirmKey.current=crypto.randomUUID()}
  catch(err){if(active.current&&epoch===generation.current)setError(err)}finally{if(active.current&&epoch===generation.current){mutating.current=false;setBusy(false)}}
 }
 async function confirm(){
  if(mutating.current||!preview||(!confirmationUnknown&&sourceChanged))return;let input;try{input=internalConfirmationInput(preview,reviewed)}catch{return}mutating.current=true;setBusy(true);setError(undefined);const epoch=generation.current;
  try{const result=await boundedCommand('internal_assistant.confirm',input,confirmKey.current);if(!active.current||epoch!==generation.current)return;if(!validInternalReceipt(result,preview))throw new ApiError('REQUEST_FAILED',502);setReceipt(result);setConfirmationUnknown(false);setPreview(undefined);setReviewed(false);await refresh();onRefresh()}
  catch(err){if(active.current&&epoch===generation.current){setError(err);if(uncertain(err))setConfirmationUnknown(true);else{setPreview(undefined);setReviewed(false);setConfirmationUnknown(false);await refresh();onRefresh()}}}finally{if(active.current&&epoch===generation.current){mutating.current=false;setBusy(false)}}
 }
 if(!enabled)return null;
 const selectValues=(event:React.ChangeEvent<HTMLSelectElement>)=>Array.from(event.target.selectedOptions,option=>option.value);
 const locked=busy||Boolean(unknownIntent)||confirmationUnknown;
 const date=(value:string)=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString(locales[language],{timeZone:'Europe/Berlin'}):value;
 const previewInput=preview?.preview.input||{};
 const manualCommand={TASK_BATCH:'task.create',REPORT:'report.create',MATERIAL_REQUEST:'request.create'}[kind];
 return <section className="internal-assistant-panel" data-testid="internal-assistant-panel" aria-labelledby="internal-assistant-title">
  <header><Sparkles size={22}/><div><h2 id="internal-assistant-title">{t('internalDraftTitle')}</h2><p>{t('internalDraftDescription')}</p></div><Button variant="ghost" data-testid="internal-assistant-refresh" disabled={reading||busy||!navigator.onLine} onClick={()=>{setError(undefined);void refresh();onRefresh()}}><RefreshCw size={16}/>{t('refresh')}</Button></header>
  <p className="internal-draft-boundary">{t('internalDraftBoundary')}</p>
  {Boolean(error)&&<div role="alert" className="notice danger"><AlertTriangle size={17}/><div>{errorText(error,t)}{error instanceof ApiError&&<small>{error.code}</small>}</div></div>}
  {unknownIntent&&<div role="status" className="notice warning"><span>{t('internalDraftUnknown')}</span><Button data-testid="internal-assistant-delivery-check" disabled={busy||!navigator.onLine} onClick={()=>void submitRequest()}>{t('queueCheckReceipt')}</Button></div>}
  <form className="internal-draft-form" onSubmit={e=>{e.preventDefault();void submitRequest()}}>
   <div className="internal-draft-fields"><label className="field"><span>{t('internalDraftChannel')}</span><select data-testid="internal-assistant-channel" required disabled={locked} value={channelId} onChange={e=>edit(()=>{setChannelId(e.target.value);setSiteIds([]);setContext(emptyContext())})}><option value="">{t('internalDraftChoose')}</option>{channels.map(row=><option key={row.id} value={row.id}>{entityName(row)}</option>)}</select></label>
   <label className="field"><span>{t('internalDraftMessage')}</span><select data-testid="internal-assistant-message" required disabled={locked||!channelId||reading} value={messageId} onChange={e=>edit(()=>setMessageId(e.target.value))}><option value="">{t('internalDraftChoose')}</option>{messages.map(row=><option key={row.id} value={row.id}>{row.data.text.slice(0,110)} · v{row.data.message_version}</option>)}</select></label>
   <label className="field"><span>{t('internalDraftConfig')}</span><select data-testid="internal-assistant-config" required disabled={locked} value={configId} onChange={e=>edit(()=>setConfigId(e.target.value))}><option value="">{t('internalDraftChoose')}</option>{configs.map(row=><option key={row.id} value={row.id}>{entityName(row)} · v{row.data.configVersion} · {row.data.provider}</option>)}</select></label>
   <label className="field"><span>{t('internalDraftKind')}</span><select data-testid="internal-assistant-kind" value={offeredKinds.includes(kind)?kind:''} required disabled={locked} onChange={e=>edit(()=>{setKind(e.target.value as InternalDraftKind);setContext(emptyContext())})}><option value="" disabled>{t('internalDraftChoose')}</option>{offeredKinds.map(value=><option key={value} value={value}>{t('internalDraftKind_'+value)}</option>)}</select></label></div>
   {config?.data.provider==='DISABLED'&&<p className="notice warning" data-testid="internal-assistant-disabled-notice">{t('internalDraftDisabledNotice')}</p>}{!channels.length&&<p className="notice warning">{t('internalDraftNoChannels')}</p>}{channelId&&!reading&&!messages.length&&<p className="notice warning">{t('internalDraftNoMessages')}</p>}{!configs.length&&<p className="notice warning">{t('internalDraftNoConfig')}</p>}
   {source&&<blockquote className="internal-draft-original"><small>{t('original')} · {languageNames[source.data.language as Language]||source.data.language} · v{source.data.message_version}</small><p>{source.data.text}</p></blockquote>}
   <fieldset disabled={locked} className="internal-draft-context"><legend>{t('internalDraftContext')}</legend><p>{t('internalDraftContextNotice')}</p><label className="field"><span>{t('internalDraftSites')} *</span><select data-testid="internal-assistant-sites" multiple size={Math.min(4,Math.max(2,sites.length))} required value={siteIds} onChange={e=>edit(()=>{setSiteIds(selectValues(e).slice(0,10));setContext(emptyContext())})}>{sites.map(row=><option key={row.id} value={row.id}>{entityName(row)}</option>)}</select></label><div className="internal-draft-fields">{(Object.keys(context) as (keyof InternalContext)[]).map(key=><label className="field" key={key}><span>{t(labels[key])}</span><select data-testid={'internal-assistant-'+key} multiple size={3} value={context[key]} disabled={!siteIds.length||!options[key].length||locked} onChange={e=>edit(()=>setContext(old=>({...old,[key]:selectValues(e)})))}>{options[key].map(row=><option key={row.id} value={row.id}>{display(row)}</option>)}</select></label>)}</div></fieldset>
   <div className="internal-draft-actions"><Button data-testid="internal-assistant-request" disabled={locked||!source||!config||!siteIds.length||!navigator.onLine}>{busy?t('loading'):t('internalDraftRequest')}</Button>{allowed.some(row=>row.name===manualCommand)&&<Button type="button" variant="secondary" disabled={busy} onClick={()=>onManual(manualCommand,{...(siteIds[0]?{siteId:siteIds[0]}:{}),...(context.locationIds[0]?{locationId:context.locationIds[0]}:{}),...(kind==='TASK_BATCH'?{assigneeIds:context.assigneeIds}:{})})}>{t('internalDraftManual')}</Button>}</div>
  </form>
  <div className="internal-draft-requests" aria-live="polite"><h3>{t('internalDraftRequests')}</h3>{requests.length===0?<Empty title={t('internalDraftEmpty')}/>:requests.slice(0,50).map(request=><article key={request.id} data-testid="internal-assistant-request-row" data-request-id={request.id} data-request-status={request.data.status}><div><b>{t('internalDraftKind_'+request.data.kind)}</b><small>{date(request.createdAt)} · {request.data.siteIds?.map((id:string)=>lookup(id,'site')).join(' / ')}</small></div><Badge tone={request.data.status==='FAILED'?'red':['READY','CONFIRMED'].includes(request.data.status)?'green':'amber'}>{t('internalDraftStatus_'+request.data.status)}</Badge>{request.data.error&&<div data-testid="internal-assistant-failure" className="internal-draft-failure"><p>{t(request.data.error==='PROVIDER_DISABLED'?'internalDraftProviderDisabled':request.data.providerOutcome==='UNKNOWN'?'internalDraftProviderUnknown':'internalDraftFailed')}</p><code>{request.data.error}</code></div>}{request.data.draftId&&['READY','NEEDS_CLARIFICATION','CONFIRMED'].includes(request.data.status)&&<Button variant="secondary" disabled={busy||Boolean(unknownIntent)||confirmationUnknown||!navigator.onLine} data-testid="internal-assistant-preview" onClick={()=>void loadPreview(request)}>{t('internalDraftPreview')}</Button>}</article>)}</div>
  {preview&&<div className="internal-draft-preview" data-testid="internal-assistant-preview-result"><h3>{t('internalDraftReviewTitle')}</h3><p>{t('internalDraftBoundary')}</p><Badge>{t('internalDraftStatus_'+preview.status)}</Badge>{preview.needsClarification?<div className="notice warning"><b>{t('internalDraftClarification')}</b><p>{preview.clarification||preview.preview.clarification}</p></div>:preview.kind==='TASK_BATCH'?<div className="internal-draft-task-previews">{Array.isArray(preview.preview.tasks)&&preview.preview.tasks.map((task:any,index:number)=><article key={index}><h4>{task.title}</h4><p className="internal-draft-path">{task.fullPath?.join(' / ')}</p><dl><div><dt>{t('internalDraftSites')}</dt><dd>{lookup(task.siteId,'site')}</dd></div><div><dt>{t('internalDraftAssignees')}</dt><dd>{task.executors?.map((row:any)=>row.label).join(', ')||t('internalDraftUnassigned')}</dd></div><div><dt>{t('internalDraftQuantity')}</dt><dd>{new Intl.NumberFormat(locales[language],{maximumFractionDigits:3}).format(task.plannedQuantityMilli/1000)} {t('internalDraftUnit_'+task.unit)}</dd></div></dl><p>{task.description}</p>{task.checklist?.length>0&&<ul>{task.checklist.map((item:any)=><li key={item.id}>{item.label}{item.required?' *':''}</li>)}</ul>}{task.acceptanceCriteria?.length>0&&<><b>{t('internalDraftAcceptance')}</b><ul>{task.acceptanceCriteria.map((text:string,i:number)=><li key={i}>{text}</li>)}</ul></>}<blockquote><small>{t('internalDraftSourceQuote')}</small><p>{task.sourceQuote}</p></blockquote></article>)}</div>:<div className="internal-draft-document-preview"><dl><div><dt>{t('internalDraftSites')}</dt><dd>{lookup(previewInput.siteId,'site')}</dd></div>{preview.kind==='REPORT'?<><div><dt>{t('internalDraftOrders')}</dt><dd>{lookup(previewInput.orderId,'order')}</dd></div><div><dt>{t('internalDraftPeriod')}</dt><dd>{date(previewInput.periodStart)} – {date(previewInput.periodEnd)}</dd></div><div><dt>{t('internalDraftTasks')}</dt><dd>{previewInput.taskIds?.map((id:string)=>lookup(id,'task')).join(', ')}</dd></div><div><dt>{t('internalDraftDocument')}</dt><dd>{previewInput.documentType}</dd></div></>:<><div><dt>{t('internalDraftMaterials')}</dt><dd>{lookup(previewInput.materialId,'material')}</dd></div><div><dt>{t('internalDraftQuantity')}</dt><dd>{previewInput.quantity} {previewInput.unit}</dd></div><div><dt>{t('internalDraftDue')}</dt><dd>{date(previewInput.dueAt)}</dd></div><div><dt>{t('internalDraftUrgency')}</dt><dd>{t('internalDraftUrgency_'+previewInput.urgency)}</dd></div>{previewInput.taskId&&<div><dt>{t('internalDraftTasks')}</dt><dd>{lookup(previewInput.taskId,'task')}</dd></div>}</>}</dl><p>{previewInput.descriptionDe||previewInput.reason}</p><p>{t('internalDraftAfterConfirmation')}</p></div>}
   {preview.requiresUserConfirmation&&!preview.needsClarification&&<><label className="internal-draft-confirm-check"><input data-testid="internal-assistant-confirm-check" type="checkbox" checked={reviewed} disabled={busy||confirmationUnknown} onChange={e=>setReviewed(e.target.checked)}/><span>{t('internalDraftConfirmCheck')}</span></label>{confirmationUnknown&&<p role="status" className="notice warning">{t('internalDraftConfirmUnknown')}</p>}<Button data-testid="internal-assistant-confirm" disabled={!reviewed||busy||(!confirmationUnknown&&sourceChanged)||!navigator.onLine} onClick={()=>void confirm()}>{confirmationUnknown?t('queueCheckReceipt'):t('internalDraftConfirm')}</Button></>}
   {preview.status==='CONFIRMED'&&<p>{t('internalDraftConfirmed')}</p>}
  </div>}
  {receipt&&<div role="status" className="notice success" data-testid="internal-assistant-receipt"><Check size={20}/><div><b>{t('internalDraftConfirmed')}</b><p>{t('internalDraftAfterConfirmation')}</p><span>{receipt.entityIds.length} {t('record')}</span></div></div>}
 </section>;
}
