import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {Badge,Button,Empty,Modal} from '../../../packages/ui/index';
import {ArrowRight,MessageSquare,RefreshCw,ShieldCheck} from './icons';
import {ApiError,command} from './api';
import {errorText,type Translate} from './CommandForm';
import type {Language} from '../../../packages/i18n/index';
type HandoffReference={channel_id:string;version:number;requested_at:string;state:'HANDOFF_PENDING'};
export default function OperatorInbox({t,language,enabled,onClaimed,children}:{t:Translate;language:Language;enabled:boolean;onClaimed:(id:string)=>Promise<void>|void;children:ReactNode}){
 const [items,setItems]=useState<HandoffReference[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[selected,setSelected]=useState<HandoffReference>();const sequence=useRef(0),key=useRef(crypto.randomUUID());const selectionCurrent=Boolean(selected&&items.some(item=>item.channel_id===selected.channel_id&&item.version===selected.version));
 const read=useCallback(async()=>{if(!enabled)return;const current=++sequence.current;setLoading(true);try{const result:any=await command('handoff.inbox',{});if(current!==sequence.current)return;setItems(Array.isArray(result.items)?result.items:[])}catch(error){if(current===sequence.current){setItems([]);setError(error)}}finally{if(current===sequence.current)setLoading(false)}},[enabled]);
 useEffect(()=>{if(!enabled){sequence.current++;setItems([]);setSelected(undefined);setError(undefined);setLoading(false);return;}void read();const timer=setInterval(()=>{if(navigator.onLine&&document.visibilityState==='visible')void read()},10_000);return()=>{sequence.current++;clearInterval(timer)}},[read,enabled]);
 async function claim(){if(!selected||!selectionCurrent||busy||!navigator.onLine)return;setBusy(true);setError(undefined);try{const saved:any=await command('handoff.take',{channel_id:selected.channel_id},selected.version,key.current);if(saved?.id!==selected.channel_id||saved.kind!=='channel'||saved.data?.handoff?.state!=='HUMAN_ACTIVE')throw new ApiError('REQUEST_FAILED',502);setSelected(undefined);await onClaimed(saved.id);await read()}catch(error){setError(error);void read()}finally{setBusy(false)}}
 return <div className="operator-inbox">{enabled&&<section className="content-panel operator-pending"><header className="panel-heading"><div><MessageSquare size={18}/><h2>{t('handoffPendingRequests')}</h2><Badge tone="amber">{items.length}</Badge></div><button className="icon-button" aria-label={t('refresh')} disabled={loading} onClick={()=>{setError(undefined);void read()}}><RefreshCw size={17}/></button></header><p className="operator-boundary"><ShieldCheck size={16}/>{t('handoffInboxBoundary')}</p>{Boolean(error)&&!selected&&<div className="notice danger" role="alert">{errorText(error,t)}{error instanceof ApiError&&<small>{error.code}</small>}</div>}{loading&&!items.length?<p className="operator-loading" role="status">{t('loading')}</p>:items.length?<ul>{items.map(item=><li key={item.channel_id}><div><code>{item.channel_id}</code><small>{new Intl.DateTimeFormat(language==='UK'?'uk-UA':language.toLowerCase(),{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Berlin'}).format(new Date(item.requested_at))} · {t('version')} {item.version}</small></div><Button variant="secondary" disabled={busy||!navigator.onLine} onClick={()=>{key.current=crypto.randomUUID();setError(undefined);setSelected({...item})}}>{t('handoffClaim')}<ArrowRight size={14}/></Button></li>)}</ul>:<Empty title={t('handoffNoPending')}/>}</section>}{children}{selected&&<Modal title={t('handoffClaim')} closeLabel={t('cancel')} onClose={()=>{if(!busy)setSelected(undefined)}}><div className="operator-claim"><p>{t('handoffClaimReview')}</p><code>{selected.channel_id}</code><p><Badge>{t('version')} {selected.version}</Badge></p>{Boolean(error)&&<div className="notice danger" role="alert">{errorText(error,t)}{error instanceof ApiError&&<small>{error.code}</small>}</div>}{!selectionCurrent&&<div className="notice warning" role="status">{t('conflict')}</div>}<footer className="form-footer"><Button variant="secondary" disabled={busy} onClick={()=>setSelected(undefined)}>{t('cancel')}</Button><Button disabled={busy||!navigator.onLine||!selectionCurrent} onClick={claim}>{busy?t('loading'):t('handoffClaim')}</Button></footer></div></Modal>}</div>;
}
