import {createHash} from 'node:crypto';
import {z} from 'zod';
import {assert,type Actor,type CommandContext,type CommandRegistry,type Data,type Entity,type Transaction,id,timestamp} from './core.ts';
import {ROLE_PERMISSIONS} from './permissions.ts';

export const PRIVACY_PROJECTION_VERSION='knaba-dsar-v1';
const DAY=86400000,MAX_DELEGATION_DAYS=30,MAX_HOLD_DAYS=365;
const reason=z.string().trim().min(3).max(2000),evidence=z.string().trim().min(8).max(2000);
const uniqueIds=z.array(id).max(100).refine(a=>new Set(a).size===a.length,'Duplicate IDs');
const category=z.enum(['PROFILE','TIME','PAYROLL','MESSAGES','MEDIA']);
const categories=z.array(category).min(1).max(5).refine(a=>new Set(a).size===a.length,'Duplicate categories');
const retentionCategory=z.enum(['PROFILE','TIME','PAYROLL','GPS','CHAT','MEDIA','AUDIT']);
const retentionCategories=z.array(retentionCategory).min(1).max(7).refine(a=>new Set(a).size===a.length,'Duplicate categories');
const canonical=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).filter(k=>v[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
const sha=(v:any)=>createHash('sha256').update(canonical(v)).digest('hex');
const definition=(permission:string,schema:z.ZodTypeAny,handler:(c:CommandContext,i:any)=>Promise<any>,highRisk=false)=>({permission,schema,handler,highRisk});
async function checked(tx:Transaction,companyId:string,kind:string,entityId:string){const item=await tx.get(kind,entityId);assert(item.companyId===companyId,'NOT_FOUND_SAFE');return item;}
function baseActor(user:Entity):Actor {return {userId:user.id,companyId:user.companyId,roles:user.data.roles||[],permissions:[...new Set([...(user.data.roles||[]).flatMap((r:string)=>ROLE_PERMISSIONS[r]||[]),...(user.data.permissions||[])])],siteIds:user.data.siteIds||[],warehouseIds:user.data.warehouseIds||[],customerIds:[]};}
const scopeHeld=(a:Actor,siteIds:string[],warehouseIds:string[])=>a.permissions.includes('scope.company')||(siteIds.every(s=>a.siteIds.includes(s))&&warehouseIds.every(s=>a.warehouseIds.includes(s)));
const forbidden=(p:string)=>/^(finance|payroll|payout|rate|location|gps|privacy|audit|scope|bot|assistant|automation|integration|notifications|customer|price|service)\./.test(p)||['role.manage','identity.manage','legal.manage','company.manage','inventory.manage','site.create','chat.manage'].includes(p)||p.endsWith('.export');
const known=new Set(Object.values(ROLE_PERMISSIONS).flat());
function validateRights(a:Actor,permissions:string[],siteIds:string[],warehouseIds:string[]){assert(permissions.length>0&&permissions.every(p=>known.has(p)&&!forbidden(p)&&a.permissions.includes(p)),'ACCESS_DENIED',{reason:'UNHELD_OR_RESTRICTED_DELEGATION_PERMISSION'});assert(scopeHeld(a,siteIds,warehouseIds),'ACCESS_DENIED',{reason:'DELEGATION_SCOPE_EXCEEDS_GRANTOR'});assert(siteIds.length+warehouseIds.length>0,'VALIDATION_ERROR',{reason:'NAMED_SCOPE_REQUIRED'});}
function ownerReview(c:CommandContext){assert(c.actor.roles.includes('OWNER')&&c.actor.mfaVerified===true,'NEEDS_REAUTH');}
const grantSnapshot=(d:Data)=>({granteeId:d.granteeId,grantorId:d.grantorId,permissions:d.permissions,siteIds:d.siteIds,warehouseIds:d.warehouseIds,startsAt:d.startsAt,expiresAt:d.expiresAt,reason:d.reason});
export interface EffectiveGrant {id:string;version:number;permissions:string[];siteIds:string[];warehouseIds:string[];startsAt:string;expiresAt:string;}
export interface EffectiveDelegations {grants:EffectiveGrant[];grantIds:string[];fingerprint:string;}
/** No transitive grants and no global site/permission cross product. Called fresh in each transaction. */
export async function effectiveDelegations(tx:Transaction,actor:Actor,now:string):Promise<EffectiveDelegations>{
 const recipient=await checked(tx,actor.companyId,'user',actor.userId),grants:EffectiveGrant[]=[];
 if(recipient.data.active===true&&!recipient.data.roles?.some((r:string)=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST','SERVICE_ACCOUNT'].includes(r)))for(const d of await tx.list('delegation')){
  const start=Date.parse(d.data.startsAt),end=Date.parse(d.data.expiresAt);if(d.companyId!==actor.companyId||d.data.granteeId!==actor.userId||d.data.state!=='APPROVED'||!Number.isFinite(start)||!Number.isFinite(end)||start>=end||end-start>MAX_DELEGATION_DAYS*DAY||start>Date.parse(now)||end<=Date.parse(now)||d.data.previewHash!==sha(grantSnapshot(d.data)))continue;
  let grantor:Entity;try{grantor=await checked(tx,actor.companyId,'user',d.data.grantorId);}catch{continue;}if(grantor.data.active!==true)continue;
  const held=baseActor(grantor);if(!held.permissions.includes('role.manage')||!scopeHeld(held,d.data.siteIds,d.data.warehouseIds))continue;
  const permissions=d.data.permissions.filter((p:string)=>known.has(p)&&!forbidden(p)&&held.permissions.includes(p));
  if(permissions.length)grants.push({id:d.id,version:d.version,permissions,siteIds:d.data.siteIds,warehouseIds:d.data.warehouseIds,startsAt:d.data.startsAt,expiresAt:d.data.expiresAt});
 }
 grants.sort((a,b)=>a.id.localeCompare(b.id));return {grants,grantIds:grants.map(g=>g.id),fingerprint:sha(grants)};
}
export function delegationScope(actor:Actor,effective:EffectiveDelegations,permission:string):Actor {const matching=effective.grants.filter(g=>g.permissions.includes(permission)),baseHolds=actor.permissions.includes(permission);return {...actor,permissions:[...new Set([...actor.permissions.filter(p=>baseHolds||p!=='scope.company'),...(matching.length?[permission]:[])])],siteIds:[...new Set([...(baseHolds?actor.siteIds:[]),...matching.flatMap(g=>g.siteIds)])],warehouseIds:[...new Set([...(baseHolds?actor.warehouseIds:[]),...matching.flatMap(g=>g.warehouseIds)])]};}

async function privacyLegal(tx:Transaction,companyId:string,legalApprovalId:string,now:string){const a=await checked(tx,companyId,'legal_approval',legalApprovalId);assert(a.data.subject==='PRIVACY'&&a.data.status==='APPROVED'&&a.data.active===true&&a.data.evidenceReference?.length>=8&&Date.parse(a.data.approvedAt)<=Date.parse(now)&&Date.parse(a.data.expiresAt)>Date.parse(now),'NEEDS_APPROVAL',{reason:'RECORDED_PRIVACY_REVIEW_REQUIRED'});return a;}
const toRetention=(c:string)=>c==='MESSAGES'?'CHAT':c;
export async function activeLegalHolds(tx:Transaction,subjectUserId:string,categories:string[],now:string){return (await tx.list('legal_hold')).filter(h=>h.data.subjectUserId===subjectUserId&&h.data.state==='ACTIVE'&&Date.parse(h.data.expiresAt)>Date.parse(now)&&h.data.categories.some((c:string)=>categories.map(toRetention).includes(c)));}
const short=z.string().max(2000).nullable().optional(),integer=z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).nullable().optional();
export const privacyProjectionSchemas={
 profile:z.object({userId:id,name:short,email:short,employeeCode:short,businessCode:short,language:short,active:z.boolean().optional()}),
 time:z.object({id,kind:z.enum(['shift','timesheet']),state:short,startedAt:short,endedAt:short,periodStart:short,periodEnd:short,totalSeconds:integer,payableSeconds:integer,totalMinutes:integer,remainderSeconds:integer}),
 payroll:z.object({id,kind:z.enum(['payroll_calculation','payout','payout_receipt']),periodStart:short,periodEnd:short,state:short,amountCents:integer,payableCents:integer,receivedCents:integer,method:short,decision:short,statement:short,transferredAt:short,currency:short}),
 message:z.object({id,text:z.string().max(20000),language:short,sentAt:short}),
 media:z.object({id,stage:short,mimeType:short,byteSize:integer,caption:short,uploadedAt:short,visibility:short})
};
async function ownRequest(tx:Transaction,actor:Actor,requestId:string){const r=await checked(tx,actor.companyId,'privacy_request',requestId);assert(r.data.subjectUserId===actor.userId,'ACCESS_DENIED');return r;}
export async function buildPrivacyExport(tx:Transaction,actor:Actor,requestId:string,now:string){
 const request=await ownRequest(tx,actor,requestId);assert(request.data.type==='ACCESS'&&request.data.state==='APPROVED_EXPORT','INVALID_STATE');const legal=await privacyLegal(tx,actor.companyId,request.data.legalApprovalId,now);assert(legal.data.scope?.projectionVersion===PRIVACY_PROJECTION_VERSION&&request.data.categories.every((c:string)=>legal.data.scope.exportCategories?.includes(c)),'NEEDS_APPROVAL');
 const subject=await checked(tx,actor.companyId,'user',actor.userId),snapshot:Data={projectionVersion:PRIVACY_PROJECTION_VERSION,subjectUserId:actor.userId,createdAt:now,categories:request.data.categories,scope:'MINIMIZED_SELF_DATA_EXPORT',fullLegalDsarFulfillment:false,omissions:['credentials','other_person_data','raw_routes','bank_details','other_authors_messages','inaccessible_channels','blob_keys']};
 if(request.data.categories.includes('PROFILE'))snapshot.profile=privacyProjectionSchemas.profile.parse({...subject.data,userId:subject.id});
 if(request.data.categories.includes('TIME')){snapshot.time=[];for(const kind of ['shift','timesheet'])for(const row of await tx.list(kind))if(row.companyId===actor.companyId&&row.data.employeeId===actor.userId)snapshot.time.push(privacyProjectionSchemas.time.parse({...row.data,startedAt:row.data.startAt!==undefined?row.data.startAt:row.data.startedAt,endedAt:row.data.endAt!==undefined?row.data.endAt:row.data.endedAt,id:row.id,kind}));}
 if(request.data.categories.includes('PAYROLL')){snapshot.payroll=[];for(const kind of ['payroll_calculation','payout','payout_receipt'])for(const row of await tx.list(kind))if(row.companyId===actor.companyId&&row.data.employeeId===actor.userId)snapshot.payroll.push(privacyProjectionSchemas.payroll.parse({...row.data,id:row.id,kind}));}
 if(request.data.categories.includes('MESSAGES')){const channels=new Map<string,string|undefined>(),memberships=await tx.list('customer_membership');for(const ch of await tx.list('channel')){const member=ch.data.members?.find((m:Data)=>m.user_id===actor.userId&&!m.left_at&&!m.revoked_at&&!m.removed_at&&m.active!==false&&(!m.expires_at||Date.parse(m.expires_at)>Date.parse(now)));if(!member)continue;let siteId=ch.data.site_id??ch.data.siteId;if(!siteId&&(ch.data.task_id??ch.data.taskId)){try{siteId=(await checked(tx,actor.companyId,'task',ch.data.task_id??ch.data.taskId)).data.siteId;}catch{continue;}}if(ch.data.type==='SITE_CLIENT'){if(!siteId)continue;let site:Entity;try{site=await checked(tx,actor.companyId,'site',siteId);}catch{continue;}if(!memberships.some(m=>m.data.active===true&&!m.data.revokedAt&&(!m.data.expiresAt||Date.parse(m.data.expiresAt)>Date.parse(now))&&(m.data.userId??m.data.user_id)===actor.userId&&m.data.customerId===site.data.customerId&&m.data.permissions?.includes('VIEW')&&(!(m.data.siteIds||[]).length||m.data.siteIds.includes(siteId))))continue;}else if(siteId&&!actor.permissions.includes('scope.company')&&!actor.siteIds.includes(siteId))continue;const historyFrom=member.history_from??member.joined_at;if(historyFrom&&(!Number.isFinite(Date.parse(historyFrom))||Date.parse(historyFrom)>Date.parse(now)))continue;channels.set(ch.id,historyFrom);}snapshot.messages=(await tx.list('message')).filter(m=>typeof m.data.text==='string'&&!m.data.deleted_at&&!m.data.deletedAt&&m.companyId===actor.companyId&&(m.data.author_id??m.data.authorId)===actor.userId&&channels.has(m.data.channel_id??m.data.channelId)&&(!channels.get(m.data.channel_id??m.data.channelId)||Date.parse(m.createdAt)>=Date.parse(channels.get(m.data.channel_id??m.data.channelId)!))).map(m=>privacyProjectionSchemas.message.parse({id:m.id,text:m.data.text,language:m.data.language,sentAt:m.createdAt}));}
 if(request.data.categories.includes('MEDIA'))snapshot.media=(await tx.list('media_asset')).filter(m=>m.companyId===actor.companyId&&(m.data.employeeId?m.data.employeeId===actor.userId:m.data.uploadedBy===actor.userId)).map(m=>privacyProjectionSchemas.media.parse({...m.data,id:m.id}));
 const bytes=Buffer.from(canonical(snapshot),'utf8');return {snapshot,bytes,sha256:createHash('sha256').update(bytes).digest('hex'),fileName:`KNABA-DE-own-data-${request.id}.json`,mimeType:'application/json; charset=utf-8'};
}
export async function privacyExportBytes(tx:Transaction,actor:Actor,exportId:string){const item=await checked(tx,actor.companyId,'privacy_export',exportId);assert(item.data.subjectUserId===actor.userId,'ACCESS_DENIED');assert(item.data.immutable===true,'INVALID_STATE');const bytes=Buffer.from(canonical(item.data.snapshot),'utf8');assert(createHash('sha256').update(bytes).digest('hex')===item.data.sha256,'INVALID_STATE',{reason:'PRIVACY_EXPORT_CHECKSUM_MISMATCH'});return {bytes,sha256:item.data.sha256,fileName:item.data.fileName,mimeType:'application/json; charset=utf-8'};}

export const governanceCommands:CommandRegistry={
 'delegation.create':definition('role.manage',z.object({granteeId:id,permissions:z.array(z.string().regex(/^[a-z_]+(?:\.[a-z_]+)+$/)).min(1).max(100).refine(a=>new Set(a).size===a.length),siteIds:uniqueIds.default([]),warehouseIds:uniqueIds.default([]),startsAt:timestamp.optional(),expiresAt:timestamp,reason}).strict(),async(c,i)=>{
  assert(i.granteeId!==c.actor.userId,'ACCESS_DENIED',{reason:'SELF_DELEGATION_FORBIDDEN'});const grantor=baseActor(await checked(c.tx,c.actor.companyId,'user',c.actor.userId));assert(grantor.permissions.includes('role.manage'),'ACCESS_DENIED');const grantee=await checked(c.tx,c.actor.companyId,'user',i.granteeId);assert(grantee.data.active===true&&!grantee.data.roles?.some((r:string)=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST','SERVICE_ACCOUNT'].includes(r)),'ACCESS_DENIED');validateRights(grantor,i.permissions,i.siteIds,i.warehouseIds);
  const startsAt=i.startsAt||c.now;assert(Date.parse(startsAt)>=Date.parse(c.now)&&Date.parse(i.expiresAt)>Date.parse(startsAt)&&Date.parse(i.expiresAt)<=Date.parse(c.now)+MAX_DELEGATION_DAYS*DAY,'VALIDATION_ERROR',{reason:'DELEGATION_MAX_30_DAYS'});
  for(const siteId of i.siteIds)await checked(c.tx,c.actor.companyId,'site',siteId);for(const warehouseId of i.warehouseIds){const warehouse=await checked(c.tx,c.actor.companyId,'stock_location',warehouseId);assert(['WAREHOUSE','VEHICLE'].includes(warehouse.data.type),'VALIDATION_ERROR');}
  const data={...i,startsAt,grantorId:c.actor.userId,state:'DRAFT',createdBy:c.actor.userId,createdAt:c.now};const row=await c.tx.add('delegation',{...data,previewHash:sha(grantSnapshot(data))});await c.tx.event('delegation.drafted',{delegationId:row.id,granteeId:i.granteeId});return row;
 },true),
 'delegation.approve':definition('role.manage',z.object({delegationId:id,confirmedHash:z.string().regex(/^[a-f0-9]{64}$/),reason}).strict(),async(c,i)=>{ownerReview(c);const d=await checked(c.tx,c.actor.companyId,'delegation',i.delegationId);assert(d.data.state==='DRAFT','INVALID_STATE');assert(c.actor.userId!==d.data.createdBy&&c.actor.userId!==d.data.granteeId,'SELF_APPROVAL_DENIED');assert(i.confirmedHash===d.data.previewHash&&i.confirmedHash===sha(grantSnapshot(d.data)),'VERSION_CONFLICT');assert(Date.parse(d.data.expiresAt)>Date.parse(c.now),'INVALID_STATE');const grantor=await checked(c.tx,c.actor.companyId,'user',d.data.grantorId),grantee=await checked(c.tx,c.actor.companyId,'user',d.data.granteeId);assert(grantor.data.active===true&&grantee.data.active===true,'ACCESS_DENIED');assert(baseActor(grantor).permissions.includes('role.manage'),'ACCESS_DENIED');validateRights(baseActor(grantor),d.data.permissions,d.data.siteIds,d.data.warehouseIds);const row=await c.tx.save(d,{...d.data,state:'APPROVED',approvedBy:c.actor.userId,approvedAt:c.now,approvalReason:i.reason},c.expectedVersion??d.version);await c.tx.event('delegation.approved',{delegationId:d.id,granteeId:d.data.granteeId,expiresAt:d.data.expiresAt});return row;},true),
 'delegation.revoke':definition('role.manage',z.object({delegationId:id,reason}).strict(),async(c,i)=>{const d=await checked(c.tx,c.actor.companyId,'delegation',i.delegationId);assert(c.actor.userId===d.data.grantorId||c.actor.roles.includes('OWNER'),'ACCESS_DENIED');assert(['DRAFT','APPROVED'].includes(d.data.state),'INVALID_STATE');const row=await c.tx.save(d,{...d.data,state:'REVOKED',revokedBy:c.actor.userId,revokedAt:c.now,revocationReason:i.reason},c.expectedVersion??d.version);await c.tx.event('delegation.revoked',{delegationId:d.id,granteeId:d.data.granteeId});return row;},true),
 'privacy.request':definition('identity.self',z.object({type:z.enum(['ACCESS','ERASURE']),subjectUserId:id.optional(),categories,reason}).strict(),async(c,i)=>{assert(!i.subjectUserId||i.subjectUserId===c.actor.userId,'ACCESS_DENIED');await checked(c.tx,c.actor.companyId,'user',c.actor.userId);const request=await c.tx.add('privacy_request',{...i,subjectUserId:c.actor.userId,state:'REQUESTED',requestedBy:c.actor.userId,requestedAt:c.now,sourceDataDeleted:false});await c.tx.event('privacy.requested',{requestId:request.id,subjectUserId:c.actor.userId,type:i.type});return request;}),
 'privacy.review':definition('privacy.review',z.object({requestId:id,decision:z.enum(['APPROVE_EXPORT','REFER_ERASURE','RETAIN','REJECT']),legalApprovalId:id,evidenceReference:evidence,reason}).strict(),async(c,i)=>{const r=await checked(c.tx,c.actor.companyId,'privacy_request',i.requestId);assert(r.data.subjectUserId!==c.actor.userId,'SELF_APPROVAL_DENIED');assert(r.data.state==='REQUESTED'||r.data.state==='ON_LEGAL_HOLD','INVALID_STATE');const legal=await privacyLegal(c.tx,c.actor.companyId,i.legalApprovalId,c.now);assert(i.decision!=='APPROVE_EXPORT'||r.data.type==='ACCESS','INVALID_STATE');assert(i.decision!=='REFER_ERASURE'||r.data.type==='ERASURE','INVALID_STATE');if(i.decision==='APPROVE_EXPORT')assert(legal.data.scope?.projectionVersion===PRIVACY_PROJECTION_VERSION&&r.data.categories.every((cat:string)=>legal.data.scope.exportCategories?.includes(cat)),'NEEDS_APPROVAL');const holds=await activeLegalHolds(c.tx,r.data.subjectUserId,r.data.categories,c.now);const state=i.decision==='APPROVE_EXPORT'?'APPROVED_EXPORT':i.decision==='REFER_ERASURE'?(holds.length?'ON_LEGAL_HOLD':'AWAITING_ERASURE_EXECUTION'):i.decision==='RETAIN'?'RETAINED_LEGAL_BASIS':'REJECTED';const row=await c.tx.save(r,{...r.data,state,legalApprovalId:legal.id,legalApprovalVersion:legal.version,reviewedBy:c.actor.userId,reviewedAt:c.now,reviewReason:i.reason,evidenceReference:i.evidenceReference,holdIds:holds.map(h=>h.id),sourceDataDeleted:false},c.expectedVersion??r.version);await c.tx.event('privacy.reviewed',{requestId:r.id,state,subjectUserId:r.data.subjectUserId});return row;},true),
 'privacy.export':definition('identity.self',z.object({requestId:id}).strict(),async(c,i)=>{const built=await buildPrivacyExport(c.tx,c.actor,i.requestId,c.now);assert(!(await c.tx.list('privacy_export')).some(e=>e.data.requestId===i.requestId),'DUPLICATE_EFFECT');const row=await c.tx.add('privacy_export',{requestId:i.requestId,subjectUserId:c.actor.userId,snapshot:built.snapshot,sha256:built.sha256,byteSize:built.bytes.length,fileName:built.fileName,projectionVersion:PRIVACY_PROJECTION_VERSION,createdAt:c.now,immutable:true});await c.tx.event('privacy.export_prepared',{exportId:row.id,subjectUserId:c.actor.userId,sha256:built.sha256});return {exportId:row.id,fileName:built.fileName,sha256:built.sha256,byteSize:built.bytes.length,status:'PRIVATE_JSON_ARTIFACT_READY',securedDownloadRequired:true};}),
 'legal_hold.create':definition('privacy.review',z.object({subjectUserId:id,categories:retentionCategories,expiresAt:timestamp,legalApprovalId:id,evidenceReference:evidence,reason}).strict(),async(c,i)=>{ownerReview(c);await checked(c.tx,c.actor.companyId,'user',i.subjectUserId);await privacyLegal(c.tx,c.actor.companyId,i.legalApprovalId,c.now);assert(Date.parse(i.expiresAt)>Date.parse(c.now)&&Date.parse(i.expiresAt)<=Date.parse(c.now)+MAX_HOLD_DAYS*DAY,'VALIDATION_ERROR',{reason:'SPECIFIC_HOLD_MAX_365_DAYS'});const row=await c.tx.add('legal_hold',{...i,state:'ACTIVE',createdBy:c.actor.userId,createdAt:c.now,automaticDeletionOnExpiry:false});await c.tx.event('privacy.hold_created',{holdId:row.id,subjectUserId:i.subjectUserId,categories:i.categories,expiresAt:i.expiresAt});return row;},true),
 'legal_hold.release':definition('privacy.review',z.object({holdId:id,evidenceReference:evidence,reason}).strict(),async(c,i)=>{ownerReview(c);const hold=await checked(c.tx,c.actor.companyId,'legal_hold',i.holdId);assert(hold.data.state==='ACTIVE','INVALID_STATE');assert(hold.data.createdBy!==c.actor.userId,'SELF_APPROVAL_DENIED');const row=await c.tx.save(hold,{...hold.data,state:'RELEASED',releasedAt:c.now,releasedBy:c.actor.userId,releaseReason:i.reason,releaseEvidenceReference:i.evidenceReference},c.expectedVersion??hold.version);await c.tx.event('privacy.hold_released',{holdId:row.id});return row;},true),
 'retention.create':definition('privacy.manage',z.object({category:retentionCategory,retentionDays:z.number().int().min(0).max(36500),legalApprovalId:id,reason}).strict(),async(c,i)=>{const legal=await privacyLegal(c.tx,c.actor.companyId,i.legalApprovalId,c.now),bounds=z.object({minDays:z.number().int().min(0).max(36500),maxDays:z.number().int().min(0).max(36500)}).parse(legal.data.scope?.retentionProfiles?.[i.category]);assert(bounds.minDays<=bounds.maxDays&&i.retentionDays>=bounds.minDays&&i.retentionDays<=bounds.maxDays,'VALIDATION_ERROR',{reason:'APPROVED_RETENTION_BOUNDS_REQUIRED'});const data={...i,...bounds,legalApprovalVersion:legal.version,state:'DRAFT',createdBy:c.actor.userId,createdAt:c.now,automaticDeletion:false};const row=await c.tx.add('retention_policy',{...data,previewHash:sha(data)});await c.tx.event('retention.drafted',{policyId:row.id,category:i.category});return row;},true),
 'retention.approve':definition('privacy.manage',z.object({policyId:id,confirmedHash:z.string().regex(/^[a-f0-9]{64}$/),reason}).strict(),async(c,i)=>{ownerReview(c);const p=await checked(c.tx,c.actor.companyId,'retention_policy',i.policyId);assert(p.data.state==='DRAFT','INVALID_STATE');assert(p.data.createdBy!==c.actor.userId,'SELF_APPROVAL_DENIED');const {previewHash,...draft}=p.data;assert(i.confirmedHash===previewHash&&sha(draft)===previewHash,'VERSION_CONFLICT');const legal=await privacyLegal(c.tx,c.actor.companyId,p.data.legalApprovalId,c.now);assert(legal.version===p.data.legalApprovalVersion&&legal.data.scope?.retentionProfiles?.[p.data.category]?.minDays===p.data.minDays&&legal.data.scope?.retentionProfiles?.[p.data.category]?.maxDays===p.data.maxDays,'NEEDS_APPROVAL');const row=await c.tx.save(p,{...p.data,state:'APPROVED',approvedBy:c.actor.userId,approvedAt:c.now,approvalReason:i.reason},c.expectedVersion??p.version);await c.tx.event('retention.approved',{policyId:row.id,category:p.data.category,retentionDays:p.data.retentionDays});return row;},true),
 'privacy.erasure_evidence':definition('privacy.review',z.object({requestId:id,categories,evidenceReference:evidence,evidenceSha256:z.string().regex(/^[a-f0-9]{64}$/),executionReference:evidence,completedAt:timestamp,derivedDataEvidence:z.array(z.object({kind:z.enum(['TRANSLATIONS','COPIES','SEARCH_INDEXES','BACKUPS','PROCESSOR_COPIES']),reference:evidence,result:z.enum(['PURGED','RETAINED_LEGAL_BASIS','PENDING'])}).strict()).max(5).refine(a=>new Set(a.map(x=>x.kind)).size===a.length),reason}).strict(),async(c,i)=>{ownerReview(c);const r=await checked(c.tx,c.actor.companyId,'privacy_request',i.requestId);assert(r.data.subjectUserId!==c.actor.userId,'SELF_APPROVAL_DENIED');assert(r.data.type==='ERASURE'&&r.data.state==='AWAITING_ERASURE_EXECUTION','INVALID_STATE');assert(i.categories.every((cat:string)=>r.data.categories.includes(cat))&&Date.parse(i.completedAt)<=Date.parse(c.now),'VALIDATION_ERROR');await privacyLegal(c.tx,c.actor.companyId,r.data.legalApprovalId,c.now);assert(!(await activeLegalHolds(c.tx,r.data.subjectUserId,i.categories,c.now)).length,'LEGAL_HOLD_BLOCKS_ERASURE');for(const cat of i.categories)assert((await c.tx.list('retention_policy')).some(p=>p.data.state==='APPROVED'&&p.data.category===toRetention(cat)),'NEEDS_APPROVAL',{reason:'CATEGORY_RETENTION_POLICY_REQUIRED'});const row=await c.tx.add('privacy_erasure_evidence',{...i,subjectUserId:r.data.subjectUserId,recordedBy:c.actor.userId,recordedAt:c.now,verificationStatus:'EXTERNAL_REFERENCE_NOT_VERIFIED',systemDataDeleted:false,immutable:true});await c.tx.save(r,{...r.data,state:'EVIDENCE_RECORDED_PENDING_VERIFICATION',evidenceId:row.id,sourceDataDeleted:false},c.expectedVersion??r.version);await c.tx.event('privacy.erasure_evidence_recorded',{requestId:r.id,evidenceId:row.id,actualSystemDeletion:false});return {evidenceId:row.id,status:'EVIDENCE_RECORDED_PENDING_VERIFICATION',actualSystemDeletion:false};},true),
 'privacy.status':definition('identity.self',z.object({requestId:id}).strict(),async(c,i)=>{const r=await ownRequest(c.tx,c.actor,i.requestId);return {requestId:r.id,type:r.data.type,categories:r.data.categories,state:r.data.state,sourceDataDeleted:r.data.sourceDataDeleted===true,liveSourceStatus:r.data.liveSourceStatus??null,externalCopiesStatus:r.data.externalCopiesStatus??'NOT_VERIFIED',requestFulfilled:false,requestedAt:r.data.requestedAt,reviewedAt:r.data.reviewedAt||null};})
};
