import { z } from 'zod';
import { assert,id,timestamp,type CommandContext,type CommandRegistry,type Data } from './core.js';
import { hashPassword,hashToken,opaqueToken,openSecret,sealSecret,sql,validateTotp,verifyPassword,type SqlTransaction } from '../../apps/api/auth.js';

import { ROLE_PERMISSIONS, EXPLICIT_PRIVILEGED_PERMISSIONS } from './permissions.js';
export { ROLE_PERMISSIONS } from './permissions.js';
export const roles=['OWNER','DIRECTOR','OPERATIONS_MANAGER','DISPATCHER','INTERNAL_BAULEITER','TEAM_LEADER','EMPLOYEE','STOREKEEPER','PROCUREMENT','ACCOUNTANT','CLIENT','EXTERNAL_BAULEITER','BOT_ADMIN','QUALITY_CONTROL','AUDITOR','DEVELOPER_SUPPORT','GUEST','SERVICE_ACCOUNT'] as const;
export const DEMO_ROLE_ALIASES:Record<string,string>={FOREMAN:'INTERNAL_BAULEITER',TEAM_LEAD:'TEAM_LEADER',WAREHOUSE:'STOREKEEPER'};
export function permissionsForRoles(userRoles:string[]){return [...new Set(userRoles.flatMap(role=>ROLE_PERMISSIONS[role]??[]))];}
export function permits(actorPermissions:string[],permission:string){return actorPermissions.includes(permission);}
const safeRoles=z.array(z.enum(roles.filter(r=>!['GUEST','SERVICE_ACCOUNT'].includes(r)) as any)).min(1).max(10).refine(r=>new Set(r).size===r.length);
const permission=z.string().regex(/^[a-z_]+(?:\.[a-z_]+)+$/).max(100);
const text=z.string().trim().min(1).max(2000);
const command=(permission:string,schema:z.ZodTypeAny,handler:(ctx:CommandContext,input:any)=>Promise<any>,highRisk=false)=>({permission,schema,handler,highRisk});
async function guardRoles(c:CommandContext,userRoles:string[],permissions:string[]){
 assert(!userRoles.some(role=>['OWNER','DIRECTOR','ACCOUNTANT','BOT_ADMIN','DEVELOPER_SUPPORT'].includes(role))||c.actor.roles.includes('OWNER'),'ACCESS_DENIED');
 const defaults=permissionsForRoles(userRoles);
 for(const p of permissions)assert(defaults.includes(p)||(c.actor.roles.includes('OWNER')&&EXPLICIT_PRIVILEGED_PERMISSIONS.has(p)&&!userRoles.some(r=>['CLIENT','EXTERNAL_BAULEITER'].includes(r))),'ACCESS_DENIED',{reason:'EXPLICIT_PERMISSION_NOT_IN_ROLE'});
 if(!c.actor.roles.includes('OWNER'))for(const p of [...permissions,...defaults.filter(p=>!['identity.self','finance.payout.ack','payroll.self','payout.acknowledge'].includes(p))])assert(permits(c.actor.permissions,p),'ACCESS_DENIED',{reason:'CANNOT_GRANT_UNHELD_PERMISSION'});
}
async function lastOwner(c:CommandContext,userId:string,nextRoles:string[],active=true){const target=await c.tx.get('user',userId);if(target.data.roles.includes('OWNER')&&(!active||!nextRoles.includes('OWNER'))){const count=(await c.tx.list('user')).filter(u=>u.data.active!==false&&u.data.roles.includes('OWNER')).length;assert(count>1,'INVALID_STATE',{reason:'LAST_OWNER_PROTECTED'});}}
export const identityCommands:CommandRegistry={
 'user.invite':command('identity.manage',z.object({email:z.string().email().max(200),name:z.string().min(1).max(200),roles:safeRoles,permissions:z.array(permission).max(200).default([]),siteIds:z.array(id).max(100).default([]),warehouseIds:z.array(id).max(100).default([]),expiresHours:z.number().int().min(1).max(48).default(24)}).strict(),async(c,i)=>{await guardRoles(c,i.roles,i.permissions);assert(!(await c.tx.list('user')).some(u=>u.data.email?.toLowerCase()===i.email.toLowerCase()),'INVALID_STATE',{reason:'IDENTITY_ALREADY_EXISTS'});for(const siteId of i.siteIds){c.requireSite(siteId);await c.tx.get('site',siteId);}for(const warehouseId of i.warehouseIds){assert(c.actor.roles.includes('OWNER')||c.actor.warehouseIds.includes(warehouseId),'ACCESS_DENIED');await c.tx.get('stock_location',warehouseId);}for(const old of await c.tx.list('user_invitation'))if(old.data.email===i.email.toLowerCase()&&old.data.status==='PENDING')await c.tx.save(old,{...old.data,status:'REVOKED',revokedAt:c.now,reason:'INVITATION_REPLACED'},old.version);const token=opaqueToken();const invitation=await c.tx.add('user_invitation',{...i,email:i.email.toLowerCase(),tokenHash:hashToken(token),status:'PENDING',expiresAt:new Date(Date.parse(c.now)+i.expiresHours*3600000).toISOString(),createdBy:c.actor.userId});await c.tx.event('identity.invitation_created',{invitationId:invitation.id,email:i.email,roles:i.roles});return {id:invitation.id,token,expiresAt:invitation.data.expiresAt};},true),
 'user.invitation.revoke':command('identity.manage',z.object({id,reason:text}).strict(),async(c,i)=>{const e=await c.tx.get('user_invitation',i.id);assert(e.data.status==='PENDING','INVALID_STATE');return c.tx.save(e,{...e.data,status:'REVOKED',revokedAt:c.now,reason:i.reason},c.expectedVersion);},true),
 'user.roles':command('identity.manage',z.object({userId:id,roles:safeRoles,permissions:z.array(permission).max(200).default([]),siteIds:z.array(id).max(100),warehouseIds:z.array(id).max(100).default([]),reason:text}).strict(),async(c,i)=>{assert(i.userId!==c.actor.userId,'ACCESS_DENIED',{reason:'SELF_ESCALATION_FORBIDDEN'});await guardRoles(c,i.roles,i.permissions);await lastOwner(c,i.userId,i.roles);for(const siteId of i.siteIds){c.requireSite(siteId);await c.tx.get('site',siteId);}for(const warehouseId of i.warehouseIds){assert(c.actor.roles.includes('OWNER')||c.actor.warehouseIds.includes(warehouseId),'ACCESS_DENIED');await c.tx.get('stock_location',warehouseId);}const user=await c.tx.get('user',i.userId);const result=await c.tx.save(user,{...user.data,roles:i.roles,permissions:i.permissions,siteIds:i.siteIds,warehouseIds:i.warehouseIds,roleChangeReason:i.reason,roleChangedBy:c.actor.userId},c.expectedVersion);for(const assignment of await c.tx.list('role_assignment'))if(assignment.data.userId===user.id&&assignment.data.active)await c.tx.save(assignment,{...assignment.data,active:false,revokedAt:c.now,revokedBy:c.actor.userId,revocationReason:'USER_ROLES_REPLACED'},assignment.version);await sql(c.tx as SqlTransaction,'UPDATE auth_sessions SET revoked_at=now() WHERE user_id=$1 AND company_id=$2',[user.id,c.actor.companyId]);await c.tx.event('identity.roles_changed',{userId:user.id,reason:i.reason});return {userId:user.id,version:result.version,roles:i.roles};},true),
 'user.disable':command('identity.manage',z.object({userId:id,reason:text}).strict(),async(c,i)=>{assert(i.userId!==c.actor.userId,'ACCESS_DENIED',{reason:'SELF_DISABLE_FORBIDDEN'});const user=await c.tx.get('user',i.userId);await lastOwner(c,user.id,user.data.roles,false);const result=await c.tx.save(user,{...user.data,active:false,disabledAt:c.now,disabledBy:c.actor.userId,disableReason:i.reason},c.expectedVersion);await sql(c.tx as SqlTransaction,'UPDATE auth_sessions SET revoked_at=now() WHERE user_id=$1 AND company_id=$2',[user.id,c.actor.companyId]);for(const device of await c.tx.list('device'))if(device.data.employeeId===user.id&&device.data.active)await c.tx.save(device,{...device.data,active:false,revokedAt:c.now,revocationReason:'USER_DISABLED'},device.version);await c.tx.event('identity.user_disabled',{userId:user.id,reason:i.reason});return {userId:user.id,version:result.version,active:false};},true),
 'user.password.rotate':command('identity.self',z.object({currentPassword:z.string().min(1).max(128),newPassword:z.string().min(12).max(128)}).strict(),async(c,i)=>{const row=(await sql(c.tx as SqlTransaction,'SELECT password_hash FROM auth_credentials WHERE user_id=$1 AND company_id=$2',[c.actor.userId,c.actor.companyId])).rows[0];assert(row&&await verifyPassword(i.currentPassword,row.password_hash),'NEEDS_REAUTH');const passwordHash=await hashPassword(i.newPassword);await sql(c.tx as SqlTransaction,'UPDATE auth_credentials SET password_hash=$3 WHERE user_id=$1 AND company_id=$2',[c.actor.userId,c.actor.companyId,passwordHash]);await sql(c.tx as SqlTransaction,'UPDATE auth_sessions SET revoked_at=now() WHERE user_id=$1 AND company_id=$2',[c.actor.userId,c.actor.companyId]);await c.tx.event('identity.password_rotated',{userId:c.actor.userId});return {ok:true,reauthenticationRequired:true};}),
 'user.mfa.configure':command('identity.self',z.object({currentPassword:z.string().min(1).max(128),secret:z.string().regex(/^[A-Z2-7]{16,100}$/),otp:z.string().regex(/^\d{6}$/)}).strict(),async(c,i)=>{const row=(await sql(c.tx as SqlTransaction,'SELECT password_hash FROM auth_credentials WHERE user_id=$1 AND company_id=$2',[c.actor.userId,c.actor.companyId])).rows[0];assert(row&&await verifyPassword(i.currentPassword,row.password_hash),'NEEDS_REAUTH');const counter=validateTotp(i.secret,i.otp,Date.parse(c.now));assert(counter!==null,'NEEDS_REAUTH');const sealed=sealSecret(i.secret,process.env.AUTH_ENCRYPTION_KEY??process.env.SESSION_SECRET);await sql(c.tx as SqlTransaction,'UPDATE auth_credentials SET totp_secret=$3,totp_last_counter=$4 WHERE user_id=$1 AND company_id=$2',[c.actor.userId,c.actor.companyId,sealed,counter]);await sql(c.tx as SqlTransaction,'UPDATE auth_sessions SET revoked_at=now() WHERE user_id=$1 AND company_id=$2',[c.actor.userId,c.actor.companyId]);await c.tx.event('identity.mfa_configured',{userId:c.actor.userId});return {ok:true,reauthenticationRequired:true};}),
 'legal_approval.record':command('legal.manage',z.object({subject:z.enum(['TAX_PROFILE','QUOTE_TEMPLATE','WORK_ACCEPTANCE_TEMPLATE','AI_TRANSFER','GPS_LEGAL_PROCESS','GPS_NECESSITY','GPS_WORKS_COUNCIL','GPS_EMPLOYEE_NOTICE','PRIVACY','PAYROLL']),reviewer:text,evidenceReference:z.string().min(8).max(2000),approvedAt:timestamp,expiresAt:timestamp,scope:z.record(z.unknown()),documentMediaId:id.optional()}).strict(),async(c,i)=>{assert(c.actor.roles.some(r=>['OWNER','DIRECTOR'].includes(r)),'ACCESS_DENIED');assert(Date.parse(i.approvedAt)<=Date.parse(c.now)&&Date.parse(i.expiresAt)>Date.parse(c.now),'VALIDATION_ERROR');if(i.documentMediaId)await c.tx.get('media_asset',i.documentMediaId);const result=await c.tx.add('legal_approval',{...i,status:'APPROVED',active:true,recordedBy:c.actor.userId,recordedAt:c.now,approvalType:'RECORDED_EXTERNAL_REVIEW'});await c.tx.event('legal.approval_recorded',{approvalId:result.id,subject:i.subject,evidenceReference:i.evidenceReference});return result;},true),
 'legal_approval.revoke':command('legal.manage',z.object({id,reason:text}).strict(),async(c,i)=>{const approval=await c.tx.get('legal_approval',i.id);const result=await c.tx.save(approval,{...approval.data,active:false,status:'REVOKED',revokedAt:c.now,revokedBy:c.actor.userId,reason:i.reason},c.expectedVersion);await c.tx.event('legal.approval_revoked',{approvalId:approval.id,subject:approval.data.subject});return result;},true),
};

/** Invitation possession verifies only the explicitly invited identity and scopes. Atomic SQL and aggregate commit. */
export async function activateInvitation(tx:SqlTransaction,companyId:string,input:{token:string;password:string;totpSecret?:string;otp?:string},now=new Date().toISOString(),encryptionKey?:string){const i=z.object({token:z.string().min(30).max(100),password:z.string().min(12).max(128),totpSecret:z.string().regex(/^[A-Z2-7]{16,100}$/).optional(),otp:z.string().regex(/^\d{6}$/).optional()}).strict().parse(input);const invitation=(await tx.list('user_invitation')).find(e=>e.data.tokenHash===hashToken(i.token));assert(invitation&&invitation.companyId===companyId&&invitation.data.status==='PENDING'&&Date.parse(invitation.data.expiresAt)>Date.parse(now),'NOT_FOUND_SAFE');assert(!(await tx.list('user')).some(u=>u.data.email?.toLowerCase()===invitation.data.email),'NOT_FOUND_SAFE');let secret:string|null=null,counter=-1;const needsMfa=invitation.data.roles.some((r:string)=>['OWNER','DIRECTOR','OPERATIONS_MANAGER','ACCOUNTANT','BOT_ADMIN','DISPATCHER'].includes(r));if(needsMfa||i.totpSecret){assert(i.totpSecret&&i.otp,'NEEDS_REAUTH');counter=validateTotp(i.totpSecret,i.otp,Date.parse(now))??-1;assert(counter>=0,'NEEDS_REAUTH');secret=sealSecret(i.totpSecret,encryptionKey);}const passwordHash=await hashPassword(i.password);const user=await tx.add('user',{name:invitation.data.name,email:invitation.data.email,roles:invitation.data.roles,permissions:invitation.data.permissions,siteIds:invitation.data.siteIds,warehouseIds:invitation.data.warehouseIds,customerIds:[],active:true,activatedAt:now,invitationId:invitation.id,mfaRequired:needsMfa});await sql(tx,'INSERT INTO auth_credentials(user_id,company_id,password_hash,totp_secret,totp_last_counter) VALUES($1,$2,$3,$4,$5)',[user.id,companyId,passwordHash,secret,counter]);await tx.add('contact_identity',{userId:user.id,type:'EMAIL',value:invitation.data.email,verified:true,active:true,verifiedAt:now,verificationSource:'ONE_TIME_COMPANY_INVITATION'});await tx.save(invitation,{...invitation.data,status:'CONSUMED',consumedAt:now,userId:user.id},invitation.version);await tx.event('identity.invitation_activated',{invitationId:invitation.id,userId:user.id});return {userId:user.id};}
