import { createHash, randomBytes } from 'node:crypto';
import { z } from 'zod';
import {taskCalendarScheduleSchema,planTaskCalendar,taskOccurrenceKey} from './task-calendar.ts';
import {createWorkingTimeAdvisoryCommands} from './working-time-advisory.ts';
import { assert, id, timestamp, transition, type CommandContext, type CommandDefinition, type CommandRegistry, type Data, type Entity } from './core.ts';

const text = z.string().trim().min(1).max(4000);
const shortText = z.string().trim().min(1).max(250);
const quantity = z.number().int().nonnegative().safe();
const activity = z.enum(['WORKING', 'ON_BREAK', 'AWAY_PENDING_REASON', 'SERVICE_TASK', 'WAITING_WORK']);
const activities = [...activity.options, 'TRAVELLING'] as const;
const units = z.enum(['M2', 'WINDOW', 'ROOM', 'FLOOR', 'UNIT', 'HOUR']);
const completionKind = z.enum(['ORIGINAL', 'CONTINUATION', 'REWORK', 'ADDITIONAL_SCOPE']);
const nodeType = z.enum(['BUILDING', 'SECTION', 'ENTRANCE', 'FLOOR', 'APARTMENT', 'ROOM', 'COMMON_AREA', 'OUTDOOR_ZONE', 'TERRITORY_SEGMENT', 'FENCE_SEGMENT', 'STORAGE_AREA', 'CUSTOM']);
const checklist = z.array(z.object({ id, label: shortText, required: z.boolean().default(true), checked: z.boolean().default(false) }).strict()).max(100);
const taskInput = z.object({
  siteId: id, locationId: id.optional(), orderId: id.optional(), workPackageId: id.optional(), title: shortText,
  description: z.string().max(10000).default(''), originalLanguage: z.enum(['de', 'uk', 'en', 'pl', 'ru', 'lt']).default('de'),
  serviceType: shortText.default('GENERAL'), unit: units.default('UNIT'), plannedQuantityMilli: quantity.default(1000),
  plannedMinutes: quantity.default(0), assigneeIds: z.array(id).max(100).default([]), dueAt: timestamp.optional(),
  priority: z.enum(['LOW', 'NORMAL', 'HIGH', 'URGENT']).default('NORMAL'), dependencyIds: z.array(id).max(100).default([]),
  checklist: checklist.default([]), acceptanceCriteria: z.array(shortText).max(100).default([]), requiredPhotoCount: quantity.max(50).default(0),
  completionKind: completionKind.default('ORIGINAL'), clientVisible: z.boolean().default(false),
  billingScope: z.enum(['CONTRACT', 'CHANGE_ORDER', 'INTERNAL', 'PENDING_APPROVAL']).default('CONTRACT'),
  changeOrderId: id.optional(), materialRequirements: z.array(z.object({ materialId: id, quantityBase: quantity.positive() }).strict()).max(100).default([]),
}).strict();
const locationInput = z.object({ siteId: id, parentId: id.nullable().optional(), nodeType, code: shortText, name: shortText,
  names: z.record(z.string().max(200)).default({}), sortOrder: z.number().int().default(0), floorLevel: z.number().int().min(-50).max(300).optional(),
  floorLabelDe: shortText.optional(), measurement: z.object({ valueMilli: quantity, unit: shortText, source: shortText }).strict().optional(),
  externalKey: id.optional(), customTypeApproval: shortText.optional(),
}).strict();
const taskTransitions: Record<string, string[]> = { DRAFT: ['READY', 'ASSIGNED', 'CANCELLED'], READY: ['ASSIGNED', 'CANCELLED'], ASSIGNED: ['IN_PROGRESS', 'BLOCKED', 'CANCELLED'], IN_PROGRESS: ['SUBMITTED_FOR_REVIEW', 'BLOCKED', 'CANCELLED'], SUBMITTED_FOR_REVIEW: ['ACCEPTED', 'REOPENED'], ACCEPTED: ['REOPENED'], BLOCKED: ['ASSIGNED', 'IN_PROGRESS', 'CANCELLED'], REOPENED: ['ASSIGNED', 'IN_PROGRESS', 'CANCELLED'], CANCELLED: [] };
function command(permission: string, schema: z.ZodTypeAny, handler: CommandDefinition['handler'], highRisk = false): CommandDefinition { return { permission, schema, handler, ...(highRisk ? { highRisk: true } : {}) }; }
function utc(value: string): string { return new Date(value).toISOString(); }
function ms(value: string): number { return new Date(value).getTime(); }
function occurred(ctx: CommandContext, input?: string): string { const result = utc(input ?? ctx.now); assert(ms(result) <= ms(ctx.now) + 300_000, 'INVALID_STATE', { reason: 'DEVICE_CLOCK_FUTURE' }); return result; }
async function entity(ctx: CommandContext, kind: string, entityId: string): Promise<Entity> { const result = await ctx.tx.get(kind, entityId); assert(result.companyId === ctx.actor.companyId, 'NOT_FOUND_SAFE'); return result; }
async function all(ctx: CommandContext, kind: string): Promise<Entity[]> { return (await ctx.tx.list(kind)).filter(e => e.companyId === ctx.actor.companyId); }
async function site(ctx: CommandContext, siteId: string): Promise<Entity> { ctx.requireSite(siteId); const s = await entity(ctx, 'site', siteId); assert(s.data.active !== false, 'INVALID_STATE', { reason: 'SITE_ARCHIVED' }); return s; }
async function employee(ctx: CommandContext, employeeId: string, siteId?: string): Promise<void> { const u = await entity(ctx, 'user', employeeId); assert(u.data.active !== false, 'ACCESS_DENIED'); assert(!siteId || (u.data.siteIds ?? []).includes(siteId) || (u.data.roles ?? []).some((r: string) => ['OWNER', 'DIRECTOR', 'OPERATIONS_MANAGER'].includes(r)), 'ACCESS_DENIED', { reason: 'EMPLOYEE_SITE_SCOPE' }); }
async function task(ctx: CommandContext, taskId: string): Promise<Entity> { const t = await entity(ctx, 'task', taskId); await site(ctx, t.data.siteId); return t; }
function assigned(ctx: CommandContext, t: Entity): void { assert((t.data.assigneeIds ?? []).includes(ctx.actor.userId), 'ACCESS_DENIED'); }
async function path(ctx: CommandContext, nodeId?: string): Promise<Data[]> { if (!nodeId) return []; const output: Data[] = []; let current: string | null = nodeId; const visited = new Set<string>(); while (current) { assert(!visited.has(current), 'INVALID_STATE', { reason: 'LOCATION_CYCLE' }); visited.add(current); const n = await entity(ctx, 'location', current); output.unshift({ id: n.id, code: n.data.code, name: n.data.name, nodeType: n.data.nodeType, floorLevel: n.data.floorLevel, floorLabelDe: n.data.floorLabelDe, revision: n.data.revision }); current = n.data.parentId ?? null; } return output; }
async function checkParent(ctx: CommandContext, siteId: string, parentId?: string | null, childId?: string): Promise<void> { if (!parentId) return; const parent = await entity(ctx, 'location', parentId); assert(parent.data.siteId === siteId && parent.data.active, 'INVALID_STATE', { reason: 'INVALID_PARENT' }); const ancestors = await path(ctx, parentId); assert(!ancestors.some(n => n.id === childId), 'INVALID_STATE', { reason: 'LOCATION_CYCLE' }); }
function checkLocationInput(input: Data): void { assert(input.nodeType !== 'FLOOR' || (input.floorLevel !== undefined && input.floorLabelDe), 'VALIDATION_ERROR', { reason: 'FLOOR_LABEL_REQUIRED', clarification: 'EG or 1. OG must be explicit' }); assert(input.nodeType !== 'CUSTOM' || input.customTypeApproval, 'NEEDS_APPROVAL', { reason: 'CUSTOM_LOCATION_TYPE' }); }
async function createLocation(ctx: CommandContext, input: Data, validatedBatch = false): Promise<Entity> { await site(ctx, input.siteId); checkLocationInput(input); await checkParent(ctx, input.siteId, input.parentId); const nodes = await all(ctx, 'location'); assert(validatedBatch || !nodes.some(n => n.data.siteId === input.siteId && n.data.parentId === (input.parentId ?? null) && n.data.code === input.code), 'INVALID_STATE', { reason: 'DUPLICATE_LOCATION_CODE' }); assert(!input.externalKey || !nodes.some(n => n.data.siteId === input.siteId && n.data.externalKey === input.externalKey), 'INVALID_STATE', { reason: 'DUPLICATE_EXTERNAL_KEY' }); const n = await ctx.tx.add('location', { ...input, parentId: input.parentId ?? null, active: true, revision: 1 }); await ctx.tx.add('location_revision', { locationId: n.id, revision: 1, snapshot: { ...n.data }, pathSnapshot: await path(ctx, n.id), actorId: ctx.actor.userId }); await ctx.tx.event('location.created', { locationId: n.id, siteId: input.siteId }); return n; }
async function validateTaskInput(ctx: CommandContext, input: Data): Promise<void> { await site(ctx, input.siteId); assert(new Set(input.assigneeIds).size === input.assigneeIds.length && new Set(input.checklist.map((i: Data) => i.id)).size === input.checklist.length, 'VALIDATION_ERROR', { reason: 'DUPLICATE_ITEM' }); if (input.locationId) { const n = await entity(ctx, 'location', input.locationId); assert(n.data.siteId === input.siteId && n.data.active, 'INVALID_STATE', { reason: 'LOCATION_SITE_MISMATCH' }); } if (input.orderId) { const o = await entity(ctx, 'order', input.orderId); assert(o.data.siteId === input.siteId, 'INVALID_STATE', { reason: 'ORDER_SITE_MISMATCH' }); } if (input.workPackageId) { const w = await entity(ctx, 'work_package', input.workPackageId); assert(w.data.siteId === input.siteId, 'INVALID_STATE'); } for (const worker of input.assigneeIds) await employee(ctx, worker, input.siteId); for (const dep of input.dependencyIds) { const d = await task(ctx, dep); assert(d.data.siteId === input.siteId, 'INVALID_STATE'); } assert(input.completionKind !== 'REWORK', 'NEEDS_APPROVAL', { reason: 'USE_DEFECT_REWORK_COMMAND' }); if (input.completionKind === 'ADDITIONAL_SCOPE' && input.billingScope !== 'INTERNAL') { assert(input.changeOrderId, 'NEEDS_APPROVAL', { reason: 'CHANGE_ORDER_REQUIRED' }); const c = await entity(ctx, 'change_order', input.changeOrderId); assert(['APPROVED', 'ACCEPTED'].includes(c.data.state ?? c.data.status), 'NEEDS_APPROVAL'); assert(c.data.orderId === input.orderId && input.orderId, 'ACCESS_DENIED', { reason: 'CHANGE_ORDER_SCOPE_MISMATCH' }); if (c.data.siteId) assert(c.data.siteId === input.siteId, 'ACCESS_DENIED'); } }
async function taskCreate(ctx: CommandContext, input: Data): Promise<Entity> { await validateTaskInput(ctx, input); const result = await ctx.tx.add('task', { ...input, state: input.assigneeIds.length ? 'ASSIGNED' : 'DRAFT', reportedQuantityMilli: 0, acceptedQuantityMilli: 0, reviewCycle: 0, locationSnapshot: await path(ctx, input.locationId), createdBy: ctx.actor.userId }); await ctx.tx.event('task.created', { taskId: result.id, siteId: input.siteId }); return result; }
async function updateTaskState(ctx: CommandContext, t: Entity, next: string, extra: Data = {}): Promise<Entity> { transition(t.data.state, next, taskTransitions); const result = await ctx.tx.save(t, { ...t.data, ...extra, state: next }, ctx.expectedVersion); await ctx.tx.event('task.state_changed', { taskId: t.id, siteId: t.data.siteId, from: t.data.state, to: next, actorId: ctx.actor.userId }); return result; }
async function shift(ctx: CommandContext, shiftId: string): Promise<Entity> { const s = await entity(ctx, 'shift', shiftId); ctx.requireOwn(s.data.employeeId); if (s.data.siteId) ctx.requireSite(s.data.siteId); return s; }
async function segments(ctx: CommandContext, shiftId: string): Promise<Entity[]> { return (await all(ctx, 'time_segment')).filter(s => s.data.shiftId === shiftId).sort((a, b) => ms(a.data.startAt) - ms(b.data.startAt)); }
async function timeEvent(ctx: CommandContext, s: Entity, type: string, occurredAt: string, source = 'MANUAL', detail: Data = {}): Promise<void> { await ctx.tx.add('time_event', { shiftId: s.id, employeeId: s.data.employeeId, type, occurredAt, receivedAt: utc(ctx.now), source, actorId: ctx.actor.userId, ...detail }); }
async function changeActivity(ctx: CommandContext, s: Entity, input: Data, source = 'MANUAL', applyExpected = true): Promise<Entity> { assert(s.data.state === 'ACTIVE', 'INVALID_STATE', { reason: 'SHIFT_ENDED' }); const at = occurred(ctx, input.occurredAt); const current = await entity(ctx, 'time_segment', s.data.activeSegmentId); assert(current.data.endAt === null && ms(at) >= ms(current.data.startAt), 'INVALID_STATE', { reason: 'OUT_OF_ORDER_TIME', correctionRequired: true }); if (input.siteId) await site(ctx, input.siteId); if (input.taskId) { const t = await task(ctx, input.taskId); assert(t.data.siteId === input.siteId && t.data.assigneeIds.includes(s.data.employeeId), 'ACCESS_DENIED'); } assert(input.activity !== 'WORKING' || input.siteId, 'VALIDATION_ERROR', { reason: 'WORK_SITE_REQUIRED' }); await ctx.tx.save(current, { ...current.data, endAt: at }); const next = await ctx.tx.add('time_segment', { shiftId: s.id, employeeId: s.data.employeeId, startAt: at, endAt: null, activity: input.activity, siteId: input.activity === 'ON_BREAK' ? null : input.siteId ?? null, taskId: input.activity === 'ON_BREAK' ? null : input.taskId ?? null, tripId: input.tripId ?? null, pausedTaskId: input.pausedTaskId ?? null, source, reason: input.reason ?? null }); const result = await ctx.tx.save(s, { ...s.data, activity: input.activity, siteId: input.siteId ?? s.data.siteId, activeSegmentId: next.id }, applyExpected ? ctx.expectedVersion : undefined); await timeEvent(ctx, s, 'ACTIVITY_CHANGED', at, source, { from: current.data.activity, to: input.activity, segmentId: next.id, reason: input.reason ?? null }); if (input.activity === 'ON_BREAK') await ctx.tx.event('tracking.pause', { shiftId: s.id, employeeId: s.data.employeeId, reason: 'PRIVATE_BREAK', occurredAt: at }); await ctx.tx.event('shift.activity_changed', { shiftId: s.id, activity: input.activity, occurredAt: at }); return result; }
function durationSeconds(s: Entity, now: string): number { return Math.max(0, Math.floor((ms(s.data.endAt ?? now) - ms(s.data.startAt)) / 1000)); }
function summary(segs: Entity[], now: string, paidActivities: string[] = ['WORKING', 'SERVICE_TASK', 'WAITING_WORK']): Data { const counts: Data = Object.fromEntries(activities.map(a => [a, 0])); for (const s of segs) counts[s.data.activity] = (counts[s.data.activity] ?? 0) + durationSeconds(s, now); const totalSeconds = Object.values(counts).reduce((sum: number, v: any) => sum + v, 0); const payableSeconds = paidActivities.reduce((sum, a) => sum + (counts[a] ?? 0), 0); return { totalSeconds, workSeconds: counts.WORKING, travelSeconds: counts.TRAVELLING, breakSeconds: counts.ON_BREAK, pendingSeconds: counts.AWAY_PENDING_REASON, serviceSeconds: counts.SERVICE_TASK, waitingSeconds: counts.WAITING_WORK, payableSeconds, totalMinutes: Math.floor(payableSeconds / 60), remainderSeconds: payableSeconds % 60, counters: counts, paidActivities, formula: 'sum([startAt,endAt) seconds); payable by explicit activity policy; customer billing is separate' }; }
async function endTrip(ctx: CommandContext, trip: Entity, at: string, state: string, reason?: string, applyExpected = true): Promise<Entity> { assert(trip.data.state === 'IN_PROGRESS', 'INVALID_STATE'); const result = await ctx.tx.save(trip, { ...trip.data, state, endAt: at, arrivalAt: state === 'ARRIVED' ? at : null, actualSeconds: Math.floor((ms(at) - ms(trip.data.startAt)) / 1000), reason: reason ?? trip.data.reason }, applyExpected ? ctx.expectedVersion : undefined); await ctx.tx.event('trip.ended', { tripId: trip.id, state, occurredAt: at }); return result; }
export async function effectiveTimesheet(ctx: CommandContext, t: Entity): Promise<Data[]> { let snapshot: Data[] = structuredClone(t.data.segmentSnapshot); const adjustments = (await all(ctx, 'timesheet_adjustment')).filter(a => a.data.timesheetId === t.id && a.data.state === 'APPROVED').sort((a, b) => (a.data.sequence ?? 0) - (b.data.sequence ?? 0)); for (const a of adjustments) { const changes: Data[] = a.data.proposedSnapshots ?? [a.data.proposedSnapshot]; snapshot = snapshot.map(s => changes.find(c => c.id === s.id) ?? s); } return snapshot; }
function assertTimeline(snapshot: Data[], original: Data[]): void { for (const shiftId of new Set(snapshot.map(s => s.shiftId))) { const rows = snapshot.filter(s => s.shiftId === shiftId).sort((a, b) => ms(a.startAt) - ms(b.startAt)); const prior = original.filter(s => s.shiftId === shiftId).sort((a, b) => ms(a.startAt) - ms(b.startAt)); assert(rows[0]?.startAt === prior[0]?.startAt && rows.at(-1)?.endAt === prior.at(-1)?.endAt && rows.every((s, i) => ms(s.startAt) < ms(s.endAt) && (!i || rows[i - 1]!.endAt === s.startAt)), 'INVALID_STATE', { reason: 'CORRECTION_CREATES_GAP_OR_OVERLAP' }); } }
async function trackingPolicy(ctx: CommandContext): Promise<Entity> { const policies = (await all(ctx, 'tracking_policy')).filter(p => p.data.state === 'APPROVED' && p.data.enabled).sort((a, b) => b.data.revision - a.data.revision); assert(policies.length, 'MISSING_CONFIGURATION', { reason: 'GPS_LEGAL_GATE_CLOSED' }); return policies[0]!; }
async function trackingDevice(ctx: CommandContext, deviceId: string, s: Entity): Promise<Entity> { const d = await entity(ctx, 'device', deviceId); assert(d.data.employeeId === s.data.employeeId && d.data.active && s.data.deviceId === d.id, 'ACCESS_DENIED', { reason: 'TRACKER_REVOKED_OR_FOREIGN' }); return d; }
export function geodesicMeters(a: { latitude: number; longitude: number }, b: { latitude: number; longitude: number }): number { const rad = (n: number) => n * Math.PI / 180; const h = Math.sin(rad(b.latitude - a.latitude) / 2) ** 2 + Math.cos(rad(a.latitude)) * Math.cos(rad(b.latitude)) * Math.sin(rad(b.longitude - a.longitude) / 2) ** 2; return 6_371_000 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(Math.max(0, 1 - h))); }
const destination = z.object({ kind: z.enum(['SITE', 'WAREHOUSE', 'SERVICE_POINT']), id, label: shortText.optional() }).strict();
async function validateDestination(ctx: CommandContext, dest: Data): Promise<void> { if (dest.kind === 'SITE') await site(ctx, dest.id); else { const d = await entity(ctx, dest.kind === 'WAREHOUSE' ? 'stock_location' : 'service_point', dest.id); assert(d.data.active !== false, 'INVALID_STATE'); if (d.data.siteId) ctx.requireSite(d.data.siteId); if (dest.kind === 'WAREHOUSE') assert(ctx.actor.warehouseIds.includes(dest.id) || ctx.actor.roles.some(r => ['OWNER', 'DIRECTOR', 'OPERATIONS_MANAGER'].includes(r)), 'ACCESS_DENIED'); } }

export const operationsCommands: CommandRegistry = {
  'site.create': command('site.create', z.object({ code: shortText, name: shortText, address: shortText, customerId: id.optional(), timeZone: z.literal('Europe/Berlin').default('Europe/Berlin'), managerIds: z.array(id).max(30).default([]) }).strict(), async (ctx, input) => { assert(!(await all(ctx, 'site')).some(s => s.data.code === input.code), 'INVALID_STATE', { reason: 'DUPLICATE_SITE_CODE' }); if (input.customerId) await entity(ctx, 'customer', input.customerId); const result = await ctx.tx.add('site', { ...input, active: true, revision: 1 }); await ctx.tx.event('site.created', { siteId: result.id }); return result; }),
  'site.update': command('site.structure.edit', z.object({ siteId: id, code: shortText.optional(), name: shortText.optional(), address: shortText.optional() }).strict(), async (ctx, input) => { const s = await site(ctx, input.siteId); assert(!input.code || !(await all(ctx, 'site')).some(x => x.id !== s.id && x.data.code === input.code), 'INVALID_STATE'); await ctx.tx.add('site_revision', { siteId: s.id, revision: s.data.revision, snapshot: s.data, actorId: ctx.actor.userId }); const { siteId, ...changes } = input; return ctx.tx.save(s, { ...s.data, ...changes, revision: s.data.revision + 1 }, ctx.expectedVersion); }),
  'location.create': command('site.structure.edit', locationInput, createLocation),
  'location.update': command('site.structure.edit', locationInput.omit({ siteId: true }).partial().extend({ locationId: id }).strict(), async (ctx, input) => { const n = await entity(ctx, 'location', input.locationId); await site(ctx, n.data.siteId); const { locationId, ...changes } = input; const next = { ...n.data, ...changes, revision: n.data.revision + 1 }; checkLocationInput(next); await checkParent(ctx, n.data.siteId, next.parentId, n.id); assert(!(await all(ctx, 'location')).some(x => x.id !== n.id && x.data.siteId === n.data.siteId && ((x.data.parentId === next.parentId && x.data.code === next.code) || (next.externalKey && x.data.externalKey === next.externalKey))), 'INVALID_STATE', { reason: 'DUPLICATE_LOCATION_CODE' }); await ctx.tx.add('location_revision', { locationId: n.id, revision: n.data.revision, snapshot: n.data, pathSnapshot: await path(ctx, n.id), actorId: ctx.actor.userId }); const result = await ctx.tx.save(n, next, ctx.expectedVersion); await ctx.tx.event('location.updated', { locationId: n.id, revision: next.revision }); return result; }),
  'location.archive': command('site.structure.edit', z.object({ locationId: id, reason: text }).strict(), async (ctx, input) => { const n = await entity(ctx, 'location', input.locationId); await site(ctx, n.data.siteId); assert(!(await all(ctx, 'location')).some(c => c.data.parentId === n.id && c.data.active), 'INVALID_STATE', { reason: 'ACTIVE_CHILDREN' }); assert(!(await all(ctx, 'task')).some(t => t.data.locationId === n.id && !['ACCEPTED', 'CANCELLED'].includes(t.data.state)), 'INVALID_STATE', { reason: 'OPEN_TASKS' }); await ctx.tx.add('location_revision', { locationId: n.id, revision: n.data.revision, snapshot: n.data, pathSnapshot: await path(ctx, n.id), actorId: ctx.actor.userId }); return ctx.tx.save(n, { ...n.data, active: false, archiveReason: input.reason, revision: n.data.revision + 1 }, ctx.expectedVersion); }),
  'location.breadcrumb': command('site.read', z.object({ locationId: id }).strict(), async (ctx, input) => { const n = await entity(ctx, 'location', input.locationId); await site(ctx, n.data.siteId); return { siteId: n.data.siteId, path: await path(ctx, n.id), archived: !n.data.active }; }),
  'work_package.create': command('task.create', z.object({ siteId: id, locationId: id.optional(), parentId: id.optional(), title: shortText, unit: units, plannedQuantityMilli: quantity, progressWeightMilli: quantity.positive().default(1000) }).strict(), async (ctx, input) => { await site(ctx, input.siteId); if (input.locationId) { const n = await entity(ctx, 'location', input.locationId); assert(n.data.siteId === input.siteId, 'INVALID_STATE'); } if (input.parentId) { const p = await entity(ctx, 'work_package', input.parentId); assert(p.data.siteId === input.siteId && p.data.unit === input.unit, 'INVALID_STATE'); } return ctx.tx.add('work_package', { ...input, state: 'ACTIVE' }); }),
  'task.create': command('task.create', taskInput, taskCreate),
  'task.ready': command('task.create', z.object({ taskId: id }).strict(), async (ctx, input) => updateTaskState(ctx, await task(ctx, input.taskId), 'READY')),
  'task.assign': command('task.assign', z.object({ taskId: id, employeeIds: z.array(id).min(1).max(100) }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assert(['DRAFT', 'READY', 'ASSIGNED', 'REOPENED', 'BLOCKED'].includes(t.data.state), 'INVALID_STATE'); assert(new Set(input.employeeIds).size === input.employeeIds.length, 'VALIDATION_ERROR'); for (const employeeId of input.employeeIds) await employee(ctx, employeeId, t.data.siteId); const result = await ctx.tx.save(t, { ...t.data, state: 'ASSIGNED', assigneeIds: input.employeeIds }, ctx.expectedVersion); await ctx.tx.add('task_assignment', { taskId: t.id, siteId: t.data.siteId, employeeIds: input.employeeIds, assignedBy: ctx.actor.userId, assignedAt: ctx.now }); await ctx.tx.event('task.assigned', { taskId: t.id, employeeIds: input.employeeIds, siteId: t.data.siteId }); return result; }),
  'task.start': command('task.work', z.object({ taskId: id }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assigned(ctx, t); for (const dep of t.data.dependencyIds) assert((await task(ctx, dep)).data.state === 'ACCEPTED', 'INVALID_STATE', { reason: 'DEPENDENCY_NOT_ACCEPTED' }); if (t.data.state === 'IN_PROGRESS') return t; return updateTaskState(ctx, t, 'IN_PROGRESS', { startedAt: ctx.now }); }),
  'task.worklog': command('task.work', z.object({ taskId: id, quantityMilli: quantity, description: text, remainingQuantityMilli: quantity.optional(), problems: z.string().max(4000).optional(), delayReason: z.string().max(4000).optional(), groupResultKey: id.optional(), employeeIds: z.array(id).max(100).optional(), photoIds: z.array(id).max(100).default([]) }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assigned(ctx, t); assert(['IN_PROGRESS', 'BLOCKED', 'REOPENED'].includes(t.data.state), 'INVALID_STATE'); const ids = input.employeeIds ?? [ctx.actor.userId]; assert(ids.includes(ctx.actor.userId) && ids.every((u: string) => t.data.assigneeIds.includes(u)) && new Set(ids).size === ids.length, 'ACCESS_DENIED'); assert(t.data.assigneeIds.length <= 1 || input.groupResultKey, 'VALIDATION_ERROR', { reason: 'TEAM_RESULT_KEY_REQUIRED' }); if (input.groupResultKey) { const existing = (await all(ctx, 'worklog')).find(w => w.data.taskId === t.id && w.data.groupResultKey === input.groupResultKey); if (existing) { assert(existing.data.quantityMilli === input.quantityMilli, 'INVALID_STATE', { reason: 'TEAM_RESULT_CONFLICT' }); return existing; } } for (const photoId of input.photoIds) { const m = await entity(ctx, 'media_asset', photoId); assert(m.data.siteId === t.data.siteId && (!m.data.taskId || m.data.taskId === t.id), 'ACCESS_DENIED'); } const result = await ctx.tx.add('worklog', { ...input, siteId: t.data.siteId, unit: t.data.unit, employeeIds: ids, authorId: ctx.actor.userId, reportedAt: ctx.now, reviewCycle: t.data.reviewCycle }); await ctx.tx.save(t, { ...t.data, reportedQuantityMilli: t.data.reportedQuantityMilli + input.quantityMilli }, ctx.expectedVersion); await ctx.tx.event('worklog.created', { worklogId: result.id, taskId: t.id, siteId: t.data.siteId }); return result; }),
  'task.checklist': command('task.work', z.object({ taskId: id, itemId: id, checked: z.boolean(), note: z.string().max(2000).optional() }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assigned(ctx, t); assert(!['ACCEPTED', 'CANCELLED'].includes(t.data.state), 'INVALID_STATE'); assert(t.data.checklist.some((c: Data) => c.id === input.itemId), 'NOT_FOUND_SAFE'); return ctx.tx.save(t, { ...t.data, checklist: t.data.checklist.map((c: Data) => c.id === input.itemId ? { ...c, checked: input.checked, checkedBy: ctx.actor.userId, checkedAt: ctx.now, note: input.note ?? null } : c) }, ctx.expectedVersion); }),
  'task.submit': command('task.work', z.object({ taskId: id, description: z.string().max(4000).optional() }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assigned(ctx, t); return updateTaskState(ctx, t, 'SUBMITTED_FOR_REVIEW', { submittedAt: ctx.now, submittedBy: ctx.actor.userId, submissionDescription: input.description ?? null }); }),
  'task.review': command('task.review', z.object({ taskId: id, decision: z.enum(['ACCEPT', 'REJECT']), reason: text.optional() }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assert(t.data.state === 'SUBMITTED_FOR_REVIEW', 'INVALID_STATE'); assert(!t.data.assigneeIds.includes(ctx.actor.userId) && t.data.submittedBy !== ctx.actor.userId, 'ACCESS_DENIED', { reason: 'SELF_APPROVAL_FORBIDDEN' }); const logs = (await all(ctx, 'worklog')).filter(w => w.data.taskId === t.id && w.data.reviewCycle === t.data.reviewCycle); if (input.decision === 'ACCEPT') { assert(t.data.checklist.every((c: Data) => !c.required || c.checked), 'NEEDS_APPROVAL', { reason: 'CHECKLIST_INCOMPLETE' }); assert(new Set(logs.flatMap(w => w.data.photoIds ?? [])).size >= t.data.requiredPhotoCount, 'NEEDS_APPROVAL', { reason: 'REQUIRED_PHOTO_MISSING' }); } else assert(input.reason, 'VALIDATION_ERROR', { reason: 'REVIEW_REASON_REQUIRED' }); await ctx.tx.add('task_review', { taskId: t.id, siteId: t.data.siteId, cycle: t.data.reviewCycle, decision: input.decision, reason: input.reason ?? null, reviewedBy: ctx.actor.userId, reviewedAt: ctx.now, quantityMilli: t.data.reportedQuantityMilli, worklogIds: logs.map(w => w.id), snapshot: t.data }); if (input.decision === 'ACCEPT' && t.data.completionKind === 'REWORK' && t.data.defectId) { const defect = await entity(ctx, 'defect', t.data.defectId); assert(defect.data.reworkTaskId === t.id, 'INVALID_STATE'); await ctx.tx.save(defect, { ...defect.data, state: 'CLOSED', resolvedBy: ctx.actor.userId, resolvedAt: ctx.now }); } return updateTaskState(ctx, t, input.decision === 'ACCEPT' ? 'ACCEPTED' : 'REOPENED', { reportedQuantityMilli: input.decision === 'REJECT' ? 0 : t.data.reportedQuantityMilli, acceptedQuantityMilli: input.decision === 'ACCEPT' ? t.data.reportedQuantityMilli : t.data.acceptedQuantityMilli, reviewedBy: ctx.actor.userId, reviewedAt: ctx.now, reviewCycle: t.data.reviewCycle + 1 }); }),
  'task.block': command('task.work', z.object({ taskId: id, reason: text }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assigned(ctx, t); return updateTaskState(ctx, t, 'BLOCKED', { blockedReason: input.reason, blockedAt: ctx.now }); }),
  'task.reopen': command('task.review', z.object({ taskId: id, reason: text }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); await ctx.tx.add('task_review', { taskId: t.id, decision: 'REOPEN', reason: input.reason, snapshot: t.data, reviewedBy: ctx.actor.userId, reviewedAt: ctx.now }); return updateTaskState(ctx, t, 'REOPENED', { reopenReason: input.reason, acceptedQuantityMilli: 0, reportedQuantityMilli: 0, reviewCycle: t.data.reviewCycle + 1, submittedBy: null }); }),
  'task.cancel': command('task.assign', z.object({ taskId: id, reason: text }).strict(), async (ctx, input) => updateTaskState(ctx, await task(ctx, input.taskId), 'CANCELLED', { cancellationReason: input.reason })),
  'task.progress': command('task.read', z.object({ siteId: id, workPackageId: id.optional(), locationId: id.optional() }).strict(), async (ctx, input) => { await site(ctx, input.siteId); let tasks = (await all(ctx, 'task')).filter(t => t.data.siteId === input.siteId && t.data.state !== 'CANCELLED'); if (input.workPackageId) tasks = tasks.filter(t => t.data.workPackageId === input.workPackageId); if (input.locationId) { const descendants = new Set([input.locationId]); const nodes = (await all(ctx, 'location')).filter(n => n.data.siteId === input.siteId); for (let changed = true; changed;) { changed = false; for (const n of nodes) if (descendants.has(n.data.parentId) && !descendants.has(n.id)) { descendants.add(n.id); changed = true; } } tasks = tasks.filter(t => descendants.has(t.data.locationId)); } const byUnit: Data = {}; for (const t of tasks) { const u = byUnit[t.data.unit] ??= { plannedQuantityMilli: 0, submittedQuantityMilli: 0, acceptedQuantityMilli: 0, taskIds: [] }; u.plannedQuantityMilli += t.data.plannedQuantityMilli; if (['SUBMITTED_FOR_REVIEW', 'ACCEPTED'].includes(t.data.state)) u.submittedQuantityMilli += t.data.reportedQuantityMilli; if (t.data.state === 'ACCEPTED') u.acceptedQuantityMilli += t.data.acceptedQuantityMilli; u.taskIds.push(t.id); } for (const u of Object.values(byUnit) as Data[]) { u.acceptedRatio = u.plannedQuantityMilli > 0 ? u.acceptedQuantityMilli / u.plannedQuantityMilli : null; u.submittedRatio = u.plannedQuantityMilli > 0 ? u.submittedQuantityMilli / u.plannedQuantityMilli : null; } return { byUnit, formula: 'atomic accepted quantity / planned quantity; incompatible units are separate', tasks: tasks.length }; }),
  'defect.create': command('task.review', z.object({ taskId: id, externalKey: id, description: text, severity: z.enum(['LOW', 'NORMAL', 'HIGH', 'CRITICAL']).default('NORMAL'), dueAt: timestamp.optional(), photoIds: z.array(id).max(100).default([]) }).strict(), async (ctx, input) => { const t = await task(ctx, input.taskId); assert(['SUBMITTED_FOR_REVIEW', 'ACCEPTED', 'REOPENED'].includes(t.data.state), 'INVALID_STATE'); const existing = (await all(ctx, 'defect')).find(d => d.data.taskId === t.id && d.data.externalKey === input.externalKey); if (existing) return existing; for (const photoId of input.photoIds) { const p = await entity(ctx, 'media_asset', photoId); assert(p.data.siteId === t.data.siteId, 'ACCESS_DENIED'); } const d = await ctx.tx.add('defect', { ...input, siteId: t.data.siteId, locationId: t.data.locationId ?? null, state: 'OPEN', authorId: ctx.actor.userId, originalTaskSnapshot: t.data }); await ctx.tx.event('defect.created', { defectId: d.id, taskId: t.id, siteId: t.data.siteId }); return d; }),
  'defect.rework': command('task.review', z.object({ defectId: id, assigneeIds: z.array(id).min(1).max(100), title: shortText.optional(), plannedQuantityMilli: quantity.optional(), plannedMinutes: quantity.default(0), responsibilityDecision: text }).strict(), async (ctx, input) => { const d = await entity(ctx, 'defect', input.defectId); await site(ctx, d.data.siteId); if (d.data.reworkTaskId) return task(ctx, d.data.reworkTaskId); const original = await task(ctx, d.data.taskId); for (const u of input.assigneeIds) await employee(ctx, u, d.data.siteId); const rework = await ctx.tx.add('task', { ...original.data, title: input.title ?? `REWORK: ${original.data.title}`, state: 'ASSIGNED', assigneeIds: input.assigneeIds, completionKind: 'REWORK', billingScope: 'INTERNAL', sourceTaskId: original.id, defectId: d.id, plannedQuantityMilli: input.plannedQuantityMilli ?? original.data.plannedQuantityMilli, plannedMinutes: input.plannedMinutes, reportedQuantityMilli: 0, acceptedQuantityMilli: 0, reviewCycle: 0, submittedAt: null, submittedBy: null, reviewedBy: null, reviewedAt: null, startedAt: null, checklist: original.data.checklist.map((c: Data) => ({ id: c.id, label: c.label, required: c.required, checked: false })), createdBy: ctx.actor.userId }); await ctx.tx.save(d, { ...d.data, state: 'REWORK_ASSIGNED', reworkTaskId: rework.id, responsibilityDecision: input.responsibilityDecision, decidedBy: ctx.actor.userId }); await ctx.tx.add('rework_link', { defectId: d.id, originalTaskId: original.id, reworkTaskId: rework.id, siteId: d.data.siteId, billingScope: 'INTERNAL', originalSnapshot: original.data }); await ctx.tx.event('defect.rework_created', { defectId: d.id, taskId: rework.id, siteId: d.data.siteId }); return rework; }),
  'shift.start': command('shift.manage', z.object({ employeeId: id.optional(), siteId: id, taskId: id.optional(), occurredAt: timestamp.optional(), deviceId: id.optional() }).strict(), async (ctx, input) => { const employeeId = input.employeeId ?? ctx.actor.userId; ctx.requireOwn(employeeId); await site(ctx, input.siteId); await employee(ctx, employeeId, input.siteId); const active = (await all(ctx, 'shift')).find(s => s.data.employeeId === employeeId && s.data.state === 'ACTIVE'); assert(!active, 'INVALID_STATE', { reason: 'ACTIVE_SHIFT_EXISTS', shiftId: active?.id }); const at = occurred(ctx, input.occurredAt); const past = (await all(ctx, 'shift')).filter(s => s.data.employeeId === employeeId); assert(!past.some(s => ms(at) < ms(s.data.endAt ?? ctx.now)), 'INVALID_STATE', { reason: 'SHIFT_OVERLAP', correctionRequired: true }); if (input.taskId) { const t = await task(ctx, input.taskId); assert(t.data.siteId === input.siteId && t.data.assigneeIds.includes(employeeId), 'ACCESS_DENIED'); } let selectedDeviceId = input.deviceId; if (selectedDeviceId) { const d = await entity(ctx, 'device', selectedDeviceId); assert(d.data.employeeId === employeeId && d.data.active, 'ACCESS_DENIED'); } else selectedDeviceId = (await all(ctx, 'device')).find(d => d.data.employeeId === employeeId && d.data.active)?.id; const s = await ctx.tx.add('shift', { employeeId, siteId: input.siteId, state: 'ACTIVE', activity: 'WORKING', startAt: at, endAt: null, deviceId: selectedDeviceId ?? null, timesheetState: 'DRAFT' }); const seg = await ctx.tx.add('time_segment', { employeeId, shiftId: s.id, activity: 'WORKING', siteId: input.siteId, taskId: input.taskId ?? null, tripId: null, startAt: at, endAt: null, source: 'MANUAL', reason: null }); const result = await ctx.tx.save(s, { ...s.data, activeSegmentId: seg.id }); await timeEvent(ctx, s, 'SHIFT_STARTED', at); await ctx.tx.event('shift.started', { shiftId: s.id, employeeId, siteId: input.siteId, occurredAt: at }); return result; }),
  'shift.activity': command('shift.manage', z.object({ shiftId: id, activity, siteId: id.optional(), taskId: id.optional(), occurredAt: timestamp.optional(), reason: text.optional() }).strict(), async (ctx, input) => { const s = await shift(ctx, input.shiftId); assert(s.data.activity !== 'TRAVELLING', 'INVALID_STATE', { reason: 'USE_TRIP_STOP_OR_END' }); return changeActivity(ctx, s, input); }),
  'shift.end': command('shift.manage', z.object({ shiftId: id, occurredAt: timestamp.optional(), description: z.string().max(10000).optional() }).strict(), async (ctx, input) => { const s = await shift(ctx, input.shiftId); assert(s.data.state === 'ACTIVE', 'INVALID_STATE'); const at = occurred(ctx, input.occurredAt); const current = await entity(ctx, 'time_segment', s.data.activeSegmentId); assert(ms(at) >= ms(current.data.startAt), 'INVALID_STATE', { reason: 'OUT_OF_ORDER_TIME' }); await ctx.tx.save(current, { ...current.data, endAt: at }); for (const t of (await all(ctx, 'trip')).filter(t => t.data.shiftId === s.id && t.data.state === 'IN_PROGRESS')) await endTrip(ctx, t, at, 'ENDED_WITHOUT_ARRIVAL', 'SHIFT_ENDED', false); const segs = await segments(ctx, s.id); const totals = summary(segs, at); const result = await ctx.tx.save(s, { ...s.data, state: 'ENDED', activity: 'OFF_DUTY', endAt: at, summary: totals, description: input.description ?? null, pendingResultDescription: !input.description }, ctx.expectedVersion); await timeEvent(ctx, s, 'SHIFT_ENDED', at); await ctx.tx.event('shift.ended', { shiftId: s.id, employeeId: s.data.employeeId, occurredAt: at }); await ctx.tx.event('tracking.stop', { shiftId: s.id, employeeId: s.data.employeeId, occurredAt: at }); return result; }),
  'shift.summary': command('shift.read', z.object({ shiftId: id }).strict(), async (ctx, input) => { const s = await shift(ctx, input.shiftId); const segs = await segments(ctx, s.id); const allocations = (await all(ctx, 'work_allocation')).filter(a => segs.some(s => s.id === a.data.segmentId)); const allocatedSeconds = allocations.reduce((sum, a) => sum + a.data.seconds, 0); const totals = summary(segs, s.data.endAt ?? ctx.now); return { shiftId: s.id, ...totals, allocatedSeconds, unallocatedSeconds: totals.totalSeconds - totals.breakSeconds - allocatedSeconds, segments: segs, allocations, legalWorkingTime: 'REQUIRES_SEPARATE_APPROVED_POLICY', customerBilling: 'REQUIRES_SEPARATE_CONTRACT' }; }),
  'time.allocate': command('task.work', z.object({ segmentId: id, taskId: id, worklogId: id.optional(), seconds: quantity.positive() }).strict(), async (ctx, input) => { const seg = await entity(ctx, 'time_segment', input.segmentId); const s = await shift(ctx, seg.data.shiftId); const t = await task(ctx, input.taskId); assert(s.data.employeeId === ctx.actor.userId, 'ACCESS_DENIED'); assert(seg.data.endAt && ['WORKING', 'SERVICE_TASK', 'WAITING_WORK'].includes(seg.data.activity), 'INVALID_STATE'); assert(t.data.siteId === seg.data.siteId && t.data.assigneeIds.includes(s.data.employeeId), 'ACCESS_DENIED'); assert(!['APPROVED', 'LOCKED'].includes(s.data.timesheetState), 'INVALID_STATE', { reason: 'PERIOD_LOCKED' }); if (input.worklogId) { const log = await entity(ctx, 'worklog', input.worklogId); assert(log.data.taskId === t.id && log.data.employeeIds.includes(s.data.employeeId), 'ACCESS_DENIED'); } const existing = (await all(ctx, 'work_allocation')).filter(a => a.data.segmentId === seg.id); assert(existing.reduce((sum, a) => sum + a.data.seconds, 0) + input.seconds <= durationSeconds(seg, ctx.now), 'INVALID_STATE', { reason: 'ALLOCATION_EXCEEDS_SEGMENT' }); return ctx.tx.add('work_allocation', { ...input, employeeId: s.data.employeeId, siteId: t.data.siteId, shiftId: s.id }); }),
};

const importRow = locationInput.omit({ siteId: true, parentId: true }).extend({ externalKey: id, parentExternalKey: id.nullable().optional() }).strict();
const importInput = z.object({ siteId: id, rows: z.array(importRow).min(1).max(1000) }).strict();
async function importPreview(ctx: CommandContext, input: Data): Promise<Data> {
  await site(ctx, input.siteId); const existing = (await all(ctx, 'location')).filter(n => n.data.siteId === input.siteId); const byKey = new Map(existing.filter(n => n.data.externalKey).map(n => [n.data.externalKey, n]));
  const errors: Data[] = [], seen = new Set<string>(); const graph = new Map<string, Data>(); const rowNumbers = new Map<string, number>(); const nodeKey = (n: Entity) => n.data.externalKey ? `external:${n.data.externalKey}` : `id:${n.id}`;
  for (const n of existing) { const parent = existing.find(p => p.id === n.data.parentId); graph.set(nodeKey(n), { ...n.data, parentKey: parent ? nodeKey(parent) : null }); }
  for (const [index, row] of input.rows.entries()) { const key = `external:${row.externalKey}`; if (seen.has(key)) errors.push({ row: index + 1, code: 'DUPLICATE_EXTERNAL_KEY' }); seen.add(key); rowNumbers.set(key, index + 1); graph.set(key, { ...row, parentKey: row.parentExternalKey ? `external:${row.parentExternalKey}` : null }); if (row.nodeType === 'FLOOR' && (row.floorLevel === undefined || !row.floorLabelDe)) errors.push({ row: index + 1, code: 'FLOOR_LABEL_REQUIRED' }); if (row.nodeType === 'CUSTOM' && !row.customTypeApproval) errors.push({ row: index + 1, code: 'CUSTOM_TYPE_APPROVAL_REQUIRED' }); }
  const codes = new Map<string, string>(); for (const [key, n] of graph) { const sibling = `${n.parentKey ?? '-'}:${n.code}`; const previous = codes.get(sibling); if (previous && previous !== key) errors.push({ row: rowNumbers.get(key) ?? rowNumbers.get(previous), code: 'DUPLICATE_LOCATION_CODE' }); codes.set(sibling, key); }
  for (const [key, rowNumber] of rowNumbers) { let cursor: string | null = key; const visited = new Set<string>(); while (cursor) { if (visited.has(cursor)) { errors.push({ row: rowNumber, code: 'LOCATION_CYCLE' }); break; } visited.add(cursor); const n = graph.get(cursor); if (!n) { errors.push({ row: rowNumber, code: 'PARENT_NOT_FOUND', key: cursor }); break; } cursor = n.parentKey; } }
  const previewHash = createHash('sha256').update(JSON.stringify({ input, revisions: existing.map(n => [n.id, n.version]).sort() })).digest('hex');
  return { siteId: input.siteId, previewHash, rowCount: input.rows.length, createCount: input.rows.filter((r: Data) => !byKey.has(r.externalKey)).length, updateCount: input.rows.filter((r: Data) => byKey.has(r.externalKey)).length, errors, canCommit: errors.length === 0 };
}
Object.assign(operationsCommands, {
  'location.import.preview': command('site.structure.edit', importInput, importPreview),
  'location.import.commit': command('site.structure.edit', importInput.extend({ previewHash: z.string().length(64), confirmed: z.literal(true) }).strict(), async (ctx, input) => { const { previewHash, confirmed, ...contents } = input; const preview = await importPreview(ctx, contents); assert(preview.canCommit, 'VALIDATION_ERROR', { errors: preview.errors }); assert(preview.previewHash === previewHash, 'VERSION_CONFLICT', { reason: 'STALE_IMPORT_PREVIEW' }); const nodes = (await all(ctx, 'location')).filter(n => n.data.siteId === input.siteId); const byKey = new Map(nodes.filter(n => n.data.externalKey).map(n => [n.data.externalKey, n.id])); const pending: Data[] = [...input.rows]; const results: Entity[] = []; while (pending.length) { const index = pending.findIndex(r => !r.parentExternalKey || (byKey.has(r.parentExternalKey) && !pending.some(p => p.externalKey === r.parentExternalKey))); assert(index >= 0, 'INVALID_STATE', { reason: 'LOCATION_CYCLE' }); const row = pending.splice(index, 1)[0]!; const { parentExternalKey, ...fields } = row; const next = { ...fields, siteId: input.siteId, parentId: parentExternalKey ? byKey.get(parentExternalKey) : null }; const existingId = byKey.get(row.externalKey); let result: Entity; if (existingId) { const existing = await entity(ctx, 'location', existingId); await checkParent(ctx, input.siteId, next.parentId, existingId); await ctx.tx.add('location_revision', { locationId: existing.id, revision: existing.data.revision, snapshot: existing.data, pathSnapshot: await path(ctx, existing.id), actorId: ctx.actor.userId }); result = await ctx.tx.save(existing, { ...existing.data, ...next, revision: existing.data.revision + 1 }); } else result = await createLocation(ctx, next, true); byKey.set(row.externalKey, result.id); results.push(result); } await ctx.tx.event('location.imported', { siteId: input.siteId, count: results.length, previewHash }); return { previewHash, locations: results }; }),
  'task_template.create': command('task.create', z.object({ name: shortText, task: taskInput.omit({ assigneeIds: true, dueAt: true, dependencyIds: true }), recurrence: z.enum(['DAILY', 'WEEKLY', 'MONTHLY', 'MANUAL']).default('MANUAL'), timeZone: z.literal('Europe/Berlin').default('Europe/Berlin'),schedule:taskCalendarScheduleSchema.optional(),scheduledAssigneeIds:z.array(id).max(100).default([]) }).strict(), async (ctx, input) => { await site(ctx, input.task.siteId); return ctx.tx.add('task_template', { ...input, revision: 1, active: true,createdBy:ctx.actor.userId,scheduleOwnerId:ctx.actor.userId,activatedAt:input.schedule?ctx.now:undefined }); }),
  'task_template.update': command('task.create', z.object({ templateId: id, name: shortText.optional(), task: taskInput.omit({ assigneeIds: true, dueAt: true, dependencyIds: true }).optional(), recurrence: z.enum(['DAILY', 'WEEKLY', 'MONTHLY', 'MANUAL']).optional(),schedule:taskCalendarScheduleSchema.nullable().optional(),scheduledAssigneeIds:z.array(id).max(100).optional(),active:z.boolean().optional() }).strict(), async (ctx, input) => { const t = await entity(ctx, 'task_template', input.templateId); await site(ctx, t.data.task.siteId); if (input.task) assert(input.task.siteId === t.data.task.siteId, 'INVALID_STATE'); await ctx.tx.add('task_template_revision', { templateId: t.id, revision: t.data.revision, snapshot: t.data, actorId: ctx.actor.userId }); const { templateId, ...changes } = input; return ctx.tx.save(t, { ...t.data, ...changes, revision: t.data.revision + 1,...(input.schedule!==undefined||input.recurrence!==undefined||(input.active===true&&t.data.active!==true)?{activatedAt:ctx.now,scheduleOwnerId:ctx.actor.userId}:{}) }, ctx.expectedVersion); }),
  'task_template.occurrence': command('task.create', z.object({ templateId: id, scheduledPeriod: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), locationId: id.optional(), assigneeIds: z.array(id).max(100).default([]), dueAt: timestamp.optional() }).strict(), async (ctx, input) => { const template = await entity(ctx, 'task_template', input.templateId); await site(ctx, template.data.task.siteId); assert(template.data.active, 'INVALID_STATE'); const scheduledDate = new Date(`${input.scheduledPeriod}T12:00:00Z`); assert(Number.isFinite(scheduledDate.getTime()) && scheduledDate.toISOString().slice(0, 10) === input.scheduledPeriod, 'VALIDATION_ERROR', { reason: 'INVALID_CALENDAR_DATE' }); const locationId = input.locationId ?? template.data.task.locationId; const occurrenceKey = taskOccurrenceKey(template.id,input.scheduledPeriod,locationId); const existing = (await all(ctx, 'task_occurrence')).find(o => o.data.occurrenceKey === occurrenceKey||(o.data.templateId===template.id&&o.data.scheduledPeriod===input.scheduledPeriod&&(o.data.locationId??null)===(locationId??null))); if (existing) return task(ctx, existing.data.taskId); const created = await taskCreate(ctx, taskInput.parse({ ...template.data.task, locationId, assigneeIds: input.assigneeIds, dueAt: input.dueAt })); await ctx.tx.add('task_occurrence', { occurrenceKey, templateId: template.id, templateRevision: template.data.revision, scheduledPeriod: input.scheduledPeriod, timeZone: 'Europe/Berlin', locationId: locationId ?? null, taskId: created.id, templateSnapshot: template.data }); return created; }),
  'timesheet.submit': command('timesheet.submit', z.object({ employeeId: id.optional(), periodStart: timestamp, periodEnd: timestamp }).strict(), async (ctx, input) => { const employeeId = input.employeeId ?? ctx.actor.userId; ctx.requireOwn(employeeId); const periodStart = utc(input.periodStart), periodEnd = utc(input.periodEnd); assert(ms(periodStart) < ms(periodEnd) && ms(periodEnd) <= ms(ctx.now), 'VALIDATION_ERROR'); const sheets = (await all(ctx, 'timesheet')).filter(t => t.data.employeeId === employeeId); const same = sheets.find(t => t.data.periodStart === periodStart && t.data.periodEnd === periodEnd); if (same) return same; assert(!sheets.some(t => ms(t.data.periodStart) < ms(periodEnd) && ms(t.data.periodEnd) > ms(periodStart)), 'INVALID_STATE', { reason: 'TIMESHEET_PERIOD_OVERLAP' }); const relevant = (await all(ctx, 'shift')).filter(s => s.data.employeeId === employeeId && ms(s.data.startAt) < ms(periodEnd) && ms(s.data.endAt ?? ctx.now) > ms(periodStart)); assert(relevant.every(s => s.data.state === 'ENDED'), 'INVALID_STATE', { reason: 'ACTIVE_SHIFT_IN_PERIOD' }); const segs: Entity[] = []; for (const s of relevant) { if (s.data.siteId) ctx.requireSite(s.data.siteId); for (const seg of await segments(ctx, s.id)) { const startAt = utc(new Date(Math.max(ms(periodStart), ms(seg.data.startAt))).toISOString()); const endAt = utc(new Date(Math.min(ms(periodEnd), ms(seg.data.endAt))).toISOString()); if (ms(startAt) < ms(endAt)) segs.push({ ...seg, data: { ...seg.data, startAt, endAt } }); } } const totals = summary(segs, periodEnd); const result = await ctx.tx.add('timesheet', { employeeId, periodStart, periodEnd, state: 'SUBMITTED', ...totals, payableSeconds: null, totalMinutes: null, remainderSeconds: null, shiftIds: relevant.map(s => s.id), segmentSnapshot: segs.map(s => ({ id: s.id, ...s.data, seconds: durationSeconds(s, periodEnd) })), originalSegmentSnapshot: segs.map(s => ({ id: s.id, ...s.data, seconds: durationSeconds(s, periodEnd) })), submittedBy: ctx.actor.userId, submittedAt: ctx.now, revision: 1, pendingSecondsPayability: 'UNDETERMINED' }); for (const s of relevant) await ctx.tx.save(s, { ...s.data, timesheetState: 'SUBMITTED' }); await ctx.tx.event('timesheet.submitted', { timesheetId: result.id, employeeId }); return result; }),
  'timesheet.review': command('timesheet.approve', z.object({ timesheetId: id, decision: z.enum(['APPROVE', 'DISPUTE']), reason: text.optional(), paidActivities: z.array(z.enum(activities)).max(6).default(['WORKING', 'SERVICE_TASK', 'WAITING_WORK']) }).strict(), async (ctx, input) => { const t = await entity(ctx, 'timesheet', input.timesheetId); ctx.requireOwn(t.data.employeeId); assert(t.data.employeeId !== ctx.actor.userId && t.data.submittedBy !== ctx.actor.userId, 'ACCESS_DENIED', { reason: 'SELF_APPROVAL_FORBIDDEN' }); assert(['SUBMITTED', 'DISPUTED'].includes(t.data.state), 'INVALID_STATE'); for (const s of t.data.segmentSnapshot) if (s.siteId) ctx.requireSite(s.siteId); assert(input.decision !== 'DISPUTE' || input.reason, 'VALIDATION_ERROR'); assert(!(await all(ctx, 'timesheet_correction')).some(c => c.data.timesheetId === t.id && c.data.state === 'SUBMITTED'), 'NEEDS_APPROVAL', { reason: 'CORRECTIONS_PENDING' }); const totals = summary(t.data.segmentSnapshot.map((s: Data) => ({ data: s } as Entity)), t.data.periodEnd, input.paidActivities); const state = input.decision === 'APPROVE' ? 'APPROVED' : 'DISPUTED'; const result = await ctx.tx.save(t, { ...t.data, ...totals, state, approvedBy: input.decision === 'APPROVE' ? ctx.actor.userId : null, approvedAt: input.decision === 'APPROVE' ? ctx.now : null, reviewReason: input.reason ?? null, pendingSecondsPayability: totals.pendingSeconds > 0 ? 'EXPLICIT_HUMAN_POLICY' : 'NOT_APPLICABLE' }, ctx.expectedVersion); await ctx.tx.add('timesheet_approval', { timesheetId: t.id, employeeId: t.data.employeeId, decision: input.decision, reason: input.reason ?? null, policy: { paidActivities: input.paidActivities, excludesCustomerBilling: true }, totals, approvedBy: ctx.actor.userId, approvedAt: ctx.now, snapshot: result.data }); for (const shiftId of t.data.shiftIds) { const s = await entity(ctx, 'shift', shiftId); await ctx.tx.save(s, { ...s.data, timesheetState: state }); } await ctx.tx.event('timesheet.reviewed', { timesheetId: t.id, employeeId: t.data.employeeId, state }); return result; }),
  'timesheet.lock': command('timesheet.approve', z.object({ timesheetId: id }).strict(), async (ctx, input) => { const t = await entity(ctx, 'timesheet', input.timesheetId); ctx.requireOwn(t.data.employeeId); assert(t.data.employeeId !== ctx.actor.userId && t.data.state === 'APPROVED', 'ACCESS_DENIED'); for (const shiftId of t.data.shiftIds) { const s = await entity(ctx, 'shift', shiftId); if (s.data.siteId) ctx.requireSite(s.data.siteId); await ctx.tx.save(s, { ...s.data, timesheetState: 'LOCKED' }); } return ctx.tx.save(t, { ...t.data, state: 'LOCKED', lockedBy: ctx.actor.userId, lockedAt: ctx.now }, ctx.expectedVersion); }),
  'timesheet.correction': command('timesheet.submit', z.object({ timesheetId: id, segmentId: id, activity: z.enum(activities).optional(), startAt: timestamp.optional(), endAt: timestamp.optional(), reason: text }).strict(), async (ctx, input) => {
    const t = await entity(ctx, 'timesheet', input.timesheetId); assert(t.data.employeeId === ctx.actor.userId, 'ACCESS_DENIED');
    const effective = await effectiveTimesheet(ctx, t); const original = effective.find((s: Data) => s.id === input.segmentId); assert(original, 'NOT_FOUND_SAFE'); assert(input.activity || input.startAt || input.endAt, 'VALIDATION_ERROR');
    const proposed: Data = { ...original, activity: input.activity ?? original.activity, startAt: utc(input.startAt ?? original.startAt), endAt: utc(input.endAt ?? original.endAt), correctionSource: 'HUMAN_REQUEST' }; proposed.seconds = Math.floor((ms(proposed.endAt) - ms(proposed.startAt)) / 1000); assert(proposed.activity !== original.activity || proposed.startAt !== original.startAt || proposed.endAt !== original.endAt, 'INVALID_STATE', { reason: 'NO_CORRECTION_CHANGE' });
    if (proposed.activity === 'ON_BREAK') { proposed.siteId = null; proposed.taskId = null; proposed.tripId = null; } assert(proposed.activity !== 'WORKING' || proposed.siteId, 'VALIDATION_ERROR', { reason: 'WORK_SITE_REQUIRED' });
    const next = effective.map(s => s.id === original.id ? proposed : s); assertTimeline(next, effective); const existing = (await all(ctx, 'timesheet_correction')).find(c => c.data.timesheetId === t.id && c.data.segmentId === original.id && c.data.state === 'SUBMITTED'); assert(!existing, 'INVALID_STATE', { reason: 'CORRECTION_ALREADY_PENDING' });
    const result = await ctx.tx.add('timesheet_correction', { timesheetId: t.id, employeeId: t.data.employeeId, segmentId: original.id, originalSnapshot: original, proposedSnapshot: proposed, reason: input.reason, state: 'SUBMITTED', submittedBy: ctx.actor.userId, submittedAt: ctx.now, closedPeriod: ['APPROVED', 'LOCKED'].includes(t.data.state) }); await ctx.tx.event('timesheet.correction_requested', { correctionId: result.id, timesheetId: t.id, employeeId: t.data.employeeId }); return result;
  }),
  'timesheet.correction.bulk': command('timesheet.submit', z.object({ timesheetId: id, reason: text, changes: z.array(z.object({ segmentId: id, activity: z.enum(activities).optional(), startAt: timestamp.optional(), endAt: timestamp.optional(), siteId: id.optional(), taskId: id.optional() }).strict()).min(1).max(500) }).strict(), async (ctx, input) => {
    const t = await entity(ctx, 'timesheet', input.timesheetId); assert(t.data.employeeId === ctx.actor.userId, 'ACCESS_DENIED'); assert(new Set(input.changes.map((c: Data) => c.segmentId)).size === input.changes.length, 'VALIDATION_ERROR'); const effective = await effectiveTimesheet(ctx, t); const originalSnapshots: Data[] = [], proposedSnapshots: Data[] = [];
    for (const change of input.changes) { const original = effective.find((s: Data) => s.id === change.segmentId); assert(original, 'NOT_FOUND_SAFE'); const proposed: Data = { ...original, activity: change.activity ?? original.activity, startAt: utc(change.startAt ?? original.startAt), endAt: utc(change.endAt ?? original.endAt), siteId: change.siteId ?? original.siteId, taskId: change.taskId ?? original.taskId, correctionSource: 'HUMAN_REQUEST' }; proposed.seconds = Math.floor((ms(proposed.endAt) - ms(proposed.startAt)) / 1000); assert(ms(proposed.startAt) >= ms(t.data.periodStart) && ms(proposed.endAt) <= ms(t.data.periodEnd), 'VALIDATION_ERROR'); if (proposed.activity === 'ON_BREAK') { proposed.siteId = null; proposed.taskId = null; proposed.tripId = null; } if (proposed.siteId) await site(ctx, proposed.siteId); assert(proposed.activity !== 'WORKING' || proposed.siteId, 'VALIDATION_ERROR', { reason: 'WORK_SITE_REQUIRED' }); if (proposed.taskId) { const work = await task(ctx, proposed.taskId); assert(work.data.siteId === proposed.siteId && work.data.assigneeIds.includes(t.data.employeeId), 'ACCESS_DENIED'); } originalSnapshots.push(original); proposedSnapshots.push(proposed); }
    const next = effective.map(s => proposedSnapshots.find(p => p.id === s.id) ?? s); assertTimeline(next, effective); assert(!(await all(ctx, 'timesheet_correction')).some(c => c.data.timesheetId === t.id && c.data.state === 'SUBMITTED' && (c.data.originalSnapshots ?? [c.data.originalSnapshot]).some((s: Data) => originalSnapshots.some(o => o.id === s.id))), 'INVALID_STATE', { reason: 'CORRECTION_ALREADY_PENDING' });
    const result = await ctx.tx.add('timesheet_correction', { timesheetId: t.id, employeeId: t.data.employeeId, segmentIds: originalSnapshots.map(s => s.id), originalSnapshots, proposedSnapshots, reason: input.reason, state: 'SUBMITTED', submittedBy: ctx.actor.userId, submittedAt: ctx.now, closedPeriod: ['APPROVED', 'LOCKED'].includes(t.data.state) }); await ctx.tx.event('timesheet.correction_requested', { correctionId: result.id, timesheetId: t.id, employeeId: t.data.employeeId }); return result;
  }),
  'timesheet.correction.review': command('timesheet.approve', z.object({ correctionId: id, decision: z.enum(['APPROVE', 'DISPUTE']), reason: text }).strict(), async (ctx, input) => {
    const c = await entity(ctx, 'timesheet_correction', input.correctionId); ctx.requireOwn(c.data.employeeId); assert(c.data.employeeId !== ctx.actor.userId && c.data.submittedBy !== ctx.actor.userId, 'ACCESS_DENIED', { reason: 'SELF_APPROVAL_FORBIDDEN' }); assert(c.data.state === 'SUBMITTED', 'INVALID_STATE'); const t = await entity(ctx, 'timesheet', c.data.timesheetId); const effective = await effectiveTimesheet(ctx, t); const originals: Data[] = c.data.originalSnapshots ?? [c.data.originalSnapshot]; const proposals: Data[] = c.data.proposedSnapshots ?? [c.data.proposedSnapshot];
    for (const original of originals) { assert(JSON.stringify(effective.find((s: Data) => s.id === original.id)) === JSON.stringify(original), 'VERSION_CONFLICT', { reason: 'CORRECTION_STALE' }); if (original.siteId) ctx.requireSite(original.siteId); } for (const proposal of proposals) if (proposal.siteId) ctx.requireSite(proposal.siteId);
    const snapshot = effective.map(s => proposals.find(p => p.id === s.id) ?? s); assertTimeline(snapshot, effective); const paidActivities = t.data.paidActivities ?? ['WORKING', 'SERVICE_TASK', 'WAITING_WORK']; const beforeTotals = summary(effective.map(s => ({ data: s } as Entity)), t.data.periodEnd, paidActivities); const totals = summary(snapshot.map(s => ({ data: s } as Entity)), t.data.periodEnd, paidActivities);
    if (input.decision === 'APPROVE') { if (c.data.closedPeriod || ['APPROVED', 'LOCKED'].includes(t.data.state)) { const adjustments = (await all(ctx, 'timesheet_adjustment')).filter(a => a.data.timesheetId === t.id); await ctx.tx.add('timesheet_adjustment', { timesheetId: t.id, employeeId: t.data.employeeId, correctionId: c.id, sequence: adjustments.length + 1, state: 'APPROVED', periodStart: t.data.periodStart, periodEnd: t.data.periodEnd, deltaPayableSeconds: totals.payableSeconds - beforeTotals.payableSeconds, originalSnapshots: originals, proposedSnapshots: proposals, approvedBy: ctx.actor.userId, approvedAt: ctx.now, reason: input.reason }); } else { await ctx.tx.add('timesheet_revision', { timesheetId: t.id, revision: t.data.revision, snapshot: t.data }); await ctx.tx.save(t, { ...t.data, segmentSnapshot: snapshot, totalSeconds: totals.totalSeconds, counters: totals.counters, revision: t.data.revision + 1 }); } }
    const result = await ctx.tx.save(c, { ...c.data, state: input.decision === 'APPROVE' ? 'APPROVED' : 'DISPUTED', reviewedBy: ctx.actor.userId, reviewedAt: ctx.now, reviewReason: input.reason }); await ctx.tx.event('timesheet.correction_reviewed', { correctionId: c.id, state: result.data.state }); return result;
  }),
  'timesheet.summary': command('timesheet.read', z.object({ timesheetId: id }).strict(), async (ctx, input) => { const t = await entity(ctx, 'timesheet', input.timesheetId); ctx.requireOwn(t.data.employeeId); for (const s of t.data.segmentSnapshot) if (s.siteId) ctx.requireSite(s.siteId); return { ...t.data, corrections: (await all(ctx, 'timesheet_correction')).filter(c => c.data.timesheetId === t.id), adjustments: (await all(ctx, 'timesheet_adjustment')).filter(c => c.data.timesheetId === t.id) }; }),
} satisfies CommandRegistry);

function visibleOwn(ctx: CommandContext, employeeId: string): boolean { try { ctx.requireOwn(employeeId); return true; } catch { return false; } }
function visibleSite(ctx: CommandContext, siteId: string): boolean { try { ctx.requireSite(siteId); return true; } catch { return false; } }
function unionDuration(intervals: { startAt: string; endAt: string }[]): number { const sorted = intervals.map(i => [ms(i.startAt), ms(i.endAt)]).sort((a, b) => a[0]! - b[0]!); let seconds = 0, start = 0, end = 0; for (const i of sorted) { if (i[0]! > end) { seconds += Math.max(0, end - start) / 1000; start = i[0]!; end = i[1]!; } else end = Math.max(end, i[1]!); } return seconds + Math.max(0, end - start) / 1000; }
const taskBatchInput = z.object({ batchKey: id, tasks: z.array(taskInput).min(1).max(100) }).strict();
async function taskBatchPreview(ctx: CommandContext, input: Data): Promise<Data> {
  const errors: Data[] = []; for (const [index, work] of input.tasks.entries()) { try { await validateTaskInput(ctx, work); } catch (error) { const code = (error as { code?: string }).code; if (!code || code === 'ACCESS_DENIED') throw error; errors.push({ task: index + 1, code, details: (error as { details?: Data }).details ?? {} }); } }
  const inputHash = createHash('sha256').update(JSON.stringify(input)).digest('hex'); const revisions: Data[] = []; for (const kind of ['site', 'location', 'order', 'user', 'work_package', 'task', 'change_order']) revisions.push({ kind, versions: (await all(ctx, kind)).map(e => [e.id, e.version]).sort() });
  return { batchKey: input.batchKey, inputHash, previewHash: createHash('sha256').update(JSON.stringify({ inputHash, revisions })).digest('hex'), taskCount: input.tasks.length, affectedSiteIds: [...new Set(input.tasks.map((t: Data) => t.siteId))], errors, canCommit: errors.length === 0, sideEffectsExecuted: false };
}
Object.assign(operationsCommands, {
  'task.bulk.preview': command('task.create', taskBatchInput, taskBatchPreview),
  'task.bulk.commit': command('task.create', taskBatchInput.extend({ previewHash: z.string().length(64), confirmed: z.literal(true) }).strict(), async (ctx, input) => {
    const { previewHash, confirmed, ...contents } = input; const inputHash = createHash('sha256').update(JSON.stringify(contents)).digest('hex'); const previous = (await all(ctx, 'task_batch')).find(b => b.data.batchKey === input.batchKey); if (previous) { assert(previous.data.inputHash === inputHash, 'VERSION_CONFLICT', { reason: 'BATCH_KEY_REUSED' }); return Promise.all(previous.data.taskIds.map((taskId: string) => task(ctx, taskId))); }
    const preview = await taskBatchPreview(ctx, contents); assert(preview.canCommit, 'VALIDATION_ERROR', { errors: preview.errors }); assert(preview.previewHash === previewHash, 'VERSION_CONFLICT', { reason: 'STALE_TASK_BATCH_PREVIEW' }); const tasks: Entity[] = []; for (const inputTask of input.tasks) tasks.push(await taskCreate(ctx, inputTask)); await ctx.tx.add('task_batch', { batchKey: input.batchKey, inputHash, previewHash, taskIds: tasks.map(t => t.id), createdBy: ctx.actor.userId, confirmedAt: ctx.now }); await ctx.tx.event('task.batch_created', { batchKey: input.batchKey, taskIds: tasks.map(t => t.id), count: tasks.length }); return tasks;
  }),
  'task.summary': command('task.read', z.object({ taskId: id }).strict(), async (ctx, input) => {
    const t = await task(ctx, input.taskId); const logs = (await all(ctx, 'worklog')).filter(w => w.data.taskId === t.id); const allocations = (await all(ctx, 'work_allocation')).filter(a => a.data.taskId === t.id && visibleOwn(ctx, a.data.employeeId));
    const segs = (await all(ctx, 'time_segment')).filter(s => allocations.some(a => a.data.segmentId === s.id)); const personSeconds = allocations.reduce((sum, a) => sum + a.data.seconds, 0);
    const fullyAllocated = segs.every(s => allocations.filter(a => a.data.segmentId === s.id).reduce((sum, a) => sum + a.data.seconds, 0) === durationSeconds(s, ctx.now)); const relevantIntervals = segs.filter(s => s.data.endAt).map(s => ({ startAt: s.data.startAt, endAt: s.data.endAt })); const acceptedQuantityMilli = t.data.state === 'ACCEPTED' ? t.data.acceptedQuantityMilli : 0;
    return { taskId: t.id, state: t.data.state, unit: t.data.unit, plannedQuantityMilli: t.data.plannedQuantityMilli, reportedQuantityMilli: t.data.reportedQuantityMilli, acceptedQuantityMilli, remainingQuantityMilli: Math.max(0, t.data.plannedQuantityMilli - acceptedQuantityMilli), personSeconds, chronologicalWorkSeconds: fullyAllocated ? unionDuration(relevantIntervals) : null, productivityQuantityMilliPerPersonHour: personSeconds > 0 ? acceptedQuantityMilli * 3600 / personSeconds : null, formula: 'single accepted task quantity / allocated person-hours; duration is union of source intervals; accessible employee scope only', worklogIds: logs.map(w => w.id), allocationIds: allocations.map(a => a.id), segmentIds: segs.map(s => s.id), reviewIds: (await all(ctx, 'task_review')).filter(r => r.data.taskId === t.id).map(r => r.id), defectIds: (await all(ctx, 'defect')).filter(d => d.data.taskId === t.id).map(d => d.id) };
  }),
  'operations.statistics': command('operations.read', z.object({ periodStart: timestamp, periodEnd: timestamp, siteId: id.optional(), employeeId: id.optional(), completionKind: completionKind.optional() }).strict(), async (ctx, input) => {
    assert(ms(input.periodStart) < ms(input.periodEnd), 'VALIDATION_ERROR'); if (input.siteId) await site(ctx, input.siteId); if (input.employeeId) ctx.requireOwn(input.employeeId);
    const segs = (await all(ctx, 'time_segment')).filter(s => visibleOwn(ctx, s.data.employeeId) && (!s.data.siteId || visibleSite(ctx, s.data.siteId)) && (!input.siteId || s.data.siteId === input.siteId) && (!input.employeeId || s.data.employeeId === input.employeeId) && ms(s.data.startAt) < ms(input.periodEnd) && ms(s.data.endAt ?? ctx.now) > ms(input.periodStart)).map(s => ({ ...s, data: { ...s.data, startAt: new Date(Math.max(ms(s.data.startAt), ms(input.periodStart))).toISOString(), endAt: new Date(Math.min(ms(s.data.endAt ?? ctx.now), ms(input.periodEnd))).toISOString() } }));
    const tasks = (await all(ctx, 'task')).filter(t => visibleSite(ctx, t.data.siteId) && (!input.siteId || t.data.siteId === input.siteId) && (!input.completionKind || t.data.completionKind === input.completionKind) && (!input.employeeId || t.data.assigneeIds.includes(input.employeeId)));
    const byUnit: Data = {}; for (const t of tasks) { const unit = byUnit[t.data.unit] ??= { plannedQuantityMilli: 0, reportedQuantityMilli: 0, acceptedQuantityMilli: 0, taskIds: [] }; unit.plannedQuantityMilli += t.data.plannedQuantityMilli; unit.reportedQuantityMilli += t.data.reportedQuantityMilli; unit.acceptedQuantityMilli += t.data.state === 'ACCEPTED' ? t.data.acceptedQuantityMilli : 0; unit.taskIds.push(t.id); }
    const trips = (await all(ctx, 'trip')).filter(t => visibleOwn(ctx, t.data.employeeId) && (!input.employeeId || t.data.employeeId === input.employeeId) && (!input.siteId || t.data.origin?.id === input.siteId || t.data.destination?.id === input.siteId) && ms(t.data.startAt) < ms(input.periodEnd) && ms(t.data.endAt ?? ctx.now) > ms(input.periodStart));
    return { periodStart: utc(input.periodStart), periodEnd: utc(input.periodEnd), ...summary(segs, ctx.now), payableSeconds: null, totalMinutes: null, remainderSeconds: null, byUnit, overdueTaskIds: tasks.filter(t => t.data.dueAt && ms(t.data.dueAt) < ms(ctx.now) && !['ACCEPTED', 'CANCELLED'].includes(t.data.state)).map(t => t.id), openDefects: (await all(ctx, 'defect')).filter(d => tasks.some(t => t.id === d.data.taskId) && d.data.state !== 'CLOSED').map(d => ({ id: d.id, taskId: d.data.taskId, ageSeconds: Math.floor((ms(ctx.now) - ms(d.createdAt)) / 1000) })), trips: { count: trips.length, approvedPaidSeconds: trips.reduce((sum, t) => sum + (t.data.paidSeconds ?? 0), 0), incompleteIds: trips.filter(t => t.data.state === 'IN_PROGRESS').map(t => t.id), distanceSource: 'PER_TRIP_EXPLICIT_ONLY', ids: trips.map(t => t.id) }, segmentIds: segs.map(s => s.id), payability: 'APPROVED_TIMESHEETS_ONLY; THESE_ARE_RECORDED_FACTS', formula: 'clipped UTC interval sums; atomic task quantities by compatible unit; no AI discipline scores' };
  }),
} satisfies CommandRegistry);

const tripTime = z.object({ tripId: id, occurredAt: timestamp.optional() }).strict();
const geofenceSchema = z.object({ siteId: id, latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), radiusEnterM: z.number().positive().max(10000), radiusExitM: z.number().positive().max(20000), dwellSeconds: z.number().int().min(30).max(3600), maxAccuracyM: z.number().positive().max(1000), maxPointAgeSeconds: z.number().int().min(10).max(3600), autoReturn: z.boolean().default(false), autoPause: z.boolean().default(false), exceptionZones: z.array(z.object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), radiusM: z.number().positive().max(10000), reason: text }).strict()).max(30).default([]) }).strict();
const presenceInput = z.object({ eventId: id, deviceId: id, shiftId: id, siteId: id, sequenceNumber: quantity, observedAt: timestamp, accuracyM: z.number().positive().max(100000).optional(), distanceM: z.number().nonnegative().max(20000000).optional(), zoneDistances: z.array(z.object({ zoneIndex: z.number().int().min(0).max(29), distanceM: z.number().nonnegative().max(20000000), accuracyM: z.number().positive().max(100000).optional() }).strict()).max(30).default([]), source: z.enum(['NATIVE_GEOFENCE', 'NATIVE_LOCATION']), trackerState: z.enum(['ONLINE', 'STALE', 'OFFLINE', 'PERMISSION_DENIED', 'PAUSED']).default('ONLINE'), policyVersionId: id }).strict();
async function ownTrip(ctx: CommandContext, tripId: string): Promise<{ t: Entity; s: Entity }> { const t = await entity(ctx, 'trip', tripId); const s = await shift(ctx, t.data.shiftId); assert(t.data.employeeId === s.data.employeeId, 'INVALID_STATE'); return { t, s }; }
async function activePolicy(ctx: CommandContext, policyVersionId: string, eventAt?: string): Promise<Entity> { const policies = await all(ctx, 'tracking_policy'); assert(policies.some(p => p.data.approvedAt), 'MISSING_CONFIGURATION', { reason: 'GPS_LEGAL_GATE_CLOSED' }); const p = await entity(ctx, 'tracking_policy', policyVersionId); const at = ms(eventAt ?? ctx.now); const closedAt = p.data.disabledAt ?? p.data.supersededAt; assert(p.data.approvedAt && at >= ms(p.data.approvedAt) && at < ms(p.data.expiresAt) && (!closedAt || at < ms(closedAt)) && (p.data.enabled || !!closedAt), 'MISSING_CONFIGURATION', { reason: 'GPS_POLICY_NOT_AUTHORIZED_AT_EVENT_TIME' }); assert(ms(ctx.now) - at < p.data.retentionDays * 86400_000, 'ACCESS_DENIED', { reason: 'GPS_RETENTION_EXPIRED' }); return p; }
Object.assign(operationsCommands, {
  'trip.start': command('trip.manage', z.object({ shiftId: id, destination, purpose: text, occurredAt: timestamp.optional(), transportMode: z.enum(['CAR', 'PUBLIC_TRANSPORT', 'WALK', 'BICYCLE', 'OTHER']).default('OTHER'), passengerRole: z.enum(['DRIVER', 'PASSENGER', 'NONE']).default('NONE'), vehicleTripId: id.optional(), materialRequestId: id.optional() }).strict(), async (ctx, input) => { const s = await shift(ctx, input.shiftId); assert(s.data.employeeId === ctx.actor.userId, 'ACCESS_DENIED'); assert(['WORKING', 'AWAY_PENDING_REASON', 'SERVICE_TASK', 'WAITING_WORK'].includes(s.data.activity) && s.data.state === 'ACTIVE', 'INVALID_STATE'); assert(!(await all(ctx, 'trip')).some(t => t.data.shiftId === s.id && t.data.state === 'IN_PROGRESS'), 'INVALID_STATE', { reason: 'ACTIVE_TRIP_EXISTS' }); await validateDestination(ctx, input.destination); if (input.materialRequestId) { const req = await entity(ctx, 'material_request', input.materialRequestId); assert(req.data.employeeId === s.data.employeeId || req.data.requestedBy === s.data.employeeId, 'ACCESS_DENIED'); } if (input.vehicleTripId) await entity(ctx, 'vehicle_trip', input.vehicleTripId); const at = occurred(ctx, input.occurredAt); const t = await ctx.tx.add('trip', { ...input, employeeId: s.data.employeeId, origin: { kind: 'SITE', id: s.data.siteId }, state: 'IN_PROGRESS', approvalState: 'DRAFT', startAt: at, endAt: null, arrivalAt: null, routeAvailability: 'UNKNOWN', distanceMeters: null, distanceSource: 'UNKNOWN', source: 'MANUAL', siteId: s.data.siteId }); await changeActivity(ctx, s, { activity: 'TRAVELLING', siteId: s.data.siteId, tripId: t.id, occurredAt: at, reason: input.purpose }); await ctx.tx.event('trip.started', { tripId: t.id, employeeId: s.data.employeeId, shiftId: s.id, destination: input.destination }); return t; }),
  'trip.destination': command('trip.manage', tripTime.extend({ destination, reason: text }).strict(), async (ctx, input) => { const { t, s } = await ownTrip(ctx, input.tripId); assert(t.data.state === 'IN_PROGRESS' && s.data.employeeId === ctx.actor.userId, 'ACCESS_DENIED'); await validateDestination(ctx, input.destination); const at = occurred(ctx, input.occurredAt); await ctx.tx.add('trip_event', { tripId: t.id, type: 'DESTINATION_CHANGED', occurredAt: at, receivedAt: ctx.now, oldDestination: t.data.destination, destination: input.destination, reason: input.reason, actorId: ctx.actor.userId }); return ctx.tx.save(t, { ...t.data, destination: input.destination }, ctx.expectedVersion); }),
  'trip.stop': command('trip.manage', tripTime.extend({ kind: z.enum(['PRIVATE_BREAK', 'SERVICE_TASK', 'WAITING_WORK']), reason: text }).strict(), async (ctx, input) => { const { t, s } = await ownTrip(ctx, input.tripId); assert(t.data.state === 'IN_PROGRESS' && s.data.activity === 'TRAVELLING' && s.data.employeeId === ctx.actor.userId, 'INVALID_STATE'); const at = occurred(ctx, input.occurredAt); await ctx.tx.add('trip_event', { tripId: t.id, type: 'STOP', kind: input.kind, reason: input.reason, occurredAt: at, actorId: ctx.actor.userId }); return changeActivity(ctx, s, { activity: input.kind === 'PRIVATE_BREAK' ? 'ON_BREAK' : input.kind, siteId: s.data.siteId, tripId: t.id, occurredAt: at, reason: input.reason }, 'MANUAL', false); }),
  'trip.resume': command('trip.manage', tripTime, async (ctx, input) => { const { t, s } = await ownTrip(ctx, input.tripId); assert(t.data.state === 'IN_PROGRESS' && ['ON_BREAK', 'SERVICE_TASK', 'WAITING_WORK'].includes(s.data.activity) && s.data.employeeId === ctx.actor.userId, 'INVALID_STATE'); await ctx.tx.add('trip_event', { tripId: t.id, type: 'RESUMED', occurredAt: occurred(ctx, input.occurredAt), actorId: ctx.actor.userId }); return changeActivity(ctx, s, { activity: 'TRAVELLING', siteId: s.data.siteId, tripId: t.id, occurredAt: input.occurredAt, reason: t.data.purpose }, 'MANUAL', false); }),
  'trip.arrive': command('trip.manage', tripTime.extend({ startWork: z.boolean().default(false), taskId: id.optional() }).strict(), async (ctx, input) => { const { t, s } = await ownTrip(ctx, input.tripId); assert(t.data.state === 'IN_PROGRESS' && s.data.activity === 'TRAVELLING' && s.data.employeeId === ctx.actor.userId, 'INVALID_STATE'); const at = occurred(ctx, input.occurredAt); assert(!input.startWork || t.data.destination.kind === 'SITE', 'VALIDATION_ERROR', { reason: 'NON_SITE_DESTINATION' }); await validateDestination(ctx, t.data.destination); await changeActivity(ctx, s, { activity: input.startWork ? 'WORKING' : 'WAITING_WORK', siteId: t.data.destination.kind === 'SITE' ? t.data.destination.id : s.data.siteId, taskId: input.taskId, occurredAt: at, reason: 'ARRIVAL_CONFIRMED_BY_EMPLOYEE' }, 'MANUAL', false); const result = await endTrip(ctx, t, at, 'ARRIVED'); await ctx.tx.event('trip.arrival_confirmed', { tripId: t.id, employeeId: t.data.employeeId, occurredAt: at }); return result; }),
  'trip.end': command('trip.manage', tripTime.extend({ reason: text, nextActivity: z.enum(['AWAY_PENDING_REASON', 'SERVICE_TASK', 'WAITING_WORK', 'ON_BREAK']).default('AWAY_PENDING_REASON') }).strict(), async (ctx, input) => { const { t, s } = await ownTrip(ctx, input.tripId); assert(t.data.employeeId === ctx.actor.userId && t.data.state === 'IN_PROGRESS', 'INVALID_STATE'); const at = occurred(ctx, input.occurredAt); await changeActivity(ctx, s, { activity: input.nextActivity, siteId: s.data.siteId, occurredAt: at, reason: input.reason }, 'MANUAL', false); return endTrip(ctx, t, at, 'ENDED_WITHOUT_ARRIVAL', input.reason); }),
  'trip.approve': command('trip.approve', z.object({ tripId: id, decision: z.enum(['APPROVE', 'DISPUTE']), reason: text, paid: z.boolean().default(false), clientBillable: z.boolean().default(false), contractApprovalId: id.optional() }).strict(), async (ctx, input) => { const { t, s } = await ownTrip(ctx, input.tripId); assert(t.data.employeeId !== ctx.actor.userId && t.data.state !== 'IN_PROGRESS', 'ACCESS_DENIED', { reason: 'SELF_APPROVAL_OR_ACTIVE_TRIP' }); if (input.clientBillable) { assert(input.contractApprovalId, 'NEEDS_APPROVAL', { reason: 'CLIENT_BILLING_REQUIRES_CONTRACT' }); const co = await entity(ctx, 'change_order', input.contractApprovalId); assert(['ACCEPTED', 'APPROVED'].includes(co.data.state ?? co.data.status) && (!co.data.siteId || co.data.siteId === t.data.siteId), 'NEEDS_APPROVAL'); } const segs = (await segments(ctx, s.id)).filter(seg => seg.data.tripId === t.id); const totals = summary(segs, t.data.endAt, input.paid ? ['TRAVELLING', 'SERVICE_TASK', 'WAITING_WORK'] : []); await ctx.tx.add('trip_approval', { tripId: t.id, employeeId: t.data.employeeId, ...input, approvedBy: ctx.actor.userId, approvedAt: ctx.now, totals, snapshot: t.data }); return ctx.tx.save(t, { ...t.data, approvalState: input.decision === 'APPROVE' ? 'APPROVED' : 'DISPUTED', paidSeconds: input.decision === 'APPROVE' ? totals.payableSeconds : null, clientBillable: input.clientBillable, contractApprovalId: input.contractApprovalId ?? null }, ctx.expectedVersion); }),
  'tracking_policy.create': command('location.policy.manage', z.object({ purpose: text, retentionDays: z.number().int().min(1).max(90), maxSessionHours: z.number().int().min(1).max(16).default(12), allowPresence: z.boolean().default(true), allowBusinessRoute: z.boolean().default(false), allowMinimalReturn: z.boolean().default(false), accessRoles: z.array(shortText).min(1).max(30), externalApprovalReferences: z.array(shortText).max(30).default([]) }).strict(), async (ctx, input) => { const revisions = await all(ctx, 'tracking_policy'); return ctx.tx.add('tracking_policy', { ...input, revision: revisions.length + 1, enabled: false, state: 'DRAFT', createdBy: ctx.actor.userId, createdAt: ctx.now }); }),
  'tracking_policy.approve': command('location.policy.manage', z.object({ policyId: id, legalApprovalReference: text, necessityApprovalReference: text, worksCouncilReference: text, employeeNoticeReference: text, expiresAt: timestamp, enabled: z.literal(true) }).strict(), async (ctx, input) => { assert(ctx.actor.roles.includes('OWNER') && ctx.actor.mfaVerified, 'NEEDS_REAUTH'); const p = await entity(ctx, 'tracking_policy', input.policyId); assert(p.data.state === 'DRAFT' && ms(input.expiresAt) > ms(ctx.now), 'INVALID_STATE'); for (const [reference, subject] of [[input.legalApprovalReference, 'GPS_LEGAL_PROCESS'], [input.necessityApprovalReference, 'GPS_NECESSITY'], [input.worksCouncilReference, 'GPS_WORKS_COUNCIL'], [input.employeeNoticeReference, 'GPS_EMPLOYEE_NOTICE']]) { const approval = await entity(ctx, 'legal_approval', reference); if (approval.data.testOnly) { const company = await entity(ctx, 'company', ctx.actor.companyId); assert(['TEST', 'DEMO'].includes(company.data.operatingMode), 'NEEDS_APPROVAL', { reason: 'SYNTHETIC_APPROVAL_PRODUCTION_FORBIDDEN' }); } assert(approval.data.status === 'APPROVED' && approval.data.active !== false && approval.data.subject === subject && (!approval.data.expiresAt || ms(approval.data.expiresAt) >= ms(input.expiresAt)), 'NEEDS_APPROVAL', { subject }); } for (const previous of (await all(ctx, 'tracking_policy')).filter(e => e.data.enabled)) await ctx.tx.save(previous, { ...previous.data, enabled: false, state: 'SUPERSEDED', supersededAt: ctx.now }); const result = await ctx.tx.save(p, { ...p.data, ...input, state: 'APPROVED', approvedBy: ctx.actor.userId, approvedAt: ctx.now, expiresAt: utc(input.expiresAt) }, ctx.expectedVersion); await ctx.tx.event('tracking.policy_approved', { policyVersionId: p.id, revision: p.data.revision, enabled: true }); return result; }, true),
  'tracking_policy.disable': command('location.policy.manage', z.object({ policyId: id, reason: text }).strict(), async (ctx, input) => { const p = await entity(ctx, 'tracking_policy', input.policyId); await ctx.tx.event('tracking.stop_all', { reason: input.reason, policyId: p.id }); return ctx.tx.save(p, { ...p.data, enabled: false, state: 'DISABLED', disabledBy: ctx.actor.userId, disabledAt: ctx.now, reason: input.reason }, ctx.expectedVersion); }),
  'device.enroll': command('device.manage', z.object({ employeeId: id, expiresInMinutes: z.number().int().min(1).max(60).default(10) }).strict(), async (ctx, input) => { ctx.requireOwn(input.employeeId); await employee(ctx, input.employeeId); const token = randomBytes(24).toString('base64url'); const e = await ctx.tx.add('device_enrollment', { employeeId: input.employeeId, tokenHash: createHash('sha256').update(token).digest('hex'), expiresAt: new Date(ms(ctx.now) + input.expiresInMinutes * 60_000).toISOString(), consumedAt: null, createdBy: ctx.actor.userId }); return { enrollmentId: e.id, token, expiresAt: e.data.expiresAt }; }),
  'device.bind': command('device.self', z.object({ enrollmentId: id, token: z.string().min(20).max(100), platform: z.enum(['ANDROID', 'IOS']), deviceName: shortText, publicKey: z.string().min(20).max(4000) }).strict(), async (ctx, input) => { const e = await entity(ctx, 'device_enrollment', input.enrollmentId); assert(e.data.employeeId === ctx.actor.userId && !e.data.consumedAt && ms(e.data.expiresAt) > ms(ctx.now) && createHash('sha256').update(input.token).digest('hex') === e.data.tokenHash, 'ACCESS_DENIED'); for (const old of (await all(ctx, 'device')).filter(d => d.data.employeeId === e.data.employeeId && d.data.active)) { await ctx.tx.save(old, { ...old.data, active: false, revokedAt: ctx.now, revocationReason: 'REPLACED' }); await ctx.tx.event('device.revoked', { deviceId: old.id }); } const d = await ctx.tx.add('device', { employeeId: e.data.employeeId, platform: input.platform, deviceName: input.deviceName, publicKey: input.publicKey, active: true, boundAt: ctx.now }); await ctx.tx.save(e, { ...e.data, consumedAt: ctx.now, deviceId: d.id }); for (const s of (await all(ctx, 'shift')).filter(s => s.data.employeeId === e.data.employeeId && s.data.state === 'ACTIVE')) await ctx.tx.save(s, { ...s.data, deviceId: d.id }); await ctx.tx.event('device.bound', { deviceId: d.id, employeeId: d.data.employeeId }); return d; }),
  'device.revoke': command('device.manage', z.object({ deviceId: id, reason: text }).strict(), async (ctx, input) => { const d = await entity(ctx, 'device', input.deviceId); ctx.requireOwn(d.data.employeeId); const result = await ctx.tx.save(d, { ...d.data, active: false, revokedAt: ctx.now, revocationReason: input.reason }, ctx.expectedVersion); await ctx.tx.event('device.revoked', { deviceId: d.id }); return result; }),
  'geofence.configure': command('location.policy.manage', geofenceSchema, async (ctx, input) => { const s = await site(ctx, input.siteId); assert(input.radiusEnterM < input.radiusExitM && !(input.latitude === 0 && input.longitude === 0), 'VALIDATION_ERROR'); const versions = (await all(ctx, 'geofence')).filter(g => g.data.siteId === s.id); const g = await ctx.tx.add('geofence', { ...input, revision: versions.length + 1, configuredBy: ctx.actor.userId }); await ctx.tx.save(s, { ...s.data, geofenceVersionId: g.id, geofenceRevision: g.data.revision }, ctx.expectedVersion); await ctx.tx.event('geofence.configured', { siteId: s.id, geofenceVersionId: g.id }); return g; }, true),
  'presence.ingest': command('location.self', presenceInput, async (ctx, input) => {
    const s = await shift(ctx, input.shiftId); assert(s.data.employeeId === ctx.actor.userId, 'ACCESS_DENIED'); await trackingDevice(ctx, input.deviceId, s); const policy = await activePolicy(ctx, input.policyVersionId, input.observedAt); assert(policy.data.allowPresence, 'ACCESS_DENIED'); const selected = await site(ctx, input.siteId); const currentTrip = (await all(ctx, 'trip')).find(t => t.data.shiftId === s.id && t.data.state === 'IN_PROGRESS'); assert(s.data.siteId === selected.id || (s.data.activity === 'TRAVELLING' && currentTrip?.data.destination.kind === 'SITE' && currentTrip.data.destination.id === selected.id), 'INVALID_STATE', { reason: 'AMBIGUOUS_OR_UNASSIGNED_SITE' }); assert(selected.data.geofenceVersionId, 'MISSING_CONFIGURATION'); const g = await entity(ctx, 'geofence', selected.data.geofenceVersionId); const at = occurred(ctx, input.observedAt);
    const priorEvent = (await all(ctx, 'presence_event')).find(e => e.data.eventId === input.eventId); if (priorEvent) { assert(priorEvent.data.employeeId === s.data.employeeId && priorEvent.data.deviceId === input.deviceId, 'ACCESS_DENIED'); return priorEvent; }
    const segs = await segments(ctx, s.id); const eventSegment = segs.find(seg => ms(at) >= ms(seg.data.startAt) && ms(at) < (seg.data.endAt ? ms(seg.data.endAt) : ms(ctx.now) + 1)); assert(eventSegment && eventSegment.data.activity !== 'ON_BREAK', 'ACCESS_DENIED', { reason: 'PRIVATE_OR_OFF_DUTY_EVENT_TIME' }); assert(ms(at) - ms(s.data.startAt) <= policy.data.maxSessionHours * 3600_000, 'ACCESS_DENIED', { reason: 'TRACKING_LEASE_EXPIRED' }); assert(eventSegment.data.activity !== 'AWAY_PENDING_REASON' || policy.data.allowMinimalReturn, 'ACCESS_DENIED', { reason: 'MINIMAL_RETURN_NOT_APPROVED' });
    const presenceId = `${s.id}:${selected.id}`; let p = (await all(ctx, 'presence')).find(p => p.id === presenceId); const stale = ms(ctx.now) - ms(at) > g.data.maxPointAgeSeconds * 1000; const usable = !stale && input.trackerState === 'ONLINE' && input.accuracyM !== undefined && input.accuracyM <= g.data.maxAccuracyM && input.distanceM !== undefined;
    let candidate = 'UNKNOWN'; if (usable) { assert(new Set(input.zoneDistances.map((d: Data) => d.zoneIndex)).size === input.zoneDistances.length && input.zoneDistances.every((d: Data) => d.zoneIndex < (g.data.exceptionZones ?? []).length), 'VALIDATION_ERROR', { reason: 'INVALID_ZONE_DISTANCE' }); const zones: Data[] = g.data.exceptionZones ?? []; const exceptionInside = zones.some((zone: Data, index: number) => { const distance = input.zoneDistances.find((d: Data) => d.zoneIndex === index); const accuracy = distance?.accuracyM ?? input.accuracyM; return distance && accuracy <= g.data.maxAccuracyM && distance.distanceM + accuracy < zone.radiusM; }); const allExceptionsOutside = zones.every((zone: Data, index: number) => { const distance = input.zoneDistances.find((d: Data) => d.zoneIndex === index); const accuracy = distance?.accuracyM ?? input.accuracyM; return distance && accuracy <= g.data.maxAccuracyM && distance.distanceM - accuracy > zone.radiusM + (g.data.radiusExitM - g.data.radiusEnterM); }); if (input.distanceM + input.accuracyM < g.data.radiusEnterM || exceptionInside) candidate = 'INSIDE'; else if (input.distanceM - input.accuracyM > g.data.radiusExitM && allExceptionsOutside) candidate = 'OUTSIDE'; else candidate = 'UNCERTAIN'; }
    const late = !!p && (ms(at) <= ms(p.data.lastObservedAt) || input.sequenceNumber <= p.data.lastSequenceNumber); const event = await ctx.tx.add('presence_event', { ...input, employeeId: s.data.employeeId, receivedAt: utc(ctx.now), geofenceVersionId: g.id, candidate, usable, late, stale, correctionRequired: late || s.data.state !== 'ACTIVE' }, input.eventId);
    if (late || s.data.state !== 'ACTIVE') return event;
    const previousState = p?.data.state ?? 'UNKNOWN'; const same = p?.data.candidate === candidate && p.data.geofenceVersionId === g.id; const candidateSince = same ? p!.data.candidateSince : at; const candidateCount = same ? p!.data.candidateCount + 1 : 1; const confirmed = usable && ['INSIDE', 'OUTSIDE'].includes(candidate) && candidateCount >= 2 && ms(at) - ms(candidateSince) >= g.data.dwellSeconds * 1000;
    const state = stale || input.trackerState !== 'ONLINE' ? 'UNKNOWN' : confirmed ? candidate : previousState; const data = { shiftId: s.id, employeeId: s.data.employeeId, siteId: selected.id, deviceId: input.deviceId, state, trackerState: stale ? 'STALE' : input.trackerState, candidate, candidateSince, candidateCount, lastObservedAt: at, lastReceivedAt: utc(ctx.now), lastSequenceNumber: input.sequenceNumber, geofenceVersionId: g.id, policyVersionId: policy.id, confirmedAt: confirmed ? at : p?.data.confirmedAt ?? null };
    p = p ? await ctx.tx.save(p, data) : await ctx.tx.add('presence', data, presenceId);
    if (confirmed && state !== previousState) { await ctx.tx.event('presence.confirmed', { presenceId: p.id, shiftId: s.id, siteId: selected.id, state, observedAt: candidateSince, confirmedAt: at, receivedAt: ctx.now, geofenceVersionId: g.id, policyVersionId: policy.id }); const current = await entity(ctx, 'time_segment', s.data.activeSegmentId); if (ms(at) < ms(current.data.startAt)) { await ctx.tx.add('location_incident', { shiftId: s.id, eventId: event.id, reason: 'LATE_EVENT_REQUIRES_CORRECTION', occurredAt: at }); return { presence: p, event, correctionRequired: true }; }
      if (state === 'OUTSIDE' && s.data.activity === 'WORKING' && g.data.autoPause) { await changeActivity(ctx, s, { activity: 'AWAY_PENDING_REASON', siteId: selected.id, pausedTaskId: current.data.taskId, occurredAt: at, reason: 'GEOFENCE_EXIT' }, 'GEOFENCE', false); await ctx.tx.add('location_incident', { shiftId: s.id, employeeId: s.data.employeeId, siteId: selected.id, state: 'OPEN', reason: 'GEOFENCE_EXIT', observedAt: candidateSince, confirmedAt: at, receivedAt: ctx.now, geofenceVersionId: g.id, policyVersionId: policy.id }); await ctx.tx.event('absence.explanation_requested', { shiftId: s.id, employeeId: s.data.employeeId, siteId: selected.id, actions: ['TRIP', 'BREAK', 'SERVICE_TASK', 'GPS_ERROR', 'END_SHIFT'] }); }
      if (state === 'INSIDE' && s.data.activity === 'AWAY_PENDING_REASON' && current.data.source === 'GEOFENCE' && current.data.reason === 'GEOFENCE_EXIT' && current.data.siteId === selected.id && g.data.autoReturn && policy.data.allowMinimalReturn) { let resumeTaskId = current.data.pausedTaskId ?? undefined; if (resumeTaskId) { const priorTask = await task(ctx, resumeTaskId); if (['ACCEPTED', 'CANCELLED'].includes(priorTask.data.state) || !priorTask.data.assigneeIds.includes(s.data.employeeId)) resumeTaskId = undefined; } await changeActivity(ctx, s, { activity: 'WORKING', siteId: selected.id, taskId: resumeTaskId, occurredAt: at, reason: 'GEOFENCE_RETURN' }, 'GEOFENCE', false); await ctx.tx.event('absence.reminder_cancelled', { shiftId: s.id, reason: 'RETURN_CONFIRMED' }); }
      if (state === 'INSIDE' && s.data.activity === 'TRAVELLING') { const trip = (await all(ctx, 'trip')).find(t => t.data.shiftId === s.id && t.data.state === 'IN_PROGRESS'); if (trip?.data.destination.id === selected.id) await ctx.tx.event('trip.arrival_confirmation_requested', { tripId: trip.id, employeeId: s.data.employeeId }); }
    }
    return { presence: p, event };
  }),
  'absence.explain': command('shift.manage', z.object({ segmentId: id, explanation: text, proposedActivity: z.enum(['WORKING', 'SERVICE_TASK', 'WAITING_WORK', 'ON_BREAK', 'TRAVELLING']), gpsError: z.boolean().default(false) }).strict(), async (ctx, input) => { const seg = await entity(ctx, 'time_segment', input.segmentId); const s = await shift(ctx, seg.data.shiftId); assert(s.data.employeeId === ctx.actor.userId && seg.data.activity === 'AWAY_PENDING_REASON', 'ACCESS_DENIED'); const e = await ctx.tx.add('absence_explanation', { ...input, employeeId: s.data.employeeId, siteId: seg.data.siteId, shiftId: s.id, state: 'SUBMITTED', submittedBy: ctx.actor.userId, submittedAt: ctx.now, originalSnapshot: seg.data }); await ctx.tx.event('absence.reminder_cancelled', { shiftId: s.id, explanationId: e.id }); return e; }),
  'absence.review': command('timesheet.approve', z.object({ explanationId: id, decision: z.enum(['APPROVE', 'DISPUTE']), reason: text }).strict(), async (ctx, input) => { const e = await entity(ctx, 'absence_explanation', input.explanationId); const s = await shift(ctx, e.data.shiftId); assert(e.data.employeeId !== ctx.actor.userId && e.data.state === 'SUBMITTED', 'ACCESS_DENIED'); if (e.data.siteId) ctx.requireSite(e.data.siteId); const result = await ctx.tx.save(e, { ...e.data, state: input.decision === 'APPROVE' ? 'APPROVED' : 'DISPUTED', reviewedBy: ctx.actor.userId, reviewedAt: ctx.now, reviewReason: input.reason }, ctx.expectedVersion); await ctx.tx.event('absence.reviewed', { explanationId: e.id, shiftId: s.id, state: result.data.state, proposedActivity: e.data.proposedActivity, requiresTimesheetCorrection: true }); return result; }),
  'trip.sample': command('location.self', z.object({ eventId: id, deviceId: id, shiftId: id, tripId: id, sequenceNumber: quantity, observedAt: timestamp, latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), accuracyM: z.number().positive().max(100000), policyVersionId: id }).strict(), async (ctx, input) => {
    const { t, s } = await ownTrip(ctx, input.tripId); assert(s.id === input.shiftId && t.data.employeeId === ctx.actor.userId, 'ACCESS_DENIED');
    await trackingDevice(ctx, input.deviceId, s); const policy = await activePolicy(ctx, input.policyVersionId, input.observedAt);
    assert(policy.data.allowBusinessRoute, 'ACCESS_DENIED', { reason: 'ROUTE_TRACKING_NOT_APPROVED' });
    const at = occurred(ctx, input.observedAt), expiresAt = new Date(ms(at) + policy.data.retentionDays * 86400_000).toISOString();
    assert(!(input.latitude === 0 && input.longitude === 0) && ms(ctx.now) < ms(expiresAt), 'VALIDATION_ERROR', { reason: 'INVALID_OR_EXPIRED_SAMPLE' });
    assert(ms(at) - ms(s.data.startAt) <= policy.data.maxSessionHours * 3600_000, 'ACCESS_DENIED', { reason: 'TRACKING_LEASE_EXPIRED' });
    const segs = await segments(ctx, s.id), seg = segs.find(seg => ms(at) >= ms(seg.data.startAt) && ms(at) < (seg.data.endAt ? ms(seg.data.endAt) : ms(ctx.now) + 1));
    assert(seg?.data.activity === 'TRAVELLING' && seg.data.tripId === t.id, 'ACCESS_DENIED', { reason: 'PRIVATE_OR_OFF_DUTY_EVENT_TIME' });
    const acknowledgement = (sample: Entity) => ({ eventId: sample.data.eventId, sampleId: sample.id, accepted: true, expiresAt: sample.data.expiresAt });
    const existing = (await all(ctx, 'location_sample')).find(e => e.data.eventId === input.eventId);
    if (existing) {
      assert(existing.data.employeeId === s.data.employeeId && existing.data.deviceId === input.deviceId && existing.data.shiftId === s.id && existing.data.tripId === t.id, 'ACCESS_DENIED');
      assert(ms(ctx.now) < ms(existing.data.expiresAt), 'ACCESS_DENIED', { reason: 'GPS_RETENTION_EXPIRED' });
      return acknowledgement(existing);
    }
    const siteIds = [...new Set([t.data.origin?.kind === 'SITE' ? t.data.origin.id : null, t.data.destination?.kind === 'SITE' ? t.data.destination.id : null, seg.data.siteId].filter((siteId): siteId is string => typeof siteId === 'string' && siteId.trim().length > 0))];
    // The persistence adapter stores coordinates separately under TTL; this entity keeps a permanent deduplication tombstone.
    const sample = await ctx.tx.add('location_sample', { ...input, employeeId: s.data.employeeId, siteIds, receivedAt: utc(ctx.now), mode: 'BUSINESS_TRAVEL', expiresAt, quality: input.accuracyM > 100 ? 'UNCERTAIN' : 'USABLE', source: 'DEVICE_GPS', isEvidenceOfPerson: false }, input.eventId);
    if (t.data.routeAvailability === 'UNKNOWN') await ctx.tx.save(t, { ...t.data, routeAvailability: 'PARTIAL', distanceSource: 'UNKNOWN', distanceMeters: null });
    return acknowledgement(sample);
  }),
} satisfies CommandRegistry);

operationsCommands['task_template.generate_due']=command('task.create',z.object({templateId:id,templateVersion:z.number().int().positive()}).strict(),async(ctx,input)=>{
 const template=await entity(ctx,'task_template',input.templateId);await site(ctx,template.data.task.siteId);
 assert(template.version===input.templateVersion&&(ctx.expectedVersion===undefined||ctx.expectedVersion===template.version),'VERSION_CONFLICT',{reason:'CALENDAR_TEMPLATE_CHANGED'});
 assert(template.data.scheduleOwnerId===ctx.actor.userId,'ACCESS_DENIED');
 const cursorId=createHash('sha256').update(JSON.stringify(['task-calendar',template.id,template.data.revision])).digest('hex');
 const cursors=await all(ctx,'task_calendar_cursor'),previous=cursors.find(c=>c.id===cursorId);
 const existingKeys=new Set((await all(ctx,'task_occurrence')).filter(o=>o.data.templateId===template.id).map(o=>taskOccurrenceKey(template.id,o.data.scheduledPeriod,o.data.locationId)));
 const plan=planTaskCalendar({templateId:template.id,recurrence:template.data.recurrence,active:template.data.active===true,activatedAt:template.data.activatedAt,schedule:template.data.schedule??undefined,now:ctx.now,locationId:template.data.task.locationId,afterPeriod:previous?.data.cursor,existingKeys,maxOccurrences:25,maxScannedPeriods:1000});
 const created=[];const occurrence=operationsCommands['task_template.occurrence']!;
 for(const period of plan.occurrences){const data=occurrence.schema.parse({templateId:template.id,scheduledPeriod:period.scheduledPeriod,locationId:template.data.task.locationId,dueAt:period.dueAt,assigneeIds:template.data.scheduledAssigneeIds??[]});created.push(await occurrence.handler({...ctx,expectedVersion:undefined},data));}
 const state={templateId:template.id,siteId:template.data.task.siteId,scheduleRevision:template.data.revision,cursor:plan.cursor,nextDueAt:plan.nextDueAt,hasMore:plan.hasMore,blockedReason:plan.blockedReason??null,evaluatedAt:ctx.now};
 if(previous)await ctx.tx.save(previous,state);else await ctx.tx.add('task_calendar_cursor',state,cursorId);
 return {createdTaskIds:created.map(t=>t.id),...state};
});

Object.assign(operationsCommands,createWorkingTimeAdvisoryCommands(effectiveTimesheet));
