import {createHash} from 'node:crypto';
import {z} from 'zod';
import {assert,DomainError,id,timestamp,type Actor,type CommandContext,type CommandRegistry,type Entity,type Transaction,type Data} from './core.js';
import {effectiveTimesheet} from './operations.js';
import {automationCronSchema,automationScheduleDue,parseAutomationCron} from './automation-schedule.js';
import {berlinCalendarInstant} from './task-calendar.js';

export interface DigestTransaction extends Transaction {companyId:string;}
export interface OperationsDigestHost<T extends DigestTransaction=DigestTransaction> {
 actorIn(tx:T,userId:string):Promise<Actor>;
 scope(actor:Actor,permission:string):Actor;
 visible(tx:T,actor:Actor,entity:Entity):Promise<boolean>;
 project(tx:T,actor:Actor,entity:Entity):Promise<Entity>;
 registry:CommandRegistry;
}
const ids=z.array(id).max(100).refine(values=>new Set(values).size===values.length,'duplicate scope IDs');
export const digestPolicySchema=z.object({id:id.optional(),name:z.string().trim().min(1).max(150),kind:z.enum(['MORNING','DAY','WEEK']),ownerId:id,scope:z.object({siteIds:ids.default([]),customerIds:ids.default([])}).strict(),cron:automationCronSchema,timezone:z.literal('Europe/Berlin').default('Europe/Berlin'),channel:z.enum(['WEB','WHATSAPP']).default('WEB'),channelId:id.optional(),template:z.string().min(1).max(100).optional(),templateStatus:z.enum(['APPROVED','PENDING','REJECTED']).optional(),activeFrom:timestamp.optional(),enabled:z.boolean().default(true)}).strict().superRefine((policy,ctx)=>{const cron=parseAutomationCron(policy.cron);if((policy.kind==='WEEK')!==(cron.weekday!==null))ctx.addIssue({code:'custom',path:['cron'],message:'WEEK requires one weekday; MORNING/DAY require daily *'});if(policy.channel==='WHATSAPP'&&!policy.channelId)ctx.addIssue({code:'custom',path:['channelId'],message:'Private owner DIRECT channel required'});});
export const DIGEST_SECTIONS={crews:'dispatch.read',tasks:'task.read',time:'timesheet.read',travel:'trip.approve',materials:'inventory.read',shortages:'inventory.read',leads:'lead.read',decisions:'decision.manage'} as const;
export interface DigestReference {kind:string;id:string;version:number;permission:string;}
export interface DigestSlot {slotKey:string;slotAt:string;localDate:string;periodStart:string;periodEnd:string;plannedStart:string;plannedEnd:string;}
const ms=(at:unknown)=>typeof at==='string'?Date.parse(at):NaN;
function parts(at:Date){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(at).map(p=>[p.type,p.value]));}
function addDays(day:string,days:number){return new Date(Date.parse(day+'T00:00:00Z')+days*86400000).toISOString().slice(0,10);}
/** Berlin's civil midnight is valid on both DST transition days. */
export function berlinDigestMidnight(day:string){let instant=Date.parse(day+'T00:00:00Z');const target=instant;for(let attempt=0;attempt<4;attempt++){const p=parts(new Date(instant)),wall=Date.parse(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:00Z`);instant+=target-wall;}return new Date(instant).toISOString();}
export function digestSlot(policy:Entity,at:Date):DigestSlot {
 assert(Number.isFinite(at.getTime()),'VALIDATION_ERROR');const p=parts(at),localDate=`${p.year}-${p.month}-${p.day}`,slotAt=new Date(Math.floor(at.getTime()/60000)*60000).toISOString();
 let from=localDate,until=slotAt;
 if(policy.data.kind==='MORNING'||policy.data.kind==='DAY'&&p.hour==='00'&&p.minute==='00'){from=addDays(localDate,-1);until=berlinDigestMidnight(localDate);}
 if(policy.data.kind==='WEEK'){const weekday=new Date(localDate+'T12:00:00Z').getUTCDay(),monday=addDays(localDate,-((weekday+6)%7));from=addDays(monday,-7);until=berlinDigestMidnight(monday);}
 return {slotKey:`${localDate}:${p.hour}:${p.minute}`,slotAt,localDate,periodStart:berlinDigestMidnight(from),periodEnd:until,plannedStart:berlinDigestMidnight(localDate),plannedEnd:berlinDigestMidnight(addDays(localDate,1))};
}
export function policyDue(policy:Entity,now:Date):DigestSlot|null {
 const input=digestPolicyInput(policy);
 if(!input.enabled||ms(input.activeFrom)>Math.floor(now.getTime()/60000)*60000)return null;
 if(!automationScheduleDue(input.cron,now))return null;return digestSlot(policy,now);
}
/** Explicit manual generation selects at most the latest eight-day scheduled
 * slot; DST gaps are skipped, overlaps choose the first actual occurrence. */
export function latestDigestSlot(policy:Entity,now:Date):DigestSlot|null {const input=digestPolicyInput(policy),cron=parseAutomationCron(input.cron),p=parts(now),day=`${p.year}-${p.month}-${p.day}`,clock=`${String(cron.hour).padStart(2,'0')}:${String(cron.minute).padStart(2,'0')}`;for(let back=0;back<8;back++){const at=new Date(berlinCalendarInstant(addDays(day,-back),clock));if(at.getTime()>now.getTime())continue;const slot=policyDue(policy,at);if(slot)return slot;}return null;}
function canonical(value:unknown):string {if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';const object=value as Data;return '{'+Object.keys(object).filter(k=>object[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+canonical(object[k])).join(',')+'}';}
export const operationsDigestHash=(value:unknown)=>createHash('sha256').update(canonical(value)).digest('hex');
export function digestPolicyInput(entity:Entity){const input=Object.fromEntries(Object.keys(digestPolicySchema.innerType().shape).filter(key=>key!=='id'&&entity.data[key]!==undefined).map(key=>[key,entity.data[key]]));return digestPolicySchema.parse(input);}
const externalRoles=['CLIENT','CUSTOMER','GUEST','EXTERNAL_BAULEITER','SERVICE_ACCOUNT'];
export async function digestOwner<T extends DigestTransaction>(tx:T,userId:string,host:OperationsDigestHost<T>):Promise<Actor>{const user=await tx.get('user',userId);assert(user.companyId===tx.companyId&&user.data.active===true,'ACCESS_DENIED');const owner=await host.actorIn(tx,userId);assert(owner.userId===userId&&owner.companyId===tx.companyId&&!owner.roles.some(role=>externalRoles.includes(role)),'ACCESS_DENIED');return owner;}
export async function digestScopeAllowed<T extends DigestTransaction>(tx:T,actor:Actor,scope:{siteIds:string[];customerIds:string[]},permission:string,host:OperationsDigestHost<T>):Promise<boolean>{
 const scoped=host.scope(actor,permission);if(scoped.companyId!==tx.companyId||scoped.userId!==actor.userId||!scoped.permissions.includes(permission))return false;
 const all=scoped.permissions.includes('scope.company');if(!scope.siteIds.length&&!scope.customerIds.length)return all;
 const boundCustomers=new Set<string>();for(const siteId of scope.siteIds){const site=await tx.get('site',siteId);if(site.companyId!==tx.companyId||site.data.active===false||!all&&!scoped.siteIds.includes(siteId))return false;if(site.data.customerId)boundCustomers.add(site.data.customerId);}
 for(const customerId of scope.customerIds){const customer=await tx.get('customer',customerId);if(customer.companyId!==tx.companyId||customer.data.active===false)return false;if(!all&&!scoped.customerIds.includes(customerId)&&!boundCustomers.has(customerId))return false;}
 return true;
}
export async function authorizeDigestPolicy<T extends DigestTransaction>(tx:T,actor:Actor,policy:Entity,host:OperationsDigestHost<T>){assert(policy.companyId===tx.companyId&&policy.kind==='digest_policy'&&policy.data.ownerId===actor.userId,'ACCESS_DENIED');const input=digestPolicyInput(policy),owner=await digestOwner(tx,input.ownerId,host);assert(await digestScopeAllowed(tx,owner,input.scope,'notifications.manage',host),'ACCESS_DENIED');return owner;}

/** All rows are projected under the exact section capability before numeric use. */
export async function buildOperationsDigest<T extends DigestTransaction>(tx:T,policy:Entity,owner:Actor,at:Date,host:OperationsDigestHost<T>,observedAt:Date=at) {
 const input=digestPolicyInput(policy),slot=digestSlot(policy,at),asOf=observedAt.toISOString(),references:DigestReference[]=[],sections:Data={},permissions:string[]=[];
 const bindings=new Map<string,string|null>(),timesheetAdjustmentSets:Data[]=[];
 const reference=(entity:Entity,permission:string)=>{if(!references.some(r=>r.kind===entity.kind&&r.id===entity.id&&r.permission===permission))references.push({kind:entity.kind,id:entity.id,version:entity.version,permission});for(const data of [entity.data,...(entity.data.segmentSnapshot??[])]){const siteId=data.siteId??data.site_id??data.snapshot?.siteId;if(siteId&&containsOne(data))bindings.set(siteId,siteCustomers.get(siteId)??null);}assert(references.length<=10000,'VALIDATION_ERROR',{reason:'DIGEST_NARROW_SCOPE_REQUIRED'});};
 const siteCustomers=new Map<string,string|null>();for(const site of await tx.list('site'))if(site.companyId===tx.companyId&&site.data.active!==false)siteCustomers.set(site.id,site.data.customerId??null);
 const containsOne=(data:Data)=>{const sid=data.siteId??data.site_id??data.snapshot?.siteId,cid=data.customerId??data.customer_id??siteCustomers.get(sid);if(sid&&(!siteCustomers.has(sid)||cid&&(siteCustomers.get(sid)??null)!==cid))return false;if(input.scope.siteIds.length&&(!sid||!input.scope.siteIds.includes(sid)))return false;if(input.scope.customerIds.length&&(!sid||!cid||!input.scope.customerIds.includes(cid)))return false;return true;};
 const contains=(data:Data)=>Array.isArray(data.segmentSnapshot)?data.segmentSnapshot.some((segment:Data)=>containsOne(segment)):containsOne(data);
 const rows=async(kind:string,permission:string)=>{const scoped=host.scope(owner,permission),out:Entity[]=[];const all=await tx.list(kind);assert(all.length<=10000,'VALIDATION_ERROR',{reason:'DIGEST_NARROW_SCOPE_REQUIRED'});for(const entity of all)if(entity.companyId===tx.companyId&&contains(entity.data)&&await host.visible(tx,scoped,entity)){const projected=await host.project(tx,scoped,entity);assert(projected.companyId===tx.companyId&&projected.id===entity.id,'ACCESS_DENIED');out.push(projected);}return out.sort((a,b)=>a.id.localeCompare(b.id));};
 const section=async(name:keyof typeof DIGEST_SECTIONS,compute:(permission:string)=>Promise<Data>)=>{const permission=DIGEST_SECTIONS[name];if(!await digestScopeAllowed(tx,owner,input.scope,permission,host)){sections[name]={status:'UNAVAILABLE',reason:'CURRENT_CAPABILITY_UNAVAILABLE'};return;}permissions.push(permission);sections[name]={status:'AVAILABLE',...await compute(permission)};};
 const eventIn=(value:unknown)=>Number.isFinite(ms(value))&&ms(value)>=ms(slot.periodStart)&&ms(value)<ms(slot.periodEnd)&&ms(value)<=observedAt.getTime();
 const integer=(value:unknown)=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=0;
 const add=(a:number,b:number)=>{assert(Number.isSafeInteger(a+b),'INVALID_STATE',{reason:'DIGEST_QUANTITY_OVERFLOW'});return a+b;};
 await section('crews',async permission=>{const items=[];for(const entity of await rows('crew_assignment',permission)){const d=entity.data;if(['ASSIGNED','ACKNOWLEDGED','STARTED'].includes(d.status)&&ms(d.startAt)<ms(slot.plannedEnd)&&ms(d.endAt)>ms(slot.plannedStart)){reference(entity,permission);items.push({id:entity.id,siteId:d.siteId,orderId:d.orderId,status:d.status,startAt:d.startAt,endAt:d.endAt,crewSize:Array.isArray(d.employeeIds)?d.employeeIds.length:null});}}return {basis:'CURRENT_PLANNED_CREWS_INTERSECTING_LOCAL_PLAN_DAY',count:items.length,items};});
 await section('tasks',async permission=>{
  const counts={accepted:0,submitted:0,incomplete:0},byUnit:Data={},items=[],tasks=await rows('task',permission),taskById=new Map(tasks.map(task=>[task.id,task]));let unresolvedQuantityCount=0;
  for(const entity of tasks){const d=entity.data;if(d.state==='CANCELLED')continue;reference(entity,permission);const bucket=d.state==='ACCEPTED'?'accepted':d.state==='SUBMITTED_FOR_REVIEW'?'submitted':'incomplete';counts[bucket]++;items.push({id:entity.id,siteId:d.siteId,state:d.state,unit:d.unit});if(typeof d.unit!=='string'||!integer(d.plannedQuantityMilli)||!integer(d.reportedQuantityMilli)||!integer(d.acceptedQuantityMilli)){unresolvedQuantityCount++;continue;}const unit=byUnit[d.unit]??={plannedQuantityMilli:0,reportedQuantityMilli:0,acceptedQuantityMilli:0};unit.plannedQuantityMilli=add(unit.plannedQuantityMilli,d.plannedQuantityMilli);unit.reportedQuantityMilli=add(unit.reportedQuantityMilli,d.reportedQuantityMilli);unit.acceptedQuantityMilli=add(unit.acceptedQuantityMilli,d.state==='ACCEPTED'?d.acceptedQuantityMilli:0);}
  const periodByUnit:Data={},periodCounts={worklogs:0,acceptedReviews:0,reopenedReviews:0},periodUnit=(task:Entity)=>periodByUnit[task.data.unit]??={reportedQuantityMilli:0,grossAcceptedQuantityMilli:0,revokedAcceptedQuantityMilli:0,acceptedQuantityMilli:0};
  for(const log of await rows('worklog',permission)){const d=log.data,task=taskById.get(d.taskId);if(!task||!eventIn(d.reportedAt??log.createdAt))continue;assert(d.siteId===task.data.siteId&&d.unit===task.data.unit&&typeof d.unit==='string'&&integer(d.quantityMilli),'INVALID_STATE',{reason:'DIGEST_WORKLOG_SCOPE_OR_QUANTITY_INVALID'});reference(task,permission);reference(log,permission);const group=periodUnit(task);group.reportedQuantityMilli=add(group.reportedQuantityMilli,d.quantityMilli);periodCounts.worklogs++;}
  for(const review of await rows('task_review',permission)){const d=review.data,task=taskById.get(d.taskId);if(!task||!eventIn(d.reviewedAt)||!['ACCEPT','REOPEN'].includes(d.decision))continue;const quantity=d.decision==='ACCEPT'?d.quantityMilli:d.snapshot?.acceptedQuantityMilli??0;assert((d.siteId??d.snapshot?.siteId)===task.data.siteId&&(!d.snapshot?.unit||d.snapshot.unit===task.data.unit)&&typeof task.data.unit==='string'&&integer(quantity),'INVALID_STATE',{reason:'DIGEST_REVIEW_SCOPE_OR_QUANTITY_INVALID'});reference(task,permission);reference(review,permission);const group=periodUnit(task),accept=d.decision==='ACCEPT';group[accept?'grossAcceptedQuantityMilli':'revokedAcceptedQuantityMilli']=add(group[accept?'grossAcceptedQuantityMilli':'revokedAcceptedQuantityMilli'],quantity);group.acceptedQuantityMilli=add(group.acceptedQuantityMilli,accept?quantity:-quantity);periodCounts[accept?'acceptedReviews':'reopenedReviews']++;}
  return {basis:'CURRENT_TASK_STATE_AS_OF;COMPATIBLE_UNITS_ONLY;NOT_PERIOD_PRODUCTION',counts,byUnit,unresolvedQuantityCount,items,periodProgress:{basis:'IN_PERIOD_WORKLOG_REPORTS_AND_NET_ACCEPT_MINUS_REOPEN_REVIEWS;HALF_OPEN_UTC;TEAM_RESULT_ONCE',counts:periodCounts,byUnit:periodByUnit}};
 });
 const approvedIntervals=async(kind:string,permission:string)=>{
  const intervals:Data[]=[],seen=new Map<string,string>();let count=0,incompleteRecords=0;const adjustmentRows=kind==='timesheet'?await tx.list('timesheet_adjustment'):[];assert(adjustmentRows.length<=10000,'VALIDATION_ERROR',{reason:'DIGEST_NARROW_SCOPE_REQUIRED'});
  let candidates=await rows(kind,permission);
  if(kind==='trip_approval'){
   candidates=[];const approvals=await tx.list('trip_approval');assert(approvals.length<=10000,'VALIDATION_ERROR',{reason:'DIGEST_NARROW_SCOPE_REQUIRED'});
   for(const trip of await rows('trip',permission)){
    if(trip.data.approvalState!=='APPROVED')continue;reference(trip,permission);
    const related=approvals.filter(a=>a.companyId===tx.companyId&&a.data.tripId===trip.id).sort((a,b)=>ms(b.data.approvedAt)-ms(a.data.approvedAt)||ms(b.createdAt)-ms(a.createdAt));const latest=related[0];
    if(!latest||latest.data.decision!=='APPROVE'||latest.data.employeeId!==trip.data.employeeId){incompleteRecords++;continue;}
    const tied=related.filter(a=>ms(a.data.approvedAt)===ms(latest.data.approvedAt)&&ms(a.createdAt)===ms(latest.createdAt));if(tied.some(a=>a.data.decision!==latest.data.decision||operationsDigestHash(a.data.segmentSnapshot)!==operationsDigestHash(latest.data.segmentSnapshot))){incompleteRecords++;continue;}
    const scoped=host.scope(owner,permission);if(!contains(latest.data)||!await host.visible(tx,scoped,latest))return {intervals:[],count:0,incompleteRecords:1,unavailableReason:'CURRENT_TRIP_APPROVAL_NOT_AUTHORIZED'};candidates.push(await host.project(tx,scoped,latest));
   }
  }
  for(const entity of candidates){
   const d=entity.data;if(kind==='timesheet'?!['APPROVED','LOCKED'].includes(d.state):d.decision!=='APPROVE')continue;
   if(!d.approvedBy||!Number.isFinite(ms(d.approvedAt))||ms(d.approvedAt)>observedAt.getTime()||!Array.isArray(d.segmentSnapshot)){incompleteRecords++;reference(entity,permission);continue;}
   let snapshot:Data[]=d.segmentSnapshot;const adjustments:Entity[]=[];
   if(kind==='timesheet'){
    const scoped=host.scope(owner,permission);
    for(const adjustment of adjustmentRows.filter(a=>a.companyId===tx.companyId&&a.data.timesheetId===entity.id&&a.data.state==='APPROVED')){
     if(!adjustment.data.approvedBy||!Number.isFinite(ms(adjustment.data.approvedAt))||ms(adjustment.data.approvedAt)>observedAt.getTime()||!await host.visible(tx,scoped,adjustment))return {intervals:[],count:0,incompleteRecords:1,unavailableReason:'APPROVED_CORRECTION_NOT_AUTHORIZED_OR_INVALID'};
     const projected=await host.project(tx,scoped,adjustment);assert(projected.companyId===tx.companyId&&projected.id===adjustment.id,'ACCESS_DENIED');adjustments.push(projected);
    }
    // Reuse the canonical sequence-based closed-period correction resolver,
    // exposing only authorized projected adjustments and prohibiting writes.
    const noWrite=async()=>{throw new DomainError('ACCESS_DENIED');},readTx:Transaction={get:(kind,id)=>tx.get(kind,id),list:async <U extends Data=Data>(kind:string)=> (kind==='timesheet_adjustment'?adjustments:[]) as Entity<U>[],add:noWrite,save:noWrite,event:noWrite};
    const ctx:CommandContext={tx:readTx,actor:scoped,now:asOf,idempotencyKey:'read-only-digest',requireSite:siteId=>{assert(scoped.permissions.includes('scope.company')||scoped.siteIds.includes(siteId),'ACCESS_DENIED');},requireOwn:userId=>{assert(userId===owner.userId||scoped.permissions.includes('timesheet.approve'),'ACCESS_DENIED');}};
    snapshot=await effectiveTimesheet(ctx,entity);timesheetAdjustmentSets.push({timesheetId:entity.id,adjustments:adjustments.map(a=>({id:a.id,version:a.version})).sort((a,b)=>a.id.localeCompare(b.id))});
   }
   let used=false;
   for(const s of snapshot){if(!contains(s))continue;if(!Number.isFinite(ms(s.startAt))||!Number.isFinite(ms(s.endAt))||ms(s.endAt)<ms(s.startAt)||!s.id){incompleteRecords++;reference(entity,permission);continue;}const start=Math.max(ms(s.startAt),ms(slot.periodStart)),end=Math.min(ms(s.endAt),ms(slot.periodEnd),observedAt.getTime());if(end<=start)continue;const key=`${s.id}:${start}:${end}`,activity=typeof s.activity==='string'?s.activity:'UNKNOWN';if(seen.has(key)){assert(seen.get(key)===activity,'INVALID_STATE',{reason:'DIGEST_CONFLICTING_APPROVED_INTERVAL'});continue;}seen.set(key,activity);intervals.push({activity,seconds:Math.floor((end-start)/1000)});used=true;}
   if(used){count++;reference(entity,permission);for(const adjustment of adjustments)reference(adjustment,permission);}
  }
  return {intervals,count,incompleteRecords};
 };
 await section('time',async permission=>{const {intervals,count,incompleteRecords,unavailableReason}=await approvedIntervals('timesheet',permission);if(unavailableReason)return {status:'UNAVAILABLE',reason:unavailableReason};const byActivity:Data={};for(const segment of intervals){const activity=['WORKING','SERVICE_TASK','WAITING_WORK','ON_BREAK','TRAVELLING','AWAY_PENDING_REASON'].includes(segment.activity)?segment.activity:'UNKNOWN';byActivity[activity]=add(byActivity[activity]??0,segment.seconds);}const knownApprovedSeconds=Object.values(byActivity).reduce((sum:number,n:any)=>add(sum,n),0);return {basis:'CLIPPED_EFFECTIVE_APPROVED_RECORDED_INTERVAL_SNAPSHOTS;APPROVED_CORRECTION_SEQUENCE;NO_PAYROLL_OR_AUTOMATIC_DEDUCTION',approvedSeconds:incompleteRecords?null:knownApprovedSeconds,knownApprovedSeconds,incompleteRecords,byActivity,timesheetCount:count};});
 await section('travel',async permission=>{const {intervals,count,incompleteRecords,unavailableReason}=await approvedIntervals('trip_approval',permission);if(unavailableReason)return {status:'UNAVAILABLE',reason:unavailableReason};const knownApprovedRecordedSeconds=intervals.filter(s=>s.activity==='TRAVELLING').reduce((sum,s)=>add(sum,s.seconds),0);return {basis:'CURRENT_TRIP_APPROVAL_AND_LATEST_CLIPPED_APPROVED_INTERVAL_SNAPSHOT;NO_GPS_OR_INFERRED_DISTANCE',approvedRecordedSeconds:incompleteRecords?null:knownApprovedRecordedSeconds,knownApprovedRecordedSeconds,tripCount:count,incompleteRecords};});
 await section('materials',async permission=>{const byMaterialUnit:Data={},items=[];let incompleteRecords=0;for(const entity of await rows('material_usage',permission)){const d=entity.data;if(!eventIn(d.confirmedAt))continue;reference(entity,permission);if(!integer(d.quantityBase)||typeof d.unit!=='string'){incompleteRecords++;continue;}const key=`${d.materialId}:${d.unit}`,group=byMaterialUnit[key]??={materialId:d.materialId,unit:d.unit,quantityBase:0};group.quantityBase=add(group.quantityBase,d.quantityBase);items.push({id:entity.id,siteId:d.siteId,materialId:d.materialId,unit:d.unit,quantityBase:d.quantityBase});}return {basis:'ACTUAL_CONFIRMED_CONSUMPTION_IN_PERIOD;INTEGER_BASE_UNITS;NO_INTERNAL_COST',count:items.length,byMaterialUnit,items,incompleteRecords};});
 await section('shortages',async permission=>{const items=[];let incompleteRecords=0;for(const entity of await rows('material_request',permission)){const d=entity.data;if(!['APPROVED','PARTIALLY_APPROVED','RESERVED','PARTIALLY_RESERVED','ISSUED','PARTIALLY_ISSUED'].includes(d.state))continue;if(!integer(d.approvedBase)||!integer(d.receivedBase)){incompleteRecords++;continue;}const unreceivedBase=Math.max(0,d.approvedBase-d.receivedBase);if(unreceivedBase===0)continue;const material=await tx.get('material',d.materialId),scoped=host.scope(owner,permission);if(material.companyId!==tx.companyId||!await host.visible(tx,scoped,material)){incompleteRecords++;continue;}const projected=await host.project(tx,scoped,material);if(typeof projected.data.baseUnit!=='string'){incompleteRecords++;continue;}reference(entity,permission);reference(projected,permission);items.push({id:entity.id,siteId:d.siteId,materialId:d.materialId,unit:projected.data.baseUnit,unreceivedBase});}return {basis:'CURRENT_APPROVED_DEMAND_NOT_RECEIVED;NOT_STOCK_FORECAST_OR_PURCHASE',count:items.length,items,incompleteRecords};});
 await section('leads',async permission=>{const byStatus:Data={};let count=0;for(const entity of await rows('lead',permission))if(eventIn(entity.createdAt)){reference(entity,permission);count++;const status=typeof entity.data.status==='string'?entity.data.status:'UNKNOWN';byStatus[status]=(byStatus[status]??0)+1;}return {basis:'NEW_AUTHORIZED_SCOPE_BOUND_LEADS_IN_PERIOD;NO_CONTACT_OR_PRIVATE_TEXT',count,byStatus};});
 await section('decisions',async permission=>{const items=[];let knownActionCents=0,unpricedCount=0;for(const entity of await rows('decision',permission)){const d=entity.data;if(d.status!=='OPEN'||d.ownerId!==owner.userId||d.approvalDomain==='FINANCE')continue;reference(entity,permission);const amount=integer(d.amountCents)?d.amountCents:null;if(amount===null)unpricedCount++;else knownActionCents=add(knownActionCents,amount);items.push({id:entity.id,siteId:d.siteId,orderId:d.orderId,dueAt:d.dueAt,amountCents:amount});}return {basis:'CURRENT_OPEN_DECISIONS_OWNED_BY_RECIPIENT;EXPLICIT_AUTHORIZED_EUR_AMOUNTS_ONLY',count:items.length,knownActionCents,unpricedCount,currency:'EUR',financeExcluded:true,items};});
 for(const siteId of input.scope.siteIds)bindings.set(siteId,siteCustomers.get(siteId)??null);
 return {policyId:policy.id,policyVersion:policy.version,kind:input.kind,...slot,asOf,sections,coverage:{basis:'CURRENT_CAPABILITY_AND_ENGINE_ROW_PROJECTION;SCOPE_FILTERED_NOT_COMPANY_TOTAL',permissions:[...new Set(permissions)],sourceReferences:references,siteBindings:[...bindings].sort(([a],[b])=>a.localeCompare(b)).map(([siteId,customerId])=>({siteId,customerId})),timesheetAdjustmentSets:timesheetAdjustmentSets.sort((a,b)=>a.timesheetId.localeCompare(b.timesheetId))},providerInvoked:false,businessEffectsExecuted:false};
}

export async function operationsDigestVisible<T extends DigestTransaction>(tx:T,actor:Actor,entity:Entity,host:OperationsDigestHost<T>):Promise<boolean>{
 try{if(entity.companyId!==tx.companyId||actor.companyId!==tx.companyId||!['digest_policy','operations_digest'].includes(entity.kind))return false;const current=await tx.get(entity.kind,entity.id);if(current.version!==entity.version||current.data.ownerId!==actor.userId)return false;const policy=current.kind==='digest_policy'?current:await tx.get('digest_policy',current.data.policyId),owner=await authorizeDigestPolicy(tx,actor,policy,host);if(current.kind==='digest_policy')return true;if(current.data.policyVersion!==policy.version||current.data.immutable!==true||current.data.sha256!==operationsDigestHash(current.data.snapshot))return false;const coverage=current.data.snapshot?.coverage;if(!coverage||!Array.isArray(coverage.permissions)||!Array.isArray(coverage.sourceReferences)||!Array.isArray(coverage.siteBindings)||!Array.isArray(coverage.timesheetAdjustmentSets)||coverage.sourceReferences.length>10000)return false;for(const permission of coverage.permissions)if(!await digestScopeAllowed(tx,owner,policy.data.scope,permission,host))return false;for(const binding of coverage.siteBindings){const site=await tx.get('site',binding.siteId);if(site.companyId!==tx.companyId||site.data.active===false||(site.data.customerId??null)!==binding.customerId)return false;}const adjustments=await tx.list('timesheet_adjustment');for(const set of coverage.timesheetAdjustmentSets){const actual=adjustments.filter(a=>a.companyId===tx.companyId&&a.data.timesheetId===set.timesheetId&&a.data.state==='APPROVED').map(a=>({id:a.id,version:a.version})).sort((a,b)=>a.id.localeCompare(b.id));if(operationsDigestHash(actual)!==operationsDigestHash(set.adjustments))return false;}for(const ref of coverage.sourceReferences){const source=await tx.get(ref.kind,ref.id),scoped=host.scope(owner,ref.permission);if(source.version!==ref.version||source.companyId!==tx.companyId||!await host.visible(tx,scoped,source))return false;await host.project(tx,scoped,source);}return true;}
 catch(error){if(error instanceof DomainError||error instanceof z.ZodError)return false;throw error;}
}
