import { randomBytes, createHash, createHmac, scrypt as nodeScrypt, timingSafeEqual, createCipheriv, createDecipheriv } from 'node:crypto';
import * as OTPAuth from 'otpauth';
import { z } from 'zod';
import { assert, DomainError, type Actor,type Entity, type Data, type Transaction } from '../../packages/domain/core.js';
import type { Request, Response } from 'express';

export interface QueryResult {rows:any[]}
export interface SqlTransaction extends Transaction {query?:(sql:string,params?:any[])=>Promise<QueryResult>}
export interface DatabaseLike {query:(sql:string,params?:any[])=>Promise<QueryResult>;transaction:<T>(companyId:string,actorId:string,fn:(tx:SqlTransaction)=>Promise<T>)=>Promise<T>;close?:()=>Promise<void>}
export interface EngineLike {authorizeEntity?:(tx:any,userId:string,kind:string,id:string)=>Promise<{actor:Actor;entity:Entity}>;execute:(actor:Actor,name:string,envelope:{input:unknown;expected_version?:number;idempotency_key:string})=>Promise<any>;readEntities:(actor:Actor,kind:string)=>Promise<any[]>;getActor:(userId:string,companyId:string)=>Promise<Actor>;registry:Record<string,any>}
export interface AuthOptions {companyId:string;appMode:string;publicOrigin?:string;cookieSecure?:boolean;encryptionKey?:string}
export const SESSION_COOKIE='knaba_session';
export const GUEST_COOKIE='knaba_guest';
export const hashToken=(value:string)=>createHash('sha256').update(value).digest('hex');
export const opaqueToken=()=>randomBytes(32).toString('base64url');
export const csrfFor=(token:string)=>createHmac('sha256',token).update('KNABA-DE-CSRF-v1').digest('base64url');
const passwordSchema=z.string().min(12).max(128);
const privileged=['OWNER','DIRECTOR','OPERATIONS_MANAGER','ACCOUNTANT','BOT_ADMIN','DISPATCHER'];
const derive=(password:string,salt:Buffer)=>new Promise<Buffer>((resolve,reject)=>nodeScrypt(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024},(error,key)=>error?reject(error):resolve(key)));
export async function hashPassword(password:string){passwordSchema.parse(password);const salt=randomBytes(24);const key=await derive(password,salt);return `scrypt$v1$32768$8$1$${salt.toString('base64url')}$${key.toString('base64url')}`;}
export async function verifyPassword(password:string,stored:string){if(password.length>128)return false;const parts=stored.split('$');if(parts.length!==7||parts.slice(0,5).join('$')!=='scrypt$v1$32768$8$1')return false;try{const salt=Buffer.from(parts[5]!,'base64url'),expected=Buffer.from(parts[6]!,'base64url');if(salt.length!==24||expected.length!==64)return false;const actual=await derive(password,salt);return timingSafeEqual(actual,expected);}catch{return false;}}
export function parseCookies(value?:string){const out:Record<string,string>={};for(const segment of (value??'').split(';')){const index=segment.indexOf('=');if(index<1)continue;try{out[segment.slice(0,index).trim()]=decodeURIComponent(segment.slice(index+1).trim());}catch{}}return out;}
export function sameOrigin(req:Request,configuredOrigin?:string){const origin=req.get('origin');if(req.get('sec-fetch-site')==='cross-site')throw new DomainError('ACCESS_DENIED');if(!origin)return;let expected=configuredOrigin; if(!expected)expected=`${req.protocol}://${req.get('host')}`;assert(origin===new URL(expected).origin,'ACCESS_DENIED');}
export function requireCsrf(req:Request,token:string,configuredOrigin?:string){sameOrigin(req,configuredOrigin);const provided=req.get('x-csrf-token')??'';const expected=csrfFor(token);const p=Buffer.from(provided),e=Buffer.from(expected);assert(p.length===e.length&&timingSafeEqual(p,e),'ACCESS_DENIED',{reason:'CSRF_REQUIRED'});}
export function sealSecret(secret:string,key?:string){if(!key)throw new DomainError('MISSING_CONFIGURATION',{field:'AUTH_ENCRYPTION_KEY'});const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',createHash('sha256').update(key).digest(),iv);const encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),encrypted].map(b=>b.toString('base64url')).join('.');}
export function openSecret(sealed:string,key?:string){if(!key)throw new DomainError('MISSING_CONFIGURATION',{field:'AUTH_ENCRYPTION_KEY'});const [i,t,e]=sealed.split('.');assert(i&&t&&e,'NEEDS_REAUTH');try{const decipher=createDecipheriv('aes-256-gcm',createHash('sha256').update(key).digest(),Buffer.from(i,'base64url'));decipher.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([decipher.update(Buffer.from(e,'base64url')),decipher.final()]).toString('utf8');}catch{throw new DomainError('NEEDS_REAUTH');}}
export function validateTotp(secret:string,token:string,now=Date.now()){if(!/^\d{6}$/.test(token))return null;try{const totp=new OTPAuth.TOTP({issuer:'KNABA DE',algorithm:'SHA1',digits:6,period:30,secret:OTPAuth.Secret.fromBase32(secret)});const delta=totp.validate({token,timestamp:now,window:1});return delta===null?null:Math.floor(now/30000)+delta;}catch{return null;}}
export async function sql(tx:SqlTransaction,statement:string,params:any[]=[]){assert(tx.query,'MISSING_CONFIGURATION',{reason:'TRANSACTION_SQL_REQUIRED'});return tx.query(statement,params);}

export class RateLimiter {
 private buckets=new Map<string,{count:number;until:number}>();
 constructor(private limit=20,private windowMs=60000){}
 check(key:string,now=Date.now()){if(this.buckets.size>10000){for(const [k,v]of this.buckets)if(v.until<=now)this.buckets.delete(k);assert(this.buckets.size<=10000,'RATE_LIMITED');}const old=this.buckets.get(key);const bucket=!old||old.until<=now?{count:0,until:now+this.windowMs}:old;bucket.count++;this.buckets.set(key,bucket);assert(bucket.count<=this.limit,'RATE_LIMITED',{retryAfterSeconds:Math.ceil((bucket.until-now)/1000)});}
}
export class AuthService {
 private limiter=new RateLimiter(12,60000);
 private dummyHash=hashPassword('KNABA dummy timing password; no account');
 constructor(public db:DatabaseLike,public engine:EngineLike,public options:AuthOptions){}
 cookie(res:Response,token:string,guest=false){res.cookie(guest?GUEST_COOKIE:SESSION_COOKIE,token,{httpOnly:true,secure:this.options.appMode==='PRODUCTION'||(this.options.cookieSecure??this.options.publicOrigin?.startsWith('https:')===true),sameSite:'strict',path:'/',maxAge:(guest?24:8)*3600000});}
 async createSession(userId:string,guest=false,mfa=false){const token=opaqueToken();const expiresAt=new Date(Date.now()+(guest?24:8)*3600000).toISOString();await this.db.query('INSERT INTO auth_sessions(token_hash,user_id,company_id,expires_at,mfa_verified) VALUES($1,$2,$3,$4,$5)',[hashToken(token),userId,this.options.companyId,expiresAt,mfa]);return {token,csrfToken:csrfFor(token),expiresAt};}
 async authenticate(req:Request,guest=false){const bearer=req.get('authorization');if(bearer){assert(/^Bearer [A-Za-z0-9_-]{30,100}$/.test(bearer),'NEEDS_REAUTH');const token=bearer.slice(7);const devices=await this.db.transaction(this.options.companyId,'AUTH_DEVICE',tx=>tx.list('device'));const device=devices.find(d=>d.data.tokenHash===hashToken(token)&&d.data.active&&(!d.data.tokenExpiresAt||Date.parse(d.data.tokenExpiresAt)>Date.now()));assert(device,'NEEDS_REAUTH');const actor=await this.engine.getActor(device.data.employeeId,this.options.companyId);return {actor:{...actor,mfaVerified:false},token,device,csrfToken:null,guest:false};}const cookies=parseCookies(req.get('cookie'));const token=cookies[guest?GUEST_COOKIE:SESSION_COOKIE];assert(token&&/^[A-Za-z0-9_-]{30,100}$/.test(token),'NEEDS_REAUTH');const result=await this.db.query('SELECT user_id,company_id,mfa_verified,created_at FROM auth_sessions WHERE token_hash=$1 AND company_id=$2 AND revoked_at IS NULL AND expires_at>now()',[hashToken(token),this.options.companyId]);const session=result.rows[0];assert(session,'NEEDS_REAUTH');const actor=await this.engine.getActor(session.user_id,session.company_id);const mfaAge=Date.now()-new Date(session.created_at).getTime();const recent=mfaAge>=-30000&&mfaAge<15*60000;return {actor:{...actor,mfaVerified:session.mfa_verified&&recent},token,csrfToken:csrfFor(token),guest,device:undefined};}
 async mutation(req:Request,guest=false){const auth=await this.authenticate(req,guest);if(!auth.device)requireCsrf(req,auth.token,this.options.publicOrigin);return auth;}
 async profile(actor:Actor){return this.db.transaction(actor.companyId,actor.userId,async tx=>{const u=await tx.get('user',actor.userId);return {id:u.id,name:u.data.name??u.data.displayName,displayName:u.data.displayName,email:u.data.email,language:u.data.language,businessCode:u.data.businessCode,roles:actor.roles};});}
 async login(req:Request,res:Response,input:any){sameOrigin(req,this.options.publicOrigin);const i=z.object({email:z.string().email().max(200),password:z.string().min(1).max(128),otp:z.string().regex(/^\d{6}$/).optional(),totp:z.string().regex(/^\d{6}$/).optional(),companyId:z.string().optional()}).strict().parse(input);assert(!i.companyId||i.companyId===this.options.companyId,'NEEDS_REAUTH');this.limiter.check(hashToken(`${req.ip??'unknown'}:${i.email.toLowerCase()}`));const user=await this.db.transaction(this.options.companyId,'AUTH_LOGIN',async tx=>(await tx.list('user')).find(u=>u.data.active!==false&&u.data.email?.toLowerCase()===i.email.toLowerCase()));const row=user?(await this.db.query('SELECT password_hash,totp_secret,totp_last_counter FROM auth_credentials WHERE user_id=$1 AND company_id=$2',[user.id,this.options.companyId])).rows[0]:undefined;const valid=await verifyPassword(i.password,row?.password_hash??await this.dummyHash);assert(user&&row&&valid,'NEEDS_REAUTH');const actor=await this.engine.getActor(user.id,this.options.companyId);let mfa=false;if(row.totp_secret){const counter=validateTotp(openSecret(row.totp_secret,this.options.encryptionKey),i.otp??i.totp??'');assert(counter!==null,'NEEDS_REAUTH');const updated=await this.db.query('UPDATE auth_credentials SET totp_last_counter=$3 WHERE user_id=$1 AND company_id=$2 AND totp_last_counter<$3 RETURNING user_id',[user.id,this.options.companyId,counter]);assert(updated.rows.length===1,'NEEDS_REAUTH');mfa=true;}else assert(this.options.appMode!=='PRODUCTION'||!actor.roles.some(r=>privileged.includes(r)),'NEEDS_REAUTH');const session=await this.createSession(user.id,false,mfa);this.cookie(res,session.token);return {actor:{...actor,mfaVerified:mfa},user:await this.profile(actor),mode:this.options.appMode,csrfToken:session.csrfToken,expiresAt:session.expiresAt};}
 async demo(req:Request,res:Response,input:any){sameOrigin(req,this.options.publicOrigin);assert(this.options.appMode==='DEMO','NOT_FOUND_SAFE');const i=z.object({role:z.string().min(1).max(60)}).strict().parse(input);this.limiter.check(hashToken(`demo:${req.ip??'unknown'}`));const requestedRole=({FOREMAN:'INTERNAL_BAULEITER',TEAM_LEAD:'TEAM_LEADER',WAREHOUSE:'STOREKEEPER'} as Record<string,string>)[i.role]??i.role;const user=await this.db.transaction(this.options.companyId,'AUTH_DEMO',async tx=>(await tx.list('user')).find(u=>u.data.active!==false&&(u.data.synthetic===true||u.data.demo===true)&&u.data.roles?.includes(requestedRole)));assert(user,'NOT_FOUND_SAFE');const session=await this.createSession(user.id,false,true);this.cookie(res,session.token);const actor=await this.engine.getActor(user.id,this.options.companyId);return {actor:{...actor,mfaVerified:true},user:await this.profile(actor),mode:'DEMO',csrfToken:session.csrfToken,expiresAt:session.expiresAt};}
 async logout(req:Request,res:Response){const auth=await this.mutation(req);await this.db.query('UPDATE auth_sessions SET revoked_at=now() WHERE token_hash=$1 AND company_id=$2',[hashToken(auth.token),this.options.companyId]);res.clearCookie(SESSION_COOKIE,{httpOnly:true,secure:this.options.appMode==='PRODUCTION'||(this.options.cookieSecure??this.options.publicOrigin?.startsWith('https:')===true),sameSite:'strict',path:'/'});return {ok:true};}
 async bootstrapOwner(input:{email:string;name:string;password:string;totpSecret:string;evidence:string}){assert(this.options.appMode==='PRODUCTION','INVALID_STATE');z.object({email:z.string().email(),name:z.string().min(1),password:passwordSchema,totpSecret:z.string().regex(/^[A-Z2-7]{16,100}$/),evidence:z.string().min(8)}).strict().parse(input);const passwordHash=await hashPassword(input.password),secret=sealSecret(input.totpSecret,this.options.encryptionKey);return this.db.transaction(this.options.companyId,'OFFLINE_BOOTSTRAP',async tx=>{assert(!(await tx.list('user')).some(u=>u.data.roles?.includes('OWNER')),'INVALID_STATE',{reason:'BOOTSTRAP_CLOSED'});const user=await tx.add('user',{name:input.name,email:input.email.toLowerCase(),roles:['OWNER'],permissions:['identity.manage','role.manage','legal.manage','company.manage','bot.manage','audit.read','scope.company'],siteIds:[],warehouseIds:[],customerIds:[],active:true,bootstrapEvidence:input.evidence,mfaRequired:true});await sql(tx,'INSERT INTO auth_credentials(user_id,company_id,password_hash,totp_secret,totp_last_counter) VALUES($1,$2,$3,$4,-1)',[user.id,this.options.companyId,passwordHash,secret]);await tx.event('identity.owner_bootstrapped',{userId:user.id,evidence:input.evidence});return {userId:user.id,companyId:this.options.companyId};});}
}
