import {materialRequestBatchView} from '../../packages/domain/material-request-batches.ts';
import {handoffReminderReadable} from '../../packages/domain/handoff-calendar.ts';
import {freshMfa} from './auth.ts';
import {workNotificationRelevant} from '../../packages/domain/work-notifications.ts';
import {createOperationsDigestCommands} from './operations-digest.ts';
import {authorizeDigestPolicy,digestScopeAllowed,operationsDigestVisible} from '../../packages/domain/operations-digest.ts';
import {createClientRedactionCommands} from './client-redaction.ts';
import {clientRedactionVisible} from '../../packages/storage/client-redaction.ts';
import {authorizeAutomationRule,authorizeAutomationRun,AUTOMATION_ACTION_PERMISSIONS,automationVisible} from '../../packages/domain/automation-authority.ts';
import {createHash} from 'node:crypto';
import {zodToJsonSchema} from 'zod-to-json-schema';
import {Database,PgTransaction} from './database.ts';
import {createPrivateBlobStore} from '../../packages/storage/index.ts';
import {createPrivacyErasureCommands} from './privacy-erasure.ts';
import {internalAssistantCommands,internalAssistantHost} from './internal-assistant.ts';
import {internalAssistantVisible} from '../../packages/integrations/internal-assistant.ts';
import {authorizeCommerceEmployeeCommand,publicIssueProjection,quoteCustomerProjection,quotePublishedForCustomer} from '../../packages/domain/commerce.ts';
import {registry} from './registry.ts';
import {effectiveDelegations,delegationScope,type EffectiveDelegations} from '../../packages/domain/governance.ts';
import {Actor,assert,CommandContext,Data,DomainError,Entity} from '../../packages/domain/core.ts';
import {enforcePermission,publicEntity,ROLE_PERMISSIONS} from '../../packages/domain/permissions.ts';
import {gpsAcknowledgement,gpsSampleVisible} from '../../packages/domain/gps.ts';
function canonical(value:any):string {if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).sort().filter(k=>value[k]!==undefined).map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';}
export interface CommandPrecondition {kind:string;id:string;version:number;}
export function commandHash(name:string,input:unknown,version?:number,preconditions?:CommandPrecondition[]){return createHash('sha256').update(canonical({name,input,version,...preconditions?.length?{preconditions}:{}})).digest('hex');}
const inventoryKinds=new Set(['material','material_batch','stock_location','stock_movement','stock_reservation','stock_transfer','transfer','material_request','material_usage','stock_count','asset_assignment']);
const procurementKinds=new Set(['supplier','purchase_requisition','purchase_order','goods_receipt','confirmed_inbound']);
const financeKinds=new Set(['rate_history','payroll_period','payroll_calculation','official_payslip','payout','payout_allocation','payout_acknowledgment','receipt','payout_receipt','payout_reversal','payroll_calculation_revision','payroll_correction','payout_reconciliation','payroll_approval','payroll_lock']);
const operationKinds=new Set(['site','location','location_revision','work_package','task','task_assignment','worklog','work_log','work_allocation','task_review','defect','task_template','task_occurrence','task_cycle','task_calendar_cursor']);
const ownKinds=new Set(['shift','time_segment','time_event','timesheet','timesheet_correction','absence_explanation','location_incident','presence','presence_event','trip','trip_segment','trip_approval','device','tracking_session','device_event_review','manual_device_event']);
const commerceKinds=new Set(['lead','service','price_book','quote','quote_version','quote_acceptance','change_order','dispatch_request','crew','crew_assignment','schedule_reservation','order_review','order_transition','site_visit_request','customer','customer_membership','employee_availability']);
const adminKinds=new Set(['knowledge','assistant_config','knowledge_document','knowledge_version','glossary','automation_rule','automation_run','bot_config','legal_approval','tracking_policy','geofence','integration_config','integration_event','integration_record','integration_quarantine','integration_outbound','integration_decision']);
const readOnlyCommands=new Set(['assistant.playground','assistant.usage','digest.preview']);
const freshReadCommands=new Set(['internal_assistant.preview','shift.working_time_advisory','timesheet.working_time_advisory','assistant.playground','assistant.usage','handoff.inbox','channel.list','message.read','translation.read','service.list','dispatch.recommend','customer.portal','knowledge.search','quote.get','issue.context','issue.get','issue.list','material.lookup','privacy.status','channel.unread','delivery.reply_context','location.breadcrumb','shift.summary','timesheet.summary','task.summary','operations.statistics','stock.balance','procurement.calculate','request.batch.view']);
export class Engine{
 private authority=new WeakMap<Actor,{base:Actor;effective:EffectiveDelegations}>();
 scope(actor:Actor,permission:string):Actor{const state=this.authority.get(actor);return state?delegationScope(state.base,state.effective,permission):actor;}
 delegationFingerprint(actor:Actor){return this.authority.get(actor)?.effective.fingerprint??null;}
 registry=registry;
 constructor(public db:Database,public mode='DEMO'){this.registry={...registry,...createPrivacyErasureCommands(db,this,createPrivateBlobStore(db)),...createClientRedactionCommands(db,this,createPrivateBlobStore(db))};assert(['DEMO','TEST','PRODUCTION'].includes(mode),'MISSING_CONFIGURATION');Object.assign(this.registry,internalAssistantCommands(db,this,mode as 'DEMO'|'TEST'|'PRODUCTION'));Object.assign(this.registry,createOperationsDigestCommands(this));}
 async getActor(userId:string,companyId:string):Promise<Actor>{return this.db.transaction(companyId,userId,tx=>this.actorIn(tx,userId));}
 async actorIn(tx:PgTransaction,userId:string):Promise<Actor>{const user=await tx.get('user',userId);assert(user.data.active!==false,'ACCESS_DENIED');const roles=(user.data.roles??[]) as string[];const permissions=[...new Set([...roles.flatMap(r=>ROLE_PERMISSIONS[r]??[]),...(user.data.permissions??[])])];const memberships=(await tx.list('customer_membership')).filter(m=>m.data.active===true&&!m.data.revokedAt&&[m.data.userId,m.data.user_id].includes(userId)&&(!m.data.expiresAt||m.data.expiresAt>new Date().toISOString()));const base:Actor={userId,companyId:tx.companyId,roles,permissions,siteIds:user.data.siteIds??[],warehouseIds:user.data.warehouseIds??[],customerIds:[...new Set(memberships.filter(m=>(m.data.permissions??[]).includes('VIEW')).map(m=>m.data.customerId))]};const effective=await effectiveDelegations(tx,base,new Date().toISOString());const actor:Actor={...base,permissions:[...new Set([...base.permissions,...effective.grants.flatMap(g=>g.permissions)])]};this.authority.set(actor,{base,effective});return actor;}
 context(tx:PgTransaction,actor:Actor,key:string,version?:number,now=new Date().toISOString(),scopedUserIds:string[]=[],permission?:string):CommandContext{return {tx,actor,now,idempotencyKey:key,expectedVersion:version,forPermission:async requested=>{const fresh=await this.actorIn(tx,actor.userId);fresh.mfaVerified=actor.mfaVerified===true&&(this.mode!=='PRODUCTION'||freshMfa(actor.mfaVerified,actor.mfaVerifiedAt));fresh.mfaVerifiedAt=actor.mfaVerifiedAt;enforcePermission(fresh,requested);const scoped=this.scope(fresh,requested);const users=(await tx.list('user')).filter(u=>u.data.active!==false&&(u.data.siteIds??[]).some((siteId:string)=>scoped.siteIds.includes(siteId))).map(u=>u.id);return this.context(tx,scoped,key,undefined,now,users,requested);},authorizeAutomationRun:(run)=>authorizeAutomationRun(tx,run,this.automationHost(),{initiator:actor,initiatorPermission:permission==='automation.execute'?'automation.execute':undefined}),authorizeAutomationRule:(rule)=>authorizeAutomationRule(tx,rule,{actorIn:(currentTx,userId)=>this.actorIn(currentTx,userId),scope:(fresh,requested)=>this.scope(fresh,requested)},{initiator:actor,initiatorPermission:permission==='automation.manage'||permission==='automation.approve'||permission==='automation.execute'?permission:undefined,allowCandidate:permission==='automation.manage'&&rule.id==='automation-rule-candidate'&&rule.data.status==='DRAFT'&&rule.version===1&&rule.data.ruleVersion===1}),requireSite:(id)=>{assert(actor.permissions.includes('scope.company')||actor.siteIds.includes(id),'ACCESS_DENIED');},requireOwn:(id)=>{if(id===actor.userId)return;const allowed=actor.permissions.includes('scope.company')||actor.permissions.some(p=>(['finance.payroll','finance.payout','finance.payout.approve','finance.payroll.approve','finance.accountant','timesheet.approve','trip.approve'].includes(p)||(permission==='device.manage'&&p==='device.manage')));assert(allowed&&(actor.permissions.includes('scope.company')||scopedUserIds.includes(id)),'ACCESS_DENIED');}};}
 private automationHost(){return {actorIn:(tx:PgTransaction,userId:string)=>this.actorIn(tx,userId),scope:(fresh:Actor,permission:string)=>this.scope(fresh,permission)};}
 private async automationCommandAuthority(tx:PgTransaction,current:Actor,permission:string,run:Entity,lease?:{id:string;token:string}){
  assert(lease&&typeof lease.id==='string'&&typeof lease.token==='string','ACCESS_DENIED');
  const held=await tx.query("SELECT id,type,data FROM outbox WHERE company_id=$1 AND id=$2 AND status='RUNNING' AND lease_token=$3 AND leased_until>clock_timestamp() FOR UPDATE",[tx.companyId,lease.id,lease.token]);
  assert(held.rows.length===1,'WORKER_LEASE_LOST');assert(held.rows[0].type==='automation.action_requested'&&held.rows[0].data?.runId===run.id,'ACCESS_DENIED');
  const service=await this.actorIn(tx,'knaba-integration-service');assert(service.roles.includes('SERVICE_ACCOUNT'),'ACCESS_DENIED');
  const owner=await authorizeAutomationRun(tx,run,this.automationHost(),{initiator:service,initiatorPermission:'automation.execute'}),rule=await tx.get('automation_rule',run.data.ruleId);
  assert(rule.data.status==='ACTIVE'&&rule.data.approvedBy&&Number.isFinite(Date.parse(rule.data.activeFrom))&&Date.parse(rule.data.activeFrom)<=Date.now()&&owner.userId===current.userId&&AUTOMATION_ACTION_PERMISSIONS[run.data.action as keyof typeof AUTOMATION_ACTION_PERMISSIONS]===permission,'ACCESS_DENIED');
 }
 private async automationReceipt(tx:PgTransaction,current:Actor,name:string,input:Data,result:any){
  const permission=name==='automation_rule.activate'?'automation.approve':name==='automation_rule.run'?'automation.execute':'automation.manage';
  const rule=await tx.get('automation_rule',name==='automation_rule.create'?result?.id:input.id);await authorizeAutomationRule(tx,rule,this.automationHost(),{initiator:current,initiatorPermission:permission});
  if(name==='automation_rule.run'){
   assert(result?.kind==='automation_run'&&result.companyId===tx.companyId&&result.data?.ruleId===rule.id&&result.data?.eventId===input.event.id,'ACCESS_DENIED');
   const run=await tx.get('automation_run',result.id);await authorizeAutomationRun(tx,run,this.automationHost(),{initiator:current,initiatorPermission:permission});return run;
  }
  const cached=name==='automation_rule.preview'?result?.rule:result;
  assert(cached?.kind==='automation_rule'&&cached.id===rule.id&&cached.companyId===tx.companyId,'ACCESS_DENIED');
  assert(cached.version===rule.version&&canonical(cached.data)===canonical(rule.data),'VERSION_CONFLICT',{reason:'AUTOMATION_RECEIPT_SOURCE_CHANGED'});return result;
 }
 private async assistantAnswerAuthority(tx:PgTransaction,current:Actor,input:Data,guards:CommandPrecondition[]|undefined,lease?:{id:string;token:string}){
  // A worker may use its exact approved configuration as a send precondition,
  // without obtaining general access to administrative configuration records.
  assert(current.userId==='knaba-integration-service'&&current.roles.includes('SERVICE_ACCOUNT'),'ACCESS_DENIED');
  enforcePermission(this.scope(current,'integration.process'),'integration.process');
  assert(lease&&typeof lease.id==='string'&&typeof lease.token==='string','WORKER_LEASE_LOST');
  const held=await tx.query("SELECT type,data FROM outbox WHERE company_id=$1 AND id=$2 AND status='RUNNING' AND lease_token=$3 AND leased_until>clock_timestamp() FOR UPDATE",[tx.companyId,lease.id,lease.token]);
  assert(held.rows.length===1,'WORKER_LEASE_LOST');
  const job=held.rows[0];assert(job.type==='assistant.answer_requested','ACCESS_DENIED');
  const source=job.data;
  assert(source&&typeof source.configId==='string'&&typeof source.channelId==='string'&&typeof source.messageId==='string'&&typeof source.actorId==='string','ACCESS_DENIED');
  assert(input.channel_id===source.channelId&&input.reply_to_id===source.messageId,'ACCESS_DENIED');
  const required=[{kind:'channel',id:source.channelId},{kind:'assistant_config',id:source.configId},{kind:'message',id:source.messageId}];
  assert(guards?.length===required.length&&required.every(ref=>guards.filter(g=>g.kind===ref.kind&&g.id===ref.id).length===1),'ACCESS_DENIED');
  const channel=await tx.get('channel',source.channelId),config=await tx.get('assistant_config',source.configId),message=await tx.get('message',source.messageId);
  assert(config.data.status==='ACTIVE'&&config.data.configVersion===source.configVersion,'AI_SUPPRESSED');
  assert(['PRIVATE_CUSTOMER_ASSISTANT','SITE_CLIENT'].includes(channel.data.type)&&channel.data.handoff?.state==='AI_ACTIVE','AI_SUPPRESSED');
  assert(message.data.channel_id===channel.id&&message.data.author_id===source.actorId&&!message.data.deleted_at,'ACCESS_DENIED');
  const requester=await this.actorIn(tx,source.actorId);enforcePermission(this.scope(requester,'chat.read'),'chat.read');
  assert(await this.visible(tx,this.scope(requester,'chat.read'),message),'ACCESS_DENIED');
  if(channel.data.lead_id)assert((await tx.get('lead',channel.data.lead_id)).data.ownership==='AI_ACTIVE','AI_SUPPRESSED');
  for(const referenced of [channel,config,message]){
   const guard=guards.find(g=>g.kind===referenced.kind&&g.id===referenced.id)!;
   assert(referenced.version===guard.version,'VERSION_CONFLICT',{reason:'PREVIEW_REFERENCE_CHANGED',kind:referenced.kind,id:referenced.id});
  }
  return config.id;
 }
 private async nativeDeviceAuthority(tx:PgTransaction,actor:Actor,name:string,input:Data,bound:{id:string;token_hash:string}){
  assert(bound&&typeof bound.id==='string'&&typeof bound.token_hash==='string'&&/^[a-f0-9]{64}$/.test(bound.token_hash),'NEEDS_REAUTH');
  assert(['presence.ingest','trip.sample','shift.start','shift.end','shift.activity','trip.start','trip.stop','trip.resume','trip.arrive','trip.end','absence.explain'].includes(name),'ACCESS_DENIED');
  const device=await tx.get('device',bound.id);
  assert(device.companyId===actor.companyId&&device.data.employeeId===actor.userId&&device.data.active===true&&!device.data.revokedAt&&device.data.tokenHash===bound.token_hash&&Date.parse(device.data.tokenExpiresAt)>Date.now(),'NEEDS_REAUTH');
  if(name==='shift.start'){assert(input.deviceId===device.id&&(input.employeeId===undefined||input.employeeId===actor.userId),'ACCESS_DENIED');return;}
  let shiftId=input.shiftId;
  if(!shiftId&&input.tripId)shiftId=(await tx.get('trip',input.tripId)).data.shiftId;
  if(!shiftId&&input.incidentId)shiftId=(await tx.get('location_incident',input.incidentId)).data.shiftId;
  if(!shiftId&&input.segmentId)shiftId=(await tx.get('time_segment',input.segmentId)).data.shiftId;
  assert(typeof shiftId==='string','ACCESS_DENIED');const shift=await tx.get('shift',shiftId);
  assert(shift.companyId===actor.companyId&&shift.data.employeeId===actor.userId&&shift.data.deviceId===device.id,'ACCESS_DENIED');
 }
 async execute(actor:Actor,name:string,envelope:{input?:any;expected_version?:number;idempotency_key?:string;preconditions?:CommandPrecondition[];worker_lease?:{id:string;token:string};native_device?:{id:string;token_hash:string}}):Promise<any>{const def=this.registry[name];assert(def,'NOT_FOUND_SAFE');assert(typeof envelope.idempotency_key==='string'&&envelope.idempotency_key.length>=8&&envelope.idempotency_key.length<=200,'VALIDATION_ERROR',{field:'idempotency_key'});const input=def.schema.parse(envelope.input??{});const guards=envelope.preconditions;assert(guards===undefined||Array.isArray(guards)&&guards.length<=20&&guards.every(g=>g&&typeof g.kind==='string'&&g.kind.length>0&&g.kind.length<=100&&typeof g.id==='string'&&g.id.length>0&&g.id.length<=200&&Number.isInteger(g.version)&&g.version>0),'VALIDATION_ERROR');const hash=commandHash(name,input,envelope.expected_version,guards);
 if(readOnlyCommands.has(name)){
  assert(envelope.preconditions===undefined&&envelope.worker_lease===undefined&&envelope.native_device===undefined,'VALIDATION_ERROR');
  if(envelope.expected_version!==undefined)assert(Number.isInteger(envelope.expected_version)&&envelope.expected_version>0,'VALIDATION_ERROR');
  return this.db.transaction(actor.companyId,actor.userId,async tx=>{
   const current=await this.actorIn(tx,actor.userId);current.mfaVerified=actor.mfaVerified===true&&(this.mode!=='PRODUCTION'||freshMfa(actor.mfaVerified,actor.mfaVerifiedAt));current.mfaVerifiedAt=actor.mfaVerifiedAt;enforcePermission(current,def.permission);
   if(def.highRisk&&this.mode==='PRODUCTION')assert(current.mfaVerified,'NEEDS_REAUTH');
   const scoped=this.scope(current,def.permission);scoped.mfaVerified=current.mfaVerified;scoped.mfaVerifiedAt=current.mfaVerifiedAt;
   return def.handler(this.context(tx,scoped,envelope.idempotency_key!,envelope.expected_version,new Date().toISOString(),(await tx.list('user')).filter(u=>u.data.active!==false&&(u.data.siteIds??[]).some((siteId:string)=>scoped.siteIds.includes(siteId))).map(u=>u.id),def.permission),input);
  },10000,true);
 }
 return this.db.transaction(actor.companyId,actor.userId,async tx=>{const current=await this.actorIn(tx,actor.userId);current.mfaVerified=actor.mfaVerified===true&&(this.mode!=='PRODUCTION'||freshMfa(actor.mfaVerified,actor.mfaVerifiedAt));current.mfaVerifiedAt=actor.mfaVerifiedAt;enforcePermission(current,def.permission);if(envelope.native_device)await this.nativeDeviceAuthority(tx,current,name,input,envelope.native_device);if(def.highRisk&&this.mode==='PRODUCTION')assert(current.mfaVerified,'NEEDS_REAUTH');if(envelope.expected_version!==undefined)assert(Number.isInteger(envelope.expected_version)&&envelope.expected_version>0,'VALIDATION_ERROR');const channelAccess=(await tx.list('channel')).filter(c=>c.data.members?.some((m:Data)=>m.user_id===current.userId)).map(c=>({id:c.id,members:c.data.members.filter((m:Data)=>m.user_id===current.userId).map((m:Data)=>({...m,effective:!m.revoked_at&&!m.left_at&&!m.removed_at&&m.active!==false&&(!m.expires_at||Date.parse(m.expires_at)>Date.now())}))}));const authorizationHash=createHash('sha256').update(canonical({permissions:current.permissions,roles:current.roles,siteIds:current.siteIds,warehouseIds:current.warehouseIds,customerIds:current.customerIds,delegations:this.delegationFingerprint(current),memberships:(await tx.list('customer_membership')).filter(m=>(m.data.userId??m.data.user_id)===current.userId).map(m=>({data:m.data,effective:m.data.active===true&&!m.data.revokedAt&&(!m.data.expiresAt||Date.parse(m.data.expiresAt)>Date.now())})),channelAccess})).digest('hex');const assistantAnswerConfig=name==='message.send'&&input.source==='AI'?await this.assistantAnswerAuthority(tx,current,input,guards,envelope.worker_lease):undefined;for(const guard of guards??[])if(guard.kind==='automation_run')await this.automationCommandAuthority(tx,current,def.permission,await tx.get('automation_run',guard.id),envelope.worker_lease);if(name==='digest.generate'){
 const policy=await tx.get('digest_policy',input.policyId);await authorizeDigestPolicy(tx,current,policy,this);
 assert(policy.version===input.policyVersion,'VERSION_CONFLICT');assert(policy.data.enabled&&Date.parse(policy.data.activeFrom)<=Date.now(),'NOT_DUE');
 if(envelope.worker_lease){const lease=await tx.query("SELECT id,type,data FROM outbox WHERE company_id=$1 AND id=$2 AND status='RUNNING' AND lease_token=$3 AND leased_until>clock_timestamp() FOR UPDATE",[tx.companyId,envelope.worker_lease.id,envelope.worker_lease.token]);
  assert(lease.rows.length===1,'WORKER_LEASE_LOST');const job=lease.rows[0];assert(job.type==='digest.requested'&&job.data?.policyId===policy.id&&job.data?.policyVersion===policy.version&&job.data?.ownerId===current.userId&&job.data?.slotAt===input.slotAt,'ACCESS_DENIED');
  const service=await this.actorIn(tx,'knaba-integration-service');assert(service.roles.includes('SERVICE_ACCOUNT')&&await digestScopeAllowed(tx,service,policy.data.scope,'automation.execute',this),'ACCESS_DENIED');
 }
}if(name==='media.redact'){
 const media=await tx.get('media_asset',input.mediaId);assert(!current.roles.some(role=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST','SERVICE_ACCOUNT'].includes(role)),'ACCESS_DENIED');
 for(const permission of ['report.approve','media.read']){const scoped=this.scope(current,permission);assert(scoped.permissions.includes(permission)&&(scoped.permissions.includes('scope.company')||scoped.siteIds.includes(media.data.siteId)),'ACCESS_DENIED');}
 assert(await this.visible(tx,current,media),'NOT_FOUND_SAFE');
}if(name==='notification.read')assert(await this.visible(tx,current,await tx.get('notification',input.notification_id)),'NOT_FOUND_SAFE');await authorizeCommerceEmployeeCommand(this.context(tx,this.scope(current,def.permission),envelope.idempotency_key!,undefined,new Date().toISOString(),[],def.permission),name,input);const receipt=await tx.query('SELECT command,input_hash,result,authorization_hash,created_at FROM command_receipts WHERE company_id=$1 AND actor_id=$2 AND idempotency_key=$3',[actor.companyId,actor.userId,envelope.idempotency_key]);if(receipt.rows[0]){assert(receipt.rows[0].authorization_hash===authorizationHash,'ACCESS_DENIED');if(name==='callback.consume')assert(Date.now()-new Date(receipt.rows[0].created_at).getTime()<900000,'INVALID_STATE');assert(receipt.rows[0].command===name&&receipt.rows[0].input_hash===hash,'IDEMPOTENCY_CONFLICT',{reason:'IDEMPOTENCY_KEY_REUSED'});if(name==='digest.generate'){
 const result=receipt.rows[0].result;assert(result?.kind==='operations_digest'&&result.companyId===tx.companyId&&result.data?.policyId===input.policyId,'ACCESS_DENIED');
 const digest=await tx.get('operations_digest',result.id);assert(await operationsDigestVisible(tx,current,digest,this),'ACCESS_DENIED');return digest;
}if(name==='media.redact'){
 const media=await tx.get('media_asset',input.mediaId),result=receipt.rows[0].result;
 assert(result?.kind==='media_asset'&&result.id===media.id&&result.companyId===media.companyId&&result.data?.clientCopyVersion===media.data.clientCopyVersion&&result.data?.clientSha256===media.data.clientSha256,'VERSION_CONFLICT',{reason:'CLIENT_COPY_CHANGED'});return result;
}if(['automation_rule.create','automation_rule.preview','automation_rule.activate','automation_rule.run'].includes(name))return this.automationReceipt(tx,current,name,input,receipt.rows[0].result);if(!freshReadCommands.has(name))return name==='trip.sample'?gpsAcknowledgement(receipt.rows[0].result):receipt.rows[0].result;}if(envelope.worker_lease){assert(typeof envelope.worker_lease.id==='string'&&typeof envelope.worker_lease.token==='string','VALIDATION_ERROR');const lease=await tx.query("SELECT id FROM outbox WHERE company_id=$1 AND id=$2 AND status='RUNNING' AND lease_token=$3 AND leased_until>clock_timestamp() FOR UPDATE",[actor.companyId,envelope.worker_lease.id,envelope.worker_lease.token]);assert(lease.rows.length===1,'WORKER_LEASE_LOST');}for(const guard of guards??[]){const referenced=await tx.get(guard.kind,guard.id);if(guard.kind==='whatsapp_router_action'){
 assert(referenced.data.status==='CLAIMED'&&Date.parse(referenced.data.expires_at)>Date.now(),'CALLBACK_EXPIRED');
 assert(referenced.data.user_id===current.userId,'ACCESS_DENIED');
 const identities=(await tx.list('contact_identity')).filter(i=>i.data.active!==false&&i.data.verified===true&&!i.data.revokedAt&&!i.data.revoked_at&&(!i.data.expiresAt||Date.parse(i.data.expiresAt)>Date.now())&&(!i.data.expires_at||Date.parse(i.data.expires_at)>Date.now())&&['WHATSAPP','PHONE'].includes(i.data.type)&&String(i.data.value).replace(/[^\d]/g,'')===referenced.data.sender);
 const owners=[...new Set(identities.map(i=>i.data.userId))];assert(owners.length===1&&owners[0]===current.userId,'ACCESS_DENIED');
 }
 if(guard.kind==='automation_run'){await this.automationCommandAuthority(tx,current,def.permission,referenced,envelope.worker_lease);assert(['QUEUED','FAILED'].includes(referenced.data.status),'INVALID_STATE');}
 if(!['whatsapp_router_action','automation_run'].includes(guard.kind)&&!(guard.kind==='assistant_config'&&guard.id===assistantAnswerConfig))assert(await this.visible(tx,this.scope(current,def.permission),referenced),'NOT_FOUND_SAFE');
 assert(referenced.version===guard.version,'VERSION_CONFLICT',{reason:'PREVIEW_REFERENCE_CHANGED',kind:guard.kind,id:guard.id});
 }const scoped=this.scope(current,def.permission);scoped.mfaVerified=current.mfaVerified;scoped.mfaVerifiedAt=current.mfaVerifiedAt;const result=await def.handler(this.context(tx,scoped,envelope.idempotency_key!,envelope.expected_version,new Date().toISOString(),(await tx.list('user')).filter(u=>u.data.active!==false&&(u.data.siteIds??[]).some((siteId:string)=>scoped.siteIds.includes(siteId))).map(u=>u.id),def.permission),input);if(envelope.worker_lease){const lease=await tx.query("SELECT id FROM outbox WHERE company_id=$1 AND id=$2 AND status='RUNNING' AND lease_token=$3 AND leased_until>clock_timestamp()",[actor.companyId,envelope.worker_lease.id,envelope.worker_lease.token]);assert(lease.rows.length===1,'WORKER_LEASE_LOST');}if(receipt.rows[0])return result;const after=await this.actorIn(tx,actor.userId);const afterChannels=(await tx.list('channel')).filter(c=>c.data.members?.some((m:Data)=>m.user_id===after.userId)).map(c=>({id:c.id,members:c.data.members.filter((m:Data)=>m.user_id===after.userId).map((m:Data)=>({...m,effective:!m.revoked_at&&!m.left_at&&!m.removed_at&&m.active!==false&&(!m.expires_at||Date.parse(m.expires_at)>Date.now())}))}));const receiptAuthorizationHash=createHash('sha256').update(canonical({permissions:after.permissions,roles:after.roles,siteIds:after.siteIds,warehouseIds:after.warehouseIds,customerIds:after.customerIds,delegations:this.delegationFingerprint(after),memberships:(await tx.list('customer_membership')).filter(m=>(m.data.userId??m.data.user_id)===after.userId).map(m=>({data:m.data,effective:m.data.active===true&&!m.data.revokedAt&&(!m.data.expiresAt||Date.parse(m.data.expiresAt)>Date.now())})),channelAccess:afterChannels})).digest('hex');await tx.query('INSERT INTO command_receipts(company_id,actor_id,idempotency_key,command,input_hash,result,authorization_hash) VALUES($1,$2,$3,$4,$5,$6,$7)',[actor.companyId,actor.userId,envelope.idempotency_key,name,hash,JSON.stringify(name==='trip.sample'?gpsAcknowledgement(result):result??null),receiptAuthorizationHash]);await tx.query('INSERT INTO audit_log(company_id,actor_id,action,detail) VALUES($1,$2,$3,$4)',[actor.companyId,actor.userId,'COMMAND:'+name,JSON.stringify({inputHash:hash,permission:def.permission})]);return result;});}
 catalog(actor:Actor){return {commands:Object.entries(this.registry).filter(([,v])=>actor.permissions.includes(v.permission)).map(([name,v])=>({name,permission:v.permission,highRisk:!!v.highRisk,schema:zodToJsonSchema(v.schema,{target:'jsonSchema7',$refStrategy:'none'})}))};}
 async authorizeEntity(tx:PgTransaction,userId:string,kind:string,id:string){const actor=await this.actorIn(tx,userId),entity=await tx.get(kind,id);assert(await this.visible(tx,actor,entity),'NOT_FOUND_SAFE');return {actor,entity};}
 async readEntities(actor:Actor,kind:string):Promise<Entity[]>{return this.db.transaction(actor.companyId,actor.userId,async tx=>{const fresh=await this.actorIn(tx,actor.userId);if(kind==='audit_log'){enforcePermission(fresh,'audit.read');const result=await tx.query('SELECT id,actor_id,action,aggregate_kind,aggregate_id,detail,created_at FROM audit_log WHERE company_id=$1 ORDER BY id DESC LIMIT 500',[fresh.companyId]);return result.rows.map((r:any)=>({id:String(r.id),kind:'audit_log',companyId:fresh.companyId,version:1,data:{actorId:r.actor_id,action:r.action,aggregateKind:r.aggregate_kind,aggregateId:r.aggregate_id,detail:r.detail},createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.created_at).toISOString()}));}const entities=await tx.list(kind);const items:Entity[]=[];for(const e of entities){if(await this.visible(tx,fresh,e))items.push(publicEntity(await this.project(tx,fresh,e)));}return items;});}
 async readEntitiesPage(actor:Actor,kind:string,page:{limit:number;snapshotAt:string;after?:{createdAt:string;id:string}},channelId?:string):Promise<{items:Entity[];has_more:boolean;cursorAfter?:{createdAt:string;id:string}}> {
  assert(Number.isInteger(page.limit)&&page.limit>0&&page.limit<=100&&typeof kind==='string'&&kind.length<=100,'VALIDATION_ERROR');
  return this.db.transaction(actor.companyId,actor.userId,async tx=>{
   const fresh=await this.actorIn(tx,actor.userId);
   if(kind==='audit_log')enforcePermission(fresh,'audit.read');
   if(channelId){assert(kind==='message','VALIDATION_ERROR');assert(await this.visible(tx,fresh,await tx.get('channel',channelId)),'NOT_FOUND_SAFE');}
   let after=page.after,lastScanned=after,scanned=0,exhausted=false;const items:Entity[]=[];
   while(items.length<=page.limit&&scanned<500){
    const count=Math.min(200,500-scanned),rows=await tx.listPage(kind,count,page.snapshotAt,after,channelId);
    for(const row of rows){scanned++;lastScanned={createdAt:row.createdAt,id:row.id};if(kind==='audit_log'||await this.visible(tx,fresh,row))items.push(publicEntity(await this.project(tx,fresh,row)));if(items.length>page.limit)break;}
    if(items.length>page.limit)break;
    if(rows.length<count){exhausted=true;break;}
    after=lastScanned;
   }
   const has_more=items.length>page.limit||!exhausted&&scanned>=500;
   const selected=items.slice(0,page.limit),boundary=items.length>page.limit?selected.at(-1):lastScanned;
   return {items:selected,has_more,...has_more&&boundary?{cursorAfter:{createdAt:boundary.createdAt,id:boundary.id}}:{}};
  },10000,true);
 }
 private async employeeDirectoryAllowed(tx:PgTransaction,a:Actor,e:Entity,permission='dispatch.manage'):Promise<boolean>{const identity=permission==='identity.manage';if(e.kind!=='employee'||e.companyId!==a.companyId||tx.companyId!==a.companyId||!identity&&e.data.active===false||a.roles.some(r=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(r)))return false;const scoped=this.scope(a,permission);if(!scoped.permissions.includes(permission))return false;if(identity&&scoped.permissions.includes('scope.company'))return true;try{const user=await tx.get('user',e.data.userId??e.data.user_id??e.id);return user.companyId===a.companyId&&(identity||user.data.active!==false&&!user.data.roles?.some((r:string)=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(r)))&&(scoped.permissions.includes('scope.company')||(user.data.siteIds??[]).some((siteId:string)=>scoped.siteIds.includes(siteId)));}catch(error){if(error instanceof DomainError)return false;throw error;}}
 private crewManagementAllowed(a:Actor,e:Entity):boolean{return e.companyId===a.companyId&&!a.roles.some(r=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(r))&&['commerce.manage','commerce.read','dispatch.manage','customer.manage','customer.read','lead.manage'].some(permission=>{const scoped=this.scope(a,permission);return scoped.permissions.includes(permission)&&(scoped.permissions.includes('scope.company')||!!e.data.siteId&&scoped.siteIds.includes(e.data.siteId));});}
 private async ownCrewEmployee(tx:PgTransaction,a:Actor,e:Entity):Promise<Entity|undefined>{if(e.companyId!==a.companyId||tx.companyId!==a.companyId||a.roles.some(r=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(r))||!e.data.siteId||!Array.isArray(e.data.employeeIds))return;const scoped=this.scope(a,'dispatch.acknowledge');if(!scoped.permissions.includes('dispatch.acknowledge')||!scoped.permissions.includes('scope.company')&&!scoped.siteIds.includes(e.data.siteId))return;try{const site=await tx.get('site',e.data.siteId);if(site.companyId!==a.companyId||site.data.active===false)return;for(const id of e.data.employeeIds){try{const employee=await tx.get('employee',id);if(employee.companyId===a.companyId&&employee.data.active!==false&&(employee.data.userId??employee.data.user_id??employee.id)===a.userId)return employee;}catch(error){if(!(error instanceof DomainError))throw error;}}}catch(error){if(!(error instanceof DomainError))throw error;}return;}
 async visible(tx:PgTransaction,a:Actor,e:Entity,notificationDepth=0):Promise<boolean>{const d=e.data,k=e.kind,p=a.permissions;const external=a.roles.some(r=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(r));const all=p.includes('scope.company');let sid=k==='site'?e.id:(d.siteId??d.site_id??d.snapshot?.siteId??d.snapshot?.site?.id??d.task?.siteId??d.templateSnapshot?.task?.siteId);if(!sid&&operationKinds.has(k)){for(const [kind,ref]of [['task',d.taskId],['location',d.locationId],['work_package',d.workPackageId]]){if(ref){try{sid=(await tx.get(kind,ref)).data.siteId;if(sid)break;}catch{}}}}const own=[d.ownerUserId,d.userId,d.user_id,d.employeeId,d.employee_id,d.recipientId,d.recipient_id,d.createdBy,d.created_by,d.authorId,d.author_id,d.uploadedBy].includes(a.userId);const siteAllowed=!sid||all||a.siteIds.includes(sid);const allowed=(permission:string)=>{const scoped=this.scope(a,permission);return scoped.permissions.includes(permission)&&(!sid||scoped.permissions.includes('scope.company')||scoped.siteIds.includes(sid));};const anyAllowed=(rights:string[])=>rights.some(allowed);
 if(k==='delegation')return [d.granteeId,d.grantorId].includes(a.userId)||p.includes('role.manage');
 if(k==='privacy_export')return d.subjectUserId===a.userId;
 if(k==='privacy_request'||k==='privacy_erasure_evidence'||k==='privacy_erasure_plan'||k==='privacy_erasure_execution'||k==='legal_hold')return d.subjectUserId===a.userId||(!external&&p.includes('privacy.review'));
 if(k==='retention_policy')return !external&&p.includes('privacy.manage');
 if(k==='assistant_lead_draft')return d.ownerUserId===a.userId;
 if(['internal_assistant_request','internal_assistant_draft'].includes(k))return internalAssistantVisible(tx,a,e,internalAssistantHost(this.db,this,this.mode as 'DEMO'|'TEST'|'PRODUCTION'),new Date().toISOString());
 if(k==='automation_rule'||k==='automation_run')return automationVisible(tx,a,e,{actorIn:(currentTx,userId)=>this.actorIn(currentTx,userId),scope:(fresh,requested)=>this.scope(fresh,requested)});
 if(k==='company')return p.includes('company.manage')||p.includes('bot.manage');
 if(k==='employee'){if(e.companyId!==a.companyId)return false;if(e.id===a.userId||[d.userId,d.user_id].includes(a.userId))return true;for(const permission of ['identity.manage','dispatch.manage','task.assign'])if(await this.employeeDirectoryAllowed(tx,a,e,permission))return true;return false;}
 if(k==='user')return e.id===a.userId||(!external&&(p.includes('identity.manage')||p.includes('task.assign'))&&(all||(d.siteIds??[]).some((s:string)=>a.siteIds.includes(s))));
 if(k==='contact_identity'||k==='invitation'||k==='device_enrollment'||k==='transfer_token'||k==='admin_action'||k==='media_upload')return own||(!external&&p.includes('identity.manage'));
 if(k==='channel'){return !!d.members?.some((m:Data)=>m.user_id===a.userId&&!m.revoked_at&&!m.left_at&&!m.removed_at&&m.active!==false&&(!m.expires_at||Date.parse(m.expires_at)>Date.now()))&&(!external||['SITE_CLIENT','PRIVATE_CUSTOMER_ASSISTANT'].includes(d.type))&&(external&&d.type==='SITE_CLIENT'?await this.customerSite(tx,a,sid):allowed('chat.read'));}
 if(['message','message_version','translation','translation_request','delivery','channel_activity','callback'].includes(k)){if(['translation_request','delivery','channel_activity','callback'].includes(k)&&!own)return false;const cid=d.channel_id??d.channelId;if(!cid)return false;try{const channel=await tx.get('channel',cid);const m=channel.data.members?.find((m:Data)=>m.user_id===a.userId&&!m.revoked_at&&!m.left_at&&!m.removed_at&&m.active!==false&&(!m.expires_at||Date.parse(m.expires_at)>Date.now()));return !!m&&await this.visible(tx,a,channel)&&(!d.deleted_at)&&e.createdAt>=(m.history_from??'');}catch{return false;}}
 if(k==='notification'){
  if(!own||notificationDepth>=8)return false;
  if(d.event==='HANDOFF_MANAGER_REMINDER')return handoffReminderReadable(tx,a,e,new Date().toISOString());
  try{if(d.work_cause&&!await workNotificationRelevant(tx,this,e))return false;
   if(d.message_id&&!await this.visible(tx,a,await tx.get('message',d.message_id),notificationDepth+1))return false;
   if(d.related_kind&&d.related_id&&!await this.visible(tx,a,await tx.get(d.related_kind,d.related_id),notificationDepth+1))return false;
   return true;
  }catch(error){if(error instanceof DomainError)return false;throw error;}
 }
 if(k==='notification_preference')return own;
 if(k==='presence'||k==='presence_event'||k==='device_event_review'){
  if(external||e.companyId!==a.companyId)return false;
  if(d.employeeId===a.userId)return true;
  const routeReview=k==='device_event_review'&&d.command==='trip.sample',permission=routeReview?'location.history.read':'location.presence.read',scoped=this.scope(a,permission);
  if(!scoped.permissions.includes(permission)||!await this.employeeScope(tx,scoped,d.employeeId)||!sid||!scoped.permissions.includes('scope.company')&&!scoped.siteIds.includes(sid))return false;
  try{const policy=await tx.get('tracking_policy',d.policyVersionId);return policy.data[routeReview?'allowBusinessRoute':'allowPresence']===true&&policy.data.active!==false&&Array.isArray(policy.data.accessRoles)&&policy.data.accessRoles.some((r:string)=>a.roles.includes(r));}catch{return false;}
 }
 if(k==='location_sample'){if(!gpsSampleVisible(a,e,this.scope(a,'location.history.read')))return false;if(d.employeeId===a.userId)return true;try{const policy=await tx.get('tracking_policy',d.policyVersionId);return Array.isArray(policy.data.accessRoles)&&policy.data.accessRoles.some((r:string)=>a.roles.includes(r));}catch{return false;}}
 if(operationKinds.has(k)){if(external){if(k!=='site')return false;return await this.customerAccess(tx,a,d.customerId,e.id);}return (!!sid||['site.read','task.read','operations.read'].some(right=>this.scope(a,right).permissions.includes(right)&&this.scope(a,right).permissions.includes('scope.company')))&&anyAllowed(['site.read','task.read','operations.read']);}
 if(k==='timesheet_adjustment'){
  if(external||e.companyId!==a.companyId)return false;
  const scoped=this.scope(a,'timesheet.read');if(!scoped.permissions.includes('timesheet.read'))return false;
  try{const parent=await tx.get('timesheet',d.timesheetId);if(parent.companyId!==tx.companyId||parent.data.employeeId!==d.employeeId||!await this.visible(tx,scoped,parent))return false;
   const snapshots=[...(parent.data.segmentSnapshot??[]),...(d.originalSnapshots??[d.originalSnapshot]),...(d.proposedSnapshots??[d.proposedSnapshot])].filter(Boolean);
   return snapshots.every((segment:Data)=>!segment.siteId||scoped.permissions.includes('scope.company')||scoped.siteIds.includes(segment.siteId));
  }catch(error){if(error instanceof DomainError)return false;throw error;}
 }
 if(ownKinds.has(k)){if(external)return false;const subject=d.employeeId??d.employee_id??d.userId??d.user_id;if(subject===a.userId)return true;const rights=k==='device'||k==='tracking_session'?['device.manage']:k==='trip'||k==='trip_segment'||k==='trip_approval'?['trip.approve']:['timesheet.approve','finance.accountant','finance.payroll'];for(const right of rights){const scoped=this.scope(a,right);if(!scoped.permissions.includes(right)||!await this.employeeScope(tx,scoped,subject))continue;const sites=[sid,...(d.segmentSnapshot??[]).map((segment:Data)=>segment.siteId)].filter(Boolean);if(sites.every(siteId=>scoped.permissions.includes('scope.company')||scoped.siteIds.includes(siteId)))return true;}return false;}
 if(financeKinds.has(k)){return (d.employeeId??d.employee_id)===a.userId||(!external&&p.some(p=>['finance.payroll','finance.accountant','finance.payout','finance.payout.approve','finance.payroll.approve'].includes(p))&&await this.employeeScope(tx,a,d.employeeId??d.employee_id));}
 if(k==='business_calendar'){const scoped=this.scope(a,'chat.manage');return !external&&(p.includes('company.manage')||scoped.permissions.includes('chat.manage'))&&(scoped.permissions.includes('scope.company')||Array.isArray(d.siteIds)&&d.siteIds.length>0&&d.siteIds.every((siteId:string)=>scoped.siteIds.includes(siteId)));}
 if(k==='material_request_batch'){const scoped=this.scope(a,'inventory.read');return !external&&scoped.permissions.includes('inventory.read')&&Array.isArray(d.siteIds)&&d.siteIds.length>0&&(scoped.permissions.includes('scope.company')||d.siteIds.every((siteId:string)=>scoped.siteIds.includes(siteId)));}
 if(inventoryKinds.has(k)){const inventoryActor=this.scope(a,'inventory.read');if(external||!inventoryActor.permissions.includes('inventory.read'))return false;if(k==='material'||k==='material_batch')return true;const refs=k==='stock_location'?[e.id]:[d.locationId,d.fromLocationId,d.toLocationId,d.sourceLocationId,d.destinationLocationId,d.sourceId,d.targetId,d.stockLocationId].filter(Boolean);if(refs.length){for(const ref of refs)if(!await this.stockScope(tx,inventoryActor,ref))return false;return allowed('inventory.read');}return own||(!!sid&&allowed('inventory.read'))||inventoryActor.permissions.includes('scope.company');}
 if(procurementKinds.has(k))return !external&&p.some(x=>x.startsWith('procurement.')&&allowed(x));
 if(k==='crew_assignment')return this.crewManagementAllowed(a,e)||!!await this.ownCrewEmployee(tx,a,e);
 if(commerceKinds.has(k)){if(k==='service')return d.active===true||p.includes('commerce.manage');if(external){if(k==='customer')return await this.customerAccess(tx,a,e.id);if(k==='lead')return own;if(k==='quote_version'){
  try{
   const parent=await tx.get('quote',d.quoteId),publication=parent.data.portalPublication;
   if(e.companyId!==a.companyId||parent.companyId!==a.companyId||tx.companyId!==a.companyId||!quotePublishedForCustomer(parent)||!publication||d.immutable!==true||!Number.isInteger(d.quoteVersion)||d.quoteVersion!==publication.quoteVersion||d.quoteVersion!==parent.data.quoteVersion||d.publishedAt!==publication.publishedAt||!['SENT','ACCEPTED','REJECTED','EXPIRED','SUPERSEDED'].includes(d.status))return false;
   const lead=await tx.get('lead',parent.data.leadId);if(lead.companyId!==a.companyId)return false;
   const orderId=parent.data.orderId??lead.data.orderId,order=orderId?await tx.get('order',orderId):undefined;
   if(order&&order.companyId!==a.companyId)return false;
   const customerId=parent.data.customerId??lead.data.customerId??order?.data.customerId,siteId=order?.data.siteId??parent.data.siteId??lead.data.siteId;
   if(order?.data.customerId&&customerId!==order.data.customerId)return false;
   return customerId?await this.customerAccess(tx,a,customerId,siteId):(lead.data.ownerUserId??lead.data.userId)===a.userId;
  }catch{return false;}
 }if(k==='quote'){
  try{
   if(e.companyId!==a.companyId||tx.companyId!==a.companyId||!quotePublishedForCustomer(e))return false;
   const lead=await tx.get('lead',d.leadId);if(lead.companyId!==a.companyId)return false;
   const orderId=d.orderId??lead.data.orderId,order=orderId?await tx.get('order',orderId):undefined;if(order&&order.companyId!==a.companyId)return false;
   const customerId=d.customerId??lead.data.customerId??order?.data.customerId,siteId=order?.data.siteId??d.siteId??lead.data.siteId;if(order?.data.customerId&&customerId!==order.data.customerId)return false;
   return customerId?await this.customerAccess(tx,a,customerId,siteId):(lead.data.ownerUserId??lead.data.userId)===a.userId;
  }catch{return false;}
 }return ['order','quote_acceptance','change_order'].includes(k)&&await this.customerAccess(tx,a,d.customerId,d.siteId);}return anyAllowed(['commerce.manage','commerce.read','dispatch.manage','customer.manage','customer.read','lead.manage']);}
 if(k==='order')return external?await this.customerAccess(tx,a,d.customerId,d.siteId):anyAllowed(['commerce.manage','dispatch.manage','site.read']);
 if(k==='report'||k==='report_version'){if(external)return (k==='report_version'?!!d.publishedAt&&d.immutable===true:d.state==='PUBLISHED')&&await this.customerAccess(tx,a,d.customerId??d.snapshot?.customerId,d.siteId??d.snapshot?.site?.id);return p.some(x=>x.startsWith('report.')&&allowed(x));}
 if(k==='issue'){if(d.state==='DRAFT'&&d.createdBy!==a.userId)return false;return p.includes('issue.read')&&(external?await this.customerAccess(tx,a,d.customerId,d.siteId):allowed('issue.read'));}
 if(k==='digest_policy'||k==='operations_digest')return operationsDigestVisible(tx,a,e,this);
 if(k==='media_client_edit')return clientRedactionVisible(tx,a,e,{store:createPrivateBlobStore(this.db),actorIn:(currentTx,userId)=>this.actorIn(currentTx,userId),scope:(fresh,requested)=>this.scope(fresh,requested),visible:(currentTx,fresh,source)=>this.visible(currentTx,fresh,source)});
 if(k==='media_asset'){if(d.visibility==='CONFIDENTIAL'||d.employeeId){return !external&&(d.employeeId===a.userId||(p.some(x=>['finance.accountant','finance.payroll'].includes(x))&&await this.employeeScope(tx,a,d.employeeId)));}if(external){if(d.uploadedBy===a.userId)return await this.customerSite(tx,a,d.siteId);if(d.state!=='APPROVED_FOR_CLIENT'||d.visibility!=='CLIENT_AFTER_APPROVAL'||!d.clientBlobKey)return false;return this.customerSite(tx,a,d.siteId);}return d.uploadedBy===a.userId||(!!sid&&allowed('media.read'));}
 if(k==='knowledge'){if(external)return d.visibility==='PUBLIC'&&d.status==='APPROVED';if(!p.includes('assistant.read')&&!p.includes('assistant.manage'))return false;if(d.visibility==='PERSONAL')return d.subjectUserId===a.userId;return all||!(d.siteIds??[]).length||d.siteIds.some((siteId:string)=>a.siteIds.includes(siteId));}
 if(k==='decision')return !external&&allowed('decision.manage')&&(!d.approvalDomain||d.approvalDomain!=='FINANCE'||p.includes('finance.payout.approve'));
 if(adminKinds.has(k))return !external&&p.some(x=>['bot.manage','assistant.manage','assistant.read','company.manage','location.policy.manage','automation.manage'].includes(x));
 return false;}
 async employeeScope(tx:PgTransaction,a:Actor,id?:string):Promise<boolean>{if(!id)return false;if(id===a.userId||a.permissions.includes('scope.company'))return true;try{const user=await tx.get('user',id);return (user.data.siteIds??[]).some((siteId:string)=>a.siteIds.includes(siteId));}catch{return false;}}
 async stockScope(tx:PgTransaction,a:Actor,id:string):Promise<boolean>{try{const loc=await tx.get('stock_location',id);if(a.permissions.includes('scope.company'))return true;if(loc.data.type==='WAREHOUSE')return a.warehouseIds.includes(id);if(loc.data.type==='EMPLOYEE')return loc.data.employeeId===a.userId;if(loc.data.siteId)return a.siteIds.includes(loc.data.siteId);return false;}catch{return false;}}
 async customerSite(tx:PgTransaction,a:Actor,id?:string):Promise<boolean>{if(!id)return false;try{const site=await tx.get('site',id);return this.customerAccess(tx,a,site.data.customerId,id);}catch{return false;}}
 async customerAccess(tx:PgTransaction,a:Actor,customerId:string,siteId?:string):Promise<boolean>{const memberships=await tx.list('customer_membership');const now=new Date().toISOString();return memberships.some(m=>m.data.active===true&&!m.data.revokedAt&&(m.data.permissions??[]).includes('VIEW')&&(m.data.userId??m.data.user_id)===a.userId&&m.data.customerId===customerId&&(!m.data.expiresAt||m.data.expiresAt>now)&&(!siteId||!(m.data.siteIds??[]).length||m.data.siteIds.includes(siteId)));}
 async project(tx:PgTransaction,a:Actor,e:Entity):Promise<Entity>{if(e.kind==='employee'&&!a.roles.some(r=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(r))&&!a.permissions.includes('identity.manage')){assert(await this.visible(tx,a,e),'NOT_FOUND_SAFE');const data:Data={};for(const key of ['name','businessCode','employeeCode','skills','active','userId','user_id','availabilityWindows','availabilityValidUntil','travelBufferMinutes'])if(e.data[key]!==undefined)data[key]=e.data[key];return {...e,data};}if(e.kind==='crew_assignment'){assert(await this.visible(tx,a,e),'NOT_FOUND_SAFE');if(!this.crewManagementAllowed(a,e)){const employee=await this.ownCrewEmployee(tx,a,e);assert(employee,'NOT_FOUND_SAFE');const data:Data={employeeId:employee.id,acknowledged:(e.data.acknowledgedIds??[]).includes(employee.id)};for(const key of ['orderId','siteId','status','startAt','endAt','scheduleVersion','requireEmployeeAck'])if(e.data[key]!==undefined)data[key]=e.data[key];return {...e,data};}}if(e.kind==='material_request_batch'){assert(await this.visible(tx,a,e),'NOT_FOUND_SAFE');const scoped=this.scope(a,'inventory.read');return materialRequestBatchView(this.context(tx,scoped,'batch-read-projection',undefined,new Date().toISOString(),[],'inventory.read'),e);}if(e.kind==='presence'){const last=Date.parse(e.data.lastUsableObservedAt??'');if(!Number.isFinite(last)||Date.now()-last>=300000)e={...e,data:{...e.data,state:'UNKNOWN',stale:true,staleReason:'NO_USABLE_POINT_300_SECONDS'}};}if(['integration_config','integration_event','integration_quarantine','integration_record','integration_decision','integration_outbound'].includes(e.kind)){const data:Data={};for(const key of ['source','eventId','event_id','externalId','status','reason','receivedAt','createdAt','resolvedAt','approvedAt','approvedBy','payloadHash','hash','effectId','quarantineId','duplicate','attempts','outcome','active','direction','mappingVersion','previewHash','activatedAt','pausedAt'])if(e.data[key]!==undefined)data[key]=e.data[key];return {...e,data};}const external=a.roles.some(r=>['CLIENT','CUSTOMER','EXTERNAL_BAULEITER','GUEST'].includes(r));if(e.kind==='user'&&e.id!==a.userId)return {...e,data:{name:e.data.name,roles:e.data.roles,siteIds:e.data.siteIds,active:e.data.active,businessCode:e.data.businessCode}};if(external){if(e.kind==='quote_version'){
  assert(await this.visible(tx,a,e),'NOT_FOUND_SAFE');const parent=await tx.get('quote',e.data.quoteId),publication=parent.data.portalPublication;
  return {...e,data:{...quoteCustomerProjection(parent),id:e.id,version:e.version,quoteId:parent.id,quoteVersion:publication.quoteVersion,immutable:true,publishedAt:publication.publishedAt}};
 }if(e.kind==='quote'){assert(await this.visible(tx,a,e),'NOT_FOUND_SAFE');return {...e,data:quoteCustomerProjection(e)};}if(e.kind==='issue')return publicIssueProjection(e);if(e.kind==='report_version')return {...e,data:{reportId:e.data.reportId,state:e.data.state,number:e.data.number,version:e.data.version,checksum:e.data.checksum,sha256:e.data.sha256,publishedAt:e.data.publishedAt,immutable:e.data.immutable,snapshot:e.data.snapshot}};const d={...e.data};for(const key of ['blobKey','sha256','uploadedBy','employeeId','duplicateOf','inputSnapshot','internalCost','costCents','margin','employeeIds','payroll','salary','route','gps','bank','notesInternal'])delete d[key];return {...e,data:d};}return e;}
}
