import { writeXlsxWorkbook, type XlsxCell, type XlsxSheet } from '../../packages/storage/xlsx.ts';
import { createHash } from 'node:crypto';
import PDFDocument from 'pdfkit';
import { assert, Data, Entity, type Transaction } from '../../packages/domain/core.ts';
import type { BlobReceipt, BlobSql, PrivateBlobStore } from '../../packages/storage/index.ts';
import { formatReportHours } from '../../packages/domain/resources.ts';
import { reportExportSnapshot } from '../../packages/domain/report-export.ts';
export { reportExportSnapshot } from '../../packages/domain/report-export.ts';
import { reportFont } from '../../packages/storage/fonts/dejavu.ts';

export interface ReportMedia {id:string;bytes:Buffer;mimeType:'image/jpeg'|'image/png'|'image/webp';}
export interface ExportOptions {media?:ReportMedia[];}
export type ReportArtifactFormat='PDF'|'XLSX'|'CSV';
export interface ArchivedReportArtifact {artifact:Entity;bytes:Buffer;createdBlob?:BlobReceipt;}

function exactDecimal(value:number,denominator:number,digits:number){assert(Number.isSafeInteger(value)&&Number.isSafeInteger(denominator)&&denominator>0,'INVALID_STATE');const n=BigInt(value),absolute=n<0n?-n:n;return `${n<0n?'-':''}${absolute/BigInt(denominator)}${digits?'.'+String(absolute%BigInt(denominator)).padStart(digits,'0'):''}`;}
export const reportMoney=(value:number)=>`${exactDecimal(value,100,2).replace('.',',')} EUR`;
const text=(value:any)=>typeof value==='string'?value:JSON.stringify(value??'');
export function reportExportRows(version:Entity):(string|number)[][] {const s=reportExportSnapshot(version);const rows:(string|number)[][]=[['Abschnitt','Feld','Wert','Einheit'],['Bericht','Nummer',s.number||version.id,''],['Bericht','Version',version.data.version,''],['Bericht','Quell-SHA256',version.data.sha256,''],['Bericht','Vorherige Version',version.data.previousVersionId||'',''],['Bericht','Ausgestellt am',version.data.publishedAt,'UTC'],['Firma','Name',text(s.company.legalName),''],['Firma','Anschrift',text(s.company.address),''],['Kunde','Name',text(s.customer.name),''],['Kunde','Anschrift',text(s.customer.address),''],['Objekt','Code',s.site.code||s.site.id,''],['Objekt','Name',text(s.site.name),''],['Objekt','Anschrift',text(s.site.address),''],['Zeitraum','Von',s.periodStart,'UTC'],['Zeitraum','Bis',s.periodEnd,'UTC'],['Leistung','Beschreibung',s.descriptionDe,''],['Stunden','Gesamt (exakt)',s.totalSeconds,'Sekunden'],['Stunden','Gesamt (Anzeige)',formatReportHours(s.totalSeconds),'Stunden'],['Preis','Ursprünglich vereinbart',s.baseNetCents,'EUR Cent'],['Preis','Genehmigte Nachträge',s.approvedChangesNetCents,'EUR Cent'],['Preis','Netto',s.totalNetCents,'EUR Cent'],['Preis','Steuer',s.totalTaxCents,'EUR Cent'],['Preis','Gesamt',s.totalGrossCents,'EUR Cent'],['Preis','Status',s.priceStatus,''],['Hinweis','Rechtliche Erklärung',s.legalNotice,'']];
  for(const task of s.taskRows||[]){rows.push(['Aufgabe','ID',task.taskId,''],['Aufgabe','Beschreibung',task.descriptionDe||task.title||'',''],['Aufgabe','Menge (exakt)',task.quantityMilli,`${task.unit} / 1000`],['Aufgabe','Menge (Anzeige)',exactDecimal(task.quantityMilli,1000,3),task.unit],['Aufgabe','Status',task.state,'']);}
  for(const hours of s.hoursRows||[])rows.push(['Stunden',hours.workerCode,hours.seconds,'Sekunden'],['Stunden',hours.workerCode,formatReportHours(hours.seconds),'Stunden']);
  for(const material of s.materialRows||[])rows.push(['Material',material.sku||material.name,material.quantityBase,material.unit],['Material','Bezeichnung',material.name,''],['Material','Aufgabe',material.taskId||'',''],['Material','Gesondert berechnet',material.chargedSeparately?'Ja':'Nein','']);
  for(const media of s.mediaRows||[])rows.push(['Foto',media.mediaId,media.caption||media.stage||'',''],['Foto','Hochgeladen am',media.uploadedAt||'','UTC']);return rows;
}
function csvCell(value:unknown){let content=String(value??'');if(typeof value==='string'&&/^\s*[=+@-]/.test(content))content=`'${content}`;return `"${content.replaceAll('"','""')}"`;}
export function renderReportCsv(version:Entity){return '\uFEFF'+reportExportRows(version).map(row=>row.map(csvCell).join(';')).join('\r\n')+'\r\n';}
function checkedMedia(version:Entity,options:ExportOptions){const approved=new Set((version.data.snapshot.mediaRows||[]).map((row:Data)=>row.mediaId));const seen=new Set<string>();let embeddedBytes=0;for(const m of options.media||[]){assert(approved.has(m.id)&&!seen.has(m.id)&&m.bytes.length<=25*1024*1024,'INVALID_STATE',{reason:'APPROVED_REPORT_MEDIA_REQUIRED'});const approvedPhoto=version.data.snapshot.mediaRows.find((row:Data)=>row.mediaId===m.id);assert(approvedPhoto.sha256===createHash('sha256').update(m.bytes).digest('hex')&&(!approvedPhoto.mimeType||approvedPhoto.mimeType===m.mimeType),'INVALID_STATE',{reason:'REPORT_PHOTO_CHECKSUM_MISMATCH'});seen.add(m.id);embeddedBytes+=m.bytes.length;assert(seen.size<=40&&embeddedBytes<=20*1024*1024,'VALIDATION_ERROR',{reason:'DOCUMENT_EMBED_LIMIT'});}return options.media||[];}
export async function exportReportXlsx(version:Entity,options:ExportOptions={}):Promise<Buffer> {
 const s=reportExportSnapshot(version),sheets:XlsxSheet[]=[{name:'Bericht',rows:reportExportRows(version),columnWidths:[20,32,70,20],header:true}],photos=checkedMedia(version,options);
 if(photos.length){const rows:XlsxCell[][]=[['Foto-ID','Freigegebener Kontext']],images:NonNullable<XlsxSheet['images']>=[];for(let i=0;i<photos.length;i++){const photo=photos[i],row=s.mediaRows.find((r:Data)=>r.mediaId===photo.id);while(rows.length<i*14+2)rows.push([]);rows[i*14+1]=[photo.id,row.caption||row.stage];if(photo.mimeType==='image/jpeg'||photo.mimeType==='image/png')images.push({bytes:photo.bytes,mimeType:photo.mimeType,row:i*14+3,column:2,widthPx:420,heightPx:220});else rows[i*14+2]=['WebP','Freigegebene Datei ist im Kundenportal verfügbar.'];}sheets.push({name:'Fotodokumentation',rows,columnWidths:[45,70],header:true,images});}
 return writeXlsxWorkbook({creator:s.company.legalName,createdAt:version.data.publishedAt,title:`KNABA DE ${s.documentType} ${s.number||''}`,subject:`Unveränderliche Berichtsversion ${version.data.version}`,description:`Quell-SHA256: ${version.data.sha256}`,sheets});
}
export async function renderReportPdf(version:Entity,options:ExportOptions={}):Promise<Buffer> {const s=reportExportSnapshot(version),photos=checkedMedia(version,options);const doc=new PDFDocument({size:'A4',margin:45,info:{Title:`KNABA DE ${s.documentType}`,Author:s.company.legalName,Subject:`Unveränderliche Berichtsversion ${version.data.version}`,Keywords:`Quell-SHA256: ${version.data.sha256}`,CreationDate:new Date(version.data.publishedAt),ModDate:new Date(version.data.publishedAt)}});const chunks:Buffer[]=[];const finished=new Promise<Buffer>((resolve,reject)=>{doc.on('data',chunk=>chunks.push(chunk));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);});doc.registerFont('KNABA',reportFont);doc.font('KNABA').fontSize(18).text(`KNABA DE · ${s.documentType}`).fontSize(10).text(s.company.legalName).text(text(s.company.address)).moveDown().text(`Kunde: ${s.customer.name}`).text(`Objekt: ${s.site.code||s.site.id} · ${s.site.name}`).text(text(s.site.address)).text(`Zeitraum: ${s.periodStart} — ${s.periodEnd}`).text(`Bericht ${s.number||version.id} · Version ${version.data.version}`).moveDown().text(s.descriptionDe).moveDown();
 for(const task of s.taskRows||[])doc.text(`${task.descriptionDe||task.title||''} · ${exactDecimal(task.quantityMilli,1000,3)} ${task.unit} · ${task.state}`);doc.moveDown();for(const row of s.hoursRows||[])doc.text(`${row.workerCode}: ${formatReportHours(row.seconds)} Stunden (${row.seconds} Sekunden)`);doc.text(`Vertragliche Stunden gesamt: ${formatReportHours(s.totalSeconds)}`).moveDown().text(`Ursprünglich vereinbart: ${reportMoney(s.baseNetCents)}`).text(`Genehmigte Nachträge: ${reportMoney(s.approvedChangesNetCents)}`).text(`Netto: ${reportMoney(s.totalNetCents)}`).text(`Steuer: ${reportMoney(s.totalTaxCents)}`).text(`Gesamt: ${reportMoney(s.totalGrossCents)} · ${s.priceStatus}`).moveDown();for(const material of s.materialRows||[])doc.text(`${material.name}: ${material.quantityBase} ${material.unit} · gesondert berechnet: ${material.chargedSeparately?'Ja':'Nein'}`);
 for(const photo of photos){const row=s.mediaRows.find((r:Data)=>r.mediaId===photo.id);doc.addPage().fontSize(12).text(`Fotodokumentation · ${row.caption||row.stage}`).fontSize(8).text(`Foto-ID: ${photo.id}`).moveDown();if(photo.mimeType==='image/jpeg'||photo.mimeType==='image/png')doc.image(photo.bytes,{fit:[500,610],align:'center'});else doc.text('Freigegebene WebP-Datei ist im Kundenportal verfügbar.');}
 doc.moveDown().fontSize(8).text(s.legalNotice).text(`Quell-SHA256: ${version.data.sha256}`);doc.end();return finished;
}

// Caller authorizes the published version and executes this in its company-serialized DB transaction.
// The callback lets the outer transaction track newly created S3 objects for known-rollback cleanup.
export async function archiveReportArtifact(input:{tx:Transaction&Partial<BlobSql>;store:PrivateBlobStore;version:Entity;format:ReportArtifactFormat;ownerId:string;now:string;onCreatedBlob?:(receipt:BlobReceipt)=>void;}):Promise<ArchivedReportArtifact> {
 const {tx,store,version,format,ownerId,now}=input;
 const snapshot=reportExportSnapshot(version);assert(['PDF','XLSX','CSV'].includes(format)&&ownerId,'VALIDATION_ERROR');
 const existing=(await tx.list('report_artifact')).find(a=>a.data.reportVersionId===version.id&&a.data.format===format);
 if(existing){assert(existing.companyId===version.companyId&&existing.data.immutable===true&&existing.data.sourceSha256===version.data.sha256,'INVALID_STATE',{reason:'REPORT_ARTIFACT_SOURCE_MISMATCH'});const stored=await store.get(version.companyId,existing.data.blobKey);assert(stored.sha256===existing.data.sha256&&stored.bytes.length===existing.data.byteSize&&stored.mimeType===existing.data.mimeType,'INVALID_STATE',{reason:'REPORT_ARTIFACT_CHECKSUM_MISMATCH'});return {artifact:existing,bytes:stored.bytes};}
 const media:ReportMedia[]=[];if(format!=='CSV'){assert((snapshot.mediaRows||[]).length<=40,'VALIDATION_ERROR',{reason:'DOCUMENT_EMBED_LIMIT'});let totalBytes=0;for(const row of snapshot.mediaRows||[]){assert(row.clientBlobKey&&['image/jpeg','image/png','image/webp'].includes(row.mimeType),'INVALID_STATE',{reason:'APPROVED_REPORT_MEDIA_REQUIRED'});const blob=await store.get(version.companyId,row.clientBlobKey);assert(blob.sha256===row.sha256&&blob.mimeType===row.mimeType&&(!row.byteSize||blob.bytes.length===row.byteSize),'INVALID_STATE',{reason:'REPORT_PHOTO_CHECKSUM_MISMATCH'});totalBytes+=blob.bytes.length;assert(totalBytes<=20*1024*1024,'VALIDATION_ERROR',{reason:'DOCUMENT_EMBED_LIMIT'});media.push({id:row.mediaId,bytes:blob.bytes,mimeType:blob.mimeType as ReportMedia['mimeType']});}}
 const bytes=format==='PDF'?await renderReportPdf(version,{media}):format==='XLSX'?await exportReportXlsx(version,{media}):Buffer.from(renderReportCsv(version),'utf8');
 const mimeType=format==='PDF'?'application/pdf':format==='XLSX'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv; charset=utf-8';
 const blobKey=`report_${createHash('sha256').update(`${version.companyId}\0${version.id}\0${format}`).digest('hex')}`;
 assert(store.provider!=='POSTGRES'||typeof tx.query==='function','MISSING_CONFIGURATION',{reason:'STORAGE_TRANSACTION_REQUIRED'});
 const createdBlob=await store.put({id:blobKey,companyId:version.companyId,ownerId:`report_version:${version.id}`,bytes,mimeType},typeof tx.query==='function'?tx as BlobSql:undefined);if(createdBlob.created&&createdBlob.provider==='S3')input.onCreatedBlob?.(createdBlob);
 const artifact=await tx.add('report_artifact',{reportVersionId:version.id,reportId:version.data.reportId,siteId:version.data.siteId,customerId:version.data.customerId,format,blobKey,sha256:createdBlob.sha256,sourceSha256:version.data.sha256,byteSize:bytes.length,mimeType,provider:store.provider,templateVersion:version.data.templateVersion,renderedAt:now,createdBy:ownerId,immutable:true},blobKey);
 await tx.event('report.artifact_archived',{reportVersionId:version.id,artifactId:artifact.id,format,sha256:artifact.data.sha256,sourceSha256:version.data.sha256});
 return {artifact,bytes,createdBlob};
}
