import {z} from 'zod';
import {assert,DomainError,id,timestamp,type Actor,type CommandContext,type CommandRegistry,type Entity,type Data} from '../../packages/domain/core.js';
import {whatsAppPolicy} from '../../packages/domain/communications.js';
import {authorizeDigestPolicy,buildOperationsDigest,digestOwner,digestPolicyInput,digestPolicySchema,digestScopeAllowed,latestDigestSlot,operationsDigestHash,operationsDigestVisible,policyDue,type DigestTransaction,type OperationsDigestHost} from '../../packages/domain/operations-digest.js';

export function createOperationsDigestCommands<T extends DigestTransaction>(host:OperationsDigestHost<T>):CommandRegistry {
 const fresh=async(c:CommandContext)=>{const tx=c.tx as T;assert(tx.companyId===c.actor.companyId,'ACCESS_DENIED');return {tx,owner:await digestOwner(tx,c.actor.userId,host)};};
 const policy=async(c:CommandContext,policyId:string)=>{const {tx,owner}=await fresh(c),record=await tx.get('digest_policy',policyId);await authorizeDigestPolicy(tx,owner,record,host);return {tx,owner,record};};
 const transport=async(tx:T,owner:Actor,record:Entity,now:string)=>{
  const input=digestPolicyInput(record);if(input.channel!=='WHATSAPP')return;
  for(const permission of ['chat.read','chat.write'])assert(await digestScopeAllowed(tx,owner,input.scope,permission,host),'ACCESS_DENIED');
  const channel=await tx.get('channel',input.channelId!);assert(channel.companyId===tx.companyId&&channel.data.type==='DIRECT'&&await host.visible(tx,host.scope(owner,'chat.read'),channel),'ACCESS_DENIED');await host.project(tx,host.scope(owner,'chat.read'),channel);
  const members=(channel.data.members??[]).filter((m:Data)=>m.active!==false&&!m.revoked_at&&!m.revokedAt&&!m.left_at&&!m.leftAt&&!m.removed_at&&!m.removedAt&&(!m.expires_at&&!m.expiresAt||Date.parse(m.expires_at??m.expiresAt)>Date.parse(now)));
  assert(members.some((m:Data)=>m.user_id===owner.userId)&&members.length<=2,'ACCESS_DENIED',{reason:'DIGEST_PRIVATE_OWNER_CHANNEL_REQUIRED'});
  for(const member of members){assert(member.external!==true,'ACCESS_DENIED');if(member.user_id!==owner.userId){const user=await tx.get('user',member.user_id);assert(user.companyId===tx.companyId&&user.data.active===true&&user.data.roles?.includes('SERVICE_ACCOUNT'),'ACCESS_DENIED',{reason:'DIGEST_PRIVATE_OWNER_CHANNEL_REQUIRED'});}}
  const setting=(await tx.list('notification_setting')).find(row=>row.data.user_id===owner.userId),allowed=whatsAppPolicy({now,last_inbound_at:setting?.data.last_inbound_at,consent:setting?.data.whatsapp_consent===true,opted_out:setting?.data.opted_out,approved_template:input.template,template_status:input.templateStatus});assert(allowed.allowed,'NEEDS_APPROVAL',{reason:allowed.reason});
  const origin=process.env.PUBLIC_ORIGIN;let url:URL|undefined;try{if(origin)url=new URL(origin);}catch{}assert(url?.protocol==='https:'&&!url.username&&!url.password,'NEEDS_APPROVAL',{reason:'DIGEST_PUBLIC_ORIGIN_REQUIRED'});
 };
 return {
  'digest.configure':{permission:'notifications.manage',highRisk:true,schema:digestPolicySchema,handler:async(c,input)=>{const {tx,owner}=await fresh(c);assert(input.ownerId===owner.userId,'ACCESS_DENIED');const {id:policyId,...fields}=input,data={...fields,activeFrom:input.activeFrom??c.now,configuredAt:c.now,createdBy:owner.userId};let previous:Entity|undefined;if(policyId){previous=await tx.get('digest_policy',policyId);await authorizeDigestPolicy(tx,owner,previous,host);assert(c.expectedVersion===undefined||c.expectedVersion===previous.version,'VERSION_CONFLICT');}const candidate:Entity={id:policyId??'digest-policy-candidate',kind:'digest_policy',companyId:tx.companyId,version:previous?.version??1,createdAt:previous?.createdAt??c.now,updatedAt:c.now,data};await authorizeDigestPolicy(tx,owner,candidate,host);await transport(tx,owner,candidate,c.now);return previous?tx.save(previous,{...data,policyVersion:previous.version+1},c.expectedVersion??previous.version):tx.add('digest_policy',{...data,policyVersion:1});}},
  'digest.preview':{permission:'notifications.manage',schema:z.object({policyId:id,at:timestamp.optional()}).strict(),handler:async(c,input)=>{const {tx,owner,record}=await policy(c,input.policyId),at=new Date(input.at??latestDigestSlot(record,new Date(c.now))?.slotAt??c.now);assert(at.getTime()<=Date.parse(c.now)&&at.getTime()>=Date.parse(c.now)-370*86400000,'VALIDATION_ERROR',{reason:'DIGEST_PREVIEW_PERIOD_BOUND'});return {...await buildOperationsDigest(tx,record,owner,at,host,new Date(c.now)),scheduledSlot:policyDue(record,at)!==null};}},
  'digest.generate':{permission:'notifications.manage',schema:z.object({policyId:id,policyVersion:z.number().int().positive(),slotAt:timestamp.optional()}).strict(),handler:async(c,input)=>{
   const {tx,owner,record}=await policy(c,input.policyId);assert(record.version===input.policyVersion&&(c.expectedVersion===undefined||c.expectedVersion===record.version),'VERSION_CONFLICT');const selected=input.slotAt??latestDigestSlot(record,new Date(c.now))?.slotAt;assert(selected,'NOT_DUE');const at=new Date(selected);assert(at.getTime()<=Date.parse(c.now)&&at.getTime()>=Date.parse(c.now)-8*86400000,'VALIDATION_ERROR',{reason:'DIGEST_SLOT_BOUND'});assert(record.data.enabled&&Date.parse(record.data.activeFrom)<=at.getTime(),'NOT_DUE');const slot=policyDue(record,at);assert(slot,'NOT_DUE');const dedupKey=operationsDigestHash({companyId:tx.companyId,policyId:record.id,kind:record.data.kind,slotKey:slot.slotKey}),digestId=`digest-${dedupKey}`;
   let prior:Entity|undefined;try{prior=await tx.get('operations_digest',digestId);}catch(error){if(!(error instanceof DomainError&&error.code==='NOT_FOUND_SAFE'))throw error;}if(prior){assert(await operationsDigestVisible(tx,owner,prior,host),'ACCESS_DENIED');return prior;}
   await transport(tx,owner,record,c.now);const snapshot=await buildOperationsDigest(tx,record,owner,at,host,new Date(c.now));const digest=await tx.add('operations_digest',{policyId:record.id,policyVersion:record.version,ownerId:owner.userId,recipientId:owner.userId,kind:record.data.kind,scope:record.data.scope,slotKey:slot.slotKey,snapshot,sha256:operationsDigestHash(snapshot),immutable:true,createdBy:owner.userId,generatedAt:c.now,deliveryStatus:'QUEUED'},digestId);
   let messageId:string|undefined;if(record.data.channel==='WHATSAPP'){const sender=host.registry['message.send'];assert(sender&&owner.permissions.includes(sender.permission),'ACCESS_DENIED');const origin=new URL(process.env.PUBLIC_ORIGIN!),url=new URL('/console?digest='+encodeURIComponent(digest.id),origin);const settings=(await tx.list('notification_setting')).find(row=>row.data.user_id===owner.userId);const language=['DE','UK','RU','PL','LT','EN'].includes(settings?.data.language)?settings!.data.language:'DE';const labels:Record<string,string>={DE:'Ihr geschützter KNABA-Betriebsüberblick ist verfügbar.',UK:'Ваш захищений операційний огляд KNABA готовий.',RU:'Ваш защищённый операционный обзор KNABA готов.',PL:'Twój chroniony przegląd operacyjny KNABA jest gotowy.',LT:'Jūsų apsaugota KNABA veiklos apžvalga parengta.',EN:'Your protected KNABA operations digest is ready.'};const message=await sender.handler({...c,actor:host.scope(owner,sender.permission),expectedVersion:undefined},sender.schema.parse({channel_id:record.data.channelId,text:labels[language]+'\n'+url.href,language,source:'HUMAN'}));messageId=message.id;}
   const scheduler=host.registry['notifications.schedule'];assert(scheduler&&owner.permissions.includes(scheduler.permission),'ACCESS_DENIED');await scheduler.handler({...c,actor:host.scope(owner,scheduler.permission),expectedVersion:undefined},scheduler.schema.parse({recipient_id:owner.userId,event:'OPERATIONS_DIGEST_READY',category:'WORK',scheduled_at:c.now,dedup_key:`operations-digest:${dedupKey}`,channel:record.data.channel,related_kind:'operations_digest',related_id:digest.id,...(messageId?{message_id:messageId}:{}),...(record.data.template?{template:record.data.template,template_status:record.data.templateStatus}:{}),max_attempts:3}));return digest;
  }},
 };
}
